### ISSUE TITLE
fix documentation for Popup.PlacementMode

### ISSUE THREAD

**Issue by trebahl** [dotnet/wpf#10010]
### Description

I have seen a couple of closed issues on this question, but they don't address fixing the documentation.

Left and right are swapped based on SystemParameters.MenuDropAlignment (including in modes Top and Bottom). 

````
            bool dropFromRight = SystemParameters.MenuDropAlignment;

            switch (placement)
            {
                case PlacementMode.Bottom:
                case PlacementMode.Mouse:
                    axis = PopupPrimaryAxis.Horizontal;
                    if (dropFromRight)
                    {
                        if (i == 0) return new PointCombination(InterestPoint.BottomRight, InterestPoint.TopRight);
                        if (i == 1) return new PointCombination(InterestPoint.TopRight, InterestPoint.BottomRight);
                    }
                    else
                    {
                        if (i == 0) return new PointCombination(InterestPoint.BottomLeft, InterestPoint.TopLeft);
                        if (i == 1) return new PointCombination(InterestPoint.TopLeft, InterestPoint.BottomLeft);
                    }
                    break;
````

This should be explained in the documentation.

### Reproduction Steps

Doesn't apply; I'm just begging for the documentation to match the implementation.

### Expected behavior

Documentation explaining that if SystemParameters.MenuDropAlignment is true, then left and right are swapped.

### Actual behavior

Documentation says that left is left and right is right.

### Impact

Programmers will waste time searching through the source code of wpf to understand the behaviour they see on screen.

**Comment by miloush** [comment]
Have you tried "Open a documentation issue" at the bottom of https://learn.microsoft.com/en-us/dotnet/api/system.windows.systemparameters.menudropalignment (or wherever you think this should be placed)?
