### ISSUE TITLE
Fluent theme not working on Windows 10

### ISSUE THREAD

**Issue by LoriBru** [dotnet/wpf#10096]
### Description

Hello, I am currently working on a small WPF app and I decided to give .NET9 and the new Fluent theme a go.
I am currently working in parallel on two machines, one is Windows 10 and one is Windows 11.
While everything looks fine on Windows 11, on Windows 10 the Fluent theme does not work.
Is this expected? I cannot find any reference in the documentation regarding the expected behavior of this new Theme on Windows 10. I understood that this theme would be applied also to Windows 10.
Both machines are working with Visual Studio 17.12 and .NET 9 installed.

On Windows 11:
![Image](https://github.com/user-attachments/assets/fc01090b-6f2e-4371-babc-62ad1e389e31)

On Windows 10:
![Image](https://github.com/user-attachments/assets/21a1d259-dc3d-427e-96fc-725f85acf853)
![Image](https://github.com/user-attachments/assets/43439477-b18a-429e-ba8d-e495d6b05a93)

Winodws 10 info:
![Image](https://github.com/user-attachments/assets/4dfdc065-2056-4486-82ac-61123a230a4c)

### Reproduction Steps

Create a minimal app with Fluent theme using .NET9 and start it on both Winodws 11 and Windows 10.

### Expected behavior

Fluent theme working on Windows 10.

### Actual behavior

Fluent theme not working on Windows 10.

**Comment by miloush** [comment]
I suspect https://github.com/dotnet/wpf/issues/9635#issuecomment-2472295895 will work as a workaround for you.

**Comment by harshit7962** [comment]
@LoriBru, thank you for giving the new themes a try. Yes, certain aspects of Fluent Theme on Windows 10 needs an additional switch to be added, as pointed by @miloush. We are working on getting this fixed in the framework itself. We will try to get this fix in the subsequent service release of .NET 9.

**Comment by LoriBru** [comment]
Thank you both @miloush and @harshit7962 !
I will give the suggestion a try, indeed it is at least disappointing that the main new feature introduced with .NET9 on WPF requires a workaround right out of the box to work as expected on Windows 10.

**Comment by miloush** [comment]
@LoriBru Please note that the Win11 theming is experimental.

**Comment by LoriBru** [comment]
@miloush by reading [this ](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/whats-new/net90?view=netdesktop-9.0) I understand that setting the Theme from code is experimental, not the whole Fluent theme, which is advertised as the main addition coming with .NET9.

**Comment by MichaeIDietrich** [comment]
It seems that's not the first one who is confused that the whole Fluent theme is experimental in .NET 9: https://github.com/dotnet/wpf/discussions/10072
And I fully agree that linked document is really unclear about the fact that the whole Fluent theme is meant to be experimental.

**Comment by harshit7962** [comment]
@LoriBru, we have backported the fix to .NET 9 and it should be available with .NET SDK 9.0.2, tentatively by mid January.
Meanwhile, you can give it a try on the release/9.0 branch.

**Comment by LoriBru** [comment]
Thanks! @harshit7962 looking forward to testing it in January!
