### ISSUE TITLE
Fluent Theme: `MessageBox` does not have fluent styling

### ISSUE THREAD

**Issue by bent-rasmussen** [dotnet/wpf#10147]
### Description

Of course we can create our own MessageBox window but this is a hole in the fluent styling update:

![Image](https://github.com/user-attachments/assets/74b89f91-126b-4902-8776-07e907875a50)

### Reproduction Steps

1. Create a WPF app targeting .NET 9 with the fluent theme resource dictionary in App.xaml
2. Open a MessageBox in the MainWindow.xaml.cs

### Expected behavior

At a mimum, the MessageBox should follow the OS theme (light or dark) and ideally it should of course follow Fluent 2 with buttons, margins, etc.

### Actual behavior

Old styling, no dark mode support.

### Regression?

No, this is just a hole in the rollout of Fluent 2 support in .NET 9.

### Known Workarounds

🤖 "I'll build my own MessageBox, with..."

### Impact

Applications have a subpar and inconsistent visual appearance.

**Comment by miloush** [comment]
This is a system dialog provided by OS. If you want it to have dark theme, you need to file a feedback to Windows.

**Comment by bent-rasmussen** [comment]
Fair point. I will close the issue.
