### ISSUE TITLE
Expander control is not narrated

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#1015]
Copied from ADO ID: 850630

**Repro Steps:**
Run the attached sample program with Narrator running and focus on the Expander button. (For example, focus a ListItem and use the arrow keys to move focus to the Expander header.)

[WpfApp1.zip](https://github.com/dotnet/wpf/files/3307148/WpfApp1.zip)

**Actual Result:**
Narrator focus does not move to the Expander and it is not read.

**Expected Result:**
Narrator focus should move to the Expander and it should read its label.

**User Impact:​**
Users with visual disabilities will get confused while working with the application if screen reader is not reading information about control​ and its statuses

**Comment by arpitmathur** [comment]
MAS rule we're not compliant with is MAS 1.3.1 – Info and Relationships

**Comment by arpitmathur** [comment]
Fixed in #1278
