### ISSUE TITLE
Duplicate tabs added in SmartTag

### ISSUE THREAD

**Issue by sudharsan-narayanan** [dotnet/wpf#10163]
### Description

Once we created a new project in NetCore or Framework and install with NuGet package. Now, add a control in designer view page. The control shows the smart tag properly without any issue. Once we upgrade or downgrade the NuGet package in the project. And If I try to change the property value though smart tag. Once open the designer page, the smart tag adds duplicate tabs as shown below,

Once we create a new project in .NET Core or .NET Framework and install it with a NuGet package, we add a control in the designer view page. The control shows the smart tag properly without any issues. However, once we upgrade or downgrade the NuGet package in the project, and if I try to change the property value through the smart tag, once open the designer page, the smart tag adds duplicate tabs as shown below.

![Image](https://github.com/user-attachments/assets/0a20be32-83fb-4947-814a-545e97d8f81d)

If the project is cleaned by removing the **Bin and Obj** and we try to access the designer view page. The control properly shows the smart tag without any duplicate tabs.

![Image](https://github.com/user-attachments/assets/1593ba3a-ed4a-49a0-a5ff-2da49997716c)

**Note:** If the issue occurs only when we use the NuGet package.

Please find the sample below,

[Smartag.zip](https://github.com/user-attachments/files/18095531/Smartag.zip)
 

### Reproduction Steps

1. Run the Sample.
2. Ensure the designer issue occur or not.
3. If not occur, please upgrade or downgrade the NuGet package.
4. Now build the solution.
5. Note: the designer issue occurs as shown in the image.

![Image](https://github.com/user-attachments/assets/0a20be32-83fb-4947-814a-545e97d8f81d)

### Expected behavior

Duplicate tabs not shown when we upgrade or downgrade the NuGet.

### Actual behavior

Duplicate tabs are shown when we upgrade or downgrade the NuGet.

### Known Workarounds

Remove Bin and Obj files, if the issue occurs again.

**Comment by himgoyalmicro** [comment]
@sudharsan-narayanan as @miloush suggested can you please the issue with VS and close the issue here.
