### ISSUE TITLE
TitleBar buttons are scaled very small at a resolution of 4K

### ISSUE THREAD

**Issue by Case-Closed-X** [dotnet/wpf#10184]
### Description

WPF Gallery Preview close button doesn’t have corners, the close button will be displayed as shown in the picture at a resolution of 3840 * 2160.

Another issue is that the minimize, maximize, and close buttons are scaled very small at a resolution of 3840 * 2160.

### Actual behavior

![Image](https://github.com/user-attachments/assets/bc36d8e0-26f3-4a93-961c-886ddd7d0869)

### Expected behavior

![Image](https://github.com/user-attachments/assets/d440c0ae-ccaf-4631-829b-bd734ecc1fbb)

### Reproduction Steps

Launch WPF Gallery Preview and change the system resolution to 3840 * 2160.

**Comment by himgoyalmicro** [comment]
@Case-Closed-X Can you please open this issue on [WPF-Samples](https://github.com/microsoft/WPF-Samples)?

**Comment by Case-Closed-X** [comment]
> [@Case-Closed-X](https://github.com/Case-Closed-X) Can you please open this issue on [WPF-Samples](https://github.com/microsoft/WPF-Samples)?

sure.

**Comment by Case-Closed-X** [comment]
> [@Case-Closed-X](https://github.com/Case-Closed-X) Can you please open this issue on [WPF-Samples](https://github.com/microsoft/WPF-Samples)?

By the way, even without using Win11 theme (.net 9), the TitleBar buttons are still scaled very small at a resolution of 3840 * 2160 (both Win10 and Win11 systems). Can this problem be solved?

WPF Small buttons:
![Image](https://github.com/user-attachments/assets/b400f431-93ec-4d35-9876-edf0b67cc933)

WinUI 3 Normal buttons:
![Image](https://github.com/user-attachments/assets/b992a5cb-76e2-449e-bde0-5f13d6b3dade)
