### ISSUE TITLE
Multiple culture issues with DataGrid, MenuItem

### ISSUE THREAD

**Issue by debugnik** [dotnet/wpf#1034]
* .NET Core Version: 3.0 preview 6
* Windows version: 10.0.17134
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

Exact same bug as in #913 but with multiple other UI cultures. Exact same repro, identical exception and stacktrace. The only difference is the `ArgumentException` message:

* es-ES (and all other es-\* locales I've tried): `Requested value 'REPÁG' was not found.`
* fr-FR and fr-CA: `Requested value 'PG. PRÉC' was not found.`
* it-IT: `Requested value 'PGSU' was not found.`

I didn't try more, so there's probably other localizations with the same issue. The only ones I tried that did not trigger are pt-PT and pt-BR.

Note the bug doesn't just trigger in DataGrid. For example, certain keyboard interactions over MenuItems also throw the same exception.

**Comment by weltkante** [comment]
#913 was fixed for all languages in #919 - you can use daily builds as described [here](https://github.com/dotnet/core/blob/master/daily-builds.md) or change your resource language to en-US (`CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");`) until preview 7 is released.

**Comment by debugnik** [comment]
Oh, I didn't notice #919 fixed it for other languages too, but so it seems looking at the changed files. Never mind then.
