### ISSUE TITLE
Support Control Library project templates

### ISSUE THREAD

**Issue by jmarolf** [dotnet/wpf#1036]
>*Moved from https://github.com/dotnet/project-system/issues/4715*

This is to bring us to experience parity with desktop for WPF on .NET Core 3.0.

This is available on desktop today:

<img width="362" alt="image" src="https://user-images.githubusercontent.com/6309070/55912698-0c3d2080-5b98-11e9-9863-03777a858dc6.png">

these should be available for .NET Core 3.0.

The project template should have the correct MSBuildisms (e.g., desktop sdk and `<UseWPF>true</UseWPF>` for WPF).

**Comment by grubioe** [comment]
@jmarolf for what VS release is this needed for?

**Comment by jmarolf** [comment]
16.3 ideally

**Comment by grubioe** [comment]
Thanks. We'll get this in for 16.3 Preview 2.   

cc: @vatsan-madhavan

**Comment by thomasclaudiushuber** [comment]
Note that .NET Framework has in addition this template:

![image](https://user-images.githubusercontent.com/7116546/61227710-1cc7de80-a725-11e9-9dae-8a6e2bb66fde.png)

I guess this is the one we don't want to have for .NET Core 3.0, as Browser apps are not supported. So we should have these three templates for .NET Core in VS 16.3:

- WPF App
- WPF Custom Control Library
- WPF User Control Library

**Comment by vatsan-madhavan** [comment]
@thomasclaudiushuber, that's correct. XBAP's are not supported (and beyond that - they are completely non-functional) in .NET Core.

**Comment by vatsan-madhavan** [comment]
Fixed by #1005
