### ISSUE TITLE
Textbox input is partly is broken in 3.0.100-preview7 

### ISSUE THREAD

**Issue by Symbai** [dotnet/wpf#1039]
* .NET Core Version: 3.0.100-preview7-012537 /  Commit:    8361cb8c23
* Windows version: 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**

Installed latest daily build today and noticed that moving the caret in textbox via the arrow keys is broken. Also removing text using the delete button doesn't work. Others keys working fine.

![ezgif com-crop](https://user-images.githubusercontent.com/14368203/59913160-2badc080-9407-11e9-9fe8-0c0416272974.gif)
 
 **Actual behavior:** 

- Arrow keys does nothing
- Delete key does nothing
- Home key does nothing
- End key does nothing
 
 **Minimal repro:**
```
 <Window x:Class="WpfApp3.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp3"
        mc:Ignorable="d"
        Title="MainWindow" Height="250" Width="400">
    <Grid>
        <TextBox HorizontalAlignment="Center" VerticalAlignment="Center" MinWidth="200" Text="aaaaaaaaaaa"/>
    </Grid>
</Window>
```

//edit: Added note about home and end key.

**Comment by ryalanms** [comment]
@Symbai: Could you try a recent nightly build?  

https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe

A number of fixes have gone in for keybindings and the scenario is working for me with yesterday's nightly build (3.0.0-preview7-27824-03).  Thanks.

**Comment by Symbai** [comment]
Works fine using the SDK you linked, thanks!

**Comment by yosaf055** [comment]
https://github.com/dotnet/wpf/issues/1039#issue-459105001
