### ISSUE TITLE
WPF Datagrid - Losing new row and getting set to read only after windows update

### ISSUE THREAD

**Issue by DanielPramik** [dotnet/wpf#1041]
* .NET Framework 4.7.2
* Windows version: (`10`)

 
 
 **Problem description:**
We use a WPF Datagrid that has a blank new row for users to begin entering data. After the user enters their first line item and it is validated, we move them to the next row so that they can enter another item immediately. If the user instead clicks back into the first row of the grid to edit a value, the empty new row is lost, and the grid is put into a read only mode. This has only started happening on Windows 10 Update 1903. Any other users not on this update do not experience this behavior.

Here are some screenshots showing the behavior.

1. User enters screen, datagrid is empty and shows a blank row for data entry:
![wpfGrid1](https://user-images.githubusercontent.com/52073354/59921695-81c93680-93fc-11e9-9884-a60b55124ce8.jpg)
2. User begins to enter data:
![wpfGrid2](https://user-images.githubusercontent.com/52073354/59921745-aae9c700-93fc-11e9-8f1c-6f792a810bec.jpg)
3. User finishes first line item, new row is created for the user to continue data entry:
![wpfGrid3](https://user-images.githubusercontent.com/52073354/59921808-e2587380-93fc-11e9-8977-f72493182f40.jpg)
4. User clicks back into the first row to edit one of the fields, quantity for example, the new row is lost, and the grid is read only:
![wpfGrid5](https://user-images.githubusercontent.com/52073354/59921864-10d64e80-93fd-11e9-8d93-6064c43bb30c.jpg)

The user should see the empty new row when going back to a previous line item, and they should be able to edit fields in the existing item:
![wpfGrid4](https://user-images.githubusercontent.com/52073354/59921993-732f4f00-93fd-11e9-9840-8131c73d0c63.jpg)

We have many users using this application, and the only ones affected are those using Windows 10 Update 1903. These users also span many .NET Framework versions, 4.7.2 is currently our latest. We are not using .NET Core at the moment.

We initially entered an item into the developer community issues, but were told to post it here. Please let us know if we need to put this somewhere else, or if there is any other information needed.

https://developercommunity.visualstudio.com/content/problem/614082/wpf-datagrid-with-new-row-gets-cleared.html?

**Comment by SamBent** [comment]
@DanielPramik - on Win10 1903 you are using .NET 4.8 runtime (even if your app targets 4.7.2).  However, a standard DataGrid works correctly on my 4.8 machine.  Either the behavior you describe has been fixed since the snap of 4.8 for Win10 1903, or (more likely) it depends on factors present in your DataGrid or data model but not in mine.

Please attach (or link to) a minimal project that illustrates the issue.

**Comment by DanielPramik** [comment]
@SamBent I will work on trying to get you the simplest example I can. Here is my current thought on why this is happening.

The standard DataGrid allows the user to go to the new row by hitting the Return key on the last column. We don't allow that on this specific grid in our application, as we require the user to enter another dialog before a row can be completed. Also, we are making use of the System.Windows.Data.CollectionView.NewItemPlaceholder to show that new row that the user can click into, which you can see in the last screenshot of my initial post.

I think this functionality is part of what is causing the problem here. Again, I will work to getting you the simplest example I can.

**Comment by stevef86** [comment]
Hi @SamBent,

Dan and I have been working on this, I'm attaching a simplified (as much as we could get it) example.

I also included some videos of a before and after I was able to reproduce using the sample on a clean virtual machine.

[WPFDGIssuesRev1.zip](https://github.com/dotnet/wpf/files/3418901/WPFDGIssuesRev1.zip)


As far as the videos go, there are two MP4s, 

BEFORE_UPDATE.mp4 was run with the 4.7 version of the .NET framework installed, I went here:

https://dotnet.microsoft.com/download/dotnet-framework/net48

Then downloaded the 4.8 runtime and installed it, and then AFTER_UPDATE.mp4 is how it behaves after that.

Codewise there's a solution in the MSDG folder that was used to build it.

Hopefully this helps,
Steve

**Comment by SamBent** [comment]
@stevef86 @DanielPramik - Thanks for the repro.  I tried it on my machines, and it works correctly (as in your "before" video).  This suggests that the root cause has already been fixed;  if so, the fix will appear soon in a servicing update.   It will take further study to identify which fix solves your problem and which update contains the fix, but I wanted to reassure you right away that help is on the way.

**Comment by DanielPramik** [comment]
@SamBent  Thank you for the quick response. We'll keep an eye out for updates and let you know what we see.

Thank you!
Dan

**Comment by stevef86** [comment]
Thanks Sam, we appreciate the update

**Comment by stevef86** [comment]
@SamBent  yes thanks!

Do you happen to know what servicing update this is and if it's available as a beta? We are a little concerned that this simplified example may only be one manifestation of the problem, so were thinking if there was an update we could apply on a virtual machine/test box we could destroy we could run the full example to know it's fixed (or if it's not, come up with a different example).

Thanks again!
Steve

**Comment by orlando008** [comment]
@SamBent 
Have you perhaps tried to use the provided code on a snapshot environment from a month or two ago to see if you can reproduce that way?  Then we could know for sure that a subsequent update fixes the problem.

Thanks

**Comment by stevef86** [comment]
FWIW I upgraded said virtual to build 10.0.18362 and still have the issue with the sample I provided.

**Comment by SamBent** [comment]
I found the relevant bugfix.  It hasn't shipped yet.  Please see the customer's original [StackOverflow post](https://stackoverflow.com/questions/56775786/wpf-datagrid-rowvirtualization-problem-with-framework-net-4-8/57418223#57418223) for further details.

**Comment by orlando008** [comment]
@SamBent - do we have a more concrete release date for the fix?  We are getting pressure from our customers to get a firm date on a fix.  They are avoiding windows updates because of this problem.

**Comment by SamBent** [comment]
The fix was released today, and announced in the [.NET blog](https://devblogs.microsoft.com/dotnet/net-framework-september-2019-preview-of-quality-rollup/).

**Comment by stevef86** [comment]
Hi SamBent,

I confirmed the fix does appear to work last night (will test in a few different environments and other people t be sure, but all signs point to it being fixed in Windows 10, thanks!).

One thing we're starting to see though, I'm assuming other versions of Windows are seeing the .NET framework update as we're seeing Wndows 7 reports of the same issue. Is there a patch planned for those as well?

Steve
