### ISSUE TITLE
[DRT] DrtDigitalSignature fails due to changes in corefx

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#1047]
Copied from AzDO 832895

**Steps to reproduce:**

1. Run DrtDigitalSignature
2. Observe NRE.

This is caused by a method that no longer exists in corefx and that this test reflects into, it is related to the improved security towards sha1 signing.

Test is attempting to find a method:
typeof(System.Security.Cryptography.Xml.SignedXml)
                 .GetField("XmlDsigRSADefault",​
                System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);

which no longer exists, need to find a suitable replacement

**Comment by rladuca** [comment]
These are fixed now via: https://dnceng.visualstudio.com/internal/_git/dotnet-wpf-test/pullrequest/2445?_a=overview
