### ISSUE TITLE
[DRT] DRTXaml - ReflectionOnlyLoad is not available on .NET Core - need to sanitize codebase and fix up tests that depend on it.

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#1048]
Copied from AzDO ID 690127

ReflectionOnlyLoad API's are not available in .NET Core. WPF uses these - not extensively, but in certain critical codepaths. We have DRT's that exist to validate that these work correctly (XamlDrts - SchemaTests - ReflectionOnlyTests). 

Today, these tests are failing. We need to modify the codebase to use alternatives. System.Reflection.Metadata is one possibility. 

We also need to get going on this right away. 

Treat this as a preview blocker. Likely, this affects only PBT, but we should validate that no mainstream WPF scenarios are affected. We also seem to check if an assembly is loaded as ReflectionOnly before calling into ReflectionOnly API's - this should be protection enough. We need to validate that we are doing this everywhere carefully. 

Once we have validated these, we should modify XamlDrts\SchemaTests\ReflectionOnlyTests to an equivalent set of tests for Metadata related tests (assuming we end up converting to use S.R.MetaData). 

== 
E:\Repos\DotNet-Trusted\src\WPF\src 
λ findstr /snip reflectiononlyload *.cs | wc
     24     161    3664

E:\Repos\DotNet-Trusted\src\WPF\src 
λ findstr /snip reflectiononlyload *.cs 

PresentationFramework\System\Windows\Documents\Serialization\SerializerDescriptor.cs:236:                Assembly plugIn = Assembly.ReflectionOnlyLoadFrom(sd._assemblyPath);
PresentationFramework\System\Windows\Markup\XamlReaderHelper.cs:3375:                    Assembly asmPC = ReflectionHelper.GetAlreadyReflectionOnlyLoadedAssembly("PRESENTATIONCORE");
PresentationFramework\System\Windows\Markup\XamlReaderHelper.cs:6732:                    Assembly asmXml = ReflectionHelper.GetAlreadyReflectionOnlyLoadedAssembly("SYSTEM.XML");
PresentationFramework\System\Windows\Markup\XamlTypeMapper.cs:462:        // This event handler is called when a ReflectionOnlyLoad can't succeed because of
PresentationFramework\System\Windows\Markup\XamlTypeMapper.cs:477:                Assembly asm = ReflectionHelper.GetAlreadyReflectionOnlyLoadedAssembly(assemblyShortName);
PresentationFramework\System\Windows\Markup\XamlTypeMapper.cs:4572:                        if (!ReflectionHelper.HasAlreadyReflectionOnlyLoaded(assemblyNameLookup))
PresentationFramework\System\Windows\Markup\XmlnsCache.cs:117:                assy = ReflectionHelper.GetAlreadyReflectionOnlyLoadedAssembly(assemblyName);
Shared\System\Windows\Markup\ReflectionHelper.cs:197:        // Given a ReflectionOnlyLoaded member, returns the value of a metadata attribute of
Shared\System\Windows\Markup\ReflectionHelper.cs:208:        // Given a ReflectionOnlyLoaded type, returns the value of a metadata attribute of
Shared\System\Windows\Markup\ReflectionHelper.cs:219:        // Helper that enumerates a list of CustomAttributeData obtained via ReflectionOnlyLoad, and
Shared\System\Windows\Markup\ReflectionHelper.cs:280:        // Helper that inspects a specific CustomAttributeData obtained via ReflectionOnlyLoad, and
Shared\System\Windows\Markup\ReflectionHelper.cs:352:            _reflectionOnlyLoadedAssembliesHash[assemblyNameLookup] = null;
Shared\System\Windows\Markup\ReflectionHelper.cs:361:            return ReflectionOnlyLoadAssembly(assemblyName, assemblyPath);
Shared\System\Windows\Markup\ReflectionHelper.cs:488:        internal static bool HasAlreadyReflectionOnlyLoaded(string assemblyNameLookup)
Shared\System\Windows\Markup\ReflectionHelper.cs:504:             return (_reflectionOnlyLoadedAssembliesHash.Contains(assemblyNameLookup) && _reflectionOnlyLoadedAssembliesHash[assemblyNameLookup] != null);
Shared\System\Windows\Markup\ReflectionHelper.cs:507:        internal static Assembly GetAlreadyReflectionOnlyLoadedAssembly(string assemblyNameLookup)
Shared\System\Windows\Markup\ReflectionHelper.cs:509:             return (Assembly)_reflectionOnlyLoadedAssembliesHash[assemblyNameLookup];
Shared\System\Windows\Markup\ReflectionHelper.cs:517:        private static Assembly ReflectionOnlyLoadAssembly(string assemblyGivenName, string fullpath)
Shared\System\Windows\Markup\ReflectionHelper.cs:525:            Assembly asm = (Assembly)_reflectionOnlyLoadedAssembliesHash[assemblyShortName];
Shared\System\Windows\Markup\ReflectionHelper.cs:573:                           asm = Assembly.ReflectionOnlyLoad(asmContents);
Shared\System\Windows\Markup\ReflectionHelper.cs:613:                    asm = Assembly.ReflectionOnlyLoadFrom(fullpath);
Shared\System\Windows\Markup\ReflectionHelper.cs:621:                         asm = Assembly.ReflectionOnlyLoad(assemblyGivenName);
Shared\System\Windows\Markup\ReflectionHelper.cs:634:                    _reflectionOnlyLoadedAssembliesHash[assemblyShortName] = asm;
Shared\System\Windows\Markup\ReflectionHelper.cs:641:        private static Hashtable _reflectionOnlyLoadedAssembliesHash = new Hashtable(8);

Comments from AzDO:

The work on using MetadataLoadContext in the WPF code base has been completed. 

This test is meant to test the ability to load a reflection-only type and have XamlType interact correctly with it. In Framework this was done by loading the type through the ReflectionOnlyLoad APIs which provided an AppDomain-wide reflection-only load context, the new MetadataLoadContext APIs don't work in the same way, there no longer is a global context, rather the user is meant to create their own context, this causes an issue with how XamlType interacts with the resulting reflection-only types, because it needs to be able to call IsAssignableFrom on runtime types against these reflection-only types, which do not support comparison between types loaded from different contexts.

I believe that in order to provide support for reflection-only types in System.Xaml we would need to add a set of APIs that expose a MetadataLoadContext within System.Xaml that can be used to load the desired types and guarantee them working with System.Xaml

**Comment by rladuca** [comment]
This needs a real estimate, this might be a larger fix than the generally 2 day we are usually assigning.

**Comment by rladuca** [comment]
The test in question belies a larger set of changes that would potentially need to occur in `System.Xaml` to support load context awareness.

The test is failing in .NET Core since `ReflectionOnlyLoad` is not supported.  However, `MetadataLoadContext` cannot be used instead due to different semantics.  The assemblies in a `MetadataLoadContext` are a closed set. When deciding various properties of `XamlType`, we often use idioms like `typeof(T1).IsAssignableFrom(T2)` where T2 comes from the assemblies passed into a `XamlSchemaContext`.  In this case, T1 is coming from the runtime assemblies in the default `AssemblyLoadContext`.  In `ReflectionOnlyLoad` this would succeed as T1 and T2 would share the same root.  Since `MetadataLoadContext` is a closed set, this is no longer true and the various idioms fail.

For now this test should be disabled so as to not adversely affect results from the rest of the DRT.

**Comment by rladuca** [comment]
Internal PR: https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-test/pullrequest/3132?_a=overview

**Comment by rladuca** [comment]
Test has been disabled, closing.
