### ISSUE TITLE
[DRT] DrtImaging fails only in x64

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#1049]
Copied from AzDo: 832996

**Steps to reproduce:**

1. Run DrtImaging
2. Observe NRE.

DrtImaging fails due to a weird timing issue, only in x64, if run inside the debugger the test passes, I suspect this is a timing issue, I've confirmed it's not related to the native component

**Comment by SamBent** [comment]
No repro, using Preview7 release build.

**Comment by rladuca** [comment]
We are able to reproduce this and @SamBent knows what needs fixing for this.

Assigning to him and fixing up all the tags, etc.

**Comment by SamBent** [comment]
Fixes ported to 3.1 and 5.0 branches of test repo.
