### ISSUE TITLE
[DRT] DrtMetroTest System.Windows.Markup.XamlParseException

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#1050]
Copied from AzDO: 841548

Steps to reproduce:

1. Run DigitalDocuments/...../DrtMetroTest (failure is in DRTFixedTest)
2. Observe following exception:

System.Windows.Markup.XamlParseException: ''Initialization of 'System.Windows.Documents.FixedDocument' threw an exception.' Line number '1' and line position '552'.'

NotSupportedException: Specified method is not supported.

**Comment by rladuca** [comment]
This isn't failing in latest test passes, likely due to the wrapped stream fixes.

Going to close this.
