### ISSUE TITLE
[DRT] Re-Enable GetPartUri code in DRTPackagingAPIs

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#1051]
Copied from AzDo: 843574

 Re-enable code that uses currently missing API 'GetPartUri' when the implementation is merged into CoreFX (System.IO.Packaging).
Code snippet is in DRTPackagingApis.cs in the DigitalDocuments Area under a TODO comment. Search for 'GetPartUri'.

**Comment by stevenbrix** [comment]
This has been completed with this PR: https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-test/pullrequest/2195?_a=overview
