### ISSUE TITLE
[DRT] DrtInterleavedPackage fails after System.IO.Packaging refactoring

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#1052]
Copied from AzDO: 848772

Steps to reproduce:

1. Run DrtInterleavedPackage
2. Observe NullReferenceException from missing PAckage.Open method we reflect into.

The purpose of this test is to simulate the way XpsDocument calls into System.IO.Packaging to achieve package generation for printing and saving to disk. since System.IO.Packaging changed significantly in the support for certain features we need to first figure out how to achieve package generation correctly in product code, once we do that we can look into changing this test to reflect that.

**Comment by stevenbrix** [comment]
This has been completed with this internal PR: https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-test/pullrequest/2195?_a=overview
