### ISSUE TITLE
Build fails on current master

### ISSUE THREAD

**Issue by grokys** [dotnet/wpf#1072]
## .NET Core Version

3.0.100-preview6-012264

## Windows version

1903 (18362.175)
 
## Problem description

Running `build.cmd` on current master (2651715b87f94d1ea1e2d9a0328ab6a2d2dcf6c0) fails with:

```
PresentationFramework-SystemXml -> D:\projects\dotnet\wpf\artifacts\bin\PresentationFramework-SystemXml\Debug\netcoreapp3.0\PresentationFramework-SystemXml.dll
D:\projects\dotnet\wpf\src\Microsoft.DotNet.Wpf\src\PresentationBuildTasks\Microsoft.WinFX.targets(243,9): error MC1000: Unknown build error, 'The type initializer for 'MS.Internal.Markup.ReflectionHelper' threw an exception.'  [D:\projects\dotnet\wpf\src\Microsoft.DotNet.Wpf\test\DRT\DrtXaml\BamlTestClasses40\BamlTestClasses40.csproj]
```
 
Full build output: https://gist.github.com/grokys/516b6c771c81d236769bcc31149db9d8

There are a bunch of warnings at the top of the output, but I have no idea what should be done to fix them, or whether they're relevant...

**Comment by ryalanms** [comment]
Thanks, @grokys.  This appears to have been fixed. 

If the error appears again, try to kill all msbuild processes, delete artifacts, and clear nuget cache before building. 

```
taskkill /f /t /im msbuild.exe
taskkill /f /t /im dotnet.exe
taskkill /f /t /im vbcscompiler.exe
rmdir artifacts /q /s
dotnet nuget locals --clear all
```
If it still repros, please re-open this issue.  Thanks!
