### ISSUE TITLE
Inline Row and Column definition in Grid Constructor

### ISSUE THREAD

**Issue by Kayot** [dotnet/wpf#1073]
Row and Column definition in the Grid Constructor would help reduce a lot of boiler plate code when using XAML.

For instance, using the following;

```
<Grid ColumnDefinitions="100,1.5*,4*" RowDefinitions="1*,Auto,4*"  >
</Grid>
```

Would be faster and easier to read with near zero loss in translation or increase in complication compared to the following;

```
<Grid >
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="100"/>
        <ColumnDefinition Width="1.5*"/>
        <ColumnDefinition Width="4*"/>
    </Grid.ColumnDefinitions>
    <Grid.RowDefinitions>
        <RowDefinition Height="1*"/>
        <RowDefinition Height="Auto"/>
        <RowDefinition Height="4*"/>
    </Grid.RowDefinitions>
</Grid>
```

This could be an option, not a replacement so designers could still use the longer style and older projects would still maintain ease of portability to the WPF .NET Core 3 libraries.

Please note that I didn't think of this idea. I saw it done on Avalonia and thought it was a more efficient way of constructing a Grid.

**Comment by Symbai** [comment]
Looks like a dup of https://github.com/dotnet/wpf/issues/166 ?

**Comment by Kayot** [comment]
Dang, I thought I did a thorough search too. Since it's already been suggested I'll close this suggestion. I'll look harder next time.
