### ISSUE TITLE
Adding reference to assembly System.Web.Extensions causes build error

### ISSUE THREAD

**Issue by cbaysinger** [dotnet/wpf#1088]
dotnet -- info dotnet\packs\Microsoft.NETCore.App.Ref\3.0.0-preview6-27804-01\ref\netcoreapp3.0\System.Web.dll
* Windows version: (1809 build 17763.557)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
 **Problem description:**
Create a Core 3 App and add a reference to System.Web.Extensions then try to build. The following error is reported:
 1>C:\Program Files (x86)\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(243,9): error MC1000: Unknown build error, 'Could not find type 'System.Web.UI.WebResourceAttribute' in assembly 'C:\Program Files (x86)\dotnet\packs\Microsoft.NETCore.App.Ref\3.0.0-preview6-27804-01\ref\netcoreapp3.0\System.Web.dll'.'
 **Expected behavior:**
 Reference should be rejected or it should build as expected.
The target API is System.Web.Extensions.JavaScriptSerializer()

**Comment by grubioe** [comment]
@cbaysinger we need a minimal self contained repro to be able to investigate this.   Thanks.

**Comment by cbaysinger** [comment]
Repaired my runtime and the namespace System.Web.Extensions no longer resolves so I am going to close this.

**Comment by smohanty05** [comment]
I am getting the same error...
Severity	Code	Description	Project	File	Line	Suppression State
Error	MC1000	Unknown build error, 'Could not find type 'System.Web.UI.TagPrefixAttribute' in assembly 'C:\Program Files (x86)\dotnet\packs\Microsoft.NETCore.App.Ref\5.0.0\ref\net5.0\System.Web.dll'.' 	XXXXX	C:\Program Files (x86)\dotnet\sdk\5.0.403\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets	240

I have the following package reference and framework reference..

<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
    <PackageReference Include="Microsoft.Web.WebView2">
      <Version>1.0.1020.30</Version>
    </PackageReference>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

I tried repairing runtime, even reinstalling SDK, but still issue is not resolved. I am using Visual Studio Version 16.11.7.

**Comment by vishalmsft** [comment]
@smohanty05 we need a minimal self contained repro to be able to investigate this. Thanks

**Comment by smohanty05** [comment]
We have a 3rd party dll which we are using for a long time and it works fine .net framework4.8
But now we trying to migrate our projects to .net5.

If I add that 3rd party dll as ref. and add a blank winform(no controls added), there is no build error.
But if add a blank wpf window(no controls added), I get the build error.

When I opened that 3rd party dll in ildasm, it shows...
// Metadata version: v2.0.50727
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 2:0:0:0
}
.assembly extern System
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 2:0:0:0
}
.assembly extern System.Windows.Forms
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 2:0:0:0
}
.assembly extern System.Drawing
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 2:0:0:0
}
.assembly extern System.Data
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 2:0:0:0
}
_.assembly extern System.Web
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 2:0:0:0
}_
.assembly extern System.Xml
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 2:0:0:0
}

So not sure why error only if we have a WPF window.
