### ISSUE TITLE
Exclude release/* builds from Helix runs

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#1103]
`release/*` branches do not need test runs in Helix. During release time, these branches (like `release/3.0`) should not have to wait 45-90 mins to complete builds. 

Can we exclude these branches from Helix based test runs? 

/cc @stevenbrix

**Comment by stevenbrix** [comment]
I'd imagine we can, but I don't know off the top of my head. If we start splitting things up into different definitions then I believe we should be able to trigger those based on the branch
