### ISSUE TITLE
ToolsError build failures in 'official/dnceng/dotnet-wpf-test/refs/heads/master' - '20190627.2'

### ISSUE THREAD

**Issue by robertborr** [dotnet/wpf#1110]
@dotnet-mc-bot commented on [Thu Jun 27 2019](https://github.com/dotnet/core-eng/issues/6822)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=241858
  - **Agent:** 
  - **Error log:** ContinueOnError: False...

@robertborr

---

@robertborr commented on [Thu Jun 27 2019](https://github.com/dotnet/core-eng/issues/6822#issuecomment-506452012)

E:\A\_work\9\s\.dotnet\sdk\3.0.100-preview7-012512\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(149,5): error MSB3026: Could not copy "E:\A\_work\9\s\artifacts\bin\TestRuntime\x64\Debug\win-x64\TestApiCore.dll" to "E:\A\_work\9\s\publish\Debug\x64\Test\FeatureTests\3D\TestApiCore.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'E:\A\_work\9\s\publish\Debug\x64\Test\FeatureTests\3D\TestApiCore.dll' because it is being used by another process.  [E:\A\_work\9\s\src\Test\3D\CGTGenerated\CGTGenerated.csproj]
E:\A\_work\9\s\.dotnet\sdk\3.0.100-preview7-012512\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(149,5): error MSB3026: Could not copy "E:\A\_work\9\s\artifacts\bin\TestRuntime\x64\Debug\win-x64\TestApiCore.dll" to "E:\A\_work\9\s\publish\Debug\x64\Test\FeatureTests\3D\TestApiCore.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'E:\A\_work\9\s\publish\Debug\x64\Test\FeatureTests\3D\TestApiCore.dll' because it is being used by another process.  [E:\A\_work\9\s\src\Test\3D\CGTGenerated\CGTGenerated.csproj]
E:\A\_work\9\s\.dotnet\sdk\3.0.100-preview7-012512\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(149,5): error MSB3026: Could not copy "E:\A\_work\9\s\artifacts\bin\TestRuntime\x64\Debug\win-x64\TestRuntime.dll" to "E:\A\_work\9\s\publish\Debug\x64\Test\FeatureTests\3D\TestRuntime.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'E:\A\_work\9\s\publish\Debug\x64\Test\FeatureTests\3D\TestRuntime.dll' because it is being used by another process.  [E:\A\_work\9\s\src\Test\3D\CGTGenerated\CGTGenerated.csproj]
E:\A\_work\9\s\.dotnet\sdk\3.0.100-preview7-012512\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(149,5): error MSB3026: Could not copy "E:\A\_work\9\s\artifacts\bin\TestRuntime\x64\Debug\win-x64\TestRuntime.dll" to "E:\A\_work\9\s\publish\Debug\x64\Test\FeatureTests\3D\TestRuntime.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'E:\A\_work\9\s\publish\Debug\x64\Test\FeatureTests\3D\TestRuntime.dll' because it is being used by another process.  [E:\A\_work\9\s\src\Test\3D\CGTGenerated\CGTGenerated.csproj]
    0 Warning(s)
    4 Error(s)

---

@robertborr commented on [Thu Jun 27 2019](https://github.com/dotnet/core-eng/issues/6822#issuecomment-506452777)

Cc: @rladuca

**Comment by rladuca** [comment]
Looks like the way publish is being done in dotnet-wpf-test is resulting in a race condition between projects and sometimes they are clobbering each other.  We need to fix this up and do things the correct way.

**Comment by rladuca** [comment]
We addressed this in the short term by suppressing the MSBuild warnings.

In the long term, we need a better publishing strategy.  We're going to fix this as part of our test engineering work.
