### ISSUE TITLE
June Update for WPF on .NET Core 3.0

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#1113]
# June Update for WPF on .NET Core 3.0

In last month’s [update](https://github.com/dotnet/wpf/issues/738), we shared the exciting news that the team had open sourced 15 additional assemblies.  This month we continue to port the WPF code base to work on .NET Core and all of the latest bug fixes and code updates for Preview 7 are available via the [daily builds](https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries).  The latest released version is Preview 6 and available via [this download page](https://dotnet.microsoft.com/download/dotnet-core/3.0).

The team has been getting better and better at operating in the open, we have improved our issue triage process with a goal of triaging new issues at least twice a week.   This will ensure that we identify issues that need to be solved for .NET Core 3.0 and also to assign all issues to a milestone. 

We have been working hard at fixing issues for 3.0 and porting additional functionality from .NET Framework.  You can review all [issues](https://github.com/dotnet/wpf/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+closed%3A2019-05-23..2019-06-26+) and [PRs](https://github.com/dotnet/wpf/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+closed%3A2019-05-23..2019-06-26) that have been closed since last month's update.  

Here are a few callouts for issues resolved this month:

*  **Localization:** @ryalanms has been working on improving WPF's localization and fixing [localization issues](https://github.com/dotnet/wpf/issues/913).
* **Removing Deprecated Features:**   we have been working on cleaning up deprecated features, @ojhad has been working on removing code for a [deprecated security mode](https://github.com/dotnet/wpf/pull/1035)l and @vatsan-madhavan closed a PR for [removing XBAP code](https://github.com/dotnet/wpf/pull/1009).
* **Intellisense Support:**  @vatsan-madhavan has been doing some work on ensuring that [Intellisense works](https://github.com/dotnet/wpf/pull/979) for all Visual Studio users
* **Test Porting:** @miguep, @sambent and @arpitmathur have been working on porting feature tests and fixing DRTs.
* **Improving documentation and test infrastructure:**  @Stevenbrix has been working on improving the developer guide and on-boarding to [Helix's test infrastructure](https://github.com/dotnet/wpf/pull/888). 
* **Imrove Usability of WindowsDesktopSDK:**   @vatsan-madhavan did some work ([#1027](https://github.com/dotnet/wpf/pull/1027),[#3315](https://github.com/dotnet/sdk/pull/3315)) to improve the usability of WindowsDesktop SDK by adding warnings when UseWpf or UseWindowsForms are not set.  
* **API Compatibility Checks:**  @rladuca did [work](https://github.com/dotnet/wpf/pull/880) on [API Compatibility](https://github.com/dotnet/wpf/blob/master/Documentation/api-compat.md) in WPF, to set up and enable API Compat against .NET 4.8 reference assemblies, hand-crafted ref assemblies and their lib counterparts.
* **Application Compatibility Flags:**  We [ensured](https://github.com/dotnet/wpf/pull/787) that the Application Compatibility flags that were inherited in .NET Core from .NET Framework continue to work as before. The list and the respective default values in .NET Core are documented in this [sample](https://github.com/microsoft/WPF-Samples/pull/87/files#diff-367b1d34f8344ca7b58710a6b1d70a1a).

Thank again for your contributions and engagement.   If you have questions, suggestions, or concerns, please let us know.

**Comment by windsOne** [comment]
.net core3 WPF tried, under win7, there is a dependency on the system patch, this is too pit, I don't know if the official version can be solved.
@grubioe

**Comment by windsOne** [comment]
.net core3 WPF tried, under win7, there is a dependency on the system patch, this is too pit, I don't know if the official version can be solved.
@grubioe

**Comment by grubioe** [comment]
@windsOne.  Can you open a separate issue for it?  Thanks!
