### ISSUE TITLE
How to resolve resource keys from embedded xaml files?

### ISSUE THREAD

**Issue by weltkante** [dotnet/wpf#1146]
In #865 the xaml theme files were embedded into their theme assemblies to allow tools like VS/Blend to copy them for editing the templates.

I wanted to take a look and compared the current nightly build against the xaml files delivered with VS and noticed that the embedded resources did not provide named keys, for example

*Reference xaml installed with Visual Studio:*
```xaml
<SolidColorBrush x:Key="Button.Pressed.Border" Color="#FF2C628B" />
```
*Embedded resource xaml:*
```xaml
<SolidColorBrush x:Key="&#214;" Color="#FF2C628B" />
```

How are Visual Studio / Blend resolving these IDs to resource keys when copying a template (I'd like to provide similar logic in my own msbuild-based tooling), or is this a bug and the wrong xaml files got embedded?

**Comment by vatsan-madhavan** [comment]
@chabiss, can you help?

**Comment by weltkante** [comment]
I assume this becomes irrelevant, #1393 is removing the embedded resources, so standalone tooling will also need to carry its own copy of the reference xaml files for now.

**Comment by vatsan-madhavan** [comment]
> I assume this becomes irrelevant, #1393 is removing the embedded resources, so standalone tooling will also need to carry its own copy of the reference xaml files for now.

You are right. Also, please see #1402.
