### ISSUE TITLE
BAML streams can be longer than in .NET 4.8.  This can cause more NavigationProgress events.

### ISSUE THREAD

**Issue by SamBent** [dotnet/wpf#1147]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`) 3.0 Preview8
* Windows version: (`winver`) any
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 
 **Problem description:**
Compiling most XAML files in .NET Core produces a longer BAML stream than in .NET Framework.  This is because Core's "SDK builds" add implicit references to assemblies that contribute to the default namespace, which then appear as AssemblyInfo records in the BAML stream;  these records don't appear in Framework unless the assemblies were explicitly referenced.   For example, a typical simple app's Core BAML includes records for "System.Windows.Controls.Ribbon" and "WindowsFormsIntegration" that don't appear in the corresponding Framework BAML.  The extra records, plus references to them from elsewhere in the BAML, increases the length of the BAML stream by about 200 bytes.

This obviously results in larger file sizes and a perf impact (for reading the extra bytes), but that is admittedly small.  It doesn't cause an assembly-load impact at runtime;  the extra assemblies are not loaded if they're never used.  One less obvious impact is that loading the BAML can result in raising more [NavigationProgress](https://docs.microsoft.com/en-us/dotnet/api/system.windows.navigation.navigationservice.navigationprogress?view=netframework-4.8) events, as these are purely a function of the length of the BAML stream.

**Comment by grubioe** [comment]
Closing as known issue.

**Comment by vatsan-madhavan** [comment]
The default list of reference assemblies is outlined here for netfx projects built using WindowsDesktop SDK: 

https://github.com/dotnet/wpf/blob/008e1bb07cef9c701b4c3a976eca41509efd93ad/packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props#L91

netcore projects built using WindowsDesktop SDK will reference all WPF assemblies except Theme assemblies when UseWpf==true; they will also reference WindowsFormsIntegraion and all WinForms assemblies when UseWpf==true && UseWindowsForms==true
