### ISSUE TITLE
Add .editorconfig to clarify code style

### ISSUE THREAD

**Issue by batzen** [dotnet/wpf#115]
I think it would be nice if we could get an .editorconfig in this repo so no one has to worry about how code should be formatted and tools can take care of adhering to the desired formatting.

I guess the most consistent way would be to sync this across all dotnet repos or at least use the same as in corefx for example.
https://github.com/dotnet/corefx/blob/master/.editorconfig

**Comment by karelz** [comment]
Sounds like a good idea. Do you want to submit a PR?

**Comment by batzen** [comment]
Of course. Will do that during the weekend.
