### ISSUE TITLE
Hovering over MenuItem causes the window to get activated

### ISSUE THREAD

**Issue by batzen** [dotnet/wpf#1168]
* .NET Core Version: All
* Windows version: 1903
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 **Problem description:**
 
 **Actual behavior:**
Hovering over a `MenuItem` causes the window to get activated.
 
 **Expected behavior:**
Hovering over a `MenuItem` does not activate the window.
 
 **Minimal repro:**
- Create a new window containing a `MenuItem`
- Focus a different window
- Hover over the `MenuItem`
- Window gets activated

**Comment by grubioe** [comment]
To be considered when all tests have been ported.

**Comment by batzen** [comment]
@grubioe any news on this?

**Comment by grubioe** [comment]
@fabiant3  can provide the latest status.

**Comment by dipeshmsft** [comment]
Hey @batzen, can you provide a minimal repro for this ?

**Comment by batzen** [comment]
It's as simple as the description states.

Just place a menuitem directly inside your window.
No Menu around it.

That's of course not the real usage, but it's similar enough.
