### ISSUE TITLE
XMLNS sweep to ensure parity with desktop framework

### ISSUE THREAD

**Issue by rladuca** [dotnet/wpf#119]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`) All
* Windows version: (`winver`) All
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
 
 **Problem description:**
WPF is missing various xmlns attributes in its reference assemblies.  We need to sweep all of them to ensure we pick everything up.
 **Actual behavior:** 
 N/A
 **Expected behavior:**
 N/A
 **Minimal repro:**
 See the various related issues.

**Comment by rladuca** [comment]
We've completed the sweep and we were missing both WindowsBase and System.Xaml reference assembly XMLNS attributes.

I'll update when I am sure the fixes have made the daily builds.

**Comment by taori** [comment]
@rladuca just checking - forgot to update, or no updates yet? Currently trying to compile for netcore3.0 and XmlnsDefinitionAttribute + XmlnsPrefix is missing.

**Comment by rladuca** [comment]
@taori I want to make sure I understand, are you saying the attributes themselves are missing?

I just created a new .NET Core 3 project and I was able to add XmlnsDefinition and also XmlnsPrefix, they both were under System.Windows.Markup as expected.  Cracking open the binaries from the latest nightly, I see them defined there as well.

Is there a reproduction application you can link me to just so I can get a better idea of what is going on?

**Comment by rladuca** [comment]
Also this issue should have been closed, I forgot to do so when the daily build had updated.

@taori I'll keep this open in case I missed something, but if it's not the same problem, we might shift to opening a new issue.

**Comment by taori** [comment]
@rladuca https://github.com/taori/Amusoft.UI.WPF.git , src/Amusoft.UI.WPF/Amusoft.UI.WPF.csproj did not compile with netcoreapp3.0 - perhaps i am on a different sdk build which is not public yet ofc. If so - is there an alternative download source other than https://dotnet.microsoft.com/download/dotnet-core/3.0, where i can obtain an installer?

Using the latest sdk on the download site provides me with this:

![grafik](https://user-images.githubusercontent.com/5545184/51168317-2e7d1600-18a9-11e9-8d39-fd9a6464f542.png)

**Comment by ccifra** [comment]
The issue I was seeing was that using x:Reference in XAML would fail with a compile error.

For example using this XAML in the default WPF .net core app fails to compile with Preview 1:

<Window x:Class="TestXReference.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:TestXReference"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid x:Name="_dataGrid">
        <Grid.RowDefinitions>
            <RowDefinition Height="9*"/>
            <RowDefinition Height="1*"/>
        </Grid.RowDefinitions>
        <Label DataContext="{x:Reference _dataGrid}" Content="Hello .NET Core!" HorizontalAlignment="Center" VerticalAlignment="Center"
               FontSize="40"/>
        <Button Content="Exit" Grid.Row="1" FontSize="20" Click="ButtonExit_Click"/>
    </Grid>
</Window>


This works fine with desktop WPF.  Can I try the most recent SDK to test things out?  Will preview 2 have the fix?

  --Chris

**Comment by rladuca** [comment]
@taori That happens, having to consider the implicit references via the SDK is a new thing for a lot of WPF developers.  Glad to hear it works.

@radiy and @ccifra, I'll take a look today at x:reference.

**Comment by rladuca** [comment]
This is my mistake in my previous change, I didn't add the file to the build correctly.  Apologies, this should be fixed in daily builds a few days from now.  I believe this fix will also make Preview 2.

**Comment by rladuca** [comment]
You should now see this fix in the latest daily build (3.0.0-preview-27315-14) of the WindowsDesktop SDK.

I was able to compile with x:Reference without issue on that build.

@radiy and @ccifra if you can confirm that you're good to go, I'll close this.  Thanks!

**Comment by radiy** [comment]
@rladuca Thank you, finally something compiles.

**Comment by rladuca** [comment]
This is in both the latest daily builds and will make it into Preview 2, so I am going to close this.

Feel free to comment and ping me if you think there is more to fix.

**Comment by ccifra** [comment]
This still seems to be an issue with Preview 2:

[cid:image003.png@01D4B357.9517AB30]
[cid:image004.jpg@01D4B357.9517AB30]
Did it definitely make it in?

  --Chris

**Comment by rladuca** [comment]
@ccifra I installed the latest daily build of .NET Core 3 and was able to compile and run the sample code that you pasted with no issue.

I cracked open both the installed shared framework lib binary and the ref assembly from the corresponding nuget package.  Both contain the XML namespace definitions.  This was checked in early enough to snap to Preview 2 builds (there is no officially released Preview 2 yet) so it will be out with that as well.

Are you sure you're using the latest daily builds?  I can't see what you posted as the error condition.

**Comment by ccifra** [comment]
To close the loop on this.  I thought that the Visual Studio Preview 2 include the .net core preview 2.  My mistake.  I did test our code against the latest daily build of .net core and this issue does appear to be fixed.

Thanks,
   --Chris

**Comment by rladuca** [comment]
Yep, that can be confused when multiple things with the preview moniker are in flight.  Thanks for confirming!
