### ISSUE TITLE
[DRT] Remove DrtInterleavedPackage, DrtPackageCompression, DrtZipIO

### ISSUE THREAD

**Issue by SamBent** [dotnet/wpf#1200]
These three DRTs test internal implementation by reflecting into WindowsBase to find the internal classes/methods of interest.  But the implementation moved to CoreFX, so these DRTs fail because reflection doesn't find the targets.  These DRTs are of no value to WPF - remove them.

**Comment by SamBent** [comment]
Fixed in wpf-test.

**Comment by rladuca** [comment]
CC: @stevenbrix In case this impacts anything you're porting.

**Comment by stevenbrix** [comment]
I had deleted DrtZipIO, but I thought that the other two were just using reflection to access the public types in WindowsBase that moved to corefx and still had value. But maybe we should really port the tests over to corefx?
