### ISSUE TITLE
Crash if run from ZIP

### ISSUE THREAD

**Issue by onovotny** [dotnet/wpf#123]
Take a zip file containing a self contained app. Open it in WinRAR, then try to run the exe. WinRAR extracts it to a temp directory, but there's a 8.3 mismatch:

```
1) Failed WPF DLL consistency checks. Expected location: C:\Users\Administrator\AppData\Local\Temp\Rar$EXa0.654.
DLL Name: PresentationNative_cor3.dll DLL Location: C:\Users\ADMINI~1\AppData\Local\Temp\Rar$EXa0.654
```

The consistency check should take the 8.3 name into account as a match.

**Comment by rladuca** [comment]
@onovotny Thanks for reporting this.  We'll take a look at the code for this and loop back when we have a fix for it.

**Comment by grubioe** [comment]
Closing as this was fixed, if this is still a problem please file a new issue.
