### ISSUE TITLE
Missing some exe files

### ISSUE THREAD

**Issue by Simon-IT** [dotnet/wpf#1238]
.NET Core Version: 3.0.100-preview6-012264
Windows version: Windows 10 1903 (build SO 18362.239)

Hi,
running dotnet/wpf/build.cmd four packages are downloaded as prerequisites:

- dotnet-api-docs_netcoreapp3.0-0.0.0.1-win64-x64.zip;
- msvcurt-c1xx-0.0.0.4-win64-x64.zip;
- net-framework-48-ref-assemblies-0.0.0.1-win64-x64.zip
- strawberry-perl-5.28.1.1-1-win64-x64.zip

All four should has an exe file inside, but they haven't it instead. This issue throw an exception and so the build procedure stops.
Regards,
Smone

**Comment by vatsan-madhavan** [comment]
Can you post the build output exactly as you see ?

**Comment by Simon-IT** [comment]
Yes, but give me a moment for explain the situation better.
I've debugged the PS scripts starting from the build.cmd file. The relevant point is in _dotnet\wpf\eng\common\native\install-tool.ps1_ file. Starting at line 84 the procedure downloads and extracts the zip file for the tool: for example the URI for perl is _https://netcorenativeassets.blob.core.windows.net/resource-packages/external/windows/strawberry-perl/strawberry-perl-5.28.1.1-1-win64-x64.zip_. At this point it searches an exe file among the extracted files that for perl is _strawberry-perl.exe_: this is at line 101 `$ToolFilePath = Get-ChildItem $ToolInstallDirectory -Recurse -Filter "$ToolName.exe" | % { $_.FullName }`. Since the file is not present, the procedure fails; this happens with the four packages above.

This is the diagnostic log:
_D:\Sources\Repos\NetFoundation\dotnet\wpf>build -verbose diag
DETTAGLIATO: Caricamento del modulo dal percorso 'D:\Sources\Repos\NetFoundation\dotnet\wpf\eng\common\native\CommonLibrary.psm1'.
DETTAGLIATO: Importazione della funzione 'DownloadAndExtract'.
DETTAGLIATO: Importazione della funzione 'Expand-Zip'.
DETTAGLIATO: Importazione della funzione 'Get-File'.
DETTAGLIATO: Importazione della funzione 'Get-MachineArchitecture'.
DETTAGLIATO: Importazione della funzione 'Get-NativeInstallDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempPathFilename'.
DETTAGLIATO: Importazione della funzione 'New-ScriptShim'.
Processing D:\Sources\Repos\NetFoundation\dotnet\wpf\global.json
DETTAGLIATO: Installing strawberry-perl version 5.28.1.1-1
DETTAGLIATO: Executing 'D:\Sources\Repos\NetFoundation\dotnet\wpf\eng\common\native\install-tool.ps1 System.Collections.Hashtable'
DETTAGLIATO: Importazione della funzione 'DownloadAndExtract'.
DETTAGLIATO: Importazione della funzione 'Expand-Zip'.
DETTAGLIATO: Importazione della funzione 'Get-File'.
DETTAGLIATO: Importazione della funzione 'Get-MachineArchitecture'.
DETTAGLIATO: Importazione della funzione 'Get-NativeInstallDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempPathFilename'.
DETTAGLIATO: Importazione della funzione 'New-ScriptShim'.
DETTAGLIATO: strawberry-perl (5.28.1.1-1) already exists, skipping install
strawberry-perl was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: strawberry-perl was not found in .
AVVISO: strawberry-perl installation failed
DETTAGLIATO: Installing net-framework-48-ref-assemblies version 0.0.0.1
DETTAGLIATO: Executing 'D:\Sources\Repos\NetFoundation\dotnet\wpf\eng\common\native\install-tool.ps1 System.Collections.Hashtable'
DETTAGLIATO: Importazione della funzione 'DownloadAndExtract'.
DETTAGLIATO: Importazione della funzione 'Expand-Zip'.
DETTAGLIATO: Importazione della funzione 'Get-File'.
DETTAGLIATO: Importazione della funzione 'Get-MachineArchitecture'.
DETTAGLIATO: Importazione della funzione 'Get-NativeInstallDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempPathFilename'.
DETTAGLIATO: Importazione della funzione 'New-ScriptShim'.
DETTAGLIATO: net-framework-48-ref-assemblies (0.0.0.1) already exists, skipping install
net-framework-48-ref-assemblies was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: net-framework-48-ref-assemblies was not found in .
AVVISO: net-framework-48-ref-assemblies installation failed
DETTAGLIATO: Installing dotnet-api-docs_netcoreapp3.0 version 0.0.0.1
DETTAGLIATO: Executing 'D:\Sources\Repos\NetFoundation\dotnet\wpf\eng\common\native\install-tool.ps1 System.Collections.Hashtable'
DETTAGLIATO: Importazione della funzione 'DownloadAndExtract'.
DETTAGLIATO: Importazione della funzione 'Expand-Zip'.
DETTAGLIATO: Importazione della funzione 'Get-File'.
DETTAGLIATO: Importazione della funzione 'Get-MachineArchitecture'.
DETTAGLIATO: Importazione della funzione 'Get-NativeInstallDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempPathFilename'.
DETTAGLIATO: Importazione della funzione 'New-ScriptShim'.
DETTAGLIATO: dotnet-api-docs_netcoreapp3.0 (0.0.0.1) already exists, skipping install
dotnet-api-docs_netcoreapp3.0 was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: dotnet-api-docs_netcoreapp3.0 was not found in .
AVVISO: dotnet-api-docs_netcoreapp3.0 installation failed
DETTAGLIATO: Installing msvcurt-c1xx version 0.0.0.4
DETTAGLIATO: Executing 'D:\Sources\Repos\NetFoundation\dotnet\wpf\eng\common\native\install-tool.ps1 System.Collections.Hashtable'
DETTAGLIATO: Importazione della funzione 'DownloadAndExtract'.
DETTAGLIATO: Importazione della funzione 'Expand-Zip'.
DETTAGLIATO: Importazione della funzione 'Get-File'.
DETTAGLIATO: Importazione della funzione 'Get-MachineArchitecture'.
DETTAGLIATO: Importazione della funzione 'Get-NativeInstallDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempPathFilename'.
DETTAGLIATO: Importazione della funzione 'New-ScriptShim'.
DETTAGLIATO: msvcurt-c1xx (0.0.0.4) already exists, skipping install
msvcurt-c1xx was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: msvcurt-c1xx was not found in .
AVVISO: msvcurt-c1xx installation failed
Detecting WPF Git hooks...
Detected existing WPF Git pre-commit hook.
DETTAGLIATO: Importazione della funzione 'DownloadAndExtract'.
DETTAGLIATO: Importazione della funzione 'Expand-Zip'.
DETTAGLIATO: Importazione della funzione 'Get-File'.
DETTAGLIATO: Importazione della funzione 'Get-MachineArchitecture'.
DETTAGLIATO: Importazione della funzione 'Get-NativeInstallDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempPathFilename'.
DETTAGLIATO: Importazione della funzione 'New-ScriptShim'.
Processing D:\Sources\Repos\NetFoundation\dotnet\wpf\eng\..\global.json
DETTAGLIATO: Installing strawberry-perl version 5.28.1.1-1
DETTAGLIATO: Executing 'D:\Sources\Repos\NetFoundation\dotnet\wpf\eng\common\native\install-tool.ps1 System.Collections.Hashtable'
DETTAGLIATO: Importazione della funzione 'DownloadAndExtract'.
DETTAGLIATO: Importazione della funzione 'Expand-Zip'.
DETTAGLIATO: Importazione della funzione 'Get-File'.
DETTAGLIATO: Importazione della funzione 'Get-MachineArchitecture'.
DETTAGLIATO: Importazione della funzione 'Get-NativeInstallDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempPathFilename'.
DETTAGLIATO: Importazione della funzione 'New-ScriptShim'.
DETTAGLIATO: strawberry-perl (5.28.1.1-1) already exists, skipping install
strawberry-perl was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: strawberry-perl was not found in .
AVVISO: strawberry-perl installation failed
DETTAGLIATO: Installing net-framework-48-ref-assemblies version 0.0.0.1
DETTAGLIATO: Executing 'D:\Sources\Repos\NetFoundation\dotnet\wpf\eng\common\native\install-tool.ps1 System.Collections.Hashtable'
DETTAGLIATO: Importazione della funzione 'DownloadAndExtract'.
DETTAGLIATO: Importazione della funzione 'Expand-Zip'.
DETTAGLIATO: Importazione della funzione 'Get-File'.
DETTAGLIATO: Importazione della funzione 'Get-MachineArchitecture'.
DETTAGLIATO: Importazione della funzione 'Get-NativeInstallDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempPathFilename'.
DETTAGLIATO: Importazione della funzione 'New-ScriptShim'.
DETTAGLIATO: net-framework-48-ref-assemblies (0.0.0.1) already exists, skipping install
net-framework-48-ref-assemblies was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: net-framework-48-ref-assemblies was not found in .
AVVISO: net-framework-48-ref-assemblies installation failed
DETTAGLIATO: Installing dotnet-api-docs_netcoreapp3.0 version 0.0.0.1
DETTAGLIATO: Executing 'D:\Sources\Repos\NetFoundation\dotnet\wpf\eng\common\native\install-tool.ps1 System.Collections.Hashtable'
DETTAGLIATO: Importazione della funzione 'DownloadAndExtract'.
DETTAGLIATO: Importazione della funzione 'Expand-Zip'.
DETTAGLIATO: Importazione della funzione 'Get-File'.
DETTAGLIATO: Importazione della funzione 'Get-MachineArchitecture'.
DETTAGLIATO: Importazione della funzione 'Get-NativeInstallDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempPathFilename'.
DETTAGLIATO: Importazione della funzione 'New-ScriptShim'.
DETTAGLIATO: dotnet-api-docs_netcoreapp3.0 (0.0.0.1) already exists, skipping install
dotnet-api-docs_netcoreapp3.0 was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: dotnet-api-docs_netcoreapp3.0 was not found in .
AVVISO: dotnet-api-docs_netcoreapp3.0 installation failed
DETTAGLIATO: Installing msvcurt-c1xx version 0.0.0.4
DETTAGLIATO: Executing 'D:\Sources\Repos\NetFoundation\dotnet\wpf\eng\common\native\install-tool.ps1 System.Collections.Hashtable'
DETTAGLIATO: Importazione della funzione 'DownloadAndExtract'.
DETTAGLIATO: Importazione della funzione 'Expand-Zip'.
DETTAGLIATO: Importazione della funzione 'Get-File'.
DETTAGLIATO: Importazione della funzione 'Get-MachineArchitecture'.
DETTAGLIATO: Importazione della funzione 'Get-NativeInstallDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempDirectory'.
DETTAGLIATO: Importazione della funzione 'Get-TempPathFilename'.
DETTAGLIATO: Importazione della funzione 'New-ScriptShim'.
DETTAGLIATO: msvcurt-c1xx (0.0.0.4) already exists, skipping install
msvcurt-c1xx was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: msvcurt-c1xx was not found in ._

Simone

**Comment by vatsan-madhavan** [comment]
> AVVISO: dotnet-api-docs_netcoreapp3.0 installation failed

It's a  _warning_. The warning text says things like "failed", but it's still just a warning. 

If the corresponding zip files get downloaded to `%userprofile%\.netcoreeng\native\temp`, and subsequently get unzipped under `$(RepoRoot).tools\native`, then these tools are being acquired correctly.
