### ISSUE TITLE
visual studio hang while working with .net core wpf

### ISSUE THREAD

**Issue by ghost1372** [dotnet/wpf#1239]
hi when i working with .net core and wpf app after 2 or 3 time build and run app, visual studio hangs and displays the message Visual Studio busy...
windows 10.18362
visual studio 16.2 preview 3 
core sdk preview 6

**Comment by grubioe** [comment]
Hi @ghost1372 please log an issue in the Visual Studio Developer Community- it will then be directed to the Visual Studio team.
https://developercommunity.visualstudio.com/content/problem/post.html?space=8

Thanks!
