### ISSUE TITLE
Build failed while writing custom controls

### ISSUE THREAD

**Issue by hez2010** [dotnet/wpf#1264]
* .NET Core Version: 3.0 preview 6
* Windows version: windows 10 1809 17763.615
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**
Write a custom control, and build it. There's a possibility to get build error: Unknown build error, 'An item with the same key has already been added. Key: themes/generic.baml'.  
And if you build it multiple times, it might succeed.
 
 **Actual behavior:**
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(687,5): error RG1000: Unknown build error, 'An item with the same key has already been added. Key: themes/generic.baml'

 **Expected behavior:**
No errors. 

 **Minimal repro:**
[XSecControls.zip](https://github.com/dotnet/wpf/files/3390244/XSecControls.zip)

**Comment by ryalanms** [comment]
Thanks @hez2010.   The SDK automatically pulls in all .xaml files, including themes/generic.xaml, which appears to be causing the duplicate ResourceItem at compile time.  

https://github.com/dotnet/wpf/blob/master/packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props#L37

```xml
    <Page Include="**/*.xaml"
          Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder);@(ApplicationDefinition)"
          Condition="'$(EnableDefaultPageItems)' != 'false'" >
      <Generator>MSBuild:Compile</Generator>
    </Page>
```

Two options to fix the error when building the repro project are removing the explicit Page Item include for generic.xaml or setting the 'EnableDefaultPageItems' property to false and explicitly including all .xaml files as Pages.   

Removing the Include for Generic.xaml from the .csproj is probably the easiest fix.  This file will automatically be pulled in by the SDK: 

```xml
 <ItemGroup>
    <Page Include="Themes\Generic.xaml" >
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
```

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <OutputType>library</OutputType>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <Version>3.0.0.0</Version>
    <Authors>X-Sec</Authors>
    <Product>X-Sec Antivirus</Product>
    <Description>X-Sec Antivirus Custom Controls</Description>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Copyright>(c) X-Sec.  All rights reserved.</Copyright>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Remove="Themes\**" />
    <EmbeddedResource Remove="Themes\**" />
    <None Remove="Themes\**" />
  </ItemGroup>

 <ItemGroup>
    <Page Include="Themes\Generic.xaml" >
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  
</Project>
```

**Comment by ryalanms** [comment]
Please re-open this issue if the above suggestions don't work.  Thanks.

**Comment by vatsan-madhavan** [comment]
Turns out that there is a bug in `Microsoft.NET.Sdk.WindowsDesktop.props` - it fails to correctly initialize `EnableDefaultPageItems`, which in turn prevents the duplicate detection logic for `Page` items from running. 

Reactivating this so that we can fix this issue.

**Comment by ryalanms** [comment]
Adding a default 'true' for unset `EnableDefaultPageItems` and `EnableDefaultApplicationDefinition` in `Microsoft.NET.Sdk.WindowsDesktop.props` causes MSBuild's `CheckForDuplicateItems` to output the correct error: 

C:\Program Files\dotnet\sdk\3.0.100-preview8-013270\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.NET.Sdk.WindowsDesktop.targets(21,5): error NETSDK1022: Duplicate 'Page' items were included. The .NET SDK includes 'Page' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultPageItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'Themes\Generic.xaml' [I:\test\XSecControls\XSecControls.csproj]

I'll send a PR shortly.

**Comment by ryalanms** [comment]
https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#default-compilation-includes-in-net-core-projects needs to be updated.

**Comment by grubioe** [comment]
Closing as documentation issue is being tracked separately.
