### ISSUE TITLE
DesignerProperties.DesignStyle throws object reference exception

### ISSUE THREAD

**Issue by Symbai** [dotnet/wpf#1267]
* .NET Core Version: 3.0.0-preview8-27911-03
* Windows version: Win10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: **No**

 **Problem description:**
using `DesignerProperties.DesignStyle` feature in a .NET Core 3.0 WPF project fails with an exception. Works fine in .NET Framework 4.8 WPF project.
 
 **Actual behavior:**
`Object reference not set to an instance of an object.` is thrown in Visual studio log. The designer works fine even when the exception is thrown. I can still modify the XAML and see changes but the style in DesignStyle is ignored.
 
 **Expected behavior:**
No exception and desired effect is shown in designer.
 
 **Minimal repro:**

1.  Create a new WPF .NET Core 3.0 project
2. Add a usercontrol to it
3. Add the following code 

```
<d:DesignerProperties.DesignStyle>
        <Style TargetType="UserControl">
            <Style.Setters>
                <Setter Property="Background" Value="White" />
            </Style.Setters>
        </Style>
    </d:DesignerProperties.DesignStyle>
```

**Comment by grubioe** [comment]
Hi @Symbai can you log an issue in the Visual Studio Developer Community- it will then be directed to the Designer team.
https://developercommunity.visualstudio.com/content/problem/post.html?space=8

Thanks!

Cc@LyalinDotCom
