### ISSUE TITLE
AttachedPropertyBrowsableForType attribute need to be added

### ISSUE THREAD

**Issue by TempeBrennan** [dotnet/wpf#1280]
In .NET Framework, we use AttachedPropertyBrowsableForType attribute to show attach property in Visual Studio property window in design time.
```
[AttachedPropertyBrowsableForType(typeof(UIElement))] 
public static double GetAngle(DependencyObject obj)
{
       return (double)obj.GetValue(AngleProperty);
}
```
Now in .NET Core, it seems not support this property. 
But I can see .NET Core support AttachedPropertyBrowsableForChildren attribute.

Can we add this attribute or is there any workaround? thanks a lot!

**Comment by rladuca** [comment]
@TempeBrennan Do you mean the type for the attribute cannot be found or that Visual Studio is ignoring the attribute with respect to the property window?

**Comment by TempeBrennan** [comment]
> @TempeBrennan Do you mean the type for the attribute cannot be found or that Visual Studio is ignoring the attribute with respect to the property window?

yes, I found Visual Studio is ignoring the attribute with respect to the property window.
I found doc doesn't write support for .NET  Core for this attribute:

please refer:

[AttachedPropertyBrowsableForType support for .net framework](https://docs.microsoft.com/zh-cn/dotnet/api/system.windows.attachedpropertybrowsablefortypeattribute.targettype?redirectedfrom=MSDN&view=netframework-4.8#System_Windows_AttachedPropertyBrowsableForTypeAttribute_TargetTypehttps://docs.microsoft.com/zh-cn/dotnet/api/system.windows.attachedpropertybrowsablefortypeattribute.targettype?redirectedfrom=MSDN&view=netframework-4.8#System_Windows_AttachedPropertyBrowsableForTypeAttribute_TargetType)

[AttachedPropertyBrowsableForChildrenAttribute support for .net framework and .net core preview 6](https://docs.microsoft.com/zh-cn/dotnet/api/system.windows.attachedpropertybrowsableforchildrenattribute?view=netframework-4.8)

**Comment by rladuca** [comment]
@TempeBrennan Thanks!  That makes more sense to me then, I was worried somehow the type had not been picked up from our assemblies.

@grubioe I think this is a designer issue and not a WPF issue.  We might want to move this accordingly during triage.

@chabiss Is this something that designer would be doing or some other VS team?

**Comment by grubioe** [comment]
Thanks all. 

@TempeBrennan can you log an issue in the Visual Studio Developer Community? It will then be directed to the correct Visual Studio team.
https://developercommunity.visualstudio.com/content/problem/post.html?space=8

Cc: @LyalinDotCom

**Comment by TempeBrennan** [comment]
Thanks for respond.
I reported a bug here:
[link](https://developercommunity.visualstudio.com/content/problem/650802/attachedpropertybrowsablefortype-attribute-need-to.html)

**Comment by varKeytrap** [comment]
Any news on this ? I have the same issue, the `[AttachedPropertyBrowsableForType(typeof(TextBoxBase))]` has no effect whatsoever

**Comment by GF-Huang** [comment]
They fake out us.
