### ISSUE TITLE
Project Template error in .NetCore 3

### ISSUE THREAD

**Issue by ghost1372** [dotnet/wpf#1324]
* .NET Core Version: 3.0 Preview6
* Windows version: 18362.239
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
 
 **Problem description:**
Hi, I've created a project template for netcore3 that includes a package
I added the package this way:
```
 <WizardData>
    <packages repository="extension" repositoryId="5949c79d-eb43-4033-8b7b-9349d34512c6">
      <package id="HandyControl" version="2.0.0" />
    </packages>
  </WizardData>	

```
 **Actual behavior:** 
 Now, when I create a project with this template, I get the error
![Untitled](https://user-images.githubusercontent.com/9213496/61575510-fd90ce80-aae1-11e9-83a7-559a9632d3e5.png)
But after an error, if I run the project, it will be compiled and run without problems
 **Expected behavior:**
 Create project without error

**Comment by grubioe** [comment]
Hi @ghost1372  can you log an issue in the Visual Studio Developer Community- it will then be directed to the right Visual Studio team.  
https://developercommunity.visualstudio.com/content/problem/post.html?space=8

Thanks!
