### ISSUE TITLE
Xaml Islands - 'Windows.UI.Xaml.Markup.XamlParseException'

### ISSUE THREAD

**Issue by ken30096** [dotnet/wpf#1328]
# Xaml Islands - 'Windows.UI.Xaml.Markup.XamlParseException'
Using the following Microsoft documentation - "WindowsXamlHost control for Windows Forms and WPF", I am attempting to complete the following exercise: [Add a custom UWP control](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/windowsxamlhost#add-a-custom-uwp-control). After carefully following the documentation I get the following error "Xaml parsing failed". See below for further details.

## Error
<code>
Exception thrown at 0x00007FF9C8BAA839 (KernelBase.dll) in TestWPFApp.exe: WinRT originate error - 0x80004005 : 'Cannot locate resource from 'ms-appx:///UWPClassLibrary/MyPage.xaml'.'.
onecore\com\combase\winrt\error\restrictederror.cpp(1014)\combase.dll!00007FF9C97EB690: (caller: 00007FF9C97E60BC) ReturnHr(1) tid(2f80) 8007007E The specified module could not be found.
Exception thrown: 'Windows.UI.Xaml.Markup.XamlParseException' in TestWPFApp.exe
The thread 0x54b4 has exited with code 0 (0x0).
</code>

## Research
I made certain that I did not accidentally step on the xaml code that I was instructed to insert into MyPage.xaml by removing it and I got the same error. It seems to me WPF is trying to locate a UWP Class Library as a locally defined resource but this is Xaml Island not WPF. If that is indeed the case, how do I do this? Are instructions missing from documentation? This is not just a futile exercise, I need to know how to create a UWP user control for my WPF project. I am using the exercise as a first step. You can repeat the error by following the documentation. I created a video that completes the full exercise up to the point of the error and my attempt to resolve it. Since I know you are pressed for time, as always, the error occurs at minute: 22:14. Click on this link to review the video: [Xaml Islands - Add a custom UWP control](https://www.youtube.com/watch?v=oMH7aPd9xvM)

>Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes! <br>

## Sofware used to build the application:
<ul>
  <li>Microsoft Visual Studio Community 2019 Preview (version 16.2.0 Preview 4.0).</li>
  <li>Windows 10 Pro 1903 OS Build 18362.10005</li>
  <li>WPF .Net Framework 4.7.2 using C#</li>
  <li>Windows Application Packaging
    <ul id="list2">
        <li>Target version: Windows 10. version 1903 (10.0; Build 18362)</li>
        <li>Min version:    Windows 10. version 1903 (10.0; Build 18362)</li>
    </ul>
  </li>  
  <li>NuGet Packages
    <ul id="list2">
        <li>Microsoft.Windows.SDK.Contracts (v10.0.18362.2002-preview)</li>
        <li>Microsoft.Toolkit.Wpf.UI.XamlHost (v6.0.0-preview6.4)</li>
    </ul>
  </li>  
</ul>
<br>

**Comment by lindexi** [comment]
Could you clean your obj and bin folder and then restore and rebuild it? I will find sometimes rebuild can fix the xaml parser exception.

**Comment by ken30096** [comment]
## Clean object and bin folder - failed:<br> 

I used the following StackOverflow article as a guide on [How to clean Visual Studio bin and obj folders](https://stackoverflow.com/questions/1088593/how-to-clean-visual-studio-bin-and-obj-folders)  I unloaded UWPClassLibrary.csproj and added the following code just before the last statement: 

```
  <Target Name="SpicNSpan" AfterTargets="Clean">
    <RemoveDir Directories="$(TargetDir)" />
    <!-- bin -->
    <RemoveDir Directories="$(ProjectDir)$(BaseIntermediateOutputPath)" />
    <!-- obj -->
  </Target>
```
<p>
and reloaded the project. I right-clicked on the UWPClassLibrary and selected "Build". I am assuming by "restore" you are referring to NuGet Packages. I had previously set the following option in VS2019CE: In Tools -> Options -> NuGet Package Manager -> General, select the "Allow NuGet to download missing packages" option which allows NuGet to restore and then "Automatically check for missing packages during build in Visual Studio" which enables on build restore.  I then rebuilt the solution and received the same error. 
</p>

Since I was uncertain of what effect  cleaning the object and bin folder was supposed to have, I downloaded  [Clean Bin and Obj](https://marketplace.visualstudio.com/items?itemName=dobrynin.cleanbinandobj) from the Marketplace and ran it. It produced the following:

<p>
18:58:41.4890: Starting... Projects to clean: 3<br>
18:58:41.5049: Cleaning BuildWAP\BuildWAP.wapproj<br>
18:58:41.5368: Cleaning TestWPFApp\TestWPFApp.csproj<br>
18:58:41.5539: Cleaning UWPClassLibrary\UWPClassLibrary.csproj<br>
18:58:41.5697: Finished. Process took 00:00.0680
</p>
<p>
I got the same results. In addition I totally rebuilt the project from scratch, implemented the suggested proposal again and got the same results!
</p>

**Comment by grubioe** [comment]
Moving to Microsoft.Toolkit.Win32 Repo

https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/148

**Comment by ken30096** [comment]
grubioe, I noticed that the issue that I opened has been closed without a resolution. I see where you have provided a [link](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/148) indicating that it was moved but when I click on that link it takes me to a clone of the same issue that I opened but with a different issue number (148), which is also CLOSED! Please let me know what's happening?

**Comment by grubioe** [comment]
I'm seeing the issue open in the Win32 repo:

https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/148, can you check that you are on the Win32 repo? 

Thanks

**Comment by azchohfi** [comment]
.NET Framework WPF projects cannot instantiate Managed UWP controls. You can only use managed UWP custom controls within a .NET **Core** WPF or WinForms app.

**Comment by ken30096** [comment]
I tested this issue on 3 platforms:<br>.Net Framework 4.7.2<br>.Net Framework 8<br>.Net Core 3.0<br>. Each time I got the same error! I created a [video](https://www.youtube.com/watch?v=0fMxGrkHuHg) of the exercise using .Net Core 3.0 (minute 01:04) and the subsequent error (minute 16:57). Before I opened this issue, I tried very hard to make certain it was an issue.
