### ISSUE TITLE
MarkupCompilePass1 temp project looping

### ISSUE THREAD

**Issue by wjk** [dotnet/wpf#134]
* .NET Core Version: 3.0.100-preview-009812
* Windows version: Windows 10 1908, build 17763.134
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
 
## Problem description

Under circumstances I'm not yet able to fully pin down (outside of my proprietary project, I cannot get this bug to reproduce), the `MarkupCompilePass1` temporary projects for some bizarre reason create and invoke themselves recursively until one of the projects' paths hits the 260-character mark and the build fails. This only happens with one project in my solution, does not occur with the other two projects in the solution, and does not occur when I copy the project out of the solution into its own folder.

## Actual behavior

The `*_wpftmp.csproj` files create and invoke themselves recursively, until the path name gets too long (it gets longer each iteration) and an exception is thrown.

## Expected behavior

It should build!

## Minimal repro

Can't isolate one yet, but an MSBuild binlog is attached (zipped to get GitHub to accept it).

[msbuild.binlog.zip](https://github.com/dotnet/wpf/files/2660130/msbuild.binlog.zip)

**Comment by ryalanms** [comment]
@wjk, have you seen this with recent SDKs?  Thanks.

**Comment by wjk** [comment]
@ryalanms I have not seen this bug in any other project, and the codebase I first found it in I have since discarded. I will hazard to say it has been fixed in the interm. If it ever reoccurs, I'll reopen this issue. Thanks!
