### ISSUE TITLE
[Request] Open source C++ projects even if it doen't compile or integrates with C# projects.

### ISSUE THREAD

**Issue by zwcloud** [dotnet/wpf#1341]
I want to **learn**:
* How WPF rendering?
* How WPF layout complex text paragraph?

Almost all these underlying implementations are written in native C++ projects, for example, milcore.dll and [Line Services](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/TextFormatting/LineServices.cs).

To learn from these, one don't need a compile-able vcxproj, only the source code is needed.

Puting these projects in a downloadable zip file is enough: there is no need to add them to this repo.

I think one important aspect of opensource is provide code so others can learn from it.

**Comment by weltkante** [comment]
> I want to learn: How WPF layout complex text paragraph?

Don't get your hopes up too much, Text layout and Line Services are not considered part of WPF and won't be open sourced, `PresentationNative_cor3` will only be deployed in binary form. [[1]](https://github.com/dotnet/wpf/commit/ba91ee72562f2a11848103111d11fe1e2161f378#r35295686). Rendering itself is still on the roadmap as far as I understand.
