### ISSUE TITLE
[Question]Does WPF support displaying HDR images? 

### ISSUE THREAD

**Issue by MattHyman** [dotnet/wpf#1344]
Does WPF support displaying HDR images? Specifically does it support displaying JXR images as bitmaps in the application? Do any manifest changes need to be made to enable this?

**Comment by grubioe** [comment]
Replied via internal email:  

WPF relies on WIC (Windows Imaging Component) for image display and looking at documentation it seems that HDR is supported.  

I found a few StackOverflow articles that might help as well:

https://stackoverflow.com/questions/22499407/how-to-display-a-bitmap-in-a-wpf-image?noredirect=1

https://stackoverflow.com/questions/94456/load-a-wpf-bitmapimage-from-a-system-drawing-bitmap
