### ISSUE TITLE
After branching for 5.0, increase the version of WindowsBase to fix incorrect conflict resolution

### ISSUE THREAD

**Issue by dagood** [dotnet/wpf#1351]
In Core-Setup, we're trying to pack up 3.0 WPF assets to deliver as a 5.0 WindowsDesktop shared framework, and hit problems with WindowsBase.dll versioning: https://gist.github.com/dagood/5f328e6148acd7cc8ee1afcc6c60f814.

Basically, CoreFX produces a 5.0 WindowsBase.dll, which wins against WPF's 4.8 WindowsBase.dll, causing conflict resolution to favor CoreFX's--which isn't supposed to happen.

This is a tracking issue to make sure it's fixed.

/cc @ericstj @vatsan-madhavan

**Comment by ericstj** [comment]
To be clear about versions here.  AssemblyVersion from corefx is 4.0.0.0, fileversion is 5.a.b.c.

My expectation is that when WPF reversions for 5.0 it will bump AssemblyVersion to 5.0.0.0 and we'll no longer need to worry about synchronizing fileversion anymore.

**Comment by vatsan-madhavan** [comment]
Until WPF forks, wouldn't it make sense to force-back corefx's WindowsBase down to 4.0.0.0 temporarily ?

**Comment by ericstj** [comment]
Not worth it since no one should be trying to consume the WindowsDesktop SDK coming out of core-setup master.
