### ISSUE TITLE
Applying Style to a custom control masks control's template 

### ISSUE THREAD

**Issue by cbaysinger** [dotnet/wpf#1374]
* .NET Core Version: 3.0.0-preview6-27804-01
* Windows version: 1809 (OS Build 17763.615)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
**Problem description:**
Custom controls with locally applied styles are not rendered.
 **Minimal repro:**
Add a custom button control to a window and run the application. The button appears as expected and the "Live Visual Tree" shows the various elements within the custom control template. The "Live Property Explorer" says the Style is defined by Generic.xaml of the correct type as expected.  Define a style in the Window.Resources and apply the style to the button. Run the application. The button does not appear. The "Live Visual Tree" shows the root element of the button with the correct type but there are no internal elements.  The "Live Property Explorer" says the Style is defined by mainwindow.xaml. The local style properties such as foreground and background color appear updated correctly in "Live Property Explorer".  The style masking the controls template can be as simple as a style that does not set any properties.
Adding a simple button or label control with a local style does not show this behavior, rather the visual tree within the control is visible in "Live Visual Tree" and the style properties appear in the rendered button or label.  
If the custom control has the properties defined in the style set locally within the control's xaml rather than by a Style element, then the properties work correctly and the control is rendered correctly. 
The attached image illustrates a windows label with a style defined in the window, next line the custom controls without any style or local properties set. The next line illustrates these controls with properties set within the controls xaml, and finally the missing controls have their style set by styles in the windows resources. 

The attached project does not include the custom controls. If that is need I will respond.

![image](https://user-images.githubusercontent.com/22218080/61835602-512c5080-ae31-11e9-9578-b3c8c1537261.png)

[CoreApp.zip](https://github.com/dotnet/wpf/files/3429110/CoreApp.zip)

**Comment by grubioe** [comment]
@cbaysinger does this reproduce in the latest daily builds?  Thanks

**Comment by cbaysinger** [comment]
I rebuilt the project attached to the issue that was built with preview 6 using preview 7 and observed the same behavior.
Have not tried the latest daily build. If there a rational for using the latest daily build I will do that based on your advice.
I have been porting a large project to Core 3 and the preview 7 broke due to System.Window.Forms went missing.
Question, how can I define a type double in xaml since xmlns:sys="clr-namespace:System;assembly=mscorlib" is no longer available?
Thanks,
cb

**Comment by weltkante** [comment]
See #708 about the double thing. According to that issue it "should just work", but there are a few workarounds mentioned.

**Comment by cbaysinger** [comment]
Tried to build the little project I previously attached with the tip build Microsoft.NETCore.App\3.0.0-preview8-28376-13 and I can no longer build the project. The project creates COM interfaces using System.Activator.CreateInstance and this is no longer working. Tried the new preview8 version on the large project we are trying to port and had the same issue so at this point too much is broken to give you an answer. 
Regarding the Double, none of the methods in the workarounds work, but I agree it "should just work".

**Comment by weltkante** [comment]
@cbaysinger are you saying when you define doubles in xaml you get compiler errors, or do you mean designer errors? The example from #708 compiles and runs for me, only the designer is giving errors. You might want to hide intellisense errors for large WPF projects.

If you have a scenario where you get actual compile/runtime errors you probably should try to reduce it and open a new issue so it can be fixed.

**Comment by cbaysinger** [comment]
Thanks, it works just as you indicated, the designer is telling me it doesn't work but the compiler says it is ok.

**Comment by SamBent** [comment]
The Style issue is By Design.  Your assembly NPWpfCommon.dll lacks a ThemeInfo attribute, so WPF doesn't know that it contains theme resources.  (See the last section of the [documentation](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/control-authoring-overview) for more info.)   The local value for Style doesn't declare a value for Template;  WPF would look for a value declared in theme resources, but can't find any.  Therefore Template falls back to its default value - null.

A comparable .NET Framework control library behaves the same way if you remove its ThemeInfo attribute, or change both its components to ResourceLocationDictionary.None.  (In VisualStudio, that's found in Properties\assemblyinfo.cs.)

**Comment by cbaysinger** [comment]
Thanks, that fixed the problem.
I had followed a tutorial that said get rid of the AsseblyInfo.cs file because the SDK-style project would automatically create the information.  This link explains how to port the file rather than get rid of it.
https://docs.microsoft.com/en-us/dotnet/core/porting/wpf
