### ISSUE TITLE
WPF app build fails on Preview 7 when using System.Windows.Forms

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#1404]
From https://github.com/dotnet/core/issues/3075#issuecomment-515336549
@piiov reports: 

> Build a WPF Core app with the latest preview 3.0.100-preview7-012821.
> when using system.windows.forms the build failed.
> 
> Severity Code Description Project File Line Suppression State
> Error MC1000 Unknown build error, 'Could not find assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly. Line 11 Position 33.' WpfApp9 C:\Users\p.kern\source\repos\WpfApp9\WpfApp9\MainWindow.xaml 11

**Comment by vatsan-madhavan** [comment]
@rylanms, Can you please take a look ? 

/cc @dotnet/wpf-developers

**Comment by ryalanms** [comment]
`WindowsFormsHost` is working in a test application that creates a WindowsForms RichTextBox running on Preview7.  If `UseWindowsForms` is set to true in the .csproj, the markup compiler tasks should get the Windows Forms assemblies in a parameter (ReferenceList), the list consumed by `MetadataAssemblyResolver` inside `MetadataLoadContext`.   @piiov, could you post the markup and .csproj for the project that fails to compile? Thanks. 

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
</Project
```

```xml
<Window x:Class="WPF.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WPF"
        xmlns:winForms="clr-namespace:System.Windows.Forms;assembly=System.Windows.Forms"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
        <WindowsFormsHost>
            <winForms:RichTextBox/>
        </WindowsFormsHost>
</Window>
```

**Comment by Kyle-Undefined** [comment]
Upgraded a Preview 6 WPF app to Preview 7 and was getting an error like what was reported.

Adding <UseWindowsForms>true</UseWindowsForms> to the csproj resolved the issue and project now builds and runs properly.

**Comment by cbaysinger** [comment]
Thanks, this change allowed my project to build as well.

**Comment by piiov** [comment]
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
</Project

works for me, too. 
is this a workaround or the "way to go" when using system.windows.forms in wpf?

thanks @ryalanms

**Comment by merriemcgaw** [comment]
I believe this is the "way to go" for using WinForms in WPF.

**Comment by ryalanms** [comment]
Thanks for opening this issue, @piiov.
