### ISSUE TITLE
Runtime can't find COM object

### ISSUE THREAD

**Issue by cbaysinger** [dotnet/wpf#1408]
* 3.0.0-preview8-28376-13
* Windows version: Windows version: 1809 (OS Build 17763.615)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
 **Problem description:**
At runtime a COM interface can't be created because the file can't be found as in the following error displayed in the Output window: Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
An exception of type 'System.IO.FileNotFoundException' occurred in System.Private.CoreLib.dll and wasn't handled before a managed/native boundary
Could not load file or assembly 'Interop.MSComDlg, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

 **Actual behavior:** 
A simple COM object such as MSComDlg can be added to a project and it appears in the Object Browser and in IntelliSense however at run time the following exception is thrown before the MainWindow.xaml.cs static members are constructed:
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Interop.MSComDlg, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
[CoreApp.zip](https://github.com/dotnet/wpf/files/3437746/CoreApp.zip)

 **Expected behavior:**
The component should be found so that the following line of code will create an interface:
m_Dlg = (MSComDlg.CommonDialog)System.Activator.CreateInstance( m_objDlgType );
 
 **Minimal repro:**
 See the attached zip file.

**Comment by rladuca** [comment]
@cbaysinger I was able to reproduce the same issue in a console application.  This issue isn't specific to WPF and is probably better suited to somewhere like CoreFX.

**Comment by rladuca** [comment]
@grubioe I don't have permissions to transfer issues to CoreFX, do you?

**Comment by grubioe** [comment]
Me neither.  I can log an item there tomorrow

________________________________

**Comment by grubioe** [comment]
Moved to CoreFX repo:  https://github.com/dotnet/corefx/issues/39862
