### ISSUE TITLE
Library "PresentationFramework" and its dependencies

### ISSUE THREAD

**Issue by FSharpCSharp** [dotnet/wpf#142]
So first of all great praise to the whole team of Microsoft that now WPF is developed further under Open Source. This is a big milestone in the history of the .NET framework. 

I have already read all blogs and ReadMes, but unfortunately my question was not answered.

Is Microsoft also planning to publish all controls and their dependencies under Open Source, or does WPF only refer to the actual technology? WinForms also provided all the controls, so far there is only System.Xaml, the origin of WPF.

I know it's a very stupid question, but I'd be happy to get back to you if and when that will happen.

Thanks a lot!

**Comment by dotMorten** [comment]
> I have already read all blogs and ReadMe

It's literally mentioned in both the readme and roadmap files in this repo 😁. The answer is yes.

**Comment by FSharpCSharp** [comment]
All clear thanks! Then we can close the issue! Many thanks for the quick feedback! Something big is coming towards us.
