### ISSUE TITLE
A11y_.NETCore3.0(WPF)_WPFBrush_LinearGradient-InteractiveExample_AI4D: (Brushes/button '') An onscreen element must not have a null BoundingRectangle property.

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#1457]
Copied from VSO: [949047](https://devdiv.visualstudio.com/DevDiv/_queries/edit/949047/)

Application: Brushes has the following accessibility issue that needs investigation.

Issue Details
If the element is offscreen, set its IsOffscreen property to TRUE. If the element is onscreen, provide a BoundingRectangle property.

Element path: button ''

To Reproduce and How to Fix guidance: Please open the attached Accessibility Insights for Windows Test File (*.a11ytest) to reproduce the error in Accessibility Insights for Windows.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information & download this tool at https://aka.ms/AccessibilityInsights.

screenshot
![image](https://user-images.githubusercontent.com/49078227/62074414-99fc5480-b1f7-11e9-9dbb-35ad40da35c0.png)

**Comment by arpitmathur** [comment]
This is not a bug in the framework. The testing tool is complaining about a null bounding rectangle for one of the repeat buttons on the slider. This bounding rectangle is only null when the slider is moved all the way to one end, where the width of its immediate repeat button is zero.  https://github.com/microsoft/axe-windows/issues/139 was opened to track the issue
