### ISSUE TITLE
FileFormatException is in WindowsBase and System.IO.Packaging

### ISSUE THREAD

**Issue by ccifra** [dotnet/wpf#146]
# FileFormatException is in WindowsBase and System.IO.Packaging

I am working on porting a WPF application to .NET Core.  The projects reference the Microsoft.Windows.Compatibility nuget to bring in types that I need.  I am running into issues with FileFormatException.  When I use it I get a build error that FileFormatException is defined in WindowsBase and System.IO.Packaging.

# General

I am seeing this issue with .NET Core 3 preview 1 and Microsoft.Windows.Compatibility nuget version 2.1.0-preview.18571.3.  I could probably solve this with an Alias but that seems ugly and I don't even know how to alias an assembly that comes from a nuget.

You can see here where it is defined in more than 1 assembly:
https://apisof.net/catalog/System.IO.FileFormatException

You can also reproduce the issue by creating a default WPF .NET Core app, reference Microsoft.Windows.Compatibility and try to use a FileFormatException.

**Comment by ericstj** [comment]
That's fine so long as folks aren't doing runtime compilation.  Once it's gone through the compiler there isn't any ambiguity because the assembly names (and thus type names) are totally different.

**Comment by ccifra** [comment]
Switching to using the individual packages from Microsoft.Windows.Compatibility except for Microsoft.Windows.Compatibility.Shims and System.IO.Packaging seems to resolve the compile issue.  I haven't tested everything yet, but I am able to make progress.

**Comment by grubioe** [comment]
Closing as fixed.
