### ISSUE TITLE
A11y_.NETCore3.0(WPF)_WPFExpenseItStandAlone_ScreenReader: ScreenReader reads repetitive information about the button "Create Expense Report".

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#1461]
Copied from VSO [951722](https://devdiv.visualstudio.com/DevDiv/_queries/edit/951722)

Check out Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

Environment Details:
Application Name: .NET Core 3.0 (WPF)

.NET Core SDK version:  3.0.100-preview8-013442
Windows Version: Windows10

ScreenReader Version: Narrator, NVDA 2019.1.1

Pre-requisite:

1) Download the latest .NET Core 3 daily build by going to this link.
2) Install Windows (x86 or x64) versions of sdk listed under Master (3.0.x Runtime) by clicking "Installer" link. 

Repro Steps:

1) Run exe file for "ExpenseItDemo" from the build app folder provided.
2) Main Window for "ExpenseItDemo" solution will appear. ​
3) Start ScreenReader and move to "Create Expense Report" button.

Actual:

ScreenReader reads repetitive information about the button "Create Expense Report".

It reads the Name, Accelerator key, Help Text values which are all same. 

This issue has been observed both in Narrator and NVDA.

Expected:

ScreenReader should not read repetitive information about the button "Create Expense Report". Tooltip can be removed for the controls with labels. 

User Impact:

ScreenReader users will get repetitive information about the button "Create Expense Report" which can be disgusting while using the application. 

Recommendations:

Please refer to below URL which is repository for accessibility bug fixes.

https://microsoft.sharepoint.com/teams/msenable/Pages/Home.aspx

MAS Reference:

MAS 1.3.1

https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

MAS 4.2.1 
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a12f3779-bdf1-40c2-bbcc-0e314ea94858}

**Comment by arpitmathur** [comment]
This is not a framework issue. The sample app developer has defined various properties on the control that are being read out via Narrator. This is expected behavior.
