### ISSUE TITLE
A11y_.NETCore3.0(WPF)_WPFBrush_LinearGradient-InteractiveExample_ScreenReader: screen reader  focus is not going on the text which is inside the Markup expandable group.

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#1469]
Copied from VSO [956749](https://devdiv.visualstudio.com/DevDiv/_queries/edit/956749/)

Check out Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

Environment Details:

Application Name: .NET Core 3.0 WPF

.NET Core SDK version:  3.0.100-preview8-013442
Windows Version: Windows10

Screen Reader Vesion : Narrator, NVDA 2019.1.1

Pre-requisite:

1) Download the latest .NET Core 3 daily build by going to this link.
2) Install Windows (x86 or x64) versions of sdk listed under Master (3.0.x Runtime) by clicking "Installer" link.

Repro Steps:

1) Run exe file for "Brushes" from the build app folder provided.
2) Main Window for "Brush Examples" solution will appear.​
3) Navigate to "Gradient Examples" option from left navigation and hit enter key.​
4) Navigate to "Linear Gradient Brush Example" option and hit enter key.​
5) Navigate to "Interactive Examples" option and hit enter key.  ​
6) Main window for "Interactive Examples" option will appear.
7) Start screen reader.
8) Navigate Markup expandable group

Actual:

Nvda Focus is not going on the text which is inside the Markup expandable group.

Expected:

Screen reader should read the inside text of the Markup expandable group

User Impact:

Screen reader user may not able to access this information.

Recommendations:

Please refer to below URL which is repository for accessibility bug fixes.

https://microsoft.sharepoint.com/teams/msenable/Pages/Home.aspx

MAS Reference:

MAS 1.3.1

https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Comment by arpitmathur** [comment]
This issue doesn't reproduce in Narrator. WPF is exposing the reported text to the automation tree. This is a NVDA bug.
