### ISSUE TITLE
dotnet-wpf-int builds fail due to ResXCodeFileGenerator regression in recent dev16.3p2 builds

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#1492]
WPF uses `ResXFileCodeGenerator `it its builds. We have a resx with entries like this (Documents.resx)

```xml
  <data name="Invalid_35x35" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>Invalid_35x35.png;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</value>
  </data>
```

It generates getters that should look like this: 

``` C#
        internal static System.Drawing.Bitmap Invalid_35x35 {
            get {
                object obj = ResourceManager.GetObject("Invalid_35x35", resourceCulture);
                return ((System.DrawingBitmap)(obj));
            }
        }
```

Suddenly, as of some recent VS build, `ResXFileCodeGenerator `is starting to emit files with getters that are instead like this (not the return type – they are plain `object`). 

``` C#
        /// <summary>
        ///   Looks up a localized resource of type System.Object similar to Microsoft.Build.Tasks.ResourceHandling.LiveObjectResource.
        /// </summary>
        internal static object Invalid_35x35 {
            get {
                object obj = ResourceManager.GetObject("Invalid_35x35", resourceCulture);
                return ((object)(obj));
            }
        }
```

Here is a standalone repro that illustrates the problem. Build with commandline msbuild (not `dotnet`, use `msbuild`, VS version dev16.3p2 29128.8.master, Int Preview). 

After building, open `obj\Debug\netcoreapp3.0\MS.Internal.Documents.Resources.cs` and you can see getters that return `object` instead of specifc types. 

[resx-codegen-issue.zip](https://github.`com/dotnet/wpf/files/3453868/resx-codegen-issue.zip)

**Comment by rainersigwald** [comment]
microsoft/msbuild#4588 should deliver a fix for this with no change required in WPF.

**Comment by vatsan-madhavan** [comment]
Opened an issue to track undoing the workaround put in here - https://github.com/dotnet/wpf/issues/1588. closing since the issue has been fixed.
