### ISSUE TITLE
System.Windows.Point not available in System.Windows

### ISSUE THREAD

**Issue by jdbriaris** [dotnet/wpf#1496]
* .NET Core Version: 3.0.100-preview7-012821
* Windows version: Windows 10, Version 1903, Build 18362.239
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
 
 **Problem description:**
I have a separate "pure" .NET Core 3 library (i.e. no reference to Microsoft.WindowsDesktop.App) that I'm using to define my View Models. Within that library I have access to the geometry classes, e.g. [ArcSegment](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.arcsegment?view=netframework-4.8), available in the `System.Windows.Media namespace`. However, if I then attempt to create an [ArcSegment](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.arcsegment?view=netframework-4.8) by defining its [ArcSegment.Point](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.arcsegment.point?view=netframework-4.8) property, I get the build error

`Error	CS0234	The type or namespace name 'Point' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)`

Both the docs for [ArcSegment.Point](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.arcsegment?view=netframework-4.8) suggest that it applies to .NET Core Preview 7, but the docs for [Point](https://docs.microsoft.com/en-us/dotnet/api/system.windows.point?view=netframework-4.8) does not suggest such support.

If I reference the package `Microsoft.WindowsDesktop.App` I have access to [Point](https://docs.microsoft.com/en-us/dotnet/api/system.windows.point?view=netframework-4.8) and can successfully build. However, I'd want to keep this a pure .NET Core 3 library.

Further explanation on this [SO question](https://stackoverflow.com/questions/57295940/net-core-3-wpf-and-paths).
 
 **Expected behavior:**
I'd expect to be able to use the geometry classes specified in `System.Windows.Media` in a .NET Core 3 library.

**Comment by weltkante** [comment]
You may need to add `<UseWPF>true</UseWPF>` to the project files property section and not just reference the package. Thats because the package supports both WinForms and WPF and you need to specify which you want (you can specify both, but note that WinForms property is `<UseWindowsForms>true</UseWindowsForms>`)

**Comment by jdbriaris** [comment]
@weltkante Good to know. Albeit, the issue here seems to be a discrepancy in the docs, or that I'm misinterpreting them, i.e., classes like `ArcSegment` are supposedly supported in `.NET Core 3 Preview 7` yet one of their fundamental components, the `Point` Struct, is not.

**Comment by weltkante** [comment]
@jdbriaris I had misread how your comment about the package reference, so removed that comment, apparently not before you started an answer ;)

**Comment by vatsan-madhavan** [comment]
@grubioe, i think this is a bug after all, albeit one with documentation. This is closely related to https://github.com/dotnet/dotnet-api-docs/issues/2602. 

@mairaw, do we have an update on https://github.com/dotnet/dotnet-api-docs/issues/2602? It seems to me that in addition to not producing intellisense XML's for WindowsBase, dotnet/api-docs is also failing to produce docs for WidnowsBase.dll. I want to reiterate that the copy of WindowsBase in Microsoft.NetCore.App is not the canonical version. If you must drop one, please drop that and instead start producing docs and intellisense XML's for the version of WindowsBase.dll in Microsoft.WindowsDesktop.App.

**Comment by vatsan-madhavan** [comment]
@jdbriaris, the problems with documentation notwithstanding (thanks for bringing this to our attention - its greatly appreciated!), you will not be able to use WPF types without referencing `Microsoft.WindowsDesktop.App`. This includes `System.Windows.Point,` as well as `System.Windows.Media.ArcSegment`. 

There are some exceptions to this generality - e.g., some types in `System.IO.Packaging` namespace - that will be available in `Microsoft.NetCore.App`, and will also continue to be available in `Microsoft.WindowsDesktop.App` through type-forwards in `WindowsBase.dll` (as they used to in .NET Framework). 

The general idea is that WPF and WinForms reside in `Microsoft.WindowsDesktop.App`.

**Comment by jdbriaris** [comment]
@vatsan-madhavan thanks for the update. That does make sense - I did think it a little peculiar that I could use `System.Windows.Media.ArcSegment` in a pure `.NET Core` library.
