### ISSUE TITLE
System.Windows.Forms.FolderBrowserDialog no longer compiles in WPF app

### ISSUE THREAD

**Issue by skanvk15** [dotnet/wpf#1503]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

* Windows version: (`winver`)
Windows 10

* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No
N/A

 
 
 **Problem description:**
I used to be able to use the Win Forms folder dialog in .NET Core 3.0 Preview version WPF app, like this:
`System.Windows.Forms.FolderBrowserDialog folderBrowserDialog;`
But with latest .NET Core 3.0 Preview version I get compiler error.

 **Actual behavior:** 
 I get this compiler error:
error CS0234: The type or namespace name 'Forms' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)

 **Expected behavior:**
No error
 
 **Minimal repro:**
 Create new .NET Core WPF app and update MainWindow constructor like this:
`public MainWindow()
        {
            InitializeComponent();
            System.Windows.Forms.FolderBrowserDialog folderBrowserDialog;
        }`

**Comment by 0xd4d** [comment]
Make sure you see this in your csproj file:
```csproj
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
```

**Comment by skanvk15** [comment]
Thanks that fixed it!

**Comment by msyusuf** [comment]
Thanks, it fixed it for me too.
