### ISSUE TITLE
[DRT] Fix DrtFlow failures

### ISSUE THREAD

**Issue by rladuca** [dotnet/wpf#1510]
DrtFlow()
OS: 2k8R2
Log Link: See Test Results Emails

**Comment by grubioe** [comment]
@ojhad - can you look into this one?  Thanks

**Comment by ojhad** [comment]
Closing this issue because failure is only happening on OS that is no longer supported by .NET Core 3.0:
https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md
