### ISSUE TITLE
Generate xml documentation files for public WPF api

### ISSUE THREAD

**Issue by rogalmic** [dotnet/wpf#1531]
Would there be a possibity to include autogenerated C# xml documentation in github releases?

![image](https://user-images.githubusercontent.com/23117003/62428759-ac99f080-b705-11e9-9998-38c9dae160cc.png)

It would be good to have those for public part of WPF API...

**Comment by weltkante** [comment]
XML documentation isn't generated from the source code, its generated from the online docs and merged into the nuget package during the build.

**Comment by rogalmic** [comment]
OK, found in:
```
https://www.nuget.org/packages/Microsoft.WindowsDesktop.App/3.0.0-preview7-27912-14
```

Thanks for support...
