### ISSUE TITLE
CS0118 if folder name ends with "Application"

### ISSUE THREAD

**Issue by livarcocc** [dotnet/wpf#154]
@taori commented on [Sat Dec 08 2018](https://github.com/dotnet/cli/issues/10454)

## Steps to reproduce
- create folder like Company.Desktop.Application
- enter folder
- dotnet new wpf
- dotnet run

## Expected  behavior
Application runs

## Actual behavior
Application can't compile because of CS0118

## Environment data
`dotnet --info` output:

dotnet --info

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Alle Rechte vorbehalten.

.NET Core SDK (gemäß "global.json"):
 Version:   3.0.100-preview-009812
 Commit:    e3abf6e935

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-009812\

Host (useful for support):
  Version: 3.0.0-preview-27122-01
  Commit:  00c5c8bc40

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009812 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27122-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27128-4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

---

@livarcocc commented on [Sun Dec 09 2018](https://github.com/dotnet/cli/issues/10454#issuecomment-445560538)

cc @jaredpar 

---

@jaredpar commented on [Mon Dec 10 2018](https://github.com/dotnet/cli/issues/10454#issuecomment-445908513)

@taori can you post the error message please + the source for the main file? 

Guessing what is happening here is the namespace being generated here is `Company.Desktop.Application` and the code spit attempts to use a type named `Application` from the framework in the code spit. Essentially:

``` csharp
var x = new Application();
```

That would result in that particular error.

If I'm right that's really an issue for templates to solve. The compiler is behaving properly. But I think we'll either be faced with a choice of:

1. Keep the templates simple and with standard C# code spit
1. Make the templates resilient to issues like this by doing using aliases and lots of `::global` qualifiers. 

---

@taori commented on [Mon Dec 10 2018](https://github.com/dotnet/cli/issues/10454#issuecomment-445940191)

@jaredpar 

##generated app.xaml.cs

```
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;

namespace test.Application
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : Application
    {
    }
}

```

`::global` seems like a great idea to solve it. 

---

@jaredpar commented on [Mon Dec 10 2018](https://github.com/dotnet/cli/issues/10454#issuecomment-445985641)

@taori thanks for providing the source there. 

> ::global seems like a great idea to solve it.

That will be up to the template owners to decide. I'm not sure what repository they live in (@livarcocc ?). 

My 2 cents: there will always be a way to break templates. There needs to be a balance between robustness and simplicity. My gut is to vote against anything that has `::global` in it on the basis it's probably a tad too far on the robust side of templates. 

---

@taori commented on [Mon Dec 10 2018](https://github.com/dotnet/cli/issues/10454#issuecomment-446023200)

> 
> 
> @taori thanks for providing the source there.
> 
> > ::global seems like a great idea to solve it.
> 
> That will be up to the template owners to decide. I'm not sure what repository they live in (@livarcocc ?).
> 
> My 2 cents: there will always be a way to break templates. There needs to be a balance between robustness and simplicity. My gut is to vote against anything that has `::global` in it on the basis it's probably a tad too far on the robust side of templates.

Yeah. That level of robustness is overkill indeed. I am sure anyone would figure out how to fix it, since the diagnostic points it out just fine. Just thought it might be interesting if this is a case which can happen but was overlooked until now.

---

@livarcocc commented on [Tue Dec 11 2018](https://github.com/dotnet/cli/issues/10454#issuecomment-446291414)

Moving this issue to the wpf repo. They can decide to change the template there. Though, I also vote for simplicity here.

**Comment by ptorr-msft** [comment]
Per discussion above, we'd rather keep the templates simple than make them robust against all possible project names. Thanks for reporting the issue though; if this turns out to be a common scenario and more people get tripped up by this, we can revisit.

**Comment by dotMorten** [comment]
You don't need to use `global::` though. You could just fully qualify the inheritance.
`public partial class App : System.Windows.Application`
