### ISSUE TITLE
 XAML Behaviors SDK

### ISSUE THREAD

**Issue by elite-works** [dotnet/wpf#155]
* .NET Core Version: 3.0.100-preview-009812
* Windows version: Windows 10 version 1809 build 17134.441
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Don't Know

 **Problem description:**
The XAML behaviors is not supported/implemented in .NET Core 3.0.100-preview-009812, either by reference to "Microsoft.Expression.Interactions" and "System.Windows.Interactivity"
<pre>
xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
xmlns:ie="http://schemas.microsoft.com/expression/2010/interactions"
</pre>
Or by "Microsoft.Xaml.Behaviors.Wpf" NuGet package (v1.0.1), and referencing "Microsoft.Xaml.Behaviors"
<pre>
xmlns:i="http://schemas.microsoft.com/xaml/behaviors"
</pre>

 **Actual behavior:** 
 Using the first method results in the below error:
<code>
___error MC3074:___ The tag 'LaunchUriOrFileAction' does not exist in XML namespace 'http://schemas.microsoft.com/expression/2010/interactivity'.
</code>

And the second method result is:
<code>
___warning NU1701:___ Package 'Microsoft.Xaml.Behaviors.Wpf 1.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.
</code>

 **Expected behavior:**
 Ability to use XAML behaviors, like the simple one below:

```xml
        <Button Content="Click Me!" >
            <i:Interaction.Triggers>
                <i:EventTrigger EventName="Click">
                    <i:LaunchUriOrFileAction Path="https://github.com/dotnet/wpf/" />
                </i:EventTrigger>
            </i:Interaction.Triggers>
        </Button>
```

 **Minimal repro:**

**Comment by dotMorten** [comment]
Looks like duplicate of:
https://github.com/Microsoft/XamlBehaviorsWpf/issues/13
https://github.com/Microsoft/XamlBehaviorsWpf/issues/8

**Comment by elite-works** [comment]
> The NU1701 warning tells you what you need to know.
> 
> Looks like duplicate of:
> [Microsoft/XamlBehaviorsWpf#13](https://github.com/Microsoft/XamlBehaviorsWpf/issues/13)
> [Microsoft/XamlBehaviorsWpf#8](https://github.com/Microsoft/XamlBehaviorsWpf/issues/8)

Sorry, Yes, It is a duplicate of [#13](https://github.com/Microsoft/XamlBehaviorsWpf/issues/13)
