### ISSUE TITLE
Clicking a TreeView item while the tooltip is visible results in System.FormatException: 'Token is not valid.'

### ISSUE THREAD

**Issue by matt-entrekin** [dotnet/wpf#1550]
* .NET Core Version: 3.0 Preview 7
* Windows version: Windows 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
 
 **Problem description:**
Clicking on an item in a TreeView while a tooltip is visible causes an exception to be thrown.

 **Actual behavior:**
System.FormatException
  HResult=0x80131537
  Message=Token is not valid.
  Source=PresentationCore
  StackTrace:
   at MS.Internal.Parsers.ParseBrush(String brush, IFormatProvider formatProvider, ITypeDescriptorContext context) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Parsers.cs:line 298
   at System.Windows.Media.Brush.Parse(String value, ITypeDescriptorContext context) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Brush.cs:line 84
   at System.Windows.Media.BrushConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value) in /_/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Generated/BrushConverter.cs:line 124
   at System.ComponentModel.TypeConverter.ConvertFromInvariantString(String text)
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.TypeServices.PropertyValueHelper.GetValueAsConvertableString(Object value, TypeConverter converter, Type targetType)

 **Expected behavior:**
The user should be able to click tree items while a tooltip is visible without an exception being thrown.
 
 **Minimal repro:**
1. Create a .NET Core WPF app with a TreeView that has an item with a tooltip
```xaml
<TreeView>
  <TextBlock Text="text" ToolTip="tooltip"/>
</TreeView>
``` 
2. Hover over the item with the tooltip
3. While the tooltip is visible, click on the tree item

**Comment by weltkante** [comment]
I've seen this regularly when the debugger is attached. You have `Microsoft.VisualStudio.DesignTools.WpfTap` in the stack trace. Do you have by any chance set the debugger to "break on first exception"? If so try to resume the debugger (or ignore the exception). This always worked when I had these exceptions. I think the debugger is catching them.

**Comment by matt-entrekin** [comment]
![image](https://user-images.githubusercontent.com/1117585/62573124-e92b3080-b85a-11e9-8fe4-430dbb1084f3.png)

I don't think I have that enabled. Is there another setting I should be looking for?

> I've seen this regularly when the debugger is attached

I verified that the exception only occurs when the debugger is attached.

**Comment by weltkante** [comment]
There is an exception settings panel outside the options (menu Debug/Windows/Exception Settings)

![grafik](https://user-images.githubusercontent.com/5845814/62574007-b9e6e480-b897-11e9-9754-4636c2a5d32b.png)

If you break on System.FormatException the Debugger will break even if the exception is caught by calling code. My workaround is to remove that checkbox for the time being. Causes you to miss legit FormatExceptions but when I have to debug those I just turn it back on. Not great but works.

**Comment by matt-entrekin** [comment]
@weltkante thanks, I forgot about those settings.

The exception is still caught by the debugger when I uncheck System.FormatException in Exception Settings.

![image](https://user-images.githubusercontent.com/1117585/62578660-4dec8800-b867-11e9-861a-323ff9cd68ee.png)

**Comment by grubioe** [comment]
@matt-entrekin  Can you log an issue in the [Visual Studio Developer Community]( https://developercommunity.visualstudio.com/content/problem/post.html?space=8)-  it will then be directed to the right Visual Studio team to troubleshoot?  By logging an issue there, the Visual Studio team will have more information to troubleshoot your issue.  
Thanks!

**Comment by matt-entrekin** [comment]
https://developercommunity.visualstudio.com/content/problem/683943/net-core-30-preview-7-clicking-a-treeview-item-whi.html
