### ISSUE TITLE
Theme assemblies cannot be referenced from XAML in latest SDK

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#1552]
This is related to #765, which primarily deals with the inability to reference theme assemblies for consumption in C#/VB etc. code. 

In recent preview8 builds, XAML like this no longer builds because the WPF theme assembles are no longer referenced by default by `Microsoft.WindowsDesktop`.

```XAML
... xmlns:theme="clr-namespace:Microsoft.Windows.Themes;assembly=PresentationFramework.Aero"

<theme:SystemDropShadowChrome>
       <HeaderedContentControl Padding="10" Foreground="#CCFFFFFF">
              <HeaderedContentControl.Header>

```

Given there is no way to reference these directly at build-time,  the theme assemblies are not complete unusable. 

This change was made by https://github.com/dotnet/core-setup/issues/7218, which was done in due to a miscommunication between the WPF and the SDK teams. We are working together to undo this change for .NET Core 3.0. 

Also related: https://github.com/dotnet/sdk/issues/3265
This issue tracks work in dotnet/sdk: https://github.com/dotnet/sdk/issues/3512

**Comment by vatsan-madhavan** [comment]
@rladuca the core-sdk build coming out today https://github.com/dotnet/core-sdk/pull/3907/checks?check_run_id=190165861 should have this fix. would you mind verifying and closing?

**Comment by rladuca** [comment]
I was able to build a simple project referencing `SystemDropShadowChrome` from different theme assemblies using `3.0.100-preview9-013756`.

Closing.
