### ISSUE TITLE
Adopt YAML stages based publishing and validation for DncEng\dotnet-wpf-test

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#1566]
See https://github.com/dotnet/wpf/issues/1564 for details. You can base the work on https://github.com/dotnet/wpf/pull/1565. 

The Arcade team has guidance available for the adoption of publishing via YAML Stages here: https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/YamlStagesPublishing.md

They will be tracking the status of repos adopting these templates here: https://github.com/dotnet/arcade/blob/master/Documentation/YamlStagesRepoStatus.md.

/cc @rladuca, @ojhad

**Comment by rladuca** [comment]
Internal PR: https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-test/pullrequest/3137?_a=overview
