### ISSUE TITLE
open source rest of managed WPF assemblies

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/wpf#1579]
Open source the rest of the managed assemblies:
1. PresentationUI
2. System.Windows.Presentation
3. System.Windows.Controls.Ribbon
4. System.Printing
5. Themes
   - PresentationFramework.Aero
   - PresentationFramework.Aero2
   - PresentationFramework.AeroLite
   - PresentationFramework.Classic
   - PresentationFramework.Luna
   - PresentationFramework.Royale

The following steps need to be done to ensure this is done right:
1. Add new OSS license headers
2. Scan/clean code using Policheck
3. Verify no IL differences when building in the new repo
4. Validate both dotnet/wpf and dotnet-wpf-int builds correctly consume the nuget packages

**Comment by stevenbrix** [comment]
Here is the internal PR that removes the code: https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/2583?_a=overview

**Comment by grubioe** [comment]
Reviewed during 8/13 .NET Tactics
