### ISSUE TITLE
Re-enable SDL validation job in build-YAML

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#1585]
_Originally posted by @sunandabalu in https://github.com/dotnet/arcade/issues/3565#issuecomment-520018790_

> PR to add pool to execure-sdl.yml is merged. Closing this issue.

Enable SDL Validation in our build YAML when this change flows into dotnet/wpf (and also in dotnet-wpf-int) - this should just require changing a bool from false -> true.

https://github.com/dotnet/wpf/blob/6d15ef7526d1bcdd0f9b42126aa22ed32e2e7b55/azure-pipelines.yml#L79-L83

SDL validation is a requirement for GA - this **must** be done either in preview9.

**Comment by rladuca** [comment]
Internal PR: https://dnceng.visualstudio.com/internal/_git/dotnet-wpf-int/pullrequest/2650

**Comment by rladuca** [comment]
Test Builds:

Internal: https://dnceng.visual studio.com/internal/_build/results?buildId=310246
GitHub: https://dnceng.visualstudio.com/internal/_build/results?buildId=310562

**Comment by rladuca** [comment]
We have about 1500 policheck style issues to deal with and/or get exemptions for.

I'll file a separate issue to address these.
