### ISSUE TITLE
Build failure in SortDescriptionCollection

### ISSUE THREAD

**Issue by wjk** [dotnet/wpf#1593]
* .NET Core Version: 3.0.100-preview9-013709
* Windows version: 18362.239
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No, this is a build error

## Problem description

I clone the repo, and run `build.cmd`. It builds a few projects, then fails with the following error (line-wrapped for readability):

```
System\ComponentModel\SortDescriptionCollection.cs(138,75): error CS8614:
Nullability of reference types in type of parameter 'index' of
'void Collection<SortDescription>.RemoveAt(int index)' doesn't match implicitly
implemented member 'void IList.RemoveAt(int index)'.
[D:\Projects\dotnet-wpf\src\Microsoft.DotNet.Wpf\src\WindowsBase\WindowsBase.csproj]
```

What's weird is that we don't use nullable reference types anywhere in WPF that I know of, nor does it appear to be used in System.Private.CoreLib, which is where IList is defined, not to mention `int` isn't even a reference type to begin with!

**Minimal repro:**
 
1. Checkout 448bc7130a12144e44acb0eceba5e5bcb2c03d05
2. Run `restore.cmd` in repo root
3. Run `build.cmd` in repo root.

## Other information

When I open Microsoft.DotNet.Wpf.sln in VS2019, the IntelliSense doesn't work right. I opened SortDescriptionCollection.cs in the editor to try to investigate the build break, and references to classes not in the current solution are not recognized. (For example, the words Collection and INotifyCollectionChanged in `public class SortDescriptionCollection : Collection<SortDescription>, INotifyCollectionChanged` are not colored, and pressing F12 on them gives a generic navigation-failed error message.) However, no class-not-found errors are generated by the compiler or by IntelliSense.

Furthermore, the Dependencies node for the WindowsBase project and all projects that reference it show error icons on all sub-entries. No error messages appear in the Error List or Output panes, and `Restore.cmd` succeeds with no issues. The only projects that restore correctly as far as VS is concerned `System.Xaml` and `System.Xaml-ref`. I don't suspect that this is caused by the same problem as is my build failure, but unless this issue is also resolved I cannot effectively contribute to WPF. Thanks for looking into this for me!

**Comment by vatsan-madhavan** [comment]
I suspect you are hitting https://github.com/dotnet/roslyn/issues/37281.  

Try with Dev16.3 builds if they are available publicly, or try building with `/p:LanguageVersion=7.3`. 

I haven’t tried the latter and don’t know how well it works in our repo - I only know that Dev16.3 builds fixes this problem. These [release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview) seem to indicate that 16.3 Preview 1 is available to the public...

**Comment by wjk** [comment]
Setting LangVersion to 7.3 does appear to fix the immediate problem I've ran into; the build then breaks on a different issue in PresentationFramework (caused by overriding the language version). The IntelliSense issue is now a bit spotty; it works for some assemblies (such as WindowsBase), but not others (such as PresentationCore). I'll look more into it tomorrow. Thanks!

**Comment by wjk** [comment]
I successfully installed 16.3 Preview 1, after which the solution builds with no issues. IntelliSense also appears to be working fully now that the entire solution has binaries on disk for Roslyn to consume. I have reverted my LangVersion=7.3 workaround. Thanks for your help @vatsan-madhavan!
