### ISSUE TITLE
WindowsBase types are missing documentation & intellisense XML's

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#1597]
[dotnet/dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs) does not seem to be generating documentation and intellisense XML's for WindowsBase.dll. 

Looking for documentation for `System.Windows.Point` shows this error:

```
The requested page is not available for .NET Core 3.0 Preview 7. You have been redirected to the newest product version this page is available for.
```

It seems like the docs repo is generating data for the shim DLL that is built out of corefx (Microsoft.NetCore.App), and in turn, that is _hiding_ types from the real WindowsBase.dll (Microsoft.WindowsDesktop.App) 

https://github.com/dotnet/dotnet-api-docs/issues/2602 was opened a while back, but has seen very little movement. 

We should treat this as an exist-criteria blocker for .NET 3.0 release. As part of documentation completion (which is expected to be done by Aug 16th), we should ensure that the docs repo owners get this fixed. 

/cc @mairaw, @carlossanlop, @safern
/cc @grubioe

**Comment by safern** [comment]
This should be fixed for Preview8. The WindowsBase.dll was overlapping with the one from .NET Core which is a pure shim, for Preview8 I fixed this when generating the drop.

**Comment by grubioe** [comment]
Thanks @safern can we close this?

**Comment by safern** [comment]
> Thanks @safern can we close this?

I would say to wait until @mairaw is done with generating the docs for Preview8 and we can actually see the WindosBase types in the docs site.

**Comment by mairaw** [comment]
Yep, leave it open until the expected behavior is confirmed. My CI run failed last night 😢 but the engineering team already took care of a bug and it's running again.

**Comment by vatsan-madhavan** [comment]
This has been fixed now.

**Comment by vatsan-madhavan** [comment]
Reopening - the docs were fixed, but intellisense XML's weren't. Will be sending out a PR shortly.
