### ISSUE TITLE
Improve I18N support

### ISSUE THREAD

**Issue by Genteure** [dotnet/wpf#160]
- The [Globalization and Localization Guide](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/globalization-and-localization) is too confusing. After reading mutiple times, I still don't understand what exactly should I do.
- The link to the tool "LocBaml" was dead. `archive.msdn.microsoft.com` doesn't even point to a IP address.
- As stated on [this page](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-localize-an-application): _The LocBaml tool is not a production-ready application._ We should have a production-ready localization solution ready to use, you can't expect everyone make their own tools.

If I misunderstood something please point me to the right direction, thank you.

**Comment by stevenbrix** [comment]
@Genteure are you able to find a sample on the https://github.com/Microsoft/WPF-Samples repo that help you out? If not, maybe it would be worth filing an issue there to provide one. Then we can work on updating our documentation to help people getting started.

The information on the docs is incredibly detailed, and is probably more information than needed to get started.  It might be more appropriate for people who already have some background information, which in itself is a problem. I'd recommend finding a helpful tutorial online like [this](http://www.thebestcsharpprogrammerintheworld.com/2017/07/26/localizing-a-wpf-program-using-c/) and see if that helps you out. I'm hopeful nothing substantial has changed in .NET Core that makes this article outdated.

If you could share some more detail on your thoughts about the documentation that would be really helpful (i.e what you find confusing, and what are some things you'd like to see?)

**Comment by Genteure** [comment]
https://github.com/Microsoft/WPF-Samples is not helpful because it is using the now unavailable tool "LocBaml".

---

It's confusing mainly because of the the tool "LocBaml", mentioned throughout the documentation is unavailable. The tool is also being used by at least two [samples](https://github.com/Microsoft/WPF-Samples/tree/master/Globalization%20and%20Localization).

---

[WPF Globalization and Localization Overview #Examples of WPF Localization](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/wpf-globalization-and-localization-overview#examples-of-wpf-localization)

> ### Localizing the Run Dialog
>
> #### Parse
>
> ... Using LocBaml, run the following to parse: **LocBaml /parse RunDialog.resources.dll /out:** to generate a "RunDialog.resources.dll.CSV" file. ...

---

[How to: Localize an Application #Use LocBaml to Parse a File](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-localize-an-application#use-locbaml-to-parse-a-file)

> 2. To parse the satellite assembly file and store the output as a .csv file, use the following command:
>
> **LocBaml.exe /parse HelloApp.resources.dll /out:Hello.csv**

---

The page [How to: Localize an Application](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-localize-an-application) says:

> **(!) Note**
>The LocBaml tool is not a production-ready application. It is presented as a sample that uses some of the localization APIs and illustrates how you might write a localization tool.

I personally think having a tool that is ready for everyone to use would be better. Also, since I haven't seen a example using the `System.Windows.Markup.Localizer` API yet, I don't know how would those classes work with each other to form a localization tool.

---

Now I think about it, I should probably open this issue on the dotnet/docs repo instead of here. It doesn't really have anything to do with WPF being ported to .NET Core. 

I just realized this technically is a duplicate of https://github.com/dotnet/docs/issues/3623

**Comment by Genteure** [comment]
Closing because #612 is more well written and useful.
