### ISSUE TITLE
Update private C++ toolset to 0.0.0.7

### ISSUE THREAD

**Issue by rladuca** [dotnet/wpf#1604]
A new drop of private C++ tooling is available and tested on the WPF repositories (both internal and external).

We should update to these tools in both repositories.

**Comment by vatsan-madhavan** [comment]
After this is fixed, the following dangling type-refs would still be left: 


- Release Builds: 
  - DirectWriteForwarder:
    - `[mscorlib] System.Runtime.CompilerServices.AssemblyAttributesGoHereM`
    - `[mscorlib] System.Runtime.CompilerServices.AssemblyAttributesGoHere`  
  - System.Printing
    - All the same problems observed in DirectWriteForwarder
    - Additional:`[System.Runtime.CompilerServices.VisualC] System.Runtime.CompilerServices.IsVolatile`
- Debug Builds:
  - DirectWriteForwarder
    - `[mscorlib] System.Runtime.CompilerServices.SuppressMergeCheckAttribute` 
    - `[System.Runtime] System.Runtime.CompilerServices.AssemblyAttributesGoHere`
    - `[mscorlib] System.Runtime.CompilerServices.AssemblyAttributesGoHereM`
    - `[mscorlib] System.Runtime.CompilerServices.AssemblyAttributesGoHere`
  - System.Printing
    - All the same problems observed in  Debug/DirectWriteForwarder
    - Additional: `[System.Runtime.CompilerServices.VisualC`

**Comment by grubioe** [comment]
Reviewed during 8/13 .NET Tactics
