### ISSUE TITLE
one SingleInstance WPF by using WindowsFormsApplicationBase with App.xaml

### ISSUE THREAD

**Issue by godpit** [dotnet/wpf#1611]
There are some application resources named of ResourceDictionary with App.xaml, the App.xaml.cs extend Application. There is an error that can not find static resource with starting WPF. However, I added the resources by loading dynamically within the App.xmal.cs construction.

 var resources = this.Resources.MergedDictionaries;
            resources.Add(new ResourceDictionary()
            {
                Source = new Uri("pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.Teal.xaml", UriKind.RelativeOrAbsolute)
            });

It is ok, but there is an error that can not find the Customized  Locator resource with the Customized  resource.
     <ResourceDictionary>
                    <vm:ViewModelLocator x:Key="Locator" d:IsDataSource="True"  />
                </ResourceDictionary>

Q1: how to solve the Customized  resource by loading dynamically ?
Q2: how to create one SingleInstance WPF Application by using WindowsFormsApplicationBase with App.xaml?

**Comment by godpit** [comment]
![App xaml](https://user-images.githubusercontent.com/34534331/62960618-9c80c000-be2d-11e9-8fc4-cf9722e26d86.png)
![App xaml cs](https://user-images.githubusercontent.com/34534331/62960623-a1457400-be2d-11e9-80a4-f5e07f8c1203.png)

**Comment by grubioe** [comment]
@godpit can you provide a minimum repro (either a GitHub Repo or a .Zip)?  Also, can you log a separate issue for your second question?

Thanks
