### ISSUE TITLE
Global namespace definition

### ISSUE THREAD

**Issue by danielmeza** [dotnet/wpf#165]
It will be grate if we can define namespaces to be used across all views like in Razor with the _ViewImports.cshtml

**Comment by dotMorten** [comment]
@danielmezza I don't see how this could work beyond the assembly level, and we already have a way to do that

**Comment by dotMorten** [comment]
An even fancier prefix-less way to do it, is piggy-backing on the default prefixless namespace:
https://github.com/dotMorten/UniversalWPF/blob/master/src/UniversalWPF.RelativePanel/Properties/AssemblyInfo.cs#L29-L30

This allows you to simply use `<MyControl />` without having to add any extra prefixes in the header. Of course this should be used with great caution as you could get into a case where multiple classes with the same name would clash.

**Comment by danielmeza** [comment]
@stevenbrix  Yes it meet the necessity, and @dotMorten nice info. this issue can be closed.
