### ISSUE TITLE
XAML References to Microsoft.Windows.Themes failing to build in Preview 8

### ISSUE THREAD

**Issue by nick-beer** [dotnet/wpf#1655]
.NET Core 3.0 Preview 8

 
 
 **Problem description:**
Updating to Preview 8 broke our build that was working with Preview 7.  At least some references to items in PresentationFramework.Aero (such as Microsoft.Windows.Themes.SystemDropShadowChrome) cause the build to fail with errors like:
`The tag 'SystemDropShadowChrome' does not exist in XML namespace 'clr-namespace:Microsoft.Windows.Themes;assembly=PresentationFramework.Aero'`
 
 **Minimal repro:**
 Add a reference to SystemDropShadowChrome in the `dotnet new wpf` template:

```xml
<Window x:Class="temp_wpf.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:temp_wpf"
        xmlns:themes="clr-namespace:Microsoft.Windows.Themes;assembly=PresentationFramework.Aero"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <themes:SystemDropShadowChrome><Button>Hello</Button></themes:SystemDropShadowChrome>
    </Grid>
</Window>

```

**Comment by rladuca** [comment]
This is a known issue that is already fixed in Preview 9 builds.

See https://github.com/dotnet/core-setup/pull/7601.

Please try a daily build of Preview 9 and confirm.

**Comment by nick-beer** [comment]
I just tried 3.0.100-preview9-013936 and the issue is resolved.  Thanks!

**Comment by Sybren-** [comment]
Code behind references seem to fail (Preview 9). Xaml references are working.

Given this code example:

`using Microsoft.Windows.Themes;`
`private static bool IsValidOriginalSource(object dragSource)
        {
            if (dragSource is ScrollBar || dragSource is ScrollChrome)
            {
                return false;
            }
        }`

Error: Error	CS0433	The type 'ScrollChrome' exists in both 'PresentationFramework.Aero, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

Do I have to work with 'extern alias' (there seems no support for this in .NET Core)?
How to solve the above issue?
