### ISSUE TITLE
Unable to print Text with StringFormat when using TextBlock as ContentTemplate in ContentControl

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#1663]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/662885/unable-to-print-text-with-stringformat-when-using.html)._

---
<p><a href="https://developercommunity.visualstudio.com/storage/attachments/85228-printingdemo.zip">printingdemo.zip</a>I tried to print page number with StringFormat (StringFormat=&quot;Page {0} of&quot;) But it does not print text when setting the TextBlock as a content template of Content control. The page number is not only printing in below environment alone,Meanwhile, it works fine in <strong>Windows 10. </strong>Please look onto this and provide the solution.</p><p><strong>Windows details: Windows 7, Windows Server 2003, Windows Server 2008</strong></p><p><strong>Printer details: Canon MF5900 Series UFRII LT</strong></p><p>I use below code snippet for printing.</p><pre> private void Printbutton_Click(object sender, RoutedEventArgs e)
        {
            var fixedDoc = new FixedDocument();
            var printDialog = new PrintDialog();
            printDialog.PrintTicket.PageMediaSize = new PageMediaSize(300, 300);
            var pageControl = new PageControl();
            var pageContent = new PageContent();
            var fixedPage = new FixedPage();
            fixedPage.Children.Add(pageControl);
            ((IAddChild)pageContent).AddChild(fixedPage);
            fixedDoc.Pages.Add(pageContent);
            printDialog.PrintDocument(fixedDoc.DocumentPaginator, &quot;Printing&quot;);
            foreach (var page in fixedDoc.Pages)
            {
                page.Child.Children.Clear();
            }
        }
&lt;a href=&quot;https://developercommunity.visualstudio.com/storage/attachments/85178-printing-sample.zip&quot;&gt;printing-sample.zip&lt;/a&gt;
</pre>

---
#### Visual Studio Feedback System on 7/28/2019, 08:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Rob LaDuca [MSFT] on 7/29/2019, 04:36 PM: 

<p>I’ve run your repro on WIn10, Win7 + 4.7.2 and Win7 + 4.5.2.  From what I can tell, the output is identical in all of these configurations.</p>
<p>If you run with a different printer, does this repro?</p>
<p>What .NET version is installed on the machine (see <a target='_blank' href="https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed">https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed</a>)?</p>

#### Susmitha Sundar on 7/31/2019, 11:18 PM: 

<p>Hi,</p><p>I tested with different printers. This issue reproduced in  <strong>Canon MF5900 Series UFRII LT  </strong>printer only.</p><p>I used the below .Net version in my machine.</p><p><strong>GetVersionFromRegistry</strong></p><p>v2.0.50727  2.0.50727.5420  SP2<br>v3.0  3.0.30729.5420  SP2<br>v3.5  3.5.30729.5420  SP1<br>v4.0  <br>  Client  4.0.0.0</p><p><strong>Get45PlusFromRegistry</strong></p><p>.NET Framework Version: 4.7.2</p><p>Regards,</p><p>Susmitha S</p>

#### Gustavo Rubio Escudero [MSFT] on 8/5/2019, 02:20 PM: 

<p>Hi Susmitha,</p>
<p>As this issue is specific to Canon printers I’d suggest contacting Canon directly so that they can troubleshoot.</p>
<p>Best,<br>
Gustavo</p>

#### Gustavo Rubio Escudero [MSFT] on 8/5/2019, 02:23 PM: 

<p>We have determined that the feedback applies to another product. We recommend that you submit the feedback to Canon at <a target='_blank' href="https://www.usa.canon.com/internet/portal/us/home/support">https://www.usa.canon.com/internet/portal/us/home/support</a>. Thank you and we value your contribution to Developer Community.</p>

---
#### Susmitha Sundar solved on 8/19/2019, 02:27 AM, 0 votes: 

<p>Hi,</p><p>It's not related to Canon printers. This issue reproduced when I try to print the Print Header as PDF format, page number does not print in pdf file also. </p><p>I attached the video for your references. Can you please check the video and provide a solution for this?</p><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/88731-print-8ac85976.zip">print-8ac85976.zip</a></p><p>Regards,</p><p>Susmitha S</p>

**Comment by grubioe** [comment]
Susmita- Can you give us more information on the scenario that is affected and the type of application where this issue is found?   Thank you

**Comment by weltkante** [comment]
Taking a look at his attached example I cannot reproduce his original issue of StringFormat not working (page numbers are printing fine for me), but find two minor unrelated points:

* The `Part_PageHeader` has a top-margin of 200 which leads to the header never beeing visible (neither on Desktop nor Core). Changing it to a zero margin shows the header.
* When I create a new WPF Core application to copy/paste his code I have to manually add `[assembly: ThemeInfo(ResourceDictionaryLocation.None, ResourceDictionaryLocation.SourceAssembly)]` in order to pick up the style from the Generic.xaml -- why isn't this part of the application template? It certainly was on Desktop. I'll open a new issue for that regression since its probably not related to the OP issue in printing.

> This issue reproduced when I try to print the Print Header as PDF format, page number does not print in pdf file also.

I cannot reproduce this with the attached example, page number always prints for me, page header prints if I fix the margin. To diagnose the printing issue further the OP will need to provide more information.
