### ISSUE TITLE
Triage and fix Policheck issues reported for managed assemblies

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#1696]
Triage and fix (where appropriate0 Policheck issues reported for managed assemblies 

Bug query [internal link](https://devdiv.visualstudio.com/DevDiv/_queries?tempQueryId=81dc8da9-2a4a-42d7-8a60-b587fe29e0f6)

**Comment by vatsan-madhavan** [comment]
This shouldn't take more than a day to work through.

**Comment by grubioe** [comment]
Items found in internal query:  https://devdiv.visualstudio.com/DevDiv/_queries/query/30caea81-641d-410f-ae83-d601284a083b/

**Comment by vatsan-madhavan** [comment]
https://github.com/dotnet/wpf/pull/1705
