### ISSUE TITLE
How to debug a WPF applications ?

### ISSUE THREAD

**Issue by Simon-IT** [dotnet/wpf#1702]
Hi,
I've follow all the instructions from the developer-guide.md files. All is compiled well, but I cannot configure VS to debug a WPF application, because it doesn't take the pdb files compiled by the build.cmd. Can you help me ?

**Comment by stevenbrix** [comment]
Hey @Simon-IT, we can definitely help! Can you walk me through what you've done? Can you verify in the Modules window inside VS that the proper assemblies are being loaded?

**Comment by lindexi** [comment]
You can use [dnSpy](https://github.com/0xd4d/dnSpy) to debug the dotnet core WPF and you can decompile all .NET code.

**Comment by Simon-IT** [comment]
Hi Steven, sorry for the delay. This is my configuration:

- VS Community 2019 16.3.0 Preview 2;

- .Net SDKs:
    - 2.1.700 [C:\Program Files\dotnet\sdk]
    - 2.1.701 [C:\Program Files\dotnet\sdk]
    - 2.1.800 [C:\Program Files\dotnet\sdk]
    - 2.1.801 [C:\Program Files\dotnet\sdk]
    - 3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

- All dlls loaded (by Modules Window) are from "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview8-28405-07

These are some snapshot from VS:

![Immagine](https://user-images.githubusercontent.com/24890180/63697751-c965a780-c81d-11e9-93d5-302eb02f827e.png)

Starts from here. Thak you.

**Comment by Simon-IT** [comment]
Hi Steven. The point is this: I did nothing :-). I've read much documentation before to do this question, but I didn't find how to link the compiled pbd to the wpf solution. I think that I can use the copy-wpf.ps1 script. Is it right ?

**Comment by jespersh** [comment]
If I had to wager a guess, then I'm thinking you're linking up against microsoft's built preview8 instead of your own.
If you need to modify the Wpf code and contribute then you're on the right approach. If you're just looking to debug the microsoft built preview8, then you could look into Source Link in visual studio instead.

**Comment by Simon-IT** [comment]
Hi @jespersh. My goal is to contribute to wpf project. Moreover there are two bugs that blocks software development into my company.
For @stevenbrix. I've succesfully used the copy-wpf.ps1 script and I've included the copied dll into my wpf application. But there is a problem. During compilation a message appears into Output window:

> warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "DirectWriteForwarder", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

> warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "System.Printing", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project

I think that this warnings generates the exception during the parser of the xaml file:

> System.Windows.Markup.XamlParseException
>   HResult=0x80131501
>   Message=The type initializer for 'System.Windows.Window' threw an exception.
>   Source=PresentationFramework
>   StackTrace:
>    at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri) in D:\Sources\NetFoundation\dotnet\wpf\src\Microsoft.DotNet.Wpf\src\PresentationFramework\System\Windows\Markup\XamlReader.cs:line 401
> 
> Inner Exception 1:
> TypeInitializationException: The type initializer for 'System.Windows.FrameworkElement' threw an exception.
> 
> Inner Exception 2:
> TypeInitializationException: The type initializer for 'System.Windows.Documents.TextElement' threw an exception.
> 
> Inner Exception 3:
> TypeInitializationException: The type initializer for 'System.Windows.Documents.Typography' threw an exception.
> 
> Inner Exception 4:
> BadImageFormatException: Could not load file or assembly 'DirectWriteForwarder, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Tentativo di caricare un programma con un formato non corretto.

I think this should be a bug.

**Comment by stevenbrix** [comment]
@Simon-IT how are you publishing the app? Are you using `dotnet publish -r win-x86 --self-contained`? I just tested this out with Preview 9 and it is working fine.

If you could provide more detailed repro steps that might help us understand exactly what is going on. If you find any of the documentation in the [developer guide](https://github.com/dotnet/wpf/blob/master/Documentation/developer-guide.md) unclear or confusing, please let us know and we can work on making this easier for external contributors to get started, thanks!

**Comment by Simon-IT** [comment]
@stevenbrix I've published the app as you have mentioned, but it didn't work because the following packages are missing:

- Microsoft.NETCore.App.Runtime.win-x86;
- Microsoft.WindowsDesktop.App.Runtime.win-x86
- Microsoft.NETCore.App.Host.win-x86
- Microsoft.AspNetCore.App.Runtime.win-x86

I've Windows 10 1903 (build SO 18362.295) 64bit and I've have installed NET Core SDK Preview 8 64bit because it is the last available. Please note that I've just tryied this out with Preview 7 but the problem remain. Where are these packages ?

**Comment by stevenbrix** [comment]
@Simon-IT ahh yeah, you need to have a nuget.config file in you're repo with the correct feeds. There is an example one that you can copy and paste here: https://github.com/dotnet/core-sdk#installers-and-binaries

**Comment by Simon-IT** [comment]
@stevenbrix In the end I managed to connect the right pdb file and now I'm able to debug my application. I've follow your tips (publishing application and use of copy-wpf.ps1 script) and now I understood better the logic. It wasn't easy. Thank you

**Comment by weltkante** [comment]
@Simon-IT just a side note, this wasn't a problem about picking up PDB files, you weren't using the right DLLs.

**Comment by Simon-IT** [comment]
@weltkante you're right. The problem was the couple dll -> pdb. I created a simple wpf desktop app project by VS and obviusly it linked to the wpf "version" present in the net core sdk. My first problem was how to link to the wpf dll compiled by me. Moreover I had some problems during build.cmd execution, the resolved by git clean -xdf. I was in trouble....

**Comment by stevenbrix** [comment]
@Simon-IT, glad to hear you are finally unblocked! What was it that finally got things working for you? Please feel free to update the developer guide with any steps that you think are missing!

**Comment by stevenbrix** [comment]
@Simon-IT I'm going to close out this issue, please update the developer-guide if you think the instructions are unclear, or could be worded better!
