### ISSUE TITLE
WPF with .NET Core 3.0

### ISSUE THREAD

**Issue by betam4x** [dotnet/wpf#1708]
I tried out the latest version of VS 2019 and .NET Core 3.0 earlier with WPF, I believe .NET Core was preview 8.  I am running the latest version of Windows 10.  I have 2 4K monitors, and though WPF (and UWP) scaled fine when using the .NET framework, a new project I started with .NET core had completely broken HiDPI scaling under .NET Core.  I'm not sure where to report this.  It acted like I was still using a 96 dpi monitor, even though it's 144dpi with scaling (and 163dpi without).  I had just worked on another project prior to installing everything, and HiDPI scaling was working fine.  It was only when I tried .NET Core that things broke.

**Comment by vatsan-madhavan** [comment]
Can you share a self-contained, buildable, minimal, project, that can be used to reproduce the problem? Please ensure that it contains a `global.json` that indicates the SDK version used in your experiments. (`dotnet new globaljson --sdk-version` is a good way to create one)

Also, DXDiag output to show us your monitor and Windows configuration, along with a description of specific symptoms that are observed by you (perhaps an expected vs. observed list) that seem to suggest that High DPI is completely broken, would be of help.
