### ISSUE TITLE
RibbonWindow Min/Max/Close buttons not working

### ISSUE THREAD

**Issue by miloush** [dotnet/wpf#1722]
16.3.0 Preview 2.0, 18956.rs_prerelease
Reproduces on .NET Framework 4.8.03921.

1. Create a new project
2. Add reference to System.Windows.Controls.Ribbon
3. Change the root element from `Window` to `RibbonWindow` and code-behind class accordingly
4. Run

Expected: To be able to minimize/maximize/close the window using the system buttons in the non-client area.

Actual: The buttons respond to hover, but not to mouse down. Nothing happens when clicked. The window gets maximized/restored when any of the buttons are double-clicked as if double-clicking on the window title.

**Comment by miloush** [comment]
Fixed in OS. Confirmed in 18980.vb_release.190907-1301, possibly already in 18975 according to insider release notes.

**Comment by vpolson** [comment]
where can i get the updates or can please provide download link for the fixes.
