### ISSUE TITLE
.NET Core 3.0 embedded resources weren't compiled into executable

### ISSUE THREAD

**Issue by hez2010** [dotnet/wpf#1754]
* .NET Core Version: 3.0 preview 8
* Windows version: 1903 (18362.295)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**
Embedded resources weren't compiled into executable.
I added an image to a resx file Resource1.resx, and add the resource file to project file:
```xml
  <ItemGroup>
    <Compile Update="Resources\Resource1.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource1.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Resource1.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource1.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
```
Then I use this image in WPF `<Image Source="..." />`

 **Actual behavior:**
The image should display in my WPF app.
 
 **Expected behavior:**
The image can only display in Visual Studio XAML Designer.
 
 **Minimal repro:**
 
[WpfTest.zip](https://github.com/dotnet/wpf/files/3559450/WpfTest.zip)

**Update**
Not only WPF projects, all kinds of projects in .NET Core 3.0 cannot correctly use resource files.

**Comment by vatsan-madhavan** [comment]
@rainersigwald do you have any ideas what’s going on?

**Comment by rainersigwald** [comment]
Using the repro project, I also don't see an image when running the application, but I do see a byte-array resource embedded:

![image](https://user-images.githubusercontent.com/3347530/64052697-29718c00-cb45-11e9-9b4f-9cb2bf372d8c.png)

That matches what I'd expect from the resx:

```xml
  <data name="_592e202b3f70f28bd23fd9f830a8fb0a" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>592e202b3f70f28bd23fd9f830a8fb0a.jpg;System.Byte[], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
```

@vatsan-madhavan, can you take the next step? I don't know what

```xaml
<Image Source="/Resources/592e202b3f70f28bd23fd9f830a8fb0a.jpg"></Image>
```

boils down to in terms of interacting with the embedded resources.

**Comment by rainersigwald** [comment]
> Not only WPF projects, all kinds of projects in .NET Core 3.0 cannot correctly use resource files.

@hez2010, can you elaborate on this, please? The embedding process changed a lot in 3.0 but we're not aware of any specific problems. What else have you found not to work?

**Comment by hez2010** [comment]
@rainersigwald 
You can add some resx files into your project, and then run with Release configuration
```
dotnet run -c Release
```

Then you will find all resources becomes null.

A repro sample:
[ResourceFiles.zip](https://github.com/dotnet/wpf/files/3562094/ResourceFiles.zip)

**Comment by weltkante** [comment]
@hez2010 your original post repros also on Desktop Framework. It works in the designer because it looks in the file system of the project. Note that WPF doesn't use resx resources, you should use the WPF-style resource embedding. (`<Resource>` tag instead of `<EmbeddedResource>` and no resx file, just adding the image as a resource).

**Comment by hez2010** [comment]
As for the issue I mentioned in the top post, after I change build option of my images to `Resource`, it works as expected. 

As for the second issue `Not only WPF projects, all kinds of projects in .NET Core 3.0 cannot correctly use resource files`, I have opened another issue, see https://github.com/dotnet/roslyn/issues/38437

**Comment by vatsan-madhavan** [comment]
See related issue/discussion at https://github.com/dotnet/project-system/issues/4534

**Comment by vatsan-madhavan** [comment]
@hez2010 let's know if we can close out this issue now since you seem to have a path forward.

**Comment by hez2010** [comment]
Yes, this issue can be closed because it was caused by https://github.com/dotnet/project-system/issues/4534, not WPF itself.
