### ISSUE TITLE
EnableDefaultApplicationDefinition to false prevents Page's from working

### ISSUE THREAD

**Issue by onovotny** [dotnet/wpf#1758]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`) 3.0 preview 8

 
 
 **Problem description:**

If you set `EnableDefaultApplicationDefinition` to `false`, the other page XAML items get set to None instead of Page.
 
 **Actual behavior:** 
 
 **Expected behavior:**
Page items should still be working 

 **Minimal repro:**
 
New WPF app, add a page.

Set `EnableDefaultApplicationDefinition` to `false`.

**Comment by rladuca** [comment]
Thanks for reporting this @onovotny !  This was a regression from a prior change to support Visual Studio's reading of None items (see #685).

This fix was merged in both master and release/3.0 branches.
