### ISSUE TITLE
Is PresentationCore built with Debug configuration? 

### ISSUE THREAD

**Issue by omariom** [dotnet/wpf#1766]
* .NET Core Version: 3.0.0-preview8-28405-07, 3.0.0-preview6-27804-01
* Windows version: 1903
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No
 
 **Problem description:**

While looking at the jitted code of PresentationCore, found that the code was not optimized.
Turned out the assembly has optimizations explicitly disabled.

![image](https://user-images.githubusercontent.com/1781701/64218473-b4da7c80-ceb9-11e9-9074-d81ed788edba.png)

**Comment by rladuca** [comment]
Yep, we discovered this as part of an investigation into #1549.  Long story short, we inject a module constructor into `PresentationCore` via IL(D)Asm and had incorrect settings leading to the wrong parameters being used for the `DebuggableAttribute`.

This was already fixed recently.  Closing as a duplicate.
