### ISSUE TITLE
MediaElement can not play successful in WPFCore project

### ISSUE THREAD

**Issue by chabiss** [dotnet/wpf#1772]
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview9-014004
 Commit:    8e7ef240a5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   D:\VS\src\Tools\dotnet\sdk\3.0.100-preview9-014004\

Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a

.NET Core SDKs installed:
  3.0.100-preview9-014004 [D:\VS\src\Tools\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [D:\VS\src\Tools\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [D:\VS\src\Tools\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [D:\VS\src\Tools\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

 
 
 **Problem description:**
1. Create a WPFCore project

2. Add attach a mp4 video to to project (make sure that build action is resource, is that a separate bug? 

3. Add this code in Grid
```
<MediaElement Source="your video.mp4" />
```
3. F5

Actual:

 **Actual behavior:** 
Video can not play successful
 
 **Expected behavior:**
 
Video should play.  

The problem is that the MP4 file is *not* copied into the bin directory.

**Comment by weltkante** [comment]
> 2. make sure that build action is resource
> The problem is that the MP4 file is not copied into the bin directory.

these two contradict each other, if you make it a resource its embedded in the file not copied around

**Comment by nguerrera** [comment]
cc @davkean

**Comment by nguerrera** [comment]
When I follow these steps for a .NET *Framework* classic project, the video doesn't play either. The item is added with "Build Action" = "Content" and "Copy To Output Directory" = "Do not copy. Changing it to "Copy if newer" causes the video to play on F5.

Now testing the same in core project.

**Comment by nguerrera** [comment]
The behavior is basically the same for core. The default build action is none, not Content, but these are actually treated the same almost everywhere in the build. And I can get the video to play in the same number of steps in either case:

1. Right click project, Add existing item, browse to mp4
2. Right click mp4, properties, change "Copy to Output Directory" from "Do not copy" to "Copy if newer"
3. Add MediaElement to Grid

I'm not seeing the bug here.

**Comment by grubioe** [comment]
Closing per offline discussion
