### ISSUE TITLE
Code in WPF Application CTor is not executed

### ISSUE THREAD

**Issue by Dirkster99** [dotnet/wpf#1773]
I am in the process of converting a [WPF project from .Net 4.5.1 to NetCore 3](https://github.com/Dirkster99/MsgBox/tree/master) based on **Preview 9** and noticed that the code in the Applictions Constructor is never executed (see attached refderence project).

App.xaml.cs
```
public App()
{
  ServiceContainer.Instance.AddService<IMessageBoxService>(new MessageBoxService());
}
```

...the  ServiceContainerInstance code is not executed whether I select NetCore or .Net in VS 2019 makes no difference. This can also be verified by setting a breakpoint (which is never hit). So, one might be thinking its bug in VS but it looks like a project type/framework bug to me since I can later catch an exception when I click on the **Show test Message** button in the Demo project:

![Untitled](https://user-images.githubusercontent.com/2129700/64364687-b91aad00-d013-11e9-8267-2e6f9614b251.png)

![Untitled1](https://user-images.githubusercontent.com/2129700/64364693-bddf6100-d013-11e9-8330-120d38077f16.png)

I am sure its not a project issue because:
1) this worked before the conversion
2) I can move the above statement from the App.CTor() to the MainWindow.CTor() (which is also hit in the debugger) and verify that everything's working as expected.

[MsgBox_App_CTor_Bug_Reference.zip](https://github.com/dotnet/wpf/files/3580540/MsgBox_App_CTor_Bug_Reference.zip)

**Comment by weltkante** [comment]
`App.xaml` and `App.xaml.cs` use different namespaces, so they generate two distinct App classes. The one from the xaml is used for startup.

**Comment by Dirkster99** [comment]
Yes, you are right - everythings fine once the namespace in consolidated in App.xaml and App.xaml.cs. Thanks for the quick response :-)
