### ISSUE TITLE
WPF TextBox insertion caret does not render when moved to lower DPI monitor in a PMAv2 process

### ISSUE THREAD

**Issue by SamBent** [dotnet/wpf#1774]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`) 3.0
* Windows version: (`winver`) 1803+  (PMAv2 needed)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? no

 
 
 **Problem description:**
 [Port of a bugfix in the .NET 4.8 servicing pipeline.]

1. Have 200% primary, 100% secondary
2. Launch repro proj exe on primary
3. Focus the textbox and see the caret blinking
4. Move it to secondary

  **Actual behavior:** 
 The caret disappears, but can still type in the textbox

 **Expected behavior:**
 The caret doesn't disappear.

 **Minimal repro:**
 [Available in .NETFx bug]  It's just a WPF app with a TextBox, manifested to request PerMonitorAwareV2.

**Comment by weltkante** [comment]
#1066  might be related (or actually the same)

**Comment by vatsan-madhavan** [comment]
> #1066 might be related (or actually the same)

It's the same!

**Comment by SamBent** [comment]
Fixed for 3.1 via #1939.
