### ISSUE TITLE
Visual Studio 2019 16.1.4 crashes when sorting a table in SQL Server Object Explorer by datetime column

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#1775]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/624340/visual-studio-2019-1614-crashes-when-sorting-a-tab.html)._

---
### Visual Studio 2019 16.1.4 crashes when sorting a table in SQL Server Object Explorer by datetime column

Sorting a table in SQL Server Object Explorer causes Visual Studio to prompt with an index error popup and crash.

Steps To Repo
1. Open the SQL Server Object Explorer
1. Browse any local/remote SQL database for a table to view
1. Right-click the table to view data
1. Click on the sort data icon
1. On a datetime column, click sort by Ascending/Descending
1. Click Ok/Apply

---
#### Fiona Niu[MSFT] on 6/27/2019, 02:52 PM: 

<p>Thank you for taking the time to log this issue!<br>
I’ve tried to reproduce and investigate using the description, and attachments already provided. Unfortunately those aren’t enough and more information is needed in order to investigate it further.<br>
The easiest way to provide all the information is to use the Visual Studio Feedback Tool. This will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace).<br>
Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool:<br>
Open Visual Studio Feedback tool.<br>
Click the banner letting you know that you have problems requesting your attention.<br>
Click this problem from the list<br>
Click “View their request and respond” from the problem details banner<br>
Add a comment, in the Attachments/Record: click Start Recording<br>
When the Steps Recorder tool appears, perform the steps that reproduce the problem.<br>
When you’re done, choose the Stop Record button.<br>
Wait a few minutes for Visual Studio to collect and package the information that you recorded.<br>
Submit. You will be able to see the comment on Developer Community. For security reasons, your files come directly to us and don’t appear on Developer Community.<br>
For the full instructions, please see: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info</a>  . For information about what data is collected, see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect">https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect</a><br>
We look forward to hearing from you!</p>

#### Cory Langston on 6/27/2019, 07:12 PM: 

I am getting an error when sorting even a local table by any column in the SQL Server Object Explorer "View Data" window without getting a pop-up window titled "Microsoft Visual Studio" with a white x on a red circle stating "Index was out of range. Must be non-negative and less than the size of the collection.  Parameter name: index"  <br><br>The VS Feedback tool has an issue: 1)  the screen preview inaccurately shows a blank VS main window when I'm seeing a table of results and the "Filter and Sort [table]" dialogue box from the SQL Server Object Explorer window, 2) I *think* the feedback recording is not submitted properly if the instance of Visual Studio associated with the Feedback tool crashes and relaunches during the recording.  I will try again.
#### Cory Langston on 6/28/2019, 07:03 PM: 

Trying to capture a recording of the VS 2019 Enterprise 16.1.4 crash from SQL Server Object Explorer, following the instruction of support by creating a new instance of VS prior to clicking on Record.  Note: Running as local admin without any solution/project open.  From instance 1 of VS, I created a new VS instance and started a recording.. that instance crashed and relaunched. Submitting recording from instance 1.
#### Fiona Niu[MSFT] on 6/28/2019, 08:23 AM: 

(private comment, text removed)
#### Fiona Niu[MSFT] on 7/2/2019, 07:33 AM: 

<p>Thanks a lot for providing the information. We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### borgoyn on 7/26/2019, 06:21 AM: 

<p>I have also experienced the same problem with all of my local databases and any table. This used to work until recently.</p>

#### Visual Studio Feedback System on 7/26/2019, 04:53 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Visual Studio Feedback System on 7/29/2019, 10:51 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Shmariahu Porat on 7/31/2019, 06:56 PM: 

Have the same problem 
#### Elías Sánchez on 8/31/2019, 06:24 AM: 

<p>Any update in this issue? having the same issue in VS Community 2019 V 16.2.3 in Windows 10 V 1903</p><p>  </p>

---
### Original Solutions
(no solutions)

**Comment by grubioe** [comment]
Internal ID: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/938083

**Comment by joeruder** [comment]
This is still happening in 16.2.5 for me.
Not just date field, but the main index field as well.

Every table I have tried it with has failed.

All work OK on vs 2017, same machine.

These are all Azure SQL Db.

Currently a deal breaker for my work flow and having to switch back to 2017 for now.

**Comment by danielebanovaz** [comment]
I started having the same issue on VS2017 (not sure when or how it started, it used to work correctly).
Installed VS2019: issue is present here as well.

In both cases, the workaround is to select your sort column -> click ok to the error message box that appears -> click 'Apply' -> close the filtering window.
If you click 'Ok' instead of 'Apply', VS restarts.

**Comment by bobAct** [comment]
I am having the same issue on VS2017 v 15.9.14; SQL Tools v 15.1.16906.03120
There is no workaround within Object Explorer but recovery is -> click ok to the error message box that appears -> click 'Apply' -> close the filtering window.
If you click 'Ok' instead of 'Apply', VS restarts.

I was able to Use Tools-> SQL Server->New Query to build a Select statement that included an Order BY as a workaround.  Inconvenient!

**Comment by MRVDH** [comment]
Here people who run .NET Framework 4.7.0x don't have the issue, but people who run .NET Framework 4.8.x do have the issue.

What's the status on this bug?

**Comment by jwrana** [comment]
I've been have the exact same issues since my last VS update. 
Currently on Version16.3.7
.Net Version 4.8.03761

**Comment by MRVDH** [comment]
I recently updated Windows and Visual Studio, to .NET Framework 4.8.03752 and I'm having the issue now as well.

Workaround for everyone: When you sort on a column and the error pops up, press the X to close the error window and then press 'Apply' in the filter window. This way it wont crash and you can still filter.

**Comment by jwrana** [comment]
Awesome... thanks for the workaround. :-) Still not fixed as of the last update.

**Comment by SimonExelby** [comment]
Have the same problem on both computers I use for development, both VS2017 and an Azure database it has been  working fine on both up to about the beginning of September 2019 - any hope of a resolution?

**Comment by danielebanovaz** [comment]
Good news: it appears that the issue has been solved in Microsoft Visual Studio Community 2019
Version 16.4.3

I have not experienced any error message nor crash since I updated to that version.

**Comment by pchaurasia14** [comment]
Closing this as fixed in latest VS versions.
