### ISSUE TITLE
Copy file procedure fails in copy-wpf.ps1 file

### ISSUE THREAD

**Issue by Simon-IT** [dotnet/wpf#1883]
.NET Core Version: **3.0.100-preview9-014004**
Windows version: **1903 (build SO 18362.356)**
Does the bug reproduce also in WPF for .NET Framework 4.8?: **not applicable**
 
 **Problem description:**
The macro doesn't copy the files because the source directory is targeted 3.0 yet.
 
 **Actual behavior:**
The procedure exit without any message about fail.
 
 **Expected behavior:**
 All WPF files are copyed or a message that tells the source directory doesn't exists.

Maybe I was wrong but I've commit a solution to this bug and it appears in the pull request of another bug [1761](https://github.com/dotnet/wpf/pull/1761)
 Please tell me how I should behave

**Comment by weltkante** [comment]
> Please tell me how I should behave

PRs aren't commit based, each PR needs a separate branch

**Comment by Simon-IT** [comment]
Thank you @weltkante. I'll follow your suggestion. About this, is it possible remove the commit from the pull request ?

**Comment by weltkante** [comment]
You can remove the commit in your repository and do a force-push when you upload, github should pick that up and reset the PR I think. If you want to switch the branch the PR points to, not sure if thats possible, never had to do that on github but it [seems possible](https://help.github.com/en/articles/changing-the-base-branch-of-a-pull-request)

**Comment by Simon-IT** [comment]
I've done "revert" of the commit...

**Comment by Simon-IT** [comment]
@stevenbrix Sorry, what's the meaning of "up-for-grubs" ?

**Comment by Simon-IT** [comment]
@stevenbrix I'm sorry if I ask so many questions, but I have to understand better how the contribution system works. So, can I open a PR with the solution of this ssue ?

**Comment by stevenbrix** [comment]
@Simon-IT,

> I'm sorry if I ask so many questions, but I have to understand better how the contribution system works. 

No worries! Have you read our [documentation](https://github.com/dotnet/wpf/blob/master/Documentation/contributing.md) on contributing? Hopefully there is some information in there that is helpful. If not, we're always happy to answer your questions :)

> So, can I open a PR with the solution of this ssue ?

Yes, please do! 👍

**Comment by Simon-IT** [comment]
The [1883](https://github.com/dotnet/wpf/pull/1947) PR has been opened for this issue.
