### ISSUE TITLE
Handle d3d_compiler.dll dependency

### ISSUE THREAD

**Issue by rladuca** [dotnet/wpf#189]
Since .NET Framework 4.7, WPF has had a dependency on d3d_compiler.dll.  On Windows 7 SP1, Windows Server 2008 R2, and Windows Server 2008 R2 SP1, this is not necessarily installed.

We need to possibly redist d3d_compiler.dll with the WindowsDesktop SDK.  Installer chaining/blocking will probably not work here due to self contained application publishing.

**Comment by rladuca** [comment]
See #167 for an example and report of this.

**Comment by vatsan-madhavan** [comment]
This has been fixed. See note at https://github.com/dotnet/wpf/issues/37#issuecomment-494984585
