### ISSUE TITLE
help me！！Why is it wrong instead of warning?

### ISSUE THREAD

**Issue by MrLongBz** [dotnet/wpf#1935]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Windows version: (`winver`)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? If yes, please file the issue via the instructions here: https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019

 
 
 **Problem description:**  I don't know where this error is.
 
 **Actual behavior:** 我从git上克隆的项目，作者的环境能够编译，但我的不行，我的是vs 2019 preview 4.0 .net core 3.0.100-rc1-014190
 
 **Expected behavior:**
 
 **Minimal repro:**
 
![image](https://user-images.githubusercontent.com/38212157/65390363-776a6000-dd90-11e9-801e-f88241fc9c01.png)
![image](https://user-images.githubusercontent.com/38212157/65390418-15f6c100-dd91-11e9-9054-f3d354c046a8.png)

**Comment by MrLongBz** [comment]
[WpfApp4.zip](https://github.com/dotnet/wpf/files/3639940/WpfApp4.zip)
This is my Demo.

**Comment by MrLongBz** [comment]
![image](https://user-images.githubusercontent.com/38212157/65390997-57d63600-dd96-11e9-8c95-e804bbc6daef.png)

**Comment by vatsan-madhavan** [comment]
You may need a version of `Microsoft.Xaml.Behaviors.Wpf` that supports `netcoreapp3.0`. The one you are using (`1.0.1`) doesn't support `netcoreapp3.0`, so you are seeing this warning NU1701 in WpfApp4.zip. 

![image](https://user-images.githubusercontent.com/20246435/65470919-ffe51100-de21-11e9-9efb-41834dc7d254.png)

There is a compat-shim that allows us to use libraries developed for .NET Framework, but there is no way to know whether it will work until it is tested. 

See https://github.com/dotnet/standard/issues/439#issuecomment-321608375. 

I'm not able to repro the errors you have posted in the first screenshot.  

Please consider voting up this issue - https://github.com/microsoft/XamlBehaviorsWpf/issues/13 and reporting your original problem (NU1201 errors) there as well.
