### ISSUE TITLE
Can't publish app for osx-x64

### ISSUE THREAD

**Issue by lekhasy** [dotnet/wpf#1948]
**Steps to produce:**

1. Create a wpf project from WPF App (.Net core) template in visualstudio
2. Click on build -> publish
3. Change deployment mode to: Self-contained
4. Change target framework to: osx-x64

**Actual result:** the screen display this error:
![image](https://user-images.githubusercontent.com/14049235/65525913-6c433b80-df1a-11e9-8539-9b939288c505.png)

And the text in output window: 
`1>------ Publish started: Project: Demo, Configuration: Release Any CPU ------

1>Restore completed in 0.51 ms for C:\Users\Admin\source\repos\Demo\Demo\Demo.csproj.

1>There was no runtime pack for Microsoft.WindowsDesktop.App.WPF available for the specified RuntimeIdentifier 'osx-x64'.

========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========`

**Expected result:** Publish successfull

**Environment**:
.Net core version: 3.0
Visual Studio 2019 version: 16.3.0

**Comment by lindexi** [comment]
WPF can only use in windows

**Comment by grubioe** [comment]
@lekhasy - While the bulk of .NET Core is cross platform, WPF and Winforms only work on Windows.   More details via [this comment](https://github.com/dotnet/wpf/issues/48#issuecomment-444198305) from issue #48 .

**Comment by lupj** [comment]
> @lekhasy - While the bulk of .NET Core is cross platform, WPF and Winforms only work on Windows. More details via [this comment](https://github.com/dotnet/wpf/issues/48#issuecomment-444198305) from issue #48 .

Whats the ideal of your team.
