### ISSUE TITLE
Control selection reversed in Designer when FlowDirection="RightToLeft"

### ISSUE THREAD

**Issue by mrNo0b** [dotnet/wpf#1961]
When I set **FlowDirection="RightToLeft"** in MainWindow in WPF Core 3 app when I add controls to the MainWindow they shows up in their correct locations in Designer but when I want to click on them to select, the selection highlight is in the opposite side of the window
`VS 2019 16.3.1`

![designerIssue](https://user-images.githubusercontent.com/12209347/65650408-5f564300-e013-11e9-9744-85ecd26f1a60.png)

**Comment by grubioe** [comment]
@mrNo0b - thanks for raising this.  It seems specific to the Visual Studio WPF designer.

Can you log an issue in the [Visual Studio Developer Community]( https://developercommunity.visualstudio.com/content/problem/post.html?space=8)-  it will then be directed to the right Visual Studio team to troubleshoot?  By logging an issue there, the Visual Studio team will have more information to troubleshoot your issue.  
Thanks!
