### ISSUE TITLE
Reference Source for repository

### ISSUE THREAD

**Issue by weltkante** [dotnet/wpf#1967]
[Roslyn](http://source.roslyn.io) and [CoreFX](https://source.dot.net/) have online browsable source for their repositories, we should have that for WPF and WinForms as well. I'm currently still using [Desktop Reference Source](https://referencesource.microsoft.com/) but once WPF starts moving apart this would be very useful for quick research during code reviews.

**Comment by KirillOsenkov** [comment]
I think WPF is already being indexed on https://source.dot.net:
https://source.dot.net/#PresentationFramework/System/Windows/Controls/Button.cs,bfc2d93e5b6e9a96

https://github.com/dotnet/source-indexer/blob/9bff716508ba262c9583ad86c30ada7b1a07e8c8/src/index/repositories.props#L29-L37

**Comment by vatsan-madhavan** [comment]
I filed this: https://github.com/dotnet/source-indexer/issues/42.
