### ISSUE TITLE
Cannot access resource files on runtime

### ISSUE THREAD

**Issue by Symbai** [dotnet/wpf#1972]
* .NET Core Version: 3.0
* Windows version: Win10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**
Cannot access resource files on runtime when:

- Adding them as Resource
- Adding them as Embedded Resource
- Adding them through resource file
 
 **Actual behavior:**
Every time I try to access it it's not part of the resources at all and therefore returns null.
 **Expected behavior:**
 Able to access resource files on runtime. 
 **Minimal repro:**

```
<ItemGroup>
  <EmbeddedResource Include="bla3" />
</ItemGroup>
<ItemGroup>
  <Resource Include="bla2" />
</ItemGroup>
```
 
```
 public MainWindow()
        {
            InitializeComponent();
            //Fails
            ResourceTest("bla2");
            ResourceTest("bla3");
            Debug.Assert(Application.Current.Properties["bla"] != null);
        }

        static void ResourceTest(string resourceName)
        {
            try
            {
                var bla = Application.Current.TryFindResource(resourceName);
                Debug.Assert(bla != null);
            }
            catch (Exception e) { Debug.Fail(e.ToString()); }
        }
```
[ResourceTest.zip](https://github.com/dotnet/wpf/files/3664189/ResourceTest.zip)

**Comment by weltkante** [comment]
> Does the bug reproduce also in WPF for .NET Framework 4.8?: No

If I translate the project file contained in ResourceTest.zip to a Desktop Framework project it fails for me as well, so your claim that it works on Desktop is not necessarily correct. I think this may be a porting mistake when going from Desktop to Core. Can you provide an example which actually works on Desktop and fails on Core? Then we could probably tell you what you did wrong (or identify the regression if there is any)
