### ISSUE TITLE
error CS0111: Type 'App' already defines a member called 'InitializeComponent' with the same parameter types

### ISSUE THREAD

**Issue by prasanthelvr** [dotnet/wpf#1974]
**Description**

We have a WPF application which targets .NET Framework version from 2.0 to 4.6. We have used different App and Mainwindow files for .NET Framework version 2.0v-3.5v (App.xaml, MainWindow.xaml) and 4.0-4,6v (App1.xaml, MainWindow1.xaml). Now, we are providing .NET Core support using App1.xaml, MainWindow1.xaml files. While compiling, .NET Core WPF project showing compilation issue but, .NET Framework WPF project compiles properly.

**Actual Behavior**

The following compilation issue shown in .NET Core WPF project.

error CS0111: Type 'App' already defines a member called 'InitializeComponent' with the same parameter types.

**Expected Behavior**

.NET Core WPF project should compile and run properly as like .NET Framework WPF project.

**Basic Information**

* .NET Core Version: 3.0
* Windows version: Windows 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

**Reproduction Link**
The following sample have two project files.
1. .NETFramework.csproj - Run properly
1. .NETCore.csproj - Compilation issue

[NETCoreTest.zip](https://github.com/dotnet/wpf/files/3670130/NETCoreTest.zip)

**Comment by vatsan-madhavan** [comment]
Try this: 


```xml
<PropertyGroup>
  <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
</PropertyGroup>
<ItemGroup>
  <ApplicationDefinition Include="App1.xaml" />
</ItemGroup>
```

/cc @grubioe, we need the documentation tracked by https://github.com/dotnet/docs/issues/13884 soon (ideally we should have had this documented before 3.0 GA). 

I've reopened https://github.com/dotnet/wpf/issues/1302 to track this.

**Comment by prasanthelvr** [comment]
@vatsan-madhavan Thank you. The suggested solution resolved my issue.

**Comment by jamsoft** [comment]
I just tried applying the above fix to a .NET5.0 project I'm migrating from 4.7.2.

Unfortunately, I'm still getting the error.

Could anything else in an older format project cause this?

I'm having a complete nightmare migrating to be honest.

**Comment by jamsoft** [comment]
I just tried applying the above fix to a .NET5.0 project I'm migrating from 4.7.2.

Unfortunately, I'm still getting the error.

Could anything else in an older format project cause this?

I'm having a complete nightmare migrating to be honest.
