### ISSUE TITLE
Packaging Project Build Failed

### ISSUE THREAD

**Issue by clurch** [dotnet/wpf#1997]
* .NET Core Version: 3.0.0
* Windows version: 1903 (10.0; Build 18362)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No
 
 **Problem description:**
 Upon building a .NETCore WPF project package, the Microsoft.Toolkit.Win32.UI.XamlHost.dll cannot be found. I don't believe this dll is used for the Microsoft.Toolkit.Wpf.UI packages.

 **Actual behavior:** 
MSB3030	Could not copy the file "...source\repos\ToastNotifcationTestingNetCore\ToastNotifcationTestingNetCore\bin\Debug\netcoreapp3.0\Microsoft.Toolkit.Win32.UI.XamlHost.dll" because it was not found.	ToastNotificationTestingNetCore.Package	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets line 567	
 
 **Expected behavior:**
Package should build successfully.

 **Minimal repro:**
Follow the instructions found in https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-4 for "Add a notification" then perform https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-5. 

**NOTE**
This issue looks to have been resolved in https://github.com/MicrosoftDocs/windows-uwp/issues/1811 about 3 months ago, however it may have resurfaced with v6.0.0-preview9.1 of Microsoft.Toolkit.Wpf.UI.Controls and Microsoft.Toolkit.Wpf.UI.XamlHost. I am sorry if I am reporting this issue to the incorrect place.

**Comment by grubioe** [comment]
@clurch - thanks for the report, can you log an issue in the WIn UI repo? Thanks!

https://github.com/Microsoft/microsoft-ui-xaml

**Comment by clurch** [comment]
I have submitted the issue to the Win UI repo at https://github.com/microsoft/microsoft-ui-xaml/issues/1408
