### ISSUE TITLE
Missing RichTextBox.SelectionFont Property

### ISSUE THREAD

**Issue by muqiuq** [dotnet/wpf#2002]
According to the documentation https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.richtextbox.selectionfont?view=netcore-3.0 RichTextBox.SelectionFont Property sould be available. But I can't find it anywhere. Has this been replaced by something else or is it not yet implemented?

**Comment by weltkante** [comment]
You are posting to the WPF repository but linked the WinForms RichTextBox. Are you by any chance mixing up the two APIs?
