### ISSUE TITLE
DragDrop.DoDragDrop not working in wpf , when drag to windows explorer in windows10

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#2007]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/759425/dragdropdodragdrop-not-working-in-wpf-when-drag-to.html)._

---
<p>i am using below code to drag and drop the file or folder to windows explorer, it works perfectly for winforms but fails for wpf. </p> <p>In WPF the code not work in windows 10 </p><p></p><p> string path = @&quot;C:\Rajesh\documents\bug\5.07 testing folder drag&quot;;
            StringCollection collection = new StringCollection() { path };                       
            string[] files = { path };
            var data = new DataObject(DataFormats.FileDrop, files);
            data. SetData(DataFormats.Text, files[0]);
            // Clipboard.SetData(DataFormats.FileDrop, files);
            // Perform dragdrop
            DragDrop.DoDragDrop(this, data, DragDropEffects.Copy);</p> <p class=""></p><p class=""></p>
</p>

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by miloush** [comment]
Works for me.

**Comment by rladuca** [comment]
Can you confirm this is not a symptom of this problem?  https://github.com/dotnet/wpf/issues/1323

**Comment by miloush** [comment]
Does the ticket have an associated windows build number? I am on 18995.1.amd64fre.vb_release.190927-1420.

**Comment by madhankumar-g** [comment]
I am able to drag and drop to desktop, but drag and drop to outlook is not working from WPF application.

**Comment by rladuca** [comment]
Sorry, the bot is strangely closing issues incorrectly in some cases.

This went out in September/October.  If you're up to date with this [KB](https://support.microsoft.com/en-us/help/4517211/windows-10-update-kb4517211) then you should be good (assuming this is the same issue).  Can you ensure that the different users don't also have difference OS versions?
