### ISSUE TITLE
Ribbon expand/collapse issue with Managed Addin Framework MAF.NET

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#2013]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/764522/ribbon-expandcollapse-issue-with-managed-addin-fra.html)._

---
<p>I'm working on an Windows Presentation Foundation (WPF) addin-application, for Addins, we are using Managed Addin Framework MAF.NET. Addin projects are WPF applications and are responsible to generate their ribbon menu and content. The problem I'm facing is that when the Ribbon control is transformed through MAF pipeline using FrameworkElementAdapters.ElementToContractAdapter and then back to FrameworkElement using FrameworkElementAdapters.ContractToElementAdapter, it loses &quot; some&quot; functionality. I want to host this converted Ribbon on the Host side and when I collapse/expand the ribbon control, the parent grid doesn't reclaim the height. Expected behavior is that when the ribbon is collapsed the RowHeight of the Grid's RowDefinition should collapse and when the ribbon gets expanded, the RowDefinition should also expand. The issue is with Expandable controls, like Ribbon and Expander. Images are attached with the post for Desired and Undesired behavior, and a sample project is also attached herewitht he post re-produce the issue quickly. Sample project to reproduce the issue is attached with the post.</p> <p>Issue is described <a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/92d931fd-68aa-4c11-bf13-ca9a0797733b/ribbon-control-issue-when-passed-through-managed-addin-framework-maf-pipeline?forum=wpf" target=_blank> here</a> too.</p>

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by grubioe** [comment]
Closing this ticket as its not a supported scenario for WPF.  I've re-opened the feedback ticket and re-routed to another team.
