### ISSUE TITLE
Entity Framework logs not showing up anymore after migration to .NET Core 3

### ISSUE THREAD

**Issue by scalablecory** [dotnet/wpf#2046]
_From @shoe-diamente on Wednesday, October 9, 2019 9:45:08 AM_

# Issue Title

Entity Framework SQL logs stop showing up in debug after I migrated from .NET Core 2.2 to .NET Core 3.0.

# General

By using this configuration:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}

```

in `appsettings.json` I was able to see logging informations about SQL queries made via Entity Framework.

Now, even with this configuration:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug"
    }
  }
}
```

I'm unable to see any logging regarding SQL queries made (but I see other debugging messages from .NET Core which suggests that the configurations are picked up correctly).

Did anything change with regards to logging that was not [documented here](https://docs.microsoft.com/it-it/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)?

_Copied from original issue: dotnet/core#3576_

**Comment by weltkante** [comment]
@scalablecory this doesn't look related to WPF at all? sure you got the repository right?

**Comment by grubioe** [comment]
@scalablecory This doesn't belong here.   Please re-route, likely Entity Framework

**Comment by shoe-diamente** [comment]
Moved here then: https://github.com/aspnet/EntityFrameworkCore/issues/18418
