### ISSUE TITLE
Why Content  Property can't display first '_' in CheckBox Control

### ISSUE THREAD

**Issue by typinging** [dotnet/wpf#2048]
* .NET Core Version: 3.0
* Windows version: win 10 1809 (17763.475)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio: No
 
 **Problem description:** The Checkbox Control do not display first '_' in content property.
 like this: 
![QQ截图20191015164959](https://user-images.githubusercontent.com/16849935/66816160-2f43f500-ef6c-11e9-96d9-8c8d9e6912ad.png)

**Comment by weltkante** [comment]
You need to escape undescore (`_`) by duplicating it (`__`). Underscores are WPFs special character for signifying shortcuts. Holding alt will underline the letter c and pressing alt+c will check the checkbox. This is the same behavior as in Desktop Framework, no regression, its probably also documented somewhere but I don't know where to look right now.

**Comment by lindexi** [comment]
It's a feature, not a bug
