### ISSUE TITLE
WPF Datagrid crashes the app after screen loaded

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#2056]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/763608/wpf-datagrid-crashes-the-app-after-screen-loaded.html)._

---
Hi, after implementing the AppCenter in my WPF application I recived a bug that causes the app to crash (not caused by the AppCenter it looks an old issue on my client's PC)
the following report is exported to AppCenter, I am using .net frameword 4.5 and my ID is VS2019 16.3.2

System.ArgumentNullException: Value cannot be null. Parameter name: element
System.Windows.Automation.Peers
UIElementAutomationPeer.FromElement (UIElement element)
System.Windows.Controls.DataGrid
CellAutomationValueHolder.TrackValue ()
System.Windows.Controls
DataGrid.ReleaseCellAutomationValueHolders ()
System.Windows.Controls
DataGrid.OnExecutedCommitEdit (ExecutedRoutedEventArgs e)
System.Windows.Input
CommandBinding.OnExecuted (Object sender, ExecutedRoutedEventArgs e)
System.Windows.Input
CommandManager.ExecuteCommandBinding (Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)

crossover.local.xpos.productsPrism.Views.Common.Controls
XPosStockInMatrixControl.HandleMainDataGridCellEditEnding (Object sender, DataGridCellEditEndingEventArgs e)
System.Windows.Controls
DataGrid.OnCellEditEnding (DataGridCellEditEndingEventArgs e)

MS. Win32
HwndWrapper.WndProc (IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
MS. Win32
HwndSubclass.DispatcherCallbackOperation (Object o)
System.Windows.Threading
ExceptionWrapper.InternalRealCall (Delegate callback, Object args, Int32 numArgs)

MS. Win32
HwndSubclass.SubclassWndProc (IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
MS. Win32
UnsafeNativeMethods.DispatchMessage (MSG&amp; msg)
System.Windows.Threading
Dispatcher.PushFrameImpl (DispatcherFrame frame)

crossover.local.xpos.productsPrism.ViewModels.MainProductViewModel
&lt;&gt;c__DisplayClass772_0. &lt;EventAggregatorMessageProcess&gt;b__0 ()
System.Windows.Threading
ExceptionWrapper.InternalRealCall (Delegate callback, Object args, Int32 numArgs)

MS. Internal
CulturePreservingExecutionContext.Run (CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
System.Windows.Threading
DispatcherOperation.Invoke ()

MS. Win32
HwndWrapper.WndProc (IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
MS. Win32
HwndSubclass.DispatcherCallbackOperation (Object o)
System.Windows.Threading
ExceptionWrapper.InternalRealCall (Delegate callback, Object args, Int32 numArgs)

MS. Win32
HwndSubclass.SubclassWndProc (IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
MS. Win32
UnsafeNativeMethods.DispatchMessage (MSG&amp; msg)
System.Windows.Threading
Dispatcher.PushFrameImpl (DispatcherFrame frame)

crossover.local.xpos.productsPrism
App.Main ()

---
#### Fiona Niu[MSFT] on 10/7/2019, 08:35 PM: 

<p>Thank you for taking the time to log this issue!<br>
I’ve tried to reproduce and investigate using the description, and attachments already provided. Unfortunately those aren’t enough and more information is needed in order to investigate it further.<br>
The easiest way to provide all the information is to use the Visual Studio Feedback Tool. This will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace).<br>
Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool:</p>
<pre><code>• Open Visual Studio Feedback tool.
• Click the banner letting you know that you have problems requesting your attention.
• Click this problem from the list
• Click &quot;View their request and respond&quot; from the problem details banner
• Add a comment, in the Attachments/Record: click Start Recording
• When the Steps Recorder tool appears, perform the steps that reproduce the problem.
• When you're done, choose the Stop Record button.
• Wait a few minutes for Visual Studio to collect and package the information that you recorded.
• Submit. You will be able to see the comment on Developer Community. For security reasons, your files come directly to us and don't appear on Developer Community.
</code></pre>
<p>For the full instructions, please see: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info</a> . For information about what data is collected, see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect">https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect</a></p>
<p>We look forward to hearing from you!</p>

#### Visual Studio Feedback System on 10/15/2019, 08:06 PM: 

We will close this report in 7 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### Mustafa Shaban on 10/15/2019, 11:52 PM: 

<p>The problem is that this trace log is coming from the client's PC, and I am unable to reproduce this but on my device</p>

#### Fiona Niu[MSFT] on 10/16/2019, 02:27 AM: 

<p>Thanks for your reply. We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by grubioe** [comment]
Mustafa- Can you provide a crash dump and more information to help troubleshoot?  Thanks
