### ISSUE TITLE
Fault module name:	wpfgfx_cor3.dll

### ISSUE THREAD

**Issue by AmierCheng** [dotnet/wpf#2057]
* .NET Core Version: 3.0
* Windows version: window server R2 enterprise

 
 
 **Problem description:**
 问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	WpfApp1.exe
  应用程序版本:	1.0.0.0
  应用程序时间戳:	5d7bb0cb
  故障模块名称:	wpfgfx_cor3.dll
  故障模块版本:	4.800.19.46238
  故障模块时间戳:	5d7ab8ec
  异常代码:	c000001d
  异常偏移:	00158e19
  OS 版本:	6.1.7601.2.1.0.274.10
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

 **Actual behavior:** 
 
 **Expected behavior:**
 
 **Minimal repro:**

<hr/>

_edit by @vatsan-madhavan - adding a machine translation_
```
Problem Signature: 
Problem Event Name: APPCRASH 
Application Name: WpfApp1.exe 
Application Version: 1.0.0.0 
Application Timestamp: 5d7bb0cb 
Fault Module Name: wpfgfx_cor3.dll 
Fault Module Version: 4.800.19.46238 
Fault Module 
Timestamp: 5d7ab8ec 
Exception Code : c000001d 
Abnormal offset: 00158e19 
OS Version: 6.1.7601.2.1.0.274.10 
Locale ID: 2052 
Other information 1: 0a9e 
Other information 2: 0a9e372d3b4ad19135b953a78882e789 
Other information 3: 0a9e 
Other information 4: 0a9e372d3b4ad19135b953a78882e789
```

**Comment by lindexi** [comment]
Do you install the Runtime? https://dotnet.microsoft.com/download/dotnet-core/3.0/runtime

**Comment by AmierCheng** [comment]
> yes, I do.Problems still exist。

**Comment by AmierCheng** [comment]
> Do you install the Runtime? https://dotnet.microsoft.com/download/dotnet-core/3.0/runtime

yes, I do.Problems still exist。

**Comment by vatsan-madhavan** [comment]
Have you checked to see whether you have a bitness mistmatch - for e.g., a 32-bit OS attempting to run a 64-bit app?

**Comment by AmierCheng** [comment]
> Have you checked to see whether you have a bitness mistmatch - for e.g., a 32-bit OS attempting to run a 64-bit app?

Thanks，you say is right！

**Comment by thudugala** [comment]
Hi I have the same issue 

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	RocketM.exe
  Application Version:	2.0.0.0
  Application Timestamp:	5d7bb0cb
  Fault Module Name:	wpfgfx_cor3.dll
  Fault Module Version:	4.800.19.46238
  Fault Module Timestamp:	5d7ab8ec
  Exception Code:	c000001d
  Exception Offset:	00158e19
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	5129
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	6fbe
  Additional Information 4:	6fbe6bde2701766d81cbca0597a5fa35

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

OS is 

![image](https://user-images.githubusercontent.com/4112014/69830042-9f41dc80-1287-11ea-8ca4-7b2be7c17e8d.png)

app is x86

**Comment by vatsan-madhavan** [comment]
> Exception Code: c000001d

That's [`STATUS_ILLEGAL_INSTRUCTION`](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55). 

I would think that you might be trying to run a 64-bit application on a 32-bit operating system, but your screenshot clearly shows a 64-bit x64 OS, so that's probably not it. 

> I have the same issue

Your issues is not the same issue - if your report is accurate, then it just bears a resemblance on the surface. 

I'm going to fork your post into its own issue so we can dig into it further.
