### ISSUE TITLE
Error MSB4044 on build

### ISSUE THREAD

**Issue by ThomasGoulet73** [dotnet/wpf#2070]
I have recently cloned the wpf project for potentially making PRs, but as I was building the project using build.cmd, I had a MSB4044 error :

C:\Users\\{Username}\Documents\GitHub\Wpf\eng\WpfArcadeSdk\tools\InjectModuleInitializer.targets(372,5): error MSB4044:
 The "ILDasmTask" task was not given a value for the required parameter "ILDAsm". [C:\Users\\{Username}\Documents\GitHu
b\Wpf\src\Microsoft.DotNet.Wpf\src\PresentationCore\PresentationCore.csproj].

I tried building the CoreFX project and had no problems.

I didn't really know where to report those kind of issues so sorry for the inconvenience if it wasn't at the right place.

Thank you !

**Comment by rladuca** [comment]
Can you make sure you have the .NET Framework 4.6.1 SDK installed?

![image](https://user-images.githubusercontent.com/20006987/67219418-d8f80b80-f3dc-11e9-8ae7-dba7cf500209.png)

At current, we use MSBuild to locate ILDAsm.  The locator has issues detecting certain versions of the .NET toolset, but 4.6.1 should work.

**Comment by ThomasGoulet73** [comment]
Thank you @rladuca, installing the .Net Framework 4.6.1 SDK fixed my issue.
