### ISSUE TITLE
DragDrop.DoDragDrop not working in wpf , when drag to windows explorer in windows10 #2007

### ISSUE THREAD

**Issue by DragDropAP** [dotnet/wpf#2079]
i am using below code to drag and drop the file or folder to windows explorer, it works perfectly for winforms but fails for wpf. 
In WPF the code not work in windows 10 

string path = @"C:\Rajesh\documents\bug\5.07 testing folder drag"; StringCollection collection = new StringCollection() { path }; string[] files = { path }; var data = new DataObject(DataFormats.FileDrop, files); data. SetData(DataFormats.Text, files[0]); // Clipboard.SetData(DataFormats.FileDrop, files); // Perform dragdrop DragDrop.DoDragDrop(this, data, DragDropEffects.Copy);

**Comment by rladuca** [comment]
@DragDropAP What is the specific mode of failure here?  Can you supply a minimal reproduction application that shows the issue?

In a simple test application using your code and getting the data from the Drop event, I am able to receive the path.  If I also drag from explorer, I am able to see the file paths as well.
