### ISSUE TITLE
Compile error with WPF .net Core 3.0 when adding .resx files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#2112]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/771961/compile-error-with-wpf-net-core-30-when-adding-res.html)._

---
Visual Studio 2019 Professional 16.3.3

If I do **localization** with WPF **.net Framework** and add two files (Resources.resx and Resources.de.resx) it **compiles as expected.**

But if I do the same in **WPF .net Core 3.0 I get compile errors.**

- Create a WPF .net Core app
- Add a Resources folder
- Create a Resources.resx file
- Set it to public
- Create a Resources.de.resx file
- Set it to public
- Build solution

&gt; Error		Custom tool PublicResXFileCodeGenerator failed to produce an output for input file 'Resources\Resources.de.resx' but did not log a specific error.	LocalizationWpfNetCore	C:\...\source\repos\LocalizationWpfNetCore\LocalizationWpfNetCore\Resources\Resources.de.resx	1		

and

&gt; Error	MSB3086	Task could not find &quot;al.exe&quot; using the SdkToolsPath &quot;&quot; or the registry key &quot;HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.2\WinSDK-NetFx40Tools-x86&quot;. Make sure the SdkToolsPath is set and the tool exists in the correct processor specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed	LocalizationWpfNetCore	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\ MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	3639

So why does it work when I choose .net Framework but not with .net Core?

---
#### Visual Studio Feedback System on 10/10/2019, 11:27 AM: 

We have converted this feedback item from idea to problem. This change was done to better reflect the feedback's nature.
#### Visual Studio Feedback System on 10/11/2019, 01:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Olivier Leclerc on 10/19/2019, 08:44 PM: 

<p>I have the same two errors using NetStandard.Librairy 2.0.3  </p>

---
### Original Solutions
(no solutions)

**Comment by merriemcgaw** [comment]
@rainersigwald - do you have any thoughts on this one?

**Comment by rainersigwald** [comment]
Localized resx problems are probably looks like microsoft/msbuild#4794 (cc @BenVillalobos)

I'm not so sure about the `al.exe` one. That sounds like a symptom of microsoft/msbuild#4782, which should be avoided in 16.4 (and can be worked around today by installing the 4.7.2 SDK).

**Comment by Quietscheente** [comment]
The work around with installing 4.7.2 Developer Pack worked

**Comment by arpitmathur** [comment]
Closing since these are being tracked in the msbuild issues linked above.
