### ISSUE TITLE
Cant perform initial build.cmd before using solution

### ISSUE THREAD

**Issue by deanchalk** [dotnet/wpf#2128]
**Problem description:**

**I have installed all of the pre-requisites as described in the contributing guidelines but I am getting lots of failures. I have looked through several of the powershell scripts but cant work out whats missing. The 'native-tools' section in global.json I believe are loaded from a cloud store somewhere which I think fails initially, and it may be why everything else fails.**
 
 **Actual behavior:** 

C:\opensource\wpf>build.cmd
Processing C:\opensource\wpf\global.json
strawberry-perl was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: strawberry-perl was not found in .
net-framework-48-ref-assemblies was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: net-framework-48-ref-assemblies was not found in .
dotnet-api-docs_netcoreapp3.0 was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: dotnet-api-docs_netcoreapp3.0 was not found in .
msvcurt-c1xx was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: msvcurt-c1xx was not found in .
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe /nologo /bl:C:\opensource\wpf\artifacts\log\Debug\ToolsetRestore.binlog /clp:Summary /clp:ErrorsOnly;NoSummary /m /nr:True /p:ContinuousIntegrationBuild=False /p:TreatWarningsAsErrors=true /p:__ToolsetLocationOutputFile=C:\opensource\wpf\artifacts\toolset\5.0.0-beta.19527.3.txt /t:__WriteToolsetLocation /v:minimal /warnaserror C:\opensource\wpf\artifacts\toolset\restore.proj
Detecting WPF Git hooks...
Detected existing WPF Git pre-commit hook.
Processing C:\opensource\wpf\eng\..\global.json
strawberry-perl was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: strawberry-perl was not found in .
net-framework-48-ref-assemblies was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: net-framework-48-ref-assemblies was not found in .
dotnet-api-docs_netcoreapp3.0 was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: dotnet-api-docs_netcoreapp3.0 was not found in .
msvcurt-c1xx was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: msvcurt-c1xx was not found in .
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe /nologo /bl:C:\opensource\wpf\artifacts\log\Debug\Build.binlog /clp:Summary /m /nowarn:D9035 /nr:True /p:ContinuousIntegrationBuild=False /p:TreatWarningsAsErrors=true /p:Platform=x86 /p:Configuration=Debug /p:RepoRoot=C:\opensource\wpf /p:Restore=True /p:DeployDeps=False /p:Build=True /p:Rebuild=False /p:Deploy=False /p:Test=False /p:Pack=False /p:IntegrationTest=False /p:PerformanceTest=False /p:Sign=False /p:Publish=False /v:minimal /warnaserror C:\Users\deanc\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19527.3\tools\Build.proj
  Restore completed in 2.74 sec for C:\Users\deanc\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19527.3\tools
  \Tools.proj.
dotnet-install: .NET Core Runtime version 2.1.7 is already installed.
dotnet-install: Adding to current process PATH: "C:\opensource\wpf\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: .NET Core Runtime version 5.0.0-alpha1.19514.1 is already installed.
dotnet-install: Adding to current process PATH: "C:\opensource\wpf\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\System.Xaml\System.Xaml.csproj : error : Unable to locate the .NET Core
SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\System.Xaml\System.Xaml.csproj : error MSB4236: The SDK 'Microsoft.NET.S
DK' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\PresentationCore\PresentationCore.csproj(2,31): error MSB4236: The SDK '
Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\PresentationFramework\PresentationFramework.csproj(2,31): error MSB4236:
 The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\UIAutomation\UIAutomationClient\UIAutomationClient.csproj : error MSB423
6: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\UIAutomation\UIAutomationClientSideProviders\UIAutomationClientSideProvi
ders.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\UIAutomation\UIAutomationProvider\UIAutomationProvider.csproj : error MS
B4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\UIAutomation\UIAutomationTypes\UIAutomationTypes.csproj : error MSB4236:
 The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\System.Windows.Input.Manipulations\System.Windows.Input.Manipulations.cs
proj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\ReachFramework\ReachFramework.csproj : error MSB4236: The SDK 'Microsoft
.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\cycle-breakers\PresentationFramework\PresentationFramework-PresentationUI-ap
i-cycle.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\cycle-breakers\PresentationFramework\PresentationFramework-System.Printing-i
mpl-cycle.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\System.Printing\ref\System.Printing-ref.csproj : error MSB4236: The SDK
'Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\System.Xaml\ref\System.Xaml-ref.csproj : error MSB4236: The SDK 'Microso
ft.NET.SDK' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\UIAutomation\UIAutomationTypes\ref\UIAutomationTypes-ref.csproj : error
MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\test\Common\DRT\TestServices\TestServices.csproj : error MSB4236: The SDK 'M
icrosoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\Extensions\PresentationFramework-SystemData\PresentationFramework-System
Data.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\Themes\PresentationFramework.AeroLite\PresentationFramework.AeroLite.csp
roj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\Themes\PresentationFramework.Royale\PresentationFramework.Royale.csproj
: error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\System.Windows.Presentation\ref\System.Windows.Presentation-ref.csproj :
 error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\WindowsFormsIntegration\ref\WindowsFormsIntegration-ref.csproj : error M
SB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

Build FAILED.
 
 **Expected behavior:**
 
 **Minimal repro:**

**Comment by vatsan-madhavan** [comment]
> It was not possible to find any installed .NET Core SDKs
Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
https://aka.ms/dotnet-download

This. 

Correlate with the version requested in global.json and remedy, then `git clean -xdf` and try again.

**Comment by deanchalk** [comment]
I'm just running the 'build.cmd' from the instructions for getting this up and running. This command doesnt run correctly so one or more of the powershell scripts isnt working. Ive installed all of the .NET Core SDK's I could find anyway - just incase, but it fixes nothing.
All I want to do is get past first base and get this initial 'built' state achieved as per instructions

**Comment by vatsan-madhavan** [comment]
Do you have SDK version 5.0.100-alpha1-014065 installed ?

**Comment by deanchalk** [comment]
Yes

**Comment by deanchalk** [comment]
I managed to get a version 5.0.100-alpha1-015505 from https://github.com/dotnet/core-sdk. I changed to this version in global.json. Still getting the same errors. There doesnt seem to be any way of downloading a different version
.......
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\System.Xaml\System.Xaml.csproj : error : Unable to locate the .NET Core
SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\System.Xaml\System.Xaml.csproj : error MSB4236: The SDK 'Microsoft.NET.S
DK' specified could not be found.
C:\opensource\wpf\src\Microsoft.DotNet.Wpf\src\PresentationCore\PresentationCore.csproj(2,31): error MSB4236: The SDK '
Microsoft.NET.Sdk' specified could not be found.
...........

**Comment by vatsan-madhavan** [comment]
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script has a powershell script that will let you install any version of .NET Core SDK. 

`build -ci` will attempt to install the requisite .NET Core SDK's locally inside the repository root in a local tools folder and use those. I don't really recommend using `-ci` for local development, but it's a good way to troubleshoot and check to see if that remedies your problems.

**Comment by CrispyDrone** [comment]
I'm having the exact same issue. Here is the output of `dotnet --info`:

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-alpha1-015759
 Commit:    28f22a7729

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-alpha1-015759\

Host (useful for support):
  Version: 5.0.0-alpha.1.19564.1
  Commit:  c77948d92a

.NET Core SDKs installed:
  2.1.508 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  5.0.100-alpha1-015759 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-alpha1.19572.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-alpha.1.19564.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-alpha.1.19564.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I installed the latest core sdk `5.0.100-alpha1-015759` and changed the `global.json` accordingly:

```json
{
  "tools": {
    "dotnet": "5.0.100-alpha1-015515",
    "runtimes": {
      "dotnet": [
        "2.1.7",
        "$(MicrosoftNETCoreAppVersion)"
      ]
    },
    "vs": {
      "version": "16.1"
    }
  },
  "msbuild-sdks": {
    "Microsoft.DotNet.Arcade.Sdk": "5.0.0-beta.19557.20",
    "Microsoft.DotNet.Helix.Sdk": "5.0.0-beta.19557.20"
  },
  "native-tools": {
    "strawberry-perl": "5.28.1.1-1",
    "net-framework-48-ref-assemblies": "0.0.0.1",
    "dotnet-api-docs_netcoreapp3.0": "0.0.0.2",
    "msvcurt-c1xx": "0.0.0.8"
  }
}
```

Here is the output I get when running `build.cmd`:
```
Processing C:\Users\Bart\Documents\Projects\Other\wpf\global.json
strawberry-perl was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: strawberry-perl was not found in .
net-framework-48-ref-assemblies was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: net-framework-48-ref-assemblies was not found in .
dotnet-api-docs_netcoreapp3.0 was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: dotnet-api-docs_netcoreapp3.0 was not found in .
msvcurt-c1xx was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: msvcurt-c1xx was not found in .
Detecting WPF Git hooks...
Detected existing WPF Git pre-commit hook.
Processing C:\Users\Bart\Documents\Projects\Other\wpf\eng\..\global.json
strawberry-perl was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: strawberry-perl was not found in .
net-framework-48-ref-assemblies was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: net-framework-48-ref-assemblies was not found in .
dotnet-api-docs_netcoreapp3.0 was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: dotnet-api-docs_netcoreapp3.0 was not found in .
msvcurt-c1xx was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: msvcurt-c1xx was not found in .
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe /nologo /bl:C:\Users\Bart\Documents\Projects\Other\wpf\artifacts\log\Debug\Build.binlog /clp:Summary /m /nowarn:D9035 /nr:True /p:ContinuousIntegrationBuild=False /p:TreatWarningsAsErrors=true /p:Platform=x86 /p:Configuration=Debug /p:RepoRoot=C:\Users\Bart\Documents\Projects\Other\wpf /p:Restore=True /p:DeployDeps=False /p:Build=True /p:Rebuild=False /p:Deploy=False /p:Test=False /p:Pack=False /p:IntegrationTest=False /p:PerformanceTest=False /p:Sign=False /p:Publish=False /v:minimal /warnaserror C:\Users\Bart\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19557.20\tools\Build.proj
  Restore completed in 33,91 ms for C:\Users\Bart\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19557.20\tools\Tools.proj.
dotnet-install: .NET Core Runtime version 2.1.7 is already installed.
dotnet-install: Adding to current process PATH: "C:\Users\Bart\Documents\Projects\Other\wpf\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: .NET Core Runtime version 5.0.0-alpha1.19514.1 is already installed.
dotnet-install: Adding to current process PATH: "C:\Users\Bart\Documents\Projects\Other\wpf\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\System.Xaml\System.Xaml.csproj : error : Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\System.Xaml\System.Xaml.csproj : error MSB4236: The SDK 'Microsoft.NET.SDK' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\PresentationCore\ref\PresentationCore-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.SDK' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\PresentationFramework\ref\PresentationFramework-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.SDK' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\ReachFramework\ref\ReachFramework-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\System.Printing\ref\System.Printing-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\System.Windows.Input.Manipulations\ref\System.Windows.Input.Manipulations-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\System.Xaml\ref\System.Xaml-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.SDK' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\UIAutomation\UIAutomationClient\ref\UIAutomationClient-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\UIAutomation\UIAutomationClientSideProviders\ref\UIAutomationClientSideProviders-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\UIAutomation\UIAutomationProvider\ref\UIAutomationProvider-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\test\DRT\DrtXaml\XamlTestClasses.FriendWithKey\XamlTestClasses.FriendWithKey.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\Themes\PresentationFramework.Royale\ref\PresentationFramework.Royale-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

Build FAILED.

C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\System.Xaml\System.Xaml.csproj : error : Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\System.Xaml\System.Xaml.csproj : error MSB4236: The SDK 'Microsoft.NET.SDK' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\PresentationCore\ref\PresentationCore-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.SDK' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\PresentationFramework\ref\PresentationFramework-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.SDK' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\ReachFramework\ref\ReachFramework-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\System.Printing\ref\System.Printing-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\System.Windows.Input.Manipulations\ref\System.Windows.Input.Manipulations-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\System.Xaml\ref\System.Xaml-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.SDK' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\UIAutomation\UIAutomationClient\ref\UIAutomationClient-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\UIAutomation\UIAutomationClientSideProviders\ref\UIAutomationClientSideProviders-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\UIAutomation\UIAutomationProvider\ref\UIAutomationProvider-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\test\DRT\DrtXaml\XamlTestClasses.FriendWithKey\XamlTestClasses.FriendWithKey.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\Users\Bart\Documents\Projects\Other\wpf\src\Microsoft.DotNet.Wpf\src\Themes\PresentationFramework.Royale\ref\PresentationFramework.Royale-ref.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
    0 Warning(s)
    13 Error(s)

Time Elapsed 00:00:01.90
Build failed.
See log: C:\Users\Bart\Documents\Projects\Other\wpf\artifacts\log\Debug\Build.binlog
```

**Comment by vatsan-madhavan** [comment]
Don’t change global.json. Instead, install the version if SDK requested by global.json (5.0.100-alpha1-015515) and try again. 

Also try to build with “-ci” switch and see if that helps. It’s a good check, but we don’t recommend regular use of “-ci”.
