### ISSUE TITLE
Provide an equivalent for the WinForms FolderBrowserDialog class

### ISSUE THREAD

**Issue by Symbai** [dotnet/wpf#2131]
In relation to #2012 WPF generally doesn't include Windows Forms (the developer has to reference WinForms explicitly). 

One common reason why people end up having to reference WinForms is so that they can show up a dialog for the user to select a folder. This is for some reason missing while WPF has an equivalent type for FileDialog in Microsoft.Win32 namespace.  It would be good if WPF would provide an equivalent type for the FolderBrowserDialog too.

**Comment by miloush** [comment]
Duplicate of #438

**Comment by Symbai** [comment]
You are right, I'm sorry.
