### ISSUE TITLE
I am using wpf inkCanvas on win10 tablet, eraser cursor hide after touch up,  how can I prevent this behavior?

### ISSUE THREAD

**Issue by broad-m** [dotnet/wpf#2177]
.NET Framework 4.5
win10  tablet

**Comment by rladuca** [comment]
`InkCanvas` will only change the cursor to suit the `EditingMode` [if the cursor is in the bounds on the canvas](https://github.com/dotnet/wpf/blob/ac9d1b7a6b0ee7c44fd2875a1174b820b3940619/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/InkCanvas.cs#L2962).  A touch up on the primary pointer also implies an out of range.  This means that the cursor is no longer in the bounds of the canvas.  If there was a mouse device, I believe the next thing from the OS would be some mouse message which would tell the `InkCanvas` that there is a mouseover, but in this case that doesn't occur. This is probably the cause of the cursor change on the tablet device.

Do you have the ability to attach a mouse device?  If you do that as a test, does the eraser cursor still appear after a touch up?  If so, that validates the above.

You might be able to craft a custom workaround.  Try overriding the cursor explicitly via [InkCanvas.UseCustomCursor](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.inkcanvas.usecustomcursor?view=netframework-4.8).  It might be possible to tap into Preview(TouchUp/TouchDown) to force the cursor to work the way you would like.

Basically, on `PreviewTouchDown` you could turn off the custom cursor and let `InkCanvas` handle it.  Then, on a corresponding `PreviewTouchUp` save the current cursor, set InkCanvas.UseCustomCursor to true, and then explicitly set the mouse cursor.  This would be essentially keeping the last cursor state from `InkCanvas`. 

It's not a straightforward workaround and would need some experimentation and also would take handling when the cursor goes into range on some other control.

Unfortunately I can't replicate your specific scenario right now (I don't have the hardware here) so I can't validate this thinking or produce an example workaround that I know helps.  You'll have to experiment and see if you can get this functionality.

I'm going to leave this open for discussion in case others have any input.
