### ISSUE TITLE
Web Browser Control

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/wpf#2178]
Is one coming for WPF?  Perhaps one based on the chromium edge work?

**Comment by Symbai** [comment]
There is already one https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.webbrowser?view=netframework-4.8

And there is one with edge as engine, though its currently a viewer with limited features: https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/webview

**Comment by arpitmathur** [comment]
Dupe of #1094
