### ISSUE TITLE
System.SystemException: Error at "OleInitialize" for "-2147417850"

### ISSUE THREAD

**Issue by faryu** [dotnet/wpf#2185]
Hi,

I have recently migrated my WPF application from .net framework 4.6.2 to .net core 3.0.
It works great so far on my machine and at least 6 more, but now I have encountered a Notebook, which throws an error which I have not seen before while opening the MainWindow with the ShowDialog() method.

```cs
System.SystemException: Fehler bei "OleInitialize" für "-2147417850".
   at System.Windows.OleServicesContext.SetDispatcherThread()
   at System.Windows.OleServicesContext.get_CurrentOleServicesContext()
   at System.Windows.DragDrop.RegisterDropTarget(IntPtr windowHandle)
   at System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters)
   at System.Windows.Interop.HwndSource..ctor(HwndSourceParameters parameters)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
```

Which in english could mean: Error at "OleInitialize" for "-2147417850".

The notebook is using Windows 10 64-bit and is running the latest windows updates.
My application is a self-contained .net core 3.0 with WPF enabled, published for the win-x64 target platform. I do not know how to tell the exact version of which .net core 3.0 I'm using, so I'm posting the version of the PresentationCore.dll, which is file version 4.800.19.46214 and product version 4.8.0-rc2.19462.14+...

Any idea what could cause this?

**Comment by weltkante** [comment]
The error code means the thread is not in STA mode and cannot be changed to STA either. What thread are you calling `ShowDialog` on, the main thread?

**Comment by faryu** [comment]
I also checked this and the ShowDialog method is called from the Main thread, which has the STA ApartmentState set.
Strangely enough I have found a workaround. If I open another window before creating my MainWindow, then it works on that particular machine without the error.

```cs
// This Works
var wndt = new WindowTest(); // This is a new, empty window, which I use to trigger the creation of the OleServicesContext.
wndt.Show();
wndt.Close();

_wndMain = new MainWindow();
_wndMain.ShowDialog();
```

```cs
// This does not work and throws the same exception as it does without the WindowTest Dialog
_wndMain = new MainWindow();

var wndt = new WindowTest();
wndt.Show();
wndt.Close();

_wndMain.ShowDialog();
```

I'm doing quiet a few things in the constructor of the MainWindow. The main things are creating an Asp.Net.Core WebHost, starting it and starting a few other asynchronous services.

**Comment by weltkante** [comment]
> I also checked this and the ShowDialog method is called from the Main thread, which has the STA ApartmentState set.

Thats strange because it seems to contradict the error code. Except for checking that you have no misbehaving 3rd party DLLs being injected into the process I have no more ideas how to diagnose the problem, you'll have to wait for someone from the WPF team to suggest further steps to pinning this down.

**Comment by arpitmathur** [comment]
@faryu Can you please provide us a sample application that reproduces the problem? Can you also share the laptop configuration and Windows 10 version you're on?

**Comment by faryu** [comment]
Sadly I cannot at the moment, because the issue was on the device of a customer and my application has grown a bit complex over time, so it will take quite some time to recreate the issue in a sample project.
Seeing that I have a workaround that does not have a big impact on the usability of the application I will close this issue for now until I have a bit more free time and manage to reproduce the issue in a sample project.
