### ISSUE TITLE
Cleanup of inefficient code

### ISSUE THREAD

**Issue by ThomasGoulet73** [dotnet/wpf#2199]
There are several places in the WPF project where there is old code and inefficient code that aren't up-to-date with .Net. For example, in PresentationCore, there is little to no use of recent releases of the C# language. There is no use of discards or pattern matching and all those new feature that makes the code cleaner and more efficient. I would start with PresentationCore because I think it is the oldest project.

Here are the things I would change in PresentationCore:
- Use discards with unused out parameter.
- Use pattern matching instead of "as" and then null check.
- Use Null-conditional operators instead of null check and then calling the method.
- Replace literal string parameter name with nameof(parameter).
- And other cleanup which is a case per case.

There wouldn't be any breaking change because it's only cleanup.

I would like to do this cleanup in PresentationCore as my first issue. I know cleanup is probably not in your priorities which is why I would like to do this and it's very easy to review because it's not suppose to change the behavior of the code. I would do one PR per big file and group small changes to multiple file in other PR.

**Comment by weltkante** [comment]
Note that none of the points you mention is "inefficient", its just cleanup. Also note that some of this can be done automatically across the solution with already existing Analyzer/CodeFix commands. Automatic cleanup may be preferable over manual changes because lower risk of making mistakes.

**Comment by drewnoakes** [comment]
https://github.com/dotnet/wpf/blob/master/Documentation/contributing.md#code-formatting-improvements-and-minor-enhancements

**Comment by ThomasGoulet73** [comment]
> Note that none of the points you mention is "inefficient", its just cleanup. Also note that some of this can be done automatically across the solution with already existing Analyzer/CodeFix commands. Automatic cleanup may be preferable over manual changes because it has a lower risk of making mistakes.

I didn't mean inneficient performance-wise just inneficient in writting many lines of code which could be written in less lines.

> https://github.com/dotnet/wpf/blob/master/Documentation/contributing.md#code-formatting-improvements-and-minor-enhancements

My apologies, I didn't see this documentation file, I'm closing this issue as this was already addressed in the doc.

**Comment by drewnoakes** [comment]
@ThomasGoulet73 from that doc:

> We will consider code-formatting improvements that are identified by running code analyzers.

Some of the things you suggested are probably flagged by analyzers. You may still be able to make a contribution here. I don't know what analyzers this repo is using, but if it's not using those in https://github.com/dotnet/roslyn-analyzers then you may be able to make the case for adding them.
