### ISSUE TITLE
Will Visual Studio 2019 will be based on .net core 3 ?

### ISSUE THREAD

**Issue by anirudhagupta** [dotnet/wpf#223]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Windows version: (`winver`)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No

 
 
 **Problem description:**
 
 **Actual behavior:** 
 
 **Expected behaviour:**
 
 **Minimal repro:**
 
 I hear @coolcsh saying that we have used it internally and it's run quite well. It improves the performance of the overall app. WPF in .net core 3 is not going to Support Linux and Mac so there should not be a lot of trouble. They need to make it work on windows.

So upcoming Visual Studio will be based on .net framework or .net core 3.

**Comment by dotMorten** [comment]
The preview of vs is already out and that isn't on 
.Net core. Timelines doesn't seem to align either. So I'm guessing no
