### ISSUE TITLE
Visual Studio 2017 .NET Core 3.0 debugger conflict with intellitrace

### ISSUE THREAD

**Issue by AlexeiScherbakov** [dotnet/wpf#225]
* .NET Core Version: 3.0.0-preview-27122-01 (SDK 3.0.100-preview-009812) 
* Windows version: Windows 10 x64 1803 (17134.472)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
 
When:

1. Intellitrace is enabled
2. Debugging of .NET Core 3.0 WPF App
3. Click on button on second window shown as dialog

Visual Studio 2017 (15.9.4)  debugger process (msvsmon.exe) exits unexpectedly and debug session is terminated with started application.

When application is started via .exe file it works normally.
When application is started in Visual Studio version without Intellitrace, or Intellitrace is explicitly disabled - all works normal

**Comment by vatsan-madhavan** [comment]
@AlexeiScherbakov - .NET Core 3.0 is supported primarily on Visual Studio 2019. Does this repro on VS2019 Preview builds as well? 

@DoRonMotter, Would your team be the right one to take a look at this?

**Comment by stevenbrix** [comment]
@AlexeiScherbakov do you see the same behavior on vs2019?

**Comment by plnelson** [comment]
@vatsan-Madhavan, this isn't a WPF issue, it's a known issue with IntelliTrace.  AFAIK there's already an internal bug tracking this.  @wiktork would know for sure.

**Comment by wiktork** [comment]
Yep, the bug was fixed for VS 2019.

**Comment by AlexeiScherbakov** [comment]
I don't check it on full app, on small test app it is not reproduces now, so I believe you :-D

**Comment by grubioe** [comment]
Closing issue, seems resolved in VS2019.
