### ISSUE TITLE
DataGridCell.DataGridOwner accessibility

### ISSUE THREAD

**Issue by soeron** [dotnet/wpf#2261]
Currently the property [DataGridOwner](https://github.com/dotnet/wpf/blob/ae1790531c3b993b56eba8b1f0dd395a3ed7de75/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridCell.cs#L1034) is marked as internal, which is coming from full framework like this. But there are many situations where the cell may need access to its owning data grid. A simple example is the VerticalContentAlignment property of the datagrid which does nothing and is not respected in any way with the current templates in the .NET framework which is ported line by line for now. There are many other use cases where accessing the owning data grid is needed. Grid wide attached properties etc.
Other elements of the datagrid like rows, columns have this property and it is still internal. Please make it public. I can't see a reason to leave it internal.

**Comment by arpitmathur** [comment]
@soeron Thanks for filing the issue. The team discussed this and we are not planning to change the access modifier for this property.

**Comment by soeron** [comment]
Fair enough. Can you fix then VerticalContentAlignment to do what it is supposed to do for DataGrid control then?
