### ISSUE TITLE
Very strange problem ClientContext data loss

### ISSUE THREAD

**Issue by angtianqiang** [dotnet/wpf#2262]
I tested a very strange question

I tested a very strange question
Running environment: WPF netcore3.0 csla5.0.1
Problem description: set the ClientContext value in the WPF start window and read it as null, while it can be read normally in the non-wpf main window. This problem has not occurred before with WPF (net4.0)+csla4.7.2, can you help to see what is going on

Test code:

  public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            Csla.ApplicationContext.ClientContext["a"] = "test";
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            var aa = Csla.ApplicationContext.ClientContext["a"];
            //   aa = null;
            //This is in the main window and reads null
        }

       
    }

 public partial class Window1 : Window
    {
        public Window1()
        {
            InitializeComponent();
            Csla.ApplicationContext.ClientContext["b"] = "test";
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            var bb = Csla.ApplicationContext.ClientContext["b"];
            //  bb = test"
            //This is the non-wpf main window and can be read normally
        }
    }

**Comment by arpitmathur** [comment]
@angtianqiang Why do you believe this is a WPF issue and not a Csla issue?

**Comment by BentTranberg** [comment]
This was crossposted as issue [849](https://github.com/MarimerLLC/cslaforum/issues/849) in [MarimerLLC/cslaforum](https://github.com/MarimerLLC/cslaforum), and seems to have been adequately resolved there six days ago. No need to keep this open any longer.

**Comment by rladuca** [comment]
@BentTranberg Thanks for the info!  We'll close this at this point.

@angtianqiang If the CSLA resolution doesn't help and you have evidence this is a WPF issue, feel free to file another issue with more information.
