### ISSUE TITLE
The property windows for WPF is not as same as Winforms.

### ISSUE THREAD

**Issue by anirugu** [dotnet/wpf#232]
Earlier I used a Winforms a lot, just Go to property and change the name. When you are in Xaml file, you can't change the name in property windows (latest 2017) nor you can make an event by just click on the textbox as you can do same in WinForms.

Are these improvement coming to WPF. This was the thing that I found missing in WPF for Visual Studio Tooling.

**Comment by stevenbrix** [comment]
Thanks for filing this issue @anirugu! There is a "Report a Problem" tool inside Visual Studio that can be used for reporting these sorts of issues. Unfortunately, this repo only contains the source code for WPF, and not any Visual Studio tooling. For that reason, I'm going to close this issue. Please don't hesitate to respond if you have any other questions, thanks!
