### ISSUE TITLE
\wpf\src\Microsoft.DotNet.Wpf\src\System.Xaml\ref\System.Xaml-ref.csproj targets 'netcoreapp5.0'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v3.0'.

### ISSUE THREAD

**Issue by ellownet** [dotnet/wpf#2325]
I'm not sure if I am asking a stupid question

I am trying to compile the projects, any of them, and I am getting this message. Is this repository supposed to compile?

Can someone point to a direction?

I appreciate the patience, thanks.

**Comment by arpitmathur** [comment]
@ellownet Have you tried cloning from scratch and building a repository? If you're still seeing this issue, can you please look in the artifacts/log directory and attach build.binlog to the issue?
