### ISSUE TITLE
BitmapImage issue: Reference to type 'Freezable' claims it is defined in 'WindowsBase'

### ISSUE THREAD

**Issue by gdunit** [dotnet/wpf#2341]
**.NET Core Version:** 
3.1
**Windows version:** 
v1903
**Does the bug reproduce also in WPF for .NET Framework 4.8?:** 
No
**Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)?** 
No

**Problem description:**
When creating a new .net core console app (3.1) and using BitmapImage class BeginInit() or EndInit() methods, compiler errors are generated relating to the type Freezable missing from WindowsBase.dll.

**Minimal repro:**
- Create a new .net core console app (3.1) 
- Add references to PresentationCore.dll and WindowsBase.dll (tried framework 4.7.2 and 4.8 versions)
- Add the following code:
            BitmapImage bi = new BitmapImage();
            bi.BeginInit();
- The following compiler error is generated:
CS7069	Reference to type 'Freezable' claims it is defined in 'WindowsBase', but it could not be found

**Comment by weltkante** [comment]
> Add references to PresentationCore.dll and WindowsBase.dll (tried framework 4.7.2 and 4.8 versions)

Thats not going to work, you said above you are creating a .NET Core project. Core/Desktop assemblies are not compatible.

You probably want to add a line `<UseWPF>true</UseWPF>` in the project files properties section instead. Or create a WPF project in the first place instead of a console app.

**Comment by gdunit** [comment]
Thanks, OK so I guessI have misunderstood how this works.

What I am really trying to do is use the BitmapImage classes within System.Windows.Media.Imaging in a .NET core application because they leverage the Windows Imaging Component, which outperforms other imaging libraries in some areas. Previously this was not possible, but my hope was that the WPF port would allow some options.

I tried adding `<useWPF>true</useWPF>` in the project file, but this does not seem to provide access to the System.Windows.Media namespace; only referencing the assemblies directly (which I now understand is not going to work) resolves it, but with the initial exception evident.

Are there any other possibilities to achieve usage of BitmapImage in .NET Core?

**Comment by rladuca** [comment]
Add a `FrameworkReference`.

```
 <ItemGroup>
        <FrameworkReference Include="Microsoft.WindowsDesktop.App"/>
 </ItemGroup>
```

You want this in conjunction with `UseWPF` as that tells the build to pull in the WPF reference assemblies.

**Comment by gdunit** [comment]
Awesome! Works like a charm. Thanks both for your help
