### ISSUE TITLE
Microsoft.Net.Sdk.WindowsDesktop missing Mifcrosoft.WinFx.props

### ISSUE THREAD

**Issue by livarcocc** [dotnet/wpf#2363]
It seems the latest package versions of Microsoft.Net.Sdk.WindowsDesktop are missing a few files, like Microsoft.WinFx.props and Microsoft.WinFx.targets and the tools folder.

We caught this because with these files missing it is not possible to build windows desktop apps.

I turned the tests for these off in core-sdk to unblock the flow of dependencies there and linked to this issue.

**Comment by rladuca** [comment]
The [dependency project for WindowsDesktop](https://github.com/dotnet/windowsdesktop/blob/master/pkg/windowsdesktop/src/windowsdesktop.depproj) doesn't seem to consume `Microsoft.NET.Sdk.WindowsDesktop`.

I don't have a full understanding of the `WindowsDesktop` repo off the top of my head, but I can take a look later on and see what comes from adding that dependency.

**Comment by rladuca** [comment]
Sorry, completely misread this at first.  I'm not sure why those are missing, I'm going to check any changes into the packaging in this repo, this has nothing to do with the WindowsDesktop repo.

**Comment by rladuca** [comment]
I think the offending change was:

https://github.com/dotnet/wpf/blob/7937304f9f194b231eabad606c3df1791c5a9e95/eng/WpfArcadeSdk/tools/ShippingProjects.props#L188

Normally, the repo location would have been overridden here (so PBT would package in Microsoft.NET.Sdk.WindowsDesktop) but the empty check stops this from happening, so PBT packages with the normal GitHub transport package.

**Comment by rladuca** [comment]
@livarcocc The next flow up the chain should have the appropriate props, etc.

**Comment by wli3** [comment]
@rladuca could you let me know when that flows is done?

**Comment by rladuca** [comment]
@wli3 `Microsoft.NET.Sdk.WindowsDesktop` version `5.0.0-alpha1.1.20056.2` is the fixed package.

[The WindowsDesktop repo](www.github.com/dotnet/WindowsDesktop) has taken flow from that change but the rolling build is stuck on publishing, re-running that now to see if it will pass.

**Comment by rladuca** [comment]
Actually that's just a warning, so I believe it went through fine.

`Microsoft.WindowsDesktop.App.Ref` version `5.0.0-alpha.1.20056.2` was published and consumed by core-sdk 3 hours ago (https://github.com/dotnet/core-sdk/pull/6069), so you should be getting all of the latest at this point.

**Comment by rladuca** [comment]
@wli3 Looks like dotnet/toolset is a once a day flow from dotnet/WindowsDesktop, kicking that now.

**Comment by rladuca** [comment]
@wli3 Seems like a bunch of PRs are stuck in dotnet/toolset with some Ubuntu test failures.  These don't look related to `WindowsDesktop` in any form, so someone will need to look at them and get the PRs flowing again.

**Comment by wli3** [comment]
@rladuca thanks I'll look into it

**Comment by dsplaisted** [comment]
@wli3 Has this flow completed?  When it does, can you make sure we revert the commit that disabled tests for this? https://github.com/dotnet/core-sdk/pull/5761/commits/12f3f4215b7187515381f0211e7dc40e8c29b78a

**Comment by wli3** [comment]
@dsplaisted actually no, it still fails here https://github.com/dotnet/sdk/pull/4145

**Comment by wli3** [comment]
and I haven't looked into why

**Comment by vatsan-madhavan** [comment]
Is this on .NET 5/master or release/3.1?

**Comment by rladuca** [comment]
@vatsan-madhavan .NET 5/master, this is a result of the build reconfiguration changes.  Release/3.1 doesn't have the same problem afaik.

**Comment by vatsan-madhavan** [comment]
> I think the offending change was:
> 
> https://github.com/dotnet/wpf/blob/7937304f9f194b231eabad606c3df1791c5a9e95/eng/WpfArcadeSdk/tools/ShippingProjects.props#L188
> 
> Normally, the repo location would have been overridden here (so PBT would package in Microsoft.NET.Sdk.WindowsDesktop) but the empty check stops this from happening, so PBT packages with the normal GitHub transport package.

@rladuca, are you working on a fix for this, or are you waiting on me?

**Comment by rladuca** [comment]
@vatsan-madhavan Yeah #2366 is the fix.
