### ISSUE TITLE
Setting the TaskbarItemInfo leads to System.NotImplementedException when no user is logged in

### ISSUE THREAD

**Issue by elyoh** [dotnet/wpf#2377]
* .NET Core Version: All that support WPF
* Windows version: Windows 7 and later
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 **Problem description:**
Take a WPF application which attempts to set the `TaskbarItemInfo` property of the main application window on Windows 7 or later.  In some situations this can lead to an unhandled `System.NotImplementedException` which crashes the application.

The apparent cause is attempting to run such an application when no user is logged in (e.g. remote desktop / Citrix / Windows Server).

An identical issue was present (and later [fixed](https://github.com/DevExpress/DevExpress.Mvvm.Free/blob/d8f957007cd409dd7e678876640b666fcf0c6467/DevExpress.Mvvm.UI/Services/TaskbarButtonService/Native/TaskbarInfoApplicator.cs#L11)) in [DevExpress MVVM toolkit](https://www.devexpress.com/Support/Center/Question/Details/T528105/notimplementedexception-in-taskbarbuttonservice-when-no-user-is-logged-in).  

 **Actual behavior:** 
The following line throws a `System.NotImplementedException`:
https://github.com/dotnet/wpf/blob/c90f457bfeb8d7737bb32f9e088aa2d9f8aff1d2/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs#L6291
```
System.NotImplementedException: The method or operation is not implemented.
   at MS.Internal.AppModel.ITaskbarList.HrInit()
   at System.Windows.Window.ApplyTaskbarItemInfo()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

 **Expected behavior:**
If the code in the try block containing the `taskbarList.HrInit();` call fails, the exception should be caught and handled accordingly.  If setting the `TaskbarItemInfo` property is not possible, even on a supported operating system, the code should simply return without setting the `TaskbarItemInfo` property.

 **Minimal repro:**
Add the following lines to an empty WPF desktop application:
```
    <Window.TaskbarItemInfo>
        <TaskbarItemInfo Description="Test" />
    <Window.TaskbarItemInfo>
```
Attempt to run the application on a machine where no user is logged in.

**Comment by Tyrrrz** [comment]
Apparently it can happen on non-remote desktop scenarios too:

https://github.com/Tyrrrz/DiscordChatExporter/issues/297

**Comment by elyoh** [comment]
I also believe it can happen in non-remote desktop scenarios although I've never managed to reproduce the crash this way. It would be very unlikely for end users to be running the affect apps using remote desktop scenario, but non the less we see this exception cropping up a few times a month in telemetry.

**Comment by RandomEngy** [comment]
@clubside has a reliable repro without any kind of remote desktop setup. He's unable to launch my app at all.

**Comment by Mgamerz** [comment]
Would be nice to see this fixed. My telemetry for my app shows a few dozen users get this error every week. I can never reproduce it however. Haven't tested .net 5 for it, however.

**Comment by krptodr** [comment]
I believe this is exactly the cause of the issues from causing Sourcetree to crash when opening in via RemoteApp:

https://community.atlassian.com/t5/Sourcetree-questions/Allow-Sourcetree-to-be-used-in-RemoteApp/qaq-p/1514923#U1515237

**Comment by Mgamerz** [comment]
I have a small taskbar helper class that works around this. Mine uses the API pack core since previews without buttons using WPF look bad but it would not be hard to swap back to it if you wished.

https://github.com/ME3Tweaks/ME3TweaksModManager/blob/6349e1545c80f517f9b7fd43d6bdb2cd7da834a0/MassEffectModManagerCore/modmanager/helpers/TaskbarHelper.cs

The project is GPL, but for this (as the dev), I give this file a do-whatever-you-want-with-it license.

**Comment by RandomEngy** [comment]
I got another repro from someone who is using a custom desktop shell: https://github.com/RandomEngy/VidCoder/issues/1012 . I can't catch the exception unfortunately.
