### ISSUE TITLE
The WPF .NET Core app build error after installed .NET Core 5.0 SDK

### ISSUE THREAD

**Issue by Amy-Li02** [dotnet/wpf#2400]
* .NET Core Version: .NET Core SDK 5.0.100 - alpha1 5.0.100.16134
* Windows version: 1909 (OS Build 18363.535)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

**More info:**
1. The WPF .NET Core app build error after installed .NET Core 5.0 SDK, no matter targeting .NET Core 3.1 or .NET Core 5.0.
2. The Console .NET Core app cannot reproduce this issue.
3. The WinForms .NET Core app also reproduce this issue.

**Actual behavior:** 
After build the WPF .NET Core app, some error message pops up. 
![Error](https://user-images.githubusercontent.com/49627022/71793406-a96dac80-3077-11ea-8e33-4548faf3f8c9.PNG)

**Expected behavior:**
The WPF .NET Core app should build successfully.

**Minimal repro:**
1. Install .NET Core 5.0 SDK latest build from here: https://github.com/dotnet/core-sdk.
2. Create a WPF .NET Core app.
3. Build this app.

**Comment by paul1956** [comment]
This also effects WinForms, if you install .NET Core 5.0 SDK existing WinForms 3.1 applications no longer compile with the same errors. If you uninstall the SDK everything works again.

**Comment by rladuca** [comment]
Thanks for reporting this, we're aware of this and are working on it via https://github.com/dotnet/wpf/issues/2363.  There is a fix pending approval and flow which should solve this.  Closing in favor of the that issue.
