### ISSUE TITLE
Stub CAS/Security in wpf

### ISSUE THREAD

**Issue by hughbe** [dotnet/wpf#241]
From https://github.com/dotnet/wpf/pull/214#discussion_r244214372

I'm guessing cause the source is shared we can't but opening for discussion

**Comment by vatsan-madhavan** [comment]
@ojhad, since related PR have all been merged, I recommend closing this issue. 

For cleanup of remaining items, like various `using System.Security.Permissions;` and miscellaneous comments (which implicate System.Windows.Extensions), please open a new tracking issue. 

/cc @grubioe
