### ISSUE TITLE
Add additional components from the Microsoft environment.

### ISSUE THREAD

**Issue by FSharpCSharp** [dotnet/wpf#242]
When publishing the WPF components, it would be very good if the libraries of the following namespaces were also published, since some applications are based on them. Is it possible to include them?

```
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
```

**Comment by batzen** [comment]
I guess by `http://schemas.microsoft.com/expression/2010/interactivity` you mean the things from `System.Windows.Interactivity`.
If that's the case it's available at https://github.com/Microsoft/XamlBehaviorsWpf.
Only the namespaces changed and it's now `http://schemas.microsoft.com/xaml/behaviors` in XAML and `Microsoft.Xaml.Behaviors` in code.

**Comment by FSharpCSharp** [comment]
Oh, thanks for the tip. Indeed, that must have passed me by. Is there anything similar for the other namespace that I might have overlooked?

**Comment by batzen** [comment]
That should, as far as i remember, already be part of wpf as it's used to define design time data etc.

**Comment by FSharpCSharp** [comment]
All right, thanks for the information. So much has happened here lately. I can change a lot in the product now to the new components, and thus almost exclusively on Open Source set. For this reason this issue is no longer necessary. I will therefore close it!
