### ISSUE TITLE
WindowStyle="None" has thick bar at top

### ISSUE THREAD

**Issue by mike-ward** [dotnet/wpf#2435]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
Version:   3.1.101
* Windows version: (`winver`)
Verson 1903 Build 18362.592
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No
Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)?
No
 If yes, please file the issue via the instructions [here](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/master/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**
 When main window style is `WindowStyle="None"`, a thick bar appears at the top of the window

 **Actual behavior:** 

![image](https://user-images.githubusercontent.com/567927/72442531-50d29980-3772-11ea-8a4d-8bd544953301.png)
 
 **Expected behavior:**
 
No bar appears at the top.

I've seen workarounds for this issue on Stackoverflow that recommend setting `AllowsTransparancy="True"` but this also disables window sizing using the borders. 

 **Minimal repro:**

Create a new WPF app in Visual Studio and set `WindowStyle="NONE"`.

```
<Window
  x:Class="WpfAppNoWindowStyleFramework.MainWindow"
  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
  xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
  xmlns:local="clr-namespace:WpfAppNoWindowStyleFramework"
  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
  Title="MainWindow"
  WindowStyle="None"
  mc:Ignorable="d">
  <Grid>
    <TextBlock>Hello World</TextBlock>
  </Grid>
</Window>
```

**Comment by vatsan-madhavan** [comment]
Guessing based on some research - I think we may need to dig into [HwndStyleManager](https://github.com/dotnet/wpf/blob/ac9d1b7a6b0ee7c44fd2875a1174b820b3940619/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs#L3155) which is used as shown below and investigate further. 

Initially I thought that perhaps this was an inherent problem with Windows, but I'm growing skeptical of that theory (esp. after doing some digging into internal bug databases). Also when I try to build an MFC toolwindow, I don't see colored border artefacts like we do in WPF. 

![image](https://user-images.githubusercontent.com/20246435/72570909-008f3080-3873-11ea-8cea-6e8d40039873.png)


https://github.com/dotnet/wpf/blob/ac9d1b7a6b0ee7c44fd2875a1174b820b3940619/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs#L2433-L2478

/cc @SamBent

**Comment by weltkante** [comment]
I don't know what you did in MFC, was that window resizable? Did you get it to work with a proper window frame? From my own experience having a "borderless resizable window" (which is a contradiction in itself since you need a border to resize) is not possible with standard window styles, you need to do more customization to force Windows to do "the right thing".

https://stackoverflow.com/questions/39731497/create-window-without-titlebar-with-resizable-border-and-without-bogus-6px-whit

**Comment by vatsan-madhavan** [comment]
@weltkante Thanks for the SO link, that was educational. No, the MFC window was not resizable - I didn't try too hard to get all the styles identical between `WindowStyle.None` WPF window and an MFC window - I was just trying to see whether MFC _could_ build a window that remove the top border from being visible. 

When I try to build something that's resizable, I can see the top-border just like in the SO example and in WPF w/`WindowStyle.None`, like this (the border is white): 

![image](https://user-images.githubusercontent.com/20246435/72852205-ba671200-3c62-11ea-8b34-fa12a707746f.png)

**Comment by mike-ward** [comment]
There's a workaround posted on stackoverflow using the `WindowChrome` class that I could not get to work. Discovered that I was not calling the base method in my `OnSourceIntialized` override. Once I corrected my code, the `WindowChrome` workaround worked. Details at https://github.com/mike-ward/tweetz/issues/8
