### ISSUE TITLE
How do I declare an Int32 resource in XAML(netcoreapp3.1 and net461)?

### ISSUE THREAD

**Issue by chenyj796** [dotnet/wpf#2441]
In .Net Framework, I can declare an Int32 resource with xaml namespace such as:
```xaml
xmlns:sys="clr-namespace:System;assembly=mscorlib"
```

But in netcoreapp, it need another xaml namespace such as:
```xaml
xmlns:sys="clr-namespace:System;assembly=System.Runtime"
```
Since the namespace "http://schemas.microsoft.com/winfx/2009/xaml" is not supported in WPF, is there any way to do that?

**Comment by vatsan-madhavan** [comment]
Try this.

```xaml
<Window x:Class="TestApp.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:TestApp"
        xmlns:sys="clr-namespace:System;assembly=mscorlib"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Window.Resources>
        <sys:Int32 x:Key="int">10</sys:Int32>
    </Window.Resources>
</Window>

``

**Comment by chenyj796** [comment]
If I use the following namespace in netcoreapp, it will log 2 errors: XLS0414 and XLS0419 after compiled.
```xaml
xmlns:sys="clr-namespace:System;assembly=mscorlib"
```

**Comment by vatsan-madhavan** [comment]
Would you mind collecting a build log so I can see the errors? 

https://aka.ms/msbuild/Binary-Log 

Also, a copy of your project would be helpful. 

When building, please use a `global.json` like this: 

```json
{
  "sdk": {
    "version": "3.1.101"
  }
}
```

Link to [3.1.101](https://dotnet.microsoft.com/download/dotnet-core/3.1) SDK.

**Comment by chenyj796** [comment]
The error details after compiled:
```
严重性	代码	说明	
错误	XLS0414	未找到类型“sys:Int32”。请确保不缺少程序集引用并且已生成所有引用的程序集。		
错误	XLS0419	CLR 命名空间未定义。"clr-namespace" URI 引用了找不到的命名空间“System”。	

```

**Comment by vatsan-madhavan** [comment]
Please share an msbuild binary log as requested in the previous comment. Also we’d appreciate logs in English - we can use machine translation for small snippets but that becomes much harder to use when dealing with a full build log.

**Comment by Symbai** [comment]
@vatsan-madhavan: I believe he is having these errors which show up in WPF .NET Core **designer only** but building and running the application works fine:

```
Error	XLS0414	The type 'sys:Int32' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.
Error	XLS0419	Undefined CLR namespace. The 'clr-namespace' URI refers to a namespace 'System' that could not be found.
```

There are also a lot of other issues when you bind to a third party control and it has a non-string value type. For example a timespan, you will get these in designer only again:
`Error	XDG0062	Could not load type 'System.TimeSpan?' from assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

These errors have no effect. The designer works fine, the building works fin and the application runs. It just shows up and confuses. I think whoever is working on the VS WPF .NET Core designer should take a look at it. The framework designer should not be effected.

**Comment by stevenbrix** [comment]
Adding @chabiss and @mgoertz-msft for the designer issues. See the above video, it looks like the application runs fine, but the designer gives an error that gives the impression there is an issue

**Comment by mgoertz-msft** [comment]
As suggested above, switch your using statement to the following and at least the language service (XLS) error will go away:

`xmlns:sys="clr-namespace:System;assembly=System.Runtime"`

Getting that fixed in the XAML language service is still blocked by the following Roslyn issue: https://github.com/dotnet/roslyn/issues/36274

**Comment by vatsan-madhavan** [comment]
> xmlns:sys="clr-namespace:System;assembly=System.Runtime"

That's not a good recommendation for folks that are migrating from .NET Framework. It incurs significant overhead in terms of having to fixup XAML that depends on mscorlib. 

We really need VS/IDE to handle mscorlib references in XAML seamlessly to reduce friction for migration experiences.

**Comment by vatsan-madhavan** [comment]
> > xmlns:sys="clr-namespace:System;assembly=System.Runtime"
> 
> That's not a ~good~great recommendation for folks that are migrating from .NET Framework. It incurs significant overhead in terms of having to fixup XAML that depends on mscorlib.
> 
> We really need VS/IDE to handle mscorlib references in XAML seamlessly to reduce friction for migration experiences.

**Comment by mgoertz-msft** [comment]
@vatsan-madhavan I totally agree. You should add your comments to the Roslyn issue.

**Comment by vatsan-madhavan** [comment]
@chenyj796 Hopefully you have a path forward now. Let's know if you are still blocked.

**Comment by chenyj796** [comment]
I declare xmlns as below:
```
xmlns:sys="clr-namespace:System;assembly=mscorlib"
```
It still causes two compiler errors (XLS0419, XLS0414) in Visual Studio 2019 (16.5.2) since application works fine.

Is there any plan to correct this behavior?

**Comment by mgoertz-msft** [comment]
Please direct your feedback to the Roslyn issue that this is dependent on: dotnet/roslyn#36274
