### ISSUE TITLE
TextBox IsReadOnly works differently when set as a property or from style in XAML

### ISSUE THREAD

**Issue by spaceman502** [dotnet/wpf#2444]
* .NET Core Version: 3.1
* Windows version: 10 1803
* Does the bug reproduce also in WPF for .NET Framework 4.8?: didn't try
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? no

 
 **Problem description:**
When marking TextBox with IsReadOnly="True", the behavior is not the same(wrong) as when assigned in a style with a setter.

 
 **Minimal repro:**

 ```
 <TextBox Text="description" IsReadOnly="True"/> -- grayed out with gray text -- wrong

  <TextBox Text="description"> -- no change from editable but can't change the text -- correct
           <TextBox.Style>
                  <Style TargetType="TextBox">
                           <Setter Property="IsReadOnly" Value="True"/>
                  </Style>
            </TextBox.Style>
  </TextBox>
```

![Untitled](https://user-images.githubusercontent.com/26051802/72548857-9029e480-385d-11ea-8532-1b1894a307a6.png)

**Comment by vatsan-madhavan** [comment]
This is what I see using the following configuration: 

- TargetFramework net472, runtime net48
- TargetFramework netcoreapp3.1, 3.1.100 SDK 

I'm on Win10 19543.1000 Insider Preview build. The key implication is that this build has .NET Framework 4.8 in it. 

`MainWindow.xaml`

```XAML
<Window x:Class="TestApp.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d"
        Title="{Binding RelativeSource={RelativeSource Mode=Self}, Path=TFM, Mode=OneWay}" Height="450" Width="400">
    <StackPanel>
            <TextBox IsReadOnly="True">
            <![CDATA[<TextBox IsReadOnly="True" />]]>
        </TextBox>

        <TextBox TextWrapping="Wrap" AcceptsReturn="True">
            <TextBox.Style>
                <Style TargetType="TextBox">
                    <Setter Property="IsReadOnly" Value="True"/>
                </Style>
            </TextBox.Style>
            <TextBox.Text>
              <![CDATA[
             <TextBox>
                <TextBox.Style>
                    <Style TargetType="TextBox">
                        <Setter Property="IsReadOnly" Value="True"/>
                    </Style>
                </TextBox.Style>
            </TextBox>
            ]]>
            </TextBox.Text>
        </TextBox>
    </StackPanel>
</Window>
```

`MainWindow.xaml.cs`
```C#
using System.Windows;

namespace TestApp
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            DataContext = this;
        }

#if NETCOREAPP
        public string TFM => "netcoreapp";
#endif
#if NETFRAMEWORK
        public string TFM => "netfx";
#endif
    }
}
```
![image](https://user-images.githubusercontent.com/20246435/72568171-5ca28680-386c-11ea-8d72-928c9f63e6e3.png)

Simple textboxes like those below also result in the same sort of result: 

```XAML
<TextBox Text="description" IsReadOnly="True"/> -- grayed out with gray text -- wrong

 <TextBox Text="description"> -- no change from editable but can't change the text -- correct
          <TextBox.Style>
                 <Style TargetType="TextBox">
                          <Setter Property="IsReadOnly" Value="True"/>
                 </Style>
           </TextBox.Style>
 </TextBox>
```


![image](https://user-images.githubusercontent.com/20246435/72568320-bc992d00-386c-11ea-81e1-e0486b9ec4bc.png)


In any of the configurations...

- I don't see any greying
- The textboxes are **not** editable 

Net is that I can't observe any bug here. 

/cc @SamBent

**Comment by spaceman502** [comment]
In my case, the text box is contained in a RowDetailsTemplate/DataTemplate of the Telerik's RadGridView and as you saw in the snapshot, the difference is there. I can close the issue until I have more time to devote to reproducing it.

**Comment by SamBent** [comment]
Perhaps it's in the scope of a trigger that sets IsEnabled=False if IsReadOnly=true, or some such thing.  Depending on how the trigger is declared, it might apply when setting IsReadOnly directly but not when setting it via Style (the [precedence rules](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/dependency-property-value-precedence?view=netframework-4.8) can be tricky).  

But it sounds like a consequence of Telerik's actions (or maybe yours), not a bug in WPF itself.  A repro would help settle the matter.

**Comment by spaceman502** [comment]
Since it can't be reproduced, I'll close this issue. Worst comes to worst, I'll open another one if the problem is reproduced.
