### ISSUE TITLE
Update documentation for newly added APIs in XamlReader

### ISSUE THREAD

**Issue by arpitmathur** [dotnet/wpf#2448]
Issue to pickup any documentation changes needed for the newly added APIs added to XamlReader as part of #2424, #2425.

// cc: @gomathip02

**Comment by arpitmathur** [comment]
This is currently pending on the docs team.

**Comment by arpitmathur** [comment]
@ryalanms Please ping me with any questions related to this issue

**Comment by ryalanms** [comment]
All documentation updates are tracked in the dotnet-api-docs repo and are in PR: https://github.com/dotnet/dotnet-api-docs/pulls?q=is%3Apr+wpf+RC1.
