### ISSUE TITLE
BaseCompatibilityPreferences.ReuseDispatcherSynchronizationContextInstance has wrong default value

### ISSUE THREAD

**Issue by ericstj** [dotnet/wpf#245]
* WPF Version: 3.0.0-alpha-27122-4 
* Windows version: Win 10 1809 (17763.195)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**
BaseCompatibilityPreferences.ReuseDispatcherSynchronizationContextInstance is defaulting to `true` on .NETCore but defaults to `false` on .NET 4.5 and later. 
 
 **Actual behavior:** 
BaseCompatibilityPreferences.ReuseDispatcherSynchronizationContextInstance is true.
 
 **Expected behavior:**
BaseCompatibilityPreferences.ReuseDispatcherSynchronizationContextInstance is false.
 
 **Minimal repro:**
Start an app and examine value of `BaseCompatibilityPreferences.ReuseDispatcherSynchronizationContextInstance`
 
Customer issue: https://github.com/dotnet/corefx/issues/33612.

**Comment by vatsan-madhavan** [comment]
Getting AppContext and [*]CompatibilityPreferences defaults to instantiate correctly is something we are yet to get to. These need to be done to get many important scenarios to work correctly (or work at all) - for e.g., high DPI behavior. This is in our queue as an important work item for the near future.

**Comment by ericstj** [comment]
@vatsan-madhavan  this was simply a case of the defaults being wrong in the port.  One of the flags was inverted so that instead of getting "latest" behavior, one flag was defaulted to "old" behavior.  I submitted a fix internally to fix this so that the port would be consistent with "latest" behavior.

**Comment by vatsan-madhavan** [comment]
closing - this should have been in the sdk for a while now. 

i've also done some additional work recently to ensure that all `BaseCompatibilityPreferences` values are initialized correctly as part of https://github.com/dotnet/wpf/pull/787
