### ISSUE TITLE
Visual Studio Crash when developing UWP project

### ISSUE THREAD

**Issue by gomathip02** [dotnet/wpf#2478]
Copied from VSO ID: 1011513

When in UWP project development, after I close the currently debuged application and try to select other tab with typed code, visual studio just stops respond and crashes. As it happens quite often, it creates VS for UWP hardly usable. Hope recorded logs will help.

Failure in WPF.... 

StackTraceString: <none>
HResult: 88980406
There are nested exceptions on this thread. Run with -nested for details
0:000> !pe -nested
Exception object: 54da11f8
Exception type:   System.Runtime.InteropServices.COMException
Message:          UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
InnerException:   <none>
StackTrace (generated):
    SP       IP       Function
    00CFE41C 0A5D22F8 PresentationCore_ni!System.Windows.Media.Composition.DUCE+Channel.SyncFlush()+0x7dcc30
    00CFE44C 09DFA8C4 PresentationCore_ni!System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean, System.Nullable`1<ChannelSet>)+0x454
    00CFE5F4 09E0D5FB PresentationCore_ni!System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr)+0xeb
    00CFE648 09DFB137 PresentationCore_ni!System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)+0xf7
    00CFE714 09DF974B PresentationCore_ni!System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)+0x2b
    00CFE734 57EB6ED1 WindowsBase_ni!MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)+0xa1
    00CFE770 57EB6E1C WindowsBase_ni!MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)+0x6c
    00CFE780 57EB6CE2 WindowsBase_ni!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)+0x52
    00CFE7A0 57EB6C76 WindowsBase_ni!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)+0x86
    00CFE7E4 57EB5052 WindowsBase_ni!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)+0x142
    00CFE840 57EB66F4 WindowsBase_ni!MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)+0xf4

StackTraceString: <none>
HResult: 88980406

Nested exception -------------------------------------------------------------
Exception object: 54da11f8
Exception type:   System.Runtime.InteropServices.COMException
Message:          UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
InnerException:   <none>
StackTrace (generated):
    SP       IP       Function
    00CFE41C 0A5D22F8 PresentationCore_ni!System.Windows.Media.Composition.DUCE+Channel.SyncFlush()+0x7dcc30
    00CFE44C 09DFA8C4 PresentationCore_ni!System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean, System.Nullable`1<ChannelSet>)+0x454
    00CFE5F4 09E0D5FB PresentationCore_ni!System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr)+0xeb
    00CFE648 09DFB137 PresentationCore_ni!System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)+0xf7
    00CFE714 09DF974B PresentationCore_ni!System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)+0x2b
    00CFE734 57EB6ED1 WindowsBase_ni!MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)+0xa1
    00CFE770 57EB6E1C WindowsBase_ni!MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)+0x6c
    00CFE780 57EB6CE2 WindowsBase_ni!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)+0x52
    00CFE7A0 57EB6C76 WindowsBase_ni!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)+0x86
    00CFE7E4 57EB5052 WindowsBase_ni!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)+0x142
    00CFE840 57EB66F4 WindowsBase_ni!MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)+0xf4

StackTraceString: <none>

**Comment by singhashish-wpf** [comment]
@gomathip02 We'll need a minimal repro to check this further. Is it possible to share one?
