### ISSUE TITLE
WPF should build against latest CoreFx packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/wpf#248]
Currently this repository is set up to get its NETCoreApp assemblies as an implicit framework reference from the SDK.

This project does not define a RuntimeFrameworkVersion, so it gets the default implicit framework references.
https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj#L5

And it's picking up the 3.0 dotnet cli + SDK that will have "latest" (that's made its way to the SDK repo).
https://github.com/dotnet/wpf/blob/b9a9a501b7118185ea31e48aa9d79b8a385e8a98/global.json#L3

However, its picking up much older versions of packages that build on top of NETCoreApp.
https://github.com/dotnet/wpf/blob/b9a9a501b7118185ea31e48aa9d79b8a385e8a98/eng/Versions.props#L7-L8

This will "work" in most cases, since we make compatible changes to the surface area, but it has a couple draw backs:
1. If the packages have implementation assemblies that aren't in the shared framework, your tests in this repo will be running with **much older** implementation than what gets bundled into the desktop shared framework.
2. When we move types down you'll get compiler errors.  See https://github.com/dotnet/corefx/issues/34447.

These dependencies need to change to be the latest packages published from CoreFx and you should have a subscription set up so that maestro auto updates them.

**Comment by rladuca** [comment]
@danzil This will have to be updated, as well, in our internal Arcade based repositories.

**Comment by rladuca** [comment]
@stevenbrix Can you look into this being update for this repo?  We'll probably have to work by hand (for now) in internal prototypes.

**Comment by ericstj** [comment]
FWIW the internal dotnet-trusted repo was doing this correctly, as well as [WinForms](https://github.com/dotnet/winforms/blob/73ede5b00cc1ae2e00054debc178dbd3f6e69020/eng/Versions.props#L10-L20).

**Comment by vatsan-madhavan** [comment]
@stevenbrix, We should be updating versions.props file with latest preview versions of packages like System.Security. Ideally, we'd setup a DARC subscription for these so that these versions are always updated automatically.

**Comment by danzil** [comment]
@stevenbrix, see also typo at https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj#L102 
SystemSecurityPermissionsVersion instead of SystemSecurityVersion

**Comment by stevenbrix** [comment]
i'll take a look, thanks!

**Comment by stevenbrix** [comment]
@ericstj is there a darc subscription we can add for these, or do we just need to manually update these to match winforms?

**Comment by ericstj** [comment]
You should be able to subscribe to corefx /cc @safern

**Comment by safern** [comment]
Yes, you need to add a subscription to corefx directly in darc. Please reach offline if you need any help doing that, but corefx is now publishing everything into BAR, so once you have the subscription correctly, you should be able to run darc to update you corefx versions.

**Comment by AdamYoblick** [comment]
@ericstj The process for updating the corefx packages in winforms is still very much manual because I don't think corefx was publishing using darc in the past. We could use some guidance on how to automate this using darc.

Do they have artifacts we can consume now in our version.details.xml ?

**Comment by AdamYoblick** [comment]
Ahh nevermind, I didn't see Santiago's comments. I will set up the subscriptions in winforms as well.
