### ISSUE TITLE
Fails to build .NET Core WPF app using x86 "dotnet build "

### ISSUE THREAD

**Issue by ASuurkuusk** [dotnet/wpf#2483]
* .NET Core Version: 3.1.101
* Windows version: 10.0.18362
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

 **Problem description:**

I'm not able to build a .NET Core WPF app from the command line using the x86 version of dotnet.exe. It seems like the "Program files (x86)" text gets expanded to "Program Files %28x86%29" when used as the AssemblyFile argument to UsingTask in "Microsoft.WinFX.targets".

I assume this can be caused by a bug in "dotnet build", rather than WPF.
 
 **Actual behavior:**

`"c:\Program Files (x86)\dotnet\dotnet.exe" build` prints error:

> C:\Program Files (x86)\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(228,9): error MSB4062: The "Microsoft.Build.Tasks.Windows.MarkupCompilePass1" task could not be loaded from the assembly C:\Program Files %28x86%29\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.WindowsDesktop\tools\netcoreapp2.1\PresentationBuildTasks.dll. Could not load file or assembly 'C:\Program Files %28x86%29\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.WindowsDesktop\tools\netcoreapp2.1\PresentationBuildTasks.dll'. The system cannot find the path specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Sci\Tests\DotnetWpfTest\DotnetWpfTest.csproj]

 
 **Expected behavior:**

It should be possible to  build a simple WPF app using both x86 and x64 .NET Core.

 **Minimal repro:**

Run this in a command prompt with both .NET Core 3.1 SDK (x64) and .NET Core Core 3.1 (x86) installed:

    md DotnetWpfTest2
    cd DotnetWpfTest2
    dotnet new wpf

    REM dotnet build will work
    dotnet build

    REM '"c:\Program Files (x86)\dotnet\dotnet.exe" build' causes error 
    "c:\Program Files (x86)\dotnet\dotnet.exe" build

**Comment by vatsan-madhavan** [comment]
This is the same as #2415 - please look for updates there.

**Comment by vatsan-madhavan** [comment]
I can confirm that I'm able to reproduce this problem. 

```
C:\Temp\wpf\test13
λ dotnet new globaljson --sdk-version 3.1.101
The template "global.json file" was created successfully.

C:\Temp\wpf\test13
λ "C:\Program Files (x86)\dotnet\dotnet.exe" new wpf
Getting ready...
The template "WPF Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Temp\wpf\test13\test13.csproj...
  Restore completed in 145.22 ms for C:\Temp\wpf\test13\test13.csproj.

Restore succeeded.


C:\Temp\wpf\test13
λ "C:\Program Files (x86)\dotnet\dotnet.exe" build
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 31.82 ms for C:\Temp\wpf\test13\test13.csproj.
C:\Program Files (x86)\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(225,9): error MSB4062: The "Microsoft.Build.Tasks.Windows.MarkupCompilePass1" task could not be loaded from the assembly C:\Program Files %28x86%29\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.WindowsDesktop\tools\netcoreapp2.1\PresentationBuildTasks.dll. Could not load file or assembly 'C:\Program Files %28x86%29\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.WindowsDesktop\tools\netcoreapp2.1\PresentationBuildTasks.dll'. The system cannot find the path specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Temp\wpf\test13\test13.csproj]

Build FAILED.

C:\Program Files (x86)\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(225,9): error MSB4062: The "Microsoft.Build.Tasks.Windows.MarkupCompilePass1" task could not be loaded from the assembly C:\Program Files %28x86%29\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.WindowsDesktop\tools\netcoreapp2.1\PresentationBuildTasks.dll. Could not load file or assembly 'C:\Program Files %28x86%29\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.WindowsDesktop\tools\netcoreapp2.1\PresentationBuildTasks.dll'. The system cannot find the path specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Temp\wpf\test13\test13.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.30
```

**Comment by vatsan-madhavan** [comment]
Closing this in favor of #2415.
