### ISSUE TITLE
WPF app - 'Window' is not supported??

### ISSUE THREAD

**Issue by WrongBit** [dotnet/wpf#2485]
Config: Win10x64 with autoupdate, installed 28 Jan evening. VS 16.4.3, C#

I create WPF project. VS shows WPF designer for main window (with empty designer and error "Invalid markup"). I compiled project, but designer still shows error and... completely crazy warning in XAML editor: "Window is not supported in WPF project"! (and same warning for 'Grid' element)

**Comment by gomathip02** [comment]
@chabiss -Can you pls look into this issue?

**Comment by WrongBit** [comment]
Well, after update of VS the problem disappears. But the way how it appears makes me crazy:
1. I installed VS long time ago. Everything works perfect. I do not autoupdate VS - only manual way.
2. One beautiful day Win10 installs its updates and VS starts behaving improperly.

Question: WHERE IS THE LINK? Why underlying OS affects Visual Studio?

**Comment by deccer** [comment]
I am sorry for commenting on a closed issue.

@WrongBit I just faced the same issue, I'm on 16.9.3 (updated yesterday) and my wpf project didn't want to render in the designer anymore, same error "Invalid Markup" and the errorlist was full of "XXX not supported in WPF project". However building and running the project works just fine.

The usual solution with VS is
- close it
- kill `XDesProc.exe` (if still running)
- delete `bin` and `obj` folders of your project
- restart vs
- rebuild project
- switching to the designer works again

HTH

**Comment by WrongBit** [comment]
@deccer : cool, thanks! Casual "clean-up and restart" solution. With one important detail... all of that must be made by VS, not me! :)) (including rebuilding project) WinForms for years didn't need any build - just open and design. WPF follows so unprofessional way that I scare to touch it.
