### ISSUE TITLE
WPF Tree View Freeze / Hang

### ISSUE THREAD

**Issue by pjchristmas** [dotnet/wpf#2490]
* .NET Framework 4.8 with [latest patch](https://support.microsoft.com/en-us/help/4534130/kb4534130-cumulative-update-for-net-framework) that claimed to fix similar sounding bug.
* Windows version: (`winver`): Win10 1803

 **Problem description:**
 Identical to issue [1962](https://github.com/dotnet/wpf/issues/1962)
but not fixed by [update listed there](https://support.microsoft.com/en-us/help/4534130/kb4534130-cumulative-update-for-net-framework).
We have a virtualized Tree View with up to 30k items. Going to the bottom and scrolling up 51 times (or using scroll wheel) will cause it to freeze. If I leave it up for an hour it will usually come back(or maybe it's just logging out and back in that kicks it out of the layout loop)
We've tried changing the virtualization settings (ScrollUnit, VirtualizationCacheLength, VirtualizationCacheLengthUnit and VirtualizationMode.Recycling) but none had any effect.

 **Minimal repro:**
Attached app, just modified the one from previous posting and added reproducing data.
[HangTest.zip](https://github.com/dotnet/wpf/files/4154025/HangTest.zip)

Looking for a hero @SamBent

**Comment by SamBent** [comment]
@pjchristmas  - Just saw this, and looked at your repro just enough to confirm that it hangs, but for a different root cause than in 1962.    I don't know the root cause yet.

Can you speak to the business case for fixing this in .NET servicing?   How often does it happen, when did it start happening, what fraction of the data sets hit it, is there a reliable workaround - that sort of thing.  (You've alluded to some of the already, I just want to fill in more blanks.)

BTW, I didn't get an email six days ago when you tagged me.  Perhaps GitHub only sends email when you tag me in a new comment, not when you add the tag in an edit of an existing comment?

**Comment by pjchristmas** [comment]
**Business case:** This is important to key products/customers at National Instruments. We will be elevating through service channels as well.
**Reproducing:** It happens every time (you do upward scrolling) for certain data sets. The particulars of the dataset are customer driven, and we've seen it in a number of their files, but not all. Some combination of size and shape of tree seem to matter.
**Workaround:** We don't have one yet. If you have ideas, we'd love to try them. Our datasets get big enough that turning off virtualization is not an option.

Thanks for looking into this @SamBent .

**Comment by BradenCalderMurphy** [comment]
Hi, have there been any updates with regards to this?

**Comment by mattdev** [comment]
We're also having the same issue here. Put a large number of nodes in a virtualized TreeView, scroll up and down a bunch of times and it'll eventually hang while doing layout.

**Comment by BradenCalderMurphy** [comment]
So I started using https://sourceforge.net/projects/treeviewadv/ (it's on nuget) in the meantime but actually it's great, super fast and responsive. I used it in WPF with the "WindowsFormsHost"

**Comment by SamBent** [comment]
We've fixed a set of issues exposed by this bug (and variants supplied by @pjchristmas via MS customer support).  Expect to see these fixes soon in a .NET Framework update and in .NET Core.

**Comment by fabiant3** [comment]
@SamBent - let's check in the .NET Core fixes and update this thread.

**Comment by SamBent** [comment]
Fix ported to 3.1.19, 5.0.0, and 6.0.
