### ISSUE TITLE
The .Net Core WPF program UI errors

### ISSUE THREAD

**Issue by ssc19940105** [dotnet/wpf#2493]
* .NET Core Version: 3.1.1
* Windows version: 10.0.18363
* Graphics card:Geforce RTX 2070
* Graphics driver:441.87
* Does the bug reproduce also in WPF for .NET Framework 4.8?:No
* Is this bug related specifically to tooling in Visual Studio ?:Xaml Designer
The .Net Core WPF program UI may display errors on some computers. UI elements disappear and are replaced by gray blocks.

**Comment by gomathip02** [comment]
@ssc19940105 - Pls share repro app, screenshots and also pls describe the problem in detail.

**Comment by ssc19940105** [comment]
I will provide the required information later

**Comment by ssc19940105** [comment]
This is the video of the program running.
[NC31 WPF UI Render Error.zip](https://github.com/dotnet/wpf/files/4191282/NC31.WPF.UI.Render.Error.zip)

**Comment by weltkante** [comment]
@rladuca @vatsan-madhavan  the bot seems to be misbehaving and closing the issue even though a response by the issue owner has been given?

**Comment by rladuca** [comment]
@weltkante Thanks for spotting it, sorry about that @ssc19940105, we'll look into the bot.

**Comment by rladuca** [comment]
This is likely related to #707.  Can you check if you have one of the culprits listed in the bug installed on your system?  I believe the list includes Nahimic and Realtek right now, but there are likely other pieces of SW incorporating these bad behaviors.

**Comment by rladuca** [comment]
@ssc19940105 This looks like an instance of #707.  Likely this is due to a specific component interfering with WPF.  Check for things like Realtek Sonic Studio and Nahimic software.

**Comment by ssc19940105** [comment]
The program renders correctly after I try to close NahimicService.But I don't understand why .Net Framework is not affected.Is there any difference between them

**Comment by rladuca** [comment]
@ssc19940105 This isn't a WPF issue but an issue with Nahimic's software.  They are trapping certain calls and this is interfering with WPF rendering.  In .NET Framework they don't seem to do this, meaning the software is detecting either a .NET or a WPF process and is not injecting into it.  As was stated in the linked bug, WPF can't react to all possible changes like this, nor should it.

We're working as best we can to link up with various software vendors and make sure these issues are resolved.

For now I'll close this.  Please use #707 to add onto the information as we are still monitoring this and working to try and get the offending software updated appropriately

**Comment by Squall-Leonhart** [comment]
@jorisvergeer the software might be crapware, but it was previously not causing this prior to recent windows 10 cumulative updates unless a severely out dated version was installed.

Like mentioned in other posts here Nahimic did introduce measures to prevent it from causing this, and these measures have been rendered ineffective as a result of some change in the OS.
