### ISSUE TITLE
Calendar. DisplayMode="Year" blank

### ISSUE THREAD

**Issue by kaanlab** [dotnet/wpf#2496]
* .NET Core Version: 3.1.100
* Windows version: 1903
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
 
 **Problem description:** Calendar is displayed as an empty square on the Form when you choose DisplayMode="Year" in the calendar settings
 
 **Minimal repro:** `<Calendar DisplayMode="Year" />`

**Comment by arpitmathur** [comment]
@kaanlab I can't reproduce this issue you mentioned using the minimal repro that you provided. Can you please add further details or provide a sample application if you want to us to investigate this issue?

**Comment by kaanlab** [comment]
This is strange, but now everything works. ¯＼(º_o)/¯
Thank you!
