### ISSUE TITLE
VB.NET WPF does not compile on .NET 5, fails with MC1000

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#2514]
@Nukepayload2 

- .NET Core 3.0/3.1 SDK's do not support VB on WindowsDesktop. 
- Building .NET Framework targets using the SDK Style projects are primarily support for migration scenarios only - it is not intended as a new-feature for .NET Framework development. 

Since migration to .NET Core 3.1 is not fully enabled for VB projects, we do not recommend building VB based WindowsDesktop (i.e, WPF or WinForms) projects using SDK style projects on .NET Core 3.x.

_Originally posted by @vatsan-madhavan in https://github.com/dotnet/wpf/issues/2274#issuecomment-580033712_

Also \originally reported at https://developercommunity.visualstudio.com/comments/893563/view.html by: 

>SeverityCodeDescriptionProjectFileLineSuppression State Error MC1000 Unknown build error, 'Could not find assembly 'mscorlib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly.' WpfApp1C:\Program Files\dotnet\sdk\5.0.100-alpha.1.20064.2\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets225

VB will be supported on .NET 5 and this should be fixed there.

**Comment by ryalanms** [comment]
Fixed in .NET 5.0 and later.
