### ISSUE TITLE
Window.xaml Resource cannot be found in Debug Mode

### ISSUE THREAD

**Issue by SnowyPainter** [dotnet/wpf#2551]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
 Version:   2.1.802
 Commit:    177d0b2525
* Windows version: (`winver`)
WINDOWS 10.0.18362
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No
YES
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? If yes, please file the issue via the instructions [here](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/master/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:** 
I'm using vs2019
I added a window, what named "UserWindow" 
and I set this window to startupuri. so, I ran program, but program error reported me "userwindow.xaml cannot be found'.
I checked folder and namespaces but It is ok.
I ran program with realese mode, then It works
like this [thread](https://developercommunity.visualstudio.com/content/problem/285960/xaml-resource-not-found-when-debugging.html)
![image](https://user-images.githubusercontent.com/54142982/74245222-0408c100-4d26-11ea-8b59-c1498a44a4a1.png) cannot be found rescource 'userwindow.xaml'
 **Actual behavior:** 
 add window, and set the startupuri
 **Expected behavior:**
 show well the window
 **Minimal repro:**
i dont know sorry
maybe? 

[app and window error.zip](https://github.com/dotnet/wpf/files/4186192/app.and.window.error.zip)

**Comment by SnowyPainter** [comment]
No NO I"m sorry that I miss wrote verison that .net framework.
it's 4.7.2 sorry

**Comment by gomathip02** [comment]
@SnowyPainter - 1. Have you tried cleaning the solution? 2. Also, can you pls share the MSbuild binary logs by following the below link? https://github.com/Microsoft/msbuild/blob/master/documentation/wiki/Binary-Log.md

**Comment by SnowyPainter** [comment]
> @SnowyPainter - 1. Have you tried cleaning the solution? 2. Also, can you pls share the MSbuild binary logs by following the below link?
> https://aka.ms/msbuild/Binary-Log

I'm sorry that. I just clean up the code at Release Mode.
I tried clean up code at Debug Mode,
It works.

Thank you I'll close it
