### ISSUE TITLE
WPF .netcoreapp3.1 win-x86 app cannot load net35 x86 dll.

### ISSUE THREAD

**Issue by thudugala** [dotnet/wpf#2597]
* .NET Core Version: 3.1.1

![image](https://user-images.githubusercontent.com/4112014/75638032-06a86780-5c8f-11ea-9522-594297640fd6.png)

* Does the bug reproduce also in WPF for .NET Framework 4.8?: Could not try, as depecency to netstandard 2.1

 **Problem description:**

WPF .netcoreapp3.1 win-x86 app cannot load net35 x86 dll. When Process is AMD A6-9225
 
 **Actual behavior:** 

Throws

Could not load file or assembly 'CefSharp, Version=1.25.0.25466, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.
 
 **Expected behavior:**
 
Load the dll without any issue

**Comment by vatsan-madhavan** [comment]
@thudugala can you provide a self-contained repro project we can use to investigate the issue?

**Comment by thudugala** [comment]
@vatsan-madhavan please give me some time to get sample app ready as I only get access to customer PC on agreed time slots

**Comment by vatsan-madhavan** [comment]
Sure, no problems. Even if you can create a test app that can recreate the symptoms, that would do the trick. 

I tried to create a basic WPF app with NuGet references to different versions of CefSharp, and none of them seemed to have net35 specific assets. I tried going back to old versions of CefSharp and still couldn't spot one with net35 assets. 

I suspect that enumerating the versions of the packages, TFM's involved etc. is where most of the relevant information lies.

**Comment by thudugala** [comment]
Try using below nuget (it's internal nuget package)

[cefsharp.wpf.1.25.7.25471.nupkg.zip](https://github.com/dotnet/wpf/files/4233813/cefsharp.wpf.1.25.7.25471.nupkg.zip)

**Comment by thudugala** [comment]
Hi @vatsan-madhavan,

Here is the sample app that does not work. Please use the above nuget package. for cefsharp reference.   

[CefSharpNotLoading.zip](https://github.com/dotnet/wpf/files/4242686/CefSharpNotLoading.zip)

**Comment by thudugala** [comment]
Hi I'm getting error on this PC also

![image](https://user-images.githubusercontent.com/4112014/75201731-1ecf4100-57ce-11ea-92b7-6e266728a15f.png)

**Comment by amaitland** [comment]
Do the machines have the relevant Visual  C++ version installed? 

.Net Core misleadingly says incorrect format when VC++ is missing.

**Comment by thudugala** [comment]
Installed Microsoft Visual C++ 2015 Redistributable Update 3 RC (https://www.microsoft.com/en-us/download/details.aspx?id=52685)

But did not help

**Comment by amaitland** [comment]
You'll need to match the exact version of `VC++`. `2015-19` are compatible, prior to that each version had a specific runtime.

**Comment by thudugala** [comment]
@amaitland I'm bit confused, This is Windows 10 1903. What is the exact Microsoft Visual C++ Redistributable I need to install? Can you help ?

**Comment by amaitland** [comment]
What exactly is the confusion? 

> The Microsoft C++ (MSVC) compiler toolsets in Visual Studio 2013 and earlier don't guarantee binary compatibility across versions. You can't link object files, static libraries, dynamic libraries, and executables built by different versions. The ABIs, object formats, and runtime libraries are incompatible.

As per https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019

If you installed `VS 2015` and the app requires `VS2010` then it's not going to work.

> Try using below nuget (it's internal nuget package)
> 
> [cefsharp.wpf.1.25.7.25471.nupkg.zip](https://github.com/dotnet/wpf/files/4233813/cefsharp.wpf.1.25.7.25471.nupkg.zip)

Sounds like you are using a custom build, hopefully whoever built it left you some documentation. I can only speculate that it's probably `VS2010` or `VS2012`. Find a machine that has your existing app installed and look at what's installed for a hint.

If you are porting to `.Net Core` now is the time to upgrade to a supported version of `CefSharp`.

**Comment by thudugala** [comment]
Install Microsoft Visual C++, 2017,2015,2013,2012,2010,2008

But did not help

![image](https://user-images.githubusercontent.com/4112014/75833488-0a1e2900-5e1e-11ea-9630-d6ed7d8cc9bb.png)

We are looking into updating CefSharp. But for now we have live with it. It works in most of the computes.

**Comment by amaitland** [comment]
> It works in most of the computes.

In my opinion if it works on some machines then it's very unlikely a bug in `.Net Core`, more likely something missing from your environment. 

Have you analysed a working machine? Have you determined what's installed?

Installing every `VC++` can be problematic. Once you identify the required version, you can bin deploy the `VC++` dlls with your application to eliminate such problems.

**Comment by vatsan-madhavan** [comment]
@thudugala When I try to reproduce your problem using your project and your NuGet package, I'm unable to reproduce it. msbuild, Visual Studio, dotnet.exe - all 3 seem to build just fine.

**Comment by thudugala** [comment]
@vatsan-madhavan Yes. It build fine. But you cannot run it on above PC's (can run on most PC's)

**Comment by vatsan-madhavan** [comment]
Can you capture a crash dump of the failure and share? 

https://aka.ms/user-mode-dump-files-howto

**Comment by thudugala** [comment]
Will do, please wait until I get permission to access the PC
