### ISSUE TITLE
Merging Avalonia with WPF

### ISSUE THREAD

**Issue by TeddyAlbina** [dotnet/wpf#265]
After a lot of code reading i think it's possible to merge Avalonia with Wpf code to produces a cross platform standardized UI for .net core. 

It's someone interested to start ?

**Comment by lindexi** [comment]
I do not think this is a good idea.

**Comment by karelz** [comment]
Seems to be covered already here: #59. I'd suggest to close it as duplicate ...

**Comment by stevenbrix** [comment]
Duplicate of #59
