### ISSUE TITLE
Cannot show "open file dialog" window issue in WPF Apps

### ISSUE THREAD

**Issue by DotNetAppCompatFeiWang** [dotnet/wpf#2663]
* .NET Core Version: 5.0.100-preview.1.20125.9
* Windows version: Windows 10 1809
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/master/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:** Click Open File dialog button on the app.
 
 **Actual behavior:** Messagebox says  "Cannot show a file dialog unless application is running in UserInterActive mode "
 
 **Expected behavior:** Open file dialog window show.
 
 **Minimal repro:**using Microsoft.Win32;

 private void button_Click(object sender, RoutedEventArgs e)
  {
      OpenFileDialog openFileDialog = new OpenFileDialog();
      try
      {
          openFileDialog.ShowDialog();     // Exception on this line
      }
     catch (Exception ex)
      {
              MessageBox.Show(ex.Message);
       }
  }

More detail and repro machine could be found at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1074622

We are testing this app https://github.com/NuGetPackageExplorer/NuGetPackageExplorer and most WPF apps affect by this issue.
@dotnet-actwx-bot  FYI

**Comment by vatsan-madhavan** [comment]
![image](https://user-images.githubusercontent.com/20246435/75472708-c2446100-5948-11ea-830b-c40badd808b4.png)

**Comment by vatsan-madhavan** [comment]
```
---------------------------

---------------------------
System.InvalidOperationException: Cannot show a file dialog unless the application is running in UserInteractive mode.

   at Microsoft.Win32.CommonDialog.ShowDialog()

   at test003.MainWindow.OnOpenFileDialogButtonClicked(Object _, RoutedEventArgs __) in C:\Temp\wpf\test003\MainWindow.xaml.cs:line 34
---------------------------
OK   
---------------------------

```

![image](https://user-images.githubusercontent.com/20246435/75472780-e0aa5c80-5948-11ea-9184-e187d167af89.png)

**Comment by rladuca** [comment]
We pivot on [Environment.UserInteractive](https://source.dot.net/#PresentationFramework/Microsoft/Win32/CommonDialog.cs,75), is that not returning the correct value in 5.0?

**Comment by rladuca** [comment]
Looks related to https://github.com/dotnet/runtime/issues/1724#issuecomment-574728941

**Comment by vatsan-madhavan** [comment]
Yeah, doesn't look like a WPF bug. Here is a self-contained repro. 

![image](https://user-images.githubusercontent.com/20246435/75474203-6929fc80-594b-11ea-9637-8485fe8b3d57.png)

```xaml
<Window x:Class="test003.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:sys="clr-namespace:System;assembly=mscorlib"
        xmlns:local="clr-namespace:test003"
        mc:Ignorable="d"
        Title="MainWindow" Height="80" Width="250">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto"/>
            <ColumnDefinition Width="Auto"/>
        </Grid.ColumnDefinitions>
        <Button Grid.Row="0" Grid.Column="0" Click="OnOpenFileDialogButtonClicked" Content="Open File Dialog">
            <x:Code>
                <![CDATA[
        void OnOpenFileDialogButtonClicked(object _, RoutedEventArgs __)
        {
            var dlg = new Microsoft.Win32.OpenFileDialog();
            try
            {
                dlg.ShowDialog();
            }
            catch (Exception e)
            {
                MessageBox.Show(e.ToString());
            }
        }                
                ]]>
            </x:Code>
        </Button>
        <Label Grid.Row="1" Grid.Column="0" Content="Environment.UserInteractive: " FontWeight="Bold"/>
        <Label Grid.Row="1" Grid.Column="1" Content="{x:Static sys:Environment.UserInteractive}"/>
    </Grid>
</Window>
```

/cc @danmosemsft, @merriemcgaw 

This has the potential to break WinForms as well.

**Comment by merriemcgaw** [comment]
Thanks for the heads up @vatsan-madhavan . @Vino-Wang you might run into this testing WinForms. Can you see if we're impacted? File a WinForms issue to track if you do hit it?

**Comment by danmosemsft** [comment]
Tracking with https://github.com/dotnet/runtime/issues/32929

Is this a preview 1 blocking issue? 

If so, I suggest a temporary workaround in WPF code. Previous to my change, Environment.UserInteractive was hard coded to true. My change copied the .NET Framework implementation over (at least, attempted to.). The quickest workaround is for you to replace the 3 uses of Environment.UserInteractive in dotnet/wpf with hard coded "true". This will give the exact same behavior as in 3.1.

I don't see use of this in Winforms - I guess it uses the CommonDialog in WPF.

**Comment by vatsan-madhavan** [comment]
It doesn't seem to affect winforms.
