### ISSUE TITLE
A recent change in XamlObjectReader introduced the use of Linq, which is unnecessary

### ISSUE THREAD

**Issue by danzil** [dotnet/wpf#268]
* .NET Core Version: 3.0.100-preview-010024
* Windows version: 17763
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

**Problem description:**
A recent change in XamlObjectReader #73 introduced the use of Linq, which is unnecessary and ads extra dll loads.

**Comment by karelz** [comment]
Fixed in #269
