### ISSUE TITLE
WPF test framework? 

### ISSUE THREAD

**Issue by MattHyman** [dotnet/wpf#2707]
Is there an officially recommended test framework/harness for WPF? What are the recommended best practices for testing/validating a WPF app through automation?

**Comment by lindexi** [comment]
I want a modern UI Test framework or tool

**Comment by SamBent** [comment]
The WPF team has no official recommendation for any particular test framework.  The community's experience and insights are welcome here.

**Comment by lindexi** [comment]
We write a test tool [dotnet-campus/CUnit](https://github.com/dotnet-campus/CUnit ) that can help we naming the test method. But it is a  community's test tool.

**Comment by mrlacey** [comment]
I've had success using https://github.com/microsoft/WinAppDriver
