### ISSUE TITLE
WPF template used by dotnet cli should include a glob to add auto-dependency between .xaml and .xaml.cs files

### ISSUE THREAD

**Issue by jongleur1983** [dotnet/wpf#271]
I'd be happy to create a PR for this, but couldn't find where the project template is defined:

In classic .NET Framework WPF applications the XAML files (.xaml) are dependentUpon their code-behind partials (.xaml.cs).
This is reflected in the VS solution explorer.

For WPF on Core3 this is not yet the case. It would be easy to add a glob that wildcards this dependency by default:

```xml
<ItemGroup>
  <Compile Update="**\*.xaml.cs" DependentUpon="%(Filename)" />
</ItemGroup>
```

If someone could point me to the repository and/or location where the wpf project template is defined I'd be happy to issue a PR to add that.

**Comment by alejandro5042** [comment]
+1

I have temporarily put the below workaround in our `Directory.Build.targets` file. It is specifically in the `.targets` file because it has to be done after the `csproj` file is parsed and all items have been added.

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!--
    This file is automatically imported at the end of every .csproj file.
    
    See: https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2017#directorybuildprops-and-directorybuildtargets
  -->
  
  <Choose>
    <When Condition="'$(UsingMicrosoftNETSdk)' == 'true'">
      <ItemGroup Condition="'$([MSBuild]::IsRunningFromVisualStudio())' == 'true'">
        <!--
          In .NET Core projects, we don't have to specify .cs files because the project imports them automatically. However, the current mechanism does automatically do any Solution Explorer nesting; for example, nesting Dialog.xaml.cs under Dialog.xaml.
        
          In this ItemGroup, we add nesting by updating items that follow pre-determined nesting patterns and giving them DependentUpon metadata. We will only do this in Visual Studio, since this: a) wildcard globbing is CPU/disk expensive; b) this metadata should not affect the build.
        
          Note: We use $(Filename), which is the *basename* of the file, with an optional extension. We do not include any path information since "Path is not supported for [DependentUpon] metadata, it must be a file name, which must be under the same folder." Source: https://developercommunity.visualstudio.com/content/problem/106280/dependentupon-files-in-new-csproj-format-not-group.html
        -->
        
        <!-- Nest .xaml.cs files under their .xaml files. -->
        <Compile Update="**/*.xaml.cs" DependentUpon="%(Filename)" />
        
        <!-- Nest .g.cs files under their .tt files. -->
        <Compile Update="**/*.g.cs" DependentUpon="$([System.IO.Path]::GetFileName('%(Filename)')).tt" />
      </ItemGroup>
    </When>
  </Choose>
</Project>
```

Similar code should probably go in this file:
 
- C:\Program Files\dotnet\sdk\3.0.100-preview-010006\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.NET.Sdk.WindowsDesktop.targets

But I have not yet found the sources for this file on GitHub.

**Comment by wjk** [comment]
While I agree with this suggestion in theory, @alejandro5042's suggestion is _not_ the correct way to do this. We should instead use [the built-in Visual Studio support for dependent file detection](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/automatic_DependentUpon_wireup.md). This would require a change in the XAML file defining build metadata for XAML files, not the targets file. However, AFAIK the XAML file we need to modify has not yet been open-sourced.

**Comment by alejandro5042** [comment]
Awesome! Did not know about CPS, looks interesting.

I have verified that this in our `Directory.Build.props`:

```xml
<ProjectCapability Include="DynamicDependentFile"/>
<PropertyPageSchema Include="$(MSBuildThisFileDirectory)\ProjectItemsSchema.xaml" />
```

And the side `ProjectItemsSchema.xaml` file:

```xml
<ProjectSchemaDefinitions xmlns="http://schemas.microsoft.com/build/2009/properties">
  <ContentType Name="PageXaml" DisplayName="XAML Page" ItemType="Page">
    <NameValuePair Name="DependentExtensions" Value=".xaml.cs" />
  </ContentType>
</ProjectSchemaDefinitions>
```

Works as well.

**Comment by stevenbrix** [comment]
The project templates were just added with #489. Is this something that can be done now?

**Comment by vatsan-madhavan** [comment]
This is not applicable to C# project template. Rather, this is something that applues to the WindowsDedktop Sdk. 

We took a fix similar to this recently. Is this still a problem? 

/Cc @nguerrera

**Comment by rladuca** [comment]
This is fixed, please re-open it if you think there is still an issue.
