### ISSUE TITLE
Startup Performance Worse than .Net Framework 4.8

### ISSUE THREAD

**Issue by jtg15** [dotnet/wpf#2736]
.NET Core 3.1.101
Windows version 1909
Does the bug reproduce also in WPF for .NET Framework 4.8?: No

I noticed that .NET Core WPF feels noticeably more sluggish than when using .NET Framework WPF especially with startup times.

I searched around for some other issues related to performance and I found this https://github.com/dotnet/wpf/issues/1549. Using the same repo here: https://github.com/rladuca/NetCorePerformanceTest, I profiled it and I screenshotted the results.

![perfNetLeftCoreRight](https://user-images.githubusercontent.com/3445860/76169427-9b064480-613d-11ea-8409-15cad63b6e16.png)

The .NET Core app is using about 2-3x more CPU time on startup and from my measurements it is taking about 400-500ms more to show the window. The render time seems to have been fixed but startup/construction time still seems to have regressed significantly.

With an empty WPF project on .NET Core and .NET Framework the results are similar.

![2020-03-08 (2)](https://user-images.githubusercontent.com/3445860/76169526-ab6aef00-613e-11ea-878e-fd37fbdb4a4f.png)

**Comment by rladuca** [comment]
This is a function of the difference between ngen and ReadyToRun/crossgen.  We already have a tracking bug in WPF (#1748) for this and a companion bug here: https://github.com/dotnet/runtime/issues/13339.

I'm going to close this as a duplicate, please add your comments and upvotes to the dotnet/runtime bug.
