### ISSUE TITLE
[Loc] The names of WPF Core project templates are not localized but WPF Framework did

### ISSUE THREAD

**Issue by gomathip02** [dotnet/wpf#2770]
Copied from VSO ID 1075166
Attached the bug repro steps in doc format.
[https://app.zenhub.com/files/153711945/94a5b911-407a-464e-b91c-661e43a659ee/download](https://app.zenhub.com/files/153711945/94a5b911-407a-464e-b91c-661e43a659ee/download)

Affected Branch: d16.5
Affected Build: 29827.131
.Netcore version: 3.1.200
Affected SKU: ENT
Affected Product Language:  CHS
Operation System Information:19h2
Machine: XETLAB009(10.195.200.10） 

Prerequisite: 
install VS from https://aka.ms/vs/16/int.d16.5/vs_enterprise.exe
Be sure to intall language packs Chinese(Simplified)
Launch VS without code->Tools->Options->Environment->International Settings-> Select language Chinese(Simplified) ->OK ->Close VS
More Info: 
It also repro on d16.4 branch. 
Steps to reproduce:
1. Launch VS
2. Try to create a C# WPF Core project.  
Expected: 
The names of WPF Core project templates are all localized as WPF Framework templates

Actual: 
The names of WPF Core project templates are not localized

**Comment by lukaschal** [comment]
@gomathip02 Could you please attach screenshots directly to this github issue ?

**Comment by lukaschal** [comment]
All "WPF" templates localized here.

https://devdiv.visualstudio.com/_search?action=contents&text=%22wpf%20user%20control%20library%22&type=code&lp=custom-Collection&filters=&pageSize=25&result=DefaultCollection%2FDevDiv%2FLocalize%2FGBrel%2Fd16loc%2F%2Fchs%2Fvsproject%2Fplatform%2FMicrosoft.VisualStudio.WPFFlavor.dll.lcl

**Comment by ryalanms** [comment]
This should be backported to 6.0.

**Comment by ryalanms** [comment]
The files are under packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/ in .templateconfig/localize subdirectories for each template type.

**Comment by ryalanms** [comment]
The templates are now localized.  See packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/ .
