### ISSUE TITLE
XAML Editor for VSCode

### ISSUE THREAD

**Issue by Mabenan** [dotnet/wpf#280]
I don't know if i'm here right with this request.

Like the title says it would be nice to have an xaml designer in vscode. As i think many people use dotnet core with vs code.

**Comment by dotMorten** [comment]
>  But honestly all WPF and WinForms developers I know use Visual Studio

To be fair, it is their only option. It's also an expensive option.

**Comment by thomasclaudiushuber** [comment]
>  I don't get this argument. I can build iOS apps in VSCode, but that won't work on Windows or Linux, but only Mac. Why should WPF/WinForms be any different? No one is saying a plugin has to be crossplatform.

Yep. My argument was meant like this: If you need a Windows machine, what's the point of using a cross-platform tool anyway. As I wrote, it makes sense for those who prefer VSCode over Visual Studio. And this is the argument that @Mabenan also wrote, which is ok. Fair point! A plugin would be great for those who want to do everything in VSCode. 

But is this the only argument? I don't think that the license for the Community Edition is really an argument to create a plugin for VSCode. You should quote the details for individuals as well, as your quote only contains the license part for organizations:

> For individuals
Any individual developer can use Visual Studio Community to create their own free or paid apps

So, I don't see a problem there. But yes, as said, I like @Mabenan idea and this issue. What I said: I'd like to have it, but I don't see it as a top priority. We should do a poll on twitter.

**Comment by dotMorten** [comment]
So because there's a license for individuals screw the Enterprise and especially government workers who can't get several thousand dollars  approved? My point with the quote was to show not everyone can use it. That argument still stands.

**Comment by thomasclaudiushuber** [comment]
@dotMorten Ok, now I got it what you mean. Yes, makes absolutely sense, that argument stands.

So we have:
- VSCode is used by many .NET Core devs, a XAML editor would be great to stay in the tool for WPF (and maybe even UWP and other XAML platforms)
- Give workers in organizations a tool they can use that does not require a license
- One more from me: A VSCode plugin would have a positive effect on XAML imo

I just think it's not the right time before the .NET Core 3 release. This is a thought, doesn't mean I'm right. :-)

I wonder how much work it would be to bring XAML support in as a Windows-only Plugin. Could the VS Designer be re-used? Or would the XAML Editor that @michael-hawker has created as part of XAML Studio be an option and a point to start with?

**Comment by dotMorten** [comment]
Perhaps start with a XAML text editor with autocompletion, error squiggles etc, and leave the design surface out for now. From my experience most people work with xaml this way anyway (winforms is another story and more or less useless without a design surface)

**Comment by stevenbrix** [comment]
Is V

**Comment by michael-hawker** [comment]
Since I've been called out, I can't say I haven't thought about this scenario already. 😉 I haven't looked at testing WPF support for XAML Studio, but have thought about the UWP scenario and integrating XAML Studio as an external preview surface to VS Code as an editor.

Implementing IntelliSense would be they tricky bit.  Even though I'm effectively using the same Monaco API, I'm using reflection at the moment to generate suggestions as there's no longer a generated XSD for UWP XAML (though maybe one still exists for WPF?).  So, the biggest part of a plugin would be working out the auto-complete scenario. [See this article for a tutorial on XSD Monaco based IntelliSense](https://mono.software/2017/04/11/custom-intellisense-with-monaco-editor/)

Hooking it into an external process to render the preview (or report back errors) should be the easier part.

**Comment by MarkusAmshove** [comment]
Wouldn't Omnisharp be the correct place for this, at least for XAML editor?
The C# extension for VS code is powered by Omnisharp and already supports Razor

**Comment by stevenbrix** [comment]
I agree with @MarkusAmshove that is probably the right place for something like this to go. is there an associated issue over there that we can reference as a duplicate?

**Comment by SailorMax** [comment]
How about more universal solution like form server? Similar to language server?
If it possible, this allow to make any form builder: XAML, WPF, forms for Android, HTML builder,..

**Comment by grubioe** [comment]
Closing this issue, an issue exists in VSCode repo:

https://github.com/microsoft/vscode/issues/60406

**Comment by adam-becker** [comment]
How does an existing (but closed) issue supercede an open one?

**Comment by grubioe** [comment]
Please log a new issue there or ask the VSCode team to re-open the existing one. Thanks!

**Comment by stevenbrix** [comment]
@Mabenan @adam-becker I filed https://github.com/OmniSharp/omnisharp-vscode/issues/3338 to (hopefully) get the ball rolling on this a bit.

**Comment by minecraftchest1** [comment]
I do want to add to this. I use Visual Studio Code because I am not able to install Visual Studio on my Laptop for reasons that are irrelevant to this discussion. I would love, at the very least, auto completion for WPF since I type the UI up most of the time.
