### ISSUE TITLE
App.xaml resources can't be found when using a custom entry point

### ISSUE THREAD

**Issue by Rijno** [dotnet/wpf#2823]
[TestNetCoreWpfResources.zip](https://github.com/dotnet/wpf/files/4407461/TestNetCoreWpfResources.zip)
* .NET Core Version: 3.1
* Windows version: 1803
* Does the bug reproduce also in WPF for .NET Framework 4.8?: ~~No~~ **Yes, see additional comment below.**

 **Problem description:**
App.xaml resources can't be found when configuring a custom entry point with _StartupObject_ and using _new App().Run()_. 
_Application.ApplicationMarkupBaseUri_ is not set to _App.xaml_.

 **Actual behavior:**
 All resources and MergedDictionaries' resources described in the _App.xaml_ can't be found.

 **Expected behavior:**
Expected the resources and MergedDictionaries' resources described in the _App.xaml_ to be available the application.

 **Minimal repro:**

_csproj_
```
[TestNetCoreWpfResources.zip](https://github.com/dotnet/wpf/files/4407453/TestNetCoreWpfResources.zip)

<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
    <StartupObject>TestNetCoreWpfResources.Program</StartupObject>
  </PropertyGroup>
</Project>
```

_Program.cs_
```
[STAThread]
private static void Main(string[] args)
{
	//App.Main(); // This works
	
	var app = new App { ShutdownMode = ShutdownMode.OnExplicitShutdown }; // This doesn't

	// Work around?
	//var appWideResources = new ResourceDictionary { Source = new Uri("pack://application:,,,/TestNetCoreWpfResources;component/AppResources.xaml") };
	//foreach (var resource in appWideResources.MergedDictionaries) Application.Current.Resources.MergedDictionaries.Add(resource);

	var wnd = new MainWindow();
	wnd.Title = "Test App.xaml resources";
	app.Run(wnd);
}
```
_App.xaml_
```
<Application.Resources>
     <ResourceDictionary>

        <DrawingGroup x:Key="DrawingGroupSettings">
            <GeometryDrawing Brush="#FFF6F6F6" Geometry="F1M32,64C30.85,64,29.646,63.926,28.322,63.773L25.844,63.492 22.666,54.551 14.102,58.617 12.15,57.074C10.223,55.547,8.467,53.795,6.93,51.855L5.381,49.902 9.449,41.34 0.507999999999999,38.16 0.225000000000001,35.684C0.0740000000000016,34.355 0,33.152 0,32 0,30.848 0.0740000000000016,29.645 0.225000000000001,28.316L0.507999999999999,25.84 9.449,22.66 5.381,14.098 6.93,12.145C8.467,10.209,10.223,8.449,12.15,6.926L14.102,5.383 22.666,9.449 25.844,0.508000000000003 28.322,0.226999999999997C29.646,0.0739999999999981 30.85,0 32,0 33.16,0 34.367,0.0739999999999981 35.691,0.226999999999997L38.166,0.515999999999998 41.342,9.449 49.902,5.383 51.854,6.926C53.785,8.459,55.543,10.215,57.074,12.148L58.619,14.102 54.551,22.66 63.492,25.84 63.775,28.316C63.926,29.645 64,30.848 64,32 64,33.152 63.926,34.355 63.775,35.684L63.492,38.16 54.551,41.34 58.619,49.898 57.074,51.848C55.543,53.785,53.785,55.545,51.854,57.07L49.902,58.617 41.342,54.551 38.164,63.484 35.691,63.773C34.367,63.926,33.16,64,32,64" />
            <GeometryDrawing Brush="#FF424242" Geometry="F1M32,26C28.687,26 26,28.688 26,32 26,35.313 28.687,38 32,38 35.313,38 38,35.313 38,32 38,28.688 35.313,26 32,26 M32,20C25.371,20 20,25.371 20,32 20,38.629 25.371,44 32,44 38.629,44 44,38.629 44,32 44,25.371 38.629,20 32,20 M50.855,38.41C50.574,39.238,50.254,40.035,49.871,40.813L53.938,49.367C52.598,51.059,51.066,52.594,49.371,53.934L40.813,49.867C40.039,50.254,39.238,50.57,38.41,50.855L35.23,59.797C34.168,59.922 33.094,60 32,60 30.91,60 29.836,59.922 28.777,59.801L25.598,50.855C24.77,50.574,23.965,50.254,23.191,49.871L14.633,53.938C12.937,52.594,11.406,51.063,10.062,49.367L14.129,40.813C13.746,40.035,13.426,39.238,13.145,38.41L4.199,35.227C4.078,34.168 4,33.094 4,32 4,30.906 4.078,29.832 4.199,28.77L13.145,25.59C13.426,24.762,13.746,23.963,14.129,23.187L10.062,14.629C11.406,12.937,12.937,11.402,14.633,10.062L23.191,14.129C23.965,13.742,24.766,13.426,25.598,13.141L28.777,4.199C29.836,4.078 30.91,4 32,4 33.094,4 34.168,4.078 35.23,4.199L38.41,13.145C39.238,13.426,40.039,13.746,40.813,14.129L49.371,10.062C51.066,11.406,52.598,12.937,53.938,14.633L49.871,23.187C50.254,23.963,50.574,24.762,50.855,25.59L59.801,28.77C59.922,29.832 60,30.906 60,32 60,33.094 59.922,34.168 59.801,35.227z" />
            <GeometryDrawing Brush="#FFF0EFF1" Geometry="F1M32,38C28.684,38 26,35.312 26,32 26,28.687 28.684,26 32,26 35.316,26 38,28.687 38,32 38,35.312 35.316,38 32,38 M32,20C25.371,20 20,25.371 20,32 20,38.627 25.371,44 32,44 38.629,44 44,38.627 44,32 44,25.371 38.629,20 32,20" />
        </DrawingGroup>

        <DrawingImage x:Key="DrawingImageSettings" Drawing="{StaticResource DrawingGroupSettings}"/>

        <Canvas x:Key="CanvasSettings" Width="16" Height="16" x:Shared="false">
            <Rectangle Width="16" Height="16">
                <Rectangle.Fill>
                    <DrawingBrush Drawing="{StaticResource DrawingGroupSettings}" />
                </Rectangle.Fill>
            </Rectangle>
        </Canvas>

    </ResourceDictionary>
</Application.Resources>
```
_MainWindow.xaml_
```
<Menu>
    <MenuItem Header="_MenuItem with Icon" Icon="{DynamicResource CanvasSettings}" />
</Menu>
<Label x:Name="labelApplicationMarkupBaseUri"/>
```
_MainWindow.xaml.cs_

```
var app = Application.Current;
var baseUri = app.GetType().GetProperty("ApplicationMarkupBaseUri",
		System.Reflection.BindingFlags.Public |
		System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).GetValue(app, null);

labelApplicationMarkupBaseUri.Content = baseUri.ToString();
```

**Comment by Rijno** [comment]
Here is some additional findings.

We recently updated one of our WPF **.NET Framework** projects (4.8) to use the new **csproj** format. This project also has a custom entry point specified with StartupObject.
After updating to the new **csproj** format, the behavior with the .NET Framework project is the same as described earlier for .NET Core. 

To reproduce, same as original post, but using the below project file instead.
_csproj_
```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFrameWork>net48</TargetFrameWork>
    <RootNamespace>TestNetFrameworkWpfResources</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <OutputType>WinExe</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <UseWpf>true</UseWpf>
    <StartupObject>TestNetFrameworkWpfResources.Program</StartupObject>
  </PropertyGroup>
</Project>
```

**Comment by hkedjour** [comment]
It appears that you are missing a call to `app.InitializeComponent();`. The generated `InitializeComponent()` is the one that loads what's in the `xaml` file. Without calling `InitializeComponent()` the resources will not be loaded.

To solve the issue either call `app.InitializeComponent();` in the new main method. Or just call it in the `App` contstrcutor.

At least, this was my case.

**Comment by Rijno** [comment]
Thanks a lot! `InitializeComponent()` not being called was indeed the reason why the resources are not found.

This prompted me to look into our application startup again and got a found the underlying issue.
We have a generic function that takes the project specific Application type. This function creates a new instance of `TApplication` (`where TApplication : Application`). Now in order to call `InitializeComponent()`, The application instance is cast to `System.Windows.Markup.IComponentConnector`. This cast returns null for some reason and it silently failed in our projects. Never calling InitializeComponent and thus never loading the resources. 

```
var application = new TApplication { ShutdownMode = ShutdownMode.OnExplicitShutdown };
var app = (application as System.Windows.Markup.IComponentConnector);
if (app != null) app.InitializeComponent(); // app is always null in SDK-style projects.
```

I tried it again in .NET Core and .NET Framework with an SDK-style project, here the cast to `IComponentConnector` returns null. 
In .NET Framework with the 'old' project format, the cast returns the object and I can call `InitializeComponent()`. 

I don't understand why the cast fails when switching the type of the project file.

**Comment by ThomasGoulet73** [comment]
@Rijno You need to add `<EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>`, this makes the project include App.xaml as a normal `Page` instead of `ApplicationDefinition`. `EnableDefaultApplicationDefinition` also allows you the remove the generation of `App.Main` and the need to include `StartupObject` in your csproj. Also, I would recommend calling `InitializeComponent` in the constructor of `App` instead of using `IComponentConnector.InitializeComponent()`. The template for a new Page in Visual Studio already includes a constructor with `InitializeComponent`:
```
public partial class Page1 : Page
{
    public Page1()
    {
        InitializeComponent();
    }
}
```

**Comment by Rijno** [comment]
@ThomasGoulet73 Thanks for pointing that out to me. `<EnableDefaultApplicationDefinition>` was indeed what I was missing!

After setting `<EnableDefaultApplicationDefinition>` to `false`, the generated `App` code then inherits from `IComponentConnector` and our own startup works as expected again. When reading [the documentation](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props-desktop#enabledefaultapplicationdefinition), I would not expect that this setting would have an effect on the inherited types in the generated `App` code. 
`public partial class App : System.Windows.Application, System.Windows.Markup.IComponentConnector`

Is it by design that when `<EnableDefaultApplicationDefinition>` is `true`, the generated `App` code does not inherit from `IComponentConnector`? If so, this is not a bug and can be closed.

@ThomasGoulet73 Any particular reason why using `IComponentConnector` is not a good idea? 
We have generalized the bulk of the applications startup as this is used throughout many of our projects, so we can easily maintain this without needed to go over all the projects individually. This is where we use `IComponentConnector` to call `InitializeComponent`.

**Comment by ThomasGoulet73** [comment]
@Rijno I don't think that there is anything wrong with using `IComponentConnector`, I personally prefer calling `InitializeComponent` in the constructor of the class that implements it to avoid mistakes. It's easy to forget to call `IComponentConnector.InitializeComponent` everywhere but the constructor is always invoked.

Both ways are fine so I guess it comes down to personal preference.

**Comment by ThomasGoulet73** [comment]
@Rijno Can I close this issue ? According to your last comment, my suggestion fixed your issue.
