### ISSUE TITLE
WPF's transport package has dependency on System.Security.Permissions

### ISSUE THREAD

**Issue by ericstj** [dotnet/wpf#283]
**Problem description:**
WPF's transport packages should be binaries only.  The version of the dependencies is meant to be decided in dotnet-trusted when the shared framework is built.

 **Actual behavior:** 
Restores WPF binaries and some CoreFx dependencies (the closure of System.Security.Permissions).
 
 **Expected behavior:**
Only restores WPF binaries
 
 **Minimal repro:**
create a project and reference:
```xml
<PackageReference Include="runtime.win-x64.Microsoft.DotNet.Wpf.Private" Version="4.8.0-prerelease.19064.4" />
```

The fix here is to set PrivateAssets=All on all PackageDependencies in the project which produces your transport package.   Since that happens to be System.Xaml today, it needs to be done there.

**Comment by rladuca** [comment]
No longer applicable.
