### ISSUE TITLE
PresentationBuildTasks should use MetadataLoadContext 

### ISSUE THREAD

**Issue by ericstj** [dotnet/wpf#285]
**Problem description:**
PBT is still using System.Reflection.TypeLoader from corefxlab.  I believe it needs to move to use https://github.com/dotnet/corefx/tree/master/src/System.Reflection.MetadataLoadContext.
 
As a result of using the old TypeLoader it is missing fixes / changes as well as bringing in stale dependencies for this component.

/cc @ryalanms @steveharter

**Comment by nguerrera** [comment]
I'll take a quick look to see if this can be done quickly.

**Comment by stevenbrix** [comment]
Closing since this work has already been completed inside the internal repo.
