### ISSUE TITLE
 System.Windows.Media.Rotate() does not state units of measure of its parameter

### ISSUE THREAD

**Issue by DaveInCaz** [dotnet/wpf#2852]
The parameter `angle` needs to be in degrees but this is not stated in the tooltip in VS nor in the comments when you view metadata for the method.

Here's what's in the metadata for `Rotate()`:

        //
        // Summary:
        //     Applies a rotation of the specified angle about the origin of this System.Windows.Media.Matrix
        //     structure.
        //
        // Parameters:
        //   angle:
        //     The angle of rotation.
        public void Rotate(double angle);

In contrast `RotateAt()` does state the units:

        //
        // Summary:
        //     Rotates this matrix about the specified point.
        //
        // Parameters:
        //   angle:
        //     The angle, in degrees, by which to rotate this matrix.
        ...
        public void RotateAt(double angle, double centerX, double centerY);

Thanks

**Comment by lindexi** [comment]
I don't like basic types without units too

**Comment by fabiant3** [comment]
@mairaw - could we please update the docs?

**Comment by mairaw** [comment]
Pinging the @dotnet/docs to answer that

**Comment by gewarren** [comment]
I'm not finding that API on the .NET API browser. Is it documented somewhere else?

**Comment by pchaurasia14** [comment]
Fixed [here].(https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Media/Matrix.cs#L175)
