### ISSUE TITLE
How to get the dispatcher scheduler?

### ISSUE THREAD

**Issue by mrakgr** [dotnet/wpf#2856]
I am trying to use WPF with reactive extensions and am having difficulty figuring out how to do this on .NET Core 3.1. Everything on SO pertaining to this question is out of date.

[Also, see this question.](https://stackoverflow.com/questions/61097363/why-does-observable-range-freeze-when-run-on-the-gui-thread)

**Comment by weltkante** [comment]
WPF uses standard [SynchronizationContext](https://docs.microsoft.com/en-us/dotnet/api/system.threading.synchronizationcontext?view=netcore-3.1) infrastructure by implementing [DispatcherSynchronizationContext](https://docs.microsoft.com/en-us/dotnet/api/system.windows.threading.dispatchersynchronizationcontext?view=netcore-3.1), so you either use the Dispatcher directly or its SynchronizationContext (you can use SynchronizationContext.Current if you want). Nothing has changed between Desktop Framework and .NET Core with this as far as I know.

Besides having a SynchronizationContext I believe any scheduler used by other frameworks has to be programmed in that other framework and is usually based on top of SynchronizationContext - for example if you are talking about the task based programming schedulers there is [TaskScheduler.FromCurrentSynchronizationContext](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler.fromcurrentsynchronizationcontext?view=netcore-3.1)

**Comment by mrakgr** [comment]
> SynchronizationContext.Current

I've tried using this together with `SynchronizationContextScheduler`, but `SynchronizationContext.Current` always returns null for me for some reason.

**Comment by mrakgr** [comment]
I finally got it to work with `Observable.observeOn (Application.Current.Dispatcher |> Threading.DispatcherSynchronizationContext |> SynchronizationContextScheduler)`. Thanks.
