### ISSUE TITLE
Unpin privatized C++ toolsets and ship using real-signed shipping tools

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#2870]
https://github.com/dotnet/wpf/pull/2857 introduced use of privatized C++/CLI toolsets. This is a temporary fix and should be rolled back in favor of production tools. 

//build and RC/RTM products should not ship using these tools - they should be changed to production tools obtained from ambient tools coming from build pipeline machines. 

This would become possible as soon as Dev16.6p3 ships. 

**This should be treated as a release blocker for broad releases like //build, RC etc ** 

/cc @dotnet/wpf-developers

**Comment by vatsan-madhavan** [comment]
You'll need to make 2 additional changes when fixing this one. 

- https://github.com/wpfcontrib/wpf/commit/11c24e3afb31cf7a40ee649e4e1f3022d5c9f9f3
- Disable LTCG for bilinearspan.lib. This causes [error C1047](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1047) when compilers change. Though this is only a transient problem, it can be a bother in dev-builds. 

Here is a preview of an upcoming build failure: 

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29115\include\yvals_core.h(503,1): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.27 or newer.

**Comment by ryalanms** [comment]
Thanks, @Vatsan.  I'll try to get this in soon.

**Comment by vatsan-madhavan** [comment]
> Thanks, @vatsan. I'll try to get this in soon.

I might just be willing to lose by contrib history if I could get that username ;-)

**Comment by ryalanms** [comment]
Thanks, @vatsan-madhavan.  This has been merged.
