### ISSUE TITLE
BitmapDecoder remains locked after reading a non-supported file.

### ISSUE THREAD

**Issue by shibayan** [dotnet/wpf#2881]
* .NET Core Version: 3.1.3 (3.1.201)
* Windows version: 10.0.18363.752
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
 
 **Problem description:**

Users cannot write or delete files while the application is running because BitmapDecoder will remain locked after reading a non-supported file.

If an exception is thrown during the creation of BitmapDecoder, the FileStream used internally does not seem to be released.
 
 **Actual behavior:** 

The file is locked and cannot be operated until the application is terminated.
 
 **Expected behavior:**

The file does not remain locked even if a non-supported file is given.
 
 **Minimal repro:**

```csharp
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
    }

    private void Window_Loaded(object sender, RoutedEventArgs e)
    {
        try
        {
            // Always throw `NotSupportedException`
            var decoder = BitmapDecoder.Create(new Uri(@"C:\Users\shibayan\Documents\dummy.md"), BitmapCreateOptions.DelayCreation, BitmapCacheOption.OnDemand);
        }
        catch (NotSupportedException ex)
        {
        }
    }
}
```

**Comment by elyoh** [comment]
I hit this issue when attempting to load invalid / unsupported png image files.  Eventually it was determined that this was the issue.  I worked around it by passing a file stream to the decoder and making sure that it gets disposed if the decoder throws. Not ideal but a possible work around until this gets fixed.

```csharp
try
{
    using (var fs = new FileStream(filepath, FileMode.Open, FileAccess.Read, FileShare.Read))
    {
        var decoder = BitmapDecoder.Create(fs, BitmapCreateOptions.None, BitmapCacheOption.OnLoad);
    }
}
catch (NotSupportedException ex)
{
}
```
