### ISSUE TITLE
Where could one find docs mentioned in the code comments?

### ISSUE THREAD

**Issue by kekekeks** [dotnet/wpf#2882]
E. g. there is
```cs

    // It's necessary understand the Avalon Text Object Model to follow the
    // TextContainer implementation.  There's a spec for the OM at
    // http://avalon/uis/TextBox%20and%20RichTextBox/Text%20Object%20Model.doc.
``` 
in https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextContainer.cs#L24 but it's pointing to some intranet resource.

Since comment text suggests that it's necessary to read the spec to follow the implementation, it would be really nice to get these docs published.

**Comment by fabiant3** [comment]
It's unfortunate but some of the links pointed to by the WPF source are no longer available (even on our intranet). We'd also like to make these docs available, unfortunately that is not possible.
