### ISSUE TITLE
Please give us an update on community pull requests

### ISSUE THREAD

**Issue by Symbai** [dotnet/wpf#2884]
Can we please get an update on community pull requests? There are community pull requests since nearly a year without any review or comment. It would be great to know:

- If you accept community pull requests at all
- When are you planning to review the existing
- What is your roadmap on this for the future

The Winforms repro is extremely active on community pull requests, thus the community is very active on improving and contributing. For this repro its the opposite. At first I thought you would want to wait until the source is completely open sourced but since it is now completely open sourced for a while and existing pull requests are still not reviewed nor commented, I wonder what's the status on this?

**Comment by batzen** [comment]
@shanselman I don't know if you are the right person to ping her, but the absolute silence from Microsoft here is very sad. A clear statement would be very appreciated.

**Comment by GeertvanHorrik** [comment]
Pinged both @dotMorten and @clairernovotny via Twitter. I believe they have great connections within MSFT and could be a great help here.

**Comment by fabiant3** [comment]
Thank you for your active submission of Issues and PRs on the repo. Our team has recently taken over this repo and we are in the active process of defining the future strategy and roadmap for this project. We look forward to sharing it with you in a couple of weeks. Please stay tuned.

**Comment by miloush** [comment]
Sorry @fabiant3 this is a bit confusing, is "our team" a different team than the WPF developers we have been interacting with before?

**Comment by fabiant3** [comment]
Yes, our team is different from the WPF team you may have interacted with in the past. Our team is the Windev team under the Developer Ecosystem and Platform Org. We are committed to restarting active community engagements on this repo. We are currently working out our strategy since having taken over the repo. Please stay tuned for updates heading your way in a couple of weeks.

**Comment by Symbai** [comment]
Any update?!

**Comment by Wraith2** [comment]
I asked about this on the VisualStudio Community Standup. The answer was that a new PM has/is being put in place for WPF and that they have had covid related delays and technical problems. The new PM will be on the next Community Standup on 23rd of july and will talk about what's going on with the repo at that point. So no real answers just more waiting.

**Comment by Suchiman** [comment]
For reference: https://youtu.be/q7ODj3RJnME?t=2641

**Comment by svick** [comment]
> Please stay tuned for updates heading your way in a couple of weeks.

I believe that update is what's now [in the roadmap](https://github.com/dotnet/wpf/blob/master/roadmap.md):

> ### Our SLA
> #### TRIAGING GITHUB ISSUES
> We are committed to a 72 hour (3 working days) turn around on triaging and responding to new issues filed on Github starting July 10th.
> Additionally,  Issues filed prior to July 10th are also being triaged. Issues filed in 2020 will be triaged first based on number of reactions/comments, and we expect to complete doing so by the middle of 20H2. Issues filed before 2020 will be triaged after that based on number of reactions/comments.
> 
> #### EVALUATING PULL REQUESTS
> We will begin merging contributions from the community on the WPF repo by picking 1-2 PRs from the community to manually test and integrate per month. When the test infrastructure work is completed we will enable broader community pull request merging. This is our team's commitment until our resourcing for WPF ramps-up.
> #### Code PRs considered at this time will be based on:
> -	Recency
> -	Extent of Reactions (Likes, comments)
> -	Fixes to existing issues prioritized over new features
> -	Complexity of the fix
> -	Breadth of impact of the fix
> -	Low potential for regression
> -	Has adequate test coverage
> -	Is not a new feature request
> 
> #### About non-code PRs
> We are committed to a 72 hour (3 working days) turn around on triaging and responding to new non-code PRs filed on Github starting July 10th. These are PRs for documentations bugs, documentation enhancements or a general question not related to source code issues/bugs.

Why that update wasn't mentioned here, I'm not sure.

**Comment by Wraith2** [comment]
I think the expectation for external input has been set and confirmed during the lifetime of this thread. I suspect anyone who didn't already have a PR open would look at the state of the repository and decide against attempting to contribute because it clearly wasn't going to be welcomed. The code may be open source but the development is not.

**Comment by Symbai** [comment]
> 
> 
> The code may be open source but the development is not.

That's a good summary actually. I'm not sure if I thought give you a thumb up for that, or a thumb down just because its so true that it makes me sad seeing this repo and the Winforms repo where open source community has grown so fast and so many cool PRs have been accepted... and I just don't want to accept that state. I guess that's that then. The future of WPF will be as the future of .NET Framework => Maintenance mode only.

At least... we got the update this topic was about, whether we like it or not.
