### ISSUE TITLE
Feature request: Fully support nullable reference types in the WPF API surface area for .NET 5

### ISSUE THREAD

**Issue by Austin-Lamb** [dotnet/wpf#2885]
Mads Torgerson has laid out a call to action for .NET libraries to properly support the C# 8 Nullable Reference Types feature by the time .NET 5 comes out (see here : https://devblogs.microsoft.com/dotnet/embracing-nullable-reference-types/ )

It would be great if WPF can support this feature.  Currently, as an example, IValueConverter does not support this correctly - the return type from "Convert" is object but it should be "object?" since it's valid to return a null.

Currently in my WPF app I have to disable nullable reference types on my IValueConverter source files, which is unfortunate for .NET 5 alignment.

Note: there may be more parts of the WPF API surface that should be nullable-ready, IValueConverter is a concrete example I can point to, but this feature request is really to correctly support NRTs for the entire API surface per Mads' post.

**Comment by Rand-Random** [comment]
Any updates on this issue? Is .NET 7 a possibility?

**Comment by lindexi** [comment]
See https://github.com/dotnet/wpf/issues/3062

**Comment by pchaurasia14** [comment]
Closing this issue in favor of https://github.com/dotnet/wpf/issues/7563
