### ISSUE TITLE
Can wpf be compiled to native code?

### ISSUE THREAD

**Issue by kumamiko** [dotnet/wpf#289]
I'm new with wpf and dotnet core.

Just curious if wpf can be compiled to native code.

Maybe that is a stupid question？

**Comment by karelz** [comment]
Depends what you mean by native code. Is NGen image native enough?
Or are you thinking about full AOT (Ahead Of Time compilation) without any fallback to JIT? What about falling back to interpreter, is that "ok"?
Are you just curious, or do you have a specific scenario in mind? (e.g. iOS prevents JIT technologies in store)

Overall, this is a property of .NET, not specific to WPF.
.NET Core does not have full AOT solution. .NET Native is the closest thing, you can get, but it is available only for UWP Store applications. CoreRT is technology trying to achieve the same, but it is not productized. Mono has full AOT (falling back to interpreter I believe) for iOS scenarios.
The most common technology used in .NET is some prcompilation (NGen or cross-gen) with fallback to JIT (or interpreter in Mono case).

This is more StackOverflow question, discussion about general technology, not something we should solve on any particular repo in GitHub. I'd recommend to close the issue ...

**Comment by kumamiko** [comment]
thanks for reply
