### ISSUE TITLE
WPF splash screen for HiDPI

### ISSUE THREAD

**Issue by pcfulife** [dotnet/wpf#2942]
WPF splash screen is not a DPI-aware. In HiDPI environment, WPF splash screen is showing a small image. I hope that WPF splash screen will be big enough in HiDPI environment.

**Comment by pcfulife** [comment]
Duplicated issue: https://github.com/dotnet/wpf/issues/947
But, I think that supporting HiDPI for default splash screen is also good.

**Comment by lindexi** [comment]
@pcfulife I do it by  other threads. But as you can see, #297 and  #2031
