### ISSUE TITLE
.net core WPF System.Windows.ResourceDictionary warning miss details

### ISSUE THREAD

**Issue by endink** [dotnet/wpf#2956]
* .NET Core Version: 3.1
* Windows version: Windows 10

 **Problem description:**

When we debug or Run the WPF application it works fine but in output window so many lines are coming with warning 
```

System.Windows.ResourceDictionary Warning: 9 : Resource not found;
```

It does not provide any details to tell me which resource missed.
And this warning causes the UI to become slower and slower at debugging time

the output window:
<img width="351" alt="捕获" src="https://user-images.githubusercontent.com/240164/80562621-cd843d80-8a1a-11ea-9e2e-fb35035b40cc.PNG">

the same message in diagnostic tool window"

<img width="657" alt="捕获2" src="https://user-images.githubusercontent.com/240164/80562677-015f6300-8a1b-11ea-8aa0-d0ea238bf559.PNG">

How can i get the full output information?

**Comment by ActSabke** [comment]
After migrating our .net 461 wpf application we get the same error. 
Is there any way to detect which resource dictionary throws this error?

**Comment by fabiant3** [comment]
@endink - can you please attach a minimal repro?

**Comment by bender2k14** [comment]
I can provide a repo that is rather minimal.

[ZIP of reproduction](https://github.com/dotnet/wpf/files/5133230/MWE.zip)

This reproduction depends on [Material Design in XAML](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit), which is how I recently encountered this problem.  I am sure that a smaller / simpler reproduction is possible without this dependency, but I have yet to figure out how.

### Reproduction steps
1. Download ZIP
2. Unzip
3. Open the solution file
4. Run the application
5. Click anywhere (see GIF below)

![2020-08-26_19-13-21_263](https://user-images.githubusercontent.com/34664007/91369132-8e030d80-e7d0-11ea-9982-dfbdaf14e4b2.gif)

### Additional information

For the specific case of this reproduction, the fix to avoid the missing resource is to comment in the commented out line in `App.xaml`.
```XAML
<Application x:Class="WpfApp2.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
             StartupUri="MainWindow.xaml">
  <Application.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <!--<materialDesign:BundledTheme BaseTheme="Light" PrimaryColor="DeepPurple" SecondaryColor="Lime" />-->
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
  </Application.Resources>
</Application>
```
