### ISSUE TITLE
Can't publish app for linux-arm64 or ubuntu-arm64

### ISSUE THREAD

**Issue by KhArtNJava** [dotnet/wpf#2962]
Steps to produce:

- Create a project from WPF App (.Net core) template in visualstudio 2019 with .Net Core 5.0 or with .Net Core 3.1 .
- Click on build -> publish
- Change deployment mode to: Self-contained
- Change target framework to: linux-arm64 or ubuntu-arm64

Actual result: the screen display this error:
![image](https://user-images.githubusercontent.com/757085/80839464-f61b5b80-8c03-11ea-9f87-512d71d9a25b.png)

Build output is:
```
1>------ Publish started: Project: WpfApp1, Configuration: Release Any CPU ------
1>Determining projects to restore...
1>All projects are up-to-date for restore.
1>You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
1>There was no runtime pack for Microsoft.WindowsDesktop.App.WPF available for the specified RuntimeIdentifier 'ubuntu-arm64'.
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

```

Expected result: Publish successfull

Is it possible to compile .Net Core WPF app compile for ARM64 (linux-arm64 or ubuntu-arm64)?

**Comment by RhavoX** [comment]
It was stated that WPF is not supported in Linux. The same goes for windows forms therefore publishing for it won't work.

**Comment by fabiant3** [comment]
Not a supported scenario.
