### ISSUE TITLE
No flicker/flashing on modal window when parent is clicked

### ISSUE THREAD

**Issue by RhavoX** [dotnet/wpf#2966]
* .NET Core Version: 3.1.201
* Windows version: 1909
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? 
No
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/master/README.md#reporting-security-issues-and-security-bugs).
Not a security issue
 
 
 **Problem description:**
 When a modal window is shown trying to click on the parent window should flash the modal window (active/inactive/active etc.). The flash does not occur and the window loses focus. The sound indicating inability to grab focus plays. The flash occurs in Windows Forms (framework 4.8 tested). Regular applications (including some of the system apps) do the flash in such a case.

 **Actual behavior:** 
No flash when clicking on parent window when modal window is shown. 

 **Expected behavior:**
Flashing (activation toggling) of a modal window when attempting to activate the parent of that window.
 
 **Minimal repro:**
For a minimal repro just create a WPF project in net core or framework 4.8 and spawn a modal window.

**Comment by RhavoX** [comment]
An interesting update here. This seems to occur only under debug from VS. If run standalone without attached debugger the flash occurs...

**Comment by batzen** [comment]
Are you using the XAML-Debug-Tools during debugging? If that's the case it might be that that window flashes instead of yours.

**Comment by fabiant3** [comment]
Seems like an issue with the debugger and not necessarily WPF. Closing for now.
