### ISSUE TITLE
UI cross-platform (MacOS and Linux support)

### ISSUE THREAD

**Issue by jinyuttt** [dotnet/wpf#2967]
Does Microsoft have a cross platform desktop UI library or similar plan?

**Comment by LeoYang-Chuese** [comment]
> Microsoft是否具有跨平台的桌面UI库或类似计划？

 There has been much discussion about this issue, see here #48 .

**Comment by jinyuttt** [comment]
Did Microsoft find that QT update is fast, and more and more QT is used? Why? Will the desktop be defeated by QT? Is there a case of mobile version?

**Comment by jinyuttt** [comment]
@LeoYang-Chuese I know that I've been speaking in it recently, but the questions are too long and the content is too much and it's not easy to open the web page, so there are new questions. This time it's not specifically about WPF, it's just a set of UI libraries.

**Comment by marcosgerene** [comment]
@jinyuttt 
Maybe, this is the future: https://github.com/dotnet/maui

**Comment by jinyuttt** [comment]
Now we use Avalon

**Comment by robloo** [comment]
As of today, WPF can be used on macOS and Linux in several scenarios using Avalonia UI as the base rendering/composition engine and platform abstraction layer.

https://avaloniaui.net/XPF
