### ISSUE TITLE
RadioButtons with the same `GroupName` will affect each other over windows if window is closed

### ISSUE THREAD

**Issue by walterlv** [dotnet/wpf#2995]
* .NET Core Version: 3.1.202
* Windows version: 10.0.18363 / 10.0.19624
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 **Problem description:**

If some `RadioButton`s are in the same group, they should check and uncheck each other. If we create two windows both contain the same XAML RadioButton groups, we'll find that the `RadioButton`s are separated into two windows. However, if one window is closed, the `RadioButton`s in the other window will affect those in the closed one.

This code below shows how to set the `GroupName`, but it's recommended to read the minimal reproduction at the end of this issue to know all the details.

```xml
<RadioButton GroupName="A" Content="Option 1" />
<RadioButton GroupName="A" Content="Option 2" />
<RadioButton GroupName="A" Content="Option 3" />
```

By running the minimal reproduction source code, you'll see the expected behavior and the broken behavior and I've posted the gifs below.

 **Expected behavior:**
 
![2020-05-14-radio-buttons-in-opened-windows](https://user-images.githubusercontent.com/9959623/81895669-61dacc80-95e5-11ea-989c-69f98b5ce5ae.gif)

 **Actual behavior:** 
 
![2020-05-14-radio-buttons-in-closed-windows](https://user-images.githubusercontent.com/9959623/81895674-656e5380-95e5-11ea-8147-21265318f0c7.gif)

 **Minimal repro:**

The GitHub repo:

- https://github.com/walterlv/Walterlv.Issues.RadioButton.GroupName

The keys:

1. Write some `RadioButton`s in a window XAML;
2. We want to know whether the `RadioButton`s in different windows affect each other, so I bind the first `RadioButton.IsChecked` to a singleton. This means:
    - If the radio buttons affect only in a single window, the A window checks a radio button then the binding source viewmodel propertychanged, and then the B window checks a radio button due to the viewmodel new property value.
    - But if the radio buttons affect over windows, the A window checks a radio button then it change the binding source viewmodel and then checks the B window radio button. But the radio button in B window unchecks the radio button in A window, so the binding source viewmodel property is changed to `false`. At last, all values are `false`. As a result, no radio button can be checked.

If all the windows are open, all behave as expected:

![image](https://user-images.githubusercontent.com/9959623/81897207-c51a2e00-95e8-11ea-8b01-5544f13f74ee.png)

If the previous windows are closed, then the radio buttons start to affect each other:

![image](https://user-images.githubusercontent.com/9959623/81897232-cc413c00-95e8-11ea-82e0-8f679a44fa83.png)

The XAML code:

```xml
<Window x:Class="Walterlv.Issues.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Walterlv.Issues"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <StackPanel>
        <Border>
            <RadioButton GroupName="A" IsChecked="{Binding Bar, Source={x:Static local:Foo.Instance}}" Content="Option 1" />
        </Border>
        <Border>
            <RadioButton GroupName="A" Content="Option 2" />
        </Border>
        <Border>
            <RadioButton GroupName="A" Content="Option 3" />
        </Border>
    </StackPanel>
</Window>
```

The C# code:

```csharp
using System.ComponentModel;
using System.Windows;

namespace Walterlv.Issues
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }
    }

    public class Foo : INotifyPropertyChanged
    {
        public static Foo Instance { get; } = new Foo();

        public bool Bar
        {
            get => _bar;
            set
            {
                if (!Equals(_bar, value))
                {
                    _bar = value;
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Bar)));
                }
            }
        }

        private bool _bar;
        public event PropertyChangedEventHandler PropertyChanged;
    }
}
```

**Comment by walterlv** [comment]
From the open-source codes, we can find that the radio button auto checks the focus root as the group name scope:

```csharp
KeyboardNavigation.GetVisualRoot(this)
```

**Comment by walterlv** [comment]
Before the issue is fixed, we can try to solve it by adding a `MarkupExtension` to generate the `GroupName` with a random name. So different window instances have their own `GroupName`s and they will not affect each other over windows.

```xml
<StackPanel local:RadioButtonFix.IsScope="True">
    <Border>
        <RadioButton GroupName="{local:RadioButtonFix A}" Content="Option 1" />
    </Border>
    <Border>
        <RadioButton GroupName="{local:RadioButtonFix A}" Content="Option 2" />
    </Border>
    <Border>
        <RadioButton GroupName="{local:RadioButtonFix A}" Content="Option 3" />
    </Border>
</StackPanel>
```

**Comment by weltkante** [comment]
Something must be wrong with your setup, if I add RadioButtons with GroupName to a window and then create two instances of the same window (which obviously have the same group name since they have the same XAML) they don't affect each other. I'll have a look at your repro scenario.

**Comment by walterlv** [comment]
@weltkante Yes, according to your description, they actually don't affect each other. In my scene, you should:

1. Close one window (**IMPORTANT**);
2. Bind the radio buttons to a singleton to check that that are affected each other.

**Comment by weltkante** [comment]
Ok I think I understood what you are reporting, your title is misleading. GroupName will not affect other windows.
* You are sharing the binding across windows (intentionally I assume)
* Closing the window does not disconnect the binding
* RadioButton GroupName in a closed window does not function properly
* This leads to some kind of feedback loop through the closed window, preventing the open window of functioning correctly

I agree that there's a bug somewhere, but its not about GroupName. You just need grouped radio buttons to trigger the bug. To see proof add a `GC.Collect();` somewhere (e.g. in your singleton property accessor) and observe the bug no longer reproducing.

**Comment by weltkante** [comment]
You are right the bug is in `RadioButton.UpdateRadioButtonGroup`. It doesn't need closed windows to trigger either, any window currently not connected to a visual root will trigger the bug.

```csharp
private void Button_Click(object sender, RoutedEventArgs e)
{
    new MainWindow().Show();
    new MainWindow();
    new MainWindow();
}
```

**Comment by walterlv** [comment]
@weltkante Thanks for your efforts to simplify this issue and to hit the critical codes.

**Comment by xinyuehtx** [comment]
public static class GroupNameProvider
    {
        public static readonly DependencyProperty BuildScopeProperty = DependencyProperty.RegisterAttached(
            "BuildScope", typeof(bool), typeof(GroupNameProvider), new PropertyMetadata(PropertyChangedCallback));

        private static void PropertyChangedCallback(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if (e.NewValue is bool value && value == true)
            {
                SetGroupNameA(d, Guid.NewGuid().ToString("N"));
            }
        }

        public static void SetBuildScope(DependencyObject element, bool value)
        {
            element.SetValue(BuildScopeProperty, value);
        }

        public static bool GetBuildScope(DependencyObject element)
        {
            return (bool) element.GetValue(BuildScopeProperty);
        }

        public static readonly DependencyProperty GroupNameAProperty = DependencyProperty.RegisterAttached(
            "GroupNameA", typeof(string), typeof(GroupNameProvider), new PropertyMetadata(default(string)));

        private static void SetGroupNameA(DependencyObject element, string value)
        {
            element.SetValue(GroupNameAProperty, value);
        }

        public static string GetGroupNameA(DependencyObject element)
        {
            return (string) element.GetValue(GroupNameAProperty);
        }
    }


<Grid x:Name="Panel" local:GroupNameProvider.BuildScope="True">
    <RadioButton IsChecked="{Binding Foo}"
      GroupName="{Binding ElementName=Panel,Path=(local:GroupNameProvider.GroupNameA)}"/>
</Grid>

[blog](https://xinyuehtx.github.io/post/WPF%E7%9A%84RadioButton%E6%8C%87%E5%AE%9Agroupname%E5%9C%A8window%E5%85%B3%E9%97%AD%E5%90%8E%E6%97%A0%E6%B3%95check.html)

**Comment by NaBian** [comment]
simplified your demo:
``` c#
<StackPanel>
    <Border>
        <RadioButton GroupName="A" IsChecked="{Binding Bar, Source={x:Static local:Foo.Instance}}" Content="Option 1" />
    </Border>
    <Border>
        <RadioButton GroupName="A" Content="Option 2" />
    </Border>
    <Border>
        <RadioButton GroupName="A" Content="Option 3" />
    </Border>
</StackPanel>
<StackPanel>
    <Border>
        <RadioButton GroupName="A" IsChecked="{Binding Bar, Source={x:Static local:Foo.Instance}}" Content="Option 1" />
    </Border>
    <Border>
        <RadioButton GroupName="A" Content="Option 2" />
    </Border>
    <Border>
        <RadioButton GroupName="A" Content="Option 3" />
    </Border>
</StackPanel>
```
just open window one time

**Comment by weltkante** [comment]
This is not a bug though, you have two panels sharing the same groups, thats intended.

The point of the bug report is that everything not attached to a visual root will start sharing their radiobutton groups. So while you have two windows open they can use the same radiobutton groupnames and they will be distinct, but if you close/hide them they start to share their groups. If the radiobuttons were databound this will lead to a feedback loop.

**Comment by walterlv** [comment]
@NaBian Your simpler code really describes the reason for this issue, but not describes the pain for this issue. Also @weltkante .

If radio buttons with the same group names affect each other even across different windows, then we have to give up the embedded group name feature because our visible radio buttons may be influenced by the ones which should have been destroyed.

This means we have to use the method from @xinyuehtx for nearly every radio button with group names if our programs have to open different window instances of one window class.

**Comment by harshit7962** [comment]
Analysis so far - While registering the radio buttons, the reference to them in hashtable is added as a weak reference which should allow the GC to collect it when the window is closed. However, it looks like there is some other pointer <i>strongly</i> referencing the radiobutton even after the window is closed (which is why it is still not null in this check).
[wpf/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/RadioButton.cs at 7a6188f601e6464a98e11608a9c1948bc3307fff · dotnet/wpf (github.com)](https://github.com/dotnet/wpf/blob/7a6188f601e6464a98e11608a9c1948bc3307fff/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/RadioButton.cs#L156)
 
Continuing to investigate where is the reference being held for the radio button after the window is closed.

**Comment by xinyuehtx** [comment]
来信悉知，我会尽快回复
                                                                ——黄腾霄

**Comment by harshit7962** [comment]
@walterlv We have merged the above PR which fixes the issue. Can you verify if it solves the issue.

**Comment by lindexi** [comment]
Awesome @harshit7962

**Comment by walterlv** [comment]
@harshit7962 I've tested it on .NET 8 rc2 and find that it is fixed. Thank you!
