### ISSUE TITLE
Provide PopTransform for DrawingContext

### ISSUE THREAD

**Issue by skarllot** [dotnet/wpf#2996]
The `DrawingContext` could provide the method `PopTransform` in addition to `Pop` method, allowing to pop the last transform.

**Comment by nsivov** [comment]
Again, if you need that for a wrapper around DrawingContext, you might as well track last pushed transform and type of last Push(). This way your PopTransform() will either push inverted transform, or Pop() if last push was PushTransform(). What you're suggesting seems conceptually wrong for current interface.

**Comment by weltkante** [comment]
That is dangerous, there is only a single stack of push operations, and operations on top are dependent on operations on the bottom.

What if the top is not a transform but a clip, this clip would have been relative to the transform below it, so when you want to PopTransform what should happen? There is no "obviously correct" way to handle that.

**Comment by skarllot** [comment]
@weltkante I agree, there is no correct solution.
