### ISSUE TITLE
Could not edit settings file

### ISSUE THREAD

**Issue by pcfulife** [dotnet/wpf#300]
* .NET Core Version: 3.0.100-preview-010184
* Windows version: 1809
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 
 **Problem description:**
Cannot edit WPF settings file. 

 **Actual behavior:** 
When I create WPF project (.NET Core 3.0) and create WPF setting file (Settings1.settings), an error message shows. (The reference "System" could not be added to the project. This wizard will continue to run, but the resulting project may not build properly.)
Then, I cannot edit Settings1.settings by default editor. (Visual Studio hangs and shows "Exception from HRESULT: 0x80004005 (E_FAIL), Failed to generate file: Unable to find a type of reference that is appropriate for this file: "System".) But, it can be edited by XML editor.
But, after I save Settings1.settings file with XML editor, I cannot access to namespace (WpfApp1.Properties.Settings). Because it doesn't generate Settings1.Designer.cs
I confused that it is a bug of Visual Studio or .NET Core. But, when I create a project with same VS version and .NET Framework, it doesn't occur.

 **Expected behavior:**
 

 **Minimal repro:**
 Just create WPF project and in project configuration, make a default resource, right click on Properties in solution explorer, add new settings file.

**Comment by stevenbrix** [comment]
@pcfulife which version of Visual Studio are you using?

**Comment by pcfulife** [comment]
@stevenbrix I am usuing Visual Studio 2019 Preview 3. Sorry, I forgot this issue. I reproduced it at WPF project with same version of VS. So, I think it is a bug of VS 2019.

**Comment by stevenbrix** [comment]
No worries! A lot is changing with .NET Core, so it's not unreasonable that there is an issue with VS2019 here. Have you been able to file a feedback item in VS? I think that would be the best place to start, thanks!

**Comment by pcfulife** [comment]
@stevenbrix Thanks, But, this is solved in Visual Studio 2019 Preview 4. I installed it today, and I didn't found any bug.

**Comment by stevenbrix** [comment]
That's good to hear. I'll close this issue then!
