### ISSUE TITLE
XAML won't render left curly bracket in button content

### ISSUE THREAD

**Issue by JeroenOortwijn** [dotnet/wpf#3000]
* .NET Core Version: 3.1.202
* Windows version: 10.0.18363
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? Yes, filed a [bug report](https://developercommunity.visualstudio.com/content/problem/1015032/xaml-wont-render-left-curly-bracket-in-button-cont.html), but it was closed and redirected here.
 
 **Problem description:**

 XAML designer won’t show left curly bracket if it’s defined with its decimal reference.

 **Actual behavior:**

![image](https://user-images.githubusercontent.com/51476918/81953685-4634ed80-9608-11ea-8b17-8959efc3260d.png)

 Building gives the following build error:
```
Error
MC3074
The tag '' does not exist in XML namespace https://schemas.microsoft.com/winfx/2006/xaml/presentation'. Line 13 Position 17.
```

 **Expected behavior:**

![image](https://user-images.githubusercontent.com/51476918/81953853-754b5f00-9608-11ea-83ed-c9cf074c8803.png)

 **Minimal repro:**

```
<Window x:Class="Accolade_xaml_test.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Accolade_xaml_test"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <WrapPanel>
        <Button Content="&#120;" FontSize="40" Width="40"/>
        <Button Content="&#121;" FontSize="40" Width="40"/>
        <Button Content="&#122;" FontSize="40" Width="40"/>
        <Button Content="&#123;" FontSize="40" Width="40"/> <!-- This should show left curly bracket { -->
        <Button Content="&#124;" FontSize="40" Width="40"/>
        <Button Content="&#125;" FontSize="40" Width="40"/>
        <Button Content="&#126;" FontSize="40" Width="40"/>
    </WrapPanel>
</Window>
```

**Comment by JeroenOortwijn** [comment]
On a similar note, it won't show low line when followed by line feed:

![image](https://user-images.githubusercontent.com/51476918/81954483-2fdb6180-9609-11ea-9c7e-877291de98d5.png)
```
        <Button Content="&#95;" FontSize="40" Width="40"/>
        <Button Content="&#95;&#10;" FontSize="40" Width="40"/> <!-- This should show low line _ -->
        <Button Content="&#96;" FontSize="40" Width="40"/>
        <Button Content="&#96;&#10;" FontSize="40" Width="40"/>
```

**Comment by weltkante** [comment]
Not rendering left curly bracket is by design and documented in several places, for example [here](https://docs.microsoft.com/en-us/dotnet/desktop-wpf/xaml-services/escape-sequence-markup-extension). Reason is that the curly bracket character has special meaning and is used for markup extensions. You have to use `{}` as escape sequence.

**Comment by fabiant3** [comment]
Thanks @weltkante for the follow up.
