### ISSUE TITLE
Controls in a TabItem get focused  in a strange way

### ISSUE THREAD

**Issue by ShannonZ** [dotnet/wpf#3005]
* .NET Core Version: all
* Windows version: 16299.1565
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

 **Problem description:**
 The  element in a TabItem get focused  in a strange way.

 **Actual behavior:** 
https://ibb.co/r5NkrpN

The first TextBox get focus after click the tab header. If I change the selected TabItem(i.e. click on another tab header), the first TextBox in the selected item focesed. 
At this state, if user double-click the header, no child element get focus. And then you could change the tab item between each other, all works well, no element in TabItem get focus.
 
 **Expected behavior:**
 If user have not click any UI control under TabItem, there should be no control focused.
 **Minimal repro:**
` <Grid> 
        <TabControl>
            <TabItem Header="TabItem#1" FocusManager.FocusedElement="{x:Null}">
                <StackPanel>
                    <TextBox IsReadOnly="True">Tab1</TextBox>
                    <TextBox IsReadOnly="True"> Tab1</TextBox>
                </StackPanel>
            </TabItem>
            <TabItem Header="TabItem#2" FocusManager.FocusedElement="{x:Null}">
                <StackPanel>
                    <TextBox IsReadOnly="True">Tab2 It will get focus just after change the selected Tab Item</TextBox>
                    <TextBox IsReadOnly="True">Tab2</TextBox>
                </StackPanel>
            </TabItem>
        </TabControl>
    </Grid>`

**Comment by fabiant3** [comment]
The link does not appear to be working. Can you provide a minimal repro?
