### ISSUE TITLE
"By default, the DataGrid.ColumnWidth property is set to SizeToHeader", or is it! 

### ISSUE THREAD

**Issue by dragus0** [dotnet/wpf#3006]
While not specified in the XAML Code, but shown as SizeToHeader in the Properties Window, it actually behaves like SizeToCells.

https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/sizing-options-in-the-datagrid-control

Sorry if this is the wrong repo.
'''
...
```
<DataGrid x:Name="Tables_DataGrid" Grid.Row="3" Grid.RowSpan="1" Margin ="0" RowDetailsVisibilityMode="VisibleWhenSelected" EnableRowVirtualization="True" DataContext="{StaticResource Tables_ViewSource}" ItemsSource="{Binding Source={StaticResource Tables_ViewSource}}" Grid.Column="1" IsTextSearchEnabled="True" TextSearch.TextPath="Hardware_Model" SelectedIndex="30">

...
'''
```

![grafik](https://user-images.githubusercontent.com/62744978/82055978-f159ab80-96c9-11ea-89fd-ac9440f1879a.png)

![grafik](https://user-images.githubusercontent.com/62744978/82055951-e737ad00-96c9-11ea-8869-0ddfc6438077.png)
But when a cell with longer text is reached:
![grafik](https://user-images.githubusercontent.com/62744978/82056019-00405e00-96ca-11ea-8884-0e127f5ede43.png)

VS2019

**Comment by dragus0** [comment]
<DataGrid x:Name="Tables_DataGrid" Grid.Row="3" Grid.RowSpan="1" Margin ="0" RowDetailsVisibilityMode="VisibleWhenSelected" EnableRowVirtualization="True" DataContext="{StaticResource Tables_ViewSource}" ItemsSource="{Binding Source={StaticResource Tables_ViewSource}}" Grid.Column="1" IsTextSearchEnabled="True" TextSearch.TextPath="Hardware_Model" SelectedIndex="30">

**Comment by weltkante** [comment]
HTML-like tags are not shown, you need to make a code section to paste XAML.

` ``` `
` insert XAML `
` ``` `

**Comment by fabiant3** [comment]
Most likely a documentation issue, we'll confirm.

**Comment by SamBent** [comment]
The documentation says:

>By default, the DataGrid.ColumnWidth property is set to SizeToHeader, and the DataGridColumn.Width property is set to Auto. When the sizing mode is set to Auto or SizeToCells, columns will grow to the width of their widest visible content.

> 
DataGridColumn.Width | Sets a specific width for an individual column. Overrides DataGrid.ColumnWidth.
-- | --

The value 'Auto' for column.Width overrides the value 'SizeToHeader' for datagrid.ColumnWidth.  This describes the observed behavior.  There's no bug here (of any kind).
