### ISSUE TITLE
Port fixes from https://github.com/dotnet/wpf/pull/2857 to release/3.1

### ISSUE THREAD

**Issue by MattGal** [dotnet/wpf#3010]
**Problem description:**

- Release/3.1 branches build against VS 2019 preview, which now has checks for http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1766r1.html explicitly in the native toolset.
 
 **Actual behavior:** 
Causes build breaks.  Can be **temporarily** worked around by not building on ".Pre" build pools
 
 **Expected behavior:**
 Clean build

 **Minimal repro:**
Spin build of release/3.1 branch

@vatsan-madhavan  FYI.

**Comment by vatsan-madhavan** [comment]
@fabiant3 fyi

**Comment by ryalanms** [comment]
WPF has moved off .pre build pools for both 3.1 and 5.0.
