### ISSUE TITLE
Binding isn't updated 

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/wpf#3050]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`) 5.0p4
* Windows version: (`winver`) 19041
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Unknown
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? If yes, please file the issue via the instructions [here](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019). No
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/master/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**
A textblock within a data template isn't being updated correctly in some specific repro steps.
 
 **Actual behavior:** 
Textbox displays old value 

Evalutated expression also doesn't match datacontext
![image](https://user-images.githubusercontent.com/1427284/82955011-e7faf980-9f7b-11ea-8619-282116fd7481.png)

 **Expected behavior:**
Binding is correct 

 **Minimal repro:**

- Clone/build NuGet Package Explorer from `master` hub.com/NuGetPackageExplorer/NuGetPackageExplorer
- Open from Feed... search for `Grpc.Net.Client`. Select "all versions" and open 2.28. Note the Git Commit sha on the left.
- Open from Feed, select 2.29-pre1. Notice how the other properties on the left all change but the git commit sha does not.

It's not clear what's going on -- each time a package is loaded, it's a new PackageViewModel at the MainWindow DataContext.

**Comment by miloush** [comment]
That is because the two `RepositoryMetadata` instances are equal. Unfortunately for you, the class overrides equatability and compares only the Url, see https://github.com/NuGet/NuGet.Client/blob/f7e4a189c85fc6cfcc2d3f6b3d94079125adfe91/src/NuGet.Core/NuGet.Packaging/Core/RepositoryMetadata.cs#L68.

As far as WPF is concerned, the metadata hasn't changed and there is no binding to update.

**Comment by clairernovotny** [comment]
But the whole data context hierarchy is updated? Shouldn't it refresh the bindings?

**Comment by clairernovotny** [comment]
@nkolev92 why is RepositoryMetadata only comparing part of the data?

**Comment by miloush** [comment]
@clairernovotny The bindings refresh (if you put a breakpoint into `EditablePackageMetadata.Repository` getter, it will hit as you open a new package), but the binding sees the value is the same as before so it doesn't bother updating the target.

Your options basically are:

- convince NuGet to change its equality contract, though I suspect they have a reason for it;
- create a wrapper around the `RepositoryMetadata`, basically a view model (your best bet);
- unload the package when opening a new one (not a great user experience).

The class is not sealed, so you could theoretically just inherit from it and wrap the `value` in the property setter, with no change to your API.

**Comment by miloush** [comment]
As this is by design (and the implied proposal to force-update all binding targets regardless of whether value has changed has significant performance implications and can introduce infinite loops), I assume this issue can be closed.

**Comment by nkolev92** [comment]
> @nkolev92 why is RepositoryMetadata only comparing part of the data?

@clairernovotny that's a bug :( 

https://github.com/NuGet/NuGet.Client/commit/0e4d1b598f350b3dc675018d539114d1328189ef

Created an issue: https://github.com/NuGet/Home/issues/9613
