### ISSUE TITLE
System.Windows.SplashScreen is not HDPI aware

### ISSUE THREAD

**Issue by mnissl** [dotnet/wpf#3060]
System.Windows.SplashScreen is not HDPI aware, i.e. if it displays on a monitor with 200 % scaling, it is way too little.

I'm on .NET Core 3.1.3.

**Comment by lindexi** [comment]
Maybe Duplicated : #2942 #947

**Comment by lindexi** [comment]
Link: #2031

**Comment by fabiant3** [comment]
Dupe, closing this one
