### ISSUE TITLE
Add Nullability Annotations

### ISSUE THREAD

**Issue by dotMorten** [dotnet/wpf#3062]
Most of .NET Core now has nullability annotations to help reduce null-checking, or ensure null-checks are performed.
This greatly increases the quality of the code base, as well as the quality for any apps consuming it, and reduces time spent debugging `ArgumentNullExceptions` and `NullReferenceExceptions`.

However WPF doesn't have any of these. I'd like to see this start getting added throughout the SDK.

Resources:
 - [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
 - [Migrate existing code with nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/upgrade-to-nullable-references)
 - [Reserved attributes contribute to the compiler's null state static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)

**Comment by Marv51** [comment]
Please consider prioritizing this. Almost a 100% of net 5 BCL has nullability annotations, time for WPF to step up.

**Comment by dotMorten** [comment]
WinForms is currently considering this for .NET7: https://github.com/dotnet/winforms/issues/1107

**Comment by virzak** [comment]
MAUI's implementation is [here](https://github.com/dotnet/maui/pull/13173/files#diff-ceb740099e52b2b0fc924856b74524ba1028115ac50297fffef5be24c9e90fbe)

**Comment by ThomasGoulet73** [comment]
@dotnet/wpf-developers Should this issue be closed in favor of #7563, which contains the current plan for nullability annotation.
