### ISSUE TITLE
the IsHitTestVisible Property doesn't work

### ISSUE THREAD

**Issue by sanshiliuxiao** [dotnet/wpf#3088]
* .NET Core Version:  3.1.300
* Windows version:  window10 professional  2004

 
 
 **Problem description:**
 
```

<Window x:Class="DivergenceMeter.MainWindow"
        WindowStyle="None" 
        ResizeMode="NoResize" 
        AllowsTransparency="True"  
        Background="Transparent" 
        IsHitTestVisible="False"
        >
```

 **Actual behavior:** 

![2](https://user-images.githubusercontent.com/25658690/83647847-f4b8c680-a5e7-11ea-8276-f35c6349c565.gif)

 **Expected behavior:**

![1](https://user-images.githubusercontent.com/25658690/83647874-fbdfd480-a5e7-11ea-9c8d-152c7f3c2d04.gif)

**Comment by fabiant3** [comment]
Can you attach a full (isolated) repro? Does this also reproduce in .NET Framework?

**Comment by sanshiliuxiao** [comment]
[demo link](https://github.com/sanshiliuxiao/IsHitTestVisibleDemo)

I found it also failed in Net NetFramework 4.7.2, but I don't know why！！！

 **About Expected behavior**(this is another software I use, I want to use .Net core 3 to imitate it, So I don't have the code for it)

**Maybe I used it the wrong way**

**Comment by kkwpsv** [comment]
I think `WS_EX_TRANSPARENT` and `WS_EX_LAYERED` is what you want.

**Comment by weltkante** [comment]
Thats what the win32 layer uses to force this behavior, which you can always use this as a workaround by overriding WPF, but I think the question is whether this should work out of the box by setting `IsHitTestVisible` ...

**Comment by sanshiliuxiao** [comment]
> Thats what the win32 layer uses to represent this behavior, which you can always use as a workaround by overriding WPF (assuming WPF doesn't insist on resetting these styles) - but I think the question is whether this should work out of the box by setting `IsHitTestVisible` ...

yeeeee.... if the `IsHitTestVisible` propperty can support it, This is great!!!!

**Comment by kkwpsv** [comment]
> > Thats what the win32 layer uses to represent this behavior, which you can always use as a workaround by overriding WPF (assuming WPF doesn't insist on resetting these styles) - but I think the question is whether this should work out of the box by setting `IsHitTestVisible` ...
> 
> yeeeee.... if the `IsHitTestVisible` propperty can support it, This is great!!!!

If `IsHitTestVisible` can support it, there'll be many more problems.
We can only use `WS_EX_TRANSPARENT` and `WS_EX_LAYERED` to implement, which will make the whole window Click-through.
When the window set `IsHitTestVisible` to false, and some of its child controls set `IsHitTestVisible` to false, we have no way to achieve this effect.

**Comment by sanshiliuxiao** [comment]
> > > Thats what the win32 layer uses to represent this behavior, which you can always use as a workaround by overriding WPF (assuming WPF doesn't insist on resetting these styles) - but I think the question is whether this should work out of the box by setting `IsHitTestVisible` ...
> > 
> > 
> > yeeeee.... if the `IsHitTestVisible` propperty can support it, This is great!!!!
> 
> If `IsHitTestVisible` can support it, there'll be many more problems.
> We can only use `WS_EX_TRANSPARENT` and `WS_EX_LAYERED` to achieve, which will make the whole window Click-through.
> When the window set `IsHitTestVisible` to false, and some of its child controls set `IsHitTestVisible` to true, we have no way to achieve this effect.

Thanks. 
Just now, I have used `WS_EX_TRANSPARENT` to achieve the effect I want.

**Comment by weltkante** [comment]
> We can only use WS_EX_TRANSPARENT and WS_EX_LAYERED to achieve

This is wrong, there are other ways to implement it, but this one is the obvious.

> When the window set IsHitTestVisible to false, and some of its child controls set IsHitTestVisible to true, we have no way to achieve this effect.

You misunderstand how `IsHitTestVisible` works, if its false the child controls are never asked. Try it out now, it already works this way for inner controls. Making `IsHitTestVisible=false` on the window equivalent to "click through" would just be the consequent extension of this semantic.
