### ISSUE TITLE
SplashScreen not centered when the size for apps and text is not set to 100%

### ISSUE THREAD

**Issue by jagbarcelo** [dotnet/wpf#3090]
* .NET Core Version: 3.1.4
* Windows version 10 1909 & 2004
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Not tested.
 
 **Problem description:**
When UHD & 4K monitors are used, text is usually so small that users normally *change the size of apps and text* **to a value larger** than the 100% recommended value. This can be changed in Settings -> Display. When this setting is not the default 100%, SplashScreen does not appear centered in the screen.
![image](https://user-images.githubusercontent.com/6704109/83767483-ffbe3600-a67d-11ea-866d-d299a7df978c.png)

  **Actual behavior:**
Under the former scenario SplashScreen of a WPF App (.NET Core) does not appear in the center of the screen.

 **Expected behavior:**
According the documentation at https://docs.microsoft.com/en-us/dotnet/api/system.windows.splashscreen?view=netcore-3.1
> The SplashScreen class displays the splash screen as soon as possible after the application is started. The splash screen is displayed by using native code, before the WPF application instance is created. **The splash screen is displayed in the center of the screen.** When the application is loaded, the splash screen fades.

**Minimal repro:**
Using Visual Studio 2019, create a new project/solution of the **WPF App (.NET Core)** type. Add an image to the project and under its Properties set Compilation Action as **SplashScreen**. There really is no coding involved at all, just adding an image and set it up properly.

Then change your display settings and set the above-mentioned configuration to any value larger than 100% and run the application. The SplashScreen will not appear on the center of the screen.

**Comment by lindexi** [comment]
Maybe Duplicated : #2942 #947 #3060

**Comment by neilebrown** [comment]
This is not just a problem for 4K monitors. People with small 1080p displays (e.g. on ultrabooks and small notebooks) often have the scaling set to values higher than 100%. Also the recommended setting will depend on the particular configuration. On my HP Spectre the behavior (set to 150%) is that the splash screen starts centered but at the wrong size (a DPI issue I assume) and then moves towards the top left and shrinks which is very jarring.

**Comment by fabiant3** [comment]
Dupe of #947
