### ISSUE TITLE
MessageBox control is fuzzy 

### ISSUE THREAD

**Issue by xianyun666** [dotnet/wpf#3123]
* .NET Core Version: 5.0
* Windows version: (Windows 2004)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
 
 **Problem description:**
 I have two monitors,The second monitor MessageBox control is fuzzy 
The first display，125% zoom，1920 * 1080 resolution.
The second display，100% zoom，1920 * 1080 resolution。
After adding the parameter PerMonitorV2 in the app.manifest file, the message box shows fuzzy and abnormal.
If Microsoft.Windows.Common-Controls is enabled, also fuzzy .

 **Actual behavior:** 
 After adding the parameter PerMonitorV2 in the app.manifest file, the message box shows fuzzy and abnormal
 **Expected behavior:**
 Normal display, no blur
 **Minimal repro:**
![w1](https://user-images.githubusercontent.com/22339210/84372856-5abbd400-ac0e-11ea-9325-7560910aebb5.png)
![w2](https://user-images.githubusercontent.com/22339210/84372861-5bed0100-ac0e-11ea-8b8b-f99a762ec780.png)

[netcoreapp5.0.zip](https://github.com/dotnet/wpf/files/4764076/netcoreapp5.0.zip)

**Comment by nsivov** [comment]
Is this really related to WPF? I.e. what happens if you create message box from regular Win32 application on one monitor and another, toggling DPI mode same way?

**Comment by xianyun666** [comment]
If Microsoft.Windows.Common-Controls is enabled,The reason for fuzzy should be related to Windows10

**Comment by fabiant3** [comment]
We can't see much difference between the two screenshots. We agree that this is NOT a WPF issue, we simply use the Win32 API to display these boxes.

**Comment by xianyun666** [comment]
After my research, this is really not a WPF issue
