### ISSUE TITLE
Start .net core WPF App with Administrator Privilege

### ISSUE THREAD

**Issue by geotinc** [dotnet/wpf#313]
Is there a way to start the app in administrator ?

I do the following in .net Framework
`<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />`

Thanks for reply

**Comment by wjk** [comment]
Very simple, actually. You use the exact same method with a .NET Core app as you do with a .NET Framework one. Simply copy the `app.manifest` file from your .NET Framework project, and set the `ApplicationManifest` property in the csproj file like so:

```xml
<PropertyGroup>
  <ApplicationManifest>app.manifest</ApplicationManifest>
</PropertyGroup>
```

Note that the Application Manifest item template in Visual Studio may or may not work here; it has not yet been updated to work with .NET Core. Hope this helps!

**Comment by geotinc** [comment]
Works great
Thanks for helping
