### ISSUE TITLE
Move validation steps to post-build

### ISSUE THREAD

**Issue by mmitche** [dotnet/wpf#3174]
WPF should opt-in to post-build validation for SDL, NuGet validation, etc.,

To enable the nightly validation runs, you add repo entries here: https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=%2Feng%2Fpipeline%2Ftools%2Frepos-to-validate.txt and this file a version of https://github.com/dotnet/aspnetcore/blob/master/eng/sdl-tsa-vars.config into your repo under the eng folder. Then the validation steps can be disabled in your azure pipeline as they have been in runtime’s build https://github.com/dotnet/runtime/blob/master/eng/pipelines/official/stages/publish.yml#L30-L49

**Comment by fabiant3** [comment]
@mmitche - could you explain the impact of these proposed changes?

**Comment by mmitche** [comment]
The build gets shorter and uses less resources, which should help reduce the overall end to end time. Validation is currently ~14% of the build time.

This should also improve reliability due to flakiness in the SDL tooling, symbol validation, etc.

**Comment by ryalanms** [comment]
@mmitche:  It looks like you did this work for us with https://github.com/dotnet/wpf/pull/3234.  Is this okay to close?

**Comment by ryalanms** [comment]
Please reactivate if this is not complete.  Thanks.
