### ISSUE TITLE
Narrator Scan mode gets stuck at the end of WPF FlowDocument content

### ISSUE THREAD

**Issue by guybark** [dotnet/wpf#3175]
This bug has been logged in response to a bug being logged against a Microsoft app, relating to Narrator's navigation behavior at the app. I've not verified myself that the issue repros with .NET Core.

1. Build a new WPF app with .NET Framework 4.8.
2. Add the following XAML:
<RichTextBox>
    <FlowDocument>
        <Paragraph>
            Hello.
        </Paragraph>
    </FlowDocument>
</RichTextBox>
3. Point Narrator to the running app UI, (I'm on Windows 1909).
4. Move through the app UI in Narrator's Scan mode.

Expected result: Narrator moves through all the UI in the app.

Actual result: Narrator won't move beyond the last of the content in the FlowDocument.

Note: Narrator may jump out of Scan mode when encountering the FlowDocument. If this happens for you when repro'ing the issue, explicitly re-enter Scan mode and try to move forward out of the FlowDocument. 

Note: Replacing the use of the RichTextBox hosting the FlowDocument with a FlowDocumentReader didn't seem to avoid the issue. In fact, when a FlowDocumentReader is used, the app's UIA representation includes two document elements, which seems unexpected.

I've been told that when Narrator attempts navigate forward by Paragraph in RichTextBlock in this specific scenario, the same paragraph will be returned over and over again. The API in question is ITextRangeProvider::Move with TextUnit_Paragraph.

The following image shows that the UIA hierarchy of the app seems reasonable.

![FlowDocument](https://user-images.githubusercontent.com/14315611/85611473-d81f1580-b60c-11ea-8a43-77e72ae1e900.png)

**Comment by fabiant3** [comment]
@guybark - can you update the post with the XAML? //Add the following XAML:

**Comment by guybark** [comment]
@fabiant3, add the following XAML in a UWP XAML app newly created in VS...

<Grid Margin="20">
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition Height="*" />
        <RowDefinition Height="Auto" />
        <RowDefinition Height="Auto" />
    </Grid.RowDefinitions>
    <Button Grid.Row="0" Content="Before" />
    <RichTextBox Grid.Row="1" AutomationProperties.Name="Details">
        <FlowDocument>
            <Paragraph>
                Hello.
            </Paragraph>
        </FlowDocument>
    </RichTextBox>
    <TextBlock Grid.Row="2" Text="This is static, not-focusable text." />
    <Button Grid.Row="3" Content="After" />
</Grid>

**Comment by anjalisheel-wpf** [comment]
@guybark This issue is not reproducible. I tested your code, it is working fine. It is not getting stuck at the end of WPF flow document. Please find attached video.

https://user-images.githubusercontent.com/85492722/139692259-7fcfac8c-e018-4baf-adc9-d6996df00f72.mp4
