### ISSUE TITLE
RenderingInvalidated flag is not cleared at the right time

### ISSUE THREAD

**Issue by BrannonKing** [dotnet/wpf#3200]
* This affects all versions of WPF and all platforms.
 
 **Problem description:**
The RenderingInvalidated flag should be cleared before rendering rather than after. It should be cleared right before the call to `RenderOpen()`. The problem is manifest when you have multiple properties that contain the "AffectsRender" flag and trigger propertyChanged events on those properties from non-UI threads. If you have a busy system AND modify multiple of those properties AND rely on the cross-thread propagation of the PropertyChanged event, the rendering will (often but not always) end in an out-of-date state.
 
 **Minimal repro:**
It is impossible to create a small reproduction of this issue. The problem does not show itself until the system gets busy enough that some threads cannot be immediately scheduled.

**Comment by fabiant3** [comment]
Thanks for the report @BrannonKing. In order to investigate this issue, we'd require a minimal repro. We'd also like to understand more about the specific properties you are using and their thread usage (eg: how are you triggering the notify property changed events?)

**Comment by BrannonKing** [comment]
@fabiant3 , can you not also investigate issues based on code review? It's a fairly obvious mistake in the code that any person used to writing multithreaded code would notice.

In my scenario the PropertyChanged events are triggered via various ThreadPool threads.

**Comment by BrannonKing** [comment]
I made a picture to go with my proposal.
![MoveRenderingInvalidated](https://user-images.githubusercontent.com/1509322/87814743-893a5980-c821-11ea-99ed-13ca3fec27b0.png)

**Comment by weltkante** [comment]
I'm not sure you are looking at the right place, the `RenderingInvalidated` flag is not threadsafe, so it shouldn't be set by another thread in the first place. The binding infrastructure for `INotifyPropertyChanged` originating on a different thread will [post to the UI thread](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/MS/Internal/Data/ClrBindingWorker.cs,413) before propagating the property change into the infrastructure.

I'm not sure how your scenario can happen unless you break threading assumptions made by WPF. Not every single method does a Dispatcher check so you may accidently break them, but looking at the source, `InvalidateVisual` & co seems to assume its invoked on the UI thread, it does not contain any locking or other threadsafe primitives.

**Comment by BrannonKing** [comment]
From what you're saying, FrameworkElement.OnPropertyChanged is only ever called on the UI thread. Hence, there must be some other reason that I've been missing visual updates when triggering many "AffectsRender" properties from a background thread. I'll reopen this if I get good reproduction steps.
