### ISSUE TITLE
CroppedBitmap does not propagate underlaying SourceBitmap changes.

### ISSUE THREAD

**Issue by vpenades** [dotnet/wpf#3251]
* .NET Core Version: 3.1
* Windows version: 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Don't know
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

 
 
 **Problem description:**

I am using an `System.Windows.Controls.Image` that has been bound to a `System.Windows.Media.Imaging.CroppedBitmap` using a `System.Windows.Media.Imaging.WriteableBitmap` as a source.

The WriteableBitmap contents are being rewritten several times per second.

If I bind the `WriteableBitmap` directly to the `Image`, the image onscreen is being updated correctly.

But if I wrap the `WriteableBitmap` with a `CroppedBitmap` and the latter is bound to the `Image`, the onscreen view is not being refreshed when I rewrite the writeable bitmap's contents.

This seems to indicate that changes on the `WriteableBitmap` are not propagated up the ladder to the `CroppedBitmap`

 
 **Actual behavior:**

The onscreen image is not updated when I rewrite the underlaying WriteableBitmap's content.
 
 **Expected behavior:**

The Image control accepts a BitmapSource as it's content source. It should play nice with **all** BitmapSource derived classes, and it should refresh the onscreen's view when the underlaying source of a CroppedBitmap is updated.

At first I thought this would be a feature request, but in truth, the inhability of CroppedBitmap to propagate changes of the underlaying BitmapSource essentially cripples CroppedBitmap for many many use cases.

Also, I consider that a CroppedBitmap wrapping another bitmap should behave exactly the same as the underlaying source bitmap, provided the cropping rectangle is of full size.  And this is not the case with WriteableBitmap when its pixels are rewritten.
 
 **Minimal repro:**

```c#
var writeable = new WriteableBitmap();
var cropped = new CroppedBitmap( writeable, new Int32Rect...);
var image = new Image();
image.Source = cropped;
// use image in a XAML for display
writeable.WritePixels(...);  // this should refresh image's onscreen view.
```

**Comment by miloush** [comment]
> it should refresh the onscreen's view when the underlaying source of a CroppedBitmap is updated
> CroppedBitmap wrapping another bitmap should behave exactly the same as the underlaying source bitmap

What gives you these expectations? Nowhere is such behavior documented, and would have to apply for rotations, scaling, flipping, format conversion etc. as well.

If you need to show a cropped, rotated or otherwise transformed version of a "live" bitmap source, use `Image.Clip`, `Image.Transform` etc.

The (documentation states)[https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/imaging-overview#rotating-converting-and-cropping-images]:

> To crop an image, either the `Clip` property of `Image` or `CroppedBitmap` can be used. Typically, if you just want to display a portion of an image, `Clip` should be used. If you need to encode and save a cropped image, the `CroppedBitmap` should be used.

You cannot really encode changing image, as it is changing.

**Comment by ryalanms** [comment]
Thanks for reporting this, @vpenades.  I believe this is by design.  Please reactivate if you disagree. Thanks.

**Comment by vpenades** [comment]
Well, if that's the case, I do believe that CroppedBitmap is a flawed design: It has setter properties that cannot be set, and it uses a composition pattern that does not expose the underlaying object changes after it's been created. So it's hard to see any practical use of it, compared to simply creating another WriteableBitmap with the area of interest, or, as @miloush  suggested, using the Image.Clip.

Anyway, I understand this is going to stay, so I'll take the Image.Clip approach.

**Comment by miloush** [comment]
The practical use was described in the documentation: encoding and saving a cropped image.

The properties are settable according to the `ISupportInitialize` pattern, i.e. until you call `EndInit`, as described in the class [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.imaging.croppedbitmap?view=netcore-3.1).

**Comment by vpenades** [comment]
I don't pretend to start a discussion on this... if encoding and saving a cropped image is the only practical use, I see it hard to justify an entire framework object just for this... from an API design perspective, it would have been much easier to simply add a Save method overload with an additional Rect argument to cover the same functionality.

And, if you end up creating a full framework object, it could have been great to walk an extra mile and make it much more useful by allowing modifications after the object it's been created.

**Comment by miloush** [comment]
The WPF design is basically a managed wrapper over the native [Windows Imaging Component](https://docs.microsoft.com/en-us/windows/win32/wic/) framework.

This design allows for delayed processing:

> At any specific time, an `IWICBitmapSource` object may or may not be backed by an actual bitmap in memory. This enables very efficient processing by an application, because an image can be dealt with as an abstraction. Transform operations can be chained in a transform pipeline without consuming memory resources until the application is ready to render or print the image, at which time it invokes the `CopyPixels` method on the final transform to get a bitmap in memory of the image with the selected transforms applied.

> it would have been much easier to simply add a Save method overload with an additional Rect argument to cover the same functionality

There, in fact, is `BitmapSource.CopyPixels` that takes `Rect` argument exactly for this purpose.

The framework offers several ways of processing and displaying the image, each for different purpose. Your purpose si covered using `Image.Clip`, another purpose is covered using `CroppedBitmap`, and yet another one is covered using `CopyPixels(Rect,...)`, so you can choose the one that meets your needs.
