### ISSUE TITLE
Unknown build error, 'An item with the same key has already been added.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#3292]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/853708/unknown-build-error-an-item-with-the-same-key-has.html)._

---
Working on WPF .NET Core 3.1 application and getting this error on first compile after edditing source code, no error if I rebuild it for the second time.  VS 16.4.0 Pro.

Error	RG1000	Unknown build error, 'An item with the same key has already been added.' 	Vtsr	C:\Program Files\dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets	672

---
#### Feedback Bot on 12/11/2019, 11:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/16/2020, 05:46 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Peter Czurak on 1/16/2020, 06:13 PM: 

<p>Yeah, more bugs in the product. Just amazing!</p><p>A bug is not a bug if Visual Studio Team has to fix it.</p>

#### Karlsson, Henrik on 6/17/2020, 10:48 AM: 

<p>It would be amazing if this error could give more information. I'm currently running in to the same problem (.net core 3.1 on visual studio 16.7.0 Preview 2.0 and I just can't figure out what it is.. I've more or less stripped my project down to the bones. Maybe the "item" could be named in that error?</p><p>C:\Program Files\dotnet\sdk\3.1.400-preview-015151\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(672,5): error RG1000: Unknown build error, 'An item with the same key has already been added.'</p>

#### Fabian Toader [MSFT] on 6/24/2020, 10:42 AM: 

<p>Can you please attach a simple repro project? Thanks!</p>

#### Karlsson, Henrik on 6/25/2020, 02:26 PM: 

<p>ok, I figured out why this was happening in our projects.</p><p>It seems like .net core does not like xaml files with the same names inside the same csproj. I had to rename a bunch of xaml files to give them all unique names within the same csproj.</p><p>That's where I noticed that we had multiple Generic.xaml in the same csproj and the Themes one referenced the other.. somehow both got picked up independently so the referenced one was added twice and that way caused "same key" problem.</p><p>I renamed one of the Generic.xaml to some other name and referenced that instead and problem went away.</p><p>I don't know if this is the same problem <a rel="user" href="https://developercommunity.visualstudio.com/users/1587/8adaea9a-8720-48a9-adba-5323b4521494.html" nodeid="1587">@Peter Czurak</a> had but it is not totally unlikely :-)</p><p>(The problem for generic.xaml actually goes away on second compile (somehow ends up hidden) but caused infinite loops during runtime load in some cases)</p>

#### Karlsson, Henrik on 6/26/2020, 11:43 AM: 

<p>ok, I have even more info. We don't have our csproj files in the same path as the source code (the xaml and cs files) and it seems like if that is the case the intermediate files are just flattened in to one folder... causing problems when two files have the same name.</p><p>so example:</p><p>c:\dev\myproj\myproj.csproj</p><p>have links to</p><p>c:\dev\mysource\a.xaml</p><p>c:\dev\ mysource\folder\a.xaml</p><p>Both these files write intermediate files to the same folder and overwrite each other</p><p>It feels like maybe in these cases the path to the intermediate file should be based on the &lt;link&gt; metadata in the csproj file?</p>

---
### Original Solutions
(no solutions)

**Comment by honkstar1** [comment]
Here's a tiny solution built entirely in visual studio that proves the problem.

[BadXamlIntermediate.zip](https://github.com/dotnet/wpf/files/5816356/BadXamlIntermediate.zip)

**Comment by Dragnalith** [comment]
I am experiencing the same issue, at least with sdk-style project

**Comment by IsmailHassani** [comment]
After almost 3 years, this issue is still live and kicking?

**Comment by pchaurasia14** [comment]
Since 3.1 is out of support, I tried building the above repo project after retargeting to `net7.0-windows` and it builds fine.

![image](https://user-images.githubusercontent.com/105205215/219312688-a2a42ad3-ddf9-459d-9ac6-96e2c5c78bc4.png)


Can you check if it works fine for you as well?

**Comment by IsmailHassani** [comment]
I'm also on .Net 7.0
In the [WPF Sample](https://github.com/I-Synergy/I-Synergy.Framework/tree/main/samples/ISynergy.Framework.UI/Sample.WPF) i still experience same behavior. Second build builds withouot error. It's always the first build.
