### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by Vafnir** [dotnet/wpf#3304]
* .NET Core Version: 5.0.100-preview.7.20366.6
* Windows version: 1909
* Does the bug reproduce also in WPF for .NET Framework 4.8?:  No

![g54g](https://user-images.githubusercontent.com/37485150/89332765-9cac4800-d69c-11ea-97a8-8a15eb66c163.gif)
 
 **Actual behavior:** The board disappears when the window loses focus.

**Comment by ryalanms** [comment]
Hi @Vafnir.  Could add some more detail to which version of the SDK this is, and what the repro steps are?  A sample application that reproduces the problem would be helpful.  Thanks.

**Comment by Vafnir** [comment]
SDK: 5.0.100-preview.7.20366.6
Sample: https://github.com/Vafnir/BugList

I tested any wpf application on my computer and the effect is the same there. I have not seen such a problem on other computers.

**Comment by Vafnir** [comment]
After updating Windows, the bug was fixed.
