### ISSUE TITLE
WPF tmpproj is excluding Microsoft.Net.Compilers.Toolset package 

### ISSUE THREAD

**Issue by davkean** [dotnet/wpf#3308]
**Version Used**: 
Version 16.8.0 Preview 2.0 [30404.163.master]

**Steps to Reproduce**:
[Build.zip](https://github.com/dotnet/roslyn/files/5026511/Build.zip)

From a VS developer prompt from the above version:

1. `git clone http://github.com/dotnet/project-system`
2. `cd project-system`
3. `git checkout 90acd3b85ed4fa5eaef154f71d480800332a9946`
4. `build.cmd`
 
**Expected Behavior**:
No errors

**Actual Behavior**:

Errors because we're picking up csc from the VS directory instead of the package we're using:

```
G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\Waiting\VisualStudioWaitIndicator.cs(101,24): error CS8619: Nullability of reference types in value of type '
(WaitIndicatorResult Canceled, T?)' doesn't match target type '(WaitIndicatorResult, T)'. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSyste
m.Managed.VS_jrfzhkfp_wpftmp.csproj]
G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\Waiting\VisualStudioWaitIndicator.cs(108,24): error CS8619: Nullability of reference types in value of type '
(WaitIndicatorResult Canceled, T?)' doesn't match target type '(WaitIndicatorResult, T)'. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSyste
m.Managed.VS_jrfzhkfp_wpftmp.csproj]
```

Related part of the build log:

![image](https://user-images.githubusercontent.com/1103906/89379155-9ff51180-d738-11ea-93eb-a19cfe7a73a7.png)

**Comment by tmat** [comment]
Dup of [issue](https://github.com/dotnet/wpf/issues/810). Workaround is available in Arcade SDK:
https://github.com/dotnet/arcade/blob/cbfa29d4e859622ada3d226f90f103f659665d31/src/Microsoft.DotNet.Arcade.Sdk/tools/Workarounds.props#L14
