### ISSUE TITLE
Warning C4244 - implicit double -> float conversion with possible data-loss in BaseMatrix.cpp

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#3317]
Here is the warning: 

> src\Microsoft.DotNet.Wpf\src\WpfGfx\core\common\BaseMatrix.cpp(1034,57): warning C4244: 'argument':
conversion from 'double' to 'float', possible loss of data

https://github.com/dotnet/wpf/blob/49cc5c6dcf0ead39a08b1917eeb1d472bcfbe739/src/Microsoft.DotNet.Wpf/src/WpfGfx/core/common/BaseMatrix.cpp#L1034

`CFloatFpu::Ceiling` takes a `float` param, but `std::pow` returns a `double`, which leads to the warning: 

https://github.com/dotnet/wpf/blob/49cc5c6dcf0ead39a08b1917eeb1d472bcfbe739/src/Microsoft.DotNet.Wpf/src/WpfGfx/common/shared/real.h#L628-L630

`std::pow` is defined to return `double` since C++11 ([reference](https://en.cppreference.com/w/cpp/numeric/math/pow))

>```C++
>Promoted    pow ( Arithmetic1 base, Arithmetic2 exp ); | (7) | (since C++11)
>```
>7) A set of overloads or a function template for all combinations of arguments of arithmetic type not covered by 1-3). If any argument has integral type, it is cast to `double`. If any argument is `long double`, then the return type Promoted is also `long double`, otherwise the return type is always `double`.

-- 

The result of `std::pow` should be safe to `static_cast` to `REAL` since `rScaleThreshold <= 1` (this is assert'ed early in the method). 

-- 

Why isn't this warning seen in CI/dev builds using build.cmd today? I can see it easily when building wpfgfx.vcxproj with `msbuild` directly.

**Comment by ryalanms** [comment]
Thanks, @vatsan-madhavan.
