### ISSUE TITLE
The AssemblyId of a TypeInfoRecord doesn't exist

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/wpf#3319]
I found this baml:
```TypeInfo [TypeId=0x0001, AssemblyId=0x1000, TypeFullName="x.y"]```

But there's no `AssemblyInfoRecord` with `AssemblyId=0x1000`
Why does this program can still run?
Is `0x1000` a special id? Does .Net allways try to find type in the current assembly if its `AssemblyId` doesn't exist?
Can someone tell me the logic?

**Comment by CreateAndInject** [comment]
I got it.

**Comment by miloush** [comment]
The answer being?

**Comment by CreateAndInject** [comment]
Only the lower 12 bytes are used.
