### ISSUE TITLE
Remove WpfDllVerifier checks from WPF

### ISSUE THREAD

**Issue by ryalanms** [dotnet/wpf#3322]
WPF has runtime checks to verify the correct versions of WPF assemblies are being loaded. It does so by validating that the DLLs are loaded from the same path. These checks were very useful when porting WPF to .NET Core, but WPF assembly load locations are varied for .NET 5 scenarios. The WpfDllVerifier class and uses of it should be removed for .NET 5.

    /// This class attempts to verify that core WPF binaries are all loaded from the same
    /// location.  Due to the fact that WPF can load binaries in different orders, this class
    /// needs to be called from all of the core managed binaries in static constructors of
    /// commonly used classes.
    /// 
    /// This can also be used to verify specific additional binaries as needed (say if they are
    /// optionally loaded).

    /// If the binaries fail to load from the same location an exception is thrown as we cannot 
    /// guarantee there won't be difficult to debug issues.

#11350
dotnet/runtime#38636

**Comment by dotMorten** [comment]
@ryalanms Is this also why I'm seeing this crash with a trimmed/linked WPF app?

![image](https://user-images.githubusercontent.com/1378165/95170534-73299e80-0769-11eb-9dfc-6071bcb605b6.png)
