### ISSUE TITLE
when Wpf cross-platform

### ISSUE THREAD

**Issue by ourplan9000** [dotnet/wpf#3356]
when Wpf cross-platform

**Comment by miloush** [comment]
WPF is built on DirectX and other Windows API which are not available on other platforms and "will remain in Windows", see https://devblogs.microsoft.com/dotnet/net-core-3-and-support-for-windows-desktop-applications/

**Comment by ourplan9000** [comment]
WPF is built on OpenGL???

**Comment by Simon-IT** [comment]
As sad by @miloush, WPF is built primary on DirectX technology and so will remains available only for Windows operating system

**Comment by stevenbrix** [comment]
@ourplan9000 there is no plan for WPF to be cross-plat. https://github.com/AvaloniaUI/Avalonia is a cross-plat WPF inspired framework that might be worth checking out.

**Comment by dipeshmsft** [comment]
Closing the issue.
