### ISSUE TITLE
dotnet 5.0 preview8 wpf throw System.UriFormatException when not use english project name

### ISSUE THREAD

**Issue by zxgamekingdom** [dotnet/wpf#3388]
If I do not use English as the project name of the WPF program,e.g. Japanese, Chinese.
Exception thrown when WPF application runs into control's InitializeComponent method.
Exception:`System.UriFormatException:“Invalid URI: The Authority/Host could not be parsed.”`

Environment:
Visual Studio Enterprise 16.8.0 Preview 2.0
.NET SDK v5.0.0-preview.8

**Comment by lindexi** [comment]
Duplicate of #3330 ?

**Comment by zxgamekingdom** [comment]
Yes, it is same issue.
By the way, in dotnet 5 preview 8, cannot open console window by set csproj output type ,when csproj has UseWPF or UseWindowsForms, this is bug or feature?

**Comment by lindexi** [comment]
> 
> 
> Yes, it is same issue.
> By the way, in dotnet 5 preview 8, cannot open console window by set csproj output type ,when csproj has UseWPF or UseWindowsForms, this is bug or feature?

Maybe the OutputType is `WinExe` which do not show the console window, and you can set the `OutputType` as `exe` to show it.

**Comment by zxgamekingdom** [comment]
My dotnet 5 preview 8 should be install by Visual Studio 16.8.0 preview 2.0,its name is Microsoft .Net SDK 5.0.100-preview.8.20417.9(x64) from Visual Studio.

Is it possible that Visual Studio caused this?

I use Visual Studio 16.7.2 build dotnet 3.1 wpf project, it is show console window.
The same project, use Visual Studio 16.8.0 preview 2.0 ,not show console.
Use  `dotnet run` the same wpf project ,not show console.

Environment:
Microsoft Visual Studio Enterprise 2019 16.7.2
Microsoft Visual Studio Enterprise 2019 Preview 16.8.0 Preview 2.0
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by ryalanms** [comment]
Thanks, @zxgamekingdom.  This should be fixed in runtime.

**Comment by zxgamekingdom** [comment]
Thinks.
