### ISSUE TITLE
Minimizing code in C# inheritance

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#3389]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1161460/minimizing-code-in-c-inheritance.html)._

---
I have some GUI code in C#.
It mainly uses WPF.
I would like to minimize the amount and duplication of code.
I am basically extending the TreeView

In the attached screenshot, and a snippet of the code with comments is below.
My question is why all of the checkbox items are correctly prefixed with {PLACEHOLDER} {CHECKBOX} except for 'fred [All Sounder]' which shares the same code?

public class CheckBox2TreeViewItem : InfoTreeViewItem
    {
        #region Constructor
        /// <summary>
        /// 
        /// </summary>
        /// <param name="width"></param>
        /// <param name="validationCallback"></param>
        /// <param name="fieldName - anything we call will be able to use this name to see exactly what type of field we are and we can differentiate between any number of similar fields, e.g. Input1 and Input2 (N.B. constant for all languages)"></param>
        /// <param name="maximumLength - used by any text-base fields to limit character input"></param>
        /// <param name="label - read-only label of the field (will vary by language)"></param>
        /// <param name="contents - contains initial contents string we fill the control in with"></param>
        /// <param name="indent_level - will govern where our label and control are displayed on the screen"></param>
        public CheckBox2TreeViewItem(double width, object validationCallback, string fieldName, int maximumLength, string label, string contents, int indent_level) : base(width, validationCallback, fieldName, maximumLength, label, contents, indent_level)
        {
            // 99% of construction is in the parent class, InfoTreeViewItem, which inherits from TreeViewItem
            this. Value.Text = "{PLACEHOLDER} {CHECKBOX} " + this.contents;
            SetReadOnly();
        }
        #endregion

---
#### Feedback Bot on 8/26/2020, 11:08 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Closing in the absence of minimal repro.
