### ISSUE TITLE
Source Generator support for WPF project blocked?

### ISSUE THREAD

**Issue by Marv51** [dotnet/wpf#3404]
**Version Used**: 
dotnet 5 preview 8, visual studio 16.8 preview 2

**Steps to Reproduce**:
Create fresh WPF project from VS modify project like this:
```xaml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net5.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
	    <ProjectReference Include="..\SourceGenerators\SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>
</Project>
```

**Expected Behavior**:
The source generator referenced works for me in a console dotnet core app. I would expect this to work in a WPF project too.

**Actual Behavior**:
In a freshly created WPF (dotnet core) project from the VS-template, however the generator does not seem to run. 

Is this intended behavior? 

As the generator is not used at all, I have not included it here. It is a slight variation of the HelloWorld sample.

**Comment by jaredpar** [comment]
Transferring this issue to the wpf repository as it appears they are not properly passing `$(Analyzers)` to the compiler when building their intermediate temp project. That in turn can impact build success as generators are included in that group.

**Comment by weltkante** [comment]
This would be a blocking issue for adoption since it makes either source generators or WPF unusable. Just documenting that it doesn't work isn't enough, this needs to be implemented.

Also the new COM interop story (CsWinRT) is already looking at using source generators to dynamically generate code, so the amount of things WPF would be incompatible with is only rapidly going to grow from here.

**Comment by jaredpar** [comment]
>  Just documenting that it doesn't work isn't enough, this needs to be implemented.

Intent is to fix the behavior, not document it.

**Comment by Marv51** [comment]
What info is needed @ryalanms? 

(Also, when I was asking for documentation I meant to add a known-issue that it is not working in the previews, while it is being worked on.)

**Comment by miloush** [comment]
@Marv51 from another issue

> @miloush needs-more-info was merely our way of marking the issue as "we've seen it, but we don't have time in this meeting to read the whole thread, understand it, and decide what to do about it". In this case, the more-info needed is the informed opinion of a team member (me). We need a better GitHub label for this (we're actually working on this), so as not to confuse people

**Comment by clairernovotny** [comment]
I believe this is a dup of https://github.com/dotnet/wpf/issues/810

**Comment by weltkante** [comment]
Not a direct dup, note that OP is using `<ProjectReference>` not `<PackageReference>`, but they are probably related in their underlying issue.

**Comment by Marv51** [comment]
I believe that this should get at least really looked at for 5.0? 

Source Generator are a major feature of c# 9/dotnet 5.0, for them not to work in wpf seems like a problem to me.

@jaredpar, @jmarolf

**Comment by jmarolf** [comment]
CC @dotnet/dotnet-wpf as they will need to decide when this fits into their schedule

**Comment by Zalutskii** [comment]
I found a hint on how to solve the problem here https://github.com/dotnet/wpf/issues/3974

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
...
    <IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>
...
  </PropertyGroup>
```
In my case it works.

**Comment by ryalanms** [comment]
Thanks for pointing this out, @Zalutskii.  Existing source generator and PackageReference issues have not been linked to the source generator change: #3846.  Apologies.  

This was made 'opt-in' to reduce the possibility of breaking compilation of existing WPF applications, but will eventually be turned on by default in .NET 6.0.

**Comment by Marv51** [comment]
I tried the property that @Zalutskii was mentioning above `IncludePackageReferencesDuringMarkupCompilation`, but it does not seem to work? Or maybe that PR didn't make it into 5.0.2 after all. 

One think I would like to point out, that while most people (and that Attribute) are talking about `PackageReference`, please don't forget about `ProjectReference`.
At least as far as I know, referencing a source generator within the same solution should be done by `ProjectReference`.

**Comment by Zalutskii** [comment]
> 
> 
> I tried the property that @Zalutskii was mentioning above `IncludePackageReferencesDuringMarkupCompilation`, but it does not seem to work? Or maybe that PR didn't make it into 5.0.2 after all.
> 
> One think I would like to point out, that while most people (and that attribute) are talking about `PackageReference`, please don't forget about `ProjectReference`.
> At least as far as I know, referencing a source generator within the same solution should be done by `ProjectReference`.



[here ](https://github.com/Zalutskii/Reactive-Extensions-event-generator/blob/master/WpfTestApp/WpfTestApp.csproj)I give an example of how to add the Source Generator as a Project Reference.
If you want to add as NuGet it will look like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
...
    <IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>
...
  </PropertyGroup>
  <ItemGroup>
...
    <PackageReference Include="RxSourceGenerator" Version="1.1.2" />
...
  </ItemGroup>
```
</Project>

**Comment by Nukepayload2** [comment]
I'm trying to port VB "My WPF extension" of .NET Framework to .NET 5. 
My VB source generator doesn't work because of this bug. 
The `<PropertyGroup>.<IncludePackageReferencesDuringMarkupCompilation>` element seems has no effect in VB projects. 
The error list of Visual Studio is empty, but there're build errors in the output window. I'm using Visual Studio 16.9 preview 3.
![image](https://user-images.githubusercontent.com/10798596/105661429-58418c80-5f08-11eb-93ed-064ef8e76c56.png)
![image](https://user-images.githubusercontent.com/10798596/105661331-1b759580-5f08-11eb-8361-c2e5a5728e3f.png)
![image](https://user-images.githubusercontent.com/10798596/105661364-2a5c4800-5f08-11eb-9569-c4cb9db34e88.png)
![image](https://user-images.githubusercontent.com/10798596/105661384-35af7380-5f08-11eb-8711-ab0d90473cbe.png)

Here's my project: https://github.com/Nukepayload2/MyWpfExtensionGenerator

**Comment by Marv51** [comment]
Yes this definitely works like @Zalutskii describes. The new attribute fixes the issue. Turning this on by default is tracked by #3974. So to me (the author of this issue) this is fixed. 

Feel free to reopen if issues occur.

**Comment by clairernovotny** [comment]
It's also tracked here for the .NET SDK: https://github.com/dotnet/sdk/issues/15395

**Comment by usikpavel** [comment]
In my case the @Zalutskii workaround works for simple class generation only, but not for more complicated generator. When I'm trying to apply [AutoNotify] attribute from [samples](https://github.com/dotnet/roslyn-sdk/tree/master/samples/CSharp/SourceGenerators), then all errors come back again.
