### ISSUE TITLE
Narrator ignores IsCheckable on RibbonMenuButtonItem

### ISSUE THREAD

**Issue by ChrisSires** [dotnet/wpf#349]
Expected:
If you set IsCheckable=false, the menu item should not be read in Narrator as checked or un-checked.
Actual: 
No matter how IsCheckable is set, Narrator interprets RibbonMenuButtonItems as checkable controls and tries to read them accordingly. 
Repro:
Here’s a xaml sample that will exhibit the issue in Narrator: 
```xml
<Window x:Class="RibbonBug.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:local="clr-namespace:RibbonBug"
    mc:Ignorable="d"
    Title="MainWindow" Height="450" Width="800">
    <Grid>
      <Ribbon Title="Ribbon Title">
        <RibbonMenuButton Label="RibbonMenuButton Label">
          <!-- bug: IsCheckable has no effect on Narrator's output the item is still checked or unchecked -->
          <RibbonMenuItem IsCheckable="False" Header="RibbonMenuButtonItem Header" />
        </RibbonMenuButton>
      </Ribbon>
    </Grid>
</Window>
```

**Comment by ChrisSires** [comment]
`Expected:
If you set IsCheckable=false, the menu item should not be read in Narrator as checked or un-checked.
Actual: 
No matter how IsCheckable is set, Narrator interprets RibbonMenuButtonItems as checkable controls and tries to read them accordingly. 
Repro:
Here’s a xaml sample that will exhibit the issue in Narrator:
<Window x:Class="RibbonBug.MainWindow"
xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
xmlns:local="clr-namespace:RibbonBug"
mc:Ignorable="d"
Title="MainWindow" Height="450" Width="800">
<Grid>
<Ribbon Title="Ribbon Title">
<RibbonMenuButton Label="RibbonMenuButton Label">

<RibbonMenuItem IsCheckable="False" Header="RibbonMenuButtonItem Header" />
</RibbonMenuButton>
</Ribbon>
</Grid>
</Window>`

**Comment by ChrisSires** [comment]
edit the comment to see the xaml

**Comment by wjk** [comment]
@ChrisSires Try enclosing the XAML in three backticks, like the sample below. You only used one, which won't work.

    ```xml
    <PropertyGroup>
    </PropertyGroup>
    ```

This will make the XAML visible to everyone (as I can't edit your post for you, as I'm not a maintainer of this repo), plus it will be syntax-colored for you (because the "xml" after the first pair of backticks tells GitHub what language it is).

**Comment by ChrisSires** [comment]
Thanks for the info, fixed!

**Comment by stevenbrix** [comment]
@ChrisSires, does this also happen with wpf in .net fx?

**Comment by vatsan-madhavan** [comment]
Try setting `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>` to prevent clashing with automatically generated ]assembly attributes](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets)

**Comment by ChrisSires** [comment]
Setting <GenerateAssemblyInfo>false</GenerateAssemblyInfo> appears to have no effect.

**Comment by vatsan-madhavan** [comment]
@arpitmathur , would you please investigate where this issue fits against MAS guidelines?

**Comment by arpitmathur** [comment]
We're not meeting this particular MAS requirement : MAS 1.3.1 – Info and Relationships. We should consider this for 3.0.

@stevenbrix This issue also reproduces on .net framework.

**Comment by arpitmathur** [comment]
This has been fixed in PR 2067 in wpf-int.
