### ISSUE TITLE
Speech synthesis output license/copyright

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#3523]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1182346/speech-synthesis-output-licensecopyright.html)._

---
<p>Hi
</p><p>I am planning to develop an application which converts my own text to speech using the  <a href="https://docs.microsoft.com/en-us/dotnet/api/system.speech.synthesis.speechsynthesizer?view=netframework-4.8">SpeechSynthesizer </a> with installed voices in the OS.
</p><p>I would like to know whether any licenses required for using the output audio files for training, as uploading to websites etc. and the voices are copyright protected or not.  Already gone through the <a href="https://www.microsoft.com/en-us/legal/intellectualproperty/Permissions/default.aspx">Use of Microsoft Copyrighted Content</a> and nothing found specific to the use speech synthesis output and voices.
</p><p>Thanks,
</p><p>Mathews</p>

---
#### Feedback Bot on 9/14/2020, 06:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ryalanms** [comment]
Speech is not part of .NET Core.
