### ISSUE TITLE
Winform should not support netcoreapp3.0

### ISSUE THREAD

**Issue by wli3** [dotnet/wpf#3532]
---
**Issue moved from dotnet/sdk#12799**
- Please respond to @wli3.

---

_From @wli3 on Thursday, August 6, 2020 5:05:26 AM_

![image](https://user-images.githubusercontent.com/6993335/89492935-ae0e5680-d767-11ea-8f2f-4e49dd82d6f1.png)

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#12799**
- Please respond to @wli3.

---

_From @wli3 on Thursday, August 6, 2020 5:06:07 AM_

@marcpopMSFT we should fix this before GA too.

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#12799**
- Please respond to @wli3.

---

_From @wli3 on Friday, August 7, 2020 4:06:57 AM_

Need to search for what is defining `SupportedNETCoreAppTargetFramework`

Default SDK is here  https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.SupportedTargetFrameworks.props

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#12799**
- Please respond to @dsplaisted.

---

_From @dsplaisted on Wednesday, September 16, 2020 9:29:39 PM_

This happens in the WindowsDesktop .props / .targets: https://github.com/dotnet/wpf/blob/master/packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props#L131-L135

**Comment by wli3** [comment]
Turned out the code change need to be in this repo. @Shyam-Gupta

**Comment by wli3** [comment]
Although we have shipped this dropdown for a release. I don't think it is an urgent task

**Comment by wli3** [comment]
also @RussKie

**Comment by ryalanms** [comment]
@wli3:  Is there anything that we need to do in the WPF repo? Thanks.

**Comment by wli3** [comment]
Conversation happens on https://github.com/dotnet/wpf/pull/3537 and looks like there is no conclusion yet. I am not the driver on this issue. You should follow up in that thread.

**Comment by dipeshmsft** [comment]
Closing the issue as the fix is no longer required since 3.1 is out of support
