### ISSUE TITLE
WPF application targeting .NET 4.8 with SDK Microsoft.NET.Sdk fails to build on 5.0.100-rc.1.20454.5 

### ISSUE THREAD

**Issue by ryalanms** [dotnet/wpf#3534]
* .NET Core Version: 5.0.100-rc.1.20454.5
* Windows version: 2004
 
 **Problem description:**

'dotnet build' when targeting 4.8 with Microsoft.NET.Sdk fails to build.  SDK must be changed to Microsoft.NET.Sdk.WindowsDesktop. 
 
 **Actual behavior:** 

A large number of missing reference errors.
 
 **Expected behavior:**

The project builds when targeting 5.0-windows, but not 4.8, or 4.8-windows.
 
 **Minimal repro:**

dotnet new wpf
dotnet build 
observe 5.0-windows builds
edit the .csproj to target 4.8 (net4.8)
dotnet build
observe that the build fails

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <!--
    <TargetFramework>net5.0-windows</TargetFramework> - SUCCEEDS
    <TargetFrameworks>net4.8;net5.0-windows</TargetFrameworks> - FAILS
    <TargetFramework>net4.8-windows</TargetFramework> - FAILS
    -->
    <TargetFramework>net4.8</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
</Project
```

**Comment by vatsan-madhavan** [comment]
@dsplaisted @sfoslund @wtgodbe Does the base .NET Core SDK automatically add `<PackageReference Include=`[`Microsoft.NETFramework.ReferenceAssemblies`](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/)` />` for NetFx targets in .NET 5 yet ?

**Comment by dsplaisted** [comment]
Looks like we didn't consider projects targeting .NET Framework when we did #13441

**Comment by sfoslund** [comment]
Is this supposed to build? Is the problem that the windows desktop SDK has to be explicitly referenced when targeting .NET framework? I thought this was by design.

**Comment by dsplaisted** [comment]
We made it so that the WindowsDesktop SDK wasn't required for .NET Core 3.x.  It would be nice if that was also the case for .NET Framework, however we never really considered it.

**Comment by vatsan-madhavan** [comment]
These two improvements - (i) M.NETFramework.ReferenceAssemblies implicit PackageReference, and (ii) deprecating WindowsDesktopSDK truly for NetFx targets as well - are so easy to do we should really get this in now for .NET 5. 

IMO (ii) is more important of these - we should not give our developers reasons to stay on WindowsDesktop SDK. Multitargeting net5.0+net48 will become the trivial reason why folks start resorting to a deprecated pattern, and we should fix this before the problem takes root.

**Comment by ryalanms** [comment]
@dsplaisted and @sfoslund:  Who should this issue be assigned to, and where should it be moved?  Thanks.

**Comment by sfoslund** [comment]
@marcpopMSFT made this issue to track automatically importing the windows SDK for .NET framework projects but has not assigned it yet: https://github.com/dotnet/sdk/issues/13939, it looks like we are aiming for 5.0.200 for that change.

**Comment by ryalanms** [comment]
This is being tracked in the SDK repo.
