### ISSUE TITLE
User Input Simulation API

### ISSUE THREAD

**Issue by JansthcirlU** [dotnet/wpf#3539]
## Requested API

Support for simulating various types of user input:
* mouse movement and clicks
* keyboard key presses (this is already possible in Winforms)
* touchscreen finger commands
* stylus actions

## Motivation

WPF is very much still a popular framework for Windows desktop development, despite there being plenty of alternatives such as [UWP](https://docs.microsoft.com/en-us/windows/uwp/), [Avalonia](http://avaloniaui.net/) and [Electron.NET](https://github.com/ElectronNET/Electron.NET) to name a few. Therefore, many developers may be developing touchscreen applications in WPF to scale to support more modern devices.

If there was a way to manipulate the mouse, keyboard and touch functionalities, developers could simulate end-user decisions, which could be useful for demo purposes or even for testing purposes. One could see if a certain chain of end-user decisions leads to a desired outcome. Moreover, simulating keyboard inputs can also be useful to create a customizable on-screen touchscreen keyboard, which simply does not exist as a standard control in WPF.

## The *InputSimulatorCore* NuGet package

There is this NuGet package called [Input Simulator Core](https://github.com/cwevers/InputSimulatorCore) that lets developers simulate keyboard and mouse inputs. It was originally developed to create a touchscreen keyboard. However, it is not being maintained anymore and the input simulations only work on Windows devices. Given that WPF also only works on Windows, that is admittedly not much of an issue. But seeing recent developments at Microsoft with cross-platform application development frameworks such as .NET MAUI, support for user input could provide major advantages for developers working on all platforms.

**Comment by miloush** [comment]
Any issues with `System.​Windows.​Input.InputManager.ProcessInput`?

**Comment by ryalanms** [comment]
You can use the UIAutomation framework to accomplish some of this.  But as of now, WPF has no plans to build a new input simulation framework, as it is outside the scope of our charter.
