### ISSUE TITLE
Smooth, pixel by pixel scrolling

### ISSUE THREAD

**Issue by Poopooracoocoo** [dotnet/wpf#3545]
note: i searched for "scroll" and "scrolling" and yet no one made an issue for this? touchpads and touchscreens could really do with this.

**Comment by miloush** [comment]
Can you provide repro steps of what does not smooth scroll for you?

**Comment by Poopooracoocoo** [comment]
@miloush Do you know of any WPF apps off the top of your head?

**Comment by miloush** [comment]
@Poopooracoocoo yes. Maybe I just don't know what you mean by smooth scrolling and how it differs from the current scrolling behaviour. Can you elaborate?

**Comment by Poopooracoocoo** [comment]
Could you please tell me some of them?

By smooth scrolling, I mean pixel by pixel, as opposed to line by line. This is the difference between a mouse wheel that has notches and a touchscreen, pen or touchpad. You can see this difference in apps like Chrome, Firefox, the Start Menu and Settings.

**Comment by miloush** [comment]
Visual Studio, Expression Design, Message Analyzer, PowerShell ISE, WinDbg, ILSpy, are you looking for anything specific?

The text box seems to be scrolling pixel by pixel by default. List box, combo box and similar items controls can scroll smoothly if you set `ScrollViewer.CanContentScroll="False"` on them... is that what you are looking for?

**Comment by ShankarBUS** [comment]
I guess @Poopooracoocoo is referring to smooth inertial scrolling similar to what MS Edge and UWP/WinUI provides.

Even if we set the `CanContentScroll` to **false**, it still won't be smooth (may be not stuttering but still not smooth).

**Comment by miloush** [comment]
The inertia is on by default and can be controlled by `ScrollViewer.PanningDeceleration`. It looks pretty smooth to me, that's why I was asking for repro steps.

**Comment by ShankarBUS** [comment]
Ever used any UWP apps? OP wants a scrolling experience similar to what UWP offers.

Animated, inertial & smooth scrolling to be precise.

CanContentScroll only toggles between line/content (i.e. one control at a time) scroll. There is no support for pixel by pixel scrolling in WPF natively. We have to use some ugly workarounds just for this.

**Comment by miloush** [comment]
I tried both UWP and WPF with ListBox and about hundred of items using touchpad. They are both smooth, pixel-by-pixel and have inertia. The only difference I can see is 1) speed: UWP scrolls faster on inertia but slower when fingers are still touching compared to WPF 2) UWP bounces when you reach the end of scrolling.

You can also use `VirtualizingPanel.ScrollUnit="Pixel"` instead of `CanContentScroll` which makes the scrolling not only smooth but also way faster.

**Comment by ryalanms** [comment]
@ShankarBUS, thank you for the report.  Can you reactivate this issue with a repro project and more specific details on what is wrong with the scrolling behavior?  Thanks.
