### ISSUE TITLE
unexpected FailFast in AddIfNoPrefixCollisionDetected when _partList.IndexOfKey returns -1 for a partUri that is present in the list (timing issue)

### ISSUE THREAD

**Issue by SamBent** [dotnet/wpf#3563]
When two threads load application resources from one of the predefined packages, there is a race condition that can corrupt the package's cache.  The result is a hard crash (FailFast).

[Port of a servicing fix in .NET 4.7/4.8].

**Comment by ClosetBugSlayer** [comment]
This sounds like yet another symptom of #3411 . You will find more.

"BAML readers in Application.LoadContent() are not protected with locks, resulting in showstopper exceptions"
https://github.com/dotnet/wpf/issues/3411

**Comment by SamBent** [comment]
Fix ported to 3.1.19, 5.0.0, 6.0.
