### ISSUE TITLE
Application window is resizing unexpectedly while moving to another screen (dpiAwareness PerMonitorV2)

### ISSUE THREAD

**Issue by ksosnierz** [dotnet/wpf#3573]
* .NET Core Version: 3.1.301 #7feb845744
* Windows version: 10.0.17134
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 **Problem description:**
Application window is resizing unexpectedly while moving to another screen. It happens only when **dpiAwareness** is set to PerMonitorV2 in the application manifest and the specific screen arrangement is being used:

![image](https://user-images.githubusercontent.com/922275/94126657-2cc66c80-fe58-11ea-935e-9c6393582dfb.png)

Screen 1: 3840x2160, scaling @ 175%
Screen 2: 1920x1080, scaling @ 100%

 
 **Actual behavior:**

![ice_video_20200924-114639](https://user-images.githubusercontent.com/922275/94130182-99436a80-fe5c-11ea-9555-a6ffc58c2565.gif)

 **Expected behavior:**
Resize should be triggered only once when the app is moved between the screens.
 
 **Minimal repro:**
[DpiChangeTest.zip](https://github.com/dotnet/wpf/files/5275241/DpiChangeTest.zip)

**Comment by ryalanms** [comment]
Thank you for the report, @ksosnierz.

**Comment by singhashish-wpf** [comment]
Unable to repro from the provided sample and provided information on .NET 6.0. @ksosnierz  is it possible to check and confirm this on .NET 6.0 ?

**Comment by singhashish-wpf** [comment]
Closing in absence of further information and not reproducing on .NET6.
