### ISSUE TITLE
Microsoft.NET.Sdk.WindowsDesktop crashes on Windows Nano Server

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/wpf#3609]
From https://github.com/dotnet/runtime/issues/42979

BentleyJamesSlater commented 2 days ago • 
Hi ,

Having trouble constructing a Typeface object on windows nanoserver, maybe its a bug, or maybe i'm missing something?

Can be repeated using docker image: mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1909

In C# Just contruct a new System.Windows.Media.Typeface object, using a Microsoft.NET.Sdk.WindowsDesktop project

Typeface font = new Typeface("Arial");

It produces many nested exceptions:

The type initializer for 'System.Windows.Media.FontFamily' threw an exception.
   at System.Windows.Media.Typeface..ctor(String typefaceName)
   at ConsoleApp1.Program.Main(String[] args) in C:\Temp\SmileyFaceWpfLibrary\SmileyFaceWpfLibrary\ConsoleApp1\Program.cs:line 18
---- 
The type initializer for 'MS.Internal.FontCache.DWriteFactory' threw an exception.
   at MS.Internal.FontCache.DWriteFactory.get_SystemFontCollection()
   at System.Windows.Media.FontFamily..cctor()
----
The type initializer for '<Module>' threw an exception.
   at MS.Internal.FontCache.DWriteFactory..cctor()
----
The C++ module failed to load during appdomain initialization.
   at <CrtImplementationDetails>.ThrowModuleLoadException(String errorMessage, Exception innerException)
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
----
dwrite.dll
   at MS.Internal.NativeWPFDLLLoader.LoadDwrite()
   at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   at ?A0x8cc91adf.CreateCModuleInitialize()
   at ?A0x8cc91adf.??__E?A0x8cc91adf@cmiStartupRunner@@YMXXZ()
   at <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
----
The specified module could not be found.

danmosemsft commented 2 days ago
I do not believe Windows Nano Server has support for DWrite. @SamBent ?

@danmosemsft
 
Member
danmosemsft commented 2 days ago
@fabiant3 can you please transfer to WPF? I do not have rights to do so.

@danmosemsft
 
Member
danmosemsft commented 2 days ago
@BentleyJamesSlater curious about your scenario here. Given Nano Server is headless, why are you instantiating fonts? I am not sure how much or any of WPF will work, but I am not on the WPF team and they should answer that.

@BentleyJamesSlater
 
Author
BentleyJamesSlater commented 2 days ago
@BentleyJamesSlater curious about your scenario here. Given Nano Server is headless, why are you instantiating fonts? I am not sure how much or any of WPF will work, but I am not on the WPF team and they should answer that.

Im trying to produce some graphical pdf reports. Our existing code base runs as a rest api on windows servers, which we are attempting to containerise. Im not sure its going to work out as we use wpf to produce a xps document, which is then converted into pdf. XPS support isnt looking good.

@danmosemsft
 
Member
danmosemsft commented 2 days ago
I see. I wonder what alternatives there might be to generate PDF.

**Comment by jeffschwMSFT** [comment]
@BentleyJamesSlater

**Comment by fabiant3** [comment]
@ryalanms

**Comment by SamBent** [comment]
The exception occurs because dwrite.dll can't be found.  WPF needs DWrite, especially for anything involving text and fonts, so the absence of dwrite.dll on windows nanoserver implies that WPF is not supported on nanoserver.  There's nothing we can do about that.
[I edited the title for clarity]

**Comment by danmosemsft** [comment]
@bentleyjamesslater have you tried using Windows Server Core instead?

**Comment by vatsan-madhavan** [comment]
Server Core ought to work. If you see nothing rendering, then investigate the use of [`Switch.System.Windows.Media.ShouldRenderEvenWhenNoDisplayDevicesAreAvailable`](https://github.com/microsoft/WPF-Samples/blob/c6321b20a0161701f2b37ab4218566c8ed658740/Compatibility/runtimeconfig.template.json#L84) in `runtimeconfig.json`.

**Comment by BentleyJamesSlater** [comment]
thanks @vatsan-madhavan , Yes I have got it working with server core, although I was put off by an low level unrelated exceptions - System.ExecutionEngineException, this turned out to be because the fonts where missing. Now selecting an avalible font and it works

**Comment by danmosemsft** [comment]
ExecutionEngineException it’s probably worth its own issue (with repro steps). That means that the app process is potentially in a corrupt state which doesn’t sound reasonable for a missing font
