### ISSUE TITLE
Build produces *wpftmp* folder for every application.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#3616]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1166456/build-produces-wpftmp-folder-for-every-application.html)._

---
[severity:I'm frustrated, but able to complete my work]
We have a solution with around 250 projects. There are around 15 projects in it the produce a console or wpf application. With one of the latest updates we now get for every build an automatically generated folder with the "_wpftmp" extension. For example if the is called Test you get the folder "Test_{some random number}_wpftmp". The folder is left empty.

This is really annoying since I have many unused folders in my target output.

---
#### Feedback Bot on 8/28/2020, 03:54 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sara Liu [MSFT] on 8/30/2020, 08:15 PM: 

<p>Dear customer, thank you for your feedback and I am sorry to hear that you are running into this issue.<br>
Does this folder is under the solution root folder or each project folder? Would you please help to check this issue happens to this specific solution or all solutions? I tried to create some solutions to test it, but unable to reproduce this issue in VS 2019 16.8 Preview 2.</p>

#### msedi on 8/31/2020, 10:02 AM: 

Yes, I can see it in Preview 2 and also in productive VS2019. So it&#39;s not a problem of the Preview.<br><br>I think it is also related to here: https://developercommunity.visualstudio.com/content/problem/210156/msbuild-is-adding-a-random-hash-and-wpftmp-to-my-a.html.<br><br>I&#39;m not sure if it has to do with our build configuration, but it&#39;s a pretty simple one.
#### Ryland Alaniz [MSFT] on 8/31/2020, 11:41 AM: 

<p>Is the project targeting .NET Framework or .NET Core?  Which version?  Thanks.</p>

#### Martin Sedlmair on 8/31/2020, 02:22 PM: 

<p>Sorry, I thought you can can derive this from the attached log files. It is a .NET Core project </p><pre>&lt;Project Sdk="Microsoft.NET.Sdk.WindowsDesktop"&gt;
  &lt;PropertyGroup&gt;
    &lt;OutputType&gt;WinExe&lt;/OutputType&gt;
    &lt;TargetFramework&gt;net5.0&lt;/TargetFramework&gt;
    &lt;UseWPF&gt;true&lt;/UseWPF&gt;
  &lt;/PropertyGroup&gt;
&lt;/Project&gt;</pre><p>We have indeed a few specialities, like we are using the Directory.Build.props recursively, we redirect the OutputPath/OutputDir and the IntermediatePath.</p><p>It is only for projects with XAML/WPF. All others do not show this problem. It is also completely undeterminstic to me when the folder is created.</p><p>I would recreate this issue with a simple project, but since all apps and libraries are part of a very large solution I'm not sure if I can easily create a small repro solution.</p>

#### msedi on 9/1/2020, 00:40 AM: 

<p>Sorry, it should be a netcoreapp3.1 and not net5.0.</p>

#### msedi on 9/8/2020, 03:50 AM: 

<p>Any news on this?</p>

---
### Original Solutions
(no solutions)

**Comment by ryalanms** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1184439

**Comment by PKobold** [comment]
@ryalanms  Any news on this? We experience the same problem. VS Version 16.8.4
In addition to the original description the tmp folder contains no files but is not empty and contains a folder structure (with no files)
i.e. {appname}_randomExpr_wpftmp\bin\x64\Debug\netcoreapp3.1

We redirect the output via the BaseOutputPath property
`<BaseOutputPath>$(CSharpBuildDir)\$(MSBuildProjectName)\bin</BaseOutputPath>`
and build content is placed like expected i.e. BaseOutputPath results in
`D:\build\ProjName\bin`
The expected content is build/placed into
`D:\build\ProjName\bin\x64\Debug\netcoreapp3.1`

But it also leaves behind the said emptry folder structure
`D:\build\ProjName_randomExpr_wpftmp\bin\x64\Debug\netcoreapp3.1`

which is very annoying :/

**Comment by PKobold** [comment]
Digging a bit deeper i came across this https://github.com/dotnet/wpf/issues/2930 which is related to the issue here and is also open. The proposed workaround https://github.com/dotnet/wpf/issues/2930#issuecomment-654130569 to build a cleanup target inside Directory.Build.targets works fine though. 

Still a strange behavior and an official clarification would be nice :)

**Comment by msedi** [comment]
Any news on this?

**Comment by DanForever** [comment]
For what it's worth this is something I'm experiencing with my project here: https://github.com/DanForever/Arduino-PC-Health-Monitor

**Comment by vishalmsft** [comment]
Thank you for update on the issue. Closing this issue, to have all future discussions at #2930
