### ISSUE TITLE
[5.0.100-rtm.20508.12] Greenshot failed to build

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/wpf#3628]
**Application Name:** Greenshot
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 5.0.100-rtm.20508.12
**App Source:** 
\\\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\AppSources\greenshot
**DevDiv bug:**
[https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1228900](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1228900)

**Repro steps:**
Copy \\\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\AppSources\greenshot to local machine.
Open command prompt windows as Administrator.
Navigate to "greenshot\src\Greenshot".
Run "dotnet build" command to build the application.

**Expected Result:**
The build process should successful.
**Actual Result:**
The build process stopped due to the error message.

**Findings:**
According to the error message, it was finding the xaml files from obj\Debug\net5.0-windows\Views\. We tried deleleted both bin and obj folder and rebuild again, it still get the same error.

**Exception from build process:**
```
C:\SingleFileAppsTest\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\ExportNotificationView.g.cs(49,18): error CS1504: Source file '..\..\..Views\ExportNotificationView.xaml' could not be opened -- Could not find file. [C:\SingleFileAppsTest\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileAppsTest\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\ExportNotificationView.g.cs(70,21): error CS1504: Source file '..\..\..Views\ExportNotificationView.xaml' could not be opened -- Could not find file. [C:\SingleFileAppsTest\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileAppsTest\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\FileConfigPartView.g.cs(45,18): error CS1504: Source file '..\..\..Views\FileConfigPartView.xaml' could not be opened -- Could not find file. [C:\SingleFileAppsTest\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileAppsTest\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\FileConfigPartView.g.cs(66,21): error CS1504: Source file '..\..\..Views\FileConfigPartView.xaml' could not be opened -- Could not find file. [C:\SingleFileAppsTest\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileAppsTest\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\UploadView.g.cs(58,21): error CS1504: Source file '..\..\..Views\UploadView.xaml' could not be opened -- Could not find file. [C:\SingleFileAppsTest\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
```

The app works with .NET5 RC2, but failed to build with .NET 5 RTM.

CC @dotnet-actwx-bot

**Comment by ryalanms** [comment]
@jiangzeng01:  I am unable to access the share.  Could you attach the project to the bug?  Thanks.

**Comment by jiangzeng01** [comment]
@ryalanms You can also use GitHub source: 
[https://github.com/greenshot/greenshot.git](https://github.com/greenshot/greenshot.git)

**Build steps:**
Open a powershell / shell in the directory where you cloned this repo
run dotnet build src/Greenshot.sln

**Errors:**
```
D:\repos\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\ExportNotificationView.g.cs(49,18): error CS1504: Source file '..\..\..Views\ExportNotificationView.xaml' could not be opened -- Could not find file. [D:\repos\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
D:\repos\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\ExportNotificationView.g.cs(70,21): error CS1504: Source file '..\..\..Views\ExportNotificationView.xaml' could not be opened -- Could not find file. [D:\repos\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
D:\repos\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\FileConfigPartView.g.cs(45,18): error CS1504: Source file '..\..\..Views\FileConfigPartView.xaml' could not be opened -- Could not find file. [D:\repos\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
D:\repos\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\FileConfigPartView.g.cs(66,21): error CS1504: Source file '..\..\..Views\FileConfigPartView.xaml' could not be opened -- Could not find file. [D:\repos\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
D:\repos\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\UploadView.g.cs(58,21): error CS1504: Source file '..\..\..Views\UploadView.xaml' could not be opened -- Could not find file. [D:\repos\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
```

**Comment by ryalanms** [comment]
This should be fixed with https://github.com/dotnet/wpf/pull/3637.  Thanks.

**Comment by jiangzeng01** [comment]
Thanks @ryalanms 
According the conversation in [https://github.com/dotnet/wpf/pull/3637](https://github.com/dotnet/wpf/pull/3637), the fix will come in .NET 5 servicing release, so is it will not be in .NET 5 RTM release?

**Comment by ryalanms** [comment]
This bug is fixed in .NET 5.0 RTM.  The 'fix' that was reverted to fix this bug will be updated and reapplied in a servicing release (5.0.2xx).

**Comment by jiangzeng01** [comment]
@ryalanms Thanks for update, we will verify the bug with new RTM builds then.

**Comment by ryalanms** [comment]
Thanks.

**Comment by jiangzeng01** [comment]
Verified with 5.0.100-rtm.20515.8, the issue was fixed, so close.
