### ISSUE TITLE
Wpf produces a wrong event handler if the event has a tuple parameter

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/wpf#3631]
I faced a strange Xaml behavior in VB WPF (.net Framework). I didn't find the template for WPF .NET core, so, I tested it in C# WPF.Core and got the same issue! I expect it exists in VB WPF .NET Core also as well:

Steps to reproduce:
1- Crate a new WPF .NET Core in VB.NET or C#
2. Add a UserControl to it, and add this code in the code behind:
```VB.NET
Public Class UserControl1
    Public Event RangeChanged(sender As Object, e As (fromDate As Date?, toDate As Date?))

End Class
```

```C#
    public partial class UserControl1 : UserControl
    {
        public UserControl1()
        {
            InitializeComponent();
        }

        public delegate void  RangeChangedHandler(object sender, (DateTime? fromDate, DateTime toDate) e);

        public event RangeChangedHandler  RangeChanged;
    }
```

I am using a tuple as a param of the event. It seems that Xaml doesn't handle this well.

in the main window, try to handle this event:
```xaml
    <Grid>
        <local:UserControl1 RangeChanged="UserControl1_RangeChanged"/>
    </Grid>
```

and let the editor declare the ` UserControl1_RangeChanged` sub.
In the .net framework version, I got this:
```vb.net
Private Sub UserControl1_RangeChanged(sender As Object, e As (fromDate As Date?, ))

    End Sub

    Private Sub UserControl1_RangeChanged(sender As Object, e As (fromDate As Date?, ))

    End Sub
```

```C#
        private void UserControl1_RangeChanged(object sender, (DateTime? fromDate, ) e)
        {

        }

        private void UserControl1_RangeChanged(object sender, (DateTime? fromDate, ) e)
        {

        }
```

Yes, it is repeated twice, with a missing param in each!

**Comment by ryalanms** [comment]
Thanks, @VBAndCs.  The event handler generation is done by Visual Studio, not WPF.  Please open a Visual Studio feedback ticket.  Thanks.

**Comment by VBAndCs** [comment]
@ryalanms
This soesn't happen when I create the handler from the Code editor' navigation list. It happens only from in Xaml editor. I thought it relates to WPF.

**Comment by VBAndCs** [comment]
@ryalanms
VS community asks me to sign in so send the report, while I am already signed in!
So, I can report this bug. I hope you can do.
I will not do anything further in this matter. Its up to you.
Thanks.

**Comment by ryalanms** [comment]
Thanks, @VBAndCs.  We will get it to the VS team.
