### ISSUE TITLE
OutOfMemoryException  (DUCE+Channel.SyncFlush())

### ISSUE THREAD

**Issue by hepper** [dotnet/wpf#3633]
.net app crash with 

`
OutOfMemoryException Недостаточно памяти для продолжения выполнения программы. 
PresentationCore в System.Windows.Media.Composition.DUCE.Channel.SyncFlush() 
в System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable channelSet)
в System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
в System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
в System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

target mashine win 10.0.18363.0
net framework 4.7.2
the error appears if the system has "GeForce Experience v3.20.4.14" installed
(after uninstalling "GeForce Experience" - no error appears)

**Comment by ClosetBugSlayer** [comment]
I find that WPF renders more slowly on an nVidia 1080ti 11GB than on an AMD Radeon 7850 which is almost a decade older. The longer the machine runs, the slower WPF top-level primitives take to appear, up to a whole second in many cases. Something is leaking but I don't know what.

**Comment by miloush** [comment]
@hepper Do you have a repro project? Are you actually running out of memory, or are you running out of GDI handles?

**Comment by hepper** [comment]
> @hepper Do you have a repro project? 
no :(


The reason cannot be determined, but the application's memory consumption is low, no more than 500MB. The problem is not a lack of memory, as it seems to me.

**Comment by miloush** [comment]
Can you add "GDI objects" column to the task manager and see if it is reaching limits for your application?

**Comment by hepper** [comment]
@miloush yes, I'll try

**Comment by theindra** [comment]
I have the same issue with an WPF application .NET 4.7.2. 
The application runs on thousands of PCs flawlessly.
But on Windows Server 2012 and Windows 8 I get this error when it loads a specific screen.

The strange thing is. It works when I start the application the first time after installation. After that this error appears.

Any hint?

**Comment by hepper** [comment]
@miloush hi.
I added process data collection to the application at the time of the error. and I get values like this:
 gdiHandles: 40-50, userHandles: 50-60,
process.HandleCount: 100000-200000, process.Threads.Count: 20-40. 
maybe it's somehow connected?

**Comment by hepper** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/2721256/99307409-84d18c00-2867-11eb-8600-b145a0ccc0c1.png)
![Screenshot_1](https://user-images.githubusercontent.com/2721256/99307412-856a2280-2867-11eb-80e7-bb3a68a73cf2.png)


Where do they come from?

**Comment by miloush** [comment]
What does your app do? Any image processing/rendering?

**Comment by hepper** [comment]
app - custom browser for game with cefsharp core

**Comment by hepper** [comment]
usually on all machines the number of handles does not exceed 2000, and only sometimes on some such a bug appears. related to nvidia software and drivers

**Comment by hepper** [comment]
Empirically, I found out that if there are some versions of the "GeForce Experience" application in the system, after starting my application, the handles "\Sessions\1\BaseNamedObjects\{1ABAC973-1361-4C7B-B9CE-6A084DB70189}_v2" appear in its process, the number which grows, causing my application to crash. The same handles are available in the "GeForce Experience" application. Apparently this is not related to the "WPF"

**Comment by SamBent** [comment]
@hepper - If your problem is not related to WPF, please close the issue (or allow me to do so).  

Everyone else - your problem is probably different from this, even though you see the same exception and callstack.  Please read https://docs.microsoft.com/en-us/troubleshoot/dotnet/framework/wpf-render-thread-failures for a discussion and some limited advice.
