### ISSUE TITLE
Wpf app is released as a single file and cannot be run.

### ISSUE THREAD

**Issue by lifuhua123** [dotnet/wpf#3634]
* .NET Core Version: ( .net 5 RC.1)
* Windows version: (windows 10)
* Does the bug reproduce also in WPF for .NET Framework 4.8?:No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)?:No
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/master/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**
 I tried winform and wpf independent deployment scheme under .net 5 RC.1, winform can run successfully, but wpf cannot start.

 **Actual behavior:** The program cannot be started
 **Expected behavior:** The program runs normally
 
 **Minimal repro:** Build a basic wpf program based on .net 5,select single file and ReadyToRun publish.

**Comment by ryalanms** [comment]
@lifuhua123:  This doesn't work in RC1.  Can you try RC2 or later?  Thanks.

**Comment by lindexi** [comment]
Duplicate of #3516 ?

**Comment by ryalanms** [comment]
Thanks, @lindexi.  WPF works with RC2+ for me locally, but I do hit the bug @ericstj identified.  RC1 doesn't start.

**Comment by ducanhtk5** [comment]
**I get an error in Event Viewer when I try to open a new window:**

Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x1183946c
Exception code: 0xc000041d
Fault offset: 0x0000000000023e49
Faulting process id: 0x68b8
Faulting application start time: 0x01d6a378582d3a65

**Comment by ryalanms** [comment]
Could you share the version of the .NET SDK that is installed?  Thanks.
