### ISSUE TITLE
Misc build failures in 'official/dotnet/wpf-int/refs/heads/master' - '20190219.1'

### ISSUE THREAD

**Issue by robertborr** [dotnet/wpf#365]
@dotnet-mc-bot commented on [Tue Feb 19 2019](https://github.com/dotnet/core-eng/issues/5256)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=99570
  - **Agent:** DDVSOWINAGE312
  - **Error log:** E:\A\_work\0\s\Packaging.targets(0,0): error MSB3026: Could not copy "E:\A\_work\0\s\LICENSE.TXT" to "E:\A\_work\0\s\artifacts\packaging\platform\Microsoft.DotNet.Wpf.DncEng\LICENSE.TXT". Beginning retry 1 in 1000ms. The process c...

@robertborr

---

@robertborr commented on [Tue Feb 19 2019](https://github.com/dotnet/core-eng/issues/5256#issuecomment-465273689)

E:\A\_work\1\s\Packaging.targets(58,5): error MSB3026: Could not copy "E:\A\_work\1\s\LICENSE.TXT" to "E:\A\_work\1\s\artifacts\packaging\Debug\Microsoft.DotNet.Wpf.DncEng\LICENSE.TXT". Beginning retry 1 in 1000ms. The process cannot access the file 'E:\A\_work\1\s\artifacts\packaging\Debug\Microsoft.DotNet.Wpf.DncEng\LICENSE.TXT' because it is being used by another process.  [E:\A\_work\1\s\packaging\Microsoft.DotNet.Wpf.DncEng\Microsoft.DotNet.Wpf.DncEng.csproj]
E:\A\_work\1\s\Packaging.targets(58,5): error MSB3026: Could not copy "E:\A\_work\1\s\LICENSE.TXT" to "E:\A\_work\1\s\artifacts\packaging\Debug\Microsoft.DotNet.Wpf.DncEng\LICENSE.TXT". Beginning retry 1 in 1000ms. The process cannot access the file 'E:\A\_work\1\s\artifacts\packaging\Debug\Microsoft.DotNet.Wpf.DncEng\LICENSE.TXT' because it is being used by another process.  [E:\A\_work\1\s\packaging\Microsoft.DotNet.Wpf.DncEng\Microsoft.DotNet.Wpf.DncEng.csproj]
E:\A\_work\1\s\Packaging.targets(184,5): error MSB3061: Unable to delete file "E:\A\_work\1\s\artifacts\packaging\Debug\Microsoft.DotNet.Wpf.DncEng\version.txt". The process cannot access the file 'E:\A\_work\1\s\artifacts\packaging\Debug\Microsoft.DotNet.Wpf.DncEng\version.txt' because it is being used by another process. [E:\A\_work\1\s\packaging\Microsoft.DotNet.Wpf.DncEng\Microsoft.DotNet.Wpf.DncEng.csproj]
    0 Warning(s)
    3 Error(s)

---

@robertborr commented on [Tue Feb 19 2019](https://github.com/dotnet/core-eng/issues/5256#issuecomment-465295326)

looks like a build synchronization issue. moving to wpf

**Comment by vatsan-madhavan** [comment]
I have a PR in the works that should fix this shortly.
