### ISSUE TITLE
Wpf app is released as a single file and cannot be run.

### ISSUE THREAD

**Issue by lifuhua123** [dotnet/wpf#3650]
# Issue Title

Wpf app is released as a single file and cannot be run.

# General
I tried winform and wpf independent deployment scheme under .net 5 RC.1, winform can run successfully, but wpf cannot start.

**Comment by lindexi** [comment]
Duplicate of #3634 ？

**Comment by ryalanms** [comment]
Yes, @lindexi, it looks like a duplicate to me as well.  

From my understanding, SingleFile wasn't supported until RC2, but there is another blocking bug noted in #3634.
