### ISSUE TITLE
Replace obsolete APIs used by WPF

### ISSUE THREAD

**Issue by ryalanms** [dotnet/wpf#3660]
WPF is using obsolete APIs.  These need to be replaced for 6.0.  

WebRequest.WebRequest()
WebRequest.Create(Uri)
Uri.EscapeUriString(string)

```
D:\wpf7\src\Microsoft.DotNet.Wpf\src\PresentationCore\ref\PresentationCore.cs(11,9): error SYSLIB0014: 'WebRequest.WebR
equest()' is obsolete: 'Use HttpClient instead.' [D:\wpf7\src\Microsoft.DotNet.Wpf\src\PresentationCore\ref\Presentatio
nCore-ref.csproj]

D:\wpf7\src\Microsoft.DotNet.Wpf\src\PresentationCore\MS\Internal\WpfWebRequestHelper.cs(76,30): error SYSLIB0014: 'Web
Request.Create(Uri)' is obsolete: 'Use HttpClient instead.' [D:\wpf7\src\Microsoft.DotNet.Wpf\src\PresentationCore\Pres
entationCore.csproj]

D:\wpf7\src\Microsoft.DotNet.Wpf\src\ReachFramework\PrintConfig\FallbackPTProvider.cs(403,29): error SYSLIB0013: 'Uri.E
scapeUriString(string)' is obsolete: 'Uri.EscapeUriString can corrupt the Uri string in some cases. Consider using Uri.
EscapeDataString for query string components instead.' [D:\wpf7\src\Microsoft.DotNet.Wpf\src\ReachFramework\ReachFramew
ork.csproj]
```

**Comment by ryalanms** [comment]
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/obsolete-apis-with-custom-diagnostics

@jeffhandley:  WPF has some uses of WebRequest and HttpWebRequest that will be very difficult to remove.  Is it possible for WPF to continue using them or will they stop working for .NET 6.0?

**Comment by jeffhandley** [comment]
Those APIs will continue to function in .NET 6; you can suppress the warnings if you need to continue using them.

https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0014#workarounds

**Comment by ryalanms** [comment]
@singhashish-wpf:  Let's defer the WebRequest and HttpWebRequest replacements to .NET 7.0.  Please leave the existing suppression for SYSLIB0014 in place.

**Comment by ryalanms** [comment]
This is being tracked by https://github.com/dotnet/wpf/issues/5178.
