### ISSUE TITLE
Webview in WPF app won't connect to intranet computer, but will connect to internet.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#370]
<p>I have a small WPF app and I have a UserControl that I'm using &quot;webview&quot; in.  I am using Visual Studio 2017 and doing the WPF app in C#.   I use the UserControl in the main window.  If I put in a URI for a site like Microsoft.com or Google.Com, &quot;webview&quot; will navigate to the site successfully.  If I put in a local computer URI, &quot;http://192.168.1.11/ panel&quot;, &quot;webview&quot; will not navigate and gives me an error of &quot;Not Found&quot;.  If I put this URI into the Edge browser it navigates successfully.  I have been unsuccessful in finding why it won't navigate to a local computer.  I have tried putting the WPF App's .exe assembly into allowed &quot;app&quot;  in Windows Defender for both incoming and outgoing traffic.  The Windows Defender log looks like it is dropping some of the outgoing traffic to the target computer.  I have put the target computer in Internet Options as a trusted Intranet address.  Nothing seems to work.  I have run out of things to check. I can't seem to find similar issues for webview.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/464342/webview-in-wpf-app-wont-connect-to-intranet-comput.html
VSTS ticketId: 796996_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by dotMorten** [comment]
This happens in UWP if you don’t add the “Private Networks” capability. Since WebView is UWP, I’m guessing you’re hitting something like this? (I'm not entirely sure how you'd enable this for a WPF app with WebView)

**Comment by WayneBBB** [comment]
dotMorten:  Your solution worked.  Thanks for the quick response.  Wayne

**Comment by stevenbrix** [comment]
Thanks @WayneBBB for filing this issue and @dotMorten for providing the fix!

Closing since this issue has been resolved.
