### ISSUE TITLE
The word “library” should be capitalized in the name of "WPF Class library" template.

### ISSUE THREAD

**Issue by AR-May** [dotnet/wpf#3725]
Please take a look at the field "[name](https://github.com/dotnet/wpf/blob/04630f0c21784c388f7d82ed78925a43088d9132/packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json#L5)" of the corresponding template.json file. It seems that the word "library" there should be capitalized.

**Comment by ryalanms** [comment]
Hi @AR-May.  The location of the .NET Core template is here: 

packaging\Microsoft.Dotnet.Wpf.ProjectTemplates\content\WpfClassLibrary-CSharp

Can you make the change?  Thanks.

**Comment by ryalanms** [comment]
@AR-May:  Thank you for the fix.  

/cc @dotnet/wpf-developers
