### ISSUE TITLE
FatalExecutionEngineError in WPF simple application

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#3748]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/FatalExecutionEngineError-in-WPF-simple-/720919)._

---
A colleague has discovered this. Just create an empty .NET Framework WPF application, and replace the default Window XAML by this:

&lt;Window x:Class=&quot;WpfApp1.MainWindow&quot;
        xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;       
        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;   
        DataContext=&quot;{Binding RelativeSource={RelativeSource Self}}&quot;&gt;
    &lt;Grid&gt;
        &lt;ContentPresenter Content=&quot;{Binding}&quot;/&gt;
    &lt;/Grid&gt;
&lt;/Window&gt;

* Execute with debugging

You'll get:

Managed Debugging Assistant 'FatalExecutionEngineError' 
  Message=Managed Debugging Assistant 'FatalExecutionEngineError' : 'The runtime has encountered a fatal error. The address of the error was at 0x6f4f623f, on thread 0x880. The error code is 0x80131623. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.'

Expected: a better error message.

We understand that this code could/should crash, but we think it should be better handled.

---
#### Feedback Bot on 9/4/2019, 02:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/8/2019, 05:25 PM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by SamBent** [comment]
The message comes from an assert in `UIElement.PropagateResumeLayout`:
```
                Invariant.Assert(!e.MeasureInProgress && !e.ArrangeInProgress);
```
The assert fails in this case - a runaway recursion.  But changing the code is wrong, IMHO:
- Turning off the assert for the sake of this case would lose early detection of bugs in the layout code.
- We can't detect that we're in a runaway recursion, except by letting it overflow the stack.  So we cannot change the assert to be more forgiving in this case.  
- The message is the generic "FailFast" message.  We could change it to something that mentions layout, but that would be even less helpful in the runaway recursion case.
- The assert seems dependent on the debugger environment.  With VS JIT-debugging enabled, I get StackOverflow exception instead (as expected).
- It only arises in an obviously pathologically bad pattern.  Users should be able to recognize it, despite the unhelpful message.

Leave the code as it is.  Closing.
