### ISSUE TITLE
WPF RichTextBox - pasting a numbered list from a mail received in Outlook will put 1. instead of the actual number shown in the mail

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#3752]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/WPF-RichTextBox---pasting-a-numbered-lis/737081)._

---
<p>This is a re-post, as this is still a problem.</p> <p>https://developercommunity.visualstudio.com/content/problem/395861/wpf-richtextbox-pasting-a-numbered-list-from-a-mai.html</p> <p><strong></strong><u></u><sub></sub><sup></sup></p><p>1) Create a simple WPF app just having a RichTextBox control.</p> <p>2) Create a simple mail in outlook 2013 containing a simple numbered list and sent it to yourself. <br>-In outlook the content look like this</p> <ol>   
<li>line one</li>  
<li>line two</li>  
<li>line three</li></ol> <p>3) In the mail received, copy the content and paste it to the WPF RichTextBox. <br>-In the WPF app it will look like this (the numbering is gone)</p> <p>1.line one </p> <p>1.line two </p> <p>1.line three</p> <p>If you had a mixed list which also used characters for &quot;bulleting&quot;, all letters would be replaced by a) <br><br>Using .Net 4.7 on Windows 10.</p>

---
#### Feedback Bot on 9/18/2019, 11:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/25/2019, 10:24 AM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Stefan Reichelt on 12/13/2019, 09:28 PM: 

<p>I wonder why so few users seem to have this issue. I think it's pretty annoying.</p>

---
### Original Solutions
(no solutions)

**Comment by ryalanms** [comment]
This is a known limitation of the translation from Word's format to XPS format.

**Comment by fabriceleal** [comment]
Well, can't it be fixed?
