### ISSUE TITLE
Possible unmanaged memory leak when running code using Print API(DocumentPaginator) on Windows 10

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#3754]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Possible-unmanaged-memory-leak-when-runn/775134)._

---
<p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/98147-2019-10-11-15-41-58.png">2019-10-11-15-41-58.png</a></p><p> <a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/98147-2019-10-11-15-41-58.png"></a><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/98148-wpfprinttest.zip">wpfprinttest.zip </a></p><p>Please refer to attached image and solution.</p> <p>Same code running on different OS have different result,</p><p>Windows 7: Did not observe any unmanaged memory leak.</p> <p>Windows 10: Observed memory keep increasing and checking in memory profiler shows that there is unmanaged memory leak.</p>

---
#### Feedback Bot on 10/14/2019, 11:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Kok Yong Teo on 10/31/2019, 03:37 PM: 

<p>Hi,</p><p>Any update for this issue?</p>

#### Feedback Bot on 11/22/2019, 03:09 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Kok Yong Teo on 6/17/2020, 08:36 AM: 

<p>Hi,</p><p>I am still facing this issue and I have submitted a sample application which can clearly reproduce this issue.</p><p>Please advise.</p>

---
### Original Solutions
(no solutions)

**Comment by SamBent** [comment]
Investigation into the companion .NET Framework servicing request yielded the following:

- The "leaking" objects are COM objects exposing [IXpsOMFontResource](https://docs.microsoft.com/en-us/windows/win32/api/xpsobjectmodel/nn-xpsobjectmodel-ixpsomfontresource), owned by the OS print component.
- They're not actually leaking.  They accumulate throughout the course of printing the document, but are released and freed at the end.  The "leak" affects very long documents.
- The leak has nothing to do with "DocumentPaginator".  That's just a convenient way to generate long documents.
- WPF creates (actually, asks the OS to create) the font objects every 4 pages, giving the print spooler the data it needs to actually print the 4 pages.  Waiting longer would hobble the spooler.
- The OS exposed a new print stack in Windows 8.1 (or thereabouts), that WPF uses if available.  This explains the difference between Win7 and later.
- We discovered one reference that WPF fails to release in a timely way.  Fixing this is necessary to fixing the "leak".
- But not sufficient.  The OS print component holds other references that aren't released until the document is done.  We don't know any way for WPF to encourage their release.

Thus, this bug needs fixes in WPF and in the OS print stack.  Either one by itself won't change anything.  WPF can add our fix in .NET 6.0.   We've opened a bug for the OS print team to do their part.

**Comment by wstaelens** [comment]
what is the status of this @SamBent ?

**Comment by wstaelens** [comment]
Any status updates @SamBent ?

**Comment by hiteshwpfmsft** [comment]
This issue was fixed with [PR](https://github.com/dotnet/wpf/pull/9250)
