### ISSUE TITLE
CollectionViewGroup.Items not raising PropertyChanged after having an item added?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#3770]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/CollectionViewGroupItems-not-raising-Pr/958020)._

---
<p>Hello!</p><p>I was trying to add grouping with subtotal sum into WPF DataGrid. The solution is to have an ObservableCollection with the data, wrap it into CollectionViewSource which in turn will be ItemsSource for the DataGrid. Subtotal is calculated with a converter, which receives Items of CollectionViewGroup as input and calculates the sum.</p><p>All works fine only at the initial population of the ObservableCollection, or when adding an item creates the new group. But if an item is added into any existing group, converter is simply not called for recalculation - apparently CollectionViewGroup.Items is not raising PropertyChanged event!</p><p>I browsed a bit in <a href="https://referencesource.microsoft.com/PresentationFramework/src/Framework/System/Windows/Data/CollectionViewGroup.cs.html" target=_blank>CollectionViewGroup.cs source</a> - Items are ReadOnlyObservableCollection&lt;object&gt;, which should trigger PropertyChanged after an item added, shouldn't it?</p><p>Then I noticed, that CollectionViewGroup.ItemCount is displayed properly after adding new items, so I tried a trick with a MultiBinding - added an IMultiValueConverter converter which takes both Items and ItemCount as parameters, expecting ItemCount to trigger the recalculation. I  worked, but again without full success - somehow the converter gets the correct input only once, when the new group is created. If an item was added to an existing group, ItemCount is correct, but Items are not! Items collection is missing the newly added item! E.g. when ItemCount=2, Items have only 1 &quot;old&quot; item (Items.Count=1). When ItemCount=3, Items have only 2 &quot;old&quot; items (Items.Count=2), etc. So again the converter cannot calculate the correct subtotal, because the input is incomplete...</p><p>It looks  like the only working solution would be calling Refresh() for the whole CollectionViewSource, but that expands all the groups, cause flickering, breaks MVVM concept, so it is ugly...</p><p>So my questions are:</p><ul><li>Is there still any change to make CollectionViewGroup.Items raise PropertyChanged properly?</li><li>Isn't it a bug in CollectionViewGroup, that when adding an item, Multi Converter receives Items.Count = ItemCount - 1?</li></ul><p>Any advice would be highly appreciated!</p><p>The full sample code is on <a href="https://github.com/pavka1799/ObservableVsConverter.git" target=_blank>GitHub</a>.</p><p>Some code excerpts are below -<br><strong>XAML</strong>:</p><pre>                &lt;DataGrid.GroupStyle&gt;
                &lt;GroupStyle&gt;
                    &lt;GroupStyle.ContainerStyle&gt;
                        &lt;Style TargetType=&quot;{x:Type GroupItem}&quot;&gt;
                            &lt;Setter Property=&quot;Margin&quot; Value=&quot;0,0,0,5&quot;/&gt;
                            &lt;Setter Property=&quot;Template&quot;&gt;
                                &lt;Setter.Value&gt;
                                    &lt;ControlTemplate TargetType=&quot;{x:Type GroupItem}&quot;&gt;                                       
                                        &lt;Expander IsExpanded=&quot;True&quot; BorderThickness=&quot;1,1,1,5&quot;&gt;
                                            &lt;Expander.Header&gt;
                                                &lt;DockPanel&gt;
                                                    &lt;TextBlock FontWeight=&quot;Bold&quot; Text=&quot;{Binding Path=Name}&quot; Margin=&quot;5,0,0,0&quot; Width=&quot;100&quot;/&gt;
                                                    &lt;TextBlock FontWeight=&quot;Bold&quot; Text=&quot;{Binding Path=ItemCount}&quot;/&gt;
                                                    &lt;TextBlock FontWeight=&quot;Bold&quot; Text=&quot;Sum 1: &quot; Margin=&quot;5,0,0,0&quot;/&gt;
                                                    &lt;TextBlock FontWeight=&quot;Bold&quot;  &gt;
                                                        &lt;TextBlock.Text&gt;
                                                            &lt;Binding Path=&quot;Items&quot; Converter=&quot;{StaticResource sumConverter}&quot; ConverterParameter=&quot;AmountValue&quot; StringFormat=&quot;{}{0:N2}&quot;/&gt;
                                                        &lt;/TextBlock.Text&gt;
                                                    &lt;/TextBlock&gt;
                                                    &lt;TextBlock FontWeight=&quot;Bold&quot; Text=&quot;Sum 2: &quot; Margin=&quot;5,0,0,0&quot;/&gt;
                                                    &lt;TextBlock FontWeight=&quot;Bold&quot;  &gt;
                                                        &lt;TextBlock.Text&gt;
                                                            &lt;MultiBinding Converter=&quot;{StaticResource sumMulConverter}&quot; ConverterParameter=&quot;AmountValue&quot; StringFormat=&quot;{}{0:N2}&quot;&gt;
                                                                &lt;Binding Path=&quot;Items&quot;/&gt;
                                                                &lt;Binding Path=&quot;ItemCount&quot;/&gt;
                                                            &lt;/MultiBinding&gt;
                                                        &lt;/TextBlock.Text&gt;
                                                    &lt;/TextBlock&gt;
                                                &lt;/DockPanel&gt;
                                            &lt;/Expander.Header&gt;
                                            &lt;Expander.Content&gt;
                                                &lt;ItemsPresenter /&gt;
                                            &lt;/Expander.Content&gt;
                                        &lt;/Expander&gt;
                                    &lt;/ControlTemplate&gt;
                                &lt;/Setter.Value&gt;
                            &lt;/Setter&gt;
                        &lt;/Style&gt;
                    &lt;/GroupStyle.ContainerStyle&gt;
                &lt;/GroupStyle&gt;
            &lt;/DataGrid.GroupStyle&gt;
</pre><p><strong>Converters:</strong></p><pre>    public class SumConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (value == DependencyProperty.UnsetValue) return DependencyProperty.UnsetValue;
            if (null == parameter) return null;
            string propertyName = (string)parameter;
            if (!(value is ReadOnlyObservableCollection&lt;object&gt;)) return null;
            ReadOnlyObservableCollection&lt;object&gt; collection = (ReadOnlyObservableCollection&lt;object&gt;)value;
            decimal sum = 0;
            foreach (object o in collection)
            {
                sum += (decimal)o.GetType().GetProperty(propertyName).GetValue(o);
            }
            return sum;
        }

        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }

    public class SumMulConverter : IMultiValueConverter
    {
        public object Convert(object[] values, Type targetType, object parameter, CultureInfo culture)
        {
            if (null == parameter) return null;
            if (!(parameter is string)) return null;
            string propertyName = (string)parameter;

            if (values == DependencyProperty.UnsetValue) return DependencyProperty.UnsetValue;
            if (values == null) return null;
            if (values.Length &lt; 2) return null;
            if (!(values[0] is ReadOnlyObservableCollection&lt;object&gt;)) return null;
            ReadOnlyObservableCollection&lt;object&gt; collection = (ReadOnlyObservableCollection&lt;object&gt;)values[0];
            if (!(values[1] is int)) return null;
            Debug.Print($&quot;ItemCount={(int)values[1]}; Collection Count = {collection.Count}&quot;);
            decimal sum = 0;
            foreach (object o in collection)
            {
                sum += (decimal)o.GetType().GetProperty(propertyName).GetValue(o);
            }
            return sum; //.ToString(&quot;N2&quot;, CultureInfo.CurrentCulture);
        }

        public object[] ConvertBack(object value, Type[] targetTypes, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }<br></pre><p>  </p>
</pre>

---
#### Feedback Bot on 3/23/2020, 08:51 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Pavel Karasev on 3/25/2020, 05:22 AM: 

<p>Got an advice that when an item is added to Items, the collection triggers CollectionChanged event (not PropertyChanged), so not raising PropertyChanged maybe be a correct behavior. Still,  the situation with the Multi Converter receiving Items.Count = ItemCount - 1 seems to be incorrect...</p><p>Also, would appreciate an advice, how to make use of CollectionChanged in the &lt;GroupStyle&gt;, to ensure correct recalculation of subtotals on adding items in the existing groups. Thank you!</p>

#### Feedback Bot on 5/8/2020, 03:17 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by SamBent** [comment]
When you add an item. the collection CollectionViewGroup.Items raises a CollectionChanged event.  The CollectionViewGroup does not raise a PropertyChanged event, because its Items property didn't change - it's still the same collection object.  In general, if a property's value is itself a compound object with its own properties or sub-structure, changing a sub-property or sub-structure does not raise a PropertyChanged for the parent property.  You wouldn't want it to;  in your case that would cause rebuilding the UI for the entire group every time you add an item.

ItemCount measures the number of leaf descendants of the group.  Items.Count measures the number of immediate descendants (i.e. children).  There's no reason these should be equal - they count different things.  They're equal if all the group's children are leaves (no subgroups), but there's one unavoidable problem when you add/remove an item.  Items.Count changes when the item is added to the actual collection, ItemCount changes when we assign a new value to an internal property.  These cannot happen simultaneously - one of them comes first, which means there will be a brief time when the values are out of sync.  WPF changes ItemCount first, because the other order caused even worse problems.  

To solve your summation scenario, try binding to Items.Count instead of ItemCount.  The collection should raise PropertyChanged("Count") when you add/remove an item, triggering your converter at a time when the new item is available.
