### ISSUE TITLE
NETFX Regression: No longer can set name property to MarkupExtension in certain places

### ISSUE THREAD

**Issue by reflectronic** [dotnet/wpf#378]
* .NET Core Version 3.0.100-preview-010184
* Windows version: Server 2019, 17763.253
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

I am porting a WPF control library to .NET Core. In this library, they define many `const` fields that they use in attributes, element names, etc. For example:
```cs
[TemplateVisualState(Name = MyState, GroupName = MyStateGroup)]
class MyControl : Control
{
   public const String MyState = "MyState";
   public const String MyStateGroup = "MyStateGroup";
}
```
```xml
<!-- somewhere inside of a control template -->
<VisualStateGroup Name="{x:Static local:MyControl.MyState}">...</VisualStateGroup>
```

The .NET Framework tooling works fine here. However, in .NET Core, trying to compile code using this pattern produces this error:

> error MC3079: MarkupExtensions are not allowed for Uid or Name property values, so '{x:Static local:MyControl.MyState}' is not valid.

[Here's a small repro that demonstrates this issue.](https://github.com/dotnet/wpf/files/2897472/Repro.zip) The application will compile fine if you set the target framework to `net472`, but it will not compile with the above error if you set it to `netcoreapp3.0`.

Note that this pattern doesn't work in all cases; I don't know the specifics on where it does and doesn't work, but I think it only works for files evaluated at runtime.

**Comment by stevenbrix** [comment]
Thanks for filing this issue @reflectronic! Does this work as expected in .NET 4.8 (compile and run), or just compile?

**Comment by reflectronic** [comment]
Yes, code that makes use of this pattern compiles. Using a real-world example, [here is some XAML that makes use of this](https://github.com/Wouterdek/NodeNetwork/blob/master/NodeNetwork/Themes/PortView.xaml#L20) and [here is the `const` member it references.](https://github.com/Wouterdek/NodeNetwork/blob/feature/serialization/NodeNetwork/Views/PortView.cs#L44) This project currently targets .NET Framework 4.7.

**Comment by ryalanms** [comment]
Thank you, @reflectronic.  This is a lifetime issue with the ReflectionOnlyLoad replacement, MetadataLoadContext.

**Comment by ryalanms** [comment]
BamlMapTable's KnownAssemblyInfoRecord needs to be reinitialized each time ReflectionHelper is created.

**Comment by reflectronic** [comment]
Thanks for your work!
