### ISSUE TITLE
Build of the WPF Custom Control Library is failed in .net 5 if "µ" character used in path and project

### ISSUE THREAD

**Issue by AndrDm** [dotnet/wpf#3801]
.NET Version: 5.0.100, released 10th Nov 2020 / Windows 10 ver 2004 (Build 19041.572), German.

Just migrated one of my pet project from Core 3.1 to 5.0 and got weird and funny problem.
If you have "µ" character in the name of the path and have WPF Custom Control Library, then attempt to build from command line (with "dotnet build" command) failed with error MC3050.

Steps to reproduce:

1. Create a folder with "µ" character, for example, "µmControl"
2. From this folder execute the command: dotnet new wpfcustomcontrollib
3. Try to build just created project from command line: dotnet build

Result: "\Generic.xaml(5,12): error MC3050: Der Typ "local:CustomControl1"wurde nicht gefunden." (means "Type was not found").

I checked other "non-ascii" characters like üöä - everything works as expected, without any problem. Not sure which other chars except "µ" can cause this.
Also if I open "failed" project with "µ" char in Visual Studio (16.8.0), then I can build without problem as well. The only dotnet build command failed. Previosly in .net Core 3.1 is was OK, only 5.0 failed.
It doesn't matter if the WPF Custom Control with "µ" char created in Visual Studio or from command line. Build in VisualStudio successful, but from command line failed.

If you need additional info - please let me know.
With best regards,
Andrey.

**Comment by AndrDm** [comment]
Seems to be working properly in 5.0.101. Closed for now, thank you!

**Comment by PieterDepamelaere** [comment]
For my interest: How did you manage to migrate/create a WPF Custom Control Library in a .NET 5 environment.
I've been trying to migrate a .NET 4.8 WPF custom control library to NET5

**Comment by PieterDepamelaere** [comment]
> For my interest: How did you manage to migrate/create a WPF Custom Control Library in a .NET 5 environment.
> I've been trying to migrate a .NET 4.8 WPF custom control library to NET5

(-> Nvm, there happens to exist a "WPF Custom Control Library" - fit for .Net Core WPF Applications, hence including .NET 5.
But I happened to overlook it.)
