### ISSUE TITLE
Editing a copy of the default ScrollViewer template does not work

### ISSUE THREAD

**Issue by mikernet** [dotnet/wpf#3862]
* .NET Version: 5.0 release
* Windows version: 2004 build 19041.630
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
 
 **Problem description:**
 
For some reason, the default `ScrollViewer` template does not allow you to right-click and "Edit a Copy" on .NET Core / .NET 5. This works fine on .NET 4.8 WPF.

**Comment by ryalanms** [comment]
Thanks for the report, @mikernet.  This is handled by Visual Studio, not WPF.

**Comment by mikernet** [comment]
Can you move the issue or should I repost it elsewhere?
