### ISSUE TITLE
Use C# for PresentationCore module initializer instead of the existing IL injection

### ISSUE THREAD

**Issue by LakshanF** [dotnet/wpf#3885]
Trimming a default WPF application causes issues for the linker and I'm following up on those. One issue is related with the use of IL injection for the module cctor since earlier version of the C# compiler didn't have this support. 

My colleague, @vitek-karas, has a change that addresses [this](https://github.com/dotnet/wpf/compare/master...vitek-karas:UseModuleInit) that can be leveraged for this purpose. The existing IL injection at [Arcade](https://github.com/dotnet/wpf/tree/master/eng/WpfArcadeSdk/tools/InjectModuleInitializer) might require some cleanup which could be done better by a WPF domain expert.

The other [issues](https://github.com/dotnet/sdk/issues/14261) related to WPF trimming are changes that we need to make on the linker side, at least to peel away to uncover any other deeper issues related to WPF heavy use of C++/CLI assemblies.

**Comment by madewokherd** [comment]
FWIW, in Wine Mono I was able to replace DirectWriteForwarder with a C# assembly, except for the custom loader interfaces where I encountered GC issues and moved the implementation to a native dll as a light wrapper around a managed callback.

**Comment by ryalanms** [comment]
Thanks, @LakshanF.
