### ISSUE TITLE
Large ListBox updated content not showing

### ISSUE THREAD

**Issue by ZegerDK** [dotnet/wpf#3894]
The issue below is in .NET core 3.1 .
I have a listbox where every item is a custom control which has a grid with 3 columns, each containing another custom control that contains a datagrid.
The reason I use a listbox is because each item in the listbox is a price group and depending on the selected price group, some things need to be done.
The listbox is longer than my application screen.
I have a function giving a price a red background if something is wrong. This function checks every price in every price group and in every datagrid simultaneously as they could be related.
I noticed that when running this function, the non visible listbox items didn't update the price background.
After some checking, I noticed that if I first scroll through the listbox all the way down and then run the function, every datagrid shows the updated value, while if I run the function when I haven't scrolled through the list, only the visible seem to be updated.
As my datagrids are filled with observable collections, they update automatically after any changes, but it doesn't seem to show in every situation, which is off course not the idea.

Any idea what can be the cause of this and how I can remedy this issue?

Thanks in advance,

Zeger

**Comment by miloush** [comment]
By default the ListBox panel is virtualized, so it doesn't create the controls until they are needed on screen.

If you have just a few items, you can disable the virtualization, for example by setting VirtualizingPanel.IsVirtualizing="False" on the ListBox.

Otherwise create a view model and have the background colour databound from it.

**Comment by ZegerDK** [comment]
Dear Jan,
Thank you very much for your reply. Switching off the virtualization did the trick.
I was unaware of the virtual behavior of the ListBox. For future reference, where is the best place to check these things myself?

**Comment by miloush** [comment]
That is a good question, there is a link from the `ListBox` documentation page to the virtualization overview: https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/optimizing-performance-controls

However, how to know that you need to look for it, I guess that comes with experience... there is a couple of articles about items controls in general at http://drwpf.com/blog/itemscontrol-a-to-z/ that you might find useful.
