### ISSUE TITLE
Dotnet publish self contained wpf application cannot be started

### ISSUE THREAD

**Issue by glent1** [dotnet/wpf#390]
Microsoft.NETCore.App 3.0.0-preview-27401-3
Windows 10 1803 17134.590
Not applicable to 4.8 - core specific

Running 
dotnet publish -f netcoreapp3.0 -r win10-x64 --selfcontained true -c release -o c:\temp\pub
 results in an exe that when run fails with the message

Error: 
An assembly specified in the application dependencies manifest (xxx.deps.json) has already been found but with a different file extension.
package: 
'runtimepack.runtime.win-x64.Microsoft.WindowsDesktop.App',
version '3.0.0-preview-27331-15'
path '/.System.Design.xml'
previously found assembly 'c:\temp\pub\System.Design.dll'

 To reproduce ...

cd c:\temp
mkdir WPF
cd WPF
dotnet new WPF
mkdir c:\temp\WPFPUB
dotnet publish -f netcoreapp3.0 -r win10-x64 --self-contained true -c release -o c:\temp\WPFPUB
start c:\temp\WPFPUB\WPF.exe

![image](https://user-images.githubusercontent.com/2174807/53567416-20096600-3b9a-11e9-8de7-6d7713fef8ef.png)

**Comment by glent1** [comment]
I just notice that if you hand edit the deps.json file removing all of the .xml entries, the application starts fine.

**Comment by Symbai** [comment]
I had the same problem and fixed it by uninstalling ALL .NET Core (sdk and runtime) versions and then install latest SDK and runtime again. Then publish again. My guess is there was a problem between different sdk / runtime versions on the computer where you publish the app.

**Comment by glent1** [comment]
Yep, that fixes it.  Thanks very much.
