### ISSUE TITLE
Visual Studio 2019 installation

### ISSUE THREAD

**Issue by Chorming-Lung** [dotnet/wpf#3919]
I have VS 2019 preview installed a long time ago.
Recently, I need to use the latest VS 2019.
I have downloaded the latest installer from Microsoft and run the installer. It put something in C:\Program Files (x86)\Microsoft Visual Studio\Installer and executed the installer inside. However, it tried to get the latest installer from web and re-run it again and some of the file it tried to access is locked by previous running installer. I am stuck. I tried to remove the preview version without luck because the uninstall will trigger the latest installer download and it is locked again.

Just want to run the installer without checking the web to get the latest installer. Is there is an option to disable getting the latest installer from web?

**Comment by thomasclaudiushuber** [comment]
@Chorming-Lung Not as far as I know. But you could disable your internet connection, restart your machine, and then use the installer.

**Comment by Chorming-Lung** [comment]
Unfortunately, I am using through remote desktop. I will need to get the office to try. My thinking is that it may not work since the installer is small program to get information from the web. It will not run that is what I think. Anyway, I will give it a try. Thanks for your suggestion.

**Comment by Rand-Random** [comment]
Your issue seems to have nothing to do with WPF, the github page you are currently in.
I would advise you to open an issue here https://developercommunity.visualstudio.com/

You can't report it online, you would need to report an issue through Visual Studio itself.
Since you are stuck with installing Visual Studio, you may have to use the "Visual Studio Installer" to report an issue.
![image](https://user-images.githubusercontent.com/9868626/103003324-dd640b00-4530-11eb-820b-6644024a40d1.png)

Or you could use https://stackoverflow.com.

**Comment by daisyTian0517** [comment]
You already have VS 2019 installed on your machine, so you can turn Visual Studio off and use `Visual Studio Installer` to operate then Visual Studio. You can use the `Visual Studio Installer wizard` to `Modify, Repair, Uninstall ... ` You can get it by search Visual Studio Installer` on search bar or get to `C:\Program Files (x86)\Microsoft Visual Studio\Installer\` to run `vs_installer.exe`.

**Comment by Chorming-Lung** [comment]
The problem is I have the VS 2019 Preview installed. When I try to perform Modify, Repair, Uninstall actions, it will first download the latest installer and the vicious cycle of installer started. It will download and run and found the preview was installed and think it needs to get the latest installer again and download and run second instance of installer and locked file was found by prior running installer.

Since this is not the right thread for installation issue. I will pursuit help from other location. Thanks for your help.
