### ISSUE TITLE
Intellisense is missing -> Intellisense Xml sources not found: IntellisenseXmlDir...

### ISSUE THREAD

**Issue by Symbai** [dotnet/wpf#3960]
I've following the instructions and I can build the project using `build.cmd` without a problem. My problem is that when I open the project and add for example a class that inherits from an existing class. I get no intellisense and the code is not checked for errors as well. I only see errors when I build the project.

VS shows a lot of these errors (but not errors in my code):

```
Error		Intellisense Xml sources not found: IntellisenseXmlDir=\bin\dotnet-api-docs_net5.0\0.0.0.3\_intellisense\net-5.0\	System.Windows.Controls.Ribbon-ref	
Error		Intellisense Xml sources not found: IntellisenseXmlDir=\bin\dotnet-api-docs_net5.0\0.0.0.3\_intellisense\net-5.0\	UIAutomationTypes-ref	
Error		Intellisense Xml sources not found: IntellisenseXmlDir=\bin\dotnet-api-docs_net5.0\0.0.0.3\_intellisense\net-5.0\	PresentationFramework.Aero-ref	
Error		ResolvedImplementationAssembly item must be specified to run API compat.	
Error		Intellisense Xml sources not found: IntellisenseXmlDir=\bin\dotnet-api-docs_net5.0\0.0.0.3\_intellisense\net-5.0\	PresentationFramework.Aero2-ref	
Error		ResolvedImplementationAssembly item must be specified to run API compat.	
Error		ResolvedImplementationAssembly item must be specified to run API compat.	
Error		Intellisense Xml sources not found: IntellisenseXmlDir=\bin\dotnet-api-docs_net5.0\0.0.0.3\_intellisense\net-5.0\	ReachFramework-ref	
Error		Intellisense Xml sources not found: IntellisenseXmlDir=\bin\dotnet-api-docs_net5.0\0.0.0.3\_intellisense\net-5.0\	WindowsFormsIntegration-ref	
Error		Intellisense Xml sources not found: IntellisenseXmlDir=\bin\dotnet-api-docs_net5.0\0.0.0.3\_intellisense\net-5.0\	System.Printing-ref	
Error		Intellisense Xml sources not found: IntellisenseXmlDir=\bin\dotnet-api-docs_net5.0\0.0.0.3\_intellisense\net-5.0\	PresentationFramework-ref	
Error		Intellisense Xml sources not found: IntellisenseXmlDir=\bin\dotnet-api-docs_net5.0\0.0.0.3\_intellisense\net-5.0\	PresentationFramework.Luna-ref	
and so on...
```	

When I double click on the errors, there is a comment saying:
```
<!-- 
        This blob lives in Azure storage at https://netcorenativeassets.blob.core.windows.net/resource-packages/external/windows/dotnet-api-docs_net5.0/
        Instructions for updating these artifacts are at https://github.com/dotnet/wpf/blob/master/docs/intellisense.md
      -->
```

However the first link requires me to login and the second link is invalid.

I'm using VS Community 2019 16.8.3

**Comment by daisyTian0517** [comment]
What version did the existing project target? Did it a .Net 5 project? Did you add the class which inherits from an existing class in the existing project? Please show more details to reproduce the error for more accurate analysis.

**Comment by ryalanms** [comment]
Thank you for the report, @Symbai.  Do you have a minimal repro project you could share?  Thanks.

**Comment by Symbai** [comment]
I've downloaded this project and opened it, added a class. Typed anything and that's it. The project targets whatever this WPF project targets. It doesn't matter if I inherit a class or just add an empty class and type something into it which should get this red cringles underneath and an error in the VS error window, but both doesn't happen.

For example:
`int a = "123";`

it's not marked as error.

Instead I get the errors above, which won't prevent the WPF project to compile. It looks like the intellisense data is probably something Microsoft Internal which I don't have access to and thus VS cannot use it.

**Comment by daisyTian0517** [comment]
If you use Visual studio 2019, you can go to `Tools/Options/General/Dispaly` to check the **Show error squiggles** on to show the red underline wavy.like below picture show:
![capture](https://user-images.githubusercontent.com/40193800/105141120-a1be6000-5b33-11eb-90e2-5a2701470b62.PNG)
