### ISSUE TITLE
Build error 'TypesMustExist' after adding a new class

### ISSUE THREAD

**Issue by Symbai** [dotnet/wpf#3961]
I can successfully build the default project but when I add a new class, I receive the following error I don't know how to fix it:

```
 error : TypesMustExist : Type 'Path_to_my_class' does not exist in the implementation but it does exist in the contract
. [...\src\PresentationFramework\PresentationFramework.csproj]
...\eng\WpfArcadeSdk\tools\ApiCompat.targets(239,5): error : ApiCompat failed for '...\artifacts\bin\PresentationFramework\Debug\netcoreapp5.0\PresentationFramework.dll' [...\src\Microsoft.DotNet.Wpf\src\PresentationFramework\PresentationFramework.csproj]
```

**Comment by ryalanms** [comment]
Hi @Symbai 

This was added to the build to protect against inadvertent API changes.  

When adding public API changes to WPF, the API compat checking will fail until the baseline files are regenerated. 

To re-generate the API compat files: 

> A developer can re-baseline the entirety of the product by setting the property BaselineAllAPICompatError to true during a build.

> build /p:BaselineAllAPICompatError=true

> https://github.com/dotnet/wpf/blob/master/Documentation/api-compat.md

Alternatively, API compat checking can be turned off in ApiCompat.targets: 

> https://github.com/dotnet/wpf/blob/master/eng/WpfArcadeSdk/tools/ApiCompat.targets

Let me know if this helps.  Thanks.

**Comment by lindexi** [comment]
> 
> 
> Hi @Symbai
> 
> This was added to the build to protect against inadvertent API changes.
> 
> When adding public API changes to WPF, the API compat checking will fail until the baseline files are regenerated.
> 
> To re-generate the API compat files:
> 
> > A developer can re-baseline the entirety of the product by setting the property BaselineAllAPICompatError to true during a build.
> 
> > build /p:BaselineAllAPICompatError=true
> 
> > https://github.com/dotnet/wpf/blob/master/Documentation/api-compat.md
> 
> Alternatively, API compat checking can be turned off in ApiCompat.targets:
> 
> > https://github.com/dotnet/wpf/blob/master/eng/WpfArcadeSdk/tools/ApiCompat.targets
> 
> Let me know if this helps. Thanks.

Thank you.  This solution is very useful

My previous solution was to delete the 239 lines of code in ApiCompat.targets

https://github.com/dotnet/wpf/blob/d5673edfbd274e4081d46d377ca4c0e6d3028ae2/eng/WpfArcadeSdk/tools/ApiCompat.targets#L239

**Comment by Symbai** [comment]
Thanks, this fixed my problem.
