### ISSUE TITLE
WPF project build breaks because Roslyn Source Generators do not run in WPF inner-build

### ISSUE THREAD

**Issue by AArnott** [dotnet/wpf#3963]
1. Create a new WPF project.
2. Add a PackageReference to any source generator.
3. Add code to `MainWindow.xaml.cs` that depends on the generated code.
4. Build

**Expected**

No build break

**Actual**

Build break.

In fact investigating the binary build log reveals that while the outer build's invocation of the `Csc` task provides the "analyzers" that are actually source generators:
![image](https://user-images.githubusercontent.com/3548/104056423-b30b8200-51ad-11eb-816a-57468bcf95cd.png)

The inner build invocation of `Csc` does not:
![image](https://user-images.githubusercontent.com/3548/104056466-c28acb00-51ad-11eb-8ed2-5324de6cec43.png)

**Comment by ryalanms** [comment]
Thanks for reporting this, @AArnott. 

Source generator support was added with https://github.com/dotnet/wpf/pull/3846.  

This is an opt-in feature.  To use it, set the property `IncludePackageReferencesDuringMarkupCompilation` to `true`.

I'll follow-up when I find out which version of the .NET 5.0.xx SDK has the fix.

**Comment by vatsan-madhavan** [comment]
Would you consider making this on by default in 6.0 SDK's ?

**Comment by ryalanms** [comment]
@AArnott:  I believe you validated with 5.0.102-servicing.20614.17.  Can this be closed?  Thanks.

**Comment by ryalanms** [comment]
Thanks.

**Comment by manfred-brands** [comment]
It took me a while to find this issue, only after finding the comment in Microsoft.WinFX.targets.
My issue was not source generators, but a DiagnosticSuppressor from an Roslyn Analyzer nuget package.
