### ISSUE TITLE
WPF source generator support should be on by default for .NET 6.0

### ISSUE THREAD

**Issue by ryalanms** [dotnet/wpf#3974]
Source generator support was added with #3846.  This is an opt-in feature. To use it, users must set the property IncludePackageReferencesDuringMarkupCompilation to true. 

Make source generator support on by default for .NET 6.0.

**Comment by ryalanms** [comment]
The Arcade workaround for WPF must be removed from the Arcade SDK when this is turned on.

**Comment by clairernovotny** [comment]
There's a related PR to track enabling it by default in the .NET SDK 5.0.200 here: It's also tracked here for the .NET SDK for 5.0.200: dotnet/sdk#15395

**Comment by ryalanms** [comment]
https://github.com/dotnet/wpf/pull/4089
