### ISSUE TITLE
Performance Issue When Application Activated

### ISSUE THREAD

**Issue by connordear** [dotnet/wpf#3982]
I am working on a WPF application that displays a grid of many images with scrolling/expanding animations that display a video when the user hovers the image.

When this application is run on an Intel CPU + NVidia GPU machine, the animations and video playback are very smooth at a maintained 60fps.

When run on a high-end AMD CPU + ATI GPU, the animations and video playback are noticeably laggy and the frames drop to ~30fps during animations/video playback. However - on these machines, the performance is  if the user deactivates the application (e.g. alt-tabbing to another application) and then scrolls/hovers my program behind it to trigger the animations there are no frames dropped. Videos of a side-by-side comparison are linked at the bottom.

The Render Tier on both computers is 2, and enabling software-only rendering does not help address this.

When running a diagnostics session and performing the same animations on both Activated/Deactivated, the drop in frames spike is clearly seen [Diagnostics: Red = Activated, Green = Deactivated](https://user-images.githubusercontent.com/18018265/104250747-7d73cc80-542b-11eb-8998-37ab4f91afc6.png). The UI thread does not appear to be exceeding 60%-70% at it's peaks, 

Does anyone know why there would be a performance difference when my application becomes activated?  The desired behaviour is for the animations/playback to always be smooth, as it is when the application is deactivated. It also does not appear to be very close to maxing out the UI thread either, and as far as I know, I have not written any specific tasks that only run if the application is activated.

[Video of the scrolling comparison][1]

[Video of the MediaPlayer playback comparison][2]

  [1]: https://youtu.be/nem7ymBUkds
  [2]: https://youtu.be/7ITI4Ik18OU

**Comment by ClosetBugSlayer** [comment]
I have a bad suspicion that explorer.exe is running a low level mouse hook badly, and that it is also running general-purpose window environment code which really should be put into DWM or win32k. A lot of seemingly unrelated things mess up when explorer messes up.

**Comment by connordear** [comment]
I think this issue is related to #3626 since I was able to restore performance to the application by not running the application full screen mode (`WindowState="Maximized" WindowStyle="None"`). 

I was able to restore performance in fullscreen mode by modifying the WindowChrome WindowThickness:

    <Style TargetType="{x:Type views:ApplicationView}" >
        <Setter Property="WindowChrome.WindowChrome">
            <Setter.Value>
                <WindowChrome
                    ResizeBorderThickness="6"
                    CaptionHeight="10"
                    CornerRadius="0"
                    GlassFrameThickness="1"/>
            </Setter.Value>
        </Setter>
        <Style.Triggers>
            <Trigger Property="WindowState" Value="Maximized">
                <Setter Property="BorderThickness" Value="6" />
            </Trigger>
        </Style.Triggers>
    </Style>

This link described another rendering problem, and related it to the ActualHeight/ActualWidth reported properties being larger than the set resolution.

I'm wondering if these are performance issues related to the application extending beyond the display and then causing issues with certain video drivers. Either way, it seems more related to the fullscreen/screen width issue than an activation so I will close this for further discussion in #3626.
