### ISSUE TITLE
[Question] How can I add a Decorator to some control with AttachedProperty?

### ISSUE THREAD

**Issue by PieroCastillo** [dotnet/wpf#4016]
Hi guys, I'm new with WPF, and I would want to know how can I add a decorator to some control with AttachedProperty,
like this:
```xml
<Button local:myDecorator.EnableOnThis="true"/>
```

**Comment by miloush** [comment]
You can find the documentation for attached properties here: https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/attached-properties-overview?view=netframeworkdesktop-4.8

Namely, your XAML example requires a class called `myDecorator` with `SetEnableOnThis` and `GetEnableOnThis` methods and an `EnableOnThisProperty` field registering the property.

**Comment by PieroCastillo** [comment]
> You can find the documentation for attached properties here: https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/attached-properties-overview?view=netframeworkdesktop-4.8
> 
> Namely, your XAML example requires a class called `myDecorator` with `SetEnableOnThis` and `GetEnableOnThis` methods and an `EnableOnThisProperty` field registering the property.

thx u
