### ISSUE TITLE
Cannot add reference to DLL project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#4057]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Cannot-add-reference-to-DLL-project/1254036?preview=true)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:15.9.20]
I have a WPF application targeting .Net 5 built using VS2019 Preview 16.8.0

I add a class library to the project. This class library will contain XAML loaded dynamically at runtime. The XAML will not compile because of a missing reference:
Microsoft.WindowsDesktop.App.WPF (this reference is automatically added to the EXE project but not to the DLL project).

Right-click Dependencies restricts which references can be added. It has "Add project reference", "Add COM reference", etc, but no "Add reference" like in previous versions of VS. See screenshot in attached UNTITLED. PNG file.

Workaround: hand-edit the . CSPROJ file (which I have to do to multiple DLL projects)

---
#### Feedback Bot on 11/18/2020, 01:46 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by daisyTian0517** [comment]
Did you add `Microsoft.WindowsDesktop.App.WPF` in the NuGet package manager? What is your setting for NuGet Package Manager? You can check it with step:Tools>NuGet Package Manager>NuGet Package Setting. For the .Net core app, you need to choose `Package Reference` for `Package Management`.

**Comment by singhashish-wpf** [comment]
Closing in absence of any activity or response from the author.
