### ISSUE TITLE
[.NET 6] [Source Compat Failure] Greenshot & ControlzEx apps doesn't build with .net6.0 SDK

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/wpf#4061]
**Application Name:**  Greenshot
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 6.0.100-preview.1.21071.10
**Project Location:** https://github.com/greenshot/greenshot

**Verify Scenarios:**
1). Windows 10 RS5 X64 + .NET Core SDK build 6.0.100-preview.1.21071.10: Fail
2). Windows 10 RS5 X64 + .NET Core SDK build 5.0.102: Pass

**Repro steps**
1) Source Code check at [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1268782](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1268782)
2) go to src\Greenshot
3) dotnet build

**Expected Result:**
Build succeeded

**Actual Result:**
```
C:\Users\valtunc\Desktop\AppSources\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\ExportNotificationView.g.cs(49,18): error CS1504: Source file '..\..\..\Views\ExportNotificationView.xaml' could not be opened -- Could not find file. [C:\Users\valtunc\Desktop\AppSources\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]

C:\Users\valtunc\Desktop\AppSources\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\ExportNotificationView.g.cs(70,21): error CS1504: Source file '..\..\..\Views\ExportNotificationView.xaml' could not be opened -- Could not find file. [C:\Users\valtunc\Desktop\AppSources\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\Users\valtunc\Desktop\AppSources\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\FileConfigPartView.g.cs(45,18): error CS1504: Source file '..\..\..\Views\FileConfigPartView.xaml' could not be opened -- Could not find file. [C:\Users\valtunc\Desktop\AppSources\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\Users\valtunc\Desktop\AppSources\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\FileConfigPartView.g.cs(66,21): error CS1504: Source file '..\..\..\Views\FileConfigPartView.xaml' could not be opened -- Could not find file. [C:\Users\valtunc\Desktop\AppSources\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\Users\valtunc\Desktop\AppSources\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\Views\UploadView.g.cs(58,21): error CS1504: Source file '..\..\..\Views\UploadView.xaml' could not be opened -- Could not find file. [C:\Users\valtunc\Desktop\AppSources\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
    95 Warning(s)
    5 Error(s)
```

@dotnet-actwx-bot  @dotnet/compat

**Comment by jiangzeng01** [comment]
@ryalanms This issue was fixed for .NET 5 and now regressed in .NET 6. 
[https://github.com/dotnet/wpf/issues/3628](https://github.com/dotnet/wpf/issues/3628)

Are you going to revert the change or fix the issue for .NET 6?

**Comment by ryalanms** [comment]
Thanks, @jiangzeng01.  This should be fixed with https://github.com/dotnet/wpf/pull/4038.

**Comment by ryalanms** [comment]
Can you test this with the most recent version of the SDK?  Thanks.

**Comment by jiangzeng01** [comment]
@ryalanms  We will try with last version and let you know

**Comment by dsplaisted** [comment]
@ryalanms This doesn't look like it is at all related to the Directory.Build.targets breaking change (see https://github.com/dotnet/sdk/pull/15449).  The greenshot repo doesn't even have a Directory.Build.targets file.

Was there another change you thought might have fixed this?

**Comment by ryalanms** [comment]
@dsplaisted:  Yes, this is unrelated to Directory.Build.targets and is fixed in recent builds.  I confirmed with build 6.0.100-preview.1.21073.4.

**Comment by jiangzeng01** [comment]
Close this issue as verified.
