### ISSUE TITLE
IncludePackageReferencesDuringMarkupCompilation has no effect in VB projects

### ISSUE THREAD

**Issue by Nukepayload2** [dotnet/wpf#4073]
* .NET Core Version:
- Version:   5.0.200-preview.20614.14
- Commit:    863605c8c3
- Visual Studio 16.9 preview 3
* Windows version: 10.0.18363
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No. This is a bug of a new feature of .NET 5 .
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No. This bug is reproducible with .NET CLI.

 **Problem description:**
The generated code of VB source generators in WPF projects can't be accessed directly, even if I add `<IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>` to `<PropertyGroup>` . The generated code can be used with reflection. So, I guess `MainWindow.xaml.vb` was built before running VB code generators.

 **Actual behavior:** 
The source files generated by VB source generators can be used directly.

 **Expected behavior:**
The source files generated by VB source generators can **NOT** be used directly. They can only be used by using reflection.

 **Minimal repro:**
- Clone https://github.com/Nukepayload2/MyWpfExtensionGenerator
- Open `Nukepayload2.SourceGenerators.MyWpfExtension.sln` with Visual Studio 16.9 preview 3
- Build project `Nukepayload2.SourceGenerators.MyWpfExtension`
- Reload the solution
- In the `SampleNet5WpfAndWinforms` project, open `MainWindow.xaml.vb`. You will not see any build errors.
- Build the `SampleNet5WpfAndWinforms` project with Visual Studio or .NET CLI. You will see build errors in the output window or the console window.

**Comment by ryalanms** [comment]
Thank you for the report, @Nukepayload2.

**Comment by Nukepayload2** [comment]
This problem seems to have been fixed in Visual Studio 2019 16.9.0 and .NET SDK 5.0.200 .
![image](https://user-images.githubusercontent.com/10798596/110197497-d6d60600-7e86-11eb-9e73-e4408826cdc1.png)
