### ISSUE TITLE
[.NET 6] [Source Compat Failure] ControlzEx app doesn't build with "Possible null reference" when retarget 6.0

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/wpf#4079]
**Application Name:**  ControlzEx (DiscordChatExporter failed with similar error code CS8601)
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 6.0.100-preview.1.21071.10

**Verify Scenarios:**
1). Windows 10 RS5 X64 + .NET Core SDK build 6.0.100-preview.1.21075.3: Fail
2). Windows 10 RS5 X64 + .NET Core SDK build 5.0.102: Pass

**Repro steps**
Source code is targeting netcoreapp3.1 and net6.0-windows, global.json set to 6.0.100-preview.1.21075.3
1) Source Code at [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1269988](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1269988)
2) Make sure target 6.0
3) goto src\ControlzEx
4) dotnet build

**Expected Result:**
Build succeeded

**Actual Result:**
```
C:\Users\valtunc\Desktop\AppSources\ControlzEx\src\ControlzEx\Theming\ThemeManager.cs(80,58): error CS8622: Nullability of reference types in type of parameter 'sender' of 'void ThemeManager.ThemesInternalCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)' doesn't match the target delegate 'NotifyCollectionChangedEventHandler' (possibly because of nullability attributes). [C:\Users\valtunc\Desktop\AppSources\ControlzEx\src\ControlzEx\ControlzEx_z4umz3jg_wpftmp.csproj]
C:\Users\valtunc\Desktop\AppSources\ControlzEx\src\ControlzEx\Theming\ThemeManager.cs(1235,59): error CS8622: Nullability of reference types in type of parameter 'sender' of 'void ThemeManager.HandleStaticPropertyChanged(object sender, PropertyChangedEventArgs e)' doesn't match the target delegate 'PropertyChangedEventHandler' (possibly because of nullability attributes). [C:\Users\valtunc\Desktop\AppSources\ControlzEx\src\ControlzEx\ControlzEx_z4umz3jg_wpftmp.csproj]
C:\Users\valtunc\Desktop\AppSources\ControlzEx\src\ControlzEx\Theming\ThemeManager.cs(1240,63): error CS8622: Nullability of reference types in type of parameter 'sender' of 'void ThemeManager.HandleStaticPropertyChanged(object sender, PropertyChangedEventArgs e)' doesn't match the target delegate 'PropertyChangedEventHandler' (possibly because of nullability attributes). [C:\Users\valtunc\Desktop\AppSources\ControlzEx\src\ControlzEx\ControlzEx_z4umz3jg_wpftmp.csproj]
C:\Users\valtunc\Desktop\AppSources\ControlzEx\src\ControlzEx\Theming\ThemeGenerator.cs(25,20): error CS8603: Possible null reference return. [C:\Users\valtunc\Desktop\AppSources\ControlzEx\src\ControlzEx\ControlzEx_z4umz3jg_wpftmp.csproj]
```

**Results for DiscordChatExporter app:**
```
C:\Users\valtunc\Desktop\AppSources\DiscordChatExporter\DiscordChatExporter.Gui\ViewModels\Framework\DialogScreen.cs(13,44): error CS8601: Possible null reference assignment. [C:\Users\valtunc\Desktop\AppSources\DiscordChatExporter\DiscordChatExporter.Gui\DiscordChatExporter.Gui_qfzufqja_wpftmp.csproj]
```

@dotnet-actwx-bot  @dotnet/compat

**Comment by ryalanms** [comment]
Thanks, @jiangzeng01.  Is there an alternative location for the source code?  I can't access the link in the devdiv work item.

**Comment by jiangzeng01** [comment]
> Thanks, @jiangzeng01. Is there an alternative location for the source code? I can't access the link in the devdiv work item.

Just update here: confirmed offline with Ryland, he can visit the path now.

**Comment by ryalanms** [comment]
These preprocessor directives in the test application need to updated for .NET 6.0.  The nullable object isn't being included in the method signature.   Changing them to NET6_0 allowed the application to compile. 

```cs
#if NET5_0
        private void ThemesInternalCollectionChanged(object? sender, NotifyCollectionChangedEventArgs e)
#else
        private void ThemesInternalCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
#endif
```

```
modified:   Theming/ThemeGenerator.cs
modified:   Theming/ThemeManager.cs
```

**Comment by jiangzeng01** [comment]
Thanks @ryalanms ! Should we close this ticket as App issue?

**Comment by batzen** [comment]
Will fix this in ControlzEx. Would be nice if you could create an issue there the next time you discover something like this. 😉

**Comment by jiangzeng01** [comment]
> Will fix this in ControlzEx. Would be nice if you could create an issue there the next time you discover something like this. 😉

Thanks, we will check updates from app source.

**Comment by batzen** [comment]
@jiangzeng01 Code in ControlzEx should be future proof now.

**Comment by jiangzeng01** [comment]
> @jiangzeng01 Code in ControlzEx should be future proof now.

Thanks a lot for fixing, we will get latest code.

**Comment by jiangzeng01** [comment]
@batzen @ryalanms The app works fine now, thanks!

**Comment by jiangzeng01** [comment]
Close ticket as "External" (App owner has fixed the app)
