### ISSUE TITLE
.NET 5 fails to create a working executable when using same code and publish settings as .NET Core 3.1 which works.

### ISSUE THREAD

**Issue by Noemata** [dotnet/wpf#4113]
* .NET Core Version: .NET Core 3.1 compared to .NET 5
* Windows version: 10 Build 19042.768
* Does the bug reproduce also in WPF for .NET Framework 4.8?: n/a
 
 **Problem description:**
When using same code and publish settings to create a self contained binary .NET Core 3.1 creates a working executable, .NET 5 does not.
 
 **Actual behavior:**
With exactly the same code and settings a .NET 5 executable fails to run (terminates early on load) as compared to the equivalent for .NET Core 3.1 which works correctly.
 
 **Expected behavior:**
Same behavior for .NET 5 and .NET Core 3.1
 
 **Minimal repro:**
Working (.NET Core 3.1): https://github.com/Noemata/AppxInstaller.Core
Failing (.NET 5): https://github.com/Noemata/AppxInstaller

**Comment by ryalanms** [comment]
Hi @Noemata.  Is this a separate issue from the WinRT failures?  If so, I will take a look.  Thanks.

**Comment by Noemata** [comment]
@ryalanms , yes, this is separate.  The two projects should both run when built as a self contained executable.  The .NET Core 3.1 variant works exactly as I expected.  Quite well in fact.  The .NET 5 project crashes during it's load process.  Given that one works, I didn't want to waste the time trying to figure out where .NET 5 fails since it looks like a tooling issue.

I wasn't able to generate a working self contained executable with either .NET Core 3.1 or .NET 5 when I used the "Trim" feature for creating a self contained executable.  Both crashed during load.

I was hoping to use .NET 5 because it has a "true" self contained executable, whereas .NET Core 3.1 expands itself out in a temp folder on load.

**Comment by ryalanms** [comment]
Trimming is not supported with WPF applications. There is now an error in .NET 6.0 when compiling to notify developers.
