### ISSUE TITLE
WPF's default branch will be renamed to 'main' from 'master'

### ISSUE THREAD

**Issue by ryalanms** [dotnet/wpf#4120]
Rename WPF's default branch to 'main' from 'master'.

**Comment by ClosetBugSlayer** [comment]
Because...?

**Comment by ryalanms** [comment]
.NET is renaming all repositories to 'main'.  The GitHub default for new repositories is also now 'main'.

**Comment by ClosetBugSlayer** [comment]
Why?

**Comment by lindexi** [comment]
@ClosetBugSlayer  See: https://github.com/github/renaming  https://www.zdnet.com/article/ibm-microsoft-staff-rally-to-remove-racially-insensitive-language-from-products/

**Comment by ryalanms** [comment]
The deadline for .NET repos is 3/19.

**Comment by ryalanms** [comment]
The default branch in the WPF repo will be renamed this week.  Thanks.
