### ISSUE TITLE
WPF .NET Core - Console Application doesn't open console

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#4138]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/WPF-NET-Core---Console-Application-does/1289479)._

---
<p>When I create a WPF .NET Framework app and change project output type from Window Application to Console Application, the console opens as expected when I run the program.</p> <p>When I create a WPF .NET Core app it and follow the same instructions as above, it doesn't open a console window anymore. It used to work before I reimage my computer and updated to the new Visual Studio version.</p> <p>Am I missing something? </p>

---
#### Feedback Bot on 12/16/2020, 07:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Jeroen WELLEN solved on 2/2/2021, 07:06 AM, 0 votes: 

<p>https://www.codeproject.com/Tips/68979/Attaching-a-Console-to-a-WinForms-application</p>

**Comment by reflectronic** [comment]
See also https://github.com/dotnet/sdk/issues/15554 https://github.com/dotnet/sdk/issues/13624 https://github.com/dotnet/sdk/issues/13331 https://github.com/dotnet/sdk/issues/14503. The default was intentionally changed, although the SDK should probably respect an explicit choice in the project file.

**Comment by daisyTian0517** [comment]
Please add `<DisableWinExeOutputInference>true</DisableWinExeOutputInference>` to your to .csproj as below:
```
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
   <DisableWinExeOutputInference>true</DisableWinExeOutputInference>
  </PropertyGroup>
```

**Comment by ryalanms** [comment]
Thanks. everyone.  @daisyTian0517, I believe your recommendation should solve the problem.
