### ISSUE TITLE
Consider shipping System.Xaml as a separate netstandard package

### ISSUE THREAD

**Issue by ryalanms** [dotnet/wpf#4140]
System.Xaml can be used independently of WPF, but consuming System.Xaml requires building with the Windows-specific `net6.0-windows` target framework.  Consider shipping System.Xaml as a separate netstandard package that can be built without the Windows-specific TFM.

**Comment by lindexi** [comment]
Yeah, and I made it as a separate package in https://github.com/lindexi/lindexi_gd/tree/master/System.Xaml

**Comment by lindexi** [comment]
@ryalanms Because System.Xaml depends on System.Windows.Extensions, I cannot change it to netstandard. See https://github.com/dotnet/wpf/pull/4252

**Comment by lindexi** [comment]
See https://github.com/dotnet/wpf/issues/3543

**Comment by AArnott** [comment]
Looks like a dupe of #46

**Comment by pchaurasia14** [comment]
Closing as duplicate.
