### ISSUE TITLE
Controls disappear on mose over

### ISSUE THREAD

**Issue by konradsikorski** [dotnet/wpf#4141]
* .NET Core Version: 5.0.200-preview.20601.7)
* Windows version: 19042.746
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio: No
 
 **Problem description:**
Controls on mouse hover disappear spontaneously.
 
 **Actual behavior:** 
In example below just run the app and quickly move mouse over  buttons and you will see that from time to time buttons will disappear.

![1](https://user-images.githubusercontent.com/5046330/107118557-0989e000-6882-11eb-8589-ecd9bf33d375.png)
![2](https://user-images.githubusercontent.com/5046330/107118559-0989e000-6882-11eb-921b-fd3ba18a15b4.png)
![3](https://user-images.githubusercontent.com/5046330/107118560-0a227680-6882-11eb-91a3-43883eedb4a9.png)
![4](https://user-images.githubusercontent.com/5046330/107118562-0a227680-6882-11eb-9ee8-a05e4f8a3372.png)
 
 **Expected behavior:**
Moving over buttons should only change default background color.
 
 **Minimal repro:**
1. Create new WPF (.NET) project in Visual Studio 2019
2. use following code as main window content
```
<StackPanel>
      <Button Content="1" />
      <Button Content="2" />
      <Button Content="3" />
      <Button Content="4" />
</StackPanel>
```
3. run app
4. move mouse over buttons

**Comment by lindexi** [comment]
It works well when I use your code. This is my demo code: https://github.com/lindexi/lindexi_gd/tree/81b45a7dc9eb4d7fd3fe167acea414f16de83cca/NearchecekeryalkeeLekegegal

**Comment by lindexi** [comment]
Could you clean your style?

```xml
  <Grid>
    <StackPanel Style="{x:Null}">
      <Button Style="{x:Null}" Content="1" />
      <Button Style="{x:Null}" Content="2" />
      <Button Style="{x:Null}" Content="3" />
      <Button Style="{x:Null}" Content="4" />
    </StackPanel>
  </Grid>
```

**Comment by konradsikorski** [comment]
I have tested your code and have the same behavior I have described. The same code ruining on .NET Framework works fine.

**Comment by daisyTian0517** [comment]
@konradsikorski
Did your error occur in .Net 3.0 or .Net 3.1 platform? Where did you download the `Net Core 5.0.200-preview.20601.7`? Could you give me the specific link to reproduce your error.

**Comment by weltkante** [comment]
This looks suspiciously like the other rendering issues caused by faulty third party software injecting itself into the .NET Core process (#707 has the main discussion I believe). You may want to check for programs like Nahimic or try to run the program on other machines.

**Comment by ryalanms** [comment]
As @weltkante says, in #707, there is a discussion about possible causes, typically applications with overlays.  Can you try disabling this service?  *NahimicOSD*

> I stopped the Nahimic Service, and suddenly WPF acted just fine.

**Comment by konradsikorski** [comment]
I have described the solution in #707

**Comment by LengVang** [comment]
Did you ever got this issue resolved?  I'm running into the same issue.  It just happen out of the blue.  I haven't done any update or library nor VS.

**Comment by weltkante** [comment]
did you read the linked issue mentioned in the previous responses? often such problems come from bad third party software

**Comment by LengVang** [comment]
Yes, I did see that.  I thought you may have some other remedies.  I will
try to look and disable other libraries I use.

Thanks.

**Comment by legistek** [comment]
FYI, I had a client report this issue and disabling Nahimic solved it.

I don't know if this is something WPF can control or not, but it is clearly a major problem. Asking clients to disable Windows services is not a long term solution. This issue is marked as "Needs More Information" - what more do you need from us? Is anyone on the WPF team assigned to this?

**Comment by weltkante** [comment]
@legistek this issue is closed, tags are probably just leftover. The cause of the problems are third party applications like Nahimic which intrude into other processes incorrectly. For Desktop Framework and some .NET Core versions they seem to have a "whitelist" to disable/adjust this intrusion, but apparently it doesn't work on all versions of .NET Core. Thats what I take from following the conversations in the issues.

When third party vendors break the operating systems rules there's little more that can be done than pushing back to them for fixing their code, or uninstalling/disabling it.

**Comment by legistek** [comment]
Oh I see yes I must have missed that in my haste. :). 

Unfortunately customers don't care who caused the issue when your application breaks though, and I have no way of reaching the people behind this utility. IF something could be done about it at the WPF level (and I have no idea if it can) that would be ideal.
