### ISSUE TITLE
Embedded font files are not displayed in WPF application

### ISSUE THREAD

**Issue by TMGMike** [dotnet/wpf#4161]
* .NET Core Version: 5.0.102
* Windows version: Windows 10 Pro 1909 (18363.1316)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

 **Problem description:**
 Custom fonts (tested with both OTF and TTF formats) are not displayed in WPF applications. I spoke with several developers, who advised creating a bug report. 
When the URI is valid, the designer preview window will successfully display the font in Visual Studio, but when running the application, the font falls back to a Microsoft default.
Build action is set to Embedded Resource, and has been tested with multiple other font files.

 **Actual behavior:**
 WPF application falls back to a Microsoft font, while VS designer preview shows the intended font: 
![image](https://user-images.githubusercontent.com/32360252/107451496-50582e00-6b3f-11eb-881b-aadbd72d30c8.png)
 
**Expected behavior:**
 The intended font should be displayed in the application. 

 **Minimal repro:**
I created a [minimal repository to test](https://github.com/TMGMike/WPF-Font-Test), and it occurs there too. This was tested in both .NET 5.0, and .NET Core 3.1, as well as .NET Framework 4.8, although in Framework 4.8, the designer also fails to show the intended font.

**Comment by daisyTian0517** [comment]
`Embedded Resource` - This file is embedded in the main project build output as a DLL or executable. It is typically used for resource files. The `Content` file is not compiled, but is included in the Content output group. You can change the Properties for `XeeRoughFont-Regular.otf` like below:
![capture](https://user-images.githubusercontent.com/40193800/107611292-a67fbb00-6c7e-11eb-99d4-ee598a6c344a.PNG)

**Comment by TMGMike** [comment]
> 
> 
> `Embedded Resource` - This file is embedded in the main project build output as a DLL or executable. It is typically used for resource files. The `Content` file is not compiled, but is included in the Content output group. You can change the Properties for `XeeRoughFont-Regular.otf` like below:
> ![capture](https://user-images.githubusercontent.com/40193800/107611292-a67fbb00-6c7e-11eb-99d4-ee598a6c344a.PNG)

Thanks. Although I believe Embedded Resource is what I'm looking for, I'd rather the font file was compiled into the EXE, rather than a standalone file in the app's directory, so I was hoping I could just point to it this way.

**Comment by ryalanms** [comment]
Thank you for the report, @TMGMike.  We will take a look.

**Comment by miloush** [comment]
Correct, _Resource_ build action compiles the resource into the exe file. It is the one you want to use for a user font in this case. Embedded resource is a different mechanism, WPF cannot refer to such resources using Uris I believe.

See https://docs.microsoft.com/en-us/visualstudio/ide/build-actions?view=vs-2019 and https://docs.microsoft.com/en-us/dotnet/desktop/wpf/app-development/wpf-application-resource-content-and-data-files?view=netframeworkdesktop-4.8

**Comment by TMGMike** [comment]
> 
> 
> Correct, _Resource_ build action compiles the resource into the exe file. It is the one you want to use for a user font in this case. Embedded resource is a different mechanism, WPF cannot refer to such resources using Uris I believe.
> 
> See https://docs.microsoft.com/en-us/visualstudio/ide/build-actions?view=vs-2019 and https://docs.microsoft.com/en-us/dotnet/desktop/wpf/app-development/wpf-application-resource-content-and-data-files?view=netframeworkdesktop-4.8

Gotcha, thank you for the clarification. I assumed, where it mentioned `.g.resources`, that it would be a separate file in the bin directory. In which case, Resource should do the job for me.

**Comment by rishavspn** [comment]
Correct, Resource build action compiles the resource into the exe file. It is the one you want to use for a user font in this case. Embedded resource is a different mechanism, WPF cannot refer to such resources using Uris I believe.

See https://docs.microsoft.com/en-us/visualstudio/ide/build-actions?view=vs-2019 and https://docs.microsoft.com/en-us/dotnet/desktop/wpf/app-development/wpf-application-resource-content-and-data-files?view=netframeworkdesktop-4.8
