### ISSUE TITLE
Dynamically Loading XAML has Different Whitespace Preservation Behavior from Compiled XAML

### ISSUE THREAD

**Issue by shartte** [dotnet/wpf#4178]
* .NET Core Version: Version:   5.0.103 (72dec52dbd)
* Windows version: Windows 20 20H2
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Don't know
 
 **Problem description:**
Loading XAML via `XamlReader.Parse` and other dynamic XAML loading methods exhibits a difference in behavior from compiled XAML when using `xml:space="preserve"` and self-closing XML tags.
 
 **Actual behavior:**
When dynamically loading `<TextBlock xml:space="preserve"> <Run/> </TextBlock>` dynamically, whitespace preceding `<Run/>` is stripped. Using the same markup in a compiled XAML file will **not** strip the preceding whitespace (which is incorrect).
When loading `<TextBlock xml:space="preserve"> <Run></Run> </TextBlock>` dynamically, whitespace preceding `<Run></Run>` **isn't stripped** (which is correct).
 
 **Expected behavior:**
When loading `<TextBlock xml:space="preserve"> <Run/> </TextBlock>` dynamically, the preceding whitespace is preserved.
 
 **Minimal repro:**
https://github.com/shartte/WpfXamlWhiteSpaceMiniRepro

Run `dotnet run`.

![image](https://user-images.githubusercontent.com/1261399/107874755-0e6f1500-6ebc-11eb-8de1-82580356b2fc.png)

It will parse all three cases, and simply output the number of elements in the TextBlocks' inline collection. For the dynamically loaded self-closing tag version, it'll output 2, rather than 3, since the leading white-space has been stripped. For more details, inspect the three TextBlock objects in a debugger.

**Comment by ryalanms** [comment]
Thanks, @shartte.   I'll test this on .NET Framework.  If the behavior is different, we will consider fixing it in .NET Core.

**Comment by miloush** [comment]
Same output on .NET Framework 4.8 for me.

**Comment by shartte** [comment]
Might be closed as a known issue then. Although it'd probably be nice to mention on the markdown page that describes the whitespace behavior that it may differ between dynamic and compiled XAML.

**Comment by ryalanms** [comment]
Thanks, @shartte.  This is similar in .NET Framework.
