### ISSUE TITLE
[VS2019][RC] Custom controls are not loaded to the toolbox

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#418]
VSF_TYPE_MARKDOWNI have again found an issue with controls being shown in the toolbox with the **RC** version of VS 2019.
This issue in not observed in the Preview version.

Steps to reproduce :-
----------------------

1) Put the C1.WPF.dll in C:\WPF folder of your machine.
2) Put the C1Tools.pkgdef in C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional_or_Enterprise_Professional_or_Community\Common7\IDE folder.
3) Open cmd and cd to the above folder.
4) Run devenv.exe /resetsettings.
5) Open Vs2019Professional_or_Enterprise_Professional_or_Community and create a WPF application .
6) Observe that the C1 WPF controls are not seen.

Now again.
7) Put the C1Tools.pkgdef in C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE folder.
8) Open cmd and cd to the above folder.
9) Run devenv.exe /resetsettings.
10) Open Vs2019Preview and create a WPF application .
6) Observe that the C1 WPF controls are seen.

My observation :-

1) The .pkgdef file makes entry to $RootKey$\ToolboxControlsInstaller of the private bin file of Visual Studio

%localappdata%\Microsoft\VisualStudio\version\privateregistry.bin

Now when I open the same of the preview version (load as hive) in regedit, I can see Software\Microsoft\VisualStudio\&lt;16.0_name&gt;_Config\ToolboxControlsInstaller registry.
When I open the same of the RC version this key doesnot exist.

I think Microsoft has again changed something in the way VS 2019 loads toolbox items.

Could you confirm whether the change is inteded? if YES, what is the correct way to register the custom controls to the toolbox.?

If it's a bug, I hope MS could fix is early in the next RC version.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/482527/vs2019rc-custom-controls-are-not-loaded-to-the-too.html
VSTS ticketId: 815307_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by IrinaPykhova** [comment]
Is anyone working on this? I need to understand whether it will be fixed in VS or requires changes from our side

**Comment by KelleyRicker** [comment]
It would be helpful to know if there is a workaround for this.

**Comment by debonte** [comment]
I have trouble believing that this is a WPF issue. I've reactivated the VS feedback issue and am investigating. This issue should probably be closed.

**Comment by debonte** [comment]
Confirmed. This is not a WPF issue. Please close.

**Comment by stevenbrix** [comment]
Thanks @debonte!
