### ISSUE TITLE
IsEditable Not Center Align Combobox

### ISSUE THREAD

**Issue by chuongmep** [dotnet/wpf#4182]
* .NET Core Version: Net FrameWork 4.7.2
* Windows version: 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
1.When we don't use IsEditable 

```
VerticalContentAlignment ="Center"
VerticalAlignment="Center"
IsTextSearchEnabled="True"
```
![image](https://user-images.githubusercontent.com/31106432/108154855-54bcb200-7110-11eb-9cf0-1f9edc57d7a6.png)
2.When we use IsEditable 

```
VerticalContentAlignment ="Center"
VerticalAlignment="Center"
IsEditable="True"
IsTextSearchEnabled="True"
```
![image](https://user-images.githubusercontent.com/31106432/108154982-95b4c680-7110-11eb-89ad-9bed7ab873f5.png)

**Comment by daisyTian0517** [comment]
I used below code to test ComboBox in .Net 4.7.2 , and I can't reproduce your error. Could you give the steps for the below code to reproduce the error.
```
<StackPanel>
        <ComboBox Width="150" Height="30" VerticalContentAlignment ="Center" VerticalAlignment="Center" IsTextSearchEnabled="True">
            <ComboBoxItem>Item1</ComboBoxItem>
            <ComboBoxItem>Item2</ComboBoxItem>
            <ComboBoxItem>Item3</ComboBoxItem>
        </ComboBox>
        <ComboBox Width="150" Height="30" VerticalContentAlignment ="Center" VerticalAlignment="Center" IsTextSearchEnabled="True" IsEditable="True">
            <ComboBoxItem>Item1_1___1</ComboBoxItem>
            <ComboBoxItem>Item2_1___2</ComboBoxItem>
            <ComboBoxItem>Item3_1___3</ComboBoxItem>
        </ComboBox>
    </StackPanel>
```
And the result picture is:
![image](https://user-images.githubusercontent.com/40193800/108168776-cf96c480-7132-11eb-8ba3-5d4b7b524ef6.png)

**Comment by chuongmep** [comment]
> I used below code to test ComboBox in .Net 4.7.2 , and I can't reproduce your error. Could you give the steps for the below code to reproduce the error.
> 
> ```
> <StackPanel>
>         <ComboBox Width="150" Height="30" VerticalContentAlignment ="Center" VerticalAlignment="Center" IsTextSearchEnabled="True">
>             <ComboBoxItem>Item1</ComboBoxItem>
>             <ComboBoxItem>Item2</ComboBoxItem>
>             <ComboBoxItem>Item3</ComboBoxItem>
>         </ComboBox>
>         <ComboBox Width="150" Height="30" VerticalContentAlignment ="Center" VerticalAlignment="Center" IsTextSearchEnabled="True" IsEditable="True">
>             <ComboBoxItem>Item1_1___1</ComboBoxItem>
>             <ComboBoxItem>Item2_1___2</ComboBoxItem>
>             <ComboBoxItem>Item3_1___3</ComboBoxItem>
>         </ComboBox>
>     </StackPanel>
> ```
> 
> And the result picture is:
> ![image](https://user-images.githubusercontent.com/40193800/108168776-cf96c480-7132-11eb-8ba3-5d4b7b524ef6.png)
When im try with combobox second of you , im working with visual studio 2017, 2019 is same problem
![image](https://user-images.githubusercontent.com/31106432/108169588-83945180-712b-11eb-816d-6415f6b27dfe.png)

**Comment by daisyTian0517** [comment]
Did you put my code into your project and run it to get the above capture?  Could you create a test demo use my code to check if the error exists?

**Comment by chuongmep** [comment]
> Did you put my code into your project and run it to get the above capture? Could you create a test demo use my code to check if the error exists?
Thanks you , i has reintall visual studio , it working now.
