### ISSUE TITLE
Published SelfContained WPF app with PublishTrimmed option set to True fails with Unhandled Exception

### ISSUE THREAD

**Issue by TwistedAnckle** [dotnet/wpf#4216]
### Issue Description
Published WPF .Net Core app using MSBuild 16.8.3+39993bd9d for .NET with options PublishTrimmed=True and SelfContained=True fails with Unhandled Exception.

The same app published with MsBuild 16.4.0 and same options works fine.

### Steps to Reproduce
Use WPF (.Net) template from Visual Studio templates, change .csproj file to:
```<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
    <UseWPF>true</UseWPF>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>
 <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="dotnet publish $(ProjectFileName) --configuration $(ConfigurationName) --framework netcoreapp3.1 --self-contained --runtime win7-x64 --no-build --output .\bin\SCD\$(ConfigurationName)" />
  </Target>
</Project>
```

Build project, try to run .exe file located in ProjectMainDirectory/bin/SCD/Debug

### Expected Behavior
Published application works after trimming operation like it was after publish with MSBuild 16.4.0

### Actual Behavior
Unhandled exception thrown.

Can be captured with adding below code to App class in  App.xaml.cs file:
```
        protected override void OnStartup(StartupEventArgs e)
        {
            Current.DispatcherUnhandledException += DisplayUnhandledException; 
            this.DispatcherUnhandledException += DisplayUnhandledException; 
            AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;
            base.OnStartup(e);
        }

        private void CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            MessageBox.Show($"Unhandled exception captured. IsTerminating: {e.IsTerminating}");
        }

        private void DisplayUnhandledException(object sender, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs e)
        {
            MessageBox.Show("Unhandled exception captured: " + e.Exception.Message);
        } 
```
### Analysis
Main issue is probably missing assembly, but why the same app published with older MSBuild works fine? Any breaking changes?

It complains about missing assembly:
FileNotFoundException: Could not load file or assembly 'System.Diagnostics.Debug, Version=4.1.2.0'

Problem occurs in Debug and Release configuration.

### Versions & Configurations
MSBuild version: 16.8.3+39993bd9d for .NET
Visual Studio version: 16.8.3
dotnet --version: 5.0.102

Last working configuration:
MSBuild version: 16.4.0+e901037fe
dotnet --version: 3.1.101

**Comment by ladipro** [comment]
Doesn't look like an MSBuild bug. WPF, can you please take a look?

**Comment by ryalanms** [comment]
Thank you for the report, @TwistedAnckle.  Trimming is not supported by WPF.

**Comment by ryalanms** [comment]
Does this repro with `PublishTrimmed` set to false?  Thanks.

**Comment by TwistedAnckle** [comment]
> Does this repro with `PublishTrimmed` set to false? Thanks.

@ryalanms 
With PublishedTrimmed set to false it works, but the .exe size is almost 2x bigger than trimmed one.
![image](https://user-images.githubusercontent.com/34349313/110620435-4acf2180-8199-11eb-83eb-509c6910ecd4.png)

**Comment by ThomasGoulet73** [comment]
Here is the MSBuild code I use to trim a very barebone application: 
```
<Target Name="ConfigureTrimming" BeforeTargets="PrepareForILLink">
  <ItemGroup>
    <ManagedAssemblyToLink Condition="'%(Filename)' == 'System.Runtime' Or '%(Filename)' == 'System.Runtime.Extensions' Or '%(Filename)' == 'System.Diagnostics.Debug'">
      <IsTrimmable>false</IsTrimmable>
    </ManagedAssemblyToLink>
  </ItemGroup>
</Target>
```

You just have to add this in your main project. I recommend trying your application thoroughly and if you have another exception similar to your exception, just add the name of the assembly at the end of the condition using "Or '%(Filename)' == 'ASSEMBLY_NAME'".

**Comment by ThomasGoulet73** [comment]
Also note that once WPF is annotated for trimming, you shouldn't have to mark assemblies as not trimmable (Though this process doesn't seem to be started).

**Comment by ryalanms** [comment]
Please see https://github.com/dotnet/sdk/issues/16716.  WPF does not support trimming.

**Comment by danmoseley** [comment]
Also linking https://github.com/dotnet/wpf/issues/3811

**Comment by ThomasGoulet73** [comment]
Hey @Symbai,

Here's one that works for .Net 6 + copyused:
```
<ItemGroup>
  <TrimmerRootAssembly Include="System.Collections" />
  <TrimmerRootAssembly Include="System.Runtime" />
  <TrimmerRootAssembly Include="System.Runtime.Extensions" />
  <TrimmerRootAssembly Include="System.Runtime.InteropServices" />
  <TrimmerRootAssembly Include="System.Runtime.CompilerServices.VisualC" />
</ItemGroup>
```

I'll try and send another one that works for .Net 6 + link later.

Hope this helps

**Comment by Symbai** [comment]
No that does not work for me. These are the additional lines I have in my project file
![image](https://user-images.githubusercontent.com/14368203/116782413-33216480-aa89-11eb-826f-8c17813775ba.png)
But launching the app I get:
`System.TypeInitializationException: The type initializer for 'System.Windows.Media.FontFamily' threw an exception.`

**Comment by ThomasGoulet73** [comment]
Hey @Symbai,

I just double-checked and it works on my machine. Here's my csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <TrimMode>copyused</TrimMode>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="System.Collections" />
    <TrimmerRootAssembly Include="System.Runtime" />
    <TrimmerRootAssembly Include="System.Runtime.Extensions" />
    <TrimmerRootAssembly Include="System.Runtime.InteropServices" />
    <TrimmerRootAssembly Include="System.Runtime.CompilerServices.VisualC" />
  </ItemGroup>

</Project>
```

Also, I use this SDK: 6.0.100-preview.5.21230.2. You could try updating, see if it fixes your issue.

Hope this helps.

**Comment by Symbai** [comment]
Yes, updating SDK did the trick. But the trimming has become worse than on .NET 5.

.NET5 trimmed = 123mb
.NET6 trimmed = 151mb

@ThomasGoulet73 Have you found a solution for link mode yet (although on .NET 5 its copyused)? I'm hoping to get at least similar trimming results as with .NET5 then.

**Comment by ThomasGoulet73** [comment]
Hey @Symbai,

Here's one that works for link mode:
<details>
  <summary>Content of the csproj</summary>
  
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <TrimMode>link</TrimMode>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="System.Collections" />
    <TrimmerRootAssembly Include="System.Runtime" />
    <TrimmerRootAssembly Include="System.Runtime.Extensions" />
    <TrimmerRootAssembly Include="System.Runtime.InteropServices" />
    <TrimmerRootAssembly Include="System.Runtime.CompilerServices.VisualC" />
    <TrimmerRootDescriptor Include="TrimmerRoots.xml" />
  </ItemGroup>

</Project>
```
</details>

<details>
  <summary>Content of TrimmerRoots.xml</summary>
  
```
<?xml version="1.0" encoding="utf-8" ?>
<linker>
  <assembly fullname="System.Private.CoreLib">
    <type fullname="System.AppDomain" />
    <type fullname="System.Attribute" />
    <type fullname="System.Reflection.Module" />
    <type fullname="System.Runtime.CompilerServices.IsConst" />
    <type fullname="System.Runtime.CompilerServices.RuntimeHelpers" />
    <type fullname="System.Runtime.InteropServices.CriticalHandle" />
    <type fullname="System.Runtime.InteropServices.GCHandle" />
    <type fullname="System.Runtime.InteropServices.Marshal" />
    <type fullname="System.Security.SecurityCriticalAttribute" />
    <type fullname="System.Security.SuppressUnmanagedCodeSecurityAttribute" />
  </assembly>
</linker>
```
</details>

Beware that your mileage may vary. I only tested it with a simple window with a textbox.

Most of the content in TrimmerRoots.xml is required because the analysis of C++/CLI is not yet supported (See https://github.com/mono/linker/issues/676).

**Comment by ryalanms** [comment]
WPF does not support Trimming.  There is now an error when compiling on .NET 6.0.

**Comment by DanFTRX** [comment]
> WPF does not support Trimming. There is now an error when compiling on .NET 6.0.

Does not currently but may in the future?  Or are there no plans to support it moving forward?

**Comment by Symbai** [comment]
> Or are there no plans to support it moving forward?

According to the [updated roadmap](https://github.com/dotnet/wpf/pull/5685), no.

**Comment by DanFTRX** [comment]
> > Or are there no plans to support it moving forward?
> 
> According to the [updated roadmap](https://github.com/dotnet/wpf/pull/5685), no.

https://github.com/dotnet/wpf/issues/3811 says "future" which I suppose is mildly better than "never"
