### ISSUE TITLE
[.NET6] [Source Compat] PicView app d2p1:Project" in element <Import> is unrecognized error during build with .NET 6 SDK

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/wpf#4221]
**Application Name:**  PicView
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:**  6.0.100-preview.3.21123.4

**Verify Scenarios:**
1. Windows 10 RS5 X64 + .NET Core SDK build 6.0.100-preview.3.21123.4: Fail
2. Windows 10 RS5 X64 + .NET Core SDK build 6.0.100-preview.2.21120.3 Fail
3. Windows 10 RS5 X64 + .NET Core SDK build 5.0.103: Pass
4. Windows 10 RS5 X64 + .NET Core SDK build 3.1.405: Pass

**Repro steps**
1 Source Code check at [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1284934](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1284934)
2 goto PicView\PicView
3 dotnet build
 
**Expected Result:**
Build succeeded

**Actual Result:**
```
C:\Users\valtunc\Desktop\AppSources\PicView\PicView\PicView_nxr2dnu4_wpftmp.csproj(9,11): error MSB4066: The attribute "d2p1:Project" in element <Import> is unrecognized.

Build FAILED.
```

**Findings:** 
Looks like error is comes from GenerateTemporaryTargetAssembly task when building.
We added binlogs for both .net5 and .net6 for comparison.

**MsBuild BinLogs:**
Check at: [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1284934](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1284934)

@dotnet-actwx-bot @dotnet/compat

**Comment by ryalanms** [comment]
It looks like the XmlDocument class is inserting d2p1 as a namespace when xmlns is declared explicitly in an SDK-style project with WPF's PackageReference support enabled.  This is from the XML rewriting done to the temp project.

**Comment by jiangzeng01** [comment]
@ryalanms  Will this issue be fixed in .NET 6 Preview 2? Just want to check if this issue is a blocker for Preview 2.

**Comment by jiangzeng01** [comment]
Close bug as verified with 6.0.100-preview.4.21180.4
