### ISSUE TITLE
[.NET6] [Source Compat] Epub app doesn't build(NETSDK1004 error) with NET6 SDK

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/wpf#4241]
**Application Name:**  Epub
**OS:** Windows 10 RS5
**CPU: X64**
**.NET Build Number:** 6.0.100-preview.2.21117.13

**Verify Scenarios:**
1. Windows 10 RS5 X64 + .NET Core SDK build6.0.100-preview.2.21117.13: Fail
2. Windows 10 RS5 X64 + .NET Core SDK build 6.0.100-preview.1.21106.4: Fail
3. Windows 10 RS5 X64 + .NET Core SDK build 5.0.103: Pass
4. Windows 10 RS5 X64 + .NET Core SDK build 3.1.405: Pass

**Repro steps:**
1. Source Code check at [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1276015](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1276015)
2. goto Epub\JFlepp.Epub.Viewer directory
3. dotnet build /p:Platform=x64

**Expected Result:**
Build succeeded

**Actual Result:**
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21117.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1004: Assets file 'C:\Users\valtunc\Desktop\AppSources\Epub\out\obj\JFlepp.Epub.Viewer_dxyrbeao_wpftmp\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\Users\valtunc\Desktop\AppSources\Epub\JFlepp.Epub.Viewer\JFlepp.Epub.Viewer_dxyrbeao_wpftmp.csproj]

**Binary Log:**
Check at [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1276015](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1276015)

@dotnet-actwx-bot @dotnet/compat

**Comment by jiangzeng01** [comment]
@ryalanms  Will this issue be fixed in .NET 6 Preview 2? Just want to check if this issue is a blocker for Preview 2.

**Comment by marcpopMSFT** [comment]
I think we have the final preview 2 build so seems like this will still be broken there. Assuming the workaround is the same, we'll leave the release notes as is.  @ryalanms I thought there were changes expected on the WPF side to eliminate the two known breakages before turning IncludePackageReferencesDuringMarkupCompilation  back on.

**Comment by ryalanms** [comment]
@marcpopMSFT:  The fix for the two issues is here: https://github.com/dotnet/wpf/pull/4205.  Yes, I should have reverted https://github.com/dotnet/wpf/pull/4089 when the SDK change went to master and the fix missed Preview 2. 

/cc @fabiant3 @dotnet/wpf-developers

**Comment by jiangzeng01** [comment]
Close bug as verified with 6.0.100-preview.4.21180.4
