### ISSUE TITLE
Executing some code in the designer context

### ISSUE THREAD

**Issue by raffaeler** [dotnet/wpf#4284]
I am trying to the nasty trick to use a converter invoked with a "d:" attribute.
I just need to load some resources right before the designer load my xaml files.
I also need to be able to update those resources every time I need to change them (they are not static).

Is there any hook to do that?

**Comment by ryalanms** [comment]
Hi @raffaeler.  There is no hook in WPF to do this.  

You may try asking VS through a feedback ticket.  Thanks.
