### ISSUE TITLE
XML Schemas in xaml files are not accessible

### ISSUE THREAD

**Issue by Garfield550** [dotnet/wpf#429]
* .NET Core Version: `3.0.100-preview4-010677`
* Windows version: `17763.316`
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 
 
 **Problem description:**

Links to XML Schemas in MainWindow.xaml (also in other XAML files) are dead.
 
 **Actual behavior:** 

```powershell
dotnet new wpf -o longlivexml
```

Open any `.xaml` file, open the links (see below).

```xml
xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
```

All of them can't be opened.
 
 **Expected behavior:**

The links show XML Schemas.
 
 **Minimal repro:**
 
See above.

**Comment by weltkante** [comment]
isn't this normal behavior? I always thought you just make up uris under your domain to avoid conflicts with 3rd parties but aren't obligated to actually publish anything under that uri.

Also, does a schema for xaml even exist? How would one describe the extensions it does over normal xml in the schema? I never saw any documentation of how to write xaml schemas, just that you use uris to disambiguate different namespaces ....

**Comment by watfordgnf** [comment]
Namespace names are URI's (IRI's as of XML 1.1), but there is no requirement that they be reachable if they happen to specify a protocol. From the [XML 1.0 recommendations](https://www.w3.org/TR/xml-names/) (emphasis mine):
> The attribute's normalized value MUST be either a URI reference — the namespace name identifying the namespace — or an empty string. The namespace name, to serve its intended purpose, SHOULD have the characteristics of uniqueness and persistence. **It is not a goal that it be directly usable for retrieval of a schema (if any exists)**. Uniform Resource Names [[RFC2141]](http://www.rfc-editor.org/rfc/rfc2141.txt) is an example of a syntax that is designed with these goals in mind. However, it should be noted that ordinary URLs can be managed in such a way as to achieve these same goals.

**Comment by stevenbrix** [comment]
Thanks for filing this issue! I do agree it's a little odd, but @weltkante is correct in that the behavior described here is expected. We don't have a specific schema for XAML since it's just xml + extensions that are understood by System.Xaml and other framework components.

I'm going to go ahead and close this issue, please re-open if you feel there is more to discuss!

**Comment by SupinePandora43** [comment]
i'm work in Visual Studio Code, and have installed XML extension by redhat.
just add this lines to xaml:
`xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://schemas.microsoft.com/winfx/2006/xaml/presentation https://raw.githubusercontent.com/rogalmic/vscode-xml-complete/master/test/Wpf/Wpf.xsd"`

you can find wpf schemas in https://github.com/rogalmic/vscode-xml-complete/blob/master/test/Wpf/Wpf.xsd
// yes it's schemas from other xml extension)
//`xsi:schemaLocation="(link to schema wich can't be opened) (link to .xsd schema file)"`
