### ISSUE TITLE
System.Windows.Media.Matrix Offset Bug with Vector 

### ISSUE THREAD

**Issue by Sickthon** [dotnet/wpf#4292]
https://referencesource.microsoft.com/#windowsbase/Base/System/Windows/Media/Matrix.cs,a64c6d95352b3e53
Code Line 725

There are two main types of parameters within the matrix.Transform() function. If you pass a Point the offset is added to the result, it is, however, not if you do the same with a System.Windows.Vector.
(I hope this is the right place to post this.)

**Comment by predavid** [comment]
@SamBent  - could you please take a look?

**Comment by SamBent** [comment]
That is the correct behavior.  A vector "represents a direction and a magnitude" (says the [doc](https://docs.microsoft.com/en-us/dotnet/api/system.windows.vector?view=net-5.0#remarks)), so applying the transform's offset isn't appropriate.  This is illustrated in the [examples](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.matrix.transform?view=net-5.0#examples) forMatrix.Transform.

**Comment by Sickthon** [comment]
Yes, this makes absolutely sense. I was mislead by the fact that one couldn‘t transform Float-Points, so I just tried to substitute them with vectors. I also don’t see any reason why this function should sometimes be applied directly to the objects and sometimes return the transformed object. Anyway, thank you for your quick and helpful answer.
