### ISSUE TITLE
C# 7.0 Tuple does not work with data binding

### ISSUE THREAD

**Issue by frankwwu** [dotnet/wpf#4312]
* .NET Core Version: 5
* Windows version: 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/master/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**
 C# 7.0 Tuple does not work with WPF DataGrid data binding. The DataGrid remains blank. The old fashion tuple works. I can provide a demo project to prove the bug if you need. Where to upload?

 **Actual behavior:** 
 
// This does not work with data binding to DataGrid:
public List<(int ID, string Name)> Bugs { get; set; }

// This works with data binding to DataGrid:
public List<Tuple<int, string>> Works { get; set; }

 **Expected behavior:**
 
 **Minimal repro:**

**Comment by ThomasGoulet73** [comment]
A DataGrid column can only bind to a property. The member `Item1` for the class Tuple is a property while the member `Item1` for the struct ValueTuple is a field. Note: `(int ID, string Name)` is syntactic sugar for `ValueTuple<int, string>`.

This is the reason why you can't bind your DataGrid to a collection of ValueTuple.

This is not just specific to DataGrid or ValueTuple. IIRC, you cannot bind anything to a field, only a property.

**Comment by jogibear9988** [comment]
You could use this Custom Markup Extension:

using System;
    using System.Globalization;
    using System.Windows.Data;
    using System.Windows.Markup;

    namespace WpfApp1
    {
        public class FieldBinding : MarkupExtension
        {
            private string _fieldName;

            public FieldBinding(string fieldName)
            {
                this._fieldName = fieldName;
            }

            public override object ProvideValue(IServiceProvider serviceProvider)
            {
                return new Binding(){Converter = new FieldValueConverter(this._fieldName) };
            }

            class FieldValueConverter:IValueConverter
            {
                private string _fieldName;

                public FieldValueConverter(string fieldName)
                {
                    this._fieldName = fieldName;
                }
                public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
                {
                    if (value != null)
                    {
                        return value.GetType().GetField(this._fieldName).GetValue(value);
                    }

                    return null;
                }

                public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
                {
                    return null;
                }
            }
        }
    }

But for Value Tuples, it will only work with "Item1" and "Item2", cause the Field Names are not stored inside the Value Tuple.

Example:

       <DataGrid x:Name="dgGrid" HorizontalAlignment="Left" Height="228" Margin="99,121,0,0" VerticalAlignment="Top" Width="351">
            <DataGrid.Columns>
                <DataGridTextColumn Binding="{local:FieldBinding Item1}"></DataGridTextColumn>
                <DataGridTextColumn Binding="{local:FieldBinding Item2}"></DataGridTextColumn>
            </DataGrid.Columns>
        </DataGrid>

**Comment by jogibear9988** [comment]
And more...

This is only a quick sample. Does not support two way, is slow (uses reflection to get value), no child fields, ...

**Comment by frankwwu** [comment]
Thank you all for help! My intention of using tuple is to write less code; and using named tuple for better maintainability. 

The documentation and many related articles of Tuple types for C# 7.0 is somewhat unclear, and misleading. They should explicitly state that the new feature was the named `ValueTuple`, not named `Tuple`.

**Comment by pchaurasia14** [comment]
@frankwwu - As mentioned by @ThomasGoulet73, the reason for this not working in `Binding` scenarios is the absence of properties. Even the doc for ValueTuple mentions this explicitly in the [Remarks](https://learn.microsoft.com/en-us/dotnet/api/system.valuetuple?view=net-7.0#remarks) section.

Hence, closing this issue as designed.

Feel free to let us know if we misread the ask here.
