### ISSUE TITLE
WPF ARM64 Support in .NET 6 Doesn't work for desktop bridge applications that support multiple languages

### ISSUE THREAD

**Issue by Samuel12321** [dotnet/wpf#4336]
* .NET Core Version: 6.0 Preview 3
* Windows version: windows 10 - all
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
 **Problem description:**
It seems WPF ARM64 Support in .NET 6 Doesn't work for desktop bridge applications that support multiple languages, it seems the “/platform” option of ALINK (al.exe) does not support arm64.
Build fails with ' "ARM64" is not a valid setting for option platform' file ALINK

 **Actual behavior:** 
Build fails with ' "ARM64" is not a valid setting for option platform' file ALINK
 
 **Expected behavior:**
Builds Normally
 
 **Minimal repro:**
To reproduce, build [ModernFlyouts](https://github.com/ModernFlyouts-Community/ModernFlyouts) for ARM64

**Comment by Samuel12321** [comment]
@ryalanms any timeline on a fix for this?

**Comment by pb5050** [comment]
no timeline?      is this not an issue worth working out?  or is there a workaround?

**Comment by Samuel12321** [comment]
This is a Visual studio issue, work around is to avoid alink.
 https://developercommunity.visualstudio.com/t/alink-alexe-does-not-support-arm64-windows/1325460
