### ISSUE TITLE
Replace DoubleUtil.IsNaN with double.IsNaN 

### ISSUE THREAD

**Issue by omariom** [dotnet/wpf#4338]
BCL's double.IsNaN  got faster long ago. In .NET Core it is a single instruction.

The usage of [DoubleUti.IsNaN](https://github.com/dotnet/wpf/blob/7e118beef92050c247fac7ad24ce0816e42e77b6/src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/DoubleUtil.cs#L303) should be replaced by [double.IsNaN](https://github.com/dotnet/runtime/blob/4f8be1992cc79807d377afce640f219d4caffb5b/src/libraries/System.Private.CoreLib/src/System/Double.cs#L91).

[Codegen difference](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAJI8YUCAAcAymIBuvMDFwBuGjWZImpBgGEGNAN40GJpuU3AIEADa7rUABQATCB2DWYDJwEoGAXgA+L1d3QSFcADlsCOdvVWpTfQTTDQZLGwYAdQAFADFnEI8vX0CGcKiYn3jE41NakwBtKQwoDjAMABlsAE9XDAcu3o4MAGleLicWAFEECWsFXgxvAF16hgkoXllsDE9cFraMBiiuAFUuXgguNaNkxMbc3hhrJwB5ADN33Bh+uhWGca7KBcbC2FxuIoAEUKMAAaqCODBqvcHk8Xh8vj8HH9lgDRMDQQxTiIMKgiYD4dZEciTABfNR3BgAeiZDAAKgALPYYbATbBQJy6DpsYIQsKRaIOXzvbjtS5cAG4BjYCQbCAIfg7Z7dBjkOiMPgCJW4awQADuYgYGA5vIYrigdrNCrNUBVEjEaDWLIYuAg6w8eE8+GwAGs9hxYFa/RxvgxoWLTnxrMIJTFfON1mJ3tBg1xFD6YFxcIstp5IE5BF7WdkpADdvgrTaji1sGAQ0rrZ4dMKAfg1bIYAIeIq4zBZJCtgwpGAuU4OEUQAxSEgAJzmFhVspTbcMADsAFYUAxF0J3o3PPyAOYcIdHXhK3k67ZUzwZzsMV1cS+eOgIXeffVAKAwDyA6RtxA4S8OQYX9/0+eCEMQsDN2gPFzw/XlvxghB4OAvC6FA8DXCg7DELIpC0HQ2BcHnI4zV4axbGATwKhYFE6kZYgAGYzAsKxbHKSVwVCBhn0RbwbjWRITnOeUrX8BguBgM1jl5WSrilGl7gwFh41CSlEQUsSkQZdiiRJMkYFmBSdNOCkEU8AAyUiAPw4CtMSYkeDJXMbJYOyeAMpzsMA8iyPiKSUl3BgHCsiR/D8bC4Lc4CGEIQgGDihKXPeFKgN8RznIcXyAEJEr+LT6WoWkgA)

<details><summary>Benchmarks</summary>
<p>

```C#
    [SimpleJob(RuntimeMoniker.Net48),
     //SimpleJob(RuntimeMoniker.NetCoreApp31),
     SimpleJob(RuntimeMoniker.NetCoreApp50),
    ]
    [DisassemblyDiagnoser]
    public class IsNaNBenchmarks
    {
        [Benchmark(Baseline = true)]
        [Arguments(123.45)]
        [Arguments(double.NaN)]
        public bool Clr(double value) => double.IsNaN(value);

        [Benchmark()]
        [Arguments(123.45)]
        [Arguments(double.NaN)]
        public bool Wpf(double value) => IsNaN(value);

        public static bool IsNaN(double value)
        {
            NanUnion t = new NanUnion();
            t.DoubleValue = value;

            ulong exp = t.UintValue & 0xfff0000000000000;
            ulong man = t.UintValue & 0x000fffffffffffff;

            return (exp == 0x7ff0000000000000 || exp == 0xfff0000000000000) && (man != 0);
        }

        [StructLayout(LayoutKind.Explicit)]
        private struct NanUnion
        {
            [FieldOffset(0)]
            internal double DoubleValue;
            [FieldOffset(0)]
            internal ulong UintValue;
        }
    }
```
</p>
</details>

### Results:
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i7-8809G CPU 3.10GHz (Kaby Lake G), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=6.0.100-preview.2.21155.3
  [Host]        : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT
  .NET 4.8      : .NET Framework 4.8 (4.8.4341.0), X64 RyuJIT
  .NET Core 5.0 : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT

| Method |           Job |       Runtime |  value |      Mean |     Error |    StdDev |    Median | Ratio | RatioSD | Code Size |
|------- |-------------- |-------------- |------- |----------:|----------:|----------:|----------:|------:|--------:|----------:|
|    Clr |      .NET 4.8 |      .NET 4.8 |    NaN | 1.4431 ns | 0.3717 ns | 1.0903 ns | 0.7239 ns |  1.00 |    0.00 |      67 B |
|    Wpf |      .NET 4.8 |      .NET 4.8 |    NaN | 1.5641 ns | 0.0412 ns | 0.0365 ns | 1.5708 ns |  1.63 |    0.73 |     116 B |
|        |               |               |        |           |           |           |           |       |         |           |
|    Clr | .NET Core 5.0 | .NET Core 5.0 |    NaN | 0.0281 ns | 0.0278 ns | 0.0247 ns | 0.0231 ns |     ? |       ? |      14 B |
|    Wpf | .NET Core 5.0 | .NET Core 5.0 |    NaN | 1.5333 ns | 0.0370 ns | 0.0328 ns | 1.5350 ns |     ? |       ? |     106 B |
|        |               |               |        |           |           |           |           |       |         |           |
|    Clr |      .NET 4.8 |      .NET 4.8 | 123.45 | 0.6543 ns | 0.0348 ns | 0.0308 ns | 0.6531 ns |  1.00 |    0.00 |      67 B |
|    Wpf |      .NET 4.8 |      .NET 4.8 | 123.45 | 1.8958 ns | 0.0343 ns | 0.0287 ns | 1.9000 ns |  2.91 |    0.14 |     116 B |
|        |               |               |        |           |           |           |           |       |         |           |
|    Clr | .NET Core 5.0 | .NET Core 5.0 | 123.45 | 0.0909 ns | 0.0276 ns | 0.0258 ns | 0.0981 ns |  1.00 |    0.00 |      14 B |
|    Wpf | .NET Core 5.0 | .NET Core 5.0 | 123.45 | 1.4530 ns | 0.0390 ns | 0.0346 ns | 1.4525 ns | 17.92 |    6.38 |     106 B |

**Comment by dipeshmsft** [comment]
Closing issue as the corresponding PR has been merged.
