### ISSUE TITLE
Why not WPF supports nested property validation?

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/wpf#4349]
```cs
// Model without INotifyDataErrorInfo
class Model {
    public string A { get; set; }
}

class ViewModel : INotifyDataErrorInfo {
    public Model M { get; set; }
    ...
}
```
```xaml
<Window ...>
    <TextBox Text="{Binding M.A}" />
</Window>
```

In this case, the validation mechanism does not seem to work.

**Comment by lindexi** [comment]
@GF-Huang How about Fody? see https://github.com/Fody

**Comment by GF-Huang** [comment]
How to use？

**Comment by SamBent** [comment]
>In this case, the validation mechanism does not seem to work.

Why should it?   The binding is writing into property A of an object that doesn't expose IDataErrorInfo or INotifyDataErrorInfo, so the only errors it can detect are exceptions thrown by the property-setter.  The parent ViewModel object doesn't participate in the writing of property A, so it can't raise an INotifyDataErrorInfo event.  And even if it did, the event should only mention its own properties, not those of a nested object.

I don't see how to interpret "nested property validation" in any way that makes sense.  Parent objects are ignorant of (and oblivious to) the inner workings of child objects they reference, unless you add mechanisms (e.g. events) to expose them.  If you've gone to that trouble, you might as well expose INotifyDataErrorInfo events too.
