### ISSUE TITLE
Will WebView support streaming from sites like Netflix?

### ISSUE THREAD

**Issue by WayneBBB** [dotnet/wpf#435]
I am trying to use WebView in a WPF app.  Since WebView is based on Edge, I have tried to connect to Netflix to see it will stream video (I can do this with Edge).  The result has been that I can log into Netflix, but if I try to run a video, then things die and the screen goes white.  So basic question which I can't seem to find an answer: Can WebView be used to stream video from a site like Netflix?

**Comment by stevenbrix** [comment]
Hey @WayneBBB, are you referring to the WebView that's in the `Microsoft.Toolkit.Win32.UI.Controls` package as described [here](https://blogs.windows.com/msedgedev/2018/05/09/modern-webview-winforms-wpf-apps/)?

If this works in .NET Fx 4.8 then it should work in .NET Core 3. Are you able to reproduce this issue in .NET Fx 4.8?

**Comment by WayneBBB** [comment]
Steven:  

 

My little WPF app is being done in .NET Framework 4.7.2.  (I have done nothing with .Net Core 3)   The Nuget package I downloaded was “ Microsoft.Toolkit.Wpf.UI.Controls.Webview ” , V6.0.0 Preview-1.  I’m using Visual Studio 2017.  

 

I can navigate to Netflix without problem, but I cannot stream Video  for some reason.  Should I be able to stream video?  If so, then what can I do?  Do I need more packages from Nuget?

 

Thanks for Responding/  Wayne

**Comment by stevenbrix** [comment]
I'd imagine something like this should be supported, although I don't know all the ins-n-outs of what may be going on here.

There is a list of known issues regarding WebView [here](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/rel/3.0.0-preview/docs/controls/WebView-known-issues.md) and I'd recommend opening an issue in that repo regarding this issue.

**Comment by WayneBBB** [comment]
I don't think this is a supported feature.  I believe it would require webview to host some form of a media player with PlayReady capabilities.  It would be nice if someone from Microsoft would answer this to either point me in the right direction, or tell me to not waste my time.
