### ISSUE TITLE
Third Party Control toolbox configuration issue – VS 2019 RC

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#436]
<p>Hi Team,</p><p>We are developing Windows Forms and WPF custom controls and configure those controls in <strong>Visual Studio 2017</strong> and <strong>2019</strong> toolbox using custom VSIX extension with pkgdef file. </p><p>But we are facing issue in WPF platform that toolbox was not configured in VS 2019 RC and it shows as Toolbox initializing long time. Refer the attached screenshot for more details.</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/62964-vs2019rc-wpf.png">vs2019rc-wpf.png</a></p><p>Is this the known issue in  VS 2019 RC and will it be resolved in VS 2019 main release ? Kindly share the details about how to resolve this issue.</p><p>Regards, </p><p>Mohamed Yasir K</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/486227/third-party-control-toolbox-configuration-issue-vs.html
VSTS ticketId: 818540_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by stevenbrix** [comment]
This sounds like a Visual Studio issue and I do believe this will be fixed in either VS2019 RTM or Update 1.
