### ISSUE TITLE
.NET Framework 4.8 WPF - UserControl loaded event firing repeatly when logging on to the computer remotely

### ISSUE THREAD

**Issue by iDreamCXK** [dotnet/wpf#4360]
Windows version: version 1809（Build：17763.1）
.NET Framework 4.8

As the title suggests, when I log on to computer remotely, I find that the  UserControl loaded event will firing every time. 
However, it only firing once for the Window element. And the problem only happens in Win10 , but not Win7 ! 
I wrote a demo to verify this problem，the test results are shown in the figure.
The source code and demo are in the attachment.

[WpfLoadedTest.zip](https://github.com/dotnet/wpf/files/6242331/WpfLoadedTest.zip)

![测试结果](https://user-images.githubusercontent.com/46046441/113268751-4d411900-930a-11eb-8fd1-e78572bc776a.png)

**Comment by batzen** [comment]
Something like that, multiple loaded events, also happens for content in tabs inside a `TabControl`.
The bad part about it is that you get multiple loaded events but not multiple unloaded events.

**Comment by iDreamCXK** [comment]
> Something like that, multiple loaded events, also happens for content in tabs inside a `TabControl`.
> The bad part about it is that you get multiple loaded events but not multiple unloaded events.

That's so bad !

**Comment by SamBent** [comment]
@iDreamCXK - When you reconnect to a remote session, the OS sends a theme-change notification (WM_THEMECHANGE) to every window.  Well, Win7 didn't do this, but Win10 does.  (I don't know why the OS changed this behavior.) 

So you're seeing [documented](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.loaded?view=net-5.0#remarks) behavior:

>Loaded and Unloaded might both be raised on controls as a result of user-initiated system theme changes. A theme change causes an invalidation of the control template and the contained visual tree, which in turn causes the entire control to unload and reload. Therefore Loaded cannot be assumed to occur only when a page is first loaded through navigation to the page.
