### ISSUE TITLE
Localization issue about scroll bar context menu in Simplified Chinese

### ISSUE THREAD

**Issue by kingcean** [dotnet/wpf#4367]
* .NET Core Version: ALL.
* Windows version: all.
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No.
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines]. No.
 
 **Problem description:**
The context menu of scroll bar in Simplified Chinese includes some menu items in English and incorrect Simplified Chinese.

| Menu item | Current implementation | Expected |
| ---------------- | ---------------- | ---------------- |
| Scroll here | 滚动至此 | 滚动至此 |
| Top | Top | 顶部 |
| Bottom | 底 | 底部 |
| Page Up | Page Up | 向上翻页 |
| Page Down | Page Down | 向下翻页 |
| Scroll Up | 向上滚动 | 向上滚动 |
| Scroll Down | 向下滚动 | 向下滚动 |
 
 **Actual behavior:**
 
Following sample targets .NET Core App 3.1 which is incorrect.

![Screenshot1](https://user-images.githubusercontent.com/1724940/113423555-46e19880-9401-11eb-9f82-8b64065a78a3.jpg)

 **Expected behavior:**
 
Following sample targets .NET Framework 4.6 which is correct.

![Screenshot2](https://user-images.githubusercontent.com/1724940/113423637-6d073880-9401-11eb-8ec1-04e1ec12670b.jpg)

 **Minimal repro:**

1. Create a WPF project.
2. Insert a `ScrollViewer`.
3. Run and right click on the scroll bar.

Required Simplified Chinese environment.

**Comment by ryalanms** [comment]
@cristianosuzuki77:  Could you take a look at this one?  Thanks.

**Comment by iamartyom** [comment]
I added fix for this in https://github.com/dotnet/wpf/pull/4407 pr.
Please check.

**Comment by iamartyom** [comment]
I added fix for this in #4407 pr.
Please check.

**Comment by iamartyom** [comment]
I added fix for this in #4407 pr.
Please check.
