### ISSUE TITLE
useWpf with SDK Style projects, NET 4.7.2 and Visual Studio 2017

### ISSUE THREAD

**Issue by manuelelucchi** [dotnet/wpf#4373]
Hi, I'm currently trying to port a big wpf codebase from net framework to net core, step by step. The company I work with is stuck on Visual Studio 2017 (latest version). Since wpf projects can't be ported to net standard, I'm first converting them using try-convert (so it adds useWpf) and then changing the target framework back to 4.7.2. On Visual Studio 2019, everything works fine, the xaml compiles and it adds all the necessary references as you can see in the image below

![image](https://user-images.githubusercontent.com/17146198/113515003-1a00c300-9572-11eb-8267-9ed029734f3e.png)

While in Visual Studio 2017, xaml compilation needs to be specified for each file and it doesn't add all the references

![image](https://user-images.githubusercontent.com/17146198/113514996-13724b80-9572-11eb-88b5-02813921fe87.png)

In the [wpf repo](https://github.com/dotnet/wpf/issues/3865) I learned about Microsoft.NET.Sdk.WindowsDesktop, but using that breaks the project on 2017 (2019 still works fine)

Is there a way to make this combo work or do I have to block this upgrade until the company can upgrade to VS2019?

Thank you in advice

**Comment by manuelelucchi** [comment]
So, asking to the WPF team, is there anything I can do or I have to wait until the Visual Studio upgrade? (or upgrading to .NET 5)

**Comment by pchaurasia14** [comment]
@manuelelucchi - Is this still an issue you're facing?

We recommend to upgrade to latest Visual Studio to ensure all the WPF dependencies are correctly included in the build.
