### ISSUE TITLE
Refocus last selected cell in DataGrid when it gain focus again

### ISSUE THREAD

**Issue by abnervieraso** [dotnet/wpf#4374]
* .NET Core Version: **3.1**
* Windows version: **Windows 10 20H2 (19042.867)**
* Does the bug reproduce also in WPF for .NET Framework 4.8?: **Yes**

 
 
 **Problem description:**
I filled a ObservableCollection with some data then I bound it to a DataGrid.
The actual problem occurs when I navigate in the DataGrid and for example I have select the third entire row (at this moment, the third row is selected). Then, I move to another control (TextBox for example).
When I move focus again to DataGrid pressing **TAB**, first cell of first column is in focus always, I mean, the dataGrid doesn't remember the last selected cell, but the selected row does. 
 
1. **Last Focused Cell:**
![sa1](https://user-images.githubusercontent.com/45499791/113643705-1fc4da00-9640-11eb-808f-5ce3a7ae7931.PNG)

2. **DataGrid lost focus:**
![sa3](https://user-images.githubusercontent.com/45499791/113644186-67983100-9641-11eb-8703-1bf0c8b63d2f.PNG)

3. **When I move focus to DataGrid again** (the cell selection is reset)
![sa2](https://user-images.githubusercontent.com/45499791/113643811-74685500-9640-11eb-9f28-cd198e74abb7.PNG)

 **Actual behavior:** 
 
 **Expected behavior:**
The expected behavior is that the last selection of the cell is refocused, and does not restart.
Like a Windows Forms  DataGridView.

 **Minimal repro:**
1. Navigate on WPF dataGrid, and select any cell.
2. Move focus to a TextBox
3. Move focus again to DataGrid using TAB key.

**Comment by daisyTian0517** [comment]
I followed your steps to create a WPF project with the DataGrid and a WinForms project with the DataGridView , I can reproduce your error.  After reviewing Microsoft's official documentation, there is no such setting. It maybe a bug for DataGrid, but I create a workaround for you to avoid the error. Add the `LostFocus ` for DataGrid and implement it in cs like below:
```
 private void dataGrid_LostFocus(object sender, RoutedEventArgs e)
        {
            if (dataGrid.SelectedItems.Count > 0)
            {
                int rowindex = this.dataGrid.SelectedIndex;
                DataGridRow dataRow = (DataGridRow)dataGrid.ItemContainerGenerator.ContainerFromIndex(rowindex);
                if(dataRow!=null)
                {
                    FocusManager.SetFocusedElement(dataGrid, dataRow as IInputElement);
                }   
            }
        }
```

**Comment by SamBent** [comment]
This is not a bug.  The result of **TAB** depends on the properties mentioned in the [Focus Overview](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/focus-overview?view=netframeworkdesktop-4.8), but not on other dynamic state like the DataGrid's selection.  While you can override this using ad-hoc code (as in previous comment), you risk violating usability and accessibility guidelines - users and assistive technologies expect **TAB** to behave the same over the lifetime of the UI, independent of the history of interaction with that UI.
