### ISSUE TITLE
DataGrid ItemsSource unexpected behavior

### ISSUE THREAD

**Issue by Omcsesz** [dotnet/wpf#4385]
Hello, Team!

I would like to report the following issue:
when I add a new item to a List, then I set it to be the ItemSource, this results in putting the two entries beside each other:
![DataGridUnexpectedBehavior](https://user-images.githubusercontent.com/1839739/113763476-02fcd500-971a-11eb-84c3-736bbd703699.jpg)

[WpfApp1.zip](https://github.com/dotnet/sdk/files/6266869/WpfApp1.zip)

Is this normal?
Can you please support?

**Comment by daisyTian0517** [comment]
The first entry is the `DataGrid.Columns` that you define yourself. The second entry is created by the `AutoGenerateColumns="True"` property.
You need add `AutoGenerateColumns="False"` to your `DataGrid`, **DataGrid.AutoGenerateColumns** is used to get or set a value that indicates whether the columns are created automatically. Its default value is **True**,  so your DataGrid columns are created automatically.

**Comment by Omcsesz** [comment]
I see.
I fixed it, and it works now!
