### ISSUE TITLE
Get of RowDefinition Height gives Pixel value with Star GridUnitType

### ISSUE THREAD

**Issue by magla42** [dotnet/wpf#4392]
* .NET Core Version: 5.0.5
* Windows version: Windows 10, build 19042.868
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Don't know, but probably not considering this [old social.msdn post](https://social.msdn.microsoft.com/Forums/vstudio/en-US/08579b70-8b53-4855-9eea-333ce05491f8/how-to-saverestore-gridsplitter-position?forum=wpf)
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)?: As far as I can judge, this is a runtime issue.

 
 
 **Problem description:**
I have the following `Grid` and `GridSplitter` in xaml:
```
<Grid>
    <Grid.RowDefinitions>            
        <RowDefinition Height="{Binding TheHeight, Mode=TwoWay}"/>
        <RowDefinition Height="2*"/>
    </Grid.RowDefinitions>

     <GridSplitter Grid.Row="0" Height="5" VerticalAlignment="Bottom"/>
     
     ... snip ...

</Grid>
```
With the initial value of `TheHeight` property on the DataContext (viewmodel) set to, for example, `GridLength(1.0, GridUnitType.Star)` this looks as expected.

When the user moves the `GridSplitter`, say for example so the two Grid-rows are equal size, I would expect the `TheHeight` property to be updated via the binding to `GridLength(2.0, GridUnitType.Star)`. 

What I get is however something like `GridLength(321.3, GridUnitType.Star)`. That is, it seems you get the Pixel-value but with the Star `GridUnitType`.

When this `GridLength` is written back to the view, typically next time it is recreated, you get a very large first row and a very small second row. So _setting_ the RowDefinition Height property seems to work as expected.

**Comment by magla42** [comment]
After looking at the code in `GridSplitter.cs` (method `SetLengths`) I realize that GridSplitter of course modifies the Height of _all_ rows using the pixel-value to retain the height-ratio, which seems a very reasonable way to do it. So to restore the same height-ratio for the user when recreating the view, I would have to do this:
```
<Grid>
    <Grid.RowDefinitions>            
        <RowDefinition Height="{Binding TheHeight1, Mode=TwoWay}"/>
        <RowDefinition Height="{Binding TheHeight2, Mode=TwoWay}"/>
    </Grid.RowDefinitions>

     <GridSplitter Grid.Row="0" Height="5" VerticalAlignment="Bottom"/>
     
     ... snip ...

</Grid>
```
and persist both `TheHeight1` and `TheHeight2`. Would this be the best way?

**Comment by SamBent** [comment]
@magla42 - In the general case, GridSplitter doesn't modify _all_ the row definitions;  it modifies all the *-rows, plus the two rows it splits (a function of the GridSplitter's ResizeBehavior).  Persisting the heights of the modified rows (or their ratio to the total *-ness) is the most reasonable thing to do, provided you and your users set your expectations correctly.

After restarting, your grid won't behave exactly like the the original, but instead like the modified grid.  You've lost the original intent of the *-rows, and perhaps converted a fixed row to a *-row, so the grid will reallocate space differently in response to a change in the overall available height or a change in the height of content in the cells.

For example, suppose the user loads data set A, tweaks the row heights to their liking, quits, then restarts and loads data set B.  It's possible that the tweaked heights do a poor job of displaying B, perhaps even worse than the original heights would have done.  The user should understand that it's their fault for changing the heights to suit A, not your fault (and certainly not WPF's).

All this applies to any grid whose heights have been modified by a GridSplitter.  It just can be more startling in your restart scenario, as that's more likely to encounter major differences in the height of the content.

**Comment by magla42** [comment]
Thank you, this was exactly what I needed.
