### ISSUE TITLE
VB My Project Application Page 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#440]
VSF_TYPE_MARKDOWNCreate a new project, Windows Desktop -&gt; WPF App (.Net Framework) / .NET Framework 4.7 - 

My Project - in Application Page, gives an error; there is no error other pages. it doesnt matter, New project and old projects.

&quot;An error occurred trying to load the page.
The method or operation is not implemented.&quot;

VS 2017 Version 15.9.9

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/487809/vb-my-project-application-page.html
VSTS ticketId: 819186_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by stevenbrix** [comment]
Hello, this repo is only for issues regarding bugs in .NET Core. Currently, only VS2019 supports .NET Core 3 development, so if you run into this issue in VS2019 and .NET Core 3 please re-open and we'll take a look, thanks!
