### ISSUE TITLE
WPF XAML file can't see types generated by Razor Source Generator

### ISSUE THREAD

**Issue by Eilon** [dotnet/wpf#4421]
* .NET Core Version: 6.0-preview3
* Windows version: N/A
* Does the bug reproduce also in WPF for .NET Framework 4.8?: N/A
* Is this bug related specifically to tooling in Visual Studio? No (interestingly, this _does_ work in VS IntelliSense, but not when compiling!)

 **Problem description:**

In .NET 6 we are enabling authoring of WPF apps in a "Blazor Desktop" scenario where Blazor web UI (HTML+CSS) is hosted in a web view in a WPF app. Such projects contain a mix of XAML (WPF), Blazor/Razor (HTML+CSS), and other code artifacts (C#, etc.). This is done with a new `<BlazorWebView ... />` WPF control being built by the ASP.NET team.

The XAML compiler, however, is unable to see the types generated by the Razor Source Generator. (Note: Using a source generator is new for Blazor in .NET 6; previously it was done in other ways).

For the WPF BlazorWebView control we’d like to support a XAML syntax like this to specify a Razor component to load:

```xaml 
<Window ...
        xmlns:local="clr-namespace:BlazorWpfApp">
   <DockPanel>
        ...
        <blazor:BlazorWebView HostPage="wwwroot\index.html" Services="{StaticResource services}">
            <blazor:BlazorWebView.RootComponents>
                <blazor:RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
            </blazor:BlazorWebView.RootComponents>
        </blazor:BlazorWebView>
    </DockPanel>
</Window>
```
 
Where `local:Main` is a class that is generated by the Razor compiler as part of the project’s compilation. There is a file `Main.razor` that generates a type Main in the same namespace. The Razor-generated class is visible from C# code, but the XAML compiler is unable to find.

From @captainsafia in an email thread:

> We'll need to do some work on the WPF size to react to the changes made in the Razor SDK.

 **Actual behavior:**

In VS Intellisense you can see the Razor-generated types (good):
![image](https://user-images.githubusercontent.com/202643/115072267-34109e80-9eac-11eb-80da-7d71b4c41f0d.png)

But when you try to compile the app, the XAML compiler can't see the same type anymore (bad):

```
...\MainWindow.xaml(17,55): error MC3050: Cannot find the type 'local:Main'. Note that type names are case sensitive. Line 17 Position 55.
```
 
 **Expected behavior:**

The XAML compiler should be able to see the Razor generated types and compile.
 
 **Minimal repro:**

See repro app here: https://github.com/Eilon/WPFXamlRazorGeneratorBug

To see just the relevant code, look at this commit: https://github.com/Eilon/WPFXamlRazorGeneratorBug/commit/b500285add1908af5a8c49c40e630267b2fabf92

1. Open the SLN in VS
2. Try to run the app, you get the above-mentioned XAML compiler error
3. In `MainWindow.xaml.cs` un-comment the line at the bottom of the file
4. Then everything works fine

**Workarounds:**

There are workarounds for this issue:

1. In the WPF app create a partial class with the same name as the Razor-generated type. The types in Razor are all partial too, so this doesn't really create a new type, but it enables the XAML compiler to believe the type it exists, while creating no ill effects. For example `partial class Index {}`.
2. Move all the Razor files (`*.razor`) to a Razor Class Library so that all the Razor-generated types are available prior to the XAML compiler running, thus enabling it to "see" all the types.

cc @captainsafia @danroth27

**Comment by captainsafia** [comment]
Some more helpful info from the email thread:

It looks like you might be running into some issues related to a breaking change that we made recently in the Razor compiler (see https://github.com/aspnet/Announcements/issues/459).

Previously, the Razor compiler produced a separate AppName.Views.dll assembly that contained the compiled view types in an application as public​ classes under the AspNetCore​namespace. 

Now, the Razor compiler produces a single AppName.dll that contains the compiled view types as internal sealed​ classes under the AspNetCoreGenerated​ namespace.

My hunch is that this change is causing the problem that you see here. It's likely that your implementation will work in .NET 6 Preview 2 and earlier.

Our current model of compiling the views into a single assembly as internal​ types is in place to support some build improvements and hot reload so we'll need to sort out a solution for this moving forward.

**Comment by taoyouh** [comment]
Actually WPF XAML cannot see types generated by other "source generators" too. For example, the resource designer classes generated by VocaDb.ResXFileCodeGenerator cannot be used in WPF XAML file.

**Comment by ThomasGoulet73** [comment]
I opened #6535 which should fix the issue.

A temporary workaround would be to add `<RootNamespace>WpfBlazorRepro</RootNamespace>` to the csproj.
