### ISSUE TITLE
Wpf app KERNELBASE.dll error in windows7 sp1，winform app normal run.

### ISSUE THREAD

**Issue by xianyun666** [dotnet/wpf#443]
# Issue Title

Wpf app KERNELBASE.dll error in windows7 sp1，winform app normal run.

# General

Virtual machine installation of the new system windows7 sp1.
KB2999226 and KB2533623 have been installed successfully

a1.exe 
   1.0.0.0 
   5c7c0388 
   KERNELBASE.dll 
   6.1.7601.17617 
   4dce2040 
   c06d007e 
   0000b9bc 
   a78 
   01d4da3a6d2bc2d0 
   C:\Users\liu\a1\bin\Debug\netcoreapp3.0\a1.exe 
   C:\Windows\syswow64\KERNELBASE.dll 
   ac826401-462d-11e9-bf34-000c29530288

**Comment by stevenbrix** [comment]
Can you provide a bit more information about what you are seeing? Is this just a default app running on Win7?

**Comment by vatsan-madhavan** [comment]
Could it be a variant of https://github.com/dotnet/wpf/issues/37?

**Comment by stevenbrix** [comment]
I think there are a few issues here regarding win7 deployment. This could also be related to #222

**Comment by xianyun666** [comment]
@stevenbrix  What information do you need from me?

**Comment by xianyun666** [comment]
@stevenbrix   This indeed also be related to #222 and #107,

**Comment by vatsan-madhavan** [comment]
I'm closing this in favor of #37. Please look for updates there.
