### ISSUE TITLE
How to specify a TTC font index in a Glyphs.FontURI property in .net5 ?

### ISSUE THREAD

**Issue by Whiletru3** [dotnet/wpf#4459]
I want to put a TTC (True Type Collection) font file in FontURI property of a Glyphs. I use .Net5.0

I found in the old silverlight documentation this : https://docs.microsoft.com/en-us/previous-versions/windows/silverlight/dotnet-windows-silverlight/ms599247(v=vs.95)

> FontUri also supports TTC (TrueType Collection) fonts. You can index a specific font face offset in the collection using the format collectionname.ttc#n where n is the index within the collection. You can omit "#0" if you intend to reference the first font face in the collection.

But in the net5.0 documentation this paragraph is not in the documentation :

https://docs.microsoft.com/en-us/dotnet/api/system.windows.documents.glyphs.fonturi?view=net-5.0

I tried the #1 in the FontURI (for Cambria Math) but without luck. enter image description here

Here is the code i tried to create the glyph font URI :

 glyph.FontUri = new Uri(@"c:\Windows\Fonts\cambria.ttc#1");

Is there a way to render glyphs from a TTC file in .net5 ?

**Comment by miloush** [comment]
It actually works the same, but there is a twist in the URI parsing. Silverlight runs in a browser, so everything is a properly formatted URI, and the `#1` gets parsed as a fragment. However, file path syntax does not support framgents, so the `#1` becomes part of the file name, as you can see by inspecting the Uri instance itself.

The solution is to use a proper URI, in this case `file://C:/Windows/Fonts/cambria.ttc#1`.

**Comment by Whiletru3** [comment]
@miloush : Thanks a lot, you made my day :)
