### ISSUE TITLE
How about create the xaml element with container?

### ISSUE THREAD

**Issue by lindexi** [dotnet/wpf#4461]
Should WPF supports the dependency injection (DI) software design pattern by create the XAML element with container?

See: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0

**Comment by miloush** [comment]
Perhaps a duplicate of #499?

**Comment by lindexi** [comment]
Thank you @miloush 

Duplicate of #499
