### ISSUE TITLE
The recommended /p:ContinuousIntegrationBuild=true causes a wpftmp build error

### ISSUE THREAD

**Issue by jnm2** [dotnet/wpf#4467]
* .NET Core Version: 5.0.300-preview.21180.15
* Windows version: 20H2
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

Steps to reproduce:

- Create a new WPF app using the WPF template targeting net5.0
- At the command line, type `dotnet build /p:ContinuousIntegrationBuild=true`

Result:

```
Microsoft (R) Build Engine version 16.10.0-preview-21175-01+afd0b6210 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
C:\Program Files\dotnet\sdk\5.0.300-preview.21180.15\Roslyn\Microsoft.Managed.Core.targets(191,5): error : SourceRoot
items must include at least one top-level (not nested) item when DeterministicSourcePaths is true
[C:\Users\Joseph\Source\Repos\WpfRepro\WpfRepro_necdjk00_wpftmp.csproj]

Build FAILED.
```

**Comment by ryalanms** [comment]
Hi @jnm2.  

ContinuousIntegrationBuilds requires /p:IncludePackageReferencesDuringMarkupCompilation=true on .NET 5.0.  Can you try that?  Thanks.

**Comment by jnm2** [comment]
@ryalanms That works great! Is IncludePackageReferencesDuringMarkupCompilation going to be set automatically in the future? I'm not sure how folks should know about it.

**Comment by ryalanms** [comment]
@jnm2:  Good to hear.  `IncludePackageReferencesDuringMarkupCompilation` is 'opt-in' in .NET 5.0 and 'opt-out' (on by default) in .NET 6.0.   It was a high-risk feature, and we wanted to avoid breaking existing .NET 5.0 WPF applications in a servicing release.

**Comment by jnm2** [comment]
Thanks, I'll close and think of this as addressed in .NET 6.
