### ISSUE TITLE
Is there anyway to simulate touch on WPF UI? 

### ISSUE THREAD

**Issue by samir-dahal** [dotnet/wpf#4488]
Is this feature request related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? If yes, please file the request via the instructions here: https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2019

**Comment by lindexi** [comment]
@samir-dahal  We can use TouchDevice to do it. The demo code: https://github.com/lindexi/lindexi_gd/tree/f0f872153ed07b2141b47580a74a18a38cc56cfd/DernijacallqaNaycerejerlal

You can find my Chinese blog in https://translate.google.com/translate?sl=auto&tl=en&u=https://blog.lindexi.com/post/WPF-%25E6%25A8%25A1%25E6%258B%259F%25E8%25A7%25A6%25E6%2591%25B8%25E8%25AE%25BE%25E5%25A4%2587.html

**Comment by samir-dahal** [comment]
What happens if to my MouseLeftButtonUp or Down events if I have the touch screen device? Do they work just fine?

**Comment by lindexi** [comment]
@samir-dahal Touch->Mouse

**Comment by samir-dahal** [comment]
Alrighty then! Thank you.
I am using behaviors for MouseLeftButtonUp and was wondering what happens if I try the app on touch screen device.

**Comment by lindexi** [comment]
@samir-dahal  I write a demo that may help you. See https://github.com/dotnet-campus/ManipulationDemo

**Comment by miloush** [comment]
Also note the relevant part of [documentation](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/input-overview?view=netframeworkdesktop-4.8#stylus-input):

> [...] WPF applications can treat the stylus as a mouse by using the mouse API, but WPF also exposes a stylus device abstraction that use a model similar to the keyboard and mouse. All stylus-related APIs contain the word "Stylus".
>
> Because the stylus can act as a mouse, applications that support only mouse input can still obtain some level of stylus support automatically. When the stylus is used in such a manner, the application is given the opportunity to handle the appropriate stylus event and then handles the corresponding mouse event. [...]

(You can also use `InputManager.ProcessIpnut` to inject input events.)

**Comment by ryalanms** [comment]
@samir-dahal:  Please close when you are satisfied with the response.  Thanks.

**Comment by lindexi** [comment]
@samir-dahal Has your problem been solved? Can we close this?
