### ISSUE TITLE
Errors appear in the error list from a WPF project that is not currently being edited or compiled, even though I choose Build Only

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#449]
VSF_TYPE_MARKDOWNI have a solution with many projects.

I chose to build a class library that has nothing to do with XML.

I set the Error List to show WPF errors for &quot;Build Only&quot;

Errors appear in the error list from a WPF project that is not currently being edited or compiled.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/495348/errors-appear-in-the-error-list-from-a-wpf-project.html
VSTS ticketId: 822269_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by stevenbrix** [comment]
Can you share more information? I think I know what issue you are talking about, and this sounds like it could be related to dependencies between projects. I've noticed that if Project A has dependencies on Project B and I right-click and build Project A, then Project B will also get built.  If this is what you are seeing, this doesn't have anything to do with WPF and is probably better suited for the http://github.com/microsoft/msbuild repo if this is behavior that can be changed.

**Comment by stevenbrix** [comment]
I'm going to close this issue for now. If my understanding of this is incorrect, please comment and re-open and we can take a closer look, thanks!
