### ISSUE TITLE
Code comments and behavior are inconsistent in Selector.cs

### ISSUE THREAD

**Issue by lindexi** [dotnet/wpf#4501]
We say that "Returns false if FrameworkElement representing this item has Selector.SelectableProperty set to false", but we just check the object type

https://github.com/dotnet/wpf/blob/1c3be71312540f51d98f769b431ea3cc110844d0/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Selector.cs#L1859-L1872

**Comment by ryalanms** [comment]
Thanks, @lindexi.  Please let WPF triage assign bugs.

**Comment by ThomasGoulet73** [comment]
@ryalanms: @SamBent seems to be the default assignee when creating an issue of type "Feature / API request": https://github.com/dotnet/wpf/blob/main/.github/ISSUE_TEMPLATE/feature_request.md.

**Comment by dipeshmsft** [comment]
Closing the issue as the corresponding PR #5216 is merged.
