### ISSUE TITLE
Use PropertyGrid in WPF, the memory increased from 63M to 4.5G

### ISSUE THREAD

**Issue by dupeng0224** [dotnet/wpf#4504]
* .NET Core Version: 5.0.202

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
when i am use propertygrid in wpf, if set the SelectedObject, the memory increase from 63M to **4.5G**

The Xaml Like this
```
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        xmlns:local1="clr-namespace:WpfCustomControlLibrary1;assembly=WpfCustomControlLibrary1"
        xmlns:winForms="clr-namespace:System.Windows.Forms;assembly=System.Windows.Forms"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800" Loaded="Window_Loaded">
    <DockPanel>
        <ComboBox DockPanel.Dock="Top" ItemsSource="{Binding ObjectItems}" SelectedIndex="{Binding SelectedIndex}"/>
        <WindowsFormsHost>
            <winForms:PropertyGrid x:Name="propertyGrid" PropertySort="Categorized" Dock="Fill"/>
        </WindowsFormsHost>
    </DockPanel>
</Window>
```

The CS Code Like This:
```
public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            this.propertyGrid.SelectedObject = new System.Windows.Forms.Button();
        }
    }
```

**Expected behavior:**

**Minimal repro:**

**Comment by dupeng0224** [comment]
my machine is 16GB Memeory, I Run it in vm it run normal, but when debug it my phyiscal machine, it is increase to 4GB.
![Uploading 企业微信截图_16208000088073.png…]()

**Comment by lindexi** [comment]
@dupeng0224  Could you run my demo?

**Comment by dupeng0224** [comment]
the screenshot above is your demo

**Comment by dupeng0224** [comment]
This is the screenshot use by dotMemory
![1620907296(1)](https://user-images.githubusercontent.com/36428348/118123051-425bc700-b426-11eb-9861-c978ce7614c9.png)

**Comment by lindexi** [comment]
@dupeng0224 what is your screen resolution? 

你的屏幕有多大呢？屏幕分辨率多少呢？

**Comment by lindexi** [comment]
See https://github.com/dotnet/wpf/issues/4265

**Comment by dupeng0224** [comment]
显示器：24寸，屏幕分辨率：1920*1080



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月14日(星期五) 上午8:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dotnet/wpf] Use PropertyGrid in WPF, the memory increased from 63M to 4.5G (#4504)





 
@dupeng0224 what is your screen resolution?
 
你的屏幕有多大呢？屏幕分辨率多少呢？

**Comment by dupeng0224** [comment]
i have resolved this problem, Update the Visual Studio To 16.9.5,  One Previous Version is 16.9.4,and anthor version is 16.8.2.
i think this problem is because of roslyn。
