### ISSUE TITLE
WPF RepeatButton fires only once on TouchUp

### ISSUE THREAD

**Issue by topsterde** [dotnet/wpf#4512]
* .NET Core Version: 3.1
* Windows version: Win 10 1809
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

 **Problem description:**
A wpf application with a "dynamic splashscreen" has a bug with the RepeatButton.
The RepeatButton is not firing repeated click events with a touch monitor. 
 
 **Actual behavior:** 
 WPF RepeatButton fires only once on TouchUp.

 **Expected behavior:**
RepeatButton fires repeated click events like with a long mouse press
 
 **Minimal repro:**
[SplashScreenRepeatButtonBug.zip](https://github.com/dotnet/wpf/files/6465919/SplashScreenRepeatButtonBug.zip)

**Comment by singhashish-wpf** [comment]
I checked this on net6.0 and it seems to work. Can you please confirm?

**Comment by topsterde** [comment]
Yes, I can confirm this.
