### ISSUE TITLE
Default value string instead of String in basic/wpf codesnippet "Add a DependencyProperty Registration" makes propertyType replacement unworkable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#4527]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Default-value-string-instead-of-String-i/1420039)._

---
! [SnippetError.jpg] (https://aka.ms/dc/image?name=B195d354f14ae400fbc6eb10242606948637564271398767543_SnippetError.jpg&tid=195d354f14ae400fbc6eb10242606948637564271398767543)

See the yellow mark of "tring" instead of "String"
Replacing <Default>string</Default> with <Default>String</Default> in the snippet file resolves the problem.

---
#### Feedback Bot on 5/12/2021, 06:19 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Closing in absence of information required to check it further.
