### ISSUE TITLE
Unable to load COM components in.NET 5.0 WPF  

### ISSUE THREAD

**Issue by lifuhua123** [dotnet/wpf#4534]
* .NET Core Version: .net 5.0
* Windows version: win 10 x64
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)?  NO

 **Problem description:**
An error occurs when I try to call an OCX control on an external device in.NET 5.0 WPF :“Could not find assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly.”	
 **Actual behavior:** 
 
 **Expected behavior:**
 
 **Minimal repro:**

**Comment by lifuhua123** [comment]
![无标题](https://user-images.githubusercontent.com/33051107/118744746-77817280-b887-11eb-9d7a-9675763563b3.png)
![无标题](https://user-images.githubusercontent.com/33051107/118744776-86682500-b887-11eb-99e3-6007d04f34aa.png)

**Comment by lindexi** [comment]
@lifuhua123  Adding the WinForms reference to your project by edit your csproj file.

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>netcoreapp3.1;net5-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
```

##### 双击项目文件，进入编辑项目文件，项目文件就是 csproj 文件，尝试在 PropertyGroup 里面加上 UseWindowsForms 属性，如上面代码
