### ISSUE TITLE
AttachedProperty cannot be assigned in a XAML file if it is declared in the same project.

### ISSUE THREAD

**Issue by walterlv** [dotnet/wpf#4544]
* .NET Core Version: 5.0.203
* Windows version: 10.0.19043.985
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 **Problem description:**

Declare a class with an AttachedProperty:

```csharp
public static class DependencyTest
{
    public static readonly System.Windows.DependencyProperty FooProperty = System.Windows.DependencyProperty.RegisterAttached(
        "Foo", typeof(bool), typeof(DependencyTest),
        new System.Windows.PropertyMetadata(default(bool)));

    public static bool GetFoo(System.Windows.DependencyObject element) => (bool)element.GetValue(FooProperty);

    public static void SetFoo(System.Windows.DependencyObject element, bool value) => element.SetValue(FooProperty, value);
}
```

Use the AttachedProperty in a XAML in the same project:

```csharp
<Window x:Class="Walterlv.Demo.XamlProperties.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:local="clr-namespace:Walterlv.Demo.XamlProperties"
        xmlns:system="clr-namespace:System;assembly=System.Runtime">
    <local:DependencyTest.Foo>
        <system:Boolean>True</system:Boolean>
    </local:DependencyTest.Foo>
    <Grid>
    </Grid>
</Window>
```

Then the build will fail.

If the AttachedProperty is written in another project, the build succeeds.
 
 **Actual behavior:**

The error message is:

```
error MC3089: The object 'Window' already has a child and cannot add ''. 'Window' can accept only one child.
```
 
 **Expected behavior:**

There is no building error and it can be treated as an AttachedProperty.
 
 **Minimal repro:**

See the repo: https://github.com/walterlv/Walterlv.Issues.XamlProperties

**Comment by walterlv** [comment]
The AttachedProperty can be completely distinguished from nested classes because nested class is not supported in a XAML.

See the official docs here: 

* [XAML and custom classes - WPF .NET Framework | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/xaml-and-custom-classes-for-wpf)

> Your custom class must not be a nested class. Nested classes and the "dot" in their general CLR usage syntax interfere with other WPF and/or XAML features such as attached properties.

**Comment by lindexi** [comment]
@walterlv  The good news is that we can build successfully with command line.

![](https://user-images.githubusercontent.com/16054566/120804079-d11bb980-c576-11eb-9da5-adc59474d3aa.png)

**Comment by lindexi** [comment]
We can not find the Assembly in NamespaceMapEntry class when the  AttachedProperty is written in the same project. And we can not find the know type in CompileBamlTag in XamlReaderHelper.cs

**Comment by walterlv** [comment]
> We can not find the Assembly in NamespaceMapEntry class when the AttachedProperty is written in the same project. And we can not find the know type in CompileBamlTag in XamlReaderHelper.cs

Try to delay your element decision to `XamlMarkupCompilePass2`?

**Comment by vain0x** [comment]
A workaround that worked for me is to put the attached property *after* the content:

```xaml
<Window x:Class="Walterlv.Demo.XamlProperties.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:local="clr-namespace:Walterlv.Demo.XamlProperties"
        xmlns:system="clr-namespace:System;assembly=System.Runtime">
    <Grid>
    </Grid>
    <local:DependencyTest.Foo>
        <system:Boolean>True</system:Boolean>
    </local:DependencyTest.Foo>
</Window>
```

On VS 2022 .NET 6.0

**Comment by lindexi** [comment]
@vain0x This is a known issue, but I haven't fixed it yet. Thank you.

**Comment by Kuldeep-MS** [comment]
> We can not find the Assembly in NamespaceMapEntry class when the AttachedProperty is written in the same project. And we can not find the know type in CompileBamlTag in XamlReaderHelper.cs

I have added a fix [here](https://github.com/dotnet/wpf/pull/7557). Can you please give it a try and let me know if it works.

**Comment by lindexi** [comment]
@walterlv and @Kuldeep-MS Awesome. It work well.

I successfully rebuild the https://github.com/walterlv/Walterlv.Issues.XamlProperties with .NET 7.0.306 SDK

**Comment by walterlv** [comment]
OK, It is fixed.
