### ISSUE TITLE
Can't compile in Dev17

### ISSUE THREAD

**Issue by RussKie** [dotnet/wpf#4604]
**Problem description:**

It doesn't seem possible to compile the solution if Visual Studio 2022 (Dev17) is installed. The build fails with multiple errors like this:
```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\shtypes.h(118,1): error C4103: alignment changed after including header, may be due to missing #pragma pack(pop) [C:\Development\wpf\src\Microsoft.DotNet.Wpf\src\DirectWriteForwarder\DirectWriteForwarder.vcxproj]
```
 
 **Actual behavior:** 
 
Multiple error. Here's the binlog: [wpf-Build-C4103.zip](https://github.com/dotnet/wpf/files/6569712/wpf-Build-C4103.zip)

 **Expected behavior:**

`.\build.cmd` is successful after clone
 
 **Minimal repro:**

1. Install Dev17
2. `.\build.cmd`

**Comment by weltkante** [comment]
One thing to look at is the C++ language version which is used. WPF projects uses the `/permissive` flag which is disallowed in newer C++ language versions. VS 2019 defaults to C++14 and the WPF projects don't seem to override it, so if VS 2022 updated the default language version to C++20 or newer then the `/permissive` flag [will be ignored](https://devblogs.microsoft.com/cppblog/standard-c20-modules-support-with-msvc-in-visual-studio-2019-version-16-8/)

Might be worth checking out if setting the language version explicitly to C++14 in the WPF projects helps building on VS 2022

**Comment by ryalanms** [comment]
@RussKie:  It looks like this has been fixed in the most recent version of Visual Studio 2022 internal preview (Preview 2.0 31422.488.main).   Updating may fix the problem.

Cleaning the repo before building may also be required:

taskkill /im msbuild.exe /f  (must be admin)
taskkill /im dotnet.exe /f
rmdir /q /s .dotnet
rmdir /q /s artifacts
