### ISSUE TITLE
WPF Application Crashed in System.Environment.FailFast(string message)

### ISSUE THREAD

**Issue by laiy1990** [dotnet/wpf#4610]
* .NET Core Version:  NAN 
* Windows version: 10.0.19042
* Does the bug reproduce also in WPF for .NET Framework 4.8?:  Yes  v4.0.30319
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/master/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**
 WPF Application SomeTime Crashed. Windows log :
堆栈:
   在 System.Environment.FailFast(System.String)
   在 System.Windows.Documents.TextStore.UpdateCompositionText(System.Windows.Documents.FrameworkTextComposition)
   在 System.Windows.Documents.TextStore.RaiseCompositionEvents(Int32 ByRef, Int32 ByRef)
   在 System.Windows.Documents.TextStore.HandleCompositionEvents(Int32)
   在 System.Windows.Documents.TextStore.GrantLockWorker(LockFlags)
   在 System.Windows.Documents.TextStore.RequestLock(LockFlags, Int32 ByRef)
   在 MS.Win32.UnsafeNativeMethods+ITfKeystrokeMgr.KeyDown(Int32, Int32, Boolean ByRef)
   在 MS.Win32.UnsafeNativeMethods+ITfKeystrokeMgr.KeyDown(Int32, Int32, Boolean ByRef)
   在 System.Windows.Input.TextServicesContext.Keystroke(Int32, Int32, KeyOp)
   在 System.Windows.Input.TextServicesManager.PostProcessInput(System.Object, System.Windows.Input.ProcessInputEventArgs)
   在 System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(System.Windows.Input.ProcessInputEventHandler, System.Windows.Input.ProcessInputEventArgs)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   在 System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawKeyboardActions, Int32, Boolean, Boolean, Int32)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(System.Windows.Interop.MSG ByRef, Boolean ByRef)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(System.Windows.Interop.MSG ByRef, System.Windows.Input.ModifierKeys)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(System.Object)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   在 System.Windows.Threading.Dispatcher.Invoke(System.Windows.Threading.DispatcherPriority, System.Delegate, System.Object)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(System.Windows.Interop.MSG ByRef, Boolean ByRef)
   在 System.Windows.Interop.ThreadMessageEventHandler.Invoke(System.Windows.Interop.MSG ByRef, Boolean ByRef)
   在 System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(System.Windows.Interop.MSG ByRef)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   在 System.Windows.Application.RunDispatcher(System.Object)
   在 System.Windows.Application.RunInternal(System.Windows.Window)
   在 MainApp.Main()
 **Actual behavior:** 
 
 **Expected behavior:**
 
 **Minimal repro:**

**Comment by miloush** [comment]
What key did you press, do you have a sample project?

**Comment by laiy1990** [comment]
> What key did you press, do you have a sample project?
I did not capture the key, this is a random event,

**Comment by lindexi** [comment]
Break in https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs#L1743 ?

**Comment by laiy1990** [comment]
> Break in
> 
> https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs#L1743
> 
> ?

yes，But i don't know how it happened.

**Comment by laiy1990** [comment]
TextBox add `IsUndoEnabled = True`  Property  This error is not happened. the Application runing a month.
