### ISSUE TITLE
Popup's placement propery is wrong

### ISSUE THREAD

**Issue by yanshouwang** [dotnet/wpf#4641]
* .NET Core Version: 3.0, 3.1, 5.0
* Windows version: (`winver`) 20H2 (19042.985)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
 
 **Problem description: Popups in WPF show's in wrong place, when set to left the popup shows at right, set to right shows at left, set to up shows at top-right (which should shows at top-left) and set to bottom shows at bottom-right (which should shows at bottom-left).
 
 **Actual behavior:** 
![image](https://user-images.githubusercontent.com/24455689/121114231-f1cd6300-c845-11eb-9550-7a5be7efe186.png)

 **Expected behavior:**
![image](https://user-images.githubusercontent.com/24455689/121114258-fe51bb80-c845-11eb-8f0d-eba0d0fae5c6.png)

 **Minimal repro:**

**Comment by daisyTian0517** [comment]
@yanshouwang
I tested your code on my desktop, and the Popups are on right place. This should be because your device is in tablet mode. **Soultion:**
Please go to your `Settings` -> `System` -> `Tablet`  , then choose `Don't swtict to tablet mode` for the `When I use this device as a tablet`.

**Comment by yanshouwang** [comment]
@daisyTian0517 No, my device is a PC, and the settings is alreay set to PC mode, I think this is related to the windows version or .NET sdk version. This issue doesn't occured on my workmates' computer which the windows and .net sdk version is lower then mine.

**Comment by daisyTian0517** [comment]
It may be not caused by SDK version or winVersion, my winVersion is 20H2, my wpf project target platform is  .NET Framework 4.8.  Do your workmates use the same machines as you?

**Comment by yanshouwang** [comment]
@daisyTian0517 yes, do you installed .net 5.0 SDK? I aslo install .NET 5.0 SDK

**Comment by yanshouwang** [comment]
@daisyTian0517 and this problem even affect my visual studio, but I tried some winform applications, which doesn't have this problem, so I think this only happened in WPF apps.
![image](https://user-images.githubusercontent.com/24455689/121634102-9950cc80-cab6-11eb-9ea7-d3548cb4e8ac.png)
![image](https://user-images.githubusercontent.com/24455689/121634184-b6859b00-cab6-11eb-84a0-e9554d012215.png)

**Comment by daisyTian0517** [comment]
I also tested in .net core5 wpf app and didn't reproduce your issue. It's probably due to your device Settings, like a person who has [simmilar issue](https://stackoverflow.com/a/4043973) with you.

**Comment by yanshouwang** [comment]
Maybe I should try to reinstall my desktop to see if this still exists.

**Comment by MichaeIDietrich** [comment]
As far as I know the popup open direction depends on whether the PC is set to left handed or right handed. For a long time there was a link in the control panel called **Tablet PC Settings** for setting this option, but it was removed in some Windows 10 update for an unknown reason. You can still open the dialog by using the run dialog (Win + R) and entering `shell:::{80F3F1D5-FECA-45F3-BC32-752C152E456E}`. You can find the option in the second tab there.

By the way not all applications or frameworks honor this option.

**Comment by yanshouwang** [comment]
@MichaeIDietrich For me the right hand is set. I think this should be a LTR direction, but actually the popup shows with RTL
![image](https://user-images.githubusercontent.com/24455689/122004344-dedb0580-cde6-11eb-910b-faca44a27efd.png)

**Comment by MichaeIDietrich** [comment]
@yanshouwang I guess the idea behind this is, that if you have a touch display and open a popup with the index finger of your right hand, then it should open to the left, else the popup would open right beneath your right hand and so it would be covered and you would need to move your hand before you can see the popup content. And vice versa with the left hand.

This means if you want the "normal" popup open direction, you need to choose the left handed setting here.
As far as I can tell the right handed option is only set by default for PCs that have a touch display or a stylus display. That's why this behavior does not occur on every PC. (or it might depend on vendor setup)

**Comment by yanshouwang** [comment]
@MichaeIDietrich Got it...but i think the popup should appear on the left when I use a finger touch and right when I use a mouse, and it's too difficult to change this behavior with settings...

**Comment by miloush** [comment]
This is a per-user setting, see #5944. It gets activated only when you connect specific class of devices, e.g. pens or old touch digitizers.

@lindexi I cannot support your workaround this time since it on purpose ignores user's wishes, creating inconsistency with other apps. (Yes I know the default behavior is confusing and annoying)

**Comment by lindexi** [comment]
@miloush Do you mind we public the property of `_menuDropAlignment` ?

**Comment by miloush** [comment]
@lindexi isn't that https://docs.microsoft.com/en-us/dotnet/api/system.windows.systemparameters.menudropalignment?

**Comment by yanshouwang** [comment]
Closed this issue for I have gived up .NET, it's so sad that Microsoft can't follow Google and Apple's steps these years, especially with mobile system, UWP and Fluent Design is finally become a joke...

**Comment by lindexi** [comment]
@miloush The SystemParameters.MenuDropAlignment is readonly. We can not ignore the system settings.

**Comment by lindexi** [comment]
@yanshouwang Do not give up. Come on.

**Comment by yanshouwang** [comment]
> @yanshouwang Do not give up. Come on.

被 Xamarin.Forms 折磨了一年之后，转战 flutter 了，没有对比就没有伤害啊

**Comment by miloush** [comment]
@lindexi I see. I would support making all the properties writeable (i.e. allow to change the system settings). If you want to ignore system settings, you should do it at the control or its template level, not by pretending the system settings are different than they are.

**Comment by miloush** [comment]
I would also support the `Popup.GetPointCombination` to use dynamic resource with `MenuDropAlignmentKey` rather than directly `SystemParameters.MenuDropAlignment`. That way, you could override the value in your resource dictionary.

**Comment by lindexi** [comment]
> I would also support the `Popup.GetPointCombination` to use dynamic resource with `MenuDropAlignmentKey` rather than directly `SystemParameters.MenuDropAlignment`. That way, you could override the value in your resource dictionary.

Thank you.
For performance issues, I do not like use dynamic resource to fix it.
