### ISSUE TITLE
Keyboard navigation to a Hyperlink doesn't show the tooltip

### ISSUE THREAD

**Issue by SamBent** [dotnet/wpf#4673]
* .NET Core Version: 3.0 and above
* Windows version: all
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? no
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/master/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**

1. Run (revised) sample app attached to #4612.
2. Press TAB until focus arrives on the Hyperlink labelled "This is a Hyperlink with a Tooltip" (look for the focus adorner).
3. Wait for the tooltip to appear
 
 **Actual behavior:** 
The tooltip never appears.
 
 **Expected behavior:**
The tooltip appears after 5 seconds.

By contrast, move the mouse over the Hyperlink - the tooltip appears after 5 seconds.

Keyboard navigation should show the tooltip on a Hyperlink (or any FrameworkContentElement), just as it does on a FrameworkElement.

**Comment by ryalanms** [comment]
Fixed by @SamBent's change.

**Comment by SamBent** [comment]
Fixed by the tooltip work in 6.0-preview7.
