### ISSUE TITLE
wpf Create sticky header

### ISSUE THREAD

**Issue by ahmedrabeasmaha** [dotnet/wpf#4684]
i want to make sticky header in application
sticky header is a header that be shown in application and when it goes top it pin and content goes uder him
i do it with canvas but canvas not go to top only content goes under him and it fixed
```
<ScrollViewer>
    <StackPanel VerticalAlignment="Top" HorizontalAlignment="Left">
        <TextBlock TextWrapping="Wrap" Margin="0">
            Scrolling is enabled when it is necessary. 
            Resize the window, making it larger and smaller.
        </TextBlock>
        <Canvas Panel.ZIndex="3" Height="189" RenderTransformOrigin="0.5,0.5">
            <Rectangle Canvas.Top="{Binding VerticalOffset, Mode=OneWay, RelativeSource={RelativeSource AncestorType={x:Type ScrollViewer}, Mode=FindAncestor}}" Width="100" Height="100" Fill="Black" Panel.ZIndex="3"/>
        </Canvas>
        <Grid width="1500" Panel.ZIndex="2">
        </Grid>
    </StackPanel>
</ScrollViewer>
```
i want to kow how to make canvas gose to top and stop when scrolling

**Comment by ryalanms** [comment]
@ahmedrabeasmaha: Can you provide more detail on what you are trying to achieve?

**Comment by miloush** [comment]
@ryalanms in this case I think the request is quite clear, it corresponds to `position: sticky` in css (see an example [here](https://www.w3schools.com/howto/howto_css_sticky_element.asp)).

In more .NET context, the `ListView` grouping in UWP is a prominent example, see a screenshote [here](https://docs.microsoft.com/en-us/windows/apps/design/controls/lists#examples-1). In terms of API, in UWP it corresponds to [`ItemsStackPanel.AreStickyGroupHeadersEnabled`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.itemsstackpanel.arestickygroupheadersenabled?view=winrt-20348).

**Comment by nivle** [comment]
You can use [dockpanel ](https://wpf-tutorial.com/panels/dockpanel/) instead of stackpanel, if you want to be able to scroll the body, and keep the header on top, so your code would look like this, if I understood this issue correctly....


```
<DockPanel>
    <TextBlock DockPanel.Dock="Top">Some header</TextBlock>
    <ScrollViewer>
        <Grid>Other stuff you want to be able to scroll...</Grid>
    </ScrollViewer>
</DockPanel>
```
