### ISSUE TITLE
The Background color painted on the Button occurs on scrolling slowly using horizontal scrollbar 

### ISSUE THREAD

**Issue by JagadeesanPichaimuthu** [dotnet/wpf#4685]
The Background color painted on the Button occurs on scrolling slowly using a horizontal scrollbar 

1. Make sure the horizontal scrollbar is positioned to the far left 
2. Move the horizontal scroll bar very slowly
3. Observe the Background color painted on the Button.

Expected result: Background color should not paint on the Button.

Output screen shot: 
![sshot-39](https://user-images.githubusercontent.com/44426969/122193707-59248c00-ceb2-11eb-8306-cd996884b868.png)

**Code snippet:**
`<Window
    x:Class="Button.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="clr-namespace:Button"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Title="MainWindow"
    Width="170"
    Height="200"
    mc:Ignorable="d">
    <ScrollViewer HorizontalScrollBarVisibility="Visible">
        <Grid Width="250" Background="Red">
            <Button
                Width="250"
                Height="30"
                Margin="20,5,5,5"
                Background="White"
                BorderBrush="White"
                Content="GroupBarItem 1"
                SnapsToDevicePixels="True" />
        </Grid>
    </ScrollViewer>
</Window>`

**Comment by lindexi** [comment]
@JagadeesanPichaimuthu Is the DPI problem? see https://github.com/microsoft/WPF-Samples/blob/master/PerMonitorDPI/readme.md

**Comment by JagadeesanPichaimuthu** [comment]
I have checked this bug by following these guidelines - https://github.com/microsoft/WPF-Samples/blob/master/PerMonitorDPI/readme.md and still the bug reproduced. And this bug reproduced in VS 2022 Preview also.
![MicrosoftTeams-image (127)](https://user-images.githubusercontent.com/44426969/124575558-20e8eb80-de69-11eb-84ea-99ed41823d8c.png)

**Comment by miloush** [comment]
The scrollbar does not scroll by integer values. You can resolve your issue by using `UseLayoutRounding="True"`, e.g. on the parent `Grid` which is in charge of the button layout (the documentation prefers it on the root element).

**Comment by pchaurasia14** [comment]
@JagadeesanPichaimuthu - Does @miloush's suggestion work for you?

**Comment by singhashish-wpf** [comment]
Closing in absence of a reply.
