### ISSUE TITLE
Improve AssemblyInformationVersionAttribute contents

### ISSUE THREAD

**Issue by onovotny** [dotnet/wpf#474]
Hi,

Currently the contents of the `AssemblyInformationalVersionAttribute` looks something like this:

`4.8.27522.14 @BuiltBy: dlab14-DDVSOWINAGE077 @Branch: master @Commit: 5cd1bc54eca491024d501e926f7fb058dbf9e657`

There's a lot in there to unpack. By contrast, the CLR's version of the attribute looks like this:

`3.0.0-preview4.27525.71+a593024b85a6e074770c88867491f4f30cc6fc8a`

Can the WPF version of the attribute be improved/split up? The branch name, if relevant (why if the commit hash is there), could go in a different AssemblyMetadata attribute. Same as the `BuildBy`.

Lastly, is there a way to get the version value itself to match that of the shared desktop version: `3.0.0-preview4-27522-14`?

What I'd like to see, for the particular version I have, is this: `3.0.0-preview4-27522-14+5cd1bc54eca491024d501e926f7fb058dbf9e657`

/cc @richlander as he drove improvements to this area for the BCL in 3.0.

**Comment by stevenbrix** [comment]
I don't have much background on how this attribute is currently created, but if other dotnet assemblies building using Arcade can do it, then I'm sure we can as well.

**Comment by stevenbrix** [comment]
Actually @onovotny i just opened up the latest windowsbase.dll installed into my shared location (from yesterday's build from http://github.com/dotnet/core)and noticed that it has the same format as you described. I'm going to close this issue since it seems to have already been fixed. If you disagree, please respond and we'll re-open it. Thanks!

**Comment by vatsan-madhavan** [comment]
Are managed C++ assemblies (directwriteforwarder, s.printing) also in the same consistent state?

**Comment by onovotny** [comment]
Any idea when that should be injected into the SDK?

**Comment by onovotny** [comment]
I just looked there as well, I don't think it's correct. It shows `4.8.0-preview4.19202.25+269024f4d2c6a32a58ce3282c5dba57dc2fc8430`

That's still tied to the .NET Framework version, which is incorrect. It should be tied to the .NET Core shared sdk version, I think?

**Comment by vatsan-madhavan** [comment]
See [this explanation](https://github.com/dotnet/toolset/pull/563#issuecomment-477854117) from @ericstj about why framework assemblies are versioned this way.

**Comment by vatsan-madhavan** [comment]
@ericstj, IIRC you had suggested recently that we should bump our `AssemblyVersion` to be greater than that of the corresponding .NET Framework `AssemblyVersion`s. Did you have a specific `AssemblyVersion` in mind that we should use instead of `4.0.0.0` or `4.8.0.0`? 

/cc @rladuca, @miguep, @ojhad
