### ISSUE TITLE
WPF != WF

### ISSUE THREAD

**Issue by DickBaker** [dotnet/wpf#4745]
the most recent commit for WPF (https://github.com/dotnet/wpf/) solely involves Winforms versioning
https://github.com/dotnet/wpf/commit/2530752f0d19900934f73c83f8b131704c70ff14

WTF has WF got to do with WPF and why is there any commonality as each has its unique design (WF is veneer over WinHandles etc, and WPF is XAML etc) ?
- I know there may be some sleight of hand with XAML islands, but I am really surprised to see overlap on GH

**Comment by ryalanms** [comment]
@DickBaker:  WPF supports WinForms through the WindowsFormsHost.  Due to this dependency the WinForms runtime flows through WPF in the .NET SDK build.  WPF then flows to the WindowsDesktop, which flows to the SDK and SDK Installer.
