### ISSUE TITLE
XAML Islands in .NET 5+

### ISSUE THREAD

**Issue by Alovchin91** [dotnet/wpf#4769]
To be honest, I'm completely lost right now.

The [official documentation](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands#wpf-and-windows-forms-applications) for XAML Islands states that XAML Islands are not currently supported on .NET 5.

[WinUI 3 roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/roadmap.md) states that XAML Islands support for WinUI 3 will arrive in a future release ([the website](https://microsoft.github.io/microsoft-ui-xaml/about.html) says next year), but I'm not sure how does it correlate with .NET team's plans.

I couldn't find any issues about XAML Islands neither in this repo nor in dotnet/runtime. I also cannot find any roadmap on when (and if) it will arrive in any future version of .NET. It's all very confusing.

Could you please clarify the situation?

**Comment by lindexi** [comment]
See https://github.com/microsoft/WindowsAppSDK/discussions/987

**Comment by Alovchin91** [comment]
Thanks! 🙂
