### ISSUE TITLE
WPF project templates use latest C# language idioms

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/wpf#4774]
In .NET 6, the included C# project templates will use the latest language idioms.

See the [parent Epic](https://github.com/dotnet/templating/issues/3359) for details.

@OliaG

**Comment by vatsan-madhavan** [comment]
@ryalanms @SamBent https://github.com/dotnet/wpf/tree/main/packaging/Microsoft.Dotnet.Wpf.ProjectTemplates sought to unify/accommodate several nearly-identical templates across multiple TFM's - it wasn't designed to handle unification of disparate templates. This change will create a new template that will be a large departure from existing templates, I think. 

I would highly recommend forking the template package at this time and starting a new line for .NET 6+ (and retain the .NET 5, .NET Core 3.x, .NET Framework support in the older package as-is).

**Comment by RussKie** [comment]
You want to be aware of https://github.com/dotnet/sdk/pull/18459 and implement global usings support once it is merged. I have https://github.com/dotnet/winforms/pull/5183 waiting for it as well.

**Comment by DamianEdwards** [comment]
@OliaG  @vatsan-madhavan the SDK feature for global usings has now been merged. The epic has been updated with details of which namespaces are imported by which SDKs. Would appreciate you adding details for WPF at your convenience.

**Comment by DamianEdwards** [comment]
@OliaG @ryalanms @SamBent @RussKie @vatsan-madhavan is there an update on the status of this for WPF?

**Comment by vatsan-madhavan** [comment]
@DamianEdwards I’m just offering pointers from experience  - it’s up to the team (@SamBent @ryalanms) to commit to specific timelines/plans.

**Comment by vlada-shubina** [comment]
Just a hint since this repo is also using `--langVersion`: in project common templates we discovered issues to due to new features are only working in certain frameworks / language versions, so we are considering to conditionally enable features based on language version set by user (if set).
Draft PR on this is here: https://github.com/dotnet/templating/pull/3454.

**Comment by RussKie** [comment]
@ryalanms you can use https://github.com/dotnet/winforms/pull/5609 as a guide.

**Comment by ryalanms** [comment]
WPF included implicit namespace support and added nullable to the templates.  Other updates will need to go in servicing.

**Comment by dipeshmsft** [comment]
@DamianEdwards @OliaG @vlada-shubina Are we good to close this issue? We have enabled implit usings and file-scoped namespaces by deault in our templates, here is the corresponding PR https://github.com/dotnet/wpf/pull/6973
