### ISSUE TITLE
Application.GetContentStream() may fail if the app is in a path that contains a "#".

### ISSUE THREAD

**Issue by neelabo** [dotnet/wpf#4781]
* .NET Core Version:  .NET 5.0
* Windows version: 21H1
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 **Problem description:**

Application.GetContentStream() will fail if you place the executable in a path that contains "#".
Apparently, the paths after the "#" have disappeared. 
 
 **Minimal repro:**

For example, if you place the executable file and content file in "C:\FooBar\Path#Name\\",
you will get the exception `FileNotFoundException: Could not find file 'C:\FooBar\test.png'.`.

``` cs
var uri = new Uri("/test.png", UriKind.Relative); // test.png is content file
var streamResourceInfo = Application.GetContentStream(uri); // <- Exception!!
```

**Comment by lindexi** [comment]
I wrote a demo in GitHub:  https://github.com/lindexi/lindexi_gd/tree/e1022aededd1871017e4c43f228ad1fe26c99b57/  and I found that it seems is the Uri's bug, not the WPF

**Comment by dipeshmsft** [comment]
Closing this issue as the corresponding fix has been merged in main branch
