### ISSUE TITLE
Custom Rendering Backend

### ISSUE THREAD

**Issue by deeprobin** [dotnet/wpf#4808]
Hello,
I would have the suggestion to add the possibility to use a custom backend for rendering. 
Then you would have the possibility to use OpenGL or other tools instead of DirectX.
This would be implementable with an interface `IRenderingBackend`. By default you could use DirectX, but you should be able to adjust this via a DependencyProperty in the App.xaml.

**Comment by lindexi** [comment]
Duplicate of #https://github.com/dotnet/wpf/issues/85 ?

**Comment by deeprobin** [comment]
@lindexi Oh yes, you're right. I'll close this.
