### ISSUE TITLE
DisableImplicitNamespaceImports required to build WPF application

### ISSUE THREAD

**Issue by kant2002** [dotnet/wpf#4827]
Microsoft.WindowsDesktop.App 6.0.0-preview.7.21356.1

If I do not add `<DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>` to project file, then WPF project cannot compile.

**Comment by kant2002** [comment]
> You want to be aware of [dotnet/sdk#18459](https://github.com/dotnet/sdk/pull/18459) and implement global usings support once it is merged. I have [dotnet/winforms#5183](https://github.com/dotnet/winforms/pull/5183) waiting for it as well.

Possible related.

**Comment by ryalanms** [comment]
This will be disabled in WPF for Preview 7.

**Comment by ryalanms** [comment]
This has been disabled in Preview 7 and main.  Thank you, @kant2002, for identifying the issue.
