### ISSUE TITLE
Disappearing Text, Zoom Text in ListView, and Garbled Icons 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#4831]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Disappearing-Text-Zoom-Text-in-ListView/1471966)._

---
[severity:It's more difficult to complete my work] [regression]
Disappearing text and garbled graphics. 

1) See MY attached video and times where issues are

00:20-00:25	Zoomed Text
00:39-00:40	Zoomed Text
00:46	scrambles graphics 
1:06 	Dis-appearing menu text

2) I have also recorded another video with Visual Studio Step Recorder showing similar issues.

3) This problems started after updating the Visual Studio 2019 to latest  v16.10.3

---
#### Feedback Bot on 7/11/2021, 07:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Pratik Patel on 7/11/2021, 09:17 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ryalanms** [comment]
Were there any overlay applications installed on the machine when testing?

**Comment by ryalanms** [comment]
We believe this is bug #707.
