### ISSUE TITLE
Scroll freezing

### ISSUE THREAD

**Issue by anton-zaicev** [dotnet/wpf#4834]
@SamBent,
I have issue related to already fixed bug: https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/407

Same actions are needed for the scroll freezing (DPI > 100%, virtualizing enabled with "Pixel" scroll unit). This behaviour seems to be related with one of the recent updates of the PresentationFramework.dll (current version I have is - 4.8.4360.0), but not sure about it.

The key thing for now is that UseLayoutRounding property is involved. When I use UseLayoutRounding="False" for the container there is no any freezing, but with "True" value I have scroll freezing every time.

Here is the scroll trace with infinite scroll calculations loop which I had collected:
[ScrollTrace.zip](https://github.com/dotnet/wpf/files/6807623/ScrollTrace.zip)

**Comment by ryalanms** [comment]
Thanks, @anton-zaicev.  Could you provide a minimal repro project?

**Comment by anton-zaicev** [comment]
Can you provide any kind of feedback? Were you able to reproduce this issue with provided project?

**Comment by SamBent** [comment]
I'm busy with servicing requests - it will be quite some time before I can look at this.  Consider opening a servicing request for this (by going through Microsoft support, as we've discussed in the past).  If it's that simple, it would meet the bar.  And that would get it on my radar.

**Comment by anton-zaicev** [comment]
Support incident has been opened. Ticket number: 2108260040002206

**Comment by dipeshmsft** [comment]
Looks like the fix has already been merged. Closing this issue
