### ISSUE TITLE
Undo workaround for inboxed analyzers after updating to Preview 7

### ISSUE THREAD

**Issue by ryalanms** [dotnet/wpf#4848]
Undo workaround for inboxed analyzers after updating to Preview 7.

WPF, WinForms, and WindowsDesktop required this Arcade change.  After updating to Preview 7, remove Exclude inboxed analyzers from VerifyClosure task dotnet/arcade#7624.

**Comment by ericstj** [comment]
Moving to WPF as workaround will be moved here.

**Comment by ryalanms** [comment]
Reverted here:  https://github.com/dotnet/arcade/commit/7b88b24068ecb4f6cf1da8395dbc2dee25a700bd.  

Thanks, @ericstj.

**Comment by ericstj** [comment]
I moved this here to track undoing https://github.com/dotnet/wpf/pull/4849

**Comment by ericstj** [comment]
I believe you should be able to undo that now, since you're on an RC sdk.

**Comment by ericstj** [comment]
Let me see if I can do this now.
