### ISSUE TITLE
[Loc]With net6 preview 7 installed on locale OS, some template names are unlocalized after runing "dotnet new --list" in CLI 

### ISSUE THREAD

**Issue by vdanche** [dotnet/wpf#4856]
Install net 6 preview 7 SDK[6.0.100-preview.7.21364.30(runtime:6.0.0-preview.7.21360.10)] from https://github.com/dotnet/installer
Install it on locale OS
Run “dotnet new --list” in CLI
Check if output contents are localized well.
**Actual Result:**
Some template names are not localized.

e.g
SC
![image](https://user-images.githubusercontent.com/65637796/125880252-13314609-cf54-447d-8b99-4a24b465be39.png)

DE;
![image](https://user-images.githubusercontent.com/65637796/125880293-64a2b3d5-7a07-4a11-8ef3-d20812a6a651.png)

**Comment by ryalanms** [comment]
Thanks, @vdanche.  This is tracked here:  https://github.com/dotnet/wpf/issues/3663.

**Comment by vdanche** [comment]
@ryalanms it still repro on the latest RC1 SDK-6.0.100-rc.1.21458.32(runtime-6.0.0-rc.1.21451.13) .
E.g(SC screenshot)
![image](https://user-images.githubusercontent.com/65637796/133036536-9bb66a2e-9171-4b28-ab32-4d2a948e4a43.png)
