### ISSUE TITLE
dotnet 5 wpf did not respect "Prefer32Bit" setting

### ISSUE THREAD

**Issue by WillLiu-Eclipse** [dotnet/wpf#4872]
* .NET Core Version: 5.0.301
* Windows version: Windows 10 Pro 1909 OS build 18363.1556
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
 
 **Problem description:**
In net48, when the project checked "Prefer32Bit" the application will run in 32bit.
In net5.0-windows, with the same setting, the application will still run in 64 bit.

Settings:
`  <PropertyGroup Condition="'$(Platform)'=='AnyCPU'">`
`        <PlatformTarget>AnyCPU</PlatformTarget>`
`        <Prefer32Bit>true</Prefer32Bit>`
`  </PropertyGroup>`
 
 **Actual behavior:** 
The application run in 64 bit
 
 **Expected behavior:**
The application should run in 32 bit
 
 **Minimal repro:**
1. create empty wpf project, right click project
2. goto properties
3. under "Build" tab select Platform target "AnyCPU" and check Prefer 32-bit
4. Run the application, verify the bitness from task manager

 **Workaround:**
Directly set the platformTarget to x86
`  <PropertyGroup Condition="'$(Platform)'=='AnyCPU'">`
`        <PlatformTarget>x86</PlatformTarget>`
`        <Prefer32Bit>true</Prefer32Bit>`
`  </PropertyGroup>`

**Comment by ryalanms** [comment]
This doesn't apply to .NET Core.  Please see https://github.com/dotnet/project-system/issues/5074.  Thanks.
