### ISSUE TITLE
The style for button can be only apply to the last button control

### ISSUE THREAD

**Issue by yebo7754116** [dotnet/wpf#4894]
* .NET Framework Version:4.6.2
* Windows version:10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 
 
 **Problem description:**
It's quite strange,when i set a style for button in window.Resource,then i place 4 button in stackpanel,but after run the demo,i found that  only the last button in the stackpanel can be applied the style(only the last button has a red ellipse on it) which i define in Windows.Resource，below is the code which i wrote 

```
<Window
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApplication1"  
        x:Class="WpfApplication1.MainWindow"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525">
    <Window.Resources>
        <Style TargetType="Button">
            <Setter Property="Width" Value="80"></Setter>
            <Setter Property="Content">
                <Setter.Value>
                    <Grid>
                        <Ellipse Fill="Red" Width="20" Height="20"/>
                    </Grid>
                </Setter.Value>
            </Setter>
        </Style>
    </Window.Resources>
    <Grid>
        <StackPanel Orientation="Vertical">
            <Button x:Name="button"  Padding="5 2" Margin="2" FontSize="11"  Width="80" Height="30" Background="Teal" ></Button>
            <Button x:Name="button1" Padding="5 2" Margin="2" FontSize="11"  Width="80" Height="30" Background="Aqua"></Button>
            <Button x:Name="button2" Padding="5 2" Margin="2" FontSize="11"  Width="80" Height="30" Background="Beige"></Button>
            <Button x:Name="button3" Padding="5 2" Margin="2" FontSize="11"  Width="80" Height="30" Background="Yellow">            </Button>
        </StackPanel>
    </Grid>
</Window>
```
 Who can tell me the reason? It's a bug in wpf?

**Comment by Metritutus** [comment]
My understanding is that, by default, WPF will reuse the same resource instance whenever that resource is requested (unless  `x:Shared="False"` is specified for that resource).

This means that WPF is not creating more than one instance of any `FrameworkElement` specified in the `Content` value, it's just reusing the same instances over and over again.  As a `FrameworkElement` can only have one parent, the button content (the `Grid` and the `Ellipse`) only ever shows up in one of the buttons.

I believe you have two options here.  You could specify `x:Shared="False"` for your `Style` (you can read more about it [here](https://docs.microsoft.com/en-us/dotnet/desktop/xaml-services/xshared-attribute)), or you could change your setter to set the `ContentTemplate` property of the button instead, eg:

```xaml
<Setter Property="ContentTemplate">
    <Setter.Value>
        <DataTemplate>
            <Grid>
                <Ellipse Fill="Red" Width="20" Height="20" />
            </Grid>
        </DataTemplate>
    </Setter.Value>
</Setter>
```

**Comment by yebo7754116** [comment]
> My understanding is that, by default, WPF will reuse the same resource instance whenever that resource is requested (unless `x:Shared="False"` is specified for that resource).
> 
> This means that WPF is not creating more than one instance of any `FrameworkElement` specified in the `Content` value, it's just reusing the same instances over and over again. As a `FrameworkElement` can only have one parent, the button content (the `Grid` and the `Ellipse`) only ever shows up in one of the buttons.
> 
> I believe you have two options here. You could specify `x:Shared="False"` for your `Style` (you can read more about it [here](https://docs.microsoft.com/en-us/dotnet/desktop/xaml-services/xshared-attribute)), or you could change your setter to set the `ContentTemplate` property of the button instead, eg:
> 
> ```
> <Setter Property="ContentTemplate">
>     <Setter.Value>
>         <DataTemplate>
>             <Grid>
>                 <Ellipse Fill="Red" Width="20" Height="20" />
>             </Grid>
>         </DataTemplate>
>     </Setter.Value>
> </Setter>
> ```

**Comment by yebo7754116** [comment]
@Metritutus Thank you for your reply
