### ISSUE TITLE
Add a WebAssembly target

### ISSUE THREAD

**Issue by dsaf** [dotnet/wpf#49]

**Comment by richlander** [comment]
We are not taking cross-platform implementations, per our [Contributor Guide](https://github.com/dotnet/wpf/blob/master/Documentation/contributing.md).

We look forward to many contributions to WPF. This request is out of scope for the project.

From a technical standpoint, WPF depends on multiple Windows components: D3D (DirectX), DWrite, User32, GDI+, WISP (Touch), and several others (including Windows Runtime dependencies). The interaction with these components is complex, critical and not architected with cross-platform in mind. As a result, our focus is on completing open source of WPF and bringing it to parity with .NET Framework.

I am closing this issue as a result.
