### ISSUE TITLE
wpf call GetMonitorInfo API returns an error screen size

### ISSUE THREAD

**Issue by zou-z** [dotnet/wpf#4932]
My screen resolution is 1920*1080 and I changed the screen zoom size to 150%.Than I write a wpf(.Net Framework 4.8) application and a C# console application to call the MonitorEnumProc and GetMonitorInfo API.The screen size returned by the wpf application is 1920*1080,but the C# console application is 1280*720.

this is my code:
`
public class ScreenUtil
{
    #region Win32
    [StructLayout(LayoutKind.Sequential)]
    public struct RECT
    {
        public int Left;
        public int Top;
        public int Right;
        public int Bottom;
    }

    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto, Pack = 4)]
    public class MONITORINFOEX
    {
        internal int cbSize;
        internal RECT rcMonitor;
        internal RECT rcWork;
        internal int dwFlags;

        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 32)]
        internal char[] szDevice;

        public MONITORINFOEX()
        {
            cbSize = Marshal.SizeOf(typeof(MONITORINFOEX));
            rcMonitor = default;
            rcWork = default;
            szDevice = new char[32];
        }
    }

    public delegate bool MonitorEnumProc(IntPtr monitor, IntPtr hdc, IntPtr lprcMonitor, IntPtr lParam);

    [DllImport("user32.dll", EntryPoint = "EnumDisplayMonitors")]
    private static extern bool EnumDisplayMonitors(IntPtr hdc, IntPtr lprcClip, MonitorEnumProc lpfnEnum, IntPtr dwData);

    [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
    private static extern bool GetMonitorInfo(IntPtr hmonitor, [In][Out] MONITORINFOEX info);
    #endregion

    public struct Screen
    {
        public IntPtr Monitor;
        public IntPtr HDC;
        public string Device;
        public Rectangle Bounds;
        public int DeviceIndex;
        public int Flag;
    }

    private static int index;
    private static List<Screen> screens=new List<Screen>();

    public static List<Screen> Screens
    {
        get
        {
            screens.Clear();
            index = 0;
            MonitorEnumProc proc = Callback;
            _ = EnumDisplayMonitors(IntPtr.Zero, IntPtr.Zero, proc, IntPtr.Zero);
            return screens;
        }
    }

    private static bool Callback(IntPtr monitor, IntPtr hdc, IntPtr lprcMonitor, IntPtr lparam)
    {
        Screen screen = new Screen
        {
            Monitor = monitor,
            HDC = hdc,
        };
        MONITORINFOEX mONITORINFOEX = new MONITORINFOEX();
        if (GetMonitorInfo(monitor, mONITORINFOEX))
        {
            screen.Bounds = checked(new Rectangle(mONITORINFOEX.rcMonitor.Left, mONITORINFOEX.rcMonitor.Top, mONITORINFOEX.rcMonitor.Right - mONITORINFOEX.rcMonitor.Left, mONITORINFOEX.rcMonitor.Bottom - mONITORINFOEX.rcMonitor.Top));
            screen.Device = new string(mONITORINFOEX.szDevice);
            screen.DeviceIndex = index++;
            screen.Flag = mONITORINFOEX.dwFlags;
        }
        screen.Device = screen.Device.Substring(0, screen.Device.IndexOf('\0'));
        screens.Add(screen);
        return true;
    }
}
`

in wpf application:
`
public MainWindow()
{
    InitializeComponent();
    List<ScreenUtil.Screen> list = ScreenUtil.Screens;
}
`

in C# console application:
`
static void Main(string[] args)
{
    List<ScreenUtil.Screen> list = ScreenUtil.Screens;
}
`

**Comment by ryalanms** [comment]
@zou-z:  One is likely not DPI aware.  WPF apps are system aware by default.
