### ISSUE TITLE
Replace helper functions through patternmatching

### ISSUE THREAD

**Issue by IAmTheCShark** [dotnet/wpf#4936]
UIElement has the following helper functions
![image](https://user-images.githubusercontent.com/20905599/127213529-7a089ea9-e817-4b56-b842-d0c870ba5944.png)
that are used in a lot of places where they can easily be replaced by `is` pattern matching.

For example `CommandManager.FindCommandBinding` which is under heavy load in large applications should benefit from this.

![image](https://user-images.githubusercontent.com/20905599/127214395-1f99da4b-8174-42ed-90bc-71fe96da955e.png)

A quick test i threw together shoes how much faster this would be.

<html>
<body>

Method | o | Mean | Error | StdDev
-- | -- | -- | -- | --
IsInstanceOfType | ? | 2.6260 ns | 0.0040 ns | 0.0033 ns
IsExpression | ? | 0.2219 ns | 0.0038 ns | 0.0034 ns
IsInstanceOfType |   | 4.0874 ns | 0.0051 ns | 0.0042 ns
IsExpression |   | 0.3285 ns | 0.0010 ns | 0.0010 ns
IsInstanceOfType | 1 | 8.4281 ns | 0.0335 ns | 0.0297 ns
IsExpression | 1 | 0.3286 ns | 0.0013 ns | 0.0011 ns

</body>
</html>

**Comment by lindexi** [comment]
@IAmTheCShark I hope to see this optimization.

**Comment by dipeshmsft** [comment]
Closing this issue as the PR for the same is merged.
