### ISSUE TITLE
Should automatic core dump via environment variables work for WPF core?

### ISSUE THREAD

**Issue by dbruning** [dotnet/wpf#4940]
[This document](https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/xplat-minidump-generation.md) discusses minidump creation on multiple platforms, and seems to imply that it should work on Windows. 
It should be possible to set environment variables such as `COMPlus_DbgEnableMiniDump` to cause the runtime to write a minidump when the application crashes.
I tried setting those variables, then running my WPF app and causing an unhandled exception. I couldn't find a minidump.

- Should this work on Windows?
- Where should the minidump be written?

**Comment by lindexi** [comment]
@dbruning  How about https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump

**Comment by dbruning** [comment]
@lindexi Thanks, but I was specifically wondering about the environment variable method.

**Comment by dbruning** [comment]
On further investigation, I can confirm that this mechanism does work properly for WPF apps targeting NET5.0
Initially I wasn't getting dumps because the application was hooking UnhandledExceptions, handling them, and then shutting down normally. I was able to test the minidump creation using Environment.FailFast()
