### ISSUE TITLE
High GPU usage

### ISSUE THREAD

**Issue by Symbai** [dotnet/wpf#4942]
For **some** people my application uses like 20-40% of GPU usage when its visible while the same application works pretty fine for me and all others. When minimized to taskbar it goes down to 0%. I cannot reproduce the problem on my end. These people have extremely strong graphic cards like Nvidia 3080. The questions are:

1. What can this be?
2. How can I measure what exactly uses how much GPU?

Especially the second question is important. I found zero information about this on my research. We have tools to measure CPU usage, memory usage but nothing for GPU. The application is pretty normal, there aren't huge graphics or diagrams etc.

**Comment by lindexi** [comment]
@Symbai We can use VisualStudio to measure the GPU, see https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-use-the-gpu-threads-window?view=vs-2019

**Comment by Symbai** [comment]
Yes but this isn't helpful because I still have no idea which WPF control or data is using how much GPU. The inbuilt feature you are referring to is rather for low level native applications which have full control over their own rendering threads etc.

**Comment by singhashish-wpf** [comment]
GPU is a resource shared by all graphics apps; the usage can't be conveniently traced to a specific control. Use the Visual Studio to measure the GPU.

**Comment by Symbai** [comment]
@singhashish-wpf Why are you closing this? The issue that some people have high GPU usage (you can see it in task manager that the WPF app only uses 20-40% of the GPU) and others don't isn't solved. And its exactly the same application.

**Comment by acemod13** [comment]
@Symbai , is your WPF app doing something GPU intensive?

**Comment by Symbai** [comment]
No it does not, that's the problem. I don't know what you mean with "elaborate". Like I said in first post, the app runs fine on most computers but some customers report high GPU usage (20-40%) when the app is visible but idle. They have strong graphic cards. I don't know what else to say because WPF/.NET does not provide any way to debug/log the GPU usage. Unlike CPU or memory.

**Comment by Symbai** [comment]
@singhashish-wpf @FirehawkV21 Can I get an answer please why this issue is closed? Or should I create a new one? Because the issue with high GPU usage for some customers still exist. Telling me to use VS to measure it is not helpful at all, I and the customers can see the GPU usage via taskmanager.
