### ISSUE TITLE
[6.0.100-preview.7.21375.4] Abstract.DataStructures.Algorithms app unable to Kruskal items correctly

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/wpf#4954]
**Application Name**: Abstract.DataStructures.Algorithms
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number**: dotnet-sdk-6.0.100-preview.7.21375.4

**App and Source code checking at** : https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1360769
**Github Repo link**: https://github.com/mfe-/Abstract.DataStructures.Algorithms

**Verification Scenarios:**
Windows10 RS5 x64 + dotnet 3.1.117-servicing-015334: Pass
Windows10 RS5 x64 + dotnet-sdk-5.0.302-servicing.21316.24: Pass
Windows10 RS5 x64 + dotnet-sdk-6.0.100-preview.7.21320.2: Pass
Windows10 RS5 x64 + dotnet-sdk-6.0.100-preview.7.21375.4: Fail
Windows10 RS5 x64 + dotnet-sdk-6.0.100-rc.1.21370.2: Fail

**Repro steps**:
**This is 3.0 app, but we are running it on 6.0, machine only have 6.0 installed, and DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2, so it runs on 6.0.**

1. Copy Abstract.DataStructures.Algorithms to local machine.
2. Launch DataStructures.UI.Demo.exe.
3. Click on the blank area, press Ctrl + O.
4. Select Abstract.DataStructures.Algorithms\dijkstra.xml file and press Enter to open it.
5. Click the third point.
6. Right-click the third point.
7. Click Kruskal menu item.

**Expected Result**:
The graphics will be changed like below screenshot.
![expected result](https://user-images.githubusercontent.com/83067197/126971249-0c004c13-a435-4e64-b3d8-2559918f72ef.png)

**Actual Result**:
The graphics doesn't change after clicking Kruskal item.
![actual result](https://user-images.githubusercontent.com/83067197/126971299-b7ebe6ac-b549-4899-9e68-704c98308a72.png)

**Issue Description**:

**This is 3.0 app, but we are running it on 6.0, machine only have 6.0 installed, and DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2, so it runs on 6.0. It works fine when running on default runtime.**
Below is the dotnet info on the machine:
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21375.4
 Commit:    0556673673

**Runtime Environment**:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21375.4\

**Host (useful for support)**:
  Version: 6.0.0-preview.7.21373.17
  Commit:  46b249d7a1

**.NET SDKs installed**:
  6.0.100-preview.7.21375.4 [C:\Program Files\dotnet\sdk]

**.NET runtimes installed**:
  Microsoft.AspNetCore.App 6.0.0-preview.7.21374.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21373.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21374.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Additional Information:**
The source code from github: https://github.com/mfe-/Abstract.DataStructures.Algorithms, which has upgraded to .NET 5.0, but it also has the same issue when running on .NET 6.0

@dotnet-actwx-bot @dotnet/compat

**Comment by jeffschwMSFT** [comment]
Thanks @weltkante it is wpf.

**Comment by ryalanms** [comment]
This should be fixed with https://github.com/dotnet/runtime/pull/54899.

**Comment by Junjun-zhao** [comment]
@ryalanms  Thanks for your update. We verified it on latest build. It is still repro.
Windows10 RS5 x64 + dotnet-sdk-6.0.100-rc.2.21454.3: Fail

**Comment by ryalanms** [comment]
I believe the final decision was to fix the test application code.  

/cc @stephentoub

**Comment by PriyaPurkayastha** [comment]
Thanks @ryalanms and cc @marklio 
Can you please share the details on the decision? I am not seeing a discussion on this issue or the PR that you linked above.

**Comment by stephentoub** [comment]
> Can you please share the details on the decision? I am not seeing a discussion on this issue or the PR that you linked above.

@PriyaPurkayastha, I forwarded you an email thread (though you're already on it).

**Comment by stephentoub** [comment]
I opened https://github.com/mfe-/DataStructures.Algorithms/pull/15 with a fix.  Code should not be relying on the implementation detail of what exact object a SyncRoot is returning or expecting it to provide the contents of the collection it's being used to synchronize.

**Comment by Junjun-zhao** [comment]
Thanks @stephentoub . Closing this issue because Fix has been submitted for the application.
