### ISSUE TITLE
I have a problem with  a Wpf Appdev 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#4974]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/I-have-a-problem-with--a-Wpf-Appdev/1491611)._

---
hi,
    I write a ListBox in WPF App, But the Render is Abnormal,this issue only can be reproduced on NVIDIA Card, Please Check the Files,Would you please check it? thank you.

OS Name         Microsoft Windows 10 Pro
     Version            10.0.19043 Build 19043
     NVIDIA             Version 456.71 GeForce RTX 2080 TI

---
#### Feedback Bot on 8/2/2021, 01:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinshiyx1989** [comment]
My Apps run Abnormally at NVIDIA Cards, too

**Comment by singhashish-wpf** [comment]
Could you please check issue #707 and inform if it applies to your problem?
Also, the video attached is illegible, if you could please attach a clear video, it will be helpful.
