### ISSUE TITLE
Publish LocBaml source

### ISSUE THREAD

**Issue by mairaw** [dotnet/wpf#498]
The .NET documentation contains links to the LocBaml sample which is no longer available since the old samples site was decommissioned: https://go.microsoft.com/fwlink/?LinkID=160016 

It would be great if we could restore those links and have the source available for customers to download again.

If you look at our tracking docs issue, you'll see we already closed quite a few duplicate issues of that same request, so there's definitively a demand:
https://github.com/dotnet/docs/issues/3623

**Comment by stevenbrix** [comment]
Agreed! I would love to open-source tools like this. 

@karelz, i feel like we should have a separate repo for any wpf related tools that we want to publish. Does that sound like a good idea?

**Comment by vatsan-madhavan** [comment]
We have a samples repo that we can use for some of these. 

We have tools that have close dependencies on product sources and sometimes even build along with the product sources - or need to kept in sync with product sources (eg BamlReflector, wpfx.dll)

Other tools are an integral part of our tests and were primarily invented as part of that infrastructure, and will continue to live with the test repo. They will naturally get open sourced with our tests. 

A separate repo isn’t always a good way to build all of them, but we should think about how these tools are likely to be consumed and publish them in a way that’s easy to ingest by users (like a nuget package, for eg)

**Comment by mairaw** [comment]
There are also a couple of other samples that we used to link to before that I can't find on https://github.com/Microsoft/WPF-Samples. I'll compile the list to share with you later as well.

**Comment by mairaw** [comment]
We also have this published on the samples repo which customers said it wasn't the source we used to publish: https://github.com/Microsoft/WPF-Samples/tree/master/Globalization%20and%20Localization/BAML%20Loc/LocApp

They said this one looks more like it: https://github.com/JeremyDurnell/locbaml

**Comment by weltkante** [comment]
The first link (https://github.com/Microsoft/WPF-Samples/tree/master/Globalization%20and%20Localization/BAML%20Loc/LocApp) makes no sense, its just a blank WPF project template with two text blocks added to the MainWindow.xaml. Even the readme.md (one folder up) has just placeholders

> %Sample% sample
>
> This sample shows how to use the %objective

Maybe it was intended as an example how to _use_ LocApp but as it is, its not even that.

**Comment by karelz** [comment]
Agreed with @vatsan-madhavan. In general I recommend as few repos as possible. In WPF case likely 2 as you have larger test assets in binary form - they should be in separate repo. Anything else - product, incl. tools for product, incl. potentially some test infra tools should be in main repo IMO.

**Comment by mairaw** [comment]
@weltkante I think the empty %Sample% sample is probably a bug in the migration from our old platform to GitHub. I think they used a template to do the migration and some titles and objectives got lost.

I've been adding titles such as in this PR https://github.com/Microsoft/WPF-Samples/pull/78 when I get reports that we have broken sample link that is still going to the old platform and I'm trying to find the replacement on wpf-samples.

**Comment by vatsan-madhavan** [comment]
@mairaw & @weltkante, we are open-sourcing LocBaml here: https://github.com/Microsoft/WPF-Samples/pull/84 

/cc @ryalanms
