### ISSUE TITLE
Mouse messages go to non-activated when dragging/moving a WPF Window using WindowChrome

### ISSUE THREAD

**Issue by SamBent** [dotnet/wpf#4980]
**Problem description:**
While Dragging a WPF Window with WindowChrome enabled, Mouse messages may be sent to underlying Windows (using WindowChrome too).  In real-world app, this can lead to hangs or deadlocks.

[port of a servicing fix for .NET 4.7-4.8]

**Comment by batzen** [comment]
What about other custom chrome implementations (from ControlzEx for example)? Does the bug also affect those and if it does how can it be fixed there?

**Comment by SamBent** [comment]
Fix ported to 3.1.19, 5.0.10, 6.0.
