### ISSUE TITLE
A11y_.NETWPF_EditExaminerRich_Help_ScreenReader: Screen Reader is not reading explainatory text inside "Help" tab

### ISSUE THREAD

**Issue by v-navesingh** [dotnet/wpf#5035]
Check out Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier.

### **GitHubTags**
#A11ySev2;#A11yMAS;#A11yTCS;#A11yWCAG;#DesktopApp;#JAWS;#NVDA;#WCAG1.3.1;#DesktopApp;#Win10;#BM-.NetCore(WPF)-Win32-July2021;.NET Core;#InfoAndRelationship

### **Environment details:**
Application Name: .NET Core WPF
Microsoft .NET Core SDK Version 6.0.100-rc.1.21380.2
Windows Version: Windows10

### **Repro Steps**

1. Launch VS 2019 Int Preview
2. Tab and Navigate to Sample Applications and right click on the Editing Examiner Demo and click on build.
3..Then right click on Editing Examiner Demo then Click on Debug-->Start New Instance. 
4..Edit Examiner screen should open.
5.Tab on Help tab.
6. Turn on NVDA and check whether information written inside "Help" box are announced by screen reader or not?

### **Actual Result:**
Screen Reader is not reading explainatory text inside "Help" tab.

### **Expected result:**
Screen Reader should read explainatory text inside "Help" tab

### **User Impact**:
Low Vision users may find difficulty in understanding the content inside help tab.

**Comment by anjalisheel-wpf** [comment]
@v-navesingh Narrator is reading text inside help, try using shortcuts - CAPS + W and CAPS + C.  CAPS + W will take that window into focus and CAPS + C will focus the section, then try navigating using TAB.
