### ISSUE TITLE
re-examine internal use of ZLib

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/wpf#505]
right now we copy code from corefx to enable use of clrcompression.dll. this isn't sustainable, as any changes there cause us to break, and then we need to make the changes here.

We either need to expose a new API from S.IO.Compression or remove our dependency entirely

**Comment by jespersh** [comment]
Out of curiosity. What is zlib used for in Wpf? I would assume the zlib usage is in the non-released source

**Comment by weltkante** [comment]
@jespersh [System.IO.Packaging](https://docs.microsoft.com/en-us/dotnet/api/system.io.packaging), according to the notes at the bottom it is the base for XPS printing support. You can find it on [reference source](https://referencesource.microsoft.com/#WindowsBase/Base/System/IO/Packaging/ZipPackage.cs).

**Comment by rladuca** [comment]
@miguep FYI
