### ISSUE TITLE
[A11Y] Editable ComboBox flagged with 'Name property of a focusable element must not be null'

### ISSUE THREAD

**Issue by cprivera** [dotnet/wpf#5053]
Configuration:
* .NET 6.0.100-preview.3.21202.5
* Windows 10

 **Problem description:** An editable ComboBox will get flagged for a "Name property of a focusable element must not be null" error in Accessibility Insights for Windows despite having AutomationProperties.Name property set.
 
 **Actual behavior:** ComboBox with IsEditable property set to true and AutomationProperties.Name property set will have an error flagged for a null element Name on an inner 'edit' control.
<img width="1078" alt="08-10-2021 (1)" src="https://user-images.githubusercontent.com/25541708/128930876-9d4292d2-09fe-4d43-b39c-a8868d7e742e.png">
<img width="640" alt="08-10-2021 (2)" src="https://user-images.githubusercontent.com/25541708/128930888-d0b05953-566f-49db-be2f-905c02a6b004.png">
 
 **Expected behavior:** If the ComboBox has AutomationProperties.Name set, any contained edit control should inherit the name of the containing ComboBox.
 
 **Minimal repro:** Create a ComboBox with IsEditable set to TRUE, set the AutomationProperties.Name property to an appropriate name, run Accessibility Insights for Windows.

**Comment by anjalisheel-wpf** [comment]
@cprivera @vishalmsft 

I created a sample app to look into this issue. I set AutomationProperties.Name property to some value and then tested it, it showed me the value I set on Accessibility Insight for Windows, refer screenshot attached.
<img width="854" alt="Img2" src="https://user-images.githubusercontent.com/85492722/129030664-aa09796c-879a-469c-bce2-07b18bde064b.png">

Later I tried 2 scenarios - (1.) Setting empty value as AutomationProperties.Name property. (2.) Not setting any value to AutomationProperties.Name property. 
In both of the cases I empty values on Accessibility Insight for Windows, refer screenshot attached.
<img width="852" alt="Img1" src="https://user-images.githubusercontent.com/85492722/129031089-578e1242-cb58-44e2-8317-d32fdaa7d0f8.png">

Could you please provide some sample app so as to get better insight for the issue.

**Comment by anjalisheel-wpf** [comment]
@cprivera

I created a sample app to look into this issue. I set AutomationProperties.Name property to some value and then tested it, it showed me the value I set on Accessibility Insight for Windows, refer screenshot attached.

<img width="854" alt="Img2" src="https://user-images.githubusercontent.com/85492722/129033488-80373b9c-460f-41ae-9165-ce22d4e1f77e.png">

Later I tried 2 scenarios - (1.) Setting empty value as AutomationProperties.Name property. (2.) Not setting any value to AutomationProperties.Name property.
In both of the cases I empty values on Accessibility Insight for Windows, refer screenshot attached.

<img width="852" alt="Img1" src="https://user-images.githubusercontent.com/85492722/129033561-b66365e4-97ea-4d4a-872a-c899b684454a.png">


Could you please provide some sample app so as to get better insight for the issue.

**Comment by cprivera** [comment]
Apologies, I forgot to mention the ComboBox contains a DataTemplate with a TextBlock inside which performs some databinding for the text, which ends up being either something the user typed or their selection from the drop down. I made a simple app with the ComboBox and included a DataTemplate and a TextBlock without databinding, without the AutomationProperties.Name property set and I'm getting an error on both the ComboBox (expected) and the inner edit control (current issue).
<img width="1014" alt="08-11-2021" src="https://user-images.githubusercontent.com/25541708/129099378-4e10fcb0-8ee1-402a-9ca2-58bdd48fe13c.png">

**Comment by anjalisheel-wpf** [comment]
@cprivera It would be extremely helpful if you can share the sample app which you are using for the testing purpose.

**Comment by anjalisheel-wpf** [comment]
@cprivera I used your sample code to reproduce the issue, I am not getting any error at all if I am not setting name.

Refer screenshot for the same : 
<img width="882" alt="Img1" src="https://user-images.githubusercontent.com/85492722/129559343-d95c7118-16a3-4729-b0c4-88bc2a0f28c4.png">

If I am setting name using AutomationProperties.Name="Abc" then I am able to see the name.

Refer screenshot for the same : 
<img width="934" alt="Img2" src="https://user-images.githubusercontent.com/85492722/129559443-8f70de9e-549a-4f7a-b218-41ec47c286ba.png">

I can see that your **Accessibility Insight's** version is 1.1.1678.1 (Prerelease build), I am using version : 1.1.1663.01.

I suspect this could be Accessibility Insight team issue, please report to them. Thanks.

**Comment by cprivera** [comment]
@anjalisheel-wpf I had originally contacted Accessibility Insights about this error thinking it was perhaps a false positive from their application but they didn't agree. I ran AI again on the three different builds they have out currently (Canary, Insider, and Production) and on all three I was still seeing this error. In the following screenshots you can see I switched to your version (1.1.1663.1) and the production version. 
<img width="1023" alt="08-16-2021" src="https://user-images.githubusercontent.com/25541708/129625004-7b0efc28-5cfa-4fd3-a7c3-c8d76009b324.png">
<img width="1019" alt="08-16-2021 (2)" src="https://user-images.githubusercontent.com/25541708/129625063-1f16171e-f10d-488c-a9c6-eb0465c04245.png">

Could it be possible if the build of the sample app were different that could affect the result? I also noticed you ran AI on just the element whereas I've run it on the whole app, perhaps that could be the discrepancy here? I have tried running AI on just the element and I still see the error. I'm not sure what could be going on here, I think at the least you should also be getting an error on the ComboBox itself for not having an AutomationProperties.Name set, it's a common error I've gotten with any focusable element so I'm confused why that isn't getting flagged.

I will follow up with Accessibility Insights again to see what they think given these new developments, and I'd ask this issue not be closed yet until we can determine the cause. Thanks for your time on this!

**Comment by anjalisheel-wpf** [comment]
@cprivera I tested it on other machine as well it is not giving any error, same behaviour.

Moreover you defined **Expected behavior: If the ComboBox has AutomationProperties.Name set, any contained edit control should inherit the name of the containing ComboBox.**

I have attached screenshots that if I am setting AutomationProperties.Name then it is taking that value and if I am not setting AutomationProperties.Name then it is not giving null.
