### ISSUE TITLE
Can WPF projects run on CentOS or Ubuntu?

### ISSUE THREAD

**Issue by dafeifei0218** [dotnet/wpf#5056]
Can WPF projects created with c# in. Net framework 4.6.2 or. Net 5 run on CentOS or Ubuntu?
If yes, which packages need to be installed or what commands need to be executed? Any examples?

**Comment by vishalmsft** [comment]
@dafeifei0218 WPF (Windows Presentation Foundation) isn't supported for CentOS or Ubuntu.

**Comment by dafeifei0218** [comment]
@vishalmsft Avalonia, Electron and GTKSharp all need to rewrite the code?
