### ISSUE TITLE
Setting EnableAnalyzers to true in .csproj doesn't pick up correct ruleset

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/wpf#506]
This was broken when the ruleset was moved to the Wpf Arcade SDK. Also, the changes to System.Xaml that were made were lost as well.

**Comment by vatsan-madhavan** [comment]
```XML
<CodeAnalysisRuleset Condition="'$(IsTestProject)'!='true' AND '$(EnableAnalyzers)'=='true'">$(MSBuildThisFileDirectory)CodeAnalysis\WpfCodeAnalysis.ruleset</CodeAnalysisRuleset>
```

That should be evaluated in a `.targets` file (for e.g., `CodeAnalysis.targets`) instead of being evaluated in [`CodeAnalysis.props`](https://github.com/dotnet/wpf/blob/e25cd6b620e1336b24d240e00d9d831225aee906/eng/WpfArcadeSdk/tools/CodeAnalysis.props#L4)
