### ISSUE TITLE
Auto generates many temp AssemblyInfo code files

### ISSUE THREAD

**Issue by Berrysoft** [dotnet/wpf#510]
* .NET Core Version: 3.0 Preview3
* Windows version: 10.0.18362
* Does the bug reproduce also in WPF for .NET Framework 4.8?: **Yes**

 
 
 **Problem description:**
Each time I build the project, a `AssemblyInfo` code file and a `AssemblyInfoInputs.cache` are generated.
 
 **Actual behavior:** 
![image](https://user-images.githubusercontent.com/37586447/55664642-bf89da80-5863-11e9-9b33-c6fcd06bd233.png)
![image](https://user-images.githubusercontent.com/37586447/55664644-d5979b00-5863-11e9-9016-ac6ff2e79fdc.png)
(The C# project is named `temp`)
 
 **Expected behavior:**
No these files.
 
 **Minimal repro:**
 ```
dotnet new wpf
dotnet run
dotnet run
dotnet run
```
Check the `obj\Debug\netcoreapp3.0` folder.

**Comment by ryalanms** [comment]
The temporary project generated by GenerateTemporaryTargetAssembly is deleted from obj\... after compilation, but the generated .cs and .cache files associated with the temporary project are not.  All files with the temporary project prefix can be deleted after compilation of the temp project.

**Comment by wjk** [comment]
In all honesty, it would be easier to just add some code to the WindowsDesktop SDK that disables generating the assembly info in the temp projects. I've done this for my SDK-style .NET Framework WPF projects, since long before .NET Core 3 was announced. Something like this should probably work:

```xml
<PropertyGroup>
  <GenerateAssemblyInfo Condition="'$(_TargetAssemblyProjectName)' != ''">false</GenerateAssemblyInfo>
</PropertyGroup>
```

**Comment by ryalanms** [comment]
@wjk: Yes, let's take whatever option is cleanest.  Thanks.

**Comment by weltkante** [comment]
Just make sure the Condition property (`_TargetAssemblyProjectName` if the suggestion is to be applied directly) is private to WPF and not a general purpose property which just happens to be only used by WPF in the builtin project types. Otherwise this fix could have unintended consequences for extensibility.
