### ISSUE TITLE
Error when creating and using user parameters (app.config) with .net 5 in VB.

### ISSUE THREAD

**Issue by Perpete** [dotnet/wpf#5129]
Hello,
By creating a first project with WPF in VB with .net 5 under the Visual Studio 16.11.1 version, I noticed a problem during the creation and use of user parameters in app.config.

When we add or modify parameters or values of these parameters and save the new information, we get the display of an error message. 

**Message :**
_'An error occurred while saving values to the app.config file. This file may be damaged or contains invalid XML code. '_

![2021-08-20 17_02_51-WpfApp5 - Microsoft Visual Studio](https://user-images.githubusercontent.com/66659162/130258542-18ecf2a6-1310-4fd1-a44b-dadedca6bf99.png)

When using a parameter reading using one of the following instructions 
_lbEssai.Content = My.MySettings.Default.Essai_ or _lbEssai.Content = My.Settings.Essai_,
I have an error in the Settings.Designer.vb file.

![2021-08-20 17_09_54-WpfApp5 (Débogage) - Microsoft Visual Studio](https://user-images.githubusercontent.com/66659162/130259218-ca114985-161c-45ec-9a94-868a0f3b61fe.png)

Here are the details of the error.

![2021-08-20 17_47_15-_D__Documents_Visual Studio 2019_Projects_IOCenterOPC_DLL_IOCenterOPC_DLL sln - ](https://user-images.githubusercontent.com/66659162/130259452-7e86ee83-630d-49b6-9442-ad03f931b792.png)

Here is just my test program.

`Class MainWindow

	Private Sub Button_Click(sender As Object, e As RoutedEventArgs)

		lbEssai.Content = My.MySettings.Default.Essai

		lbEssai.Content = My.Settings.Essai

	End Sub

End Class`

The same program in C # works fine.

What is the solution in VB?

**Comment by Perpete** [comment]
Hello,
In the App.config file, I deleted all the contents of the 'system.diagnostics' tag.
I no longer have an error detected in the Settings.Designer.vb file when reading the setting.
The reading of the parameter value is correct.

![2021-08-20 19_27_58-WpfApp5 - Microsoft Visual Studio](https://user-images.githubusercontent.com/66659162/130271834-450af7cf-0063-4c0c-94ef-07bf7ccb8604.png)

On the other hand, from the parameter data grid, there is always the display of the error message when adding or modifying the parameters or the values of these parameters when saving the new information.

**Comment by ThomasGoulet73** [comment]
This is not really a WPF bug. I would say that it's a bug with the default content of App.config in Visual Studio. If you create a new Console VB.Net project and add an App.config file from the template, you'll get the invalid system.diagnostic section.

**Comment by Perpete** [comment]
Hello ThomasGoulet73,
You are right, i also try it with WinForms in Vb and it is exactly the same problem.

I added my comment to the problem:
Updating the Default Settings file in a WinForms .NET 5 Visual Basic app fails. # 6784 in dotnet / project-system.
