### ISSUE TITLE
MouseGesture not getting called correctly when being added to InputGestureCollection

### ISSUE THREAD

**Issue by SetTrend** [dotnet/wpf#5141]
### Problem description:

Having created a custom command like this:

```c#
public static RoutedUICommand ZoomIn { get; } = new RoutedUICommand("Zoom in", "ZoomIn", typeof(CustomCommands), new InputGestureCollection() { new KeyGesture(Key.OemPlus, ModifierKeys.Control), new MouseWheelGesture(WheelDirection.Down, ModifierKeys.Control) });
```

And having written a `MouseWheelGesture` like described here:
https://stackoverflow.com/questions/2271342/mousebinding-the-mousewheel-to-zoom-in-wpf-and-mvvm#answer-7527482

The `MouseWheelGesture.Matches()` method is not getting called when the mouse wheel is rotated while the <kbd>CTRL</kbd> key is getting pressed.

### Actual behavior:

The `MouseWheelGesture.Matches()` method is getting called for the <kbd>CTRL</kbd> key is being pressed, but not for the mouse wheel being rotated.

![MouseGesture not triggered](https://user-images.githubusercontent.com/9283914/130356654-6118fd82-daf8-451a-b620-b4983dd95911.gif)

### Expected behavior:

The `MouseWheelGesture.Matches()` method should be getting called when the mouse wheel being rotated with a `MouseWheelEventArgs` event argument.

---

* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
```
.NET SDK (gemäß "global.json"):
 Version:   5.0.400
 Commit:    d61950f9bf

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  3.1.412 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
* Windows version: (`winver`)

```
21H1 Build 19043.1165
```

**Comment by singhashish-wpf** [comment]
@SetTrend Please attach your sample app where you are able to reproduce the issue.

**Comment by SetTrend** [comment]
Did anyone have the time to investigate on this issue?

**Comment by SetTrend** [comment]
Did anyone have the time to investigate on this issue?

**Comment by h3xds1nz** [comment]
@SetTrend

1) You're calling `base.Matches` first, but your override initializes with `MouseAction.None`, on which the base (`MouseGesture`) call will always return false.

Therefore we have two solutions:
1) Initialize with `MouseAction.WheelClick` instead of `MouseAction.None`, then your code works out of the box.
2) Stop using the base check and check yourself for Modifiers flags (using `Keyboard.Modifiers` as source of truth, which is what `MouseGesture` does) + that the event is `MouseWheelEventArgs`.

**Comment by SetTrend** [comment]
Excellent answer! Thanks a lot for enlightening me!

**Comment by h3xds1nz** [comment]
Welcome, only took 3 years to figure this one out, right  😄
