### ISSUE TITLE
WrapPanel incorrect ActualWidth/Height values

### ISSUE THREAD

**Issue by A-tG** [dotnet/wpf#5142]
* .NET 5.0.400
* Windows version: Windows 10 20H2
* Did't checked on netframework
 
Reading ActualWidth/ActualHeight or RenderSize of WrapPanel with wrapped child elements return values like its not wrapped.
In other words if we have 2 child elements with size 50x50 on the first line and 1 element with size 40x40 on the second line then ActualWidth will return 140 and ActualHeight will return 50.
And expected behavior: ActualWidth == 100, ActualHeight == 90

**Comment by singhashish-wpf** [comment]
The actual width is dependent upon multiple other factors (For eg: Size of the Panel). This is by design.
