### ISSUE TITLE
Visibility Hidden or Collapsed of elements in design mode for WPF

### ISSUE THREAD

**Issue by Perpete** [dotnet/wpf#5188]
Hello,
Currently, when the visibility property of a window or elements in WPF is hidden or collapsed, the window or elements no longer display in the window in design mode.
This poses a problem when it is necessary to find the elements in order to modify them.

The problem would be similar if the hide or collapse elements would remain visible on the window in design mode.
It would be necessary to find the elements covered in order to modify them.

To solve these problems, wouldn't it be interesting:
• Add a button that would allow you to view or hide elements whose Visibility property is Hidden or Collapsed?
• Add a graphic sign to these elements made visible in edit mode?

Visible elements
![2021-08-31 06_16_52-Corel PaintShop Pro 2021 - Image3](https://user-images.githubusercontent.com/66659162/131442187-b1247e2b-627b-49f6-8cb3-a32f323fb449.png)

Invisible elements
![2021-08-31 06_30_03-Corel PaintShop Pro 2021 - Image4](https://user-images.githubusercontent.com/66659162/131442218-ecaecfcb-335a-431f-b4ed-b5ff0df512e3.png)

**Comment by SamBent** [comment]
@Perpete - The designer is part of Visual Studio.  Please submit designer feature requests through https://developercommunity.visualstudio.com
