### ISSUE TITLE
TextBox not show info when set Property is Name

### ISSUE THREAD

**Issue by chuongmep** [dotnet/wpf#5191]
* .NET Core Version: 3.0
* Windows version: 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? If yes, please file the issue via the instructions [here](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/master/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**
Dear Team, 
I see a problem with set name property with Name in NetCore3.0, wheather any conflic from that ? It not show correct info in UI.
May be we need quick check.

![image](https://user-images.githubusercontent.com/31106432/131002579-0616e804-76d2-458f-98da-89f9c42ce79a.png)

 Source Demo : https://github.com/chuongmep/WPF_Bug

**Comment by singhashish-wpf** [comment]
@chuongmep Source Demo : https://github.com/chuongmep/WPF_Bug This code is 404 not found. Could you please check and update the link?

**Comment by chuongmep** [comment]
Updated

**Comment by miloush** [comment]
There are at least 3 errors in the code, each of which prevents this from working:

1. You are implementing `INotifyPropertyChanging` instead of `INotifyPropertyChanged`.
2. Your `OnPropertyChange` method is firing the event args with `nameof(propName)` instead of `propName`.
3. There is a dependency property of the same name on the object, which takes precedence. Therefore as @ThomasGoulet73 pointed out, your `Name` setter is never called. Easiest solution is to use different property than `Name`.

**Comment by chuongmep** [comment]
> There are at least 3 errors in the code, each of which prevents this from working:
> 
> 1. You are implementing `INotifyPropertyChanging` instead of `INotifyPropertyChanged`.
> 2. Your `OnPropertyChange` method is firing the event args with `nameof(propName)` instead of `propName`.
> 3. There is a dependency property of the same name on the object, which takes precedence. Therefore as @ThomasGoulet73 pointed out, your `Name` setter is never called. The easiest solution is to use different property than `Name`.
> 
> I don't see any bug in WPF.

Yes, it not a bug, may be a feature should upgrade with Name

**Comment by miloush** [comment]
The [`Name`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.name?view=windowsdesktop-6.0) property already exists and you are in conflict with it (as already hinted by the squiggles in Visual Studio). Therefore as for the feature request, let's just say that unfortunately removing an existing property would be a breaking change.

Like others suggested, create your own class where you can use any properties you like.

**Comment by vishalmsft** [comment]
@chuongmep This isn't a bug. Please consider taking the suggestion on ViewModel or Renaming the property. 
I hope, the issue can be closed as @miloush  and @ThomasGoulet73  have provided you the required answers. 

Thanks

**Comment by chuongmep** [comment]
Thanks you all, i will close topic this and use class as a solution.
