### ISSUE TITLE
[Source Compat Failure][6.0.100-rc.1.21425.10] ControlzEx Failed to build with Nullability of reference types error when retarget to .NET 6.0

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/wpf#5221]
**Application Name**: ControlzEx
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number**: 6.0.100-rc.1.21425.10

 
**Verify Scenarios:**
1) Windows 10 RS5 X64 + dotnet-sdk-5.0.401-win-x64 PASS
2) Windows 10 RS5 X64 + dotnet-sdk-6.0.100-preview.6.21322.2 PASS
3) Windows 19H1+dotnet-sdk-6.0.100-rc.1.21424.13: Fail
4) Windows 10 RS5 X64+dotnet-sdk-6.0.100-rc.1.21425.10: Fail

**App Source checking at** : https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1388731 

**Repro steps**:

This is a net5 app, issue occurs when re-target it to .NET 6.0 rc1 build.

1)Copy AppSource to machine :
2) Change "net5.0-windows" to "net6.0-windows" in Directory.Build.props.
3) Run dotnet build

**Expected Result:**

No Error

**Actual Result**:

There is an error.

Error :
```
D:\ControlzExSource\src\ControlzEx\Behaviors\GlowWindowBehavior.cs(125,46): error CS8622: Nullability of reference types in type of parameter 'o' of 'void GlowWindowBehavior.AssociatedObjectOnClosing(object o, CancelEventArgs args)' doesn't match the target delegate 'CancelEventHandler' (possibly because of nullability attributes). [D:\ControlzExSource\src\ControlzEx\ControlzEx_sy4g1miv_wpftmp.csproj]
D:\ControlzExSource\src\ControlzEx\Behaviors\GlowWindowBehavior.cs(288,50): error CS8622: Nullability of reference types in type of parameter 'o' of 'void GlowWindowBehavior.AssociatedObjectOnClosing(object o, CancelEventArgs args)' doesn't match the target delegate 'CancelEventHandler' (possibly because of nullability attributes). [D:\ControlzExSource\src\ControlzEx\ControlzEx_sy4g1miv_wpftmp.csproj]
```
**Findings** :

**Exception in GlowWindowBehavior.cs(line:125)**
```
this.AssociatedObject.Closing -= this.AssociatedObjectOnClosing;

....

private void AssociatedObjectOnClosing(object o, CancelEventArgs args)
        {
            if (!args.Cancel)
            {
                this.AssociatedObject.IsVisibleChanged -= this.AssociatedObjectIsVisibleChanged;
            }
        }

delegate is given System.ComponentModel.CancelEventHandler(line:8)
public delegate void CancelEventHandler(object sender, CancelEventArgs e);

```
**If we change the parameter of AssociatedObjectOnClosing to nullable, we can successfully build.
(This change is not required for versions before 6.0.100-preview.6.21322.2 .)**

```
private void AssociatedObjectOnClosing(object? o, CancelEventArgs args)
        {
            if (!args.Cancel)
            {
                this.AssociatedObject.IsVisibleChanged -= this.AssociatedObjectIsVisibleChanged;
            }
        }
```
**This change is not required for versions before 6.0.100-preview.6.21322.2 .**

@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
Because we in .NET 6 Validation Window, can you please check this bug ASAP and help confirm whether it  is a blocker for RC1? Thanks a lot.

**Comment by ThomasGoulet73** [comment]
Hey @Junjun-zhao,

This does not look like a WPF problem because CancelEventArgs does not seem to be owned by the WPF team. It exists in System.ComponentModel.TypeConverter, in dotnet/runtime. CancelEventArgs was newly annotated for nullability in .Net 6 in this PR: https://github.com/dotnet/runtime/pull/54961.

I would recommend opening an issue to ask them to annotate [this method](https://github.com/ControlzEx/ControlzEx/blob/develop/src/ControlzEx/Behaviors/GlowWindowBehavior.cs#L292) for the new nullability annotations in .Net 6.

Thank you

**Comment by Junjun-zhao** [comment]
@ThomasGoulet73 Thanks for your update. 
File a bug to track the issue in Runtime  https://github.com/dotnet/runtime/issues/58422.

**Comment by batzen** [comment]
Would have been way easier to redirect this to ControlzEx instead of runtime.
I just fixed the code in ControlzEx.

**Comment by batzen** [comment]
And thanks for running those tests and investigating the results.
We didn't have time yet to upgrade to .NET 6.0.
