### ISSUE TITLE
Use Roslyn v4.0 to build net6.0

### ISSUE THREAD

**Issue by eerhardt** [dotnet/wpf#5224]
See https://github.com/dotnet/wpf/pull/5208#issuecomment-908626848. Targeting `net6.0` is only supported using VS 2022, but the WPF repo is using VS 2019 in CI builds.

We should update the CI to use VS 2022 since targeting net6.0 requires using VS 2022.

Alternatively, we can update just the Roslyn version to ‘4.0’ while still using VS 2019.

cc @fabiant3 @ryalanms

**Comment by ryalanms** [comment]
The build pool machines are not under our control.  This is the schedule for machine updates:  https://github.com/dotnet/core-eng/wiki/VS2019-Upgrade-Schedule#vs2019-versions-table

@MattGal @mmitche :  Where should this bug be routed, and what action should be taken?

**Comment by ryalanms** [comment]
Apologies.  I see that the request is for us to update our .yaml file to target a different queue.

**Comment by MattGal** [comment]
@eerhardt  / @ryalanms 

Should be no problem to help out, but I need some details.
We have `buildpool.windows.amd64.vs2022.pre.open` today, but:

- This is public-only and I suspect you want internal as well, can you confirm?
- Does this need to be in the .xaml specific subscription for billing purposes (adds some complexity)

**Comment by ryalanms** [comment]
Yes, we need it both the public repo and the mirror.  It does not need to be the .xaml subscriptions.  Thanks.

**Comment by eerhardt** [comment]
Another potential way to fix this would be to use a v4.0 version of Roslyn to compile, like we do in dotnet/runtime:

https://github.com/dotnet/runtime/blob/e7765d9c13d83a09e6bf4e552842b33a9abb0fb5/eng/Versions.props#L20

https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Arcade.Sdk/tools/Settings.props#L23

https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Arcade.Sdk/tools/Compiler.props#L5

This would also fix the error that we ran into in the RC1 ingestion PR - https://github.com/dotnet/wpf/pull/5208#issuecomment-908626848

**Comment by MattGal** [comment]
@ryalanms if this suggest works, I highly recommend it since it's a lot of work to keep VS 2022 images functional, and maybe not ideal to build official products with until it's in GA.  If you still find yourself needing an internal pool e.g. `buildpool.windows.amd64.vs2022.pre`, let's chat.

**Comment by mmitche** [comment]
> @ryalanms if this suggestion works, I highly recommend it since it's a lot of work to keep VS 2022 images functional, and maybe not ideal to build official products with until it's in GA. If you still find yourself needing an internal pool e.g. `buildpool.windows.amd64.vs2022.pre`, let's chat.

Not only that, but we'll also require a regular rebuild of wpf-int if we take the new dependency.
