### ISSUE TITLE
Close, Minimize and Maximize buttons not working at simple WPF App on Windows 11 if window is not at full screen mode.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5230]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Close-Minimize-and-Maximize-buttons-not/1490454)._

---
[severity:It bothers me. A fix would be nice]
I am running Windows 11 (build 22000.100) with Visual Studio Community 2019 (Version 16.10.4).
I create an WPF App (.Net Framework 4.7.2) with no UIElement (blank window). When starting it, the Closing, Minimizing, and Maximizing Buttons are not working when the window is not in full screen mode. They do not change their colors when hovering with mouse over them.
By double clicking the title bar of the window the window maximized. After that, the three Buttons work well.
After maximizing and go back to normal mode (not full screen mode) the three buttons stops working again.
**This behavior exists only at Debug-Mode (Any-CPU and x64).** Then starting the WPF-App without Debugging the Buttons work well.

I add this report also as a _Windows 11 Inside_ report at https://aka.ms/AAdax5t

---
#### Feedback Bot on 7/29/2021, 10:47 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ryalanms** [comment]
I believe this is the issue with the VS toolbar overlapping the close/min/max buttons.
