### ISSUE TITLE
Using an SDK that comes from a PackageReference in a WPF application is broken

### ISSUE THREAD

**Issue by dotMorten** [dotnet/wpf#5239]
* .NET Core Version: 3.0preview 7 + 3.0rc1
* Windows version: Several Win10 versions and Win11 (ie doesn't matter)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? If yes, please file the issue via the instructions [here](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).
No? It is introduced with .NET 6 and/or VS2022 installer, but will even affect VS2019/.NET5 installs once installed
 
 **Problem description:**
Using an SDK that comes from a PackageReference (MSBuild.Sdk.Extras) in a WPF application is broken with WPF PackageReference support enabled. 
Setting `IncludePackageReferencesDuringMarkupCompilation` to `false` works around the issue (but comes with other downsides).
On a PC that only has VS2019 installed, the problem doesn't reproduce. If you install VS2022p3.1, the problem does reproduce, even from a VS2019 command prompt.
The problem seems to occur just by installing the .NET 6 SDK, and will break even .NET 5 and .NET Framework builds.

 **Actual behavior:** 
 > error MSB4236: The SDK 'MSBuild.Sdk.Extras/3.0.23' specified could not be found.

 **Expected behavior:**
 Build completes.

 **Minimal repro:**
From a VS2019 or VS2022 prompt run:
```
    git clone https://github.com/Esri/arcgis-toolkit-dotnet
    cd arcgis-toolkit-dotnet\src\Toolkit\Toolkit
    msbuild /restore /t:Build Esri.ArcGISRuntime.Toolkit.csproj
```

**Comment by dotMorten** [comment]
@ryalanms This is related to .NET 6.0. This is a showstopper as we have no way to build things and target .NET 6 now. Is there a reason this is scheduled for 7.0?

**Comment by ThomasGoulet73** [comment]
@dotMorten I just opened #5426 which fixes the build of arcgis-toolkit-dotnet for me. Could you try it and see if it fixes yours ?

I opened it in main (aka .Net 7) but maybe the WPF team would like to backport it to .Net 6.

**Comment by dotMorten** [comment]
@ThomasGoulet73 You're a rock star!
