### ISSUE TITLE
Why is WPF PathFigure not filled at certain rotations?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#524]
The arrow is supposed to have a red fill but the fill is missing at certain angles of the RotateTransform. It vanishes from ~92° to ~279°

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/519747/why-is-wpf-pathfigure-not-filled-at-certain-rotati.html
VSTS ticketId: 841039_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by grubioe** [comment]
Please provide more information on what version of .NET is being run and a sample app if possible.  Thanks.
