### ISSUE TITLE
FileNotFoundException after update to 16.10.3

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5256]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/FileNotFoundException-after-update-to-16/1464981)._

---
\[severity:It bothers me. A fix would be nice\] \[regression\] \[worked-in:16.10.2\] When building I'm getting this error: System.IO.FileNotFoundException HResult=0x80070002 Message=Could not load file or assembly '\_awdfvoho\_wpftmp, Culture=neutral' or one of its dependencies. The system cannot find the file specified. Source=mscorlib StackTrace: at System.Reflection.RuntimeAssembly.\_nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.Assembly.Load(AssemblyName assemblyRef) at System.Windows.Navigation.BaseUriHelper.GetLoadedAssembly(String assemblyName, String assemblyVersion, String assemblyKey) at MS.Internal.AppModel.ResourceContainer.GetResourceManagerWrapper(Uri uri, String& partName, Boolean& isContentFile) at MS.Internal.AppModel.ResourceContainer.GetPartCore(Uri uri) at System.IO.Packaging.Package.GetPartHelper(Uri partUri) at System.IO.Packaging.Package.GetPart(Uri partUri) at System.Windows.Application.GetResourceOrContentPart(Uri uri) at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator) at Emdat.InSync.App.InitializeComponent() in C:\\Users\\AlWerne\\Source\\Repos\\InSync\\InSync\\InSync\\App.xaml:line 1 at .App.Main() **Updated 7/6/2021 - This no longer fixes the issue and has broken again. Solution: 1. Close all instances of VS 2. Delete all file in the ComponentModelCache folder in C:\\Users\\\[username\]\\AppData\\Local\\Microsoft\\VisualStudio\\16.0\_XXXXX 3. Delete the .vs, bin and obj folders in your source folder 4. Rebuild project/solution

---
#### Feedback Bot on 7/1/2021, 11:06 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Joe Gallagher on 7/6/2021, 07:00 PM: 

<p>Same thing happens for me. Unable to start debugging a WPF project in Visual Studio after updating to this latest version, with the same error message on launch (“Could not load assembly”). Unfortunately the suggested work around did not work for me.</p>

#### Rodney Bates on 7/6/2021, 07:12 PM: 

<p>I updated my description because my workaround is no longer working.</p>

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Is this reproducible with the latest Visual Studio 2022 also?

**Comment by singhashish-wpf** [comment]
Closing in absence of reply and no minimal repro available.
