### ISSUE TITLE
Optional CAML instead of BAML in the name of AOT and performance 

### ISSUE THREAD

**Issue by JensNordenbro** [dotnet/wpf#5266]
Today when generating a UI in WPF with many components, BAML becomes a factor that decreases first time Window class(/other baml dependent component) initialization performance. 
Comparing first time screen open to similar screens using winforms produces a bleak picture although the subsequent rendering is fast! 

Back in the day, there was a thing called CAML according to https://stackoverflow.com/questions/1423728/why-xaml-is-compiled-into-baml-and-not-in-c-sharp. 
  - as described in the article this decision to prefer BAML was taken for reasons that might not apply fully today. 

I suggest to introduce a CAML generator as an optional source generator so that Ready2Run compilation can create huge performance benefits for Window-instances with 100:s of components.

**Comment by lindexi** [comment]
See https://github.com/kekekeks/XamlX

**Comment by lindexi** [comment]
A year ago, my friend told me that he would do it, but I haven't heard from him in the last year.

**Comment by JensNordenbro** [comment]
Hmmm... I tried to motivate this issue by simulate the CAML situation by creating objects in csharp code omitting the xaml hence baml. 

However performance was as bad as on BAML when running with R2R. 

Performance profiling says Layout is the problem. Not sure anymore if CAML is the solution. Maybe it would be good for AOT anyways but the performance aspect of it might not be there.
