### ISSUE TITLE
Could the current WPF code (for netfx) be made available under MIT?

### ISSUE THREAD

**Issue by poizan42** [dotnet/wpf#53]
Currently some parts of WPF are available at referencesource.microsoft.com and others have been made available in the past through the " .NET Framework source stepping" sources - I think only the C++/CLI parts haven't been made available at all. However these are all under MS-RSL which prevents reusing parts in your own projects.

Since everything is in the process of being added here with changes for .NET Core, could we have the current code added to the https://github.com/Microsoft/referencesource repository under MIT?

**Comment by rladuca** [comment]
Hey @poizan42 , if you take a look at our [roadmap](https://github.com/dotnet/wpf/blob/master/roadmap.md), we will be progressively open sourcing more WPF for .NET Core components throughout 2019 under the MIT license.

The code that is currently available on reference source is code from WPF for .NET Framework.  This will continue to be available as is.
