### ISSUE TITLE
What's about Microsoft.Expression.Drawing

### ISSUE THREAD

**Issue by freica** [dotnet/wpf#5301]
Wy is there no statement to this issue. This is not an "Enhancement", Microsoft.Expression.Drawing is an existing library over many years!
This library was killed.

_Originally posted by @freica in https://github.com/dotnet/wpf/issues/3097#issuecomment-918251936_

**Comment by michael-hawker** [comment]
@freica no need to open another issue when one already exists. This is a duplicate of #3097.
