### ISSUE TITLE
The roadmap is outdated

### ISSUE THREAD

**Issue by Symbai** [dotnet/wpf#5314]
Not only that 21H1 has passed, it also says you host WPF status report on WinUI Community calls. On last community call I've asked a question about the future of WPF and was told that "We here on WinUI have nothing to do with WPF, you should ask in WPF repo".

So what is the current roadmap and where do we get frequently informed about the status? Is there a replacement for the WinUI community calls? I think I'm not the only one who is interested into the future of WPF and what the team is currently working on.

**Comment by kronic** [comment]
Wpf is dead.

**Comment by Fabi** [comment]
> Wpf is dead.

If you consider the current state of MAUI and WinUI 3, WPF will live for a looong time.

**Comment by kronic** [comment]
@Fabi 
Wpf is dead in further product evolution

**Comment by noseratio** [comment]
I'm with @Fabi on this one. For the long foreseeable future, WPF will probably remain on low-maintenance life support (similar to that for .NET Framework 4.8), but it's time to start planning on porting those legacy LOB desktop apps to a new stack.

**Comment by kronic** [comment]
@noseratio tell the clients who are on Windows 7 about it

**Comment by noseratio** [comment]
@kronic, apologies I actually meant I'm with you on "WPF is dead"  - edited :)

> tell the clients who are on Windows 7 about it

I'd tell them: "All good things come to an end. Look at what's happing to IE11, let's put together a migration plan for WPF". 

It can also be convincing to talk about what specific Desktop UI technologies [Microsoft themselves use for their own products](https://dev.to/noseratio/the-signs-of-wpf-currently-being-on-life-support-1h3a#:~:text=the%20ui%20technologies%20microsoft%20use%20for%20their%20own%20mainstream%20projects), nowadays. It's only Visual Studio that uses WPF, but it's largely a brownfield project that had existed before WPF became a thing. Its UI is a set of components, some of them aren't WPF-based at all.

**Comment by lindexi** [comment]
But half of my customers are use Win7 now. 

And nearly half of Chinese are use win7. See the data from [baidu](https://tongji.baidu.com/research/site?hmsr=%E7%BB%9F%E8%AE%A1footer%E9%93%BE%E6%8E%A5&hmpl=footer&hmcu=footer&hmkw=&hmci=footer#os)

![](https://user-images.githubusercontent.com/16054566/135368149-7274a94f-3d7f-41ed-9b33-7af045297396.png)

It means give up win7 is give up the market.

**Comment by ryalanms** [comment]
Apologies for the delay here.  @predavid will follow-up with the most recent information.

**Comment by noseratio** [comment]
> But half of my customers are use Win7 now.
> 
> And nearly half of Chinese are use win7. See the data from [baidu](https://tongji.baidu.com/research/site?hmsr=%E7%BB%9F%E8%AE%A1footer%E9%93%BE%E6%8E%A5&hmpl=footer&hmcu=footer&hmkw=&hmci=footer#os)

@lindexi I'm not saying "port your WPF app to WinUI 3" is an ultimate solution. 

E.g., both Electron and WebView2 support Windows 7, and so probably does the upcoming BlazorDesktop (as long as .NET 6 still supports Windows 7).

**Comment by batzen** [comment]
I guess that highly depends on the market and China/Asia might be a totally different story than the US. Especially if half your userbase is still on an unsupported OS.
But, and that's more important, even upgrading to a supported OS like 8.1 wouldn't be enough for WinUI.
And things like Blazor are far, far away from being a proper replacement for WPF.

**Comment by predavid** [comment]
Folks -  the new roadmap is in the works. Stay tuned for an update in the near future.

**Comment by Symbai** [comment]
> near future

What is 'near' for you? Within 2021? And what about recurring community updates? Are they still placed on WinUI community updates? If not, if there is a replacement planned? Speaking with us helps us to understand what WPF team is thinking and helps you to understand what WPF developers are expecting. Remember a talkative marriage is a good marriage.

**Comment by noseratio** [comment]
@predavid:

 Hi Premalini, is the WPF team resource boost you [mentioned here](https://devblogs.microsoft.com/dotnet/whats-new-in-windows-forms-runtime-in-net-5-0/#comment-8274) still happening?

>Thank you for continuing to be active proponents of the WPF platform. The WPF team has been challenged with extremely limited dev resourcing for several months. With the limited resources on hand, we have been heads-down on getting support for .NET5 released and now are working on ARM64 support. However, the good news is that our team has now been approved for more new developer recruits to be on-boarded by the end of Jan/beginning of Feb 2021. Once they are onboarded, one of the first tasks we have lined up is open sourcing of our Test Infrastructure which in turn will get us going on more regular PR approvals and check-ins. In the meantime, please continue to send us your PRs and file Issues -all of which only aid in improving the platform for the community .We look forward to closer and active collaboration with the community in the New Year.

**Comment by juepiezhongren** [comment]
maui support wpf is a must

**Comment by Symbai** [comment]
New roadmap is there #5685, no trimming support, no AOT, no new features. Just maintenance... 🤦‍♂️👌

**Comment by noseratio** [comment]
> New roadmap is there #5685, no trimming support, no AOT, no new features. Just maintenance... 🤦‍♂️👌

Basically:

> "Incorporating .NET Framework servicing fixes into .NET Core 3.1, .NET 5 and .NET 6". 

It looks like the current WPF maintenance efforts are driven by .NET Framework 4.8.x, which itself is driven by VS2022.

**Comment by kronic** [comment]
It is sad

**Comment by vslee** [comment]
Actually, it looks to me like they're getting ready to start merging the community PRs. They are just waiting to open source the test infrastructure in 22H1. 

> When the Open Sourcing of Test Infrastructure and test collateral work is completed, we will enable broader community pull request merging.

**Comment by ClosetBugSlayer** [comment]
> Wpf is dead.

Windows 11 and UWP are dead. WPF lives on as Avalonia and can be forked further at any time.

**Comment by singhashish-wpf** [comment]
#5762 Roadmap is published here.

**Comment by lindexi** [comment]
@noseratio See https://github.com/dotnet/wpf/pull/5685

**Comment by noseratio** [comment]
> @noseratio See #5685

@lindexi I've studied [the diff](https://github.com/dotnet/wpf/pull/5685/files), but TBH, I still can't tell what's the future of WPF from this updated roadmap, besides *"incorporating .NET Framework servicing fixes into .NET Core 3.1, .NET 5 and .NET 6"*. Am I missing something? 

As far as I can tell, the current WPF development is driven by Visual Studio 2022, which is still built with .NET 4.8 and uses WPF for its UI. 

To compare, here's WinForms' roadmap: https://github.com/dotnet/winforms/blob/main/docs/roadmap.md
