### ISSUE TITLE
Inconsistent line endings on fresh clone

### ISSUE THREAD

**Issue by onovotny** [dotnet/wpf#533]
Hi,

On a fresh clone of the repo, I see this when opening many files:

![image](https://user-images.githubusercontent.com/1427284/55759397-38855f80-5a27-11e9-94af-c4f4a1d6dc06.png)

This particular one is `MarkupCompilePass2.cs`, but it happens on others as well. This could lead to problems with bad PR's and merges down the road.

Can the line endings be normalized in the repo and the right `.gitattributes` be added?

**Comment by YohDeadfall** [comment]
Checked all files. This issue can be closed, @ryalanms.
