### ISSUE TITLE
Ignore 'Option Strict On' defined in option settings with .net 5 in VB.

### ISSUE THREAD

**Issue by Perpete** [dotnet/wpf#5367]
Hello,

With WPF and Winforms, using .net 5 and visual studio version 16.11.3, the Option Strict setting to On in the settings
  options is ignored.
It is necessary to add the instruction in the code.

Despite Option Strict On, there is no conversion error detected.
![2021-09-22 08_48_25-Options](https://user-images.githubusercontent.com/66659162/134300587-2bd320cf-0675-4651-804b-fecc11a928e8.png)

With the addition of the Option Strict On statement, the conversion error is detected.
![2021-09-22 08_49_47-WpfApp1 - Microsoft Visual Studio](https://user-images.githubusercontent.com/66659162/134299354-23da6bcc-33fa-4298-9a06-98fc88b2ee8e.png)

**Comment by singhashish-wpf** [comment]
@Perpete The same behavior is also seen for the Console App also, This would require Visual Studio team's support to fix it. It seems that the "Option Strict" is not working with Visual Studio.
 Please follow up with Visual Studio Feedback team here:
 https://developercommunity.visualstudio.com/search?space=8

**Comment by Perpete** [comment]
Hello,
I reported the issue to the Visual Studio feedback team.
The problem is waiting to be answered.
Thank you for your comment.
