### ISSUE TITLE
Why the Visual.VisualOffset is double type but run the compositor in floats?

### ISSUE THREAD

**Issue by lindexi** [dotnet/wpf#5389]
We will use Visual.VisualOffset to set the visual offset. The Visual.VisualOffset is in managed code. And the type of VisualOffset is Vector which is contained the double X and the double Y.

https://github.com/dotnet/wpf/blob/7e0195803bf0144daba4e5fd2d8be93774d043ef/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Visual.cs#L3523-L3550

But we will use `CMilVisual::ProcessSetOffset` to set it in the MIL code. It will cast the double X and double Y to the float type. Just as the code says, *The packet contains doubles. Should they be floats? Why are we using doubles in managed but run the compositor in floats?*

https://github.com/dotnet/wpf/blob/7e0195803bf0144daba4e5fd2d8be93774d043ef/src/Microsoft.DotNet.Wpf/src/WpfGfx/core/resources/node.cpp#L425-L439

Can I know the reason?

**Comment by vishalmsft** [comment]
@lindexi The question is written more than 15 yrs ago. We don't have answers immediately available in the current team.

**Comment by batzen** [comment]
@vishalmsft Is it fixed or why did you close this issue?

**Comment by vishalmsft** [comment]
@batzen  The question exists in the code as comments. At some point of time, we may circle back to this one as code-review. This issue is practically a duplicate of issue already reported in code.

**Comment by lindexi** [comment]
@vishalmsft Thank you.
