### ISSUE TITLE
 WPF app may stop responding to touch when activated is set by swiping a listbox when focus was on another processes text control

### ISSUE THREAD

**Issue by SamBent** [dotnet/wpf#5440]
[Port of a servicing fix for .NET 4.7-4.8]
 
 **Problem description:**
 Touch input stops working after activating the window with a touch manipulation (when WM_POINTER stack is enabled)

 **Actual behavior:** 
 No response to subsequent touch input.

 **Expected behavior:**
 
 **Minimal repro:**

**Comment by lindexi** [comment]
Reference: [.NET Framework January 2022 Security and Quality Rollup Updates - .NET Blog](https://devblogs.microsoft.com/dotnet/net-framework-january-2022-security-and-quality-rollup-updates/ )

> Addresses an issue where WPF does not respond to touch if the WPF window was activated by a touch manipulation (e.g. swiping a listbox).
