### ISSUE TITLE
TextBox with UpdateSourceTrigger=PropertyChanged is handling Microsoft Quick (Hong Kong Chinese Traditional) Chinese characters input in unexpected behaviors

### ISSUE THREAD

**Issue by SamBent** [dotnet/wpf#5444]
[Port of a servicing fix for .NET 4.7-4.8]
 
 **Problem description:**
Use a TextBox whose Text is databound with UpdateSourceTrigger=PropertyChanged.  Use the Quick IME to type into that TextBox.

 **Actual behavior:** 
Typing works very strangely.  Wrong characters, missing compositions, etc.

 **Expected behavior:**
 Typing works the same way as in Notepad or a TextBox that isn't databound.

 **Minimal repro:**

**Comment by vishalmsft** [comment]
Attaching the [sample project](https://github.com/dotnet/wpf/files/7801378/Issue5444.zip).
