### ISSUE TITLE
Overbuild caused by PackageReference support

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/wpf#5448]
The `_wpftmp` build inside a normal project is built with a global property set: `$(_WpfTempProjectNuGetFilePathNoExt)`. It also now runs `ResolveProjectReferences` by default. This combines to cause overbuild of the referenced projects, because MSBuild treats projects as distinct when they have different global properties.

This can be observed in build output:

```sh-session
❯ dotnet build --no-restore -bl
Microsoft (R) Build Engine version 17.0.0-preview-21477-04+3a1e456fe for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\6.0.100-rc.2.21478.25\MSBuild.dll -bl -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\6.0.100-rc.2.21478.25\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\6.0.100-rc.2.21478.25\dotnet.dll -maxcpucount -verbosity:m .\wpf_incremental.sln
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  Library -> S:\play\wpf_incremental\Library\bin\Debug\net5.0\Library.dll
  Library -> S:\play\wpf_incremental\Library\bin\Debug\net5.0\Library.dll
  WpfApp -> S:\play\wpf_incremental\WpfApp\bin\Debug\net5.0-windows\WpfApp.dll
```

Note the doubled `Library -> S:\play\wpf_incremental\Library\bin\Debug\net5.0\Library.dll`: that project is building twice.

The global property for the `_wpftmp` project is set here:

https://github.com/dotnet/wpf/blob/fb1a859df66b4fc4eaa01be942e7006d20a41418/src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs#L284-L286

Timeline:

1. dotnet/arcade#1581 introduced `$(_WpfTempProjectNuGetFilePathNoExt)` to .NET's Arcade SDK.
2. dotnet/wpf#3585 introduced  `$(IncludePackageReferencesDuringMarkupCompilation)` (defaulted to `false`). This introduced this race condition.
2. dotnet/wpf#3846 backported it to .NET 5.0 SDKs. This included ee91876468a67cdb23589a439842392af0cc6021 that unconditionally set `_WpfTempProjectNuGetFilePathNoExt` to empty.
2. dotnet/sdk#15465 turned `$(IncludePackageReferencesDuringMarkupCompilation)` on by default in the SDK.
3. dotnet/sdk#15695 turned it off again, so this isn't noticeable in the default configurations under .NET SDK 5.0.yxx .
4. dotnet/wpf#4089 flipped the default in WPF.

**Comment by ryalanms** [comment]
This was missed as part of 6.0.  Both the Arcade workaround and WPF's global property should be removed. 

https://github.com/dotnet/wpf/issues/4119

**Comment by rainersigwald** [comment]
@ryalanms Do you think we can get both in for GA? I'd really like to avoid shipping this way.

**Comment by ryalanms** [comment]
@mmitche:  This will require an Arcade change.  We will need to disable (or remove) the Arcade WPF temp project workaround at the same time WPF's global `_WpfTempProjectNuGetFilePathNoExt` is removed.  Is it still possible to get this in? 

The property is `IsWpfTempProject`: 

https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/Workarounds.props#L11

Or the whole change: 

https://github.com/dotnet/arcade/pull/1581
