### ISSUE TITLE
BlazorWebView overlays other ui elements

### ISSUE THREAD

**Issue by HeilOliver** [dotnet/wpf#5459]
**Problem description:**
When another UI element should be displayed above the BlazorWebView component the UI element is not displayed
When the BlazorWebView is replaced with another UIElement, everything is displayed correctly.

 **Actual behavior:** 
Other UI element is not shown.

 **Expected behavior:**
Other UI element shoud be displayed above BlazorWebView.
 
 **Minimal repro:**
```xml
           <Grid>
                <wpf:BlazorWebView
                    HostPage="wwwroot/index.html"
                    Services="//Some ServiceProvider">

                    <wpf:BlazorWebView.RootComponents>
                        <wpf:RootComponent
                            Selector="#app"
                            ComponentType="{x:Type components:App}" />
                    </wpf:BlazorWebView.RootComponents>
                </wpf:BlazorWebView>

                <Border
                    Background="Blue"
                    VerticalAlignment="Stretch"
                    HorizontalAlignment="Stretch"/>
            </Grid>
```
In this example, the border should cover the whole WebView. 

** System **
Windows 11Pro
VS 2022 Prev 4
Net 6 RC1

**Comment by lindexi** [comment]
@HeilOliver  This is the known issues. The BlazorWebView is work as the WinFormsHost

**Comment by batzen** [comment]
@singhashish-wpf That means i will never be fixed? If that's the case it should be made clear in all documentations that it's a known issue and won't get fixed.

 There was a time where MS announced, and as far as i remember, even showcased a WPF version which did not suffer from these "airspace" issues.
