### ISSUE TITLE
Copy/paste in Visual Studio modifies project when using item globbing

### ISSUE THREAD

**Issue by ThomasGoulet73** [dotnet/wpf#5461]
**Problem description:**
 Visual Studio modifies the csproj when copy/pasting a xaml file.

This is not a critical bug because it's just reapplying the default metadata to the new item but it's annoying to have to revert changes to the csproj every time you copy/paste.

 **Actual behavior:**
Visual Studio modifies the csproj by adding this:
```
<ItemGroup>
  <Page Update="MainWindow - Copy.xaml">
    <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    <SubType>Designer</SubType>
  </Page>
</ItemGroup>
```
 
 **Expected behavior:**
Visual Studio shouldn't modify the csproj.
 
 **Minimal repro:**
1. Create a new WPF in Visual Studio.
2. Copy/Paste MainWindow.xaml
3. Look for modifications in the csproj.

**Solution**
I already have a fix locally for removing \<XamlRuntime\> but it looks like \<SubType\> is added by Visual Studio so the fix is probably not going to be in this repo.

I'll send a PR for fixing \<XamlRuntime\> shortly.

**Comment by singhashish-wpf** [comment]
@ThomasGoulet73 Do you suggest we go ahead and close this one?

**Comment by ThomasGoulet73** [comment]
@singhashish-wpf Sorry, I forgot about this issue. I just opened a PR with a fix for `<XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>`. I wasn't able to remove `<SubType>Designer</SubType>`, I don't know where it's coming from.
