### ISSUE TITLE
Microsoft.WindowsDesktop.App.Runtime.win-arm64 contains a stub "D3DCompiler_47.dll", causing issues with 3rd party libraries

### ISSUE THREAD

**Issue by kpreisser** [dotnet/wpf#5462]
* .NET Core Version: .NET SDK 5.0.401
* Windows version: Windows 11 Pro Version 21H2 (Build 22000.194) ARM64
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 
 **Problem description:**

When publishing a WPF app targeting .NET 5.0/6.0 for `win-arm64` (self-contained), a `D3DCompiler_47.dll` file is deployed in the application directory. However, in contrast to the file from the Windows `System32` directory which has ~7 MB and has exports like `D3DCompile`, the file deployed by the .NET SDK has only ~23 KB and doesn't seem to have exports (it comes from the [ Microsoft.WindowsDesktop.App.Runtime.win-arm64](https://www.nuget.org/packages/Microsoft.WindowsDesktop.App.Runtime.win-arm64) package).

Apparently, the presence of this stub DLL can cause issues with 3rd party libraries like CefSharp (embedded Chromium browser), because CEF also depends on `D3DCompiler_47.dll`. In some cases when starting the application, the chromium browser hangs, and the log file contains an error that it cannot find the `D3DCompile` entry point:

```
[1007/102117.812:WARNING:angle_platform_impl.cc(49)] Debug.cpp:180 (insertMessage): GL error: HIGH: Internal D3D11 error: HRESULT: 0x8007000E: Error finding D3DCompile entry point.
[1007/102117.813:ERROR:shared_context_state.cc(73)] Skia shader compilation error
```

**Note:** This doesn't occur when publishing the application for `win-x86` and `win-x64`, because there, a file with a different name `D3DCompiler_47_cor3.dll` is deployed instead of `D3DCompiler_47.dll` (https://github.com/dotnet/wpf/issues/37#issuecomment-494984585), and that file seems to be a [copy from the Windows SDK redist files](https://github.com/dotnet/wpf/blob/30dc08ae87526b3993f295a5e192a93d235847a2/src/Microsoft.DotNet.Wpf/redist/D3DCompiler/D3DCompiler.vcxproj#L46-L53) with all the necessary exports.

See also https://github.com/cefsharp/CefSharp/issues/2944#issuecomment-937595542.
 
 **Minimal repro:**
* Clone [https://github.com/kpreisser/TestCefSharpWpf](https://github.com/kpreisser/TestCefSharpWpf/tree/72171ce6dd52b5ded3457e0b67ed51e30dab505a) (commit 72171ce6dd) and publish the app using `dotnet publish -f net5.0-windows -r win-arm64`.
* Run the published app on a Windows 11 Build 22000 ARM64 machine that has hardware-accelerated graphics (e.g. a Parallels Desktop VM running on a Apple M1 mac).
* Notice that the embedded chromium browser sometimes only shows a white page (this doesn't always occur, sometimes you have to restart the app a few times). When this happens, errors as shown above (regarding the `D3DCompile` entry point) are logged to `TestCefSharpChromiumLog.txt`.
* Now delete the file `D3DCompiler_47.dll` from the app's directory and also remove the corresponding entry in the `TestCefSharpWpf.deps.json` file, and start the app again.
* Notice that the app now works without problems and shows the Google website (as it can now load `D3DCompiler_47.dll` from the Windows `system32` directory).

Is this stub `D3DCompiler_47.dll` file for `win-arm64` really needed?

 **Actual behavior:** 
A stub `D3DCompiler_47.dll` is deployed when publishing the application, which can cause an issue in CEF as it may load that stub file instead of the one from the Windows `system32` directory.
 
 **Expected behavior:**
No `D3DCompiler_47.dll` file is deployed, so that CEF can load the file from the Windows `system32` directory (or, a file with a different name like `D3DCompiler_47_cor3.dll` like in the `win-x86` and `win-arm64` packages is deployed; although that file would probably be superfluous for `win-arm64`).

Thank you!

**Comment by lindexi** [comment]
I think we should rename it to `D3DCompiler_47_cor3.dll` in arm64

**Comment by kpreisser** [comment]
Hi @ryalanms,
Yes, it seems the failure only occurs when publishing as self-contained app (when `D3DCompiler_47.dll` is copied to the application directory). When I set `SelfContained` as false, I can't reproduce the issue.


> d3dcompiler_47.dll can be excluded from the ARM64 WindowsDesktop SDK. It will always be in system32 on Windows10+.

👍 

Additionally, the current Windows 11 SDK (22000) seems to only include redistributables of `D3DCompiler_47.dll` for `x64` and `x86` but not `arm64`, so it seems to be intended to not redistribute this DLL for ARM64 and instead always use the `system32` one.

Thank you!

**Comment by ryalanms** [comment]
This commit successfully removes the dll from the transport package for ARM64.  

https://github.com/dotnet/wpf/commit/438d70ed139badb8400a2414db660858ae268b1f

**Comment by hamarb123** [comment]
(originally commented in #5747) I'm having issues with this on my app. Can this be back-ported to .NET 6.0.4? I'm going to wait until next LTS for upgrade so I would be stuck not being able to support arm64 users until .NET 8 (~1.5 years).

**Comment by lindexi** [comment]
@hamarb123 Could you see https://github.com/dotnet/wpf/pull/5747 ?

**Comment by hamarb123** [comment]
> @hamarb123 Could you see #5747 ?

You mean see the PR? Yes, I commented on it.

**Comment by lindexi** [comment]
@hamarb123  Sorry, I thought this issue was fixed.

**Comment by hamarb123** [comment]
It's fixed in .NET 7 (apparently), but not for .NET 6 (I'm using 6.0.3).

**Comment by lindexi** [comment]
@hamarb123 I remember it was merged into 6.0.3, let me check. Sorry.

**Comment by lindexi** [comment]
The bad news is it do not merge to 6.0.3...

**Comment by hamarb123** [comment]
Okay. Will it be in 6.0.4?

**Comment by lindexi** [comment]
@hamarb123 I ask @singhashish-wpf in https://github.com/dotnet/wpf/pull/5747#issuecomment-1074699704 

And If you can't wait, you can try building the private version.

`build.cmd -pack -ci -configuration Release -prepareMachine /p:Platform=x86`

**Comment by singhashish-wpf** [comment]
We are in process of pushing this to 6.0 servicing, earliest you can expect it to be in June servicing release.
https://github.com/dotnet/wpf/pull/6496

**Comment by hamarb123** [comment]
Okay, thanks!

**Comment by ThomasGoulet73** [comment]
.Net 6.0.6 was just released and contains the fix for this issue:
https://github.com/dotnet/wpf/releases/tag/v6.0.6

**Comment by kpreisser** [comment]
Thank you for fixing this issue and back-porting it to 6.0.6! I can confirm that Microsoft.WindowsDesktop.App.Runtime.win-arm64 6.0.6 no longer contains the stub `D3DCompiler_47.dll`.
It think this issue can be closed now.
