### ISSUE TITLE
Will Milcore libraries also be opensourced?

### ISSUE THREAD

**Issue by liquidboy** [dotnet/wpf#55]
Would love for the native Milcore part, wpfgfx, of WPF to also be opensourced

**Comment by rladuca** [comment]
@liquidboy We agree!  wpfgfx_cor3 will be open sourced as part of WPF for .NET Core.  This work is ongoing throughout 2019 ([see the roadmap](https://github.com/dotnet/wpf/blob/master/roadmap.md)).

Our first focus is getting more of our managed components open sourced.  Our native components will follow those.

**Comment by zwcloud** [comment]
Added to 3.0 milestone but not finished. 🤷‍♂

**Comment by liquidboy** [comment]
It's done 😍 https://github.com/dotnet/wpf/issues/2554.  Thankyou microsoft
