### ISSUE TITLE
WindowsDesktop SDK should recognize Application.xaml

### ISSUE THREAD

**Issue by wjk** [dotnet/wpf#550]
* .NET Core Version: 3.0.100-preview4-011006
* Windows version: 17763.437
* Does the bug reproduce also in WPF for .NET Framework 4.8?: N/A, this is a tooling issue

 **Problem description:**

The Microsoft.NET.Sdk.WindowsDesktop SDK only recognizes `App.xaml` for an automatic ApplicationDefinition item. The Visual Basic project templates call this file `Application.xaml`. Unless the file is renamed or an ApplicationDefinition item is manually specified, the project won't compile.
 
 **Actual behavior:**

Only App.xaml is recognized.
 
 **Expected behavior:**

The SDK should recognize both App.xaml and Application.xaml.

**Comment by ryalanms** [comment]
@dsplaisted: What additional error handling should @wjk add here?  Thanks.

**Comment by Berrysoft** [comment]
@wjk you mixed up the **Actual behavior** and **Expected behavior**.😄

**Comment by ryalanms** [comment]
@dsplaisted signed off.  There is one small update required and then we can merge your change.  Thanks.

**Comment by ryalanms** [comment]
It looks like you already resolved it.  Thanks.
