### ISSUE TITLE
Support System.Drawing.Image in WPF

### ISSUE THREAD

**Issue by ghost** [dotnet/wpf#5566]
WPF can use **System.Windows.Media.ImageSource** class to provide the image source to WPF controls.
But ImageSource cannot use **System.Drawing.Image** class as a source directly.

System.Windows.Media.ImageSource:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.imagesource

If this is a **mixed programming** of Winforms and WPF, the Winforms part needs to use System.Drawing.Image class to display image or bitmap. but now the WPF cannot accept the System.Drawing.Image class.

System.Drawing.Image
https://docs.microsoft.com/zh-cn/dotnet/api/system.drawing.image

**Comment by lindexi** [comment]
@roland5572 Do you means how to show PNG or JPG image in WPF ?
