### ISSUE TITLE
WPF DataGrid memory leak in VS2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5579]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WPF-DataGrid-memory-leak-in-VS2022/1559338)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.11.3]
[Original Source](https://stackoverflow.com/questions/69643694/wpf-datagrid-memory-leak/69645193)
I have this code, and no matter what I do I keep getting a memory leak from the DataGrid data update. I've been looking at all the other answers to this problem here for days and I haven't found anything that works for me. I have a WPF window and this code to update the data (it is a small version of what happens in the real code, but I get the same bug). Works fine in VS2019.

I have this WPF code:

```
<Window x:Class="TremendoMemoryLeak.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:TremendoMemoryLeak"
        mc:Ignorable="d"
        DataContext="{Binding RelativeSource={RelativeSource Self}}"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <DataGrid ItemsSource="{Binding Hmis, Mode=OneWay}" AutoGenerateColumns="False" IsReadOnly="True">
            <DataGrid.Columns>
                <DataGridTemplateColumn Header="Estado">
                    <DataGridTemplateColumn.CellTemplate>
                        <DataTemplate>
                            <Ellipse Fill="{Binding Estado}" HorizontalAlignment="Left" Height="25" Stroke="Black" VerticalAlignment="Top" Width="25"/>
                        </DataTemplate>
                    </DataGridTemplateColumn.CellTemplate>
                </DataGridTemplateColumn>
                <DataGridTextColumn Header="Dato1" Binding="{Binding Dato1}"/>
                <DataGridTextColumn Header="Dato2" Binding="{Binding Dato2}"/>
            </DataGrid.Columns>
        </DataGrid>
    </Grid>
</Window>
```

This class code:

```
/// <summary>
/// Interaction logic for MainWindow.xaml
/// </summary>
public partial class MainWindow : Window, INotifyPropertyChanged
{
    public ObservableCollection<Datos> Hmis { get; } = new ObservableCollection<Datos>();
    private System.Threading.Timer timer;

    public MainWindow()
    {
        InitializeComponent();
        timer = new System.Threading.Timer(ActualizacionUI_Tick, null, 1000, 1000);
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    private void ActualizacionUI_Tick(object data)
    {
        Datos dato1 = new Datos() { Dato1 = "1", Dato2 = "2" };

        Datos dato2 = new Datos() { Dato1 = "1", Dato2 = "2" };

        Datos dato3 = new Datos() { Dato1 = "1", Dato2 = "2" };

        Dispatcher.Invoke(() =>
        {
            dato1.Estado = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#FF5DC75D"));
            dato2.Estado = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#FF5DC75D"));
            dato3.Estado = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#FF5DC75D"));
            Hmis.Clear();
            Hmis.Add(dato1);
            Hmis.Add(dato2);
            Hmis.Add(dato3);
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Hmis"));
        });
    }
}
```

And this data class:

```
public class Datos : INotifyPropertyChanged
{
    public Brush Estado { get; set; }
    public string Dato1 { get; set; }
    public string Dato2 { get; set; }

    public event PropertyChangedEventHandler? PropertyChanged;
}
```

---
#### Feedback Bot on 10/20/2021, 11:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
@sneik15 Have you also checked by using DependencyProperty for datos or providing implementation of INotifyPropertyChanged.

Please refer to https://stackoverflow.com/questions/18542940/can-bindings-create-memory-leaks-in-wpf/18543350#18543350

**Comment by sneik15** [comment]
@singhashish-wpf I have tested it and it still happens

**Comment by singhashish-wpf** [comment]
Great, could you please upload the zip for it also?
We do see that the memory usage increased for the app in diagnostics, however we also see new objects being created each time the callback is getting called; also, those objects are there in binding. So, we need to make sure this isn't an app specific issue.

**Comment by sneik15** [comment]
Both the list of the data(ObservableCollection) and the data(Datos) itself already implement INotifyPropertyChanged in the original zip that I have uploaded.

**Comment by singhashish-wpf** [comment]
> @singhashish-wpf Ashish Singh FTE I have tested it and it still happens

@sneik15 Please upload DependencyProperty version of the zip which you tested.

**Comment by sneik15** [comment]
@singhashish-wpf  I don't know how to correctly implement a DependencyProperty  version.
