### ISSUE TITLE
What is going to happen to `System.Windows.Shell`?

### ISSUE THREAD

**Issue by daniel-white** [dotnet/wpf#56]
`System.Windows.Shell` is part of PresentationCore.dll (which is part of WPF). I'm sure it would be nice to move that into a new open source library as part of this effort.

**Comment by karelz** [comment]
@daniel-white you can check WPF repo status on its main page: https://github.com/dotnet/wpf#status

**Comment by vatsan-madhavan** [comment]
As we continue to make sources for additional WPF assemblies available [through 2019](https://github.com/dotnet/wpf/blob/master/roadmap.md), those for `System.Windows.Shell` will also be made available as part of that effort.
