### ISSUE TITLE
Application not scaled with .NET Core 3.1.19

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5613]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Application-not-scaled-with-NET-Core-3/1565743)._

---
[severity:I'm unable to use this version] [regression] [worked-in:3.1.18]
We noticed that our .NET Core WPF Touchscreen apps seem to have problems with version 3.1.19. Our touch screen apps become completely un-usable!! Eventually we found this link https://github.com/dotnet/wpf/issues/5375 that explains there is a possible fix and have applied it to our code for all existing apps.  We also call the native SetProcessDPIAware(); before OnStartUp().

We would rather not keep this fix since it just does not look right. 

Can you please advise if this is under investigation on your side and if this fix is ok or are there any plans to fix this in the .NET Core?

Any help is very much appreciated with this!

Regards,
Anthony

---
#### Feedback Bot on 10/28/2021, 01:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Is this reproducible in .NET 6 too?
The fix is likely in 3.1.21, so please test and confirm.

**Comment by singhashish-wpf** [comment]
Closed as no response received.
