### ISSUE TITLE
Faulting module name: coreclr.dll

### ISSUE THREAD

**Issue by martin-braun** [dotnet/wpf#5615]
* .NET Core Version: 5.0
* Windows version: 
<img width="231" alt="Screen Shot 2021-11-01 at 21 04 01" src="https://user-images.githubusercontent.com/24259245/139734301-c946c9f3-30ee-4cf7-8f58-82f16d14bfb3.png">
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Don't know
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No
 
 **Problem description:**

Launching a published/released WPF application with "Produce single file" causes a crash on startup. 

 **Actual behavior:** 

Event Viewer reports:

```
Faulting application name: actmx.exe, version: 0.0.1.0, time stamp: 0x6115a20d
Faulting module name: coreclr.dll, version: 5.0.1021.41214, time stamp: 0x611590cd
Exception code: 0xc0000005
Fault offset: 0x0019ee4a
Faulting process id: 0x580
Faulting application start time: 0x01d7cf5a9efd4a11
Faulting application path: \\Mac\Projects\MyApp\pub\actmx.exe
Faulting module path: \\Mac\Projects\MyApp\pub\coreclr.dll
Report Id: b67f5181-fa57-4305-9a9b-15d4d97e4c8c
```
 
 **Expected behavior:**

Launching application just fine as it works without "Produce single file" enabled in the publishing profile.
 
 **Minimal repro:**
Enable "Produce single file" in the publishing profile of a new WPF application with .net 5.0 Windows target. Architecture target is x86, but the exe will be executed on a x64 machine.

**Comment by julesx** [comment]
This is occurring in my environment as well.
My app runs fine in debug but crashes in single-file published release

**Comment by lindexi** [comment]
@julesx What is your dotnet sdk version?

**Comment by singhashish-wpf** [comment]
@martin-braun as .NET 5 is out of support, I tried to repro this on .NET6 however it didn't reproduce on my system.
I made sure of below items.
- [ ] Release
- [ ] x86
- [ ] run on x64
- [ ] single file

**Comment by singhashish-wpf** [comment]
Closing as not reproducible on .NET6

**Comment by martin-braun** [comment]
> Closing as not reproducible on .NET6

@singhashish-wpf Sure thing, I yet did not have time to investigate with .NET 6, but I will port my .NET app to version 6 soon and re-test. I will reply to you and ask for re-open if the issue won't be fixed on my end. Thanks.

**Comment by iam-Robo** [comment]
Good day,

I am facing the same issue on my Windows server 2019  :(

This is the complete report 

Faulting application name: w3wp.exe, version: 10.0.17763.1, time stamp: 0xa7ccada2
Faulting module name: coreclr.dll, version: 5.0.1722.21314, time stamp: 0x62576ff1
Exception code: 0xc0000094
Fault offset: 0x0009f871
Faulting process id: 0x58f8
Faulting application start time: 0x01d8ad568825e529
Faulting application path: C:\Windows\SysWOW64\inetsrv\w3wp.exe
Faulting module path: C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\5.0.17\coreclr.dll
Report Id: db320efa-5c8f-47dd-9f20-4de963cf1a77
Faulting package full name: 
Faulting package-relative application ID:
