### ISSUE TITLE
Application crashed due to Object null reference when remotely logging in to WPF application.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5632]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Application-crashed-due-to-Object-null-r/1210359)._

---
<p>Hi,</p><p>I am using .net framework 4.5. On remotely login to a system running a wpf application, the application crashes with the following stack trace :</p><p>&quot;System.NullReferenceException: Object reference not set to an instance of an object.__
  at System.Windows.Controls.VirtualizingStackPanel.CleanupContainers(Int32 firstItemInExtendedViewportIndex, Int32 itemsInExtendedViewportCount, ItemsControl itemsControl, Boolean timeBound, Int32 startTickCount)__ 
  at System.Windows.Controls.VirtualizingStackPanel.OnClearChildren()__ 
  at System.Windows.Controls.Panel.ClearChildren()__ 
  at System.Windows.Controls.Panel.VerifyBoundState()__ 
  at System.Windows.Controls.Panel.get_InternalChildren()__ 
  at System.Windows.Automation.Peers.ItemsControlAutomationPeer.GetChildrenCore()__ 
  at System.Windows.Automation.Peers.DataGridAutomationPeer.GetChildrenCore()__ 
  at System.Windows.Automation.Peers.AutomationPeer.EnsureChildren()__ 
  at System.Windows.Automation.Peers.AutomationPeer.UpdateChildrenInternal(Int32 invalidateLimit)__ 
  at System.Windows.Automation.Peers.ItemsControlAutomationPeer.UpdateChildren()__  
  at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ 
  at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ 
  at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ 
  at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ 
  at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ 
  at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__  
  at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__  
  at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__  
  at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__  
  at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__  
  at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__   
  at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__   
  at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__   
  at System.Windows.ContextLayoutManager.fireAutomationEvents()__   at
     System.Windows.ContextLayoutManager.UpdateLayout()__  
  at System.Windows.Interop.HwndSource.Process_WM_SIZE(UIElement rootUIElement, IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam)__ 
  at System.Windows.Interop.HwndSource.LayoutFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)__   at MS. Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)__ 
  at MS. Win32.HwndSubclass.DispatcherCallbackOperation(Object o)__   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)__   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)&quot;</p>

---
#### api.twitter Twutter on 10/7/2020, 00:42 AM: 

(private comment, text removed)
#### Feedback Bot on 10/9/2020, 05:49 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/19/2021, 04:08 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
#### api.twitter Twutter solved on 10/7/2020, 00:44 AM, 0 votes: 

<p>"System.NullReferenceException: Object reference not set to an instance of an object.__ at System.Windows.Controls.VirtualizingStackPanel.CleanupContainers(Int32 firstItemInExtendedViewportIndex, Int32 itemsInExtendedViewportCount, ItemsControl itemsControl, Boolean timeBound, Int32 startTickCount)__ at System.Windows.Controls.VirtualizingStackPanel.OnClearChildren()__ at System.Windows.Controls.Panel.ClearChildren()__ at System.Windows.Controls.Panel.VerifyBoundState()__ at System.Windows.Controls.Panel.get_InternalChildren()__ at System.Windows.Automation.Peers.ItemsControlAutomationPeer.GetChildrenCore()__ at System.Windows.Automation.Peers.DataGridAutomationPeer.GetChildrenCore()__ at System.Windows.Automation.Peers.AutomationPeer.EnsureChildren()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateChildrenInternal(Int32 invalidateLimit)__ at System.Windows.Automation.Peers.ItemsControlAutomationPeer.UpdateChildren()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.ContextLayoutManager.fireAutomationEvents()__ at System.Windows.ContextLayoutManager.UpdateLayout()__ at System.Windows.Interop.HwndSource.Process_WM_SIZE(UIElement rootUIElement, IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam)__ at System.Windows.Interop.HwndSource.LayoutFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)__ at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)__ at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)__ at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)__ at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)"</p>
<a target='_blank' href="https://developercommunity.visualstudio.com/users/289082/997720b7-1882-6d21-96b9-68c37ec519fa.html"><img src="https: secure.gravatar.com=" style="&quot;width: 24px;&quot;">api.twitter Twutter</a>(just now)
 private
<p>METACABAN\</p><ul></ul><p><a target="_blank">"System.NullReferenceException: Object reference not set to an instance of an object.__ at System.Windows.Controls.VirtualizingStackPanel.CleanupContainers(Int32 firstItemInExtendedViewportIndex, Int32 itemsInExtendedViewportCount, ItemsControl itemsControl, Boolean timeBound, Int32 startTickCount)__ at System.Windows.Controls.VirtualizingStackPanel.OnClearChildren()__ at System.Windows.Controls.Panel.ClearChildren()__ at System.Windows.Controls.Panel.VerifyBoundState()__ at System.Windows.Controls.Panel.get_InternalChildren()__ at System.Windows.Automation.Peers.ItemsControlAutomationPeer.GetChildrenCore()__ at System.Windows.Automation.Peers.DataGridAutomationPeer.GetChildrenCore()__ at System.Windows.Automation.Peers.AutomationPeer.EnsureChildren()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateChildrenInternal(Int32 invalidateLimit)__ at System.Windows.Automation.Peers.ItemsControlAutomationPeer.UpdateChildren()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()__ at System.Windows.ContextLayoutManager.fireAutomationEvents()__ at System.Windows.ContextLayoutManager.UpdateLayout()__ at System.Windows.Interop.HwndSource.Process_WM_SIZE(UIElement rootUIElement, IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam)__ at System.Windows.Interop.HwndSource.LayoutFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)__ at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)__ at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)__ at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)__ at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)"  Hide comment 1  api.twitter Twutter (just now)  private METACABAN  Just tried building some of our code stack with VS 2019 Preview 2 using toolset v142. With VS 2017 w   0  Add comment Solutions Add your solution Add your solution</a></p><p>Just tried building some of our code stack with VS 2019 Preview 2 using toolset v142. With VS 2017 w</p>
<a target='_blank' href="https://developercommunity.visualstudio.com/content/problem/1210359/application-crashed-due-to-object-null-reference-w.html#"> </a>0<a target='_blank' href="https://developercommunity.visualstudio.com/content/problem/1210359/application-crashed-due-to-object-null-reference-w.html#"> </a><a target='_blank' href="https://developercommunity.visualstudio.com/content/problem/1210359/application-crashed-due-to-object-null-reference-w.html#"></a>
<a target='_blank' href="https://developercommunity.visualstudio.com/content/problem/1210359/application-crashed-due-to-object-null-reference-w.html#">Add comment</a>
<h2>Solutions</h2> <a target='_blank' href="https://developercommunity.visualstudio.com/content/problem/1210359/application-crashed-due-to-object-null-reference-w.html#reply-form">Add your solution</a>
<h3>Add your solution</h3>

**Comment by singhashish-wpf** [comment]
Is it possible to share the complete crash dump or a minimal repro to check this further?

**Comment by singhashish-wpf** [comment]
Closing as no further details were provided.
