### ISSUE TITLE
IOException with WPF resource dictionary source from external assembly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5634]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IOException-with-WPF-resource-dictionary/1453907)._

---
[regression] [worked-in:17.0.0 Preview 1.0]
I have a solution with several projects that hold resource dictionaries (in this case a converter.xaml) that are linked into central resource dictionary xaml's (in my case a themes.xaml) Both files sit in different assemblies (converter's assembly is a reference in themes' assembly)

When removing the link to converter.xaml, I get the exact same exception for multiple other resources in other assemblies.

I had the same issue with the latest 2019 preview earlier today and fixed it by uninstalling .Net 6 Preview
The latest production version of visual studio 2019 (community) works perfectly fine with the same solution.

---
#### Feedback Bot on 6/18/2021, 00:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/9/2021, 02:05 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Could you please provide a minimal repro to check this further?

**Comment by singhashish-wpf** [comment]
Closing as no further information was available.
