### ISSUE TITLE
MSBuild WPF broken project dependencies

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5636]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MSBuild-WPF-broken-project-dependencies/1377730)._

---
[severity:It bothers me. A fix would be nice]
Hello,

i've 4 projects.
project "model", project "converters", project "workerthread" and the project "gui".
"workerthread" referred to "model" and "converters". all the dlls are in the outputfolder.
"gui" referred to "workerthread" only. only "model" and "workerthread" dlls are in the "gui" outputfolder. missing "converters".

how the converters are used (shorten code):
```
[UserControl xmlns:VisibilityConverters="clr-namespace:CMO.Common.Converters.Converters.VisibilityConverters;assembly=CMO.Common.Converters"]
    [UserControl.Resources]
        [VisibilityConverters:BooleanInvertToVisibilityConverter x:Key="BooleanInvertToVisibilityConverter"/]
    [/UserControl.Resources]
    [Grid]
        [Button Visibility="{Binding IsHidden, Converter={StaticResource BooleanToVisibilityConverter}, Mode=OneWay}" /]
    [/Grid]
[/UserControl]
```
Sorry, the XAML-Code was removed first. Replaced  with [ and ]. Hope this will work now.

the "converters"-dll will be copied to the outputfolder when i add a line with new converters to the usercontrol codebehind:
```
        public WorkerThreadBase()
        {
            InitializeComponent();
            var x = new Common.Converters.Converters.VisibilityConverters.BooleanInvertToVisibilityConverter();
        }
```

why the WPF-references will not be solved and the "converters"-dll be copied?

Using:
Visual Studio 2019 16.9.2
"model": .NET-Framework 4.7.2
"converters": .NET-Framework 4.7
"workerthread": .NET-Framework 4.8
"gui": .NET-Framework 4.8

---
#### Feedback Bot on 3/22/2021, 11:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/5/2021, 11:34 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### Stephan Weber on 7/6/2021, 02:21 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Could you please provide a minimal repro to check this further?

**Comment by singhashish-wpf** [comment]
Closing in absence of a minimal repro/reply.
