### ISSUE TITLE
WPF app published with .Net 5 preview 8 self-contained crashes on launch

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5638]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/WPF-app-published-with-Net-5-preview-8-/1174820)._

---
[severity:I'm unable to use this version of Visual Studio] [regression] [worked-in:Latest at the moment of Net5pre6 release]
I first tried .Net 5 preview 6 when it came out. I was running latest VS Preview that time. It worked well.

Now I decided to try preview 8, installed x86 SDK as well as latest VS Preview.
I have a custom entry point that creates App instance inside trycatch block and logs any exception that finds it's way here.
Here is what I got on launch:

```
[TypeInitializationException] The type initializer for 'System.Windows.Threading.Dispatcher' threw an exception.:
   at System.Windows.Threading.Dispatcher.get_CurrentDispatcher()
   at System.Windows.Threading.DispatcherObject.. ctor()
   at System.Windows.Application.. ctor()
   at NS.App.. ctor()
   at NS. Program.Main(String[] args)
```
InnerException:
```
[FileNotFoundException] The system cannot find the file specified. (0x80070002)
   at System.Reflection.RuntimeModule.GetFullyQualifiedName(QCallModule module, StringHandleOnStack retString)
   at System.Reflection.RuntimeModule.GetFullyQualifiedName()
   at System.Reflection.RuntimeModule.get_Name()
   at System.Windows.WpfDllVerifier.VerifyWpfDllSet(String[] additionalDlls)
   at System.Windows.Threading.Dispatcher.. cctor()
```
It looks like trimmed publish with too much trimmed, but it's not.
Publish parameters:

```
Target: win-x86
Deployment: self-contained
Options: Single file, R2R
```
Disabling R2R changed nothing, same issue.
I thought that maybe it's preview 8 issue. I uninstalled it and installed preview 6 back.
No changes. So I think it's a VS Preview issue.

Also I tried publishing with netcore3.1, SC, SF, R2R. Runs well after publish. The issue is with . Net5 only.
I wanted to test in stable VS as well, but . Net5 option is not available there despite SDK preview enabled.

---
#### Feedback Bot on 9/6/2020, 08:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### 0xCA on 9/29/2020, 05:23 AM: 

<p>I've updated to VS 16.8.0 p3.1 and .Net 5 to rc1. Same problem persists.</p>

#### Feedback Bot on 12/2/2020, 06:46 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by BinToss** [comment]
The WPF libraries in .NET 5 and 6 are trim-incompatible. Trimming WPF can be forced when developing with the .NET 5 SDK, but it results in runtime issues like this one.

**Comment by singhashish-wpf** [comment]
[Trimming support is disabled in WPF](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/incompatibilities#:~:text=Unfortunately%2C%20almost%20no%20WPF%20apps%20are%20runnable%20after%20trimming%2C%20so%20trimming%20support%20for%20WPF%20has%20been%20disabled%20in%20the%20.NET%206%20SDK.)
