### ISSUE TITLE
WPF FolderBrowserDialog ShowNewFolderButton 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5640]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/WPF-FolderBrowserDialog-ShowNewFolderBut/1203862)._

---
[severity:It's more difficult to complete my work]
When using Net Core 3.0 or 3.1 or the latest 5.0 release when you set the ShowNewFolderButton = true and show the dialog it does not show the create folder button. This works in .NET Frame work 4.7.X and higher.

---
#### Feedback Bot on 9/29/2020, 06:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/19/2021, 00:07 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Could you please share a minimal repro to check this further?

**Comment by singhashish-wpf** [comment]
Closing in absence of a minimal repro or details.
