### ISSUE TITLE
Custom fonts don't work in WPF when applying them from a style

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5641]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Custom-fonts-dont-work-in-WPF-when-appl/1238702?preview=true)._

---
[severity:It's more difficult to complete my work]
Create a new WPF project using Visual Studio 2019.
Import a custom font (.ttf) and add it as a resource in App.xaml
Create a style for a control (e.g. Label) and apply it to a control in MainWindow.xaml
Add your custom font resource as the font family value for the new style
Notice that while the custom font appears in the designer, but it doesn't work in release and debug mode.
Note: if you just apply the font directly it works, but not if you apply it from a style

---
#### Feedback Bot on 10/29/2020, 10:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/19/2021, 10:05 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Could you please share a minimal repro to check this further?

**Comment by miloush** [comment]
I tried and cannot repro

**Comment by singhashish-wpf** [comment]
Closing in absence of a minimal repro/reply.
