### ISSUE TITLE
.net WPF Visual Basic template

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5643]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/net-WPF-Visual-Basic-template/1254553?preview=true)._

---
[severity:It's more difficult to complete my work]
I'm not finding Visual Basic WPF (.Net 5) template.

It will be availiable in the future ?

I'm using VS 2019 16.8.1

---
#### Martin Soles on 11/12/2020, 02:08 PM: 

<p>I see that you can add a new WPF project using the CLI and then open the generated project in Visual Studio. It would be nice to have support inside the IDE for the project creation instead of trying to create my own template as a workaround.</p>

#### Feedback Bot on 11/13/2020, 11:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/19/2021, 10:06 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### jacky.perpete on 2/25/2021, 11:27 PM: 

<p>I have also reported this issue to the developer community.<br>
Here is the link below:<br>
<a target='_blank' href="https://developercommunity2.visualstudio.com/t/pas-de-creation-de-projet-wpf-app-net-en-visual-ba/1251385?from=email&amp;viewtype=all#T-ND1344402">https://developercommunity2.visualstudio.com/t/pas-de-creation-de-projet-wpf-app-net-en-visual-ba/1251385?from=email&amp;viewtype=all#T-ND1344402</a></p>
<p>After several searches, I managed to view the WPF project with <a target='_blank' href="http://VB.net">VB.net</a> and .net 5. (See link)<br>
But when selecting the target of the framework, I notice that .NET 5.0 is in progress.<br>
So I asked the following questions:<br>
What NET 5.0 is going on?<br>
Isn’t that why the WPF .NET 5 project is not available by default in <a target='_blank' href="http://VB.net">VB.net</a>?<br>
Is .NET 5.0 usable for <a target='_blank' href="http://vb.net">vb.net</a> in WPF?</p>
<p>I’m waiting for an answer.</p>

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
WPF on .NET6 has the template for VB.
