### ISSUE TITLE
C# WPF SystemParameters.MaximizedPrimaryScreenHeight

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5645]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-WPF-SystemParametersMaximizedPrimary/1468904)._

---
[severity:It's more difficult to complete my work]
SystemParameters.MaximizedPrimaryScreenHeight = 838.4
this. Height = SystemParameters.MaximizedPrimaryScreenHeight (838.40000000000009)

Even before that there were problems where this command gave even weirder values, I resorted to Screen.PrimaryScreen.Bounds.Height from Windows.Forms.

---
#### Feedback Bot on 7/6/2021, 11:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/9/2021, 02:05 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Could you please elaborate the actual issue and provide a minimal repro?

**Comment by miloush** [comment]
My guess is that the developer expected an integer number, but the values are adjusted for DPI. It might be worth mentioning that in the docs, because currently it just states "pixels".

https://docs.microsoft.com/en-us/dotnet/api/system.windows.systemparameters.maximizedprimaryscreenheight?view=windowsdesktop-6.0

**Comment by anjali-wpf** [comment]
The document has been updated for SystemParameters.MaximizedPrimaryScreenHeight, please check [here](https://learn.microsoft.com/en-us/dotnet/api/system.windows.systemparameters.maximizedprimaryscreenheight?view=windowsdesktop-6.0).
