### ISSUE TITLE
DataGrid Glitch - while multiple processes tries to update DG, it shows row glitches

### ISSUE THREAD

**Issue by PreethaBS** [dotnet/wpf#5646]
* .NET Core Version: 4.8
* Windows version: Windows 10 Enterprise - version : 20H2
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 **Problem description:**
  I have an application , in which there are 10 locations and user can create people in lots to move to these locations.
the list of people/Users created in lots are displayed in datagrid.I select a user and click command button to move the user to location 1.Once he is done at location 1, I update the status in datagrid and select him to move to location 2.I repeat this process for the x number of users in lots.
On Move next - initially I update the datagrid and call await Task.Run(() => StartProcessing() to initiate task delay and based on it result (bool flag) I update the Datagrid again.This happens simultaneously, let's say different users in different locations on Movenext.
 
 **Actual behavior:** 

![DGGlitch](https://user-images.githubusercontent.com/88112134/140565635-edda1a16-426d-46fd-beda-f9422266edb2.jpg)

 As you can see I have only, 6 lots but due to some race condition, the DG shows the same set of lots again( that is binded to the Datagrid in an observable collection.)

 DG code in xaml  : 
<DataGrid Grid.Row="0" Grid.Column="0" x:Name="dgLots"
                  ItemsSource="{Binding AvailableLots, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
                  SelectedItem="{Binding SelectedLot, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
                  SelectionUnit="FullRow" SelectionMode="Single" RowHeight="30"
                  IsReadOnly="True" CanUserReorderColumns="False" Margin="15,49,15,51" AutoGenerateColumns="False"
                  HorizontalScrollBarVisibility="Visible" VerticalScrollBarVisibility="Visible"
                  Width="370" Height="400" CanUserResizeColumns="False">
            <DataGrid.Columns>
                <DataGridTextColumn Header="Lot Id" Width="Auto" Binding="{Binding Path=LotId}">
                </DataGridTextColumn>
                <DataGridTextColumn Header="Lot Name" Width="Auto" Binding="{Binding Path=LotName}" >
                </DataGridTextColumn>...... etc 
          </DataGrid.Columns>
 </DataGrid>

Can you please help.

**Comment by singhashish-wpf** [comment]
Please provide a minimal repro of the bug.

**Comment by singhashish-wpf** [comment]
Closing in absence of minimal repro or trace.
