### ISSUE TITLE
Images from App.xaml Resource Dictionary not producing in Content Controls.

### ISSUE THREAD

**Issue by osamakawish** [dotnet/wpf#5650]
* .NET Core Version: .Net 5.0
* Windows version: 10
* **Does the bug reproduce also in WPF for .NET Framework 4.8?:** Unsure, it occurred on .Net 5.0 and the app is a bit too complicated to easily reproduce in an entirely new .NET Framework app at this point.
* **Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)?** I doubt it. The bug occurs during a debug session. But hard to pinpoint the exact source here.

 
 
 **Problem description:**

Quite unusual really. I have a set of definitions for icons in my App.xaml resource dictionary:

```c#
<Application.Resources>
    <ResourceDictionary>
        <BitmapImage x:Key="Position"  UriSource="Icons/Properties/Position.png"/>
        <BitmapImage x:Key="XPosition" UriSource="Icons/Properties/Position-x.png"/>
        <BitmapImage x:Key="YPosition" UriSource="Icons/Properties/Position-y.png"/>
    </ResourceDictionary>
</Application.Resources>
```

The position image isn't necessary here, but I'll mention it later. It's mainly the X and Y position icons that are relevant for now. All 3 images are marked with Build Action "Resource" and told to "Copy if newer". I've tried changing the Build Action to "Content" and "Embedded Resource" and the issue persists.

Now, in my MainWindow, I have a bit of a long-winded approach to accessing these images, but the key thing to note is that the X and Y Positions should be behaving identically. But the code for MainWindow looks like this:

```c#
public MainWindow()
{
    InitializeComponent();

    // Have changed this to XPosition and Position as well
    var prop = AnimatableProperties.YPosition;
    //MessageBox.Show(Directory.GetCurrentDirectory());
    var bmp = prop.Icon.Clone();
    Stack1.Children.Add(new ContentControl { Content = new Image { Source = bmp, Width = 36 }, Width = 400 });
}
```
Here Stack1 was just a Stack Panel. But the issue persisted whether I added the children to a Canvas as well.

The Animatable Properties class is just a class for easier accessibility of these things. It looks like the following:

```c#
public static class AnimatableProperties
{
    internal static AnimatableProperty<double, DoublePropertyControl> XPosition => new("XPosition");
    internal static AnimatableProperty<double, DoublePropertyControl> YPosition => new("YPosition");

    internal static AnimatablePropertyBranch Position => new("Position", XPosition, YPosition);
}
```

The relevant constructor for AnimatableProperty is:

```c#
public sealed class AnimatableProperty<TValue, TControl> : IAnimatableProperty where TControl : UIElement, IAnimatableProperty<TValue>, new()
{
    ...
    public BitmapImage Icon { get => Control.Icon; internal set => Control.Icon = value; }
    ...
    internal AnimatableProperty(string iconResourceKey) => Icon = IAnimatablePropertyExt.FromResource(iconResourceKey);
    ...
}
```

In short, this is just a long-winded approach to acquire the images from the resource dictionaries.

The relevant constructor and properties for AnimatablePropertyBranch are:

```c#
public sealed class AnimatablePropertyBranch : IAnimatableProperty
    {
        public BitmapImage Icon { get; set; }
        ...
        private readonly ReadOnlyCollection<IAnimatableProperty> _values;
        public ReadOnlyCollection<IAnimatableProperty> Values
        { get => _values; set { for (int i = 0; i < _values.Count; i++) { _values[i].Value = value[i].Value; } } }
        ...
        internal AnimatablePropertyBranch(string iconResourceKey, params IAnimatableProperty[] properties)
            => (Icon, _values) = (IAnimatablePropertyExt.FromResource(iconResourceKey), new(properties));
        ...
    }
```

Again, back to the MainWindow constructor, all that happened was that I added a basic content control containing the icon:

```c#
    // Have changed this to XPosition and Position as well
    var prop = AnimatableProperties.YPosition;
    //MessageBox.Show(Directory.GetCurrentDirectory());
    var bmp = prop.Icon.Clone();
    Stack1.Children.Add(new ContentControl { Content = new Image { Source = bmp, Width = 36 }, Width = 400 });
```

 **Actual behavior:**
The issue is a bit complex, and there may be multiple underlying issues.

Note that `Position`, `XPosition`, `YPosition` are all referencing the static properties of the `AnimatableProperties` class.

But the following things happened:

* If the `prop` variable in the MainWindow constructor is either `Position` or `YPosition`, the debug raises an IO Exception saying it cannot find the file. (Again, recall that the files are set to copy if newer, and Build Actions "Content", "Resource", and "Embedded Resource" have all been tested to try to fix this.)
* If the `prop` variable is XPosition however, the system is able to produce an image.
* If I don't clone the images from the resource dictionary, the Content Control simply writes out the `BitmapImage.Source` property as a string, and doesn't produce any image.
* No images are copied into the Icons/Properties folder of the Debug folder for the project. Not even the XPosition folder, which displays fine.
* I have triple-checked the directories and everything, the files, file names are accurate. The image below contains a search result for files containing "Position" in the Project Directory. You're free to double-check the spellings yourself. I added modification dates and times to show that they should all behave similarly, but don't.

![Screenshot (28)](https://user-images.githubusercontent.com/20045083/140620363-676f8d8e-3185-43a9-a741-8b42f87e4d42.png)

* If the Canvas or Stack Panel directly contains an image (ie. not through a Content Control, and therefore a Button as well, but an Image directly), then the images display perfectly fine for all 3 of `XPosition`, `YPosition`, and `Position`.
* Cleaning and rebuilding did not fix the issue. Neither did closing and reopening Visual Studio.

Note that XPosition and YPosition behave differently, despite having the exact same underlying code to produce the images.

Only IO Exceptions were called, and they mentioned that they were unable to find the files for the `Position` and `YPosition` properties specifically. It's worth clarifying, that there was definitely no misspelling of the resource keys, as it identified the appropriated directories to search for.

 **Expected behavior:**
 
The images should have been copied to the Icons/Properties folder of the debug directory, and been visible regardless whether or not they're inserted into the Stack Panel or Canvas via a Content Control or not. At the very least, XPosition and YPosition should have behaved identically.

 **Minimal repro:**

The issue is a little complicated that I'm not sure a minimal amount of code will even reproduce the original issue.

But the steps to produce it would be:

1. Create a WPF project.
2. Add an image to some folder.
3. Add image as a resource in a resource dictionary in App.xaml.
4. Add the image to a Panel in the MainWindow from the resources via a Content Control dynamically (ie. not in the XAML code).

If you're interested in a minimal repro, it would take some time to produce something similar, but writing this down took long enough. So I'll try to do it soon. A little busy in the upcoming days though, so unsure how soon that will be. 

The project is on GitHub privately, should anyone wish to pull it to their computer, I can add them to the repo temporarily.

**Comment by singhashish-wpf** [comment]
Please provide a minimal repro.

**Comment by osamakawish** [comment]
Seeing as it's not easy to produce a minimal repro without adding an image as part of the project, I've created [this](https://github.com/osamakawish/WpfTest). Will it do? It's also causing the same IOException for me.

**Comment by osamakawish** [comment]
I seem to have noticed the source of the issue, I think. I unpacked the project and checked the csproj file's xaml contents and got this:

```c#
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Icons\Properties\Position-x.png" />
    <None Remove="Icons\TimeIcon.png" />
    <None Remove="Library\AnimatableData\Icons\Position-x.png" />
    <None Remove="Library\AnimatableData\Icons\Position-y.png" />
    <None Remove="Library\AnimatableData\Icons\Position.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.3.246501">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.2" />
    <PackageReference Include="WpfMath" Version="0.11.0" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Icons\Properties\Position-x.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\TimeIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Library\AnimatableData\Icons\Position-x.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Library\AnimatableData\Icons\Position-y.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Library\AnimatableData\Icons\Position.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
</Project>
```

For whatever reason, the build actions I set for **Icons/Properties/Position.png** and **Icons/Properties/Position-y.png** haven't been carried over to the csproj file. As much as this can be fixed manually, I do think it should be an issue that ought to be addressed in the code-behind. 

Telling Visual Studio to **copy if newer** should be carried over to the project's csproj file for every image, but it isn't.

**Comment by osamakawish** [comment]
In fact, unloading and reloading the project seems to have fixed the issue. But please fix this issue so that others don't run into it. VS doesn't seem to always carry the action for CopyToOutputDirectory over to the csproj file, and that could confuse devs who are new to WPF.

**Comment by singhashish-wpf** [comment]
Thanks @osamakawish 
Closing this for now.
