### ISSUE TITLE
Using VideoDrawing with MediaPlayer can result in a black frame when going from pause to play amidst UI updates

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5654]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Using-VideoDrawing-with-MediaPlayer-can-/1447390)._

---
[severity:Other]
MS docs is [here](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/how-to-play-media-using-a-videodrawing?view=netframeworkdesktop-4.8) for how to play media using a VideoDrawing. However, I've discovered some issues that can result in a black frame when used in a WPF app. (.NET Framework 4.7.2) The goal is to play + show the video at the same time without a black frame being seen.

If there is some kind of UI update in the same region as the video drawing occurring at the same time transitioning from pause to play, a black frame can occur in that region. A black frame can also occur when the view becomes visible for the first time and trying to play, even when the video is already opened + loaded + paused with [ScrubbingEnabled](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.mediaelement.scrubbingenabled?view=netframework-4.7.2) set to `true`. The video itself does not have a black frame.

Where I'm at now: have the opacity start at 0 for the view and "reveal" after a short delay when first showing the view + playing. Before the video is loaded and ready, a separate first-frame image is displayed to ensure something is visible while the player is loading + not visible.

A way to test for the first issue is to cover the VideoDrawing view with a semi-transparent view while the video is paused. Can then be seen that the video is indeed loaded + paused. Marking the covering view `Visiblity.Hidden` and hitting play at the same time can result in a black region where the covering view was.

---
#### Feedback Bot on 2021/6/11, 02:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2021/10/9, 05:04 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Please share a minimal repro to check this further.

**Comment by singhashish-wpf** [comment]
Closing in absence of a minimal repro/reply.
