### ISSUE TITLE
Access Violations in wpfgfx_v0400

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5666]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Access-Violations-in-wpfgfx_v0400/1366724)._

---
[severity:It's more difficult to complete my work]
Our company develops a large application using C# and WPF. One of our clients is complaining that the application crashes randomly . They are using the application and suddenly it is totally gone. A typical client has 1000's of users using our application daily.
To troubleshoot this problem we asked this client to enable crashdumps. We received multiple crashdumps. The thing they all have in common is crashing on what I would call the render thread. (wpfgfx_v0400). They have two distinct error codes: c0000005 (Access violation) and C0000374 (heap corruption). 

The client uses Windows 10 with .net Framework 4.8

I am able to provide the crashdumps if that is neccessary. Some are full crashdumps other are minidumps.

These stackdumps all seem to be what I would call a 'NullReferenceException'

Stackdump #1
STACK_TEXT:  
08edfa58 5fd9c1b0 40d60510 08edfa78 00000000 wpfgfx_v0400! CMilBrushDuce::GetRealizer+0x33
08edfa7c 5fd9a096 40a7ef08 40d60510 08edfaa4 wpfgfx_v0400! CDrawingContext::GetBrushRealizer+0x95
08edfae0 5fd9a2b9 40a7ef08 40fc04e8 53279900 wpfgfx_v0400! CDrawingContext::DrawGlyphRun+0x126
08edfb94 5fd9ae04 40d60210 53279900 5fd9adb0 wpfgfx_v0400! CMilSlaveRenderData::Draw+0x4d1
08edfbb4 5fd9ad71 40d60210 53279900 5fd9abb0 wpfgfx_v0400! CMilVisual::RenderContent+0x3c
08edfc7c 5fd991f5 08edfc94 40d60210 00000000 wpfgfx_v0400! CDrawingContext::PreSubgraph+0x780
08edfca8 5fd9f6f6 1fed2020 40d60228 40d60210 wpfgfx_v0400! CGraphIterator::Walk+0x4e
08edfcf0 5fd9b628 1fed2020 1ff8e1a0 08edfd18 wpfgfx_v0400! CDrawingContext::DrawVisualTree+0x16b
08edfd94 5fda0aa9 1fed2020 068844f4 1ff8e1a0 wpfgfx_v0400! CDrawingContext::Render+0x275
08edfe04 5fda08e4 08edfe2b 06852588 08edfecf wpfgfx_v0400! CSlaveHWndRenderTarget::Render+0x1e9
08edfe2c 5fd95b78 08edfecf 06852588 00000000 wpfgfx_v0400! CRenderTargetManager::Render+0x40
08edfe44 5fd93446 08edfecf 06852590 5fd934b0 wpfgfx_v0400! CComposition::Render+0x1f
08edfeb4 5fd934ff 08edfecf 06852590 5fd934b0 wpfgfx_v0400! CComposition::ProcessComposition+0x16f
08edfed0 5fd93550 08edfeeb 00000001 0683f168 wpfgfx_v0400! CComposition::Compose+0x3f
08edfeec 5fd92fd8 06852590 0683f168 5fd92fa0 wpfgfx_v0400! CPartitionThread::RenderPartition+0x25
08edff04 5fdc9245 3e4db478 5fdc9210 5fdc9210 wpfgfx_v0400! CPartitionThread::Run+0x4e
08edff2c 76486359 0683f168 76486340 08edff98 wpfgfx_v0400! CPartitionThread::ThreadMain+0x2f
08edff3c 778b8944 0683f168 46f84318 00000000 kernel32! BaseThreadInitThunk+0x19
08edff98 778b8914 ffffffff 778da0b5 00000000 ntdll!__RtlUserThreadStart+0x2f
08edffa8 00000000 5fdc9210 0683f168 00000000 ntdll!_RtlUserThreadStart+0x1b

Stackdump #2
STACK_TEXT:  
071bf1f8 6079c1b0 20abb7e0 071bf218 00000000 wpfgfx_v0400! CMilBrushDuce::GetRealizer+0x33
071bf21c 6079c8bf 433de8a8 20abb7e0 071bf244 wpfgfx_v0400! CDrawingContext::GetBrushRealizer+0x95
071bf248 6079f0f8 00000001 071bf404 071bf298 wpfgfx_v0400! CDrawingContext::FillOrStrokeShape+0x3b
071bf2cc 3f800000 071bf4a8 6079f57f 071bf404 wpfgfx_v0400! CDrawingContext::DrawShape+0x153
WARNING: Frame IP not in any known module. Following frames may be wrong.
071bf2dc 433de8a8 00000000 3f627471 00000000 0x3f800000
071bf404 608c6404 3f800000 3fc00000 3f800000 0x433de8a8
071bf408 3f800000 3fc00000 3f800000 3f9ca75e wpfgfx_v0400! CRectangleFigure::`vftable'

Stackdump #3
STACK_TEXT:  
0af7f2a8 5949c1b0 22f68b78 0af7f2c8 00000000 wpfgfx_v0400! CMilBrushDuce::GetRealizer+0x33
0af7f2cc 5949a096 9b947f98 22f68b78 0af7f2f4 wpfgfx_v0400! CDrawingContext::GetBrushRealizer+0x95
0af7f330 5949a2b9 9b947f98 9b9eb5b8 4f3b9fc8 wpfgfx_v0400! CDrawingContext::DrawGlyphRun+0x126
0af7f3e4 5949ae04 22f68878 4f3b9fc8 5949adb0 wpfgfx_v0400! CMilSlaveRenderData::Draw+0x4d1
0af7f404 5949ad71 22f68878 4f3b9fc8 5949abb0 wpfgfx_v0400! CMilVisual::RenderContent+0x3c
0af7f4cc 594991f5 0af7f4e4 22f68878 00000000 wpfgfx_v0400! CDrawingContext::PreSubgraph+0x780
0af7f4f8 5949f6f6 0121b170 22f68890 22f68878 wpfgfx_v0400! CGraphIterator::Walk+0x4e
0af7f540 5949b628 0121b170 1a34b0b8 0af7f568 wpfgfx_v0400! CDrawingContext::DrawVisualTree+0x16b
0af7f5e4 594a0aa9 0121b170 0f27befc 1a34b0b8 wpfgfx_v0400! CDrawingContext::Render+0x275
0af7f654 594a08e4 0af7f67b 0121d4a0 0af7f71b wpfgfx_v0400! CSlaveHWndRenderTarget::Render+0x1e9
0af7f67c 59495b78 0af7f71b 0121d4a0 00000000 wpfgfx_v0400! CRenderTargetManager::Render+0x40
0af7f694 59493446 0af7f71b 0121d4a8 594934b0 wpfgfx_v0400! CComposition::Render+0x1f
0af7f700 594934ff 0af7f71b 0121d4a8 594934b0 wpfgfx_v0400! CComposition::ProcessComposition+0x16f
0af7f71c 59493550 0af7f737 00000001 01178ea0 wpfgfx_v0400! CComposition::Compose+0x3f
0af7f738 59492fd8 0121d4a8 01178ea0 59492fa0 wpfgfx_v0400! CPartitionThread::RenderPartition+0x25
0af7f750 594c9245 3d989a6b 594c9210 594c9210 wpfgfx_v0400! CPartitionThread::Run+0x4e
0af7f778 749a6359 01178ea0 749a6340 0af7f7e4 wpfgfx_v0400! CPartitionThread::ThreadMain+0x2f
0af7f788 771f8944 01178ea0 a59a3ebb 00000000 kernel32! BaseThreadInitThunk+0x19
0af7f7e4 771f8914 ffffffff 7721a0ce 00000000 ntdll!__RtlUserThreadStart+0x2f
0af7f7f4 00000000 594c9210 01178ea0 00000000 ntdll!_RtlUserThreadStart+0x1b

Is this a known issue? Is there something I can recommend my client so they won't have this error anymore?

Thanks for your help

---
#### Feedback Bot on 3/11/2021, 10:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vikas Patel on 4/19/2021, 08:59 PM: 

<p>A large number of our clients are having same issue. Were you able to get a resolution from Microsoft on this?</p>

#### Folko Hettinga on 4/21/2021, 00:04 AM: 

<p>Hi Vikas. We also have multiple clients facing this issue, unfortunately no help from Microsoft…</p>

#### Feedback Bot on 7/5/2021, 11:35 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Please attach the crash dumps to check this further. If possible, a sample repro will be super helpful.

**Comment by singhashish-wpf** [comment]
Closing as no further information was available.
