### ISSUE TITLE
WPF Richtextbox crashed when typing chinese use win10 default typewriting

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5667]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/WPF-Richtextbox-crashed-when-typing-chin/1344292)._

---
[severity:It's more difficult to complete my work]
1:.net 4+
2:use richtextbox 
   
```

            
                
                    
                        Symbol: B
                    
                    
                        Atomic Mass: 10.811
                    
                
            
        
```
3:type any words
! [16137863867541.png] (https://aka.ms/dc/image?name=Ba0c70cb6de85429a8e23cebd0fa73e11637493832317045466_16137863867541.png&tid=a0c70cb6de85429a8e23cebd0fa73e11637493832317045466)
4:click mouse at richtextbox ,it will send character into origin words
! [16137864988634.png] (https://aka.ms/dc/image?name=Baa9425d536114c61a45dbf84ebd657b4637493834660095318_16137864988634.png&tid=aa9425d536114c61a45dbf84ebd657b4637493834660095318)
5:select current line
! [16137867072318.png] (https://aka.ms/dc/image?name=B383224d3741749018466233841d0ff7a637493835495274861_16137867072318.png&tid=383224d3741749018466233841d0ff7a637493835495274861)
6:type any character
 
crashed

---
#### Feedback Bot on 2/19/2021, 10:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/31/2021, 08:23 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Please share a minimal repro to check this further.

**Comment by singhashish-wpf** [comment]
Closing as no further information is available.
