### ISSUE TITLE
WPF BitmapCache issue

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5672]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/WPF-BitmapCache-issue/1085122)._

---
There is an issue in WPF, when BitmapCache is used.
Just try to reproduce the following steps with the attached solution:
1. Run the application
2. Click the "Minimize and create" button (the main window will minimize and the child window will be shown with a lot of dashed lines and maximized)
3. Press Win+L to lock user session
4. Login to the user account
5. Hover the "Push "button
6. Open Task manager and pay attention to the CPU and GPU consumption and window freeze
7. Click the "Push" button (the main window will be shown and the problem with the freeze and the consumption will be gone)

---
#### Feedback Bot on 6/19/2020, 02:08 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/23/2020, 06:33 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Closing as no further information is available.
