### ISSUE TITLE
WPF Datagrid TargetDefaultValueConverter fails with System.Windows.Data Error: 6

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5673]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/WPF-Datagrid-TargetDefaultValueConverter/1140535)._

---
I have an Expander control containing aListView as the content of a Datagrid column.  When the Expander is expanded, the listview displays the results but throws this error:

>System.Windows.Data Error: 6 : 'TargetDefaultValueConverter' converter failed to convert value '∞' (type 'Double'); fallback value will be used, if available. BindingExpression:Path=MaxHeight; DataItem='Border' (Name='Content'); target element is 'RowDefinition' (HashCode=17754702); target property is 'Height' (type 'GridLength') ArgumentException:'System.ArgumentException: 'value' parameter cannot be Infinity.
>   at System.Windows.GridLength.. ctor(Double value, GridUnitType type)
>   at System.Windows.GridLengthConverter.ConvertFrom(ITypeDescriptorContext typeDescriptorContext, CultureInfo cultureInfo, Object source)
>   at MS. Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
>   at MS. Internal.Data.TargetDefaultValueConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
>   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'

Upon further testing, I found it does not matter what gets put in the expander.  The error occurrs yet the display of the result is correct.  What is going on and how can I get rid of the error please?
Here is the XAML:

<DataGridTemplateColumn HeaderStyle="{StaticResource MyDGColumnHeaderStyle}"
                                CanUserResize="True" CanUserSort="True" SortMemberPath="AttribVisible" 
                                SortDirection="Ascending" Width="20" >
                            <DataGridTemplateColumn.Header>
                                <Grid>
                                    <ctls:MyBasicButton Style="{StaticResource MyImageOnlyButtonStyle}" 
                                        DataContext="{Binding RelativeSource={RelativeSource FindAncestor, 
                                            AncestorType={x:Type UserControl}}, Path=DataContext}"
                                        ButtonName="reg.btn_AttribHeader" CanUseAlternateText="False"
                                        Image="{StaticResource TagBlue}"
                                        MaxImageSize="18"
                                        Background="Transparent" BorderThickness="0"
                                        HorizontalAlignment="Center" VerticalAlignment="Center" 
                                        HorizontalContentAlignment="Left" Margin="2,0,2,0"
                                        Command="{Binding ButtonPressedCommand, Source={StaticResource viewmodelbase}}" 
			                            CommandParameter="{Binding Mode=OneWay, RelativeSource={RelativeSource Self}}"
                                        Click="HeaderButton_Click">
                                    </ctls:MyBasicButton>
                                </Grid>
                            </DataGridTemplateColumn.Header>
                            <DataGridTemplateColumn.CellTemplate>
                                <DataTemplate>
                                    <Grid>
                                        <Expander Margin="0" Style="{StaticResource MyExpanderStyle}"
                                                  Visibility="{Binding AttribVisible, Converter={StaticResource BoolToVisibilityConverter}}">
                                            <Expander.Header>
                                                <Grid>
                                                    <Image Source="{StaticResource TagBlue}"
                                                            Width="14" Height="14" Margin="0,0,0,0"
                                                            HorizontalAlignment="Left" VerticalAlignment="Center"/>
                                                </Grid>
                                                </Expander.Header>
                                            <ListView Style="{StaticResource MyListViewStyle}"
                                                      ignore:ItemsSource="{Binding AttribList}">
                                                    <ListViewItem>ListView 1</ListViewItem>
                                                    <ListViewItem>ListView 2</ListViewItem>
                                                    <ListViewItem>ListView 3</ListViewItem>
                                            </ListView>
                                        </Expander>
                                    </Grid>
                                </DataTemplate>
                            </DataGridTemplateColumn.CellTemplate>
                        </DataGridTemplateColumn>

---
#### Feedback Bot on 8/7/2020, 02:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/20/2020, 01:43 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Please share the sample repro to check this further.

**Comment by singhashish-wpf** [comment]
Closing in absence of a minimal repro/reply.
