### ISSUE TITLE
Code Loading and Styling FlowDocument Must Produce an Error In Order to Function

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5676]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-Loading-and-Styling-FlowDocument-Mu/1545618)._

---
[severity:Other]

Private Sub Window_Loaded(sender As Object, e As RoutedEventArgs) Handles MyBase.Loaded

' Loads the content to display...
        rtbDisplay.Document = pFldContent
        rtbDisplay.IsEnabled = True

' Changes the name of the window...
        txtTitle.Text = pStrHandle
        ' Prepares to handle 
        Dim strInput As String = GetTheme(pIntWork)
        Dim strTheme As String()
        Dim strType As String = ""
        Dim strOutput As String = ""
        ' Attempts to avoid crashing...
        Try
            ' Loops through every paragraph in the display...
            For Each itmBlock As Paragraph In rtbDisplay.Document.Blocks
                ' Loops through every inline in the active paragraph...
                For Each itmInline As Inline In itmBlock.Inlines
                    ' Loops through every object in the active inline's children...
                    For Each itmObject As Object In LogicalTreeHelper.GetChildren(itmBlock)
                        ' Attempts to avoid crashing...
                        Try
                            ' Responds to User Interface Containers...
                            If itmObject.GetType = GetType(InlineUIContainer) Then
                                ' Treats the found children as inline user interface containers...
                                Dim objTest As InlineUIContainer = itmObject
                                ' Obtains theme settings...
                                strTheme = Split(strInput, ",")
                                ' Gets the object type of the item in the container...
                                strType = objTest.Child.GetType.ToString
                                strType = Right(strType, Len(strType) - InStrRev(strType, "."))
                                ' Responds based on item type...
                                Select Case strType
                                    Case "TextBox"
                                        ' Treats the child item type as a text box...
                                        Dim objText As TextBox = objTest.Child
                                        ' Works with the text box...
                                        With objText

. FontFamily = New FontFamily(strTheme(7))
                                            . FontSize = CDbl(strTheme(8))
                                            . Foreground = New SolidColorBrush(ColorConverter.ConvertFromString(strTheme(9)))
                                            . Padding = New Thickness(strTheme(10))
                                            . Background = New SolidColorBrush(ColorConverter.ConvertFromString(strTheme(11)))
                                            . BorderBrush = New SolidColorBrush(ColorConverter.ConvertFromString(strTheme(12)))
                                            . BorderThickness = New Thickness(1)
                                            . Margin = New Thickness(0)

End With

Case "ComboBox"

'   THIS NEVER HAPPENS  

' Treats the ui container item type as a combo box...
                                        Dim objCombo As ComboBox = objTest.Child

' Attempts to locate the template parent for editing (this works, but it only affects part of the design)...
                                        ' * This section generates an error.  When the error is suppressed, the window does NOT color the combo box *
                                        Dim tbTemp As TextBox = objCombo.Template.FindName("PART_EditableTextBox", objCombo)
                                        Dim svTemp As ScrollViewer = tbTemp.Template.FindName("PART_ContentHost", tbTemp)

With svTemp
                                            . Background = New SolidColorBrush(ColorConverter.ConvertFromString(strTheme(11)))
                                        End With
                                        ' * This section generates an error.  When the error is suppressed, the window does NOT color the combo box *

Try
                                            ' Adds a style resource to the combo box that sets the colors for the popup...
                                            If objCombo.Resources.Count = 0 Then
                                                ' Sets the background...
                                                objCombo.Resources.Add(SystemColors.WindowBrushKey, New SolidColorBrush(ColorConverter.ConvertFromString(strTheme(11))))
                                                ' Sets the border...
                                                objCombo.Resources.Add(SystemColors.WindowFrameBrushKey, New SolidColorBrush(ColorConverter.ConvertFromString(strTheme(12))))
                                                objCombo.Resources.Add(SystemColors.ControlTextBrushKey, New SolidColorBrush(ColorConverter.ConvertFromString(strTheme(11))))
                                            End If
                                        Catch ex As Exception
                                            MsgBox(ex. Message)
                                        End Try

' Works with the combo box...
                                        With objCombo

. FontFamily = New FontFamily(strTheme(7))
                                            . FontSize = CDbl(strTheme(8))
                                            . Foreground = New SolidColorBrush(ColorConverter.ConvertFromString(strTheme(9)))
                                            . Padding = New Thickness(strTheme(10))
                                            '. Background = New SolidColorBrush(ColorConverter.ConvertFromString(strTheme(11)))
                                            '. BorderBrush = New SolidColorBrush(ColorConverter.ConvertFromString(strTheme(12)))
                                            . BorderThickness = New Thickness(1)
                                            . Margin = New Thickness(0)

End With

Case "Button"
                                        ' Treats the child item type as a button...
                                        Dim objButton As Button = objTest.Child
                                        ' Only works with text buttons...
                                        If objButton.Name <> "btnColor" And objButton.Name <> "btnImage" Then
                                            ' Works with the button...
                                            With objButton

. FontFamily = New FontFamily(strTheme(13))
                                                . FontSize = CDbl(strTheme(14))
                                                . Foreground = New SolidColorBrush(ColorConverter.ConvertFromString(strTheme(15)))
                                                . Padding = New Thickness(strTheme(16))
                                                . Background = New SolidColorBrush(ColorConverter.ConvertFromString(strTheme(17)))
                                                . BorderBrush = New SolidColorBrush(ColorConverter.ConvertFromString(strTheme(18)))
                                                . Margin = New Thickness(strTheme(19))
                                                . BorderThickness = New Thickness(1)

End With
                                        End If

End Select
                            End If

Catch ex As Exception
                            ' Stores messages...
                            strOutput &= ex. Message & vbCrLf
                        End Try

Next

Next

Next

Catch ex As Exception
            ' Notifies the user...
            MsgBox(ex. Message, vbExclamation, "Window Style Error")
        End Try

End Sub

---
#### Feedback Bot on 10/4/2021, 08:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by pchaurasia14** [comment]
This issue needs a sample repro in order for us to troubleshoot.
