### ISSUE TITLE
MSBuildProjectExtensionsPath not handled correctly in GenerateTemporaryTargetAssembly

### ISSUE THREAD

**Issue by zivkan** [dotnet/wpf#5679]
* .NET Core Version: 6.0.100
* Windows version: n/a
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

 
 
 **Problem description:** A customer reported this issue to NuGet: https://github.com/NuGet/Home/issues/4463#issuecomment-964986638

I'm reporting it here, but @mkonijnenburg is the affected customer

 **Actual behavior:** 
 
> C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1004: Assets file 'C:\src\test\wpfArtifacts\obj\MyApp_3j03kfnj_wpftmp\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\src\test\wpfArtifacts\src\MyApp\MyApp_3j03kfnj_wpftmp.csproj]

 **Expected behavior:**

Build successfully
 
 **Minimal repro:**

Create `Directory.Build.props`:

```xml
<Project>
    <PropertyGroup>
        <BaseOutputPath>$(MSBuildThisFileDirectory)bin\$(MSBuildProjectName)\</BaseOutputPath>
        <MSBuildProjectExtensionsPath>$(MSBuildThisFileDirectory)obj\$(MSBuildProjectName)\</MSBuildProjectExtensionsPath>
        <IntermediateOutputPath>$(MSBuildThisFileDirectory)obj\$(MSBuildProjectName)\$(Configuration)\</IntermediateOutputPath>
    </PropertyGroup>
</Project>
```

then `dotnet new wpf -n MyApp ; dotnet new sln ; dotnet sln add MyApp ; dotnet build`

If I use `global.json` to pin the .NET SDK to 5.0.x, then this problem does not reproduce.

**Comment by mkonijnenburg** [comment]
A quick non-generic workaround

<Project>
	<Choose>
		<When Condition="$([System.Text.RegularExpressions.Regex]::IsMatch($(MSBuildProjectName), '^ProjectA.*_[0-9a-z]{8}_wpftmp$'))">
			<PropertyGroup>
				<BaseOutputPath>bin\ProjectA\</BaseOutputPath>
				<MSBuildProjectExtensionsPath>obj\ProjectA\</MSBuildProjectExtensionsPath>
				<IntermediateOutputPath>obj\ProjectA\$(Configuration)\</IntermediateOutputPath>
			</PropertyGroup>
		</When>
		<When Condition="! $([System.Text.RegularExpressions.Regex]::IsMatch($(MSBuildProjectName), '^.*_[0-9a-z]{8}_wpftmp$'))">
			<PropertyGroup>
				<BaseOutputPath>bin\$(MSBuildProjectName)\</BaseOutputPath>
				<MSBuildProjectExtensionsPath>obj\$(MSBuildProjectName)\</MSBuildProjectExtensionsPath>
				<IntermediateOutputPath>obj\$(MSBuildProjectName)\$(Configuration)\</IntermediateOutputPath>
			</PropertyGroup>
		</When>
	</Choose>
</Project>

**Comment by pchaurasia14** [comment]
With the steps to reproduce mentioned above, it looks like things are working fine with the new SDK releases. 

Please let us know if that is not the case.

![image](https://user-images.githubusercontent.com/105205215/173232225-dbb8ea48-88bf-45d5-b38e-f1bf99c55e3a.png)
