### ISSUE TITLE
A11y ListBoxItems cause the error "An element's IsOffScreen property must be false when its clickable point is on screen"

### ISSUE THREAD

**Issue by dkandrov** [dotnet/wpf#5686]
* .NET Core Version: .NET SDK 5.0.403
* Windows version: Windows 10 - 21H1 build 19043.1348
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

 
 
 **Problem description:**
 When you use ListBox in your forms and this ListBox contains many items which couldn't be displayed all in one time then you get an a11y error from the Accessibility Insights tool: "An element's IsOffScreen property must be false when its clickable point is on screen"
![screenshot](https://user-images.githubusercontent.com/5506989/141305442-21751c56-6721-473d-9d93-4c424850c58f.png)

If you scroll elements down and up and start a11y test again:
![screenshot2](https://user-images.githubusercontent.com/5506989/141306661-84112ad9-108b-4784-8554-0c2160dbefee.png)

In the Accessibility Insights tool repo, they have a similar issue which was closed because that is the problem of WPF: https://github.com/microsoft/axe-windows/issues/539#issuecomment-797633889

 **Actual behavior:** 
The Accessibility Insights tool shows an error: "An element's IsOffScreen property must be false when its clickable point is on screen"
 **Expected behavior:**
The Accessibility Insights tool should not show errors about this.
 **Minimal repro:*
[WpfAppListBox.zip](https://github.com/dotnet/wpf/files/7520666/WpfAppListBox.zip)
*

**Comment by singhashish-wpf** [comment]
This is fixed in RC1
#4631
