### ISSUE TITLE
.NET 6 Tooltip behavior change from .NET 5 (bug?)

### ISSUE THREAD

**Issue by Felix-Dev** [dotnet/wpf#5703]
* .NET Version: 6.0.100
* Windows version: 21H1 (19043.1165)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Not checked

 
 
 **Problem description:**
After upgrading a WPF app from .NET 5 (SDK 5.0.402) to .NET 6, new tooltips are no longer shown without delay when leaving a UI element by mouse for which a tooltip is currently open.

See the following XAML:
````code
<StackPanel Orientation="Horizontal"
        HorizontalAlignment="Center"
        VerticalAlignment="Center">
    <Button Content="Button 1"
        ToolTip="Button 1 tooltip"
        ToolTipService.Placement="MousePoint"
        ToolTipService.VerticalOffset="-50"
        ToolTipService.HorizontalOffset="-45"
        ToolTipService.InitialShowDelay="1000"
        ToolTipService.BetweenShowDelay="1000"
        ToolTipService.ShowDuration="4000"/>
    <Button Content="Button 2"
        ToolTip="Button 2 tooltip"
        ToolTipService.Placement="MousePoint"
        ToolTipService.VerticalOffset="-50"
        ToolTipService.HorizontalOffset="-45"
        ToolTipService.InitialShowDelay="1000"
        ToolTipService.BetweenShowDelay="1000"
        ToolTipService.ShowDuration="4000"/>
</StackPanel>
````

And the resulting tooltip behavior for both .NET 5 and .NET 6:
| .NET 5 | .NET 6 |
| ------------- | ------------- |
| ![WPF tooltip behavior NET 5](https://user-images.githubusercontent.com/1398851/142207902-9d2730ab-c263-4a5f-8b5a-834c17dc043d.gif)  | ![WPF tooltip behavior NET 6](https://user-images.githubusercontent.com/1398851/142207956-7b6ddcff-65fe-4dd5-8ec7-9cc1fd74e406.gif) |

As you can see, the tooltip for "Button 2" is no longer shown immediately after entering it with the mouse as it does in the .NET 5 app. This is especially problematic in an app which uses a (WinUI-styled) NumberBox control with two adjacent spinner buttons both with their own tooltips (such as "Increase/Decrease by 0.1"):
![image](https://user-images.githubusercontent.com/1398851/142208809-34321f28-0bba-4826-a2c0-15068c81e808.png)

I suspect this behavior change was introduced by the tooltip work for .NET 6, i.e. in PR https://github.com/dotnet/wpf/pull/4623. Is this behavior change intended or is this a bug? Personally, this looks like a bug to me as it negatively affects the user experience in my view. The tooltip for "Button 1" should no longer be shown when the mouse enters "Button 2" which has its own tooltip - and which should show immediately based on the `ToolTipService.BetweenShowDelay` setting.

@SamBent FYI as you worked on the tooltip changes for .NET 6.
 
 **Expected behavior:**
Same as in .NET 5.
 
 **Minimal repro:**
[WPF issue.zip](https://github.com/dotnet/wpf/files/7554940/WPF.issue.zip) (Just change the framework from .NET 5 to .NET 6 to see the .NET 6 behavior.)

**Comment by lindexi** [comment]
@Felix-Dev See https://github.com/dotnet/wpf/issues/4612
