### ISSUE TITLE
Different window display between design mode and run mode due to borders.

### ISSUE THREAD

**Issue by Perpete** [dotnet/wpf#5707]
Hello,

In WPF, I notice that there is a display difference between the window creation support and the display of the window in run mode.
This difference can cause an inappropriate display in run mode.
The useful area of the designer mode display includes borders that are not visible to the user.
Even if the WindowStyle property is None, these invisible borders are still there.

During my research on the net, I found an indication of this problem already in 2013 and still without any correction to this day.

![Window_Design_Run](https://user-images.githubusercontent.com/66659162/142371397-0c4e650a-a8d0-475f-9c7d-ab6628fd689b.png)

Run mode display on designer mode display.
You can see the edges.
![RunOnDesign](https://user-images.githubusercontent.com/66659162/142371457-37b0b1c2-c71a-4591-8420-84e462804f90.png)

**Comment by singhashish-wpf** [comment]
This needs to be checked by Visual Studio Designer.

**Comment by singhashish-wpf** [comment]
Please use Visual Studio Feedback channel for this bug and we shall close it here.
