### ISSUE TITLE
WPF breaking change in binding net5 

### ISSUE THREAD

**Issue by Apskalle** [dotnet/wpf#5710]
Binding a TextBox to a decimal source and entering a negative value throws an error in the default converters ConvertBack method if culture is "sv-SE".  
This always worked fine in the Framework and if culture is instead "en-US" it still works as expected in net5.

```
System.Windows.Data Error: 7 : ConvertBack cannot convert value '-100,00' (type 'String'). BindingExpression:Path=Value; DataItem='MyModel' (HashCode=24981566); target element is 'TextBox' (Name=''); target property is 'Text' (type 'String') FormatException:'System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Convert.ToDecimal(String value, IFormatProvider provider)
   at System.String.System.IConvertible.ToDecimal(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at MS.Internal.Data.SystemConvertConverter.ConvertBack(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertBackHelper(IValueConverter converter, Object value, Type sourceType, Object parameter, CultureInfo culture)'
```

To reproduce

In overridden OnStartUp

  ```
  protected override void OnStartup(StartupEventArgs e)
        {
            var vCulture = new CultureInfo("sv-SE");
            Thread.CurrentThread.CurrentCulture = vCulture;
            Thread.CurrentThread.CurrentUICulture = vCulture;
            CultureInfo.DefaultThreadCurrentCulture = vCulture;
            CultureInfo.DefaultThreadCurrentUICulture = vCulture;

            FrameworkElement.LanguageProperty.OverrideMetadata(
            typeof(FrameworkElement),
            new FrameworkPropertyMetadata(XmlLanguage.GetLanguage(CultureInfo.CurrentCulture.IetfLanguageTag)));
            base.OnStartup(e);
        }
```
In MainWindow.xaml.cs

 ```
public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            this.DataContext = new MyModel();

        }
    }

    public class MyModel
    {
        public MyModel()
        {
        }

        public decimal Value { get; set; } = 100;

    }
```
In MainWindow.xaml

```
<Window x:Class="TestCoreBinding.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:TestCoreBinding"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <StackPanel Orientation="Vertical">
        <TextBox Text="{Binding Path=Value, StringFormat=N2, UpdateSourceTrigger=PropertyChanged}"/>
        <TextBlock Text="{Binding Path=Value, StringFormat='Value={0:N2}'}"/>
    </StackPanel>
</Window>
```

Cheers,

/Martin

**Comment by lindexi** [comment]
See https://github.com/dotnet/csharplang/issues/5442 ?

**Comment by Apskalle** [comment]
You think they are related? 
Feels like a pretty breaking change. Solved it by providing a custom converter. Another workaround could be to supply a ConverterCulture in the binding, didnt test that though.

**Comment by singhashish-wpf** [comment]
@Apskalle Is it working fine in .Net Framework? If yes, which version?

**Comment by Apskalle** [comment]
Everyone I tested so far, currently on 4.5.2

/M
Från: Ashish Kumar Singh ***@***.***>
Skickat: den 23 november 2021 08:16
Till: dotnet/wpf ***@***.***>
Kopia: Martin Ågren ***@***.***>; Mention ***@***.***>
Ämne: Re: [dotnet/wpf] WPF breaking change in binding net5 (Issue #5710)


@Apskalle<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FApskalle&data=04%7C01%7C%7C9065d326c3204dd49e7f08d9ae511783%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637732485582347123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=s3g4Ev3UYB5YdUovzW0E%2FlV76IyKXgc89eJ%2Bd1sb6MY%3D&reserved=0> Is it working fine in .Net Framework? If yes, which version?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwpf%2Fissues%2F5710%23issuecomment-976216314&data=04%7C01%7C%7C9065d326c3204dd49e7f08d9ae511783%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637732485582357074%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=T%2FqoXFOlvrlDzjmG5KE%2FLfyOq9yJeJXsYm9QlJJ3qjY%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADXJMS7LKGVYZDDKK6VBX43UNM5SRANCNFSM5IJ3VJOA&data=04%7C01%7C%7C9065d326c3204dd49e7f08d9ae511783%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637732485582367039%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FkbwynLKjGV4aSzfsI7F3QVEDTVLJ7ypQWUTreS6Cik%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C9065d326c3204dd49e7f08d9ae511783%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637732485582376996%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BWcD5GeuQVV3t5jBg6E8yjRBudsqHoIe66gwJi5ptU8%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C9065d326c3204dd49e7f08d9ae511783%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637732485582386945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NgHJW8c9cAtUD2dtA2jGu5QDKCDJ2dh4rlZfY6xMB%2FE%3D&reserved=0>.

**Comment by rabbitism** [comment]
Please check more on this issue 
https://github.com/dotnet/runtime/issues/40922

**Comment by Apskalle** [comment]
Quote: NegativeSign for my NumberFormat was changed from "-" to "−"

This seems strange, the new value "−" (codepoint 8722) cannot even be produced on a swedish win keybord where both hyphen and numeric key minus translate to "-" (codepoint 45)  

/M

**Comment by singhashish-wpf** [comment]
@Apskalle is this still reproducible?

**Comment by dipeshmsft** [comment]
Closing this issue as it doesn't reproduce anymore.
