### ISSUE TITLE
The text contained in the label appears in duplicate when editing it

### ISSUE THREAD

**Issue by Perpete** [dotnet/wpf#5723]
Hello,

On the window in design mode, the text contained in a label appears in duplicate and shifted when editing it.
I am using visual studio 17.0.1 with net 6.
This problem was already present in the last updates of version 16 of visual studio.

![LabelWPF](https://user-images.githubusercontent.com/66659162/142816213-11767dbc-a2e9-4479-abd8-e9a27c5b7cfa.gif)

**Comment by Symbai** [comment]
If this appears only in the designer you should submit the issue via Visual Studio (Help -> Feedback -> Submit a problem) because the XAML designer is a different team than the WPF repo owner.

**Comment by singhashish-wpf** [comment]
This is not related to WPF, please raise a ticket with Visual Studio, XAML designer.
