### ISSUE TITLE
Visual Studio 2019 Visual Basic .Net "Mouse Event(s) not working correctly using WPF"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5750]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Visual-Studio-2019-Visual-Basic-Net-Mo/1312304)._

---
[severity:It bothers me. A fix would be nice]
Hi,

I just started to get back into playing with Visual Basic using WPF with .Net 4.8 Framework within VS 2019 Community and found myself trying to figure out why the mouse event(s) weren't been triggered. The main WPF window handled the mouse event(s) worked the way that is was supposed too, but none of any container based object(s) "e.g. Grid, Border, StackPanel, and so on..." that I tried to use within the main window container would not trigger any of the mouse event's at all. But not until I had changed the background color of a given container control to another color other then the background color that the main window was set too, then all the mouse events within that given container control worked as attended.

So if it is possible for someone that has some free time on there hand's would be able to not only confirm this issue that I'm having in VB, but also to see if this also effects other languages such as C# that support's WPF development to be on the safe side and hope that this issue can be resolved.

Thank you for your time,

Gordon.

---
#### Feedback Bot on 1/17/2021, 05:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/11/2021, 01:04 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by MichaeIDietrich** [comment]
Maybe this clarifies a bit what is happening and how hit testing works: 
https://docs.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/hit-testing-in-the-visual-layer?redirectedfrom=MSDN&view=netframeworkdesktop-4.8#hit-testing-scenarios

Might it be that the `Background` of those elements is set to `null`? If so, they are invisible to hit testing and won't handle any mouse events. Setting the `Background` to anything else but `null` (e.g. `Transparent`) would make them participate in hit testing.

Does this solve your issue?

**Comment by pchaurasia14** [comment]
@MichaeIDietrich - Thank you so much for the response. 

In absence of the reply from original author, we are closing this issue,
