### ISSUE TITLE
WPF ListView bug when you add item and show it in the same time

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5751]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/WPF-ListView-bug-when-you-add-item-and-s/1308391)._

---
[severity:It bothers me. A fix would be nice]
Detail:

I Put a ListView in a Window control. After the programs stat, the Window remain hide.

I Put an item into the ListView, and if the window is hide, the Show method of the Window will be called, to show a Window that contain the ListView. 

ListView will show two item in its view, and the second one is not delete-able. 

![demo.gif](https://aka.ms/dc/image?name=B14c7d9aedf1246e5b63435efb33239a2637461410606722103_demo.gif&tid=14c7d9aedf1246e5b63435efb33239a2637461410606722103)

Here is the Demo code to produce this problem:

https://github.com/weiqi-chen-domino/ListView-Bug

---
#### Feedback Bot on 1/13/2021, 07:26 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 4/13/2021, 03:51 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
[ListView-Bug-master_fixed.zip](https://github.com/dotnet/wpf/files/9010291/ListView-Bug-master_fixed.zip)
This seems an issue with the app(user code)
The attached solution seems to work as expected.
