### ISSUE TITLE
Type error in System.Windows.Media

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5753]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Erreur-de-type-dans-SystemWindowsMedia/1264233?preview=true)._

---
[severity:It bothers me. A fix would be nice] [regression]
With the latest VS 2019 update, in a WPF application under Framework 4.7.2

Error with Colors in System.Windows.Media.

CS0029 Error - Can't implicitly convert the 'System.Windows.Media.Color' type to 'System.Windows.Media.Colors' - TstAchPuzzle D: 'Documents'Visual Studio 2019'Projects-Ach-TstAchPuzzle'.cs 27 Active

public Piècette (int index)
        {
            Index - index;
            Colors c - Colors.Gray;

if (index % 2 - 0) - c - Colors.Gray; 'otherwise c' Colors.DarkGray;

path - new Path()
            {
                Stroke - new SolidColorBrush (c),
                StrokeThickness - 0
            };

}
If the variable "c" is defined as "var," then the error disappears.

---
#### Feedback Bot on 11/22/2020, 06:49 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/19/2021, 10:06 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by pchaurasia14** [comment]
Please provide sample reproduction for further investigation

**Comment by miloush** [comment]
The repro is more readable on the Developer Community website. This is an error on the developer side.

The error is here:
```C#
Colors c = Colors.Gray;
```

the `Colors.Gray` is of type `Color` not `Colors` which is a static type. Using `var` infers the correct type automatically.
