### ISSUE TITLE
Textbox inside WPF Custom Control in DLL doesn't work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5755]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Textbox-inside-WPF-Custom-Control-in-DLL/1207866)._

---
[severity:I'm unable to use this version of Visual Studio]
Don't know where else to post this issue.  It's with every version of VS, and has been for years now.  No one fixes it.  

I have made a .NET Library project in C#, that includes a WPF Custom Control inside that library; which has a Textbox inside of the custom control.

I have also made a WPF Windows Application, and referenced the above assembly.  Then I have added the WPF Custom Control to my window.  

Once loaded, the textbox inside that custom control, will not function.  It will not accept keyboard input, and even if you change the test manually, it won't change the display, however inside the debugger, you can see the value actually did change, just not the display....  Now, whats weird is if you paste text into it, it will display that, but if you type nothing.

Now, if you re target your library project to a windows application and load it from there, every time works great.  Only once it becomes a secondary binary loaded by another will it not work.  What is going on with that?  I actually don't care why, what are the fixes, and when are you guys going to correct this bug?

Please correct this, it's delaying our project which is going to cost us a lot of money.

---
#### Feedback Bot on 10/2/2020, 04:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/19/2021, 00:07 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by miloush** [comment]
I tried both user and custom control using 4.8 and cannot repro.

**Comment by singhashish-wpf** [comment]
Closing as no further information was available.
