### ISSUE TITLE
WPF RichTextBox misses key strokes when spell check kicks on.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5756]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/WPF-RichTextBox-misses-key-strokes-when-/1184194)._

---
<p>After the windows update KB4562900.  When the spell check finds a misspelled word the rich text box misses key strokes.  Only happens with the update applied.  We have noticed that turning on cap lock helps but that is not a solution of out client.  </p>

---
#### Feedback Bot on 9/15/2020, 02:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/19/2021, 00:07 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Closing the thread in absence of any response. Please register a new issue if this persists on .NET6
