### ISSUE TITLE
Screensaver Preview.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5757]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Screensaver-Preview/1182904)._

---
<p>I have created a screensaver that supports multiscreen in WPF.
The preview was working fine, but with DPI support, the preview is no longer available.
StackTrace:
The hosted HWND must be a child window of the specified parent.
System.Windows.Interop.HwndHost.BuildWindow (HandleRef hwndParent)
System.Windows.Interop.HwndHost.BuildOrReparentWindow ()
System.Windows.Interop.HwndHost.OnSourceChanged (Object sender, SourceChangedEventArgs e)
System.Windows.RoutedEventArgs.InvokeHandler (Delegate handler, Object target)
System.Windows.RoutedEventHandlerInfo.InvokeHandler (Object target, RoutedEventArgs routedEventArgs)
System.Windows.EventRoute.InvokeHandlersImpl (Object source, RoutedEventArgs args, Boolean reRaised)
System.Windows.UIElement.RaiseEventImpl (DependencyObject sender, RoutedEventArgs args)
Is there a workaround?</p>

---
#### Fiona Niu[MSFT] on 9/14/2020, 01:50 AM: 

<p>Thank you for your feedback! In order for us to investigate this further, could you please provide repro steps, a more detailed description of the issue to help us better understand this scenario? It would be very helpful if you could provide some screenshots of this problem.<br>
We look forward to hearing from you!</p>

#### MORICHIKA AKIRA on 9/14/2020, 04:04 AM: 

<p>こんにちは。</p><p>スクリーンセーバーの設定画面で、小さなモニタ内で表示されるプレビューは、,"HwndSource"の"RootVisual"に描画を設定しています 。</p><p>この時、HwndSourceParameters のParentWindowがDPIに対応していない場合、以下のエラーになります。</p><p>"ホストされるHWNDは、指定された親の子ウィンドウである必要があります。"</p><p>WPFで作成したスクリーンセーバのマニュフェストにDPIサポートを記述してビルドすれば再現します。</p>

#### Feedback Bot on 9/14/2020, 06:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/19/2021, 00:07 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by dipeshmsft** [comment]
Closing this issue due to lack of information to proceed.
