### ISSUE TITLE
After installing August 2020 cumulative update for. Net, the WPF RTF Control is laggy when spellchecking is enabled.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5758]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/After-installing-August-2020-cumulative-/1169412)._

---
<p>After installing August 2020 cumulative update for. Net, the WPF RTF Control is laggy when spellchecking is enabled. i.e you can type multiple characters before the text is shown on the screen. We have tested this in Windows 10 version 1803, 1909 and 2004 and the problem is the same on all versions. A similar problem was also present in . Net4.5<br><br>We suspect this a problem introduced by the following change in the update:
&quot;- Improved spell checking so words like &quot;etc.&quot; and &quot;e.g.&quot; will no longer be identified as spelling errors when spell-checking is enabled in WPF TextBox or RichTextBox&quot;</p>

---
#### Feedback Bot on 9/1/2020, 01:40 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jeppe Mølbak Hansen on 10/21/2020, 05:52 AM: 

(private comment, text removed)
#### Feedback Bot on 12/2/2020, 06:45 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Is this still an issue in latest .NET releases? Could you please confirm?

**Comment by singhashish-wpf** [comment]
Closing in absence of any response.
