### ISSUE TITLE
Xaml can't find a class declared in the same assembly when using an MSBuild variable in AssemblyName

### ISSUE THREAD

**Issue by loicmorvan-ansys** [dotnet/wpf#5767]
* .NET Core Version: 6.0.0 (commit 4822e3c3aa)
* Windows version: 10.0.22000
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No, as said in this issue from Developer Community : https://developercommunity.visualstudio.com/t/Xaml-cant-find-a-class-declared-in-the/1596965
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/main/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**
I declare a class in a project and want to use it directly in Xaml in that same project.
This works well until I change the `AssemblyName` of the project to `Test.$(MSBuildProjectName)`.

In that case, when building, an error is output.
 
 **Actual behavior:** 
 
The error is: `MC3048 '{local:MarkupConverter}' value is not a valid MarkupExtension expression. Cannot resolve 'MarkupConverter' in namespace 'clr-namespace:BugReproduction.Converters'. 'MarkupConverter' must be a subclass of MarkupExtension. Line 11 Position 11.	BugReproduction	C:\Users\lmorvan\source\repos\BugReproduction\BugReproduction\Controls\Page1.xaml`

 **Expected behavior:**

The project should build without error and the class should be usable in Xaml.
 
 **Minimal repro:**

I have created a very little github repository to reproduce the bug: https://github.com/loicmorvan-ansys/XamlBugReproduction

**Comment by maciej-izak** [comment]
Probably this is duplicate of https://github.com/dotnet/wpf/issues/5711

**Comment by lindexi** [comment]
See https://github.com/dotnet/wpf/issues/4544

**Comment by singhashish-wpf** [comment]
Thanks for filing the issue, this is duplicate of #5711 Closing it here, will be followed up on #5711
