### ISSUE TITLE
WPF IPimcManager2.GetTablet throw COMException

### ISSUE THREAD

**Issue by lindexi** [dotnet/wpf#5774]
* .NET Core Version: 6.0.100
* Windows version: 19043
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 
 **Problem description:**

WPF IPimcManager2.GetTablet throw COMException. I can occasionally find this problem.
 
 **Actual behavior:** 

```
System.Runtime.InteropServices.COMException (0x80040242): Exception from HRESULT:0x80040242
   at void MS.Win32.Penimc.IPimcManager2.GetTablet(uint tablet, out IPimcTablet2 IPimcTablet)
   at void System.Windows.Input.PenThreadWorker+WorkerOperationGetTabletsInfo.OnDoWork()
```
 
 **Expected behavior:**

Not any exception.
 
 **Minimal repo:**

Any WPF empty application run in the device with touch screen

**Comment by singhashish-wpf** [comment]
@lindexi Please help to provide full dump whenever it gets reproduced again. Thanks!

**Comment by pchaurasia14** [comment]
@lindexi - Are you still facing this issue ?
