### ISSUE TITLE
ContextMenu stops working if its owner is removed from the visual tree

### ISSUE THREAD

**Issue by SamBent** [dotnet/wpf#5835]
[Port of a servicing fix for .NET 4.7-4.8]
 
 **Problem description:**
If user invokes a ContextMenu (e.g. right-clicking on its owner), but the owner leaves the visual tree before the ContextMenu actually displays, the ContextMenu never displays again.  This is interesting when the ContextMenu is shared by multiple owners - it won't display for other owners, even when the other owners remain in the visual tree normally.
 
 **Actual behavior:** 
Invoking the ContextMenu does nothing.
 
 **Expected behavior:**
ContextMenu displays
 
 **Minimal repro:**

**Comment by huiliu-code** [comment]
Could you show a minimal example of a reproducible problem?

**Comment by vishalmsft** [comment]
Hi @huiliu-code , attached is the [sample project](https://github.com/dotnet/wpf/files/7778762/TestPopupMenu2.zip). Steps are
1. Start the debugging.
2. Click on "Start Test"
3. Multiple quick right click on List Items. 
4. Once Context Menu stops showing up, it never shows up again.

The PR fix that behavior.
