### ISSUE TITLE
Cancelling RequestPurchaseAsync immediately on device with Windows Hello does not cancel face recognition

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5848]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Cancelling-RequestPurchaseAsync-immediat/1332731)._

---
[severity:It's more difficult to complete my work]
**Description:**
When using a Windows Hello enabled device, cancelling a purchase dialog immediately, by clicking the **X** (close) button in the dialog frame, before it has loaded, will leave Windows Hello running after the dialog is closed.

**Expected behavior:**
When the **X** button is pressed, Windows Hello, and all authentication related activities, should cease.

**Actual behavior:**
The Windows Hello camera and the LEDs continue to blink after the dialog is cancelled/closed. The camera activity LED also stays lit.

**Repro steps:**
A Windows device with Windows Hello is REQUIRED to reproduce this issue.

1. Create a new .NET Core 3 WPF project.
2. Change the TFM to `net5.0-windows10.0.17763.0`.
3. Invoke the `StoreContext.RequestPurchaseAsync(string storeId)` method using a valid addon ID.
4. Package the project with a packaging project, and run the packaged app.
5. Once the host window pops up, close it immediately.

**Repro example**
I recommend binding the `Bug()` method to a click or keyboard event, so you are prepared to close the purchase dialog once it opens.

Example `Reproduce.cs`:
``` csharp
using System;
using System.Runtime.InteropServices;
using Windows.Services.Store;
using WinRT;
class Reproduce
{
    [ComImport]
    [Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IInitializeWithWindow
    {
        void Initialize(IntPtr hwnd);
    }

    public async void Bug(IntPtr hostHWND)
    {
        var context = StoreContext.GetDefault();
        IInitializeWithWindow initWindow = context.As();
        initWindow.Initialize(hostHWND);
        StorePurchaseResult result = await context.RequestPurchaseAsync("MYADDONID");
    }
}
```

Example `MainWindow.xaml.cs`:
``` csharp
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        SomeButton.Click += (sender, e) => Button_Click();
    }

    public async void Button_Click()
    {
        IntPtr ownerWindow = System.Diagnostics.Process.GetCurrentProcess().MainWindowHandle;
        await new Reproduce().Bug(ownerWindow).ConfigureAwait(false);
    }
}
```

**Environment:**
.NET SDK: 5.0.102
Runtime: 5.0.2
Visual Studio: 16.8.4
Winver: 19042.789
Windows Hello Face driver version: 10.0.19041.662

---
#### Feedback Bot on 2/7/2021, 06:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/11/2021, 01:04 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Since WPF is desktop application and a UWP api is being used, it is essential to capture how the bridging has been achieved. Please share the sample project.
