### ISSUE TITLE
`ArgumentException` with `WriteableBitmap.WritePixels`

### ISSUE THREAD

**Issue by loicmorvan** [dotnet/wpf#5855]
* .NET Core Version: 6.0
* Windows version: Windows 11 (21H2)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: I don't know
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No.

 
 
 **Problem description:**

Calling `WriteableBitmap.WritePixels` just crashes with an `ArgumentException` without `paramName`.

Reproduced in this repos: https://github.com/loicmorvan/BugWriteableBitmap
 
 **Actual behavior:** 
 
Crashes with an `ArgumentException` without `paramName`.

 **Expected behavior:**
 
No crash, and pixels updated into the bitmap.

 **Minimal repro:**

https://github.com/loicmorvan/BugWriteableBitmap

**Comment by lindexi** [comment]
Hi @loicmorvan  It looks like your code bug and not the wpf issues.

You should input the right sourceBufferStride argument to WritePixels:

`writeableBitmap.WritePixels(rect, pixels, sourceBufferStride: 4 * width, 0, 0);`

And I found your PixelFormats is not Bgra32, and is it right?

**Comment by loicmorvan** [comment]
OK, thanks!
Putting `4 * width` did work.

But still there is mistery in there: why should I put the length of one line in bytes?
Should we consider improving the API and its documentation to make it clearer?

**Comment by dipeshmsft** [comment]
Hey @loicmorvan , I looked into this issue and updated the comments in the code for better understanding. Will close the issue once the PR gets reviewed and merged.
