### ISSUE TITLE
Add attribute to C++/CLI assemblies

### ISSUE THREAD

**Issue by fadimounir** [dotnet/wpf#587]
As discussed over email, we need to add some attribute to the IJW assemblies (DirectWriteForwarder.dll and System.Printing.dll to help with this bug: https://github.com/dotnet/coreclr/issues/23872

For Preview 5, the coreclr bug might not get fixed in time, so we'll use the assembly attribute as a way to exclude these 2 problematic assemblies from being compiled into ReadyToRun images.

Proposed attribute to add:
`[assembly: AssemblyMetadata("Language", "C++")]`

**Comment by fadimounir** [comment]
cc @vatsan-madhavan

**Comment by vatsan-madhavan** [comment]
The latest core-sdk builds (3.0.100-preview5-011473) now have these attributes for WPF assemblies.
