### ISSUE TITLE
Tooltips on ComboBoxItems in WPF for .NET 6 appear and immediately disappear

### ISSUE THREAD

**Issue by amirburbea** [dotnet/wpf#5870]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)  6.0.101
* Windows version: (`winver`) 22000.376
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No 
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? If yes, please file the issue via the instructions [here](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).
NO
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/main/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:** In .NET 6, WPF tooltips on ComboBoxItems seem to close instantly, In .NET 4.8/5 this is not the case.
 
 **Actual behavior:** Popup appears but immediately vanishes
 
 **Expected behavior:** Popup on ComboBoxItem stays visible
 
 **Minimal repro:** https://github.com/amirburbea/PopupRepro

**Comment by huiliu-code** [comment]
I tested your code in Microsoft Visual Studio Professional 2022 (64-bit) Version 17.0.4.Tooltips on ComboBoxItems did not disappear immediately. My environment is Windows 10 (20H2). Did I misunderstand something?

![4](https://user-images.githubusercontent.com/79887220/147223047-3868d9f5-c815-4b7f-811c-2051ec9d4aee.gif)

**Comment by lindexi** [comment]
See #4612 https://github.com/dotnet/wpf/issues/5703

**Comment by amirburbea** [comment]
@huiliu-code Your screencast is only demonstrating you hovering over the listbox items which as I mentioned work fine. The repro product has a listbox (on the left) right next to a combobox on the right. if you opened the combobox (dropdown) you'd see that the toolitps on those items disappear on win11. I don't have windows 10 anymore to test.

**Comment by amirburbea** [comment]
@lindexi - Those bugs seem unrelated to this one - is this comment to just group this bug with the others?

**Comment by lindexi** [comment]
Sorry @amirburbea

**Comment by amirburbea** [comment]
Here's the app running in .NET5
![net5](https://user-images.githubusercontent.com/2123658/147302708-49042ee3-72ac-47db-b2fc-b930fbcb64a5.gif)

Here's the same app running in .NET6
![net6](https://user-images.githubusercontent.com/2123658/147302745-c427beae-b297-4233-a635-7a4c16fd825f.gif)

**Comment by huiliu-code** [comment]
Hi,@amirburbea. I reproduced your problem. It may be a problem with .Net 6. It is recommended that you could report the problem in the Developer Community.

**Comment by Yoooi0** [comment]
This seems like a duplicate of #5716.
The actual issue is not only with ComboBoxItem but with tooltips on any control inside a Popup control, caused by a `Mouse.Capture(this, CaptureMode.SubTree);` call.

@amirburbea If possible, you could also add my [user control](https://github.com/dotnet/wpf/issues/5716#issuecomment-978060207) that reproduces the issue to your PopupRepro.

**Comment by SamBent** [comment]
This is a duplicate of  #5716.  Let's track it there.

**Comment by amirburbea** [comment]
But @SamBent that ticket is for dinner reason labeled as needs more information. I feel that label means they won't work on it

**Comment by SamBent** [comment]
@amirburbea I assure you they will work on it.  In this case "they" is me, and I'm working on it right now.
