### ISSUE TITLE
By using keyboard not able to adjust the width of the column.

### ISSUE THREAD

**Issue by Swati1700** [dotnet/wpf#5880]
**GitHubTags:**#A11yUsable;#A11ySev4;#A11yTCS;#DesktopApp;#Win10;#BM-.NetCore(WPF)-Win32-July2021;#.NET Core;#Benchmark;#Keyboard;

### Environment Details:
Application Name: Azure RTOS - Trace X
Windows Version: Win10
Application Version: 6.1.9.0

### Repro Steps:

1. Open WPFDataGridSorted-master file.
2. Open WPFDataGridSorted.sln file.
3. Tab to "Start" button and hit enter.
4. Tab to First column in the table.
5. Observe that by using keyboard not able to adjust the column width.

### Actual:
By using keyboard not able to adjust the width of the "Label", "Labelled" and "Description" column.

### Expected:
By using keyboard (eg. CTRL + Right arrow/Left arrow) the width of the column should be adjustable.

### User Impact:
Keyboard only users will not able to adjust the column width and they will not able to see complete information present on the screen.

[WPFDataGridSorted-master (5).zip](https://github.com/dotnet/wpf/files/7783485/WPFDataGridSorted-master.5.zip)

https://user-images.githubusercontent.com/86710888/147543355-76c90b59-4c6a-4cd0-9cd2-14bebd774644.mp4

**Comment by vishalmsft** [comment]
@Swati1700 Is this issue created as part of migrating bugs from ADO?
User Story [1383796](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1383796): WPF GridView/DataGrid column width cannot be changed using only the keyboard

**Comment by Swati1700** [comment]
@vishalmsft We have logged the primary bug in the ADO and they have said that this is external to WPF. So we have logged this WPF bug in github.

**Comment by miloush** [comment]
I am assuming this is expected to work only when header is focused, otherwise it would interfere with DataGrid navigation. 

Is the usage of Ctrl+arrow keys meaning column resizing part of any user guidelines? Does it mirror in RTL?

Also it might be worth supporting <kbd>Ctrl</kbd>+<kbd>Num+</kbd> for autosizing all columns like the native listview control [does](https://devblogs.microsoft.com/oldnewthing/20121030-00/?p=6223),

**Comment by vishalmsft** [comment]
@miloush 

> I am assuming this is expected to work only when header is focused, otherwise it would interfere with DataGrid navigation.

The implementation will be used ALT + Arrow. That shall be safe. 

> Is the usage of Ctrl+arrow keys meaning column resizing part of any user guidelines? Does it mirror in RTL?

This is a nice test case. cc: @anjalisheel-wpf 

> Also it might be worth supporting Ctrl+Num+ for autosizing all columns like the native listview control [does](https://devblogs.microsoft.com/oldnewthing/20121030-00/?p=6223),

Current release cycle do not allow us to support more. But yes, this would have been a nice addition. Thank you for suggestion
