### ISSUE TITLE
[Question] Relationship with AvaloniaUI

### ISSUE THREAD

**Issue by Pzixel** [dotnet/wpf#59]
Hello guys.

It's really wonderful to see this repo and hear about porting WPF to .Net Core.

However, I've heard a lot about how WPF is closely tied to Windows and DirectX, so it seems to me to virtually impossible to just port it as it is.

OTOH we have an Avalonia project that tries to write it from scratch on .net core for last several years.

Do you guys plan to somehow interop with them? Maybe it worth taking some ideas/approaches/etc? Or you just want to port WPF as it is?

It's not a technical task, but I have a huge interest in WPF and asking this question. I'd like to hear as much information as possible.

And thank you for your job.

**Comment by dotMorten** [comment]
Seems like a duplicate of #48

**Comment by Pzixel** [comment]
Makes sense to me. 

Sorry, I was fooled that you have cross-platform in your mind.

Good job, anyway, OSS FTW

**Comment by karelz** [comment]
Duplicate of #48
