### ISSUE TITLE
Datagrid raises System.ArgumentNullException  in when loosing focus.

### ISSUE THREAD

**Issue by mawess** [dotnet/wpf#5900]
You get a System.ArgumentNullException with the datagrid in OnExecutedCommitEdit (wpf, .net 5.0 (have not tested with  core))
when the grid looses focus in the circumstance shown below.  Simple example code included.

How to reproduce the exception:

1. build and run code attached in "datagridcrash.cs.txt".
2. Edit the "data" grid cell, leave cursor in cell textbox
3. select File/save from menu. (the cell will revert to "data")
4. edit the "data" grid cell again, leave cursor in cell textbox
5. click on "tabitem" header -> datagrid raises System.ArgumentNullException shown in attached file datagrix.exection.txt:
first lines is:

System.ArgumentNullException
 at System.Windows.Automation.Peers.UIElementAutomationPeer.FromElement(UIElement element)
   at System.Windows.Controls.DataGrid.CellAutomationValueHolder.TrackValue()
   at System.Windows.Controls.DataGrid.ReleaseCellAutomationValueHolders()
   at System.Windows.Controls.DataGrid.OnExecutedCommitEdit(ExecutedRoutedEventArgs e)

[datagrid exception.txt](https://github.com/dotnet/wpf/files/7801579/datagrid.exception.txt)
[datagridcrash.cs.txt](https://github.com/dotnet/wpf/files/7801585/datagridcrash.cs.txt)

the error seems to be that the contents of the _editingCellAutomationValueHolders gets corrupted (the column.GridDataOwner becomes null)

**Comment by huiliu-code** [comment]
Is your project a wpf project, a console application, or a unit test project?

**Comment by huiliu-code** [comment]
Is your project a wpf project, a unit test project, or another project?

**Comment by mawess** [comment]
sorry. wasnt clear about that.
create a wpf project with .net 5.0 (or earlier) delete all the created files in solution explorer (mainwindow.* app.* and assemblyinfo.cs) 
then add  a new class and replace its contents with my code. build and run

/m

**Comment by huiliu-code** [comment]
I followed your steps to test in (Windows 10 20H2) Microsoft Visual Studio Enterprise 2019 Version 16.10.2. No error message received.
Project structure：

![image](https://user-images.githubusercontent.com/79887220/148171565-161b9b6b-0093-40a0-aecb-f0a4c01b8e71.png)

Test Results：

![4](https://user-images.githubusercontent.com/79887220/148172393-9c9627bb-77df-49b5-b36e-2afee1cf03f8.gif)

**Comment by krillboi** [comment]
Is there any progress on this? I have a very similar bug and have been chasing a fix for over a week now.

**Comment by anjalisheel-wpf** [comment]
@mawess

I followed your steps, tried reproducing it, I do not think that this is reproducible. Attaching screen recording for the same.

https://user-images.githubusercontent.com/85492722/162214945-079d2085-b23b-4d2b-bb4e-583e2848ee66.mp4
