### ISSUE TITLE
Drawing spline curves in XAML

### ISSUE THREAD

**Issue by dhq-boiler** [dotnet/wpf#5902]
I want to draw a spline curve in a WPF application.
However, the System.Windows.Media.PathSegment class is closed and non-extensible, and it seems impossible to create its subclasses.
How can I represent a spline curve in xaml code?
Is there any solution?
If possible, please implement the SplineCurveSegment class.

**Comment by gurpreet-wpf** [comment]
@dhq-boiler  Is it possible for you to use [beziersegment](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.beziersegment?view=windowsdesktop-6.0). Or can you elaborate what you are looking for in SplineCurveSegment?
@singhashish-wpf

**Comment by dhq-boiler** [comment]
No, it isn't. > [beziersegment](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.beziersegment?view=windowsdesktop-6.0)

This is what I was looking for:
https://mathworld.wolfram.com/CubicSpline.html

A cubic spline is **a curve that passes through all the point clouds** that make up it.

Using this curve, I would like to implement a drawing tool that draws a curve according to the dragged trajectory in the vector graphics drawing tool that I am developing.

As you can imagine, the SplineCurveSegment class should work like this:

```xaml
<Path Stroke="Black" StrokeThickness="1">
  <Path.Data>
    <PathGeometry>
      <PathGeometry.Figures>
        <PathFigureCollection>
          <PathFigure StartPoint="10,100">
            <PathFigure.Segments>
              <PathSegmentCollection>
                <SplineCurveSegment Points="{Binding Points}" />
              </PathSegmentCollection>
            </PathFigure.Segments>
          </PathFigure>
        </PathFigureCollection>
      </PathGeometry.Figures>
    </PathGeometry>
  </Path.Data>
</Path>
```

Or you should be able to draw using the omitted markup syntax.

```xaml
<Path Stroke="Black" StrokeThickness="1"  
  Data="M 10,100 ? 100,0 200,200 300,100" />
```

?: Alphabet representing commands to draw cubic spline curves

I think there is no limit to the number of point clouds that can be set in the SplineCurveSegment.

**Comment by ThomasGoulet73** [comment]
@dhq-boiler Would [PolyBezierSegment](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.polybeziersegment?view=windowsdesktop-6.0) work for you ? From what I understand, a cubic spline is just a collection of bezier segments.

**Comment by dhq-boiler** [comment]
This one! What I was looking for! >[PolyBezierSegment](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.polybeziersegment?view=windowsdesktop-6.0)

I immediately implemented it in the app. It's working perfectly.
I thought the PolyBezierSegment class was a kind of Bezier curve that needed control points. But it was different.
![poly_bezier](https://user-images.githubusercontent.com/7916855/148631971-20095a03-beb3-410a-9a8e-3c6c2bd68ea6.gif)

I have posted the git repository for reference.
https://github.com/dhq-boiler/boiler-s-Graphics

The branches implemented this time are as follows : feature/PolyBezierSegment

Thank you for your wonderful answer.
Thank you to those who were in charge.

**Comment by ThomasGoulet73** [comment]
Nice! I'm glad it helped.
