### ISSUE TITLE
In gooutinue, the callback C# function has an exception System.ExecutionEngineException when updating the UI

### ISSUE THREAD

**Issue by xiao-cao-x** [dotnet/wpf#5927]
When I call back the C# function in `goroutinue` of  `Golang` to update the `WPF UI`, an exception occurred and it could not be caught.

```
System.ExecutionEngineException
```

![image](https://user-images.githubusercontent.com/76673990/148685922-7712afee-725b-41f9-98c6-24978dc6351e.png)

![image](https://user-images.githubusercontent.com/76673990/148685998-368d6339-55b9-4112-bcc6-c980248d1c89.png)

`ViewModel` is in `TabItem` of `TabControl`
![image](https://user-images.githubusercontent.com/76673990/148686042-4c5a4aff-9c3e-42f5-ba04-6460a77cd78d.png)

The exception here cannot be `catch`
![image](https://user-images.githubusercontent.com/76673990/148686089-0e765fab-0eab-4a38-9083-ca190106bf65.png)

The `Output` function is called by `Golang` through `syscall`
![image](https://user-images.githubusercontent.com/76673990/148686175-e69f5270-adfa-4ac6-8e15-239d1bc03020.png)

**Comment by lindexi** [comment]
Can enter `GoOutput(IntPrt level, IntPtr content, IntPtr file, int line)` method?

Or it breaks in Marshal convert?

**Comment by xiao-cao-x** [comment]
After Golang calls back the `GoOutput` function, it is interrupted when the `Output` function is called

**Comment by xiao-cao-x** [comment]
This code works perfectly fine in console projects, but in WPF projects it throws an exception

**Comment by xiao-cao-x** [comment]
The problem and solution is that the delegate function pointer is reclaimed by the GC.
```cs
    public class GoLogger
    {
        public static ILogger? Logger { get; set; }

        static GoLogger()
        {
            _goOutputDelegate = GoOutput;
            CoreGo.LoggerSetOutputFuncAddress(Marshal.GetFunctionPointerForDelegate(_goOutputDelegate));
        }
        private readonly static GoOutputDelegate _goOutputDelegate;

        private delegate void GoOutputDelegate(IntPtr level, IntPtr content, IntPtr file, int line);


        public static void GoOutput(IntPtr level, IntPtr content, IntPtr file, int line)
        {
            Logger?.Output(
                Enum.Parse<LogLevel>(Marshal.PtrToStringUTF8(level)!),
                Marshal.PtrToStringUTF8(content)!,
                Marshal.PtrToStringUTF8(file)!,
                line
                );
        }

    }
```

Define a variable to store the delegate type
```cs
private readonly static GoOutputDelegate _goOutputDelegate;
```
