### ISSUE TITLE
Add Horizontal MouseWheel Scrolling Support

### ISSUE THREAD

**Issue by aquinn39** [dotnet/wpf#5937]
Currently, MouseWheel events are only sent in response to vertical mouse wheel scrolling; no event is sent for horizontal scrolling despite Windows sending a window message in response to horizontal mouse/touchpad scrolling. This means that horizontal scrolling does nothing in WPF apps, unless the app manually listens for and interprets the horizontal mouse wheel event and responds to it manually.

**Comment by lindexi** [comment]
```csharp
        private IntPtr Hook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
        {
            const int WM_MOUSEHWHEEL = 0x020E;
            switch (msg)
            {
                case WM_MOUSEHWHEEL:
                    int tilt = (short) HIWORD(wParam);
                    OnMouseTilt(tilt);
                    return (IntPtr) 1;
            }
            return IntPtr.Zero;
        }

        private static int HIWORD(IntPtr ptr)
        {
            var val32 = ptr.ToInt32();
            return ((val32 >> 16) & 0xFFFF);
        }

        private void OnMouseTilt(int tilt)
        {
            // Your code
           
        }
```

**Comment by Symbai** [comment]
I was going to request the same. WPF doesnt support scrolling horizontally using "mouse" devices only. Not via mouse wheel (including the classic mouse wheel with up/down, but there are also mouse wheels which you can move to left or right), and not via touchpad.

There are some "hacks" to achieve that:
https://blog.walterlv.com/post/handle-horizontal-scrolling-of-touchpad-en.html
https://stackoverflow.com/questions/4158101/how-to-horizontally-scroll-in-wpf-using-mouse-tilt-wheel
https://stackoverflow.com/questions/54549047/shift-mouse-wheel-to-scroll-horizontally (using Shift + a classic mouse wheel works fine in for example Microsoft Edge)

But this feels like it should be implemented into WPF by default.

**Comment by lindexi** [comment]
@Symbai Do you thank *adding the new event* or *adding to existing event* is better?

**Comment by Symbai** [comment]
@lindexi It is unclear to me how using MOUSEWHEEL hook tells us if it scrolls horizontal and not vertical. Imagine a scrollviewer where BOTH scrollbars are shown at the same time and the user uses a touchpad for example. He can scroll up/down but also left/right. So what exactly is sent to the application in both cases, where does it differ and how to other frameworks react on this.

Also it seems that this request has another open issue with some ideas of how to implement: https://github.com/dotnet/wpf/issues/3201

Maybe its worth it to merge both.

As for the SHIFT + mouse wheel. I just used [this workaround](https://stackoverflow.com/a/54575018) (Creating a new class inheriting the ScrollViewer, overridding the `OnMouseWheel` event. At least this wouldn't cause any public surface changes.

**Comment by Symbai** [comment]
> > Adding to existing public events would be a breaking change.
> 
> How?

Because the existing wheel change event has no indicator if its about horizontal or vertical. Adding such an indicator like a boolean forces developers to check that. Existing code wouldn't check that, so it breaks.

**Comment by aquinn39** [comment]
Closing this as a duplicate of https://github.com/dotnet/wpf/issues/3201.

**Comment by Symbai** [comment]
Instead of closing you should have merged posts. And nobody said anything to my suggestion about making a separate PR for shift + mouse wheel support.... the "duplicate" doesn't cover this.

**Comment by aquinn39** [comment]
> Instead of closing you should have merged posts. And nobody said anything to my suggestion about making a separate PR for shift + mouse wheel support.... the "duplicate" doesn't cover this.
> 
> @miloush: This still break existing code as you don't know what developers are doing in this event. They could be calling another method regardless of the delta value. And right now it is SAFE that its only for vertical scrolling.

I am happy to merge the issues, I just don’t know how. If I can figure out how to merge it, I’ll reopen and merge it.

**Comment by miloush** [comment]
> shift + mouse wheel support

That is not a standard Windows behavior and I would need some convincing to support it out of the box. It doesn't work like that in Notepad/Paint/native controls, Word (it does in VS or Adobe Reader). It's Ctrl+Shift+Scroll for Excel, Ctrl+Scroll in Illustrator/Photoshop etc. Windows Explorer scrolls horizontally using normal scrolling if there is horizontal scrollbar only.

**Comment by Symbai** [comment]
> That is not a standard Windows behavior

Shift + mouse wheel works in:

- Windows Explorer
- Microsoft Edge
- Chrome
- Firefox

Ok it doesnt work in classic Notepad but the classic Notepad shouldnt be used as a "common standard application" nowadays. If it works in Windows Explorer, then it is a standard windows behavior.
