### ISSUE TITLE
WPF multiple ShowDialogs

### ISSUE THREAD

**Issue by AHero11** [dotnet/wpf#594]
# General

with DotNetCore 3 Preview 3:
In a console-application starting a simple modal "Hello world" WPF dialog with "ShowDialog();" works fine. But after it closes, starting the same view again with ShowDialog does absolutely nothing: no view, no runtimeerror, no nothing - the programm just ignores it,

Example:
        private void Application_Startup(object sender, StartupEventArgs e)
        {
            new TestWindow().ShowDialog();
            new TestWindow().ShowDialog();
        }

**Comment by ryalanms** [comment]
Thanks, @AHero11.  Could you try with the most recent SDK?  This is working for me with the most recent SDK; both dialogs appear.  

```csharp
        public MainWindow()
        {
            InitializeComponent();

            new TestWindow().ShowDialog();
            new TestWindow().ShowDialog();
        }
```

**Comment by AHero11** [comment]
Fixed with latest SDK - thanks! :-)
