### ISSUE TITLE
Popup element are reversed left and right in Windows 11

### ISSUE THREAD

**Issue by ChengYen-Tang** [dotnet/wpf#5944]
* .NET Core Version: .net 5~6(e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Windows version: Windows 11
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No
* Is this bug related specifically to tooling in Visual Studio : No
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/main/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**
I found that using the Popup element and setting the Placement to left will actually appear on the right and the right will appear on the left
This problem happens on windows 11, windows 10 is normal
Note: Visual studio menu also has this problem 

 **Actual behavior:** 
Windows 11:
![image](https://user-images.githubusercontent.com/32535494/149258036-5b5536c7-b13e-4582-8010-143b0580e65a.png)
![image](https://user-images.githubusercontent.com/32535494/149258167-40457884-e544-46c6-9aeb-a5902301cefe.png) 

 **Expected behavior:**
 Windows 10:
![image](https://user-images.githubusercontent.com/32535494/149258583-aeaf06e3-ff61-4481-9633-b614c659b04f.png)
![image](https://user-images.githubusercontent.com/32535494/149258822-bc7b53b1-422a-4307-9a8d-f835530d986a.png)

 **Minimal repro:**

**Comment by lindexi** [comment]
It's Looks like a Windows problem, not the WPF issues.

**Comment by ChengYen-Tang** [comment]
Seems yes, but I have a few questions
1. This problem has existed since the release of Win11, but it has not been improved
2. My colleagues use Qt to develop desktop applications, this problem does not appear in Qt
3. I have been using Win11 for a while, and most programs do not have this problem
4. I don't know how to give feedback to the windows department

**Comment by miloush** [comment]
I believe this works as designed. There is a setting in Windows that controls on which side the menu appears.

This used to be part of _Control Panel_ > _Table PC settings_ > _Other_ tab > _Handedness_. 

![image](https://user-images.githubusercontent.com/10546952/149672141-4867b8bc-3572-4771-958f-623a44a4ae68.png)

However, I no longer have this tab on Win11. Try _Settings_ > _Bluetooth & Devices_ > _Pen & Windows Ink_ > _Choose which hand you write with_.

The corresponding registry setting should be `HKCU\Software\Microsoft\Windows NT\CurrentVersion\Windows\MenuDropAlignment`.

**Comment by singhashish-wpf** [comment]
Thanks @miloush!
@ChengYen-Tang Please close the issue if the above answer helped, Let us know in case there is something more to it.

**Comment by ChengYen-Tang** [comment]
Hi @singhashish-wpf 
I think @miloush just provides a temporary solution to the problem.
I can't ask all Windows 11 users to set the registry.
In my project, because the left and right are reversed, the layout is severely shifted.

**Comment by miloush** [comment]
@ChengYen-Tang I am implying this is not a WPF issue. It's a global OS setting and any Windows 11 user can set it the way the prefer.

**Comment by lindexi** [comment]
@ChengYen-Tang How about we edit the register?

`HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows\MenuDropAlignment`

- Value 0 : Default, Left-handed
- Value 1 : Right-handed

After you edit the value, you need to sign out and sign in back to your Windows account or restart your computer. Windows should place the context menu on the right side.

See https://www.top-password.com/blog/tag/tablet-pc-settings-windows-10/

**Comment by ChengYen-Tang** [comment]
@lindexi ,
It works, but the default in Windows 11 is 1.

**Comment by lindexi** [comment]
> @lindexi ,
> 
> It works, but the default in Windows 11 is 1.

Sorry,my Windows is 0

**Comment by ChengYen-Tang** [comment]
@lindexi ,
Did you upgrade from Windows 10 to Windows 11?
Or fresh install of Windows 11

**Comment by lindexi** [comment]
@ChengYen-Tang 

![图片](https://user-images.githubusercontent.com/16054566/150075514-bd80762c-2f04-4fd6-aebf-9301c3dc38b0.png)
