### ISSUE TITLE
Exception "The data area passed to a system call is too small"

### ISSUE THREAD

**Issue by matthew-a-thomas** [dotnet/wpf#6026]
### Description

Encountered the below exception stack trace in our production WPF application.

Details are scant but I do know the PC was running Windows 10 Pro 2009, and the version of our software that was running targeted net6.0-windows runtime environment. I also have a list of processes that were currently running at the time of the exception. I'm not sure how to share that privately here; let me know if you need it and I'll arrange a way.

It's difficult to tell exactly what the state of our software was when this exception happened, but other than this exception all signs indicate the software was operating normally.

Here's the stack trace:
```
Type: System.ComponentModel.Win32Exception
Message: The data area passed to a system call is too small.
Source: WindowsBase
Stack Trace:
at MS.Win32.UnsafeNativeMethods.GetWindowText(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)
at System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()
at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
at System.Windows.ContextLayoutManager.fireAutomationEvents()
at System.Windows.ContextLayoutManager.UpdateLayout()
at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Internet search results currently point to some issue with an out-of-date installation of SQL Server. I do not believe SQL Server is/was present on this machine.

### Reproduction Steps

Sorry

### Expected behavior

I expect no exception

### Actual behavior

Above exception was thrown

### Configuration

Windows 10 Pro 2009
x64
WPF
net6.0-windows target

**Comment by singhashish-wpf** [comment]
@matthew-a-thomas We will be able to help you better if there is a minimal repro project attached to this bug.

**Comment by matthew-a-thomas** [comment]
@singhashish-wpf I completely understand--I'm often in your shoes and I understand how much more difficult it is to fix sporadic issues. But unfortunately that's all I have. I'm at a loss how to turn that stack trace into something reproduceable, and it's complicated by the fact that this exception happened somewhere "out there".

The best I could do at this point is search through Microsoft source code (and decompile DLLs when source isn't available) to try and guess at the conditions that led up to this. But I figured a Microsoft employee would be better equipped to do that :)

In the meantime I'll keep an ear open for additional exceptions like this in our software. Perhaps there will be a helpful pattern.

**Comment by matthew-a-thomas** [comment]
This exception popped up again. Here are the OS and runtime involved this time:
> OS Version: Microsoft Windows 10.0.19044
> Runtime: .NET 6.0.0-rtm.21522.10

**Comment by MichaeIDietrich** [comment]
Might it be possible that your window has an extraordinary long title?

The call stack shows that a WPF layout update has been triggered which also refreshes the accessibility properties of the window. And it fails updating the `AutomationName` when trying to read the window title using the Win32 function `GetWindowText`. A fixed buffer of 512 characters is passed, it this is not enough, the function returns **0x7A ERROR_INSUFFICIENT_BUFFER** - _The data area passed to a system call is too small_.

I hope this is helpful in any way.

**Comment by matthew-a-thomas** [comment]
This has happened again. The user said they had left our software running for a few days without really interacting with it.

**Comment by MichaeIDietrich** [comment]
Usually when we discover errors that only occur for specific customers and we cannot reproduce those, we please that customer to collect a memory dump of the running application, so we can analyze the state of the application with our tools e.g. Visual Studio. In your case it might be useful to set up the Windows Error Reporting to collect a memory dump when your application crashes: https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

This might help you to understand the error. But I would not make a promise that this will definitely bring the clue to the issue, since the error happens with a native Win32 function, so it could be that the cause is neither a WPF nor a .NET issue. But still it can be an option to solve this issue.

**Comment by matthew-a-thomas** [comment]
Thank you @MichaeIDietrich for the ideas.

> when your application crashes

Just to be clear: the application isn't crashing. These exceptions are caught by our in-app exception handling. Unfortunately WER wouldn't help in this specific case.

But the general concept of trying to get some memory dumps is a good idea. I'll see what I can do.

**Comment by matthew-a-thomas** [comment]
# Reproduction

But it's easy enough to trigger this exception by simply setting the system error to 122 within a message loop hook while handling the WM_GETTEXT message and returning zero:

```csharp
// Within `MainWindow.xaml.cs` of a brand new WFP project

using System;
using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Interop;

public partial class MainWindow
{
    public MainWindow()
    {
        InitializeComponent();
        Title = string.Empty;
    }

    protected override void OnSourceInitialized(EventArgs e)
    {
        base.OnSourceInitialized(e);
        var source = (HwndSource)PresentationSource.FromVisual(this)!;
        source.AddHook(ProblemHook);
    }

    IntPtr ProblemHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
    {
        if (msg == 0x000D) // WM_GETTEXT
        {
            Marshal.SetLastSystemError(122);
        }
        return IntPtr.Zero;
    }
}
```

Actually it's not even necessary to conditionally set the error. It also throws the exception if `SetLastSystemError(122)` is outside the if-statement.

But with the above then you get this exception stack:

```
System.ComponentModel.Win32Exception (122): The data area passed to a system call is too small.
   at MS.Win32.UnsafeNativeMethods.GetWindowText(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)
   at System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.ContextLayoutManager.fireAutomationEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at System.Windows.Interop.HwndSource.Process_WM_SIZE(UIElement rootUIElement, IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Interop.HwndSource.LayoutFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

The stack trace is different because the layout pass is apparently being invoked by a different code path. But you'll notice that the same methods are being exercised at the top of the stack.

# Findings

As you can see, the exception message is caused by [Win32 error 122](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-#:~:text=ERROR_INSUFFICIENT_BUFFER,is%20too%20small.). After running all the relevant Microsoft DLLs through disassemblers and tracing through Microsoft's source code online we can see that error 122 is not raised on any of the relevant code paths.

And I guess I should state the obvious: no we are _not_ knowingly setting the system error to 122 in the message loops in our software.

Taking all these things into account, I'm deducing these things:
 * Since the call stack is different, in the wild this exception is being raised more selectively
 * This exception is being caused by a window hook somewhere setting error 122
 * It is _not_ being caused directly by any of the methods in the exception call stacks

# Path forward

## Possible workaround

First, let me acknowledge a possible workaround. We'll probably implement this in our software. All you have to do is be the first to add this band-aid hook:

```csharp
using System;
using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Interop;

public partial class MainWindow
{
    public MainWindow()
    {
        InitializeComponent();
        Title = string.Empty;
    }

    protected override void OnSourceInitialized(EventArgs e)
    {
        base.OnSourceInitialized(e);
        var source = (HwndSource)PresentationSource.FromVisual(this)!;
        source.AddHook(BandAidHook); // Make sure this is hooked first. That ensures it runs last
        source.AddHook(ProblemHook);
    }

    IntPtr ProblemHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
    {
        if (msg == 0x000D) // WM_GETTEXT
        {
            Marshal.SetLastSystemError(122);
        }
        return IntPtr.Zero;
    }

    IntPtr BandAidHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
    {
        if (msg == 0x000D) // WM_GETTEXT
        {
            Marshal.SetLastSystemError(0);
        }
        return IntPtr.Zero;
    }
}
```

## Looking long term

Let's take a look at [that WPF method at the very top of the stack](https://referencesource.microsoft.com/#WindowsBase/Shared/MS/Win32/UnsafeNativeMethodsCLR.cs,26440f71e1d03fbf):

```csharp
/// <SecurityNote>
/// SecurityCritical due to a call to SetLastError and calls GetWindowText
/// </SecurityNote>
[SecurityCritical]
internal static int GetWindowText(HandleRef hWnd, [Out] StringBuilder lpString, int nMaxCount)
{
    int returnValue = NativeMethodsSetLastError.GetWindowText(hWnd, lpString, nMaxCount);
    if (returnValue == 0)
    {
        int win32Err = Marshal.GetLastWin32Error();
        if (win32Err != 0)
        {
            throw new Win32Exception(win32Err);
        }
    }
    return returnValue;
}
```

...and the `NativeMethodsSetLAstError.GetWindowText(...)` method looks like [this](https://referencesource.microsoft.com/#WindowsBase/Shared/MS/Win32/NativeMethodsSetLastError.cs,f244c095e970602f):

```csharp
[DllImport(PresentationNativeDll, EntryPoint = "GetWindowTextWrapper", CharSet=CharSet.Auto, BestFitMapping = false, SetLastError = true)]
public static extern int GetWindowText(HandleRef hWnd, [Out] StringBuilder lpString, int nMaxCount);
```

I ran `PresentationNative_v0400.dll -> GetWindowTextWrapper(...)` through a disassembler and can see that all it's doing is `SetLastError(0)` before calling [GetWindowTextW](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowtextw), which states:

> If the function succeeds, the return value is the length, in characters, of the copied string, not including the terminating null character. If the window has no title bar or text, if the title bar is empty, or if the window or control handle is invalid, the return value is zero. To get extended error information, call GetLastError.

To me it seems like a bad decision to make it impossible to distinguish between an empty title bar and an error condition. But I'm betting that nobody will be in any hurry to alter the behavior of `GetWindowTextW`.

So I would like to propose: `UnsafeNativeMethodsCLR.GetWindowText(...)` should _not_ check for errors, but should instead just return an empty string when `NativeMethodsSetLastError.GetWindowText(...)` returns zero. Would the WPF folks like a PR for this?

**Comment by FlsZen** [comment]
This seems like it could be similar to what is being experienced in #4181 except it's a different error code being set by a hook in that case. I wonder if there's an easy way to capture stack traces when the error codes are set. I'm not an experiences win32 programmer, but maybe `SetWindowHookEx` and `WH_DEBUG` could be used to identify the hook that is leaving an error code set. Perhaps there is a hook option here that could be utilized to clear any error before returning to WPF's code.

For what it's worth, my analysis of `GetWindowTextW` reveals that it only ever sets the error `ERROR_INVALID_WINDOW_HANDLE 1400 (0x578)`. This happens to also be the only error alluded to in its documentation.

**Comment by matthew-a-thomas** [comment]
# Another workaround

I think the following will more reliably work around this issue.

In general, P/Invoke the `SetWindowsHookEx` function with these parameters:
 * `idHook`: `WH_CALLWNDPROCRET` (12)
 * `lpfn`: _the function described below_
 * `hmod`: `IntPtr.Zero`, or 0
 * `dwThreadId`: _current thread's **native** ID_

The function signature for `WH_CALLWNDPROCRET` is described here:
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nc-winuser-hookproc

What you want to do in this function is inspect the [`CWPRETSTRUCT`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-cwpretstruct) parameter to see if the message is a `WM_GETTEXT` message. If so, then just set last system error to zero (`Marshal.SetLastSystemError(0)`).

Here's some example WPF code that uses the [`PInvoke.User32`](https://www.nuget.org/packages/PInvoke.User32) and [`PInvoke.Kernel32`](https://www.nuget.org/packages/PInvoke.Kernel32) NuGet packages to make it easier to deal with the native calls and structures:

```csharp
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Windows;
using PInvoke;

public partial class App
{
    protected override void OnStartup(StartupEventArgs e)
    {
        var threadId = PInvoke.Kernel32.GetCurrentThreadId();
        Verify(PInvoke.User32.SetWindowsHookEx(
            User32.WindowsHookType.WH_CALLWNDPROCRET,
            (code, param, lParam) =>
            {
                unsafe
                {
                    ref var info = ref Unsafe.AsRef<PInvoke.User32.CWPRETSTRUCT>((void*)lParam);
                    if (info.message == User32.WindowMessage.WM_GETTEXT)
                    {
                        Marshal.SetLastSystemError(0);
                    }
                    return PInvoke.User32.CallNextHookEx(
                        IntPtr.Zero,
                        code,
                        param,
                        lParam
                    );
                }
            },
            IntPtr.Zero,
            threadId
        ));

        base.OnStartup(e);
    }

    static T Verify<T>(T handle)
    where T : SafeHandle
    {
        if (!handle.IsInvalid)
            return handle;
        var error = Marshal.GetLastWin32Error();
        if (error == 0)
            return handle;
        throw new Win32Exception(error);
    }
}
```

This (obviously) requires your project to allow unsafe code.

With this in my WPF app I can now set system errors all I want in as many hooks for `WM_GETTEXT` message hooks as I want, and my app won't throw this issue's exception.

**However** this does not hook into windows created on other threads. If you start a new `Dispatcher` in another thread and show a `Window` there then you'll need to run the above code on that thread, too.

**Comment by JayToltTech** [comment]
FYI, I have also seen this exception three times in the past two weeks in my app:

Apr 10 17:20:20 ToltTech.AbilityDrive 2210.4.2.1|Fatal|ToltTech.Reliability.CrashHandler

System.ComponentModel.Win32Exception (0x80004005): The data area passed to a system call is too small     at MS.Win32.UnsafeNativeMethods.GetWindowTextLength(HandleRef hWnd)     at MS.Win32.UnsafeNativeMethods.GetWindowTextNoThrow(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)     at System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()     at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()     at System.Windows.ContextLayoutManager.fireAutomationEvents()     at System.Windows.ContextLayoutManager.UpdateLayout()     at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)     at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()     at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()     at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)     at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Apr 16 10:28:05 A13J-21120122. ToltTech.AbilityDrive 2210.4.2.1|Fatal|ToltTech.Reliability.CrashHandler

System.ComponentModel.Win32Exception (0x80004005): The data area passed to a system call is too small     at MS.Win32.UnsafeNativeMethods.GetWindowTextLength(HandleRef hWnd)     at MS.Win32.UnsafeNativeMethods.GetWindowTextNoThrow(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)     at System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()     at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()     at System.Windows.ContextLayoutManager.fireAutomationEvents()     at System.Windows.ContextLayoutManager.UpdateLayout()     at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)     at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()     at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()     at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)     at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Apr 17 12:19:58 Stephen. ToltTech.AbilityDrive 2210.4.2.1|Fatal|ToltTech.Reliability.CrashHandler

System.ComponentModel.Win32Exception (0x80004005): The data area passed to a system call is too small     at MS.Win32.UnsafeNativeMethods.GetWindowTextLength(HandleRef hWnd)     at MS.Win32.UnsafeNativeMethods.GetWindowTextNoThrow(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)     at System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()     at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()     at System.Windows.ContextLayoutManager.fireAutomationEvents()     at System.Windows.ContextLayoutManager.UpdateLayout()     at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)     at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()     at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()     at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)     at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jfontsaballs** [comment]
I'm also facing the same problem. This is a long running application executing inside Windows Server 2019. SQL Server 2019 is also installed in the same machine. I'm using .NET 6.

```
System.ComponentModel.Win32Exception (122): The data area passed to a system call is too small.
   at MS.Win32.UnsafeNativeMethods.GetWindowText(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)
   at System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.ContextLayoutManager.fireAutomationEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at MyApp.Program.Main()
```

Can we expect a patch to solve this issue anytime soon? Is this problem solved in .NET 7?

**Comment by matthew-a-thomas** [comment]
@singhashish-wpf Just checking in on the status of this. Also double-checking that you saw [my suggestion above](https://github.com/dotnet/wpf/issues/6026#:~:text=So%20I%20would%20like%20to%20propose%3A%20UnsafeNativeMethodsCLR.GetWindowText(...)%20should%20not%20check%20for%20errors%2C%20but%20should%20instead%20just%20return%20an%20empty%20string%20when%20NativeMethodsSetLastError.GetWindowText(...)%20returns%20zero.%20Would%20the%20WPF%20folks%20like%20a%20PR%20for%20this%3F):
> So I would like to propose: `UnsafeNativeMethodsCLR.GetWindowText(...)` should _not_ check for errors, but should instead just return an empty string when `NativeMethodsSetLastError.GetWindowText(...)` returns zero. Would the WPF folks like a PR for this?

**Comment by FlsZen** [comment]
As of 09608ab5ef47e8a142e16285ec55500e3c01287e, `WindowAutomationPeer.GetNameCore(...)` now catches and handles `Win32Exception`s. I suspect that change also resolves this issue since that method is up the stack in the original stack trace.

**Comment by pchaurasia14** [comment]
@matthew-a-thomas - As @FlsZen mentioned, the corresponding [commit](https://github.com/dotnet/wpf/commit/09608ab5ef47e8a142e16285ec55500e3c01287e) should resolve this error that you are getting. It will be released as part of .NET 8 Preview 7.
Let us know if this is still a problem.

**Comment by matthew-a-thomas** [comment]
That commit looks like it'll do the job. I'm closing this issue now. Thank you!
