### ISSUE TITLE
BadImageFormatException happens when application is launching

### ISSUE THREAD

**Issue by diehell02** [dotnet/wpf#6033]
I have found a very strange exception:
![image](https://user-images.githubusercontent.com/22408851/151691570-b534671c-e9fe-40cb-aac6-4d79ef772a6e.png)

This exception is thrown when the application launches.
And my code is like this:

```
    class Program
    {
        [STAThread]
        static void Main(string[] arg)
        {
            var splash = new SplashWindow();
            splash.Show();

            App application = new App();
            application.InitializeComponent();
            application.Run();
        }
    }
```
```
<Window>
    <Grid>
        <Grid.Background>
            <VisualBrush  Stretch="UniformToFill">
                <VisualBrush.Visual>
                    <Grid Width="{StaticResource DefaultResolutionWidth}" Height="{StaticResource DefaultResolutionHeight}">
                        <Image x:Name="imageWatermark"
                        Width="{StaticResource SplashLogoWidth}"
                        Height="{StaticResource SplashLogoHeight}"
                        Source="{DynamicResource MainWindowWatermark}" />
                    </Grid>
                </VisualBrush.Visual>
            </VisualBrush>
        </Grid.Background>
    </Grid>
</Window>
```

This exception only happened once, and cannot reproduce.

I'm not sure the reason is that I show a Window of WPF before the Application construct?

**Comment by lindexi** [comment]
Why it loaded the `C:\Program Files\RingCentral Rooms\PresentationCore.dll` ?

**Comment by diehell02** [comment]
> Why it loaded the ?`C:\Program Files\RingCentral Rooms\PresentationCore.dll`

Because I use the self-contained mode to publish.

**Comment by singhashish-wpf** [comment]
@diehell02 Could you please provide a sample repro project? We shall try to check it at our side too.

**Comment by gurpreet-wpf** [comment]
@diehell02  Please create a new issue if this issue persists.
