### ISSUE TITLE
Editing for DataGrid cell is not triggered while pressing any characters in keyboard only for some set of languages

### ISSUE THREAD

**Issue by MohanramAnbukkarasu** [dotnet/wpf#6041]
In WPF DataGrid, if we select a cell and press any key, editing for that cell is triggered properly when the selected language in language preferences option in Windows 10 is English. 

If we select Tamil, then the cell doesn't enter edit mode when pressing any character in the key. 

Please refer to the attached video illustration of the problem and provide if there is any way to resolve this.

[DataGrid_EditDemo.zip](https://github.com/dotnet/wpf/files/7970881/DataGrid_EditDemo.zip)

**Comment by miloush** [comment]
Just for others, the video shows Tamil99 layout which uses TSF.

@MohanramAnbukkarasu can you provide more repro steps? I tried both .NET 6 and .NET Framework and cannot reproduce. What word are you trying to type? Does it reproduce for you when using the INFITT layout?

**Comment by MohanramAnbukkarasu** [comment]
@miloush , Thanks for the update. I'm just pressing any character in an English keyboard. The corresponding Tamil letter for that key should be entered into the selected cell. But it doesn't happen. Can you please provide more details about the INSCRIPT layout that you have mentioned? How can I check that?

**Comment by miloush** [comment]
Goto Windows Settings > Time & Language > Language > click on Tamil and press the Options button. Add a keyboard and choose INSCRIPT. Then try to reproduce (K key corresponds to KA, left half is vowels), is it the same?

**Comment by miloush** [comment]
Actually I have just noticed the IME appearing in the top left corner of your video. Are you using the Windows' built-in Tamil99 layout or did you install your own?

**Comment by MohanramAnbukkarasu** [comment]
![image](https://user-images.githubusercontent.com/44049406/152475608-a844b69c-f233-4de1-8f50-0d7e4eb9c851.png)

@miloush, I have used the option as shown in the screenshot to install the Tamil language.

**Comment by miloush** [comment]
@MohanramAnbukkarasu do you have a project that reproduces the issue? As I noted I cannot reproduce it myself in a new project. (I can reproduce the IME behavior in GTK+ but not in a WPF app.)

**Comment by MohanramAnbukkarasu** [comment]
@miloush , Please check the attached sample which I have used to record the video I have provided in my first update
[WpfApp1.zip](https://github.com/dotnet/wpf/files/8069666/WpfApp1.zip)

**Comment by miloush** [comment]
@MohanramAnbukkarasu thank you for the demo project. However when I run the exe file and follow your steps, it works for me in place:

![image](https://user-images.githubusercontent.com/10546952/154080665-76d0a9fa-4856-42a1-be86-13aefe90b7d4.png)

What Windows version are you using?

**Comment by MohanramAnbukkarasu** [comment]
@miloush ,

Please find the OS details below. 

![image](https://user-images.githubusercontent.com/44049406/154896885-89925523-e7d7-4dc0-abd6-d1051c87296b.png)
