### ISSUE TITLE
Application.LoadComponent throws unexpected XamlParseException 

### ISSUE THREAD

**Issue by pavelovcharov** [dotnet/wpf#605]
* .NET Core Version: 3.0.100-preview5-011248
* Windows version: 1809 (17763.348)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 
 **Problem description:**
 The following test throws the unexpected XamlParseException:
```
    public class TestControl : Control {
    }

    [TestFixture]
    public class TestClass {
        [Test]
        public void Test00() {
            ResourceDictionary rd = (ResourceDictionary)Application.LoadComponent(new Uri("/WpfApp1;component/TestResource.xaml", UriKind.RelativeOrAbsolute));
            Assert.IsNotNull(rd);
        }
    }
```
TestResource.xaml is a resource dictionary included into the project as Resource.
```
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:local="clr-namespace:WpfApp1"
                    >

    <Style TargetType="{x:Type local:TestControl}">

    </Style>
</ResourceDictionary>
```

 **Actual behavior:** 
System.Xaml.XamlParseException
  HResult=0x80131500
  Message=Type reference cannot find type named '{clr-namespace:WpfApp1}TestControl'.
  Source=System.Xaml
  StackTrace:
``` 	System.Xaml.dll!MS.Internal.Xaml.Context.ObjectWriterContext.ServiceProvider_Resolve(string qName)	Unknown
 	System.Xaml.dll!MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateObjectWithTypeConverter(MS.Internal.Xaml.ServiceProviderContext serviceContext, System.Xaml.Schema.XamlValueConverter<System.ComponentModel.TypeConverter> ts, object value)	Unknown
 	System.Xaml.dll!System.Xaml.XamlObjectWriter.Logic_CreateFromValue(MS.Internal.Xaml.Context.ObjectWriterContext ctx, System.Xaml.Schema.XamlValueConverter<System.ComponentModel.TypeConverter> typeConverter, object value, System.Xaml.XamlMember property, string targetName, MS.Internal.Xaml.Runtime.IAddLineInfo lineInfo)	Unknown
 	System.Xaml.dll!System.Xaml.XamlObjectWriter.Logic_ConvertPositionalParamsToArgs(MS.Internal.Xaml.Context.ObjectWriterContext ctx)	Unknown
 	System.Xaml.dll!System.Xaml.XamlObjectWriter.WriteEndMember()	Unknown
 	PresentationFramework.dll!System.Windows.Markup.WpfXamlLoader.TransformNodes(System.Xaml.XamlReader xamlReader, System.Xaml.XamlObjectWriter xamlWriter, bool onlyLoadOneNode, bool skipJournaledProperties, bool shouldPassLineNumberInfo, System.Xaml.IXamlLineInfo xamlLineInfo, System.Xaml.IXamlLineInfoConsumer xamlLineInfoConsumer, MS.Internal.Xaml.Context.XamlContextStack<System.Windows.Markup.WpfXamlFrame> stack, System.Windows.Markup.IStyleConnector styleConnector)	Unknown
 	PresentationFramework.dll!System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader xamlReader, System.Xaml.IXamlObjectWriterFactory writerFactory, bool skipJournaledProperties, object rootObject, System.Xaml.XamlObjectWriterSettings settings, System.Uri baseUri)	Unknown
 	PresentationFramework.dll!System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader xamlReader, bool skipJournaledProperties, System.Uri baseUri)	Unknown
 	PresentationFramework.dll!System.Windows.Markup.XamlReader.Load(System.Xaml.XamlReader xamlReader, System.Windows.Markup.ParserContext parserContext)	Unknown
 	PresentationFramework.dll!System.Windows.Markup.XamlReader.Load(System.Xml.XmlReader reader, System.Windows.Markup.ParserContext parserContext, System.Windows.Markup.XamlParseMode parseMode, bool useRestrictiveXamlReader)	Unknown
 	PresentationFramework.dll!System.Windows.Markup.XamlReader.Load(System.IO.Stream stream, System.Windows.Markup.ParserContext parserContext, bool useRestrictiveXamlReader)	Unknown
>	WpfApp1.dll!WpfApp1.TestClass.Test00() Line 36	C#
```
 
 **Expected behavior:**
 No exceptions should be thrown
 **Minimal repro:**
git clone git@github.com:pavelovcharov/netcore3_resourceissue.git
dotnet test netcore3_resourceissue/

**Comment by ryalanms** [comment]
Thanks, @pavelovcharov.  I'll take a look.

**Comment by ryalanms** [comment]
@pavelovcharov: Thanks for the two test applications.  

I noticed there was a small difference between the .NET core and .NET Framework projects.  The markup file containing the resource dictionary was included as a Page in the .NET Framework project and as a Resource in the .NET core project.  Changing the old style .NET Framework .csproj TestResource.xaml item from a Page to a Resource and recompiling failed at runtime with the same parsing exception as the .NET core version, so the behavior appears to be the same between the two frameworks.  

```xml
   <!-- Loads via Application.LoadComponent (TestResource is loaded as baml) -->
   <Page Include="..\WpfApp1\TestResource.xaml">
      <Link>TestResource.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
```

```xml
    <!-- Throws in XamlReader.Load (TestResource is loaded as loose .xaml file) -->
    <Resource Include="..\WpfApp1\TestResource.xaml">
      <Link>TestResource.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Resource>
```
Removing the explicit Resource item in the .NET core project for TestResource.xaml will allow Microsoft.NET.Sdk.WindowsDesktop.props (https://github.com/dotnet/wpf/blob/master/packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props#L16) to automatically add the markup file as a Page instead.  This worked for me locally and the ResourceDictionary successfully loaded at runtime (on .NET core).

**Comment by pavelovcharov** [comment]
Hi @ryalanms 

In my work project the TesResource dictionary is actually included as Resource.  And it works properly in Net Framework 472. I've update my code at https://github.com/pavelovcharov/netcore3_resourceissue to demonstrate this.

![2019-04-19_07-41-37](https://user-images.githubusercontent.com/1357165/56405832-bf7fd680-6276-11e9-9723-7a0aaebd05f6.gif)

**Comment by ryalanms** [comment]
Thanks, @pavelovcharov.  I cloned the netcore3_resourceissue repro again to make sure everything was clean, rebuilt the solution in VS2019, and both tests are failing for me with the same parse exception.  

Could you try cleaning and rebuilding the solution after changing the TestResource.xaml item to Resource in the project?

**Comment by pavelovcharov** [comment]
You are right. I've cleaned the solution and the test started failing in net472 too.

**Comment by rladuca** [comment]
@pavelovcharov  @ryalanms Is this a regression?  Is there more to do with this issue?
