### ISSUE TITLE
Community Survey

### ISSUE THREAD

**Issue by singhashish-wpf** [dotnet/wpf#6052]
A few years ago, we polled community members in this repository to see how we were doing as maintainers. 

It's time to repeat the same investigation now, to gather valuable insights and become better at doing this.
 
Tell us about your experience in participating in and contributing to the project, whether you have been around for years or are new.  

We request you to complete the below survey, it'll take a few minutes and you can reply to up to 3 repositories: 
 
https://www.surveymonkey.com/r/8QTQTGJ?Source=wpf

**Comment by danmoseley** [comment]
This survey is now closed -- thanks for all the responses. We'll now dig through them.
