### ISSUE TITLE
Show a new window as CenterScreen bugged with dpi PerMonitorV2 at second screen

### ISSUE THREAD

**Issue by luojunyuan** [dotnet/wpf#6103]
* .NET Core Version: 6.0.102
* Windows version: Windows 11 21H2 22000.434
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 
 
 **Problem description:**

I have two monitors. One set as primary screen with dpi scale 300%, another one dpi 100%.

Add `app.manifest` to the project (code below). Showing a window at the second screen with `WindowStartupLocation = WindowStartupLocation.CenterScreen`. The window doesn't show at center.
 
 **Actual behavior:** 

You can see if the `MainWindow` is in primary screen, new window is correctly displayed at the center of the screen. 

If `MainWindow` at a second screen. The new window shows beyond the screen.
 
![image](https://user-images.githubusercontent.com/28323948/153412768-679fce24-80c7-46a1-ba41-a89f2e37f2df.png)

 **Expected behavior:**

The window should be in the center of the second screen.
 
 **Minimal repro:**

`app.manifest`
```xml
<application xmlns="urn:schemas-microsoft-com:asm.v3">
  <windowsSettings>
    <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
    <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
  </windowsSettings>
</application>
```
`MainWindow.xaml.cs`
```csharp
private void Button_Click(object sender, RoutedEventArgs e)
{
     new Window() 
     { 
         Width = 400,
         Height = 500,
         WindowStartupLocation = WindowStartupLocation.CenterScreen 
      }.Show();
}
```

**Extra**
Comment out the line of `PerMonitorV2` in manifest, this problem would be fixed. But the window became more blurred than using PerMonitorV2 and I can confirm that PerMonitorV2 can bring a better performance of my apps animation.
(In TaskManager, DPI aware of the app would be displayed as `System`, so the app would not receive the OnDpiChanged event...)

**Comment by Perpete** [comment]
Hello,
I think it's still the same problem described on:
WM_DPICHANGED - WM_WINDOWPOSCHANGING - WPF windows location **#3343**
Window.Left and Window.Top are broken when usign PerMonitorV2 **#4127**
