### ISSUE TITLE
Issue building with Windows Desktop 6.0.2

### ISSUE THREAD

**Issue by RussKie** [dotnet/wpf#6109]
After updating to 6.0.2 you may experience issues running WPF apps built against 6.0.2 on 6.0.0 or 6.0.1 runtime with the following error.

```
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

For an available workaround please refer to https://github.com/dotnet/core/issues/7176.

**Comment by dotMorten** [comment]
We're hitting this too. Didn't happen with 6.0.1

**Comment by FG-rgb** [comment]
Hello, is there a possibility to tell visual studio 2022 (v 17.1.0) to explicitly build with .net 6.0.0 or 6.0.1 instead of 6.0.2?

**Comment by RussKie** [comment]
6.0.3 has been released today, please consider updating. Also check https://github.com/dotnet/core/issues/7176 for suggested workarounds.

**Comment by Molinarius** [comment]
I see exactly the same issue after updating to Visual Studio 17.1.1, .NET 6.0.3, .NET SDK 6.0.201, on 2 different computers.

**Comment by FG-rgb** [comment]
Me too. A helping workaround is using a global.json in solution dir:

{
  "sdk": {
    "version": "6.0.100",
    "rollForward": "disable"
  }
}
