### ISSUE TITLE
WPF App corrupted when using GitHub Action setup-dotnet for .NET 6

### ISSUE THREAD

**Issue by philfontaine** [dotnet/wpf#6111]
### Describe the bug
The WPF app is built with GitHub Actions. The compiled application simply does not work (nothing launches, nothing appears).
The App works fine when compiled locally.
The App was created using the default WPF template, so it's a blank page.

### To Reproduce
I have a repo here https://github.com/philfontaine/gh-actions-wpf-net-6-bug showing the bug.
The `vTest1` release contains the "corrupted" application. You may create another tag `vXxx` yourself if you don't trust its content. The action runs when pushing a tag starting with `v`.

I also added a tag `vTestManualRelease` where I ran the CI steps locally, then replaced the zip in the release with the one compiled locally, redownloaded it. In that case, the app works fine.

### More Info
- .NET 5 works fine. You can see that I created a branch and a tag with .NET 5 to showcase that it works fine.
- The OS (windows-2019 vs windows-2022) does not matter (both have the same problem).
- Console applications don't have this problem.

I tried running the corrupted app on an old Windows 7 computer just for fun. I managed to get more information there:

![image](https://user-images.githubusercontent.com/16233697/153431908-7b71df7c-599e-4691-8a46-d0ad90c2dfaa.png)
![image](https://user-images.githubusercontent.com/16233697/153432030-5bdfffb6-a2b0-441a-bc41-26b48f32f599.png)

**Comment by marcpopMSFT** [comment]
Might be the same as https://github.com/dotnet/winforms/issues/6663

**Comment by philfontaine** [comment]
@marcpopMSFT Yes it is the same problem. I applied the workaround and it works now. Thanks a lot!

See also https://github.com/dotnet/core/issues/7176

**Comment by philfontaine** [comment]
https://github.com/dotnet/wpf/issues/6109 was created after too so I'll close this one.

**Comment by RifHut** [comment]
also i get errors after switching to dotnet version 6.0.0 and 6.01 and 6.0.2 
all work fine on .net version 5.0
