### ISSUE TITLE
WPF程序调用winform的控件无法设置Zindex

### ISSUE THREAD

**Issue by yutengRen** [dotnet/wpf#6121]
使用Microsoft.DwayneNeed.dll这个DLL才能在WPF中设置winform控件的Zindex。
但是这个DLL有个bug，就是创建了几十次控件后窗体上就会有个阴影。
这个问题有办法能解决吗？

**Comment by miloush** [comment]
Google Translate: 
> Use the DLL Microsoft.DwayneNeed.dll to set the Zindex of the winform control in WPF.
But this DLL has a bug, that is, after creating dozens of controls, there will be a shadow on the form.
Is there a way to solve this problem? 

Microsoft.DwayneNeed.dll is not part of WPF so I don't expect anyone here would be able to do fix any issues with it.

Do you have any code that shows the problem?

**Comment by gurpreet-wpf** [comment]
@yutengRen Please attach a sample repro to investigate this.

**Comment by pchaurasia14** [comment]
In absence of sample repro, we're closing this issue. 
If this is still a problem, feel free to file a new ticket.
