### ISSUE TITLE
Bindings for CommandParameter do not work

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/wpf#6261]
My control  contains a ListBox which I populate with an array of strings as shown below:

	<ControlTemplate TargetType="{x:Type local:DimensionButton}">
		<Border Background="{TemplateBinding Background}"
				DataContext="{Binding RelativeSource={RelativeSource AncestorType=local:DimensionButton}}">
			<local:DropDownButton
				Content="{Binding Content}" 
				SelectedItem="{Binding SelectedItem}"
				ItemTemplate="{StaticResource DimensionButtonItemTemplate}"
				Style="{StaticResource ResourceKey=DropDownButtonStyle}">
				<local:DropDownButton.ItemsSource>
					<x:Array Type="{x:Type sys:String}">
						<sys:String>Sort Ascending</sys:String>
						<sys:String>Sort Descending</sys:String>
						<sys:String>Hide</sys:String>
					</x:Array>
				</local:DropDownButton.ItemsSource>
			</local:DropDownButton>
		</Border>
	</ControlTemplate>

	

DataTemplate is shown below.  **The bindings for the `CheckBox.CommandParameter` do not work.  Why is that and how might I fix it?**  Note that Content and Action are both bound to the same string data item.  Content works - I can see it in the UI - but Action is always null as is DimensionID.

	<DataTemplate x:Key="DimensionButtonItemTemplate">
        <Border Background="Yellow" Padding="10">
            <CheckBox Content="{Binding}" // Works
                      IsChecked="{Binding RelativeSource={RelativeSource AncestorType=local:DimensionButton}, Path=SortAscending}" // Works
                      Command="{Binding RelativeSource={RelativeSource AncestorType=local:MyControl}, Path=DimensionEventCommand}" //Works
                      >
                <CheckBox.CommandParameter>
                    <local:DimensionEventArgs 
                        DimensionID="{Binding RelativeSource={RelativeSource AncestorType=local:DimensionButton}, Path=Dimension.DisplayValue}" // error can not find RelativeSource
                        Action="{Binding}"/> // No error msg in output but value is null
                </CheckBox.CommandParameter>
            </CheckBox>
        </Border>
    </DataTemplate>
	

It is interesting to note that when I put a breakpoint on the constructor of the DimensionEventArgs class (shown below) I see the object being constructed however the properties that are targets of the binding are null. 
 
Also interesting to note that if the CommandParameter is set as follows it does contain a valid string:

	<CheckBox .... CommandParameter={Binding} />

As attempt to solve the above I tried creating the DimensionEventArgs objects in the list itself as shown below.  However this time the DimensionID binding does not work and nothing I try will fix it.  Error msg:

> Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='...DimensionButton'

	<local:DropDownButton.ItemsSource>
		<x:Array Type="{x:Type local:DimensionEventArgs}">
			<local:DimensionEventArgs Action="Sort Ascending" DimensionID="{Binding RelativeSource={RelativeSource AncestorType={x:Type local:DimensionButton}}, Path=Dimension.DisplayValue}"/>
			<local:DimensionEventArgs Action="Sort Descending" DimensionID="{Binding RelativeSource={RelativeSource AncestorType={x:Type local:DimensionButton}}, Path=Dimension.DisplayValue}"/>
			<local:DimensionEventArgs Action="Hide" DimensionID="{Binding RelativeSource={RelativeSource AncestorType={x:Type local:DimensionButton}}, Path=Dimension.DisplayValue}"/>
		</x:Array>
	</local:DropDownButton.ItemsSource>

Modified the DataTemplate as follows:

	<DataTemplate x:Key="DimensionButtonItemTemplate">
		<Border Background="Yellow" Padding="10">
			<CheckBox Content="{Binding Action}" 
					  IsChecked="{Binding RelativeSource={RelativeSource AncestorType=local:DimensionButton}, Path=SortAscending}" 
					  Command="{Binding RelativeSource={RelativeSource AncestorType=local:MyControl}, Path=DimensionEventCommand}"
					  CommandParameter="{Binding}">
				
			</CheckBox>
		</Border>
	</DataTemplate>
	
	
DimensionEventArgs class:	
	
	public class DimensionEventArgs  :Control
	{

		//  Dimension.DisplayName is guaranteed to be unique and is also the ID
		public string DimensionID
		{
			get { return (string)GetValue(DimensionIDProperty); }
			set { SetValue(DimensionIDProperty, value); }
		}

		public static readonly DependencyProperty DimensionIDProperty =
			DependencyProperty.Register("DimensionID", typeof(string), typeof(DimensionEventArgs), new PropertyMetadata(null));

		public string Action
		{
			get { return (string)GetValue(ActionProperty); }
			set { SetValue(ActionProperty, value); }
		}

		public static readonly DependencyProperty ActionProperty =
			DependencyProperty.Register("Action", typeof(string), typeof(DimensionEventArgs), new PropertyMetadata(null));
	}

I appreciate any assistance.  

Versions:

	C:\Users\sam>dotnet --info
	.NET SDK (reflecting any global.json):
	 Version:   6.0.201
	 Commit:    ef40e6aa06

	Runtime Environment:
	 OS Name:     Windows
	 OS Version:  10.0.19044
	 OS Platform: Windows
	 RID:         win10-x64
	 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

	Host (useful for support):
	  Version: 6.0.3
	  Commit:  c24d9a9c91

Visual Studio 2022 17.1 latest.

**Comment by batzen** [comment]
CommandParameter is of type object and thus not automatically part of the logical/visual tree.
That's why bindings inside don't work.

You have to use a multibinding with a converter to construct your args object.

**Comment by sam-wheat** [comment]
Thank you @batzen.  I am interested to know more about why it does not work however.  I bind to object all the time i.e. Content and the bindings work fine.  And why when I bind to CommandParameter as a single line it works?: 

    <CheckBox .... CommandParameter={Binding} />

I think there are some objects in WPF where CommandParameter is not a DependencyProperty.  In the case of CheckBox however CommandParameter is a DependencyProperty and thus should be eligible to be the target of a binding.

**Comment by batzen** [comment]
That's because the current context for `CheckBox` is used. As that control is part of the logical/visual tree your binding works.

When you do
```
<CheckBox.CommandParameter>
    <local:DimensionEventArgs 
        DimensionID="{Binding RelativeSource={RelativeSource AncestorType=local:DimensionButton}, Path=Dimension.DisplayValue}" // error can not find RelativeSource
        Action="{Binding}"/> // No error msg in output but value is null
</CheckBox.CommandParameter>
```

So context switches to the value of `CommandParameter`. As `CommandParameter` is defined as `object` and is it's value is not explicitly added to the logical tree by `CheckBox` your bindings don't work inside there.

When using a multibinding for `CommandParameter` the binding gets resolved in the context of `CheckBox`.

> I think there are some objects in WPF where CommandParameter is not a DependencyProperty. In the case of CheckBox however CommandParameter is a DependencyProperty and thus should be eligible to be the target of a binding.

It is. And that's why the binding works. 
But your code creates a new object `DimensionEventArgs`, sets that as the value of `CommandParameter`. 
Having bindings inside that would require the value of `CommandParameter` to be a part of the logical tree.

The most straight forward way for you to solve your issue would be:
```
<CheckBox.CommandParameter>
    <MultiBinding Converter="{x:Static local:DimensionEventArgsConverter.Instance}">
        <Binding RelativeSource="{RelativeSource AncestorType=local:DimensionButton}"
                        Path="Dimension.DisplayValue" />
        <Binding Path="." />
    </MultiBinding>
</CheckBox.CommandParameter>
```

where `DimensionEventArgsConverter` has a public static field `Instance` of type `DimensionEventArgsConverter`, would implement `IMultiValueConverter` and return an instance of `DimensionEventArgs` in it's `Convert` method.

**Comment by sam-wheat** [comment]
Thank you again @batzen - the MultiBinding solution works.
