### ISSUE TITLE
After updating to .Net 6.0.3 through VS2022 Tooltips in WPF immediately vanish 

### ISSUE THREAD

**Issue by redseujac75** [dotnet/wpf#6289]
### Description
All Tooltips in C#, WPF project developed in VS 2022 Community .Net 6.0.2, vanish immediately after appearing. This happens with all controls (buttons, text boxes ...) with a tooltip. This problem appeared after updating to .Net 6.0.3. It wasn't there with previous .Net 6 versions.

### Configuration

* Which version of .NET is the code running on? .NET 6.0.3
* What OS and version, and for Linux, what distro? Windows 10 Pro 21H2 build 19044.1586
* What is the architecture (x64, x86, ARM, ARM64)? x64 and x86
* Do you know whether it is specific to that configuration? NO
 
### Regression?

* Did this work in a previous build or release of .NET, or from .NET Framework? If you can try a previous release or build to find out, that can help us narrow down the problem. If you don't know, that's OK.
The problem didn't exist in versions of .NET 6 preceding 6.0.3

**Comment by mikeKuester** [comment]
Our Azure DevOps build pipeline still uses .NET 6.0.2 (image windows2022). It would be very helpful if you @ Microsoft could assure that the responsive team updates .NET **after** this bug is fixed. In the moment the production build is not broken.

**Comment by ThomasGoulet73** [comment]
According to @SamBent's comment [here](https://github.com/dotnet/wpf/pull/6300#issuecomment-1076850512), this is being worked on by the WPF team.

**Comment by SamBent** [comment]
Closing this as a dupe of #6220.
