### ISSUE TITLE
WPF Window (border and title bar) renders strangely with mixed scaling

### ISSUE THREAD

**Issue by nicolaihenriksen** [dotnet/wpf#6314]
* .NET Framework Version: 4.7.2 and 4.8 (and probably all others)
* Windows version: Windows 10 and Windows 11
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No
 
 **Problem description:**
A System.Windows.Window renders strangely if you have multiple monitors (2 is enough) with different scaling. 

 **Actual behavior:**

![image](https://user-images.githubusercontent.com/19572699/160140287-b6aa900a-7df1-4699-9ce0-7ac74743b455.png)

 In my setup I have 3 monitors, monitor 1 and 2 are 4K screens running at 150% scaling. Monitor 3 is a standard full HD monitor running at 100% scaling.

When the window is rendered on monitor 2 or 3, it renders correctly:

![image](https://user-images.githubusercontent.com/19572699/160140384-7fd1c9bc-ec99-415b-bb15-647890a41fe3.png)

When the window is moved to monitor 1, it renders incorrectly (border and title bar issues):

![image](https://user-images.githubusercontent.com/19572699/160140486-2f615aa4-3d79-4541-a797-ca236225ab08.png)

 **Expected behavior:**
The window renders more or less the same regardless of the scaling applied.
 
 **Minimal repro:**
1. Setup above mentioned monitor setup.
2. Create a new "WPF App (.NET Framework)" in Visual Studio.
3. Compile and run the default "scaffolding" application created from the template.
4. Move the window between the monitors

**Additional details:**
In the screenshot where the window renders incorrectly, you can also notice a grey line below the close button. This grey line is never visible on the 150% monitors regardless of whether the window is in normal or maximized mode. However, on the 100% scaling monitor, the grey line can be "manipulated" by resizing the window (make it larger, and more of the line will appear). Also, when you maximize the window on this monitor, the line covers the complete width of the window, which is not the case when in normal mode.

If I change monitor 1 to apply the same scaling as the other monitors (150%), the problem disappears. Same thing if I change monitor 2 and 3 to 100% scaling to match monitor 1.

**Comment by lindexi** [comment]
How aboult add DPI Awareness feature?

Add the code to your App.manifest file, See [Developing a Per-Monitor DPI-Aware WPF Application - Win32 apps | Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/hidpi/declaring-managed-apps-dpi-aware?WT.mc_id=WD-MVP-5003260 )


```
<application xmlns="urn:schemas-microsoft-com:asm.v3">
  <windowsSettings>
    <!-- The combination of below two tags have the following effect : 
         1. Per-Monitor for >= Windows 10 Anniversary Update
         2. System < Windows 10 Anniversary Update -->
    <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
    <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
  </windowsSettings>
</application>
```

**Comment by Symbai** [comment]
> See [Developing a Per-Monitor DPI-Aware WPF Application - Win32 apps | Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/hidpi/declaring-managed-apps-dpi-aware?WT.mc_id=WD-MVP-5003260)

This doc says its only for Windows 8.1, for >Windows 10 it redirect users to https://github.com/microsoft/WPF-Samples/blob/main/PerMonitorDPI/readme.md where it interestingly recommends to use `PerMonitor` and not `PerMonitorV2` + even more steps are required.

**Comment by nicolaihenriksen** [comment]
Thank you for the swift replies!

@lindexi answer solved it for me.

Using PerMonitor instead of PerMonitorV2 as @Symbai suggested based on the documentation also fixes the strangely rendered borders, but the window now becomes way to "big" compared to the applied scaling.

Once again, thank you for the swift replies!
