### ISSUE TITLE
Fix dangling type-refs in DirectWriteForwarder and System.Printing

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#634]
_From @dagood on Friday, 19 April 2019 18:26:06_

When the build attempts to crossgen these files, we get warnings:

```
Warning: Could not load type 'System.Runtime.CompilerServices.SuppressMergeCheckAttribute' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. while resolving 0x1000002 - System.Runtime.CompilerServices.SuppressMergeCheckAttribute.
Warning: Could not load type 'System.Runtime.CompilerServices.DecoratedNameAttribute' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. while resolving 0x1000044 - System.Runtime.CompilerServices.DecoratedNameAttribute.
Warning: Could not load type 'System.Runtime.CompilerServices.AssemblyAttributesGoHereM' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. while resolving 0x100006d - System.Runtime.CompilerServices.AssemblyAttributesGoHereM.
Warning: Could not load type 'System.Runtime.CompilerServices.AssemblyAttributesGoHere' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. while resolving 0x1000071 - System.Runtime.CompilerServices.AssemblyAttributesGoHere.
Warning: Could not load type 'System.Runtime.InteropServices.Marshal' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. while resolving 0x1000090 - System.Runtime.InteropServices.Marshal.
Warning: Could not load type 'System.Runtime.CompilerServices.SuppressMergeCheckAttribute' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. while resolving 0xa000001 - System.Runtime.CompilerServices.SuppressMergeCheckAttribute..ctor.
Warning: Could not load type 'System.Runtime.CompilerServices.DecoratedNameAttribute' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. while resolving 0xa000014 - System.Runtime.CompilerServices.DecoratedNameAttribute..ctor.
Warning: Could not load type 'System.Runtime.InteropServices.Marshal' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. while resolving 0xa0000c2 - System.Runtime.InteropServices.Marshal.GetExceptionPointers.
Native image wd-out/DirectWriteForwarder.dll generated successfully.

Warning: Could not load type 'System.Runtime.CompilerServices.DecoratedNameAttribute' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. while resolving 0x1000004 - System.Runtime.CompilerServices.DecoratedNameAttribute.
Warning: Could not load type 'System.Runtime.CompilerServices.IsVolatile' from assembly 'System.Runtime.CompilerServices.VisualC, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. while resolving 0x100000b - System.Runtime.CompilerServices.IsVolatile.
Warning: Could not load type 'System.Runtime.CompilerServices.AssemblyAttributesGoHere' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. while resolving 0x10000a7 - System.Runtime.CompilerServices.AssemblyAttributesGoHere.
Warning: Could not load type 'System.Runtime.CompilerServices.AssemblyAttributesGoHereM' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. while resolving 0x10000b9 - System.Runtime.CompilerServices.AssemblyAttributesGoHereM.
Warning: Could not load type 'System.Runtime.InteropServices.Marshal' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. while resolving 0x100013b - System.Runtime.InteropServices.Marshal.
Warning: Could not load type 'System.Runtime.CompilerServices.DecoratedNameAttribute' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. while resolving 0xa000002 - System.Runtime.CompilerServices.DecoratedNameAttribute..ctor.
Warning: Could not load type 'System.Runtime.InteropServices.Marshal' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. while resolving 0xa0002cc - System.Runtime.InteropServices.Marshal.GetExceptionPointers.
Native image wd-out/System.Printing.dll generated successfully.
```

Core-Setup seems to be missing some dependency input to crossgen. There's an ongoing email thread to identify what it would be.

The files are safe to use, but the warnings should be fixed.

_Copied from original issue: dotnet/core-setup#5940_

**Comment by vatsan-madhavan** [comment]
_From @ericstj on Friday, 19 April 2019 19:28:35_

Actually all these look like they have the wrong AssemblyRef.  That's a problem with the C++/CLI compiler.  It looks to me like it's assuming a bunch of types are in the core library rather than resolving the type from references.  /cc @tgani-msft

**Comment by vatsan-madhavan** [comment]
_From @vatsan-madhavan on Friday, 19 April 2019 20:52:09_

/cc @dotnet/wpf-developers

**Comment by vatsan-madhavan** [comment]
_From @dleeapho on Wednesday, 01 May 2019 16:46:19_

@vatsan-madhavan can you move this issue to your repo. Also @tgani-msft is there a compiler issue logged to track?

**Comment by vatsan-madhavan** [comment]
slip to P9

**Comment by vatsan-madhavan** [comment]
We will have a new toolset in a couple of days and should be able to update the builds. This is still likely doable in Preview 9.

**Comment by vatsan-madhavan** [comment]
This is partially mitigated by #1604. 

https://github.com/dotnet/wpf/issues/1604#issuecomment-520613833
> After this is fixed, the following dangling type-refs would still be left:
> 
> * Release Builds:
>   
>   * DirectWriteForwarder:
>     
>     * `[mscorlib] System.Runtime.CompilerServices.AssemblyAttributesGoHereM`
>     * `[mscorlib] System.Runtime.CompilerServices.AssemblyAttributesGoHere`
>   * System.Printing
>     
>     * All the same problems observed in DirectWriteForwarder
>     * Additional:`[System.Runtime.CompilerServices.VisualC] System.Runtime.CompilerServices.IsVolatile`
> * Debug Builds:
>   
>   * DirectWriteForwarder
>     
>     * `[mscorlib] System.Runtime.CompilerServices.SuppressMergeCheckAttribute`
>     * `[System.Runtime] System.Runtime.CompilerServices.AssemblyAttributesGoHere`
>     * `[mscorlib] System.Runtime.CompilerServices.AssemblyAttributesGoHereM`
>     * `[mscorlib] System.Runtime.CompilerServices.AssemblyAttributesGoHere`
>   * System.Printing
>     
>     * All the same problems observed in  Debug/DirectWriteForwarder
>     * Additional: `[System.Runtime.CompilerServices.VisualC`

**Comment by vatsan-madhavan** [comment]
@sbomer, @fadimounir, if we still have these dangling type-refs, how does it negatively affect our ability to crossgen DirectWriteForwarder and System.Printing in .NET core 3.0 ? 

/cc @rladuca, @tgani-msft

**Comment by fadimounir** [comment]
@vatsan-madhavan crossgen will emit warnings on dangling typerefs, but won't fail to produce a R2R image. The affected code will be jitted at execution time, and could potentially throw exceptions at that point
