### ISSUE TITLE
Unable to use design time data for CustomControl/UseControl in WPF

### ISSUE THREAD

**Issue by MohanramAnbukkarasu** [dotnet/wpf#6393]
**Problem description:**

Unable to use design time data for custom control, same as the way we have used for WPF ListView.
 
 **Actual behavior:**
We have used the given way below to show design time data for ListView. 

![image](https://user-images.githubusercontent.com/44049406/162748690-80ba25f3-212b-4cf6-bd02-50b1816f0e5e.png)

**Reference link:**  https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-designtime-data?view=vs-2022#wpf-net-core-example

This works properly. However, we need to achieve the same for a UserControl/CustomControl. But the x:Array was not recognized for the custom control. It shows an error message as “Operation is not valid due to the current state of the object” as shown below. 

![image](https://user-images.githubusercontent.com/44049406/162748246-df8c5697-8657-4938-a29b-84e0421ba1b0.png)

Please find the example of the code snippet we have used to define the custom control’s properties. 

![image](https://user-images.githubusercontent.com/44049406/162748873-ebc334b7-8231-4d47-8fcd-be4c65f37dbb.png)

We have tried both IEnumerable type and object type properties along with attributes used for the ItemsSource property of the ListView(ItemsControl.ItemsSource property, as ListView is derived from ItemsControl). 

 **Expected behavior:**
We are expecting the custom control to recognize the x:Array to show the design time data same as it shows in ListView. 

 **Minimal repro:**
Attached sample here. 

[DesignTimeData_Demo.zip](https://github.com/dotnet/wpf/files/8464489/DesignTimeData_Demo.zip)

**Comment by gurpreet-wpf** [comment]
This seems to be a XAML designer issue. Please check with them.
