### ISSUE TITLE
WPF source code missing in Source Browser

### ISSUE THREAD

**Issue by batzen** [dotnet/wpf#6401]
Since a few days or weeks, i don't know exactly since when, WPF source code is missing on https://source.dot.net
As i don't know which team is responsible and since WinForms is still being included there i thought this might be the correct repo to report this issue.
If this is the wrong repo it would be nice to get a hint at where this should be reported or if it gets re-routed to the correct repo.

For example, browsing to https://source.dot.net/#q=frameworkelement only lists source code from PresentationBuildTasks but not from WPF itself.

**Comment by ThomasGoulet73** [comment]
@batzen Maybe a better repo would be https://github.com/KirillOsenkov/SourceBrowser ?

**Comment by batzen** [comment]
That's just the repo containing the sources for Source Browser itself. Maybe @KirillOsenkov can point to the right repo or team?
