### ISSUE TITLE
.net 6: WriteableBitmap performance lower than Net framework 4.8.

### ISSUE THREAD

**Issue by dxh-sc** [dotnet/wpf#6411]
* .NET Core Version: .net6
* Windows version: win10 or win11
* Does the bug reproduce also in WPF for .NET Framework 4.8?  No

!!!Upgrade project to Net6, the test found this problem.

when i use WriteableBitmap to display video frame, will cost 70-90 ms with .net6, but if i use .net48, have no this issue.
the frame size is 1920x1080.

_frameBitmap = new WriteableBitmap(_camera.Width, _camera.Height, 96.0, 96.0, PixelFormats.Bgr32, null);
_backBufferPointer = _frameBitmap.BackBuffer;
 _element?.Dispatcher?.Invoke(() =>
                {
                    _frameBitmap.Lock();
                    Extension.CopyMemory(_backBufferPointer, frameInfo.data, (uint)frameInfo.frameSize);
                    _frameBitmap.AddDirtyRect(_int32Rect); 
                    _frameBitmap.Unlock(); 
                }, DispatcherPriority.Send);
 
will call this method in another thread.

so is it possible to have a fix? at least the performance should be higher

or maybe there's something wrong with my way?

Thanks.

**Comment by miloush** [comment]
Do you a project that reproduces the issue?

**Comment by lindexi** [comment]
What is the `Extension.CopyMemory` ? Thank you.

**Comment by dxh-sc** [comment]
> u

**Comment by dxh-sc** [comment]
the "Extension.CopyMemory" is a windows API.

**Comment by dxh-sc** [comment]
> Do you a project that reproduces the issue?

it is our product, it is not easy provide the rep to test.

**Comment by lindexi** [comment]
@dxh-sc  I compared the codes about WriteableBitmap of .NET Framework 4.8 and .NET 6 and didn't seem to find any significant performance difference

**Comment by dxh-sc** [comment]
> 

ok, thank for your replay, but it did happen.
and i will research more.

**Comment by lindexi** [comment]
@dxh-sc Your demo code will be very valuable.

**Comment by dxh-sc** [comment]
> @dxh-sc Your demo code will be very valuable.

ok, i will try to make a demo.

**Comment by lindexi** [comment]
@dxh-sc  Could you test the performance of `Extension.CopyMemory(_backBufferPointer, frameInfo.data, (uint)frameInfo.frameSize);` ?

**Comment by lindexi** [comment]
Or using `Buffer.MemoryCopy`

**Comment by dxh-sc** [comment]
> 

yes, it will fast, less than 2ms.

**Comment by dxh-sc** [comment]
> 

ok, i will try, but i think should not there.

**Comment by lindexi** [comment]
> Extension.CopyMemory(_backBufferPointer, frameInfo.data, (uint)frameInfo.frameSize);
> this have diffrent between net48 and net6?

I'm not sure. But P/Invoke may cause some problems

**Comment by dxh-sc** [comment]
> 

ok, let do a demo first.

**Comment by gurpreet-wpf** [comment]
@dxh-sc Can you please provide a minimal repro for this issue?

**Comment by dxh-sc** [comment]
@gurpreet-wpf Hi, this is my test repro: git@github.com:dxh-sc/videotest.git

**Comment by miloush** [comment]
@dxh-sc is the repo public?

**Comment by dxh-sc** [comment]
> 

sorry, could you try it again?

**Comment by lindexi** [comment]
@dxh-sc I try your demo code and sorry I can not find the performance issues.

**Comment by dxh-sc** [comment]
> @dxh-sc I try your demo code and sorry I can not find the performance issues.

ok, thanks, but on my product project, have this issue, i will research more about it.

maybe there have many handles and threads, case the perfomance lower than demo code.

Thanks again!

**Comment by lindexi** [comment]
@dxh-sc I write a [Chinese blog](https://blog.lindexi.com/post/dotnet-%E8%AF%BB-WPF-%E6%BA%90%E4%BB%A3%E7%A0%81%E7%AC%94%E8%AE%B0-WriteableBitmap-%E7%9A%84%E6%B8%B2%E6%9F%93%E5%92%8C%E6%9B%B4%E6%96%B0%E6%98%AF%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0.html) about the WriteableBitmap Render and update. Hope more details can bring you more optimization ideas.

**Comment by dxh-sc** [comment]
> @dxh-sc I write a [Chinese blog](https://blog.lindexi.com/post/dotnet-%E8%AF%BB-WPF-%E6%BA%90%E4%BB%A3%E7%A0%81%E7%AC%94%E8%AE%B0-WriteableBitmap-%E7%9A%84%E6%B8%B2%E6%9F%93%E5%92%8C%E6%9B%B4%E6%96%B0%E6%98%AF%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0.html) about the WriteableBitmap Render and update. Hope more details can bring you more optimization ideas.

Thank for your document!
