### ISSUE TITLE
Dispatcher MemoryLeak

### ISSUE THREAD

**Issue by IAmTheCShark** [dotnet/wpf#6412]
When investigating a memory leak using a process dump from a client, I noticed that there are lots of Dispatchers

![image](https://user-images.githubusercontent.com/20905599/163154167-f171d5d4-016a-46ab-a044-e2a4c9502c75.png)

When you take a close look on the first screenshot at paths to root it looks like Dispatchers are holding references of each other.
To my understanding a Dispatcher is connected to a Thread, so how can this happen? 

The actual problem is that those dispatchers seem to hold lots of references

![image](https://user-images.githubusercontent.com/20905599/163164937-7eab28c3-dd20-4bba-85ab-7a1be58a5804.png)
![image](https://user-images.githubusercontent.com/20905599/163165000-ca808591-3dfe-4ad5-8d08-88384e897492.png)
![image](https://user-images.githubusercontent.com/20905599/163165015-cb0cf8bd-a0e1-454d-80cd-e98c97cf50ba.png)

Sadly I do not know how to reproduce this, I only have the process dump (3.5 GB).
The Application uses lots of FlowDocuments and some WindowsFormsHosts.

Observed in .net 4.8 on a TerminalServer without RemoteGFX (software rendering).
![image](https://user-images.githubusercontent.com/20905599/163165206-96a3b3ee-27e2-4179-b99d-0a77374663fd.png)

**Comment by gurpreet-wpf** [comment]
@IAmTheCShark Can you please attach the sample repro?

**Comment by IAmTheCShark** [comment]
Unfortunately I can't.
Have tried quite a while. So i guess there is not much you can do either.

**Comment by lindexi** [comment]
@IAmTheCShark I do not think so. The object be captured by MediaContext, and it means that the object is rendering. In other words, the UI is using this object. You are confused by dotMemory, and this is just one of the reference paths.

**Comment by IAmTheCShark** [comment]
@lindexi i am not entirely convinced, but lacking a reproducable example I will close this for now.
The other concerning thing is the ammount of Dispatchers, not just the "holding itself" thing.
If I ever manage to reproduce this, I will open a new issue.

**Comment by lindexi** [comment]
@IAmTheCShark  I look forward to your demo, thank you.
