### ISSUE TITLE
The first point in StylusPlugin is wrong when use the high DPI

### ISSUE THREAD

**Issue by lindexi** [dotnet/wpf#6415]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Windows version: (`winver`)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? If yes, please file the issue via the instructions [here](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/main/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**

After https://github.com/dotnet/wpf/pull/2891 , we call calculate the point with `stylusDevice.CriticalActiveSource`. But the  `stylusDevice.CriticalActiveSource` must be null when first touch down, because the wpf do not touch any element and do not get the AcitveSource before first touch down.
 
 **Actual behavior:** 

All of the StylusPlugin will reviece the wrong coordinate point.
 
 **Expected behavior:**

These points can be calculated correctly.
 
 **Minimal repro:**

Before you try repro this issues, please make sure you own a touch screen.

Preparation:

1. Set the touch screen DPI to 150% (Not 100% is enough)

Step:

1. Create an empty WPF project.
2. Add the InkCanvas control to WPF project.
3. Run the project in the device with the touch screen and then try write an ink.

Actual behavior: you will find the first point in ink will skew, just as the image shows.

![](https://github.com/dotnet/wpf/assets/16054566/4725ea7d-2eb4-49c4-ac4a-cf62bb1d8453)

![](https://github.com/dotnet/wpf/assets/16054566/a2b88548-a19e-455a-b2bd-55aaf7e97d02)

The other repro step: Create an empty WPF project and add the StylusPlugin and then output the point received.

cc @rladuca @singhashish-wpf

**Comment by lindexi** [comment]
And I think the StylusLogic.GetAndCacheTransformToDeviceMatrix should return the first Matrix when the source is null.

https://github.com/dotnet/wpf/blob/28205800de1d11595b6c598d0760af7dca1a49d3/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/StylusLogic.cs#L417-L435

**Comment by lindexi** [comment]
When the wpf will set the `stylusDevice.CriticalActiveSource` ? The `WispLogic.PreNotifyInput` will call the `stylusDevice.UpdateState` method to calculate the ActiveSource in the Main UI Thread.

But the StylusPlugin is running in the `Stylus Input` thread and fast than the UI thread.

**Comment by singhashish-wpf** [comment]
@lindexi Thanks a lot for your contributions. These PRs are currently not prioritized as the touch area isn't prioritized as of now from the team. We can prioritize it if the area receives more hits in terms of issues or more people running into this. Thanks again for the reliability data, I will try to get these 2 PRs in the next community test pass.

**Comment by lindexi** [comment]
Thank you @singhashish-wpf
