### ISSUE TITLE
Resources used in ListBox ItemTemplate not properly loaded

### ISSUE THREAD

**Issue by KMZeiseBTAC** [dotnet/wpf#6416]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`) 5.0.16 
* Windows version: (`winver`)   21H1 19043.1645
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? If yes, please file the issue via the instructions [here](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).
  No, interestingly the XAML Designer does not show the problem 
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/main/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**
When I load a &lt;Rectangle&gt; as a resource to display inside a button, which is used inside the item template for the list box, the rectangle is only displayed for the last item in the list. It should be shown on all items.

 **Actual behavior:** 

When running the example below, I see
![Example for list box output](https://user-images.githubusercontent.com/98807064/163175907-23d87e85-56a1-4ee3-8fc8-546a451bafb6.png)

On the left the rectangle loaded via a resource, and on the right the directly specified rectangle. Both sides should be the same, but are not.
 
 **Expected behavior:**
 
 **Minimal repro:**
For MainWindow.xaml, in a standard WPF App generated via Visual Studio,
``` 
  <Window.Resources>
    <LinearGradientBrush x:Key="GreenBackground" StartPoint="0,0" EndPoint="0,1">
      <GradientStop Color="#FFE4F9F2" Offset="0"/>
      <GradientStop Color="#FFA2F1D7" Offset="2.5"/>
    </LinearGradientBrush>
    <Rectangle Width="16" Height="16" x:Key="Icon-Green" Fill="{StaticResource GreenBackground}"/>
  </Window.Resources>
  <Grid>
    <ListBox Name="lstDemo" Margin="2,29,2,0">
      <ListBox.ItemTemplate>
        <DataTemplate>
          <Grid Margin="4">
            <Grid.ColumnDefinitions>
              <ColumnDefinition Width="Auto"/>
              <ColumnDefinition Width="Auto"/>
            </Grid.ColumnDefinitions>
            <Button Content="{StaticResource Icon-Green}" Width="40" Height="24" Margin="2"/>
            <Button Width="40" Height="24" Margin="2" Grid.Column="1">
              <Rectangle Width="16" Height="16" Fill="{StaticResource GreenBackground}"/>
            </Button>
          </Grid>
        </DataTemplate>
      </ListBox.ItemTemplate>
    </ListBox>
  </Grid>
```
and in MainWindow.xaml.cs
```       
        public MainWindow() {
            InitializeComponent();
            lstDemo.ItemsSource = new int[] { 1, 2, 3, 4, 5, 6 };
        }
```

**Comment by batzen** [comment]
That's because you can't re-use visual elements as they can only have one visual parent.
Defining visuals as resources is not a good idea.
You can use a DataTemplate, VisualBrush, DrawingImage or something like that to achieve what you want.

**Comment by KMZeiseBTAC** [comment]
In other words, I can work around it with defining something like
```    
    <Style x:Key="IconGreenStyle" TargetType="Rectangle">
      <Setter Property="Width" Value="16"/>
      <Setter Property="Height" Value="16"/>
      <Setter Property="Fill">
        <Setter.Value>
          <VisualBrush>
            <VisualBrush.Visual>
              <Rectangle Width="16" Height="16" Fill="{StaticResource GreenBackground}"/>
            </VisualBrush.Visual>
          </VisualBrush>
        </Setter.Value>
      </Setter>
    </Style>
``` 
and use it with `<Rectangle Style="{StaticResource IconGreenStyle}"/>`
Verbose, works only with graphics that have a known dimension, but VisualBrush has a good performance.

The simplest code seems to define a control template:
```
    <ControlTemplate TargetType="Control" x:Key="IconGreenTemplate">
      <Rectangle Width="16" Height="16" Fill="{StaticResource GreenBackground}"/>
    </ControlTemplate>
```
and use it with `<Control Template="{StaticResource IconGreenTemplate}"/>`

Thanks, now I understand the 15 year old design decision causing the problem, and the workaround.

I believe there will be more people tripping over it, and would be nice to add a warning to the XAML compiler ("A Control resource can only be used once in the visual tree, use a ControlTemplate instead")

**Comment by gurpreet-wpf** [comment]
@KMZeiseBTAC Can we close this?
