### ISSUE TITLE
Stack object allocation in UIElementHelper.InvalidateAutomationAncestors should be removed

### ISSUE THREAD

**Issue by zgabi** [dotnet/wpf#6446]
I noticed in our application, that more than 20% of the object allocations are in the UIElementHelper.InvalidateAutomationAncestors and in InvalidateAutomationAncestorsCoreHelper, which is adding to this Stack.

This Stack object should be cached somehow.

![image](https://user-images.githubusercontent.com/3104253/163646509-72956e17-9287-4fe9-b391-16e202bd17c8.png)

**Comment by gurpreet-wpf** [comment]
@zgabi Could you please attach a sample repro? Please provide more details about the issue.

**Comment by zgabi** [comment]
Not really:(
Problem occures in our application, which is quite big.
I can attach a dotMemory dump, if it helps...however you can see in the screenshot that a lot of Stack<DependencyObjects>s are allocated in UIElementHelper.InvalidateAutomationAncestors.

**Comment by IAmTheCShark** [comment]
@zgabi do you have aby controls where you override `LogicalChildren`?
Because if you do, you also need to corretly use `AddLogicalChild` / `RemoveLogicalChild`. 
Otherwise things like `DescendentsWalker` do not work correctly and cause a mess. 

I believe we had a similiar issue that was resolved this way.

**Comment by zgabi** [comment]
I checked our source code, we do not have any LogicalChildren override. We are using Telerik controls, maybe they have it.

**Comment by gurpreet-wpf** [comment]
@zgabi Can you please provide a minimal repro sample app which doesn't use Telerik controls and exhibits the same problem?

**Comment by gurpreet-wpf** [comment]
@zgabi If you have sample repro, please open a new issue for this.
