### ISSUE TITLE
Looping method call in a BackgroundWorker does an access violation instead of a StackOverflowException

### ISSUE THREAD

**Issue by Tom60chat** [dotnet/wpf#6469]
* .NET Core Version: 6.0
* Windows version: 21H2 (19044.1645)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 
 **Problem description:** Looping method call in a BackgroundWorker does an access violation instead of a StackOverflowException
 
 **Actual behavior:** Crash with code 3221225477 'Access violation'
 
 **Expected behavior:** Throw an 'System.StackOverflowException'
 
 **Minimal repro:**
```cs
public App()
{
    var worker = new BackgroundWorker();

    worker.DoWork += (sender, e) => {
        Foo();
    };

    worker.RunWorkerAsync();
}

void Foo() => Foo();
```

Discovery of a rather amusing bug.
I accidentally called a method in a loop in a BackgroundWorker but instead of having an exception and visual studio showing me where the exception took place, the application closes directly with only the message "Program exited with code 3221225477 (0xc0000005) 'Access violation'.", I was confused but after some research I found the error.

**Comment by lindexi** [comment]
@Tom60chat I do not think it is the WPF bug. Please feedback to [runtime](https://github.com/dotnet/runtime/)

**Comment by Tom60chat** [comment]
Okay, I will transfer to runtime.
