### ISSUE TITLE
XAML Autocomplete for VSCode

### ISSUE THREAD

**Issue by jhm-ciberman** [dotnet/wpf#6472]
Visual Studio UI lacks a lot of functionallity built in VSCode and the performance is terrible. I use normally VSCode for all my work and my producitivy is increased in comparison to using Visual Studio. The only downfall is the lack of proper XAML autocompletion. 

That's why I would like to request an autocomplete support extension for visual studio code. I don't want a full visual designer like in visual studio, I don't even use that, but it would be greatly appreciated to have a working XAML autocomplete.

**Comment by singhashish-wpf** [comment]
Please raise this request in vscode repo.
