### ISSUE TITLE
.NET6  "ToolTip " property display exception

### ISSUE THREAD

**Issue by xwang-888** [dotnet/wpf#6497]
Tooltip this property will disappear after flashing once when the mouse moves in.
But downgrade the project to Display normally after net5.
![image](https://user-images.githubusercontent.com/56998197/165891132-71a8bee3-f877-4961-a263-5e1ac0fb2bbc.png)

**Comment by gurpreet-wpf** [comment]
Closing this as a dupe of #6220. This will be resolved in next release.
