### ISSUE TITLE
RichTextBox does not display numeric multilevel lists (1.1, 1.2, 1.2.1 etc) in rtf files correctly.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#650]
When you load the attached &quot;example.rtf&quot; file into a System.Windows.Control.RichTextBox using richTextBox.Selection.Load(File.OpenRead(&quot;..\\..\\example.rtf&quot;), DataFormats.Rtf); the multilevel numeric list is not displayed correctly. The Major numbers of the list items are missing. See &quot;RichTextBoxNumericListsError.PNG&quot; for an example.

However, the System.Windows.Forms.RichTextBox correctly displays the list item numbering. See &quot;FormsRichTextBoxCorrect.PNG&quot; for an example.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/491250/richtextbox-does-not-display-numeric-multilevel-li.html
VSTS ticketId: 821847_
_These are the original issue comments:_

Visual Studio Feedback System on 3/17/2019, 11:59 PM (46 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by anjali-wpf** [comment]
Could you please provide the "example.rtf", "RichTextBoxNumericListsError.PNG" and a sample app for the same.
