### ISSUE TITLE
No AutomationPeers created for MenuItems when using GroupStyle

### ISSUE THREAD

**Issue by RonHeck** [dotnet/wpf#6530]
* .NET Core Version: 6
* Windows version: 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Did not try
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

 
 
 **Problem description:**
When using GroupStyle for Menu and ContextMenu, the MenuItem instances within a GroupItem are not visible in the automation tree. 
Reason: The AutomationPeer for Menu does not inherite from ItemsControlAutomationPeer. Therefore GroupItemAutomationPeer.GetChildren returns null.

 **Actual behavior:** 
No automation peers for MenuItem instances within GroupItem are shown in the AutomationTree. 

 **Expected behavior:**
There should be an AutomationPeer for each MenuItem 

 **Minimal repro:**
[TestAutomationPeerForMenu.zip](https://github.com/dotnet/wpf/files/8626528/TestAutomationPeerForMenu.zip)

I verified the AutomationTree using Accessibility Insights and Snoop.

**Comment by singhashish-wpf** [comment]
@RonHeck 
Currently [ContextMenuAutomationPeer ](https://github.com/dotnet/wpf/blob/0bb367cb2139c5e265992ddef3ca35432a227e49/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ContextMenuAutomationPeer.cs#L24) and [MenuAutomationPeer ](https://github.com/dotnet/wpf/blob/0bb367cb2139c5e265992ddef3ca35432a227e49/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/MenuAutomationPeer.cs#L24) both inherit from [FrameworkElementAutomationPeer](https://github.com/dotnet/wpf/blob/0bb367cb2139c5e265992ddef3ca35432a227e49/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/FrameworkElementAutomationPeer.cs#L22:~:text=public%20class%20FrameworkElementAutomationPeer%20%3A%20UIElementAutomationPeer)
Changing the hierarchy, i.e making both of those inherit from ItemControlAutomationPeer could result in change in behavior in ways not known to me. Could you please elaborate on your idea and throw more light on how that change would help and not interfere with the current state of the world for both the classes?

**Comment by RonHeck** [comment]
@singhashish-wpf 
IMO I am pretty busy in other tasks. If I can gather a free timeslot will try it and refer back on you.

**Comment by anjalisheel-wpf** [comment]
@RonHeck Is there any update on the same?

**Comment by RonHeck** [comment]
Sorry, but I haven't found time to try this out yet. We're in the final stages for this release right now. Maybe I can address this issue after that.

**Comment by RonHeck** [comment]
Unfortunately, I did not receive a mail that this problem requires a response (again) and was therefore closed. Finally, I think the problem has been clearly described and needs no further explanation. Changing the inheritance for the automation peer was just an idea for a possible solution. Maybe there are other possibilities, but I haven't seen any other ideas in this thread. Is it unusual for automated UI testing to navigate the menu hierarchy with automation IDs? Are there other best practices?
