### ISSUE TITLE
Microsoft.WindowsDesktop.App could not be found

### ISSUE THREAD

**Issue by okman523** [dotnet/wpf#656]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Windows version: (`winver`)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No

 
 
 **Problem description:**
 Can the wpf project  (not self-contained)  run on a .net core runtime machine? The error message "Microsoft.WindowsDesktop.App could not be found" can only install .net core sdk?
 **Actual behavior:** 
 
 **Expected behavior:**
 
 **Minimal repro:**

**Comment by ryalanms** [comment]
Thanks, @okman523.  To make sure I understand correctly, the problem is that a .NET core WPF application that targets a shared installation of the .NET core SDK fails at runtime?  Is that correct?

**Comment by okman523** [comment]
@ryalanms No, actually, what I want to ask is that a machine with .net core runtimes seems to be unable to run the wpf program. Since Microsoft.WindowsDesktop.App is not included, is it necessary to install .net core sdk to run wpf?

**Comment by andrescirulo** [comment]
I'm having the same issue. It seems that the runtime installer does not add the Microsoft.WindowsDesktop.App runtime. So you can't run a WPF app.
The (sad) solution was to install the SDK. I suppose the final version of the runtime will include WPF support.

**Comment by b2soft** [comment]
I have the same problem using 3.0.0-preview8

**Comment by weltkante** [comment]
This was already resolved (dotnet/core-setup#6384), there's supposed to be a separate bundle for the WindowsDesktop runtime in preview9, there are some download links in the PR (dotnet/core-setup#7764)
