### ISSUE TITLE
Closing inactive issues pending for >30 days

### ISSUE THREAD

**Issue by gurpreet-wpf** [dotnet/wpf#6581]
### Discussed in https://github.com/dotnet/wpf/discussions/6573

<div type='discussions-op-text'>

<sup>Originally posted by **gurpreet-wpf** May 12, 2022</sup>
Hi All,

In order to organize issues more effectively, we are planning to close the issues where minimal sample repro is not attached and which have been inactive for more than 30 days. 

Any ideas/suggestions are welcome.

Thanks!</div>

**Comment by miloush** [comment]
@lindexi If there is no repro it is probably fair. It might be worth closing them with a no-repro label. People get notified and can decide what to do, including asking to re-open or filing a new issue. It would be good if there were instructions for when a repro is provided, how can people get the issue re-opened.

**Comment by Symbai** [comment]
> If there is no repro it is probably fair

Depends on whether a) a repro is necessary at all and b) a repro can be made and c) If people have attached a repro, this gets verified very soon and the label gets removed. For example [here](https://github.com/dotnet/wpf/issues/6246) lindexi has attached a repro 1 day after its being tagged but label has not been removed for nearly 1 month. That means this issue would get auto closed in 2 days for no reason. Without further looking I'm sure there are more like this. So its questionable to introduce this action in the current situation.

**Comment by miloush** [comment]
I did not anticipate this would be an automated swipe based on existing labels. There is only a dozen issues with [needs repro](https://github.com/dotnet/wpf/labels/Needs%20minimal%20repro%20project) label.

The issue you linked I still cannot repro even with the provided executable. I'm OK with that one to be closed. #5489 on the other hand probably deserves a look. Of those issues labelled, most of them either do need a repro or could be closed.

**Comment by wstaelens** [comment]
It is not always possible to create a repro, in a solution with 10+ projects and several 10/100-thousand lines of code, 
Waiting for XPS and memory(leak) improvements 😢

**Comment by gurpreet-wpf** [comment]
As per the feedback received from the community, we will not be going ahead with this. The issues will remain active. Thanks!
