### ISSUE TITLE
XAML/Codebehind icons in VS2019 Solution Explorer are different: Framework vs. Core

### ISSUE THREAD

**Issue by thomasclaudiushuber** [dotnet/wpf#661]
* .NET Core Version: 3.0 Preview5
* Windows version: 18362.53
* Does the bug reproduce also in WPF for .NET Framework 4.8?: It's a difference in solution explorer between Framework and Core. Maybe this bug is related to Visual Studio, or WPF integration in Visual Studio.
 
 **Problem description:**
Create a WPF project in VS2019 with .NET Core, and create one with .NET Framework. The icons for XAML files and Codebehind files look different
 
 **Actual behavior:** 
It looks like this in VS2019 16.1 Preview 3. Note the different icons for XAML and C# files between the two WPF projects:

<img src="https://user-images.githubusercontent.com/7116546/57309261-0deefb00-70e8-11e9-8919-014a50253090.png" width="400">

In VS2019 16.0.3 it looks like this:

<img src="https://user-images.githubusercontent.com/7116546/57309724-daf93700-70e8-11e9-8b51-d4036d5cc422.png" width="400">

  **Expected behavior:**
 Icons should be the same for WPF on Core and Framework

**Comment by ryalanms** [comment]
Thanks, @thomasclaudiushuber.  I believe this is a VS issue.  

@diverdan92, could you help route this bug?  Thanks.

**Comment by diverdan92** [comment]
@jjmew - can you direct?

**Comment by davidwengier** [comment]
@ryalanms This can be closed as a duplicate of https://github.com/dotnet/project-system/issues/4763

It is fixed in the release of 16.1 which came out earlier this week.

**Comment by thomasclaudiushuber** [comment]
@davidwengier I tried with 16.2 Prev1. XAML files look good, but C#/codebehind files have still a different icon. Here Solution Explorer from 16.2 Prev1:

![image](https://user-images.githubusercontent.com/7116546/58310297-98cd3680-7e06-11e9-9501-e2ff7fb848f9.png)

**Comment by davkean** [comment]
This behavior is by design. We deliberately have deviated from the legacy project system here to show the "real" icons for code behind files.

**Comment by thomasclaudiushuber** [comment]
@davkean Ok, that means a decision was made, which is good. As we have the expected behavior, I close this issue. 

Thank you all for your help and thanks @davidwengier for adjusting the XAML icons.
