### ISSUE TITLE
WPF process icon can't set

### ISSUE THREAD

**Issue by Luoyingliang** [dotnet/wpf#6630]
* .NET Core Version: net5.0、net6.0
* Windows version: Windows 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* 
 
 **Problem description:**

When i use net6.0 for wpf，i set an app icon，but there are wierd thing happen。the process icon not display，but window icon set in a true way。

![image](https://user-images.githubusercontent.com/29297262/170941060-6c120bf9-fb04-4109-8617-866a0f046deb.png)

 **Actual behavior:** 
 
 **Expected behavior:**
 this icon can set using .net framework4.8。
![image](https://user-images.githubusercontent.com/29297262/170941265-e3f05952-510d-47d6-8d49-54fa82b9cc09.png)

**Comment by lindexi** [comment]
This is the Windows bug.

**Comment by Luoyingliang** [comment]
yes, it's windows bug .
