### ISSUE TITLE
wpf incorrect binding logic

### ISSUE THREAD

**Issue by brignolff** [dotnet/wpf#6658]
* .NET Core Version: 6.0.3
* Windows version: 21H2
* Does the bug reproduce also in WPF for .NET Framework 4.8?: don't know
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? If yes, please file the issue via the instructions [here](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/main/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**
Having two UC with dependency properties.
The WPF binding isn't working as expected when binding a dependency property to another one from another usercontrol.
 
 **Actual behavior:**
using this in UC1
<local:UserControl2 Margin="50,0" ColorRectangle="{Binding ColorRectangleUC1}"/>
the binding
 is setting up on the data context of UC2.
 
 **Expected behavior:**
the binding should set up on the data context of UC1
 
 **Minimal repro:**
[WpfApp12022-06-07_11-35-41.zip](https://github.com/dotnet/wpf/files/8852045/WpfApp12022-06-07_11-35-41.zip)

**Comment by pchaurasia14** [comment]
Bindings get resolved in hierarchal fashion. It starts looking for elements which have `DataContext` property defined from the current (self) node to parent node(s) (until root node). 

As soon as a control finds an element with `DataContext` defined, the search stops and the `DataContext` will be inherited (if not already found in current node).

In your case, `UserControl2.xaml` does have it's `DataContext` property set to itself.

Now, when you instantiate `UserControl2.xaml` in `UserControl1.xaml` with the `Element, Path` options, WPF has a hold of what property value to be passed.
However, when using `{Binding ...}` syntax, WPF databinding hierarchy kicks in, and the first element that has the `DataContext` defined (in this case `UserControl2.xaml` itself), it tries to locate the `ColorRectangleUC1` property on this `DataContext` object. When it is unable to locate this property, it defaults to whatever dependency property defaults have been specified.

You can see this error being explicitly thrown in VS Output window as well.

Hope this helps clarify the issue.

PS - If you're using VS 2022, you'll see an error in the XAML Binding Failure tool window as well.

**Comment by pchaurasia14** [comment]
@brignolff  - Does this answer your question ?
