### ISSUE TITLE
Would it be better to check the Freezable.CanFreeze property in SystemResources.Freeze method?

### ISSUE THREAD

**Issue by yll690** [dotnet/wpf#6701]
https://github.com/dotnet/wpf/blob/b43302b7c61c2565f39a12239d6d516c79026928/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs#L443-L450

As the code above, if the `freezable` can not be freeze, an exception will be thrown and break the application.

I encountered this issue while using Wine. It says "Initialization of 'System.Windows.Controls.Calendar' threw an exception. ---> System.InvalidOperationException: This Freezable cannot be frozen.". I think it's unlikely WPF's fault, but would it be better to check the `CanFreeze` first?

**Comment by bgrainger** [comment]
Silently failing to Freeze a Freezable resource could introduce bugs. That does not seem like an appropriate fix for the problem you're experiencing.

**Comment by pchaurasia14** [comment]
@yll690 - I agree with @bgrainger's point. Could you provide a sample repro of the problem you're encountering.

**Comment by yll690** [comment]
Yes, you are right. Thank you. I finally give up Wine as it has so many problems with WPF application. Instead I use Avalonia, and hope MAUI.Linux could coming soon.
