### ISSUE TITLE
Rename label needs-author-feedback or update fabricbot.json

### ISSUE THREAD

**Issue by ThomasGoulet73** [dotnet/wpf#6719]
fabricbot.json currently uses `waiting-author-feedback` instead of `needs-author-feedback` so adding/removing the label `needs-author-feedback` is not currently automated. Label `needs-author-feedback` should either be renamed or `waiting-author-feedback` should be replaced with `needs-author-feedback` in fabricbot.json.

**Comment by dipeshmsft** [comment]
Renamed the label to waiting-author-feedback. Closing this issue.
