### ISSUE TITLE
Source Link fails due to wrong filename casing

### ISSUE THREAD

**Issue by gix** [dotnet/wpf#6725]
Debugging into WPF's source code fails for some files due to wrong/mismatched filename casing. For example debugging into the source for ToolTip yields:

```
ToolTip.cs not found: Source Link authentication failed

You need to find ToolTip.cs to view the source for the current call stack frame

Source Link Error:
git-credential-manager-core.exe: Could not obtain credentials. Process failed with exit code -1.
ERROR: The request failed with code 404 : "Not Found". Treating 404 as authentication failure. Some services return 404 instead of 401 for authentication failures.

Source Link URL: https://raw.githubusercontent.com/dotnet/wpf/dabcf2041548f7594b21e9bf865463abdfd14307/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ToolTip.cs
```

Note that the embedded URL uses `ToolTip.cs` (because `PresentationFramework.csproj` specifies `<Compile Include="System\Windows\Controls\ToolTip.cs" />`). But the file in the repository is named `tooltip.cs` (all lowercase), and such GitHub-URLs are case-sensitive.

There may be more files that have the wrong casing (I haven't checked).

**Comment by lindexi** [comment]
Thank you @gix and I fixed it.

**Comment by dipeshmsft** [comment]
There may be some other files that may have the same issue. I think we can go ahead and fix them along with this PR.

**Comment by dipeshmsft** [comment]
@gix have you faced the same issue with some other files ??

**Comment by lindexi** [comment]
@ThomasGoulet73 Do you include my changed? Can I close my PR?

**Comment by ThomasGoulet73** [comment]
@lindexi I think you can close your PR, I included the renaming of ToolTip.cs in mine: https://github.com/dotnet/wpf/pull/6762/files#diff-4a5eb6aba8ba26c8aaf6a5c6e419b4e22d37a804acc518d1f6adab8667a2765e.

**Comment by lindexi** [comment]
Thank you @ThomasGoulet73
