### ISSUE TITLE
A11y_.NET Core_WPF_ExpenseItIntro_ExpenseReportfor_Usability: Screen reader is announcing the table data twice when it received focus.

### ISSUE THREAD

**Issue by Swati1700** [dotnet/wpf#6735]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:**#A11yUsable;#A11yTCS;#.NET Core[WPF]-Win32-June2022;#.NET Core;#A11ySev4;#NVDA;#Narrator;#DesktopApp;#Win11;#Benchmark;

### Environment Details:
.NET Core
WPF
Operating System: Windows 11 Enterprise 21H2

### Steps to Reproduce:

1. Launch VS 2022 Int Preview
2. Navigate to Getting started and right click on the Expense it intro and click on build
3. Then right click on Expense it Intro then Click on Debug-->Start New Instance. 
4. Navigate to Names list and select any name and click on View.
5. Tab to "View" button.
6. 'Expense Report for' screen will open tab till Table and 
7. Turn on the screen reader and observe the announcement.

### Actual:
Screen reader is announcing the table data twice when it received focus.

**This issue does not observe with Narrator**

### Expected:
Screen reader should not unnecessarily announce the table data twice when it received focus. It should only announce it once.

### User Impact:
Screen reader Users will get confused because of twice announcements.

https://user-images.githubusercontent.com/86710888/176373458-e84be31e-563a-405f-a74c-d28c7b3ee570.mp4

https://user-images.githubusercontent.com/86710888/176373487-e6873536-16c5-49d3-b47c-d02203c1d78f.mp4

**Comment by anjalisheel-wpf** [comment]
@Swati1700  There is no issue from WPF code side, because in such a case even narrator would have caused double announcements. You should check this with the NVDA team.

**Comment by merriemcgaw** [comment]
Note that this is tagged as a usability issue and as such there is no SLA requiring a fix either in the sample app or the WPF framework. This can be closed if the team determines that there's not a fix on the WPF side that you want to take.
