### ISSUE TITLE
ScrollViewer (apparently) resets child Grid ColumnDefinition's to *

### ISSUE THREAD

**Issue by strajk-** [dotnet/wpf#6758]
Hello,

See the following:
![image](https://user-images.githubusercontent.com/7372902/177523900-f7032653-3a7e-49d4-b296-2be6205586f0.png)
```xaml
<Grid Width="200" Height="200">
    <ScrollViewer VerticalScrollBarVisibility="Auto" HorizontalScrollBarVisibility="Auto">
        <Grid Background="Green">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="50"/>
                <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>
            <Rectangle Fill="Red" Margin="5" Grid.Column="0"/>
            <Rectangle Fill="Blue" Margin="5" Grid.Column="1"/>
            <Rectangle Fill="Violet" Opacity="0.7" Grid.Column="0" Grid.ColumnSpan="2" Width="40" HorizontalAlignment="Left"/>
        </Grid>
    </ScrollViewer>
</Grid>

```

Inside a 200x200 Grid we have a ScrollViewer, which hosts a Grid where Rectangles are occupying their respective Columns.
A third Rectangle overflows through both defined Columns, the above XAML is fine, no issue so far.

However the moment I set the Width of the third Rectangle to a size greater than what the Grid hosting the ScrollViewer supports, for example 400, the ColumnDefinitions behave as if I had set both to "*", which is incorrect, it should show the Horizontal ScrollBar, make the Grid that is inside the ScrollViewer bigger where only the Column Index 1 inscreases in Width, while 0 remains with 50px Width.
![image](https://user-images.githubusercontent.com/7372902/177524341-36c50bae-fd3f-480b-86c5-49fa773945c3.png)

Seemingly in VS2019 it still shows in the Designer that 50 and 1* are attributed, but the behavior is as if both were 1*.
This happens in both the Designer and while running the application.

Is this a bug or is my assumption incorrect and it's behaving as intended?

**Comment by singhashish-wpf** [comment]
@strajk- Please use the template for logging the issue. 
Also provide the details regarding where you are exactly facing the issue.
It will be great if you could add 2-3 more images to show the expectation vs the bug thing.

**Comment by strajk-** [comment]
> @strajk- Please use the template for logging the issue. Also provide the details regarding where you are exactly facing the issue. It will be great if you could add 2-3 more images to show the expectation vs the bug thing.

There is no need for more information, the text and two images literally state what the problem is, all you need to do is take the posted XAML and set the third Rectangle to 400px Width in order to reproduce this.

If it is expected behavior I yield, if not then it's a bug, but as far I know ColumnDefinitions and RowDefinitions are meant to behave the way you define their boundaries, and in this example they behave as if it got reset to 1*

And what template are we talking about to edit the post to fit to it accordingly?
I simply jumped here from the README.md

**Comment by huiliu-code** [comment]
Hi,@[strajk-](https://github.com/strajk-).  

Grid1 refers to the Grid outside the ScrollViewer.
Grid2 refers to the Grid inside the ScrollViewer.

Grid 2 has no set width. When changing the width of the third rectangle, the first column of Grid2 is always 50, which changes the width of the second column, causing the overall width of Grid2 to change. When the width of Grid2 is much larger than the fixed width of Grid1, the column width changes visually.

```
<Grid Width="400" Height="200">   ---> 1
        <ScrollViewer VerticalScrollBarVisibility="Auto" HorizontalScrollBarVisibility="Auto" >
            <Grid Background="Green" >    --->   2
            </Grid>
        </ScrollViewer>
    </Grid>
```

**Comment by strajk-** [comment]
Hey @huiliu-code 

Thanks your summary is correct and easier to read than mine.
The question now is if it is intended that Column1 from Grid2 changes its Width Visually if not enough space is available inside the ScrollViewer.

That's the reason I want to use a ScrollViewer to begin with, Column1 should stay 50px no matter what while Column2 gets bigger.

**Comment by strajk-** [comment]
I see there is no desire to check if this is a bug or a feature, since it's easy to work around with by setting MaxWidth I don't really care that much, but oh well, closing it.
