### ISSUE TITLE
Auto Width of TextBox doesn't fill Horizontal StackPanel correctly

### ISSUE THREAD

**Issue by JamesC01** [dotnet/wpf#6759]
* .NET Core Version: .NET 6.0
* Windows version: 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
 
 **Problem description:**
If you create a StackPanel, with horizontal orientation, and put a textbox within it (with the default auto width) the textbox doesn't fill the Stackpanel, it defaults to a width of 6. With vertical orientation, the textbox fills the whole width.
 
 **Actual behavior:**
TextBox Auto Width is too small inside horizontal oriented StackPanel 

 **Expected behavior:**
TextBox Auto Width should fill the whole stack panel when using Auto width.
 
![example screenshot](https://user-images.githubusercontent.com/31216671/177528983-b584acea-5d6c-4c28-b706-6df2c2399ce0.png)

**Comment by miloush** [comment]
> TextBox Auto Width should fill the whole stack panel when using Auto width.

No it shouldn't, it's a stack panel so in the stacking direction controls take only as much as they need. Use `DockPanel` if you want the last child to fill the rest.

**Comment by gurpreet-wpf** [comment]
@JamesC01 This is working as expected.
