### ISSUE TITLE
Setting LinearGradientBrush for more than one control not working properly

### ISSUE THREAD

**Issue by SubashiniMahendran** [dotnet/wpf#6763]
**Problem description:**

My requirement is to set the different color for bottom border as like below. So, I have used LinearGradientBrush for my requirement.

![image](https://user-images.githubusercontent.com/92976485/177701762-04b8de8d-f9b1-4005-88c2-ddc8fd5f5c70.png)

I have a viewmodel with one LinearGradientBrush type property, then I have binded this property to many controls like TextBox, Button, RichTextBox etc  BorderBrush property. Binding same LinearGradientBrush property to many controls not working as excepted. 

Please find the sample and screenshot below:

[WPF-Application.zip](https://github.com/dotnet/wpf/files/9060848/WPF-Application.zip)

![image](https://user-images.githubusercontent.com/92976485/177703408-8ecbb9c9-a8da-4ef8-80ee-a3491e10642a.png)
 
 **Actual behavior:** Binding same LinearGradientBrush property to many controls not working as excepted. 
 
 **Expected behavior:** Binding same LinearGradientBrush property to many controls should work as excepted. 

**Note:** I have checked with other platform like WinUI, this scenario works properly. Please find the sample regarding it below:

[WinUI-Application.zip](https://github.com/dotnet/wpf/files/9060857/WinUI-Application.zip)

![image](https://user-images.githubusercontent.com/92976485/177703922-5555cb6b-3140-41a2-8114-dfca9e49143d.png)

**Comment by lindexi** [comment]
@SubashiniMahendran I download your demo and change your code. Does the image as shown below meet your expectations?

![](https://user-images.githubusercontent.com/16054566/177893407-500f4bad-b073-4e80-b43d-dce25ccf269a.png)

My demo code in: https://github.com/lindexi/lindexi_gd/tree/da1fb85b58a053f3552debd0c0a009267eeeedb2/FemnearjarhuCikaigefa

**Comment by SubashiniMahendran** [comment]
@lindexi, my requirement is to provide bottom border color with one color, left top right ride side border with another color for wpf text box, button, combobox related controls as like WinUI platform TextBox controls. Please find the screenshot below:

![image](https://user-images.githubusercontent.com/92976485/177902206-751b223e-0e6b-4d9a-a1cf-24cac7615256.png)

**Comment by huiliu-code** [comment]
Hi,@[SubashiniMahendran](https://github.com/SubashiniMahendran). You could try to set BorderBrush by referring to the code below.
```
<Window.Resources>
        <LinearGradientBrush x:Key="s2" EndPoint="1,1" StartPoint="1,0">
            <GradientStop Color="Green" Offset="0"/>
            <GradientStop Color="Green" Offset="0.9"/>
            <GradientStop Color="Red" Offset="0.9"/>
            <GradientStop Color="Red" Offset="1"/>
        </LinearGradientBrush>
       
    </Window.Resources>
    <Window.DataContext>
        <local:ThemeKeyValuePair />
    </Window.DataContext>
    <StackPanel>
        <Border>
            <StackPanel>
                <Border HorizontalAlignment="Center" Visibility="Visible" Height="50" Width="280" VerticalAlignment="Center" BorderThickness="1"
                 BorderBrush="{StaticResource s2 }" 
                 x:Name="textbox2"></Border>
                <TextBox HorizontalAlignment="Center" Margin="10" Width="280" VerticalAlignment="Center" BorderThickness="1"    BorderBrush="{StaticResource s2 }"  x:Name="textbox5"/>
                <Button HorizontalAlignment="Center" Margin="10" Height="200" Visibility="Visible"   Width="280" VerticalAlignment="Center" BorderThickness="1"
                  BorderBrush="{StaticResource s2 }" 
                 x:Name="textbox3">
                    <StackPanel>
                        <TextBlock x:Name="firstPara" FontSize="11">Hello, world!</TextBlock>
                        <TextBlock TextAlignment="Left">The RichTextBox control enables you to display or edit flow content including paragraphs, images, tables, and more. This topic introduces the TextBox class and provides examples of how to use it in both Extensible Application Markup Language (XAML) and C#.</TextBlock>
                    </StackPanel>
                </Button>
            </StackPanel>
        </Border>
    </StackPanel>
```
The result:
![image](https://user-images.githubusercontent.com/79887220/177939848-f49a29cf-4bd4-4fac-8206-bd95d019af07.png)
