### ISSUE TITLE
WindowFromPoint malfunctions for x64 WPF application.

### ISSUE THREAD

**Issue by Qiu233** [dotnet/wpf#6766]
* .NET Core Version: (6.0.202)
* Windows version: (Windows 11 21H2)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Test for 4.7.1 reproduced successfully.
 
 **Problem description:**
Native function `WindowFromPoint `  cannot be used to obtain handle to windows in x64 WPF application.  
When attempting to get a window from .NET WPF process(no matter it's a remote process or the current process), it returns the 'background' window as if the WPF window does not exist.  
This problem disappeared if  `PlatformTarget` property in '.csproj' file is set to x86(default x64 in the following project).
 
 **Minimal repro:**
[WpfApp1.zip](https://github.com/dotnet/wpf/files/9066344/WpfApp1.zip) in which is a draggable cross.
Dragging the cross to any point at the window itself does not work.

**Comment by lindexi** [comment]
And I do not think it has anything to do with x64. I think it's a problem with the coordinate calculation. I updated your code in https://github.com/lindexi/lindexi_gd/tree/8fd64c8d1a2492db535c0d57ef0d84529717d339/CemlochiharwhalYukekemcu

**Comment by Qiu233** [comment]
> I commented out the code and the app behaves the same as before.

Although `TargetPlatform` is commented out, the program still runs in 64bit mode. This can be verified by logging (IntPtr.Size==8).

**Comment by lindexi** [comment]
@Qiu233 What is `it's tmodloader 1.4.3.6` means?

**Comment by Qiu233** [comment]
> @Qiu233 What is `it's tmodloader 1.4.3.6` means?

It's a modified game, running in .NET 6 x64.

**Comment by lindexi** [comment]
@Qiu233 I re-write your application and fix it.

The definition of WindowFromPoint is error. The `WindowFromPoint` should input the struct not input two arguments.

Demo code is in: https://github.com/lindexi/lindexi_gd/tree/7985ca021f43062a54fccd656239423f970e419e/CemlochiharwhalYukekemcu

**Comment by Qiu233** [comment]
Thanks. Problem solved.
