### ISSUE TITLE
Characters with different font after fallback shaped together

### ISSUE THREAD

**Issue by miloush** [dotnet/wpf#6801]
* .NET Core Version: 7.0.100-preview.4.22252.9
* Windows version: 25151.1000.amd64fre.rs_prerelease.220625-1835
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
 
 **Problem description:**

Punctuation, whitespace and alike are treated as base characters, forming clusters with vowel marks (instead of a dotted circle being inserted) when the marks are not in the font. The Indic engine is responsible for inserting the dotted circle, but it does not get to shape the run.

Someone should split the run for shaping if the characters are to be shaped using different fonts as a result of font fallback. My initial guess is line services are to blame.
 
Visual Studio is one of the affected products, the rendered glyphs depend on how the colorization and tokenization splits the runs:

![image](https://user-images.githubusercontent.com/10546952/179063982-9f609a1b-ed74-4af3-8ec9-e15f2fe4684d.png)

but

![image](https://user-images.githubusercontent.com/10546952/179065194-ecd82104-08cf-4a46-a341-af49574f2302.png)

Here is an example where the character is sometimes clustered with the preceding one (as a question mark in a box) and sometimes rendered as expected with a circle:

<img src="https://user-images.githubusercontent.com/10546952/179065344-69b4ae09-e135-4c10-9d91-65aa9e64a7a5.png">

 
 **Minimal repro:**
[FallbackShaping.zip](https://github.com/dotnet/wpf/files/9114704/FallbackShaping.zip)

![image](https://user-images.githubusercontent.com/10546952/179066341-f3b3ece3-7369-4f54-901b-81e9af82d6c8.png)

**Comment by miloush** [comment]
Found it:

https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontFace/PhysicalFontFamily.cs#L308-L316

I will check the desired behaviour here.

**Comment by lindexi** [comment]
@miloush I remember other developer raised similar issues, but I can't find the link now. Do you remember?

**Comment by miloush** [comment]
@lindexi thanks, I didn't find a similar issue either.

OK so the reason for the current behavior is that the shaping engine can normalize the string on a character level before handing it to the font tables, so technically you can have a decomposed character in the string but only precomposed character in the font.

Since the shaping is normally broken by script, I would suggest to verify that the base character is the same script as the combining mark, and if not, check whether the mark is present in the font.
