### ISSUE TITLE
Adding an Image with a TransformedBitmap (with a ScaleTransform) as Source into a canvas changes the expected size

### ISSUE THREAD

**Issue by Miryunku** [dotnet/wpf#6846]
Hello, I have a project in where you can put `Image`s in a `Canvas` and move them around and resize them.
You can extract images from the canvas (removing an `Image` from Canvas.Children) and the image "will remember" the size it had if you put the image again into the canvas, so that the user does not have to resize it again. The problem is that the image is draw with the wrong size, even though the values that I pass are correct. I checked with the debugger and they are correct at all times. It seems that the size changes when I add the image into the canvas (canvas.Children.Add(UIElement)).

I created a demo project to see if that behaviour would still be present, and it is. You can download the demo project in here:
https://1drv.ms/u/s!Amb20j9mfkXDc7HKkr6n6T7Y0rU?e=ZfOn7r
The link points to my OneDrive, towards a .7z file of 148KB. Inside the file you can find the source code, don't worry, it is a small project. I included an image that you will need as source for a BitmapImage, just copy it to the working directory.

When you compile the program, all you have to do is to press the "Insert in canvas" button for an image to appear, you can move the image around and resize it with you mouse as advertised. To resize the image, just check the "Resizer" `RadioButton` and click on the `Image` for a ResizingBorder (a UserControl) to appear.

It is more noticeable if you resize the height.

Important places are: the Button_Click_InsertInCanvas function and Canvas_MouseLeftButtonUp function (which book-keeps the values needed to set the size of the image, you will see in the debugger that they are correct).

**Comment by lindexi** [comment]
@Miryunku What is your expected behavior? thank you

**Comment by Miryunku** [comment]
Thanks to you for replying ~
In the code you can see the function `Button_Click_InsertInCanvas`, here is the body:


```cs
private void Button_Click_InsertInCanvas(object sender, RoutedEventArgs args)
        {
            try
            {
                if (listBox_skinComponents.SelectedIndex == -1)
                {
                    return;
                }

                SkinComponent component = (SkinComponent)listBox_skinComponents.SelectedItem;
                if (!component.HasTexture || component.InCanvas)
                {
                    //TODO: Delete Properties.Resources.InvalidOp_AlreadyInCanvas
                    return;
                }

                Image2 image = new(component);
                image.MouseLeftButtonDown += Image_MouseLeftButtonDown;
                image.Source = new TransformedBitmap(component.Texture, new ScaleTransform(component.m_coordinates.sw / component.Texture.PixelWidth, component.m_coordinates.sh / component.Texture.PixelHeight));

                canvas.Children.Add(image);
                component.InCanvas = true;

                Canvas.SetLeft(image, component.m_coordinates.x);
                Canvas.SetTop(image, component.m_coordinates.y);
            }
            catch (Exception e)
            {
                MessageBox.Show(this, e.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }
```

You can see that there is a part that says:

```cs
image.Source = new TransformedBitmap(component.Texture, new ScaleTransform(component.m_coordinates.sw / component.Texture.PixelWidth, component.m_coordinates.sh / component.Texture.PixelHeight));
```

That is the part that controls the size that the image will have when you add it to the canvas. The width of the image should be `component.m_coordinates.sw`, "sw" means "width". And the height of the image should be `component.m_coordinates.sh`, "sh" means "height". "sw" and "sh" are integers that keep track of the size that the image should have.

You can see that "sw" and "sh" are set in the function `Canvas_MouseLeftButtonUp`.

If an image is resized, extracted from the canvas, and then put into the canvas again, the image does not have the size that it should have.

**Comment by Miryunku** [comment]
@lindexi oops, I ended up copying from the real project instead of the demo project, sorry !! D:
The body of `Button_Click_InsertInCanvas` is this one:
```cs
private void Button_Click_InsertInCanvas(object sender, RoutedEventArgs e)
        {
            Image2 image = new(m_healthBar);
            image.Source = new TransformedBitmap(m_healthBarTexture, new ScaleTransform(m_healthBar.w / m_healthBarTexture.PixelWidth, m_healthBar.h / m_healthBarTexture.PixelHeight));
            image.MouseLeftButtonDown += Image_MouseLeftButtonDown;

            canvas.Children.Add(image);

            Canvas.SetLeft(image, m_healthBar.x);
            Canvas.SetTop(image, m_healthBar.y);
        }
```

And the line that controls the size of the image is:
```cs
image.Source = new TransformedBitmap(m_healthBarTexture, new ScaleTransform(m_healthBar.w / m_healthBarTexture.PixelWidth, m_healthBar.h / m_healthBarTexture.PixelHeight));
```

**Comment by miloush** [comment]
@Miryunku 

Please note that `PixelWidth` is an integer and dividing two integers is an integral division: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/arithmetic-operators#division-operator-

I believe you can resolve your issues by using doubles in your structure or at least `(double)m_healthBar.w / m_healthBarTexture.PixelWidth` and height respectively.

Also note that there is no need for you to be scaling the bitmap source, you can just set the width and height on the Image element. This should give you better performance and take advantage of higher resolution displays if available.

I would also recommend you check out the adornments in WPF for the resizing UI: https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/adorners-overview?view=netframeworkdesktop-4.8

**Comment by Miryunku** [comment]
@miloush

Oh my god, the integral division actually was the problem... I am embarrased.
Thank you very much for the reply, and thank you for the tips too. I tried using the Width and Height properties for the resizing before but they did not work, even if I called BeginInit() and EndInit(), which is why I came up with the Transform solution (just wanted tell you). I will definitely try the `LayoutTransform`/`RenderTransform` tip, thanks for that again.

Now, this is embarrasing for me, but if there is a slight change that this might actually be beneficial for WPF (or other frameworks) then I am going to say it:

While testing, I encountered another bug, you can see the video in my OneDrive:
https://1drv.ms/v/s!Amb20j9mfkXDdGOnOynENBJUqsE?e=Eo0NVb
You have to resize the width until it is big enough for it to happen (as you see in the video).

You can cure this behaviour if you replace this line:
```cs
m_clickedImage.Source = new TransformedBitmap(m_healthBarTexture, new ScaleTransform(m_clickedImage.ActualWidth / m_healthBarTexture.PixelWidth, (m_resizerBorder.Height - 2.0) / m_healthBarTexture.PixelHeight));
```
with this line:
```cs
m_clickedImage.Source = new TransformedBitmap(m_healthBarTexture, new ScaleTransform((m_resizerBorder.Width - 2.0) / m_healthBarTexture.PixelWidth, (m_resizerBorder.Height - 2.0) / m_healthBarTexture.PixelHeight));
```
for the top and bottom handles of the resizing border.

It probably is just something that I don't understand with the division. But as you can see this does not affect me. I am just telling you guys because of the slight chance in my mind that this might be beneficial to the framework (or other frameworks). If it is a bug in WPF, then it is great that I could help you guys find it. If it is not, then I am just dumb. Either way, please don't feel the need to contact me to tell me about it, unless you guys want to.

**Comment by miloush** [comment]
There is no need to be embarrassed, in the worst case you learn something! We all had to start somewhere.

Not sure whether you are aware, but the [`ActualWidth`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.actualwidth?view=windowsdesktop-6.0) property returns the current width (resp. height) of an element. Since your Image element is unconstrained, it will reflect the size of the bitmap it shows. And since you are changing the bitmaps all the time, the `ActualWidth` value will change as soon as this rows executes, while what you are looking for is a constant size during the whole resizing process. The replacement works better because you cache the width before resize and keep it constant in `Image_MousefLeftButtonDown`.

You don't really need to call BeginInit and EndInit in your scenario.

> just copy it to the working directory.

When you click on the image file in _Solution Explorer_ and view its properties, you can adjust the _Copy to Output Directory_ property to do the copying for you.

I'd be interested to learn what you're building. You might not even need the data structure at all, the element remembers its Canvas position and dimensions.

**Comment by Miryunku** [comment]
@miloush

Thank you for the info!

I thought that by dividing `m_clickedImage.ActualWidth / m_healthBarTexture.PixelWidth` I would keep the width of the image constant when resizing only the height.

Also, I tried both the `LayoutTransform` and `RenderTransform` approach and they work very well, the only workarounds I had to do were:
With the `RenderTransform` approach: I had to calculate the width and height of the image like this:
```cs
m_healthBar.w = (int)(m_healthBarTexture.PixelWidth * m_clickedImage.RenderTransform.Value.M11);
m_healthBar.h = (int)(m_healthBarTexture.PixelHeight * m_clickedImage.RenderTransform.Value.M22);
```
because it seems that the properties ActualWidth and ActualHeight, and RenderSize.Width/RenderSize.Height, DesiredSize.Width/DesiredSize.Height are not updated when the transformation is applied.

With the `LayoutTransform` approach: I only had to change ActualWidth and ActualHeight to DesiredSize.Width and DesiredSize.Height because the other properties have other values or are not updated.

I am going to attach a .zip file that contains only MainWindow.xaml.cs in the case you want to see the `LayoutTransform` and `RenderTransform` approaches, they are commented so it's easier to see.

> Copy to Output Directory

I didn't know this, thank you for the tip!

I am building a "skin editor" application for a videogame that I am making, it is the same genre as this videogame:
https://www.youtube.com/watch?v=2l8jst9-W14
You can see another example of another skin in the same game in here:
https://www.youtube.com/watch?v=nX9CHbOrIEQ
The idea is that the user will be able to resize the canvas to the size of his/her monitor and then organize the textures/sprites that come from a texture atlas/spritesheet however the user wants (position and size). The position (X, Y values) and size (Width, Height values) of every texture (each texture represents a skin component) will be saved in a json file (I don't modify the texture atlas image nor create a new texture atlas image). The json file will be used by the game to position and scale the sprites (the skin components) as specified by the user.
You can see an example of the real app (not the demo project) in here:
https://1drv.ms/v/s!AkVRV9eGJ20rgT56_es7sBnSmKxE?e=JP9gip
It is the same as the demo app in functionality, but you can see a ListBox in the "Skin components" section, the ListBox contains `SkinComponent` instances.

**Comment by miloush** [comment]
Great project! It might be worth checking how the layouting works in WPF, in particular [Measuring and Arranging Children](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/layout?view=netframeworkdesktop-4.8#measuring-and-arranging-children). First the system asks the element how big it would like to be (the result of which is `DesiredSize`) and then it tells it to arrange into specific space (the result of which is `RenderSize`).

`Canvas` is a bit special as it ignores the available size and places no constraints on the size of its children, so `RenderSize` will in general end up being the same as `DesiredSize` (subject to layout transform). The page above suggests `RenderTransform` gives better performance, but as you found out (and is documented in [RenderTransform](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement.rendertransform?view=windowsdesktop-6.0), it applies after the arrangement pass, so `RenderSize` will not be affected. You don't need to use transforms if setting Width and Height does the job just fine.

`ActualWidth` and `ActualHeight` are only [wrappers](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/FrameworkElement.cs,3369) around `RenderSize.Width` resp. `RenderSize.Height`.

What you might be also interested in:
* The transform has a `Transform` and `TransformBounds` methods that can transform points or rectangles.
* Given your application, you might want to [`UseLayoutRounding`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.uselayoutrounding?view=windowsdesktop-6.0) on the window (also described in the link above), so that all dimensions end up being whole pixels (integers).
* Given your application, you might want to set `RenderOptions.BitmapScalingMode="NearestNeighbor"` on the window or canvas so that the resized bitmaps don't look blurry.

**Comment by Miryunku** [comment]
@miloush

Thank you for the links and explanations!, they were very informative.

Yep, using `RenderTransform` instead of `TransformedBitmap` for the scaling provides me better performance, it was a great suggestion, and the `UseLayoutRounding` and `RenderOptions.BitmapScalingMode="NearestNeighbor"` are great suggestions too!, I didn't know them at all, and I already incorporated them into my program! thank you so much.

About using the `Width` and `Height` properties of the `Image` element for the scaling, I tried to do it, but it does not yield the expected results, the image does not change visually, which is why I came up with the transformation solutions. I will share you a .zip file that again contains MainWindow.xaml.cs, it is ready to replace the current one that you have. When you use the demo program you will see that despite changing the `Width` and `Height` properties of the `Image` element when doing the scaling, the image does not change visually, which is why I am using transformations for the scaling.
[MainWindow.xaml.cs.zip](https://github.com/dotnet/wpf/files/9215260/MainWindow.xaml.cs.zip)

**Comment by miloush** [comment]
I see. That's because the `Image` control is being fancy and by default scales the bitmap to fit the control size. You can control that using the Stretch property: https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.stretch?view=windowsdesktop-6.0

```c#
image.Stretch = Stretch.Fill;
```

should do what you want.

**Comment by Miryunku** [comment]
How could I not have realized that (┬┬﹏┬┬)
@miloush , thank you so much again, I have learned a lot in these days thanks to you, and my program can be coded to completion also thanks to you, and now with simpler code, all I can feel is gratitude, thank you!!! 😭
