### ISSUE TITLE
RowFilter is not working properly when we add the rows by using DataTable.DefaultView.AddNew().

### ISSUE THREAD

**Issue by SathiyathanamSathish** [dotnet/wpf#6860]
* Windows version: 
Edition	Windows 11 Pro
Version	21H2
Installed on	‎4/‎23/‎2022
OS build	22000.795
Experience	Windows Feature Experience Pack 1000.22000.795.0

* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)?No. 

**Problem description:**

 RowFilter is not working properly while adding the rows by using the DataTable.DefaultView.AddNew().

 **Actual behavior:** 

Filter is not applied for newly added record.
 
 **Expected behavior:**

Filter should be added for newly added record.
 
 **Minimal repro:**

1.Run the attached sample.
2.Click the "Add" button to add the FilterPredicates.
3.Ensure the Filter is applied to the DataGrid.
4.Then click the "Add Default View" button for add the Rows. **DataTable.DefaultView.AddNew()**
5.You can view the Filter is not applied properly for newly added rows.

**Note:**
1.Run the attached sample.
2.Click the "Add" button to add the FilterPredicates.
3.Ensure the Filter is applied to the DataGrid.
4.Then click the "Add NewRow" button for add the Rows. **DataTable.NewRow();**
5.You can view the Filter is applied properly for newly added rows.

We need to know why the Filter is not applied for newly added rows in the DataTable.DefaultView.

**Sample :** [DataTable_RowFilter.zip](https://github.com/dotnet/wpf/files/9231772/DataTable_RowFilter.zip)

**Comment by singhashish-wpf** [comment]
@SathiyathanamSathish 
Why is the sample updating the view? Can we not update the datatable itself? It seems if we update the underlying datatable then the filter is applied properly. From an initial glance it seems this is the sample issue rather than a product bug.

**Comment by SathiyathanamSathish** [comment]
Hi @singhashish-wpf ,
Thanks for your information. Since we need to Validate the column values before committing the NewRow. That only we added the row in the a DataTable.DefaultView ie.DataTable.DefaultView.AddNew() in DataTable.AddingNew() process.  Then Validation process will be done and then the above added row will be added to the DataTable in a CommitNew() process. 

But if we added the row by using the DataTable.NewRow() in a DataTable.AddingNew() process then the added row will be directly added to the DataTable without checking the validation process. In this case the validation process is getting failed. That only we have updating the View initially then the View.Row will be added to the DataTable  in CommitNew() Process. This will working well for Validation Process. But it breaks the Filter. That only we have created this query.

Is any possibility to validate the column values and restrict the rows adding process when we directly the add the NewRow to the DataTable?

**Comment by singhashish-wpf** [comment]
Maybe you can take a look here and get some ideas from [here](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/how-to-implement-validation-with-the-datagrid-control?view=netframeworkdesktop-4.8&viewFallbackFrom=netdesktop-6.0)
