### ISSUE TITLE
Border color does not change in Windows 11.

### ISSUE THREAD

**Issue by jameslee214** [dotnet/wpf#6896]
* .NET Core Version: NET 6
* Windows version: Windows 11
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

The Main Window border color does not change in Windows 11.

![image](https://user-images.githubusercontent.com/52397976/184502260-bbb23dcb-2163-4709-b5f1-fade694fc71b.png)

However, I confirmed that the color can be changed through a program such as a visual studio.

![image](https://user-images.githubusercontent.com/52397976/184502239-a00d23eb-695b-4059-a668-04041697ca64.png)

**Comment by lindexi** [comment]
@jameslee214 Could you add the demo code project?

**Comment by Erapchu** [comment]
If you are using WindowChrome - that behavior is normal on Windows 11. Indeed, border color does not change (they are hidden), but if you snap your window to any corner of your screen, it should looks like in Windows 10 and corners should become square.
Visual Studio main window using custom chrome window, so it's not like a usual WindowChrome or other else.
