### ISSUE TITLE
ListView Visibility Bug

### ISSUE THREAD

**Issue by MemeMachineSO** [dotnet/wpf#6909]
## Note:

Here is a sample project I created that demonstrates this behavior (same one I used in the below GIF): https://github.com/MemeMachineSO/WpfProblem

## The Problem:

I have a TabView which has a DataTemplate for each page. This template contains two ListViews, one for drives and one for files and folders. The reason I designed it this way is that drives and files/folders require different columns, and you can not change column visibility for a ListView. The closest you can do is making the column really small, which is not a good solution as the user can still resize the column.

Anyways, when the user clicks on a drive and browses it, the DrivesListView has a DataTrigger for a bool called `DrivesListViewEnabled` which will be switched to false. This should in theory hide the drives ListView, revealing the listview under it for files and folders. The problem is this does not actually occur, and the DrivesListView is still at the front, blocking the FileFoldersListView below. **However, if I open a new tab and switch back the affected tab, the `DrivesListView` is now suddenly hidden as it should be.** I am unsure what could be causing this behavior. Perhaps it refreshes something when I switch back and forth between tabs?

## A GIF of the Problem:

[![enter image description here][1]][1]

The same issue happens when I browse out from the root of a drive. It should hide the FileFoldersListView and display the DrivesListView, but this does not happen unless I switch back and forth from another tab.

I am making sure to use NotifyPropertyChanged and an ObservableCollection to ensure updates happen. I've tweaked the XAML countless times as well. 

I also tried using a BooleanToVisibilityConverter instead of a DataTrigger. This did not help.

What could be causing this to happen?

[1]: https://i.stack.imgur.com/rJogr.gif

**Comment by miloush** [comment]
> you can not change column visibility for a ListView

Can you not remove and add them back using ListView.View.Columns?

What's happening is a bit weird indeed. Unlike the first one, the second ListView (FileFolderListView) does not seem to have its DataContext updated via inheritance, basically it uses the ChildTabViewModel of the <kbd>+</kbd> tab. As a workaround, you can add `DataContext="{Binding}"` on the ListView, that seems to fix it.

**Comment by miloush** [comment]
Okay this was a tricky one! To make long story short, when you click the <kbd>+</kbd> tab, it gets selected, so the DataContext is set to the <kbd>+</kbd> VM, this is propagated to the list views, resetting their items sources and eventually causing DrivesListView.SelectionChanged to fire.

Now the unexpected bit is that this bubbles and triggers the behavior on the TabControl:

```xml
<TabControl Name="SubTabControl" Grid.Row="1" ItemsSource="{Binding ChildTabs}" DisplayMemberPath="Header" SelectedIndex="{Binding SelectedIndex}">
    <i:Interaction.Triggers>
		<i:EventTrigger EventName="SelectionChanged">
			<i:InvokeCommandAction Command="{Binding Path=TabChangedCommand}" CommandParameter="{Binding ElementName=SubTabControl}"/>
		</i:EventTrigger>
	</i:Interaction.Triggers>
```

so MWVM.TabChanged is called not because tab selection changed, but because the list view selection changed. I mean the list view selection change was ultimately triggered by the tab change, but at this point the tab hasn't been changed yet. The custom code runs (which changes selection) and then the original tab changing code finishes resetting the DataContext to the <kbd>+</kbd>'s VM, because that is the tab that was clicked in the first place.

It's a bit of a mess. The behaviour I believe is the culprit, you need to find a way to only call the MWVM method when the tab changes, or get the original source of the event and ignore it if it doesn't come from the TabControl. Or better yet, rethink the whole way you add new tabs.

**Comment by MemeMachineSO** [comment]
> Okay this was a tricky one! To make long story short, when you click the + tab, it gets selected, so the DataContext is set to the + VM, this is propagated to the list views, resetting their items sources and eventually causing DrivesListView.SelectionChanged to fire.
> 
> Now the unexpected bit is that this bubbles and triggers the behavior on the TabControl:
> 
> ```
> <TabControl Name="SubTabControl" Grid.Row="1" ItemsSource="{Binding ChildTabs}" DisplayMemberPath="Header" SelectedIndex="{Binding SelectedIndex}">
>     <i:Interaction.Triggers>
> 		<i:EventTrigger EventName="SelectionChanged">
> 			<i:InvokeCommandAction Command="{Binding Path=TabChangedCommand}" CommandParameter="{Binding ElementName=SubTabControl}"/>
> 		</i:EventTrigger>
> 	</i:Interaction.Triggers>
> ```
> 
> so MWVM.TabChanged is called not because tab selection changed, but because the list view selection changed. I mean the list view selection change was ultimately triggered by the tab change, but at this point the tab hasn't been changed yet. The custom code runs (which changes selection) and then the original tab changing code finishes resetting the DataContext to the +'s VM, because that is the tab that was clicked in the first place.
> 
> It's a bit of a mess. The behavior I believe is the culprit, you need to find a way to only call the MWVM method when the tab changes, or get the original source of the event and ignore it if it doesn't come from the TabControl. You don't really want to be doing this on the tab changed event anyway, that's a bit late, you should be doing it on preview of mouse down and marking it as handled.
> 
> Apart from binding the ListView's DataContext workaround I mentioned above, you can also queue it for later manually using
> 
> ```cs
> Dispatcher.CurrentDispatcher.InvokeAsync(() => SelectedIndex = ChildTabs.Count - 2);
> ```
> 
> That is still sort of a hack without fixing the underlying issue. Perhaps the whole way you add new tabs needs a different design.


Thank you for your response! How would I go about implementing PreviewMouseDown for the TabItems? I can do PreviewMouseDown for the entire TabControl, but is there a way to only notify if one of the TabItem headers was clicked? Even better, only if the `+` tab header was clicked.  It seems if I define the tabs statically in the XAML I can specify a PreviewMouseDown for them, but as you know I'm using a ItemsSource for them.

Hopefully once we figure that out, I can begin fixing the entire thing.

**Comment by MemeMachineSO** [comment]
> Okay this was a tricky one! To make long story short, when you click the + tab, it gets selected, so the DataContext is set to the + VM, this is propagated to the list views, resetting their items sources and eventually causing DrivesListView.SelectionChanged to fire.
> 
> Now the unexpected bit is that this bubbles and triggers the behavior on the TabControl:
> 
> ```
> <TabControl Name="SubTabControl" Grid.Row="1" ItemsSource="{Binding ChildTabs}" DisplayMemberPath="Header" SelectedIndex="{Binding SelectedIndex}">
>     <i:Interaction.Triggers>
> 		<i:EventTrigger EventName="SelectionChanged">
> 			<i:InvokeCommandAction Command="{Binding Path=TabChangedCommand}" CommandParameter="{Binding ElementName=SubTabControl}"/>
> 		</i:EventTrigger>
> 	</i:Interaction.Triggers>
> ```
> 
> so MWVM.TabChanged is called not because tab selection changed, but because the list view selection changed. I mean the list view selection change was ultimately triggered by the tab change, but at this point the tab hasn't been changed yet. The custom code runs (which changes selection) and then the original tab changing code finishes resetting the DataContext to the +'s VM, because that is the tab that was clicked in the first place.
> 
> It's a bit of a mess. The behavior I believe is the culprit, you need to find a way to only call the MWVM method when the tab changes, or get the original source of the event and ignore it if it doesn't come from the TabControl. You don't really want to be doing this on the tab changed event anyway, that's a bit late, you should be doing it on preview of mouse down and marking it as handled.
> 
> Apart from binding the ListView's DataContext workaround I mentioned above, you can also queue it for later manually using
> 
> ```cs
> Dispatcher.CurrentDispatcher.InvokeAsync(() => SelectedIndex = ChildTabs.Count - 2);
> ```
> 
> That is still sort of a hack without fixing the underlying issue. Perhaps the whole way you add new tabs needs a different design.

Thank you for your good detective work! I was able to fix the problem with this information by basically doing MouseDownPreview on the TabItems like you suggested. I added the event to each TabItem like this: https://stackoverflow.com/a/50945354/3658854
