### ISSUE TITLE
"Install other frameworks" open new file explorer window

### ISSUE THREAD

**Issue by XianghanWang** [dotnet/wpf#691]
Steps:
 Create new wpf netcore project
 Open project property page
 In Target framework dropdown, choose install other frameworks...

I expect something to direct us to the framework install files or download location, but actually got a new file explorer window pointing to Documents

**Comment by walterlv** [comment]
It seems that `Process.Start()` use the `explorer` to run a process as a proxy. But explorer.exe cannot pass any arguments to the real executable.

**Comment by weltkante** [comment]
Just for the record, you can change that behavior of `Process.Start` by passing the proper flags, and for .NET Core the defaults have been adjusted to not do that.

**Comment by grubioe** [comment]
Please log an issue to the Visual Studio dev community:
https://developercommunity.visualstudio.com/spaces/8/index.html 

Thanks!
