### ISSUE TITLE
AccessKey underscore symbol is not removing while pressing the AltKey second time or after executed action by click the Alt+AccessKey

### ISSUE THREAD

**Issue by E-Mani** [dotnet/wpf#6915]
**Problem Description:**

Underscore symbol under the AccessKey in the text does not remove when pressing the left or right AltKey second time.

Also if we invoked action by clicking the AltKey + AccessKey(e.g Alt+F) it executed action after that it does not remove the underscore symbol under the AccessKey.
 
 **Actual behavior:** 

Underscore symbol not removed under the AccessKey after executing the action or clicking the AltKey a second time.
 
 **Expected behavior:**

Need to remove the underscore symbol under AccessKey.

<img width="570" alt="AccessKey" src="https://user-images.githubusercontent.com/92844213/185637197-02260bf4-b94e-4ffa-800a-9a7755339474.png">
 
 **Replication steps:**

1. Run the below sample.
2. Press the AltKey underscore symbol enabled on AccessKey.
3. Again press the AltKey underscore symbol that does not remove it from the AccessKey.

**Sample:** [AccessKeyIssue.zip](https://github.com/dotnet/wpf/files/9382806/AccessKeyIssue.zip)

* Windows version: 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

**Comment by miloush** [comment]
Why is that the expected behavior?

It seems that Win32 behaves the same - as soon as you press Alt or Ctrl something, it will show underscores and stay as such until closed.

**Comment by E-Mani** [comment]
@miloush Expected behavior is similar to Menu control. 

**First case:** When we press the Alt key the first time, it shows the underscore symbol under the access key. Then again press the Alt key it must remove the underscore from the access key.

**Second case:** When we press the Alt + AccessKey it executes the corresponding shortcut action. After that, it must remove the underscore from the access key.

**Comment by miloush** [comment]
> Expected behavior is similar to Menu control.

Why? The behavior seems to be consistent with Win32 which differs the same way for menu and for access keys in labels/buttons. Try for example the Internet Options from Control Panel.

**Comment by E-Mani** [comment]
@miloush We have implemented similar like menu control. In that case, when we use content presenter for sub-menu items underscore symbols are not removed. 

Since we want similar like MS menu behavior else any option to remove the underscore symbols.

**Comment by miloush** [comment]
I see, that makes more sense, your example does not show any menu-like situation. Can your control derive from `MenuBase`? That class provides this functionality when `OnIsKeyboardFocusWithinChanged` via internal `KeyboardNavigation.EnableKeyboardCues` method. I don't see a public way of calling it.

You might be able to trigger it by posting [`WM_UPDATEUISTATE`](https://docs.microsoft.com/en-us/windows/win32/menurc/wm-updateuistate) to the window.
