### ISSUE TITLE
Disable lower version of target framework in wpf netcore project property page.

### ISSUE THREAD

**Issue by XianghanWang** [dotnet/wpf#692]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Windows version: RS5
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011555
 Commit:    50184f3f6c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   D:\VS\src\Tools\dotnet\sdk\3.0.100-preview5-011555\

Host (useful for support):
  Version: 3.0.0-preview5-27623-11
  Commit:  0090de2841

.NET Core SDKs installed:
  3.0.100-preview5-011555 [D:\VS\src\Tools\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview5-19223-06 [D:\VS\src\Tools\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27623-11 [D:\VS\src\Tools\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27623-11 [D:\VS\src\Tools\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

Steps to repro:
1. Create new WPF netcore project
2. Open project property page, make sure the Target framework is .net core 3.0
3. Open the drop down 

Actual: it includes all the target frameworks, from 1.0 to 3.0
Expected: we should disable all lower versions as they don't support WPF net core project.

If you switch to lower version like 2.1, build will fail.
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Controls' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)	WpfApp4	C:\Users\xiwa\source\repos\WpfApp4\WpfApp4\MainWindow.xaml.cs	7	Active​
Error	CS0234	The type or namespace name 'Data' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)	WpfApp4	C:\Users\xiwa\source\repos\WpfApp4\WpfApp4\MainWindow.xaml.cs	8	Active​
Error	CS0234	The type or namespace name 'Documents' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)	WpfApp4	C:\Users\xiwa\source\repos\WpfApp4\WpfApp4\MainWindow.xaml.cs	9	Active​
Error	CS0234	The type or namespace name 'Media' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)	WpfApp4	C:\Users\xiwa\source\repos\WpfApp4\WpfApp4\MainWindow.xaml.cs	11	Active​
Error	CS0234	The type or namespace name 'Media' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)	WpfApp4	C:\Users\xiwa\source\repos\WpfApp4\WpfApp4\MainWindow.xaml.cs	12	Active​
Error	CS0234	The type or namespace name 'Navigation' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)	WpfApp4	C:\Users\xiwa\source\repos\WpfApp4\WpfApp4\MainWindow.xaml.cs	13	Active​
Error	CS0234	The type or namespace name 'Shapes' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)	WpfApp4	C:\Users\xiwa\source\repos\WpfApp4\WpfApp4\MainWindow.xaml.cs	14	Active​
Error	CS0246	The type or namespace name 'Window' could not be found (are you missing a using directive or an assembly reference?)	WpfApp4	C:\Users\xiwa\source\repos\WpfApp4\WpfApp4\MainWindow.xaml.cs	21	Active​
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	WpfApp4	C:\Users\xiwa\source\repos\WpfApp4\WpfApp4\MainWindow.xaml.cs	25	Active​
Warning	MC6000	Project file must include the .NET Framework assembly 'PresentationCore, PresentationFramework' in the reference list.	WpfApp4	C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets	243	​
Error	NETSDK1073	The FrameworkReference 'Microsoft.WindowsDesktop.App' was not recognized	WpfApp4	C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.TargetingPackResolution.targets	173	​

**Comment by walterlv** [comment]
If WPF is not developed by Microsoft, it may never be an issue. But I still preferred that Microsoft can improve this user experience.

Assume that we have installed a NuGet package Foo which needs .NET Core 2.1 as its minimal .NET Core version, and then we change our project framework version from .NET Core 2.1 to .NET Core 1.0. And then our project will fail to build.

I write this situation down to say that it can be explained to keep the framework version range in the drop-down box. But actually, I still preferred to limit the selection range in the property page.

**Comment by grubioe** [comment]
Please log an issue for Visual Studio to https://developercommunity.visualstudio.com/

thanks!
