### ISSUE TITLE
Fake KeyUp events generated when clicing on a WPF application which is running on a remote machine

### ISSUE THREAD

**Issue by zgabi** [dotnet/wpf#6927]
* .NET 6.0
* RDP Server Windows version: Windows Server 2022 21H2 20348.887
* RDP Client Windows version Windows 10 21H2 19044.1889
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 **Problem description:**
Fake KeyUp events generated when clicing on a WPF application which is running on a remote machine
 
 **Actual behavior:** 
KeyUp event hanler called
 
 **Expected behavior:**
KeyUp event handler should not be called
 
 **Minimal repro:**
- create new WPF app
- Add a KeyUp event handler to the MainWindow and add a TextBlock:

```
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800"
        KeyUp="UIElement_OnKeyUp">
    <Grid>
        <TextBlock x:Name="TextBlock" TextWrapping="Wrap" />
    </Grid>
</Window>

```

- Add the event handler to the code:
        private void UIElement_OnKeyUp(object sender, KeyEventArgs e)
        {
            TextBlock.Text += " " + e.Key + "/" + e.SystemKey;
        }

- Run this application on a remote computer and connect to that computer with RDP.
- Deactivate the RDP window
- Activate the RDP window and click on the WPF application

Result:
![image](https://user-images.githubusercontent.com/3104253/186009552-7b53dc84-623f-4c54-b342-6de3b355195b.png)

I'm not pressing any key on the keyboard.

I'm using mstsc to connect to the remote computer. If I'm using a 3rd partry software (mRemoteNG - RDP version = Rdc6) a simialr issue happens, but instead of 3 lines of pressed key, it shows 15 lines... so much more fake keys.

**Comment by miloush** [comment]
Why is that a problem?

Either way, this is not a WPF issue, Windows does that to Win32 apps too.

**Comment by zgabi** [comment]
Because in my application I'm using a ribbon control (from Telerik), and it starts blinking the access texts for the ribbon icons 15 times when I activate the remote window.

See this bug report: https://feedback.telerik.com/wpf/1353775-ribbonview-the-keytips-are-displayed-when-the-host-remote-desktop-window-is-clicked

Ok, then where should I report this issue?

**Comment by miloush** [comment]
I suspect the behavior from Windows is intentional (like to unstuck keys that might be hanging around due to switching out and in of RDC).

I am not very much familiar with the Telerik ribbon, but it sounds like they are the ones that need to fix this. WPF Ribbon does not seem to have the issue. For example, for menu access keys, WPF checks whether the key up corresponds to a previous key down before turning them on: https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Input/KeyboardNavigation.cs,3308

**Comment by zgabi** [comment]
Telerik fixed the issue.
