### ISSUE TITLE
window auto close

### ISSUE THREAD

**Issue by 312977** [dotnet/wpf#6969]
i  have a wpf app,  used signalr to commucation ; when i opend more then  20 ,and runing  a few minutes  later ,some client aotu closed,
i have got nothing error,only vs2022 ouput window have some info: application “[44024] CarClient.exe” has exited ,return value 3221225477 (0xc0000005) 'Access violation'。

my system is  win10 64, i am  used vs2022 and .net 6.0.
i am changed the wpf  to winform or maui form ,the  problem still there
help！！！！！！

**Comment by singhashish-wpf** [comment]
@312977 The issue description is not clear. Please upload a sample app or describe the repro in proper steps so that we can check it further. Thanks ~

**Comment by miloush** [comment]
Does your application have any native code? Try enabling native debugging in project properties and/or break on first chance exceptions in the Exceptions tool window.

**Comment by 312977** [comment]
> Does your application have any native code? Try enabling native debugging in project properties and/or break on first chance exceptions in the Exceptions tool window.

yes  i  did,but there nothing exceptions.   i will  write an demo later
