### ISSUE TITLE
API to enable internal types and members in *.xaml when running in designer

### ISSUE THREAD

**Issue by etvorun** [dotnet/wpf#7004]
XAML Designer in VS needs parse loading *.xaml which contains references to internal types, properties and events. 

Try following:
[WpfApp2.zip](https://github.com/dotnet/wpf/files/9471497/WpfApp2.zip)
1. Open and build attached project in VS 2022
2. Open MainWindow.xaml.
Observe error
![image](https://user-images.githubusercontent.com/48451158/187961087-0a63bb0a-5e71-4e0c-9016-e7b59f24c86c.png)

Some details. Project contains:
```
namespace MyControls {
internal static class InternalHelper
{
  public static DependencyProperty MyTextProperty = DependencyProperty.RegisterAttached(...);
  public static string GetMyText(UIElement obj) { ... }
  public static void SetMyText(UIElement obj, string value) { ... }
} }
```
then rd.xaml
```
<ResourceDictionary xmlns:local='clr-namespase:MyControls' xmlns='...' xmlns:x='...'>
  <ControlTemplate x:Key='T1' TargeType='TextBox'/>
    <Label Content='{TemplateBinding local:InternalHelper.MyText}'/>
  </ControlTemplate>
</ResourceDictionary>
```
XAML designer in VS will do following:
1. Start helper WpfSurface.exe process.
2. Massage content of rd.xaml to make it designer friendly. It will change `xmlns:local` from  `clr-namespase:MyControls` to `clr-namespase:MyControls;assembly=MyLib`.
4. Save modified content into %tmp%\rd.xaml.
5. In WpfSurface it will create ResourceDictionary and set Source to %tmp%\rd.xaml.

Modified XAML will fail to load because it references internal types from MyLib.dll. The repro project contains an attempt to workaround this issue. We are not sure if this is the right approach. Also those WPF internals are not documented and thus we cannot use them.

**Comment by miloush** [comment]
@etvorun is this still an issue? Does not seem to reproduce for me

**Comment by etvorun** [comment]
No longer needed. There is still an issue with internal properties (in public or internal types) but we can file a different issue for that

**Comment by pchaurasia14** [comment]
@etvorun - Shall we close this issue then?

**Comment by etvorun** [comment]
We can close it
