### ISSUE TITLE
[Accessibility] In Windows 11 narrator not reading ComboBox items

### ISSUE THREAD

**Issue by beccamc** [dotnet/wpf#7005]
* .NET Core Version: **net6.0**
* Windows version: **Windows 11 22H2 OS Builder 25145.1011**
* Does the bug reproduce also in WPF for .NET Framework 4.8?: **Yes**
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? **No**

 **Problem description:**
Narrator doesn't read the individual items in the combo box. **This only reproduces in Windows 11.** 
 
 **Actual behavior:** 
Narrator won't read the items in the combo box. See attached videos of sample project. 

https://user-images.githubusercontent.com/9122518/188230022-b6477909-cbe5-4103-b857-9d55d92c11cd.mp4

 
 **Expected behavior:**
Narrator should read aloud the items as you use the arrow keys to move through the items. 
 
 **Minimal repro:**

Add items to this combo box. **It needs to have IsEdiable = true.** 
```
    <StackPanel Loaded="StackPanel_Loaded">
        <ComboBox x:Name="MyComboBox" IsEditable="True"/>
    </StackPanel>
```

[ComboBox.zip](https://github.com/dotnet/wpf/files/9480866/ComboBox.zip)

**Comment by anjalisheel-wpf** [comment]
@beccamc I investigated this bug, it seems it is narrator's issue and not specific to wpf. I observed the same behavior for tooltip and textbox as well. Please open it for the narrator team.

Linking similar item for your reference  :  https://github.com/dotnet/wpf/issues/5557
