### ISSUE TITLE
TextBox KeyUp and KeyDown-Events are not fired correctly.

### ISSUE THREAD

**Issue by bspautz1969** [dotnet/wpf#7021]
* .NET Core Version: (Net 6.04)
* Windows version: (`Windows 10`)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

**Problem description:**
 TextBox KeyUp- and KeyDown events are not fired for all keys.

 **Actual behavior:**
The KeyUp- and KeyDown-Event are only fired on special keys like 'enter' or 'tabulator'

 **Expected behavior:**
All Keys should fire the event.

**Comment by miloush** [comment]
If the events are handled by a control, they will not bubble up the tree.

Have you tried `PreviewKeyUp` and `PreviewKeyDown`?

**Comment by bspautz1969** [comment]
Yes, also the PreviewKeyUp and Down is not fired...

**Comment by bspautz1969** [comment]
https://github.com/bspautz1969/Issue

I have created an TextBox inside of a grid. In the code behind are the necessary event handler added.

Give it a try, please.
Kind regards
Bernd Spautz

**Comment by miloush** [comment]
I tried and the event handlers get fired, e.g. when I press the <kbd>a</kbd> key on US layout:

```
PreviewKeyDown
KeyDown
TextChanged
PreviewKeyUp
KeyUp
```

Which keyboard layout are you using?

**Comment by miloush** [comment]
It would matter if it was an IME that is not sending keys immediately. All normal keyboard layouts are fine. You say the events are not fired, but in your sample, you don't do anything in the event handlers. How do you check whether they are fired?

**Comment by bspautz1969** [comment]
Setting a breakpoint in visual studio.

**Comment by bspautz1969** [comment]
Sure... here we are...

'WpfEventTests.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Users\eit\RiderProjects\WpfEventTests\WpfEventTests\bin\Debug\net6.0-windows\WpfEventTests.dll'. Symbols loaded.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.8\PresentationFramework.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.8\WindowsBase.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.8\System.Xaml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'c:\program files\microsoft visual studio\2022\professional\common7\ide\commonextensions\microsoft\hotreload\Microsoft.Extensions.DotNetDeltaApplier.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.IO.Pipes.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Threading.Overlapped.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Security.Principal.Windows.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Security.AccessControl.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Security.Claims.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\Microsoft.Win32.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Runtime.Loader.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Threading.ThreadPool.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'WpfEventTests.App..ctor'
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Diagnostics.TraceSource.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.8\System.IO.Packaging.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Private.Uri.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Text.RegularExpressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.8\PresentationCore.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.8\DirectWriteForwarder.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Runtime.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Memory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Runtime.CompilerServices.VisualC.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Diagnostics.Debug.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\Microsoft.Win32.Registry.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Collections.NonGeneric.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Collections.Specialized.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.ComponentModel.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Threading.Thread.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.8\System.Configuration.ConfigurationManager.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Runtime.InteropServices.RuntimeInformation.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Xml.ReaderWriter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Private.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Net.WebClient.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.ComponentModel.EventBasedAsync.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Text.Encoding.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'WpfEventTests.App.InitializeComponent'
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.ComponentModel.TypeConverter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.8\System.Windows.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.8\UIAutomationTypes.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.ObjectModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.8\UIAutomationProvider.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Diagnostics.Process.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.8\PresentationFramework.Aero2.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Diagnostics.Tracing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'c:\program files\microsoft visual studio\2022\professional\common7\ide\commonextensions\microsoft\xamldiagnostics\Core\x64\Microsoft.VisualStudio.DesignTools.WpfTap.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Threading.Tasks.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Runtime.Serialization.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Private.DataContractSerialization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Runtime.Serialization.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Runtime.Serialization.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Resources.ResourceManager.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Reflection.Emit.ILGeneration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Reflection.Emit.Lightweight.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Reflection.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
System.Windows.Input.PreProcessInputEventArgs Keyboard.PreviewGotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewGotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewGotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.ProcessInputEventArgs Keyboard.PreviewGotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.PreProcessInputEventArgs Keyboard.PreviewKeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewKeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewKeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.ProcessInputEventArgs Keyboard.PreviewKeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.PreProcessInputEventArgs Keyboard.KeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.KeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.KeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.ProcessInputEventArgs Keyboard.KeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.PreProcessInputEventArgs Keyboard.GotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.GotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.GotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.ProcessInputEventArgs Keyboard.GotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.PreProcessInputEventArgs Keyboard.LostKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.LostKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.LostKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.ProcessInputEventArgs Keyboard.LostKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.PreProcessInputEventArgs Keyboard.PreviewGotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewGotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewGotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.ProcessInputEventArgs Keyboard.PreviewGotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.PreProcessInputEventArgs Keyboard.PreviewKeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewKeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewKeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.ProcessInputEventArgs Keyboard.PreviewKeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.PreProcessInputEventArgs Keyboard.KeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.KeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.KeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.ProcessInputEventArgs Keyboard.KeyboardInputProviderAcquireFocus WpfEventTests.MainWindow False
System.Windows.Input.PreProcessInputEventArgs Keyboard.GotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.GotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.GotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.ProcessInputEventArgs Keyboard.GotKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.PreProcessInputEventArgs Keyboard.PreviewLostKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewLostKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewLostKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.ProcessInputEventArgs Keyboard.PreviewLostKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.PreProcessInputEventArgs Keyboard.PreviewGotKeyboardFocus System.Windows.Controls.TextBox False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewGotKeyboardFocus System.Windows.Controls.TextBox False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewGotKeyboardFocus System.Windows.Controls.TextBox False
System.Windows.Input.ProcessInputEventArgs Keyboard.PreviewGotKeyboardFocus System.Windows.Controls.TextBox False
System.Windows.Input.PreProcessInputEventArgs Keyboard.PreviewKeyboardInputProviderAcquireFocus System.Windows.Controls.TextBox False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewKeyboardInputProviderAcquireFocus System.Windows.Controls.TextBox False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewKeyboardInputProviderAcquireFocus System.Windows.Controls.TextBox False
System.Windows.Input.ProcessInputEventArgs Keyboard.PreviewKeyboardInputProviderAcquireFocus System.Windows.Controls.TextBox False
System.Windows.Input.PreProcessInputEventArgs Keyboard.KeyboardInputProviderAcquireFocus System.Windows.Controls.TextBox False
System.Windows.Input.NotifyInputEventArgs Keyboard.KeyboardInputProviderAcquireFocus System.Windows.Controls.TextBox False
System.Windows.Input.NotifyInputEventArgs Keyboard.KeyboardInputProviderAcquireFocus System.Windows.Controls.TextBox False
System.Windows.Input.ProcessInputEventArgs Keyboard.KeyboardInputProviderAcquireFocus System.Windows.Controls.TextBox False
System.Windows.Input.PreProcessInputEventArgs Keyboard.LostKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.LostKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.NotifyInputEventArgs Keyboard.LostKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.ProcessInputEventArgs Keyboard.LostKeyboardFocus WpfEventTests.MainWindow False
System.Windows.Input.PreProcessInputEventArgs Keyboard.GotKeyboardFocus System.Windows.Controls.TextBox False
System.Windows.Input.NotifyInputEventArgs Keyboard.GotKeyboardFocus System.Windows.Controls.TextBox False
System.Windows.Input.NotifyInputEventArgs Keyboard.GotKeyboardFocus System.Windows.Controls.TextBox False
System.Windows.Input.ProcessInputEventArgs Keyboard.GotKeyboardFocus System.Windows.Controls.TextBox False
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
System.Windows.Input.PreProcessInputEventArgs Keyboard.PreviewKeyDown  False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewKeyDown  False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewKeyDown System.Windows.Controls.TextBox: dddddddd False
System.Windows.Input.ProcessInputEventArgs Keyboard.PreviewKeyDown System.Windows.Controls.TextBox: dddddddd False
System.Windows.Input.PreProcessInputEventArgs Keyboard.KeyDown  False
System.Windows.Input.NotifyInputEventArgs Keyboard.KeyDown  False
System.Windows.Input.NotifyInputEventArgs Keyboard.KeyDown System.Windows.Controls.TextBox: dddddddd False
System.Windows.Input.ProcessInputEventArgs Keyboard.KeyDown System.Windows.Controls.TextBox: dddddddd False
System.Windows.Input.PreProcessInputEventArgs Keyboard.PreviewKeyUp  False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewKeyUp  False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewKeyUp System.Windows.Controls.TextBox: dddddddd False
System.Windows.Input.ProcessInputEventArgs Keyboard.PreviewKeyUp System.Windows.Controls.TextBox: dddddddd False
System.Windows.Input.PreProcessInputEventArgs Keyboard.KeyUp  False
System.Windows.Input.NotifyInputEventArgs Keyboard.KeyUp  False
System.Windows.Input.NotifyInputEventArgs Keyboard.KeyUp System.Windows.Controls.TextBox: dddddddd False
System.Windows.Input.ProcessInputEventArgs Keyboard.KeyUp System.Windows.Controls.TextBox: dddddddd False
System.Windows.Input.PreProcessInputEventArgs Keyboard.LostKeyboardFocus System.Windows.Controls.TextBox: dddddddd False
System.Windows.Input.NotifyInputEventArgs Keyboard.LostKeyboardFocus System.Windows.Controls.TextBox: dddddddd False
System.Windows.Input.NotifyInputEventArgs Keyboard.LostKeyboardFocus System.Windows.Controls.TextBox: dddddddd False
System.Windows.Input.ProcessInputEventArgs Keyboard.LostKeyboardFocus System.Windows.Controls.TextBox: dddddddd False
The thread 0x7824 has exited with code 0 (0x0).
The thread 0x11098 has exited with code 0 (0x0).
The thread 0x3f7c has exited with code 0 (0x0).
The thread 0x1122c has exited with code 0 (0x0).

**Comment by miloush** [comment]
Yeah, that's weird. I am getting
```
...
'WpfEventTests.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Diagnostics.StackTrace.dll'. Symbol loading disabled by Include/Exclude setting.
System.Windows.Input.PreProcessInputEventArgs Keyboard.PreviewKeyDown  False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewKeyDown  False
UIElement_OnKeyDown
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewKeyDown System.Windows.Controls.TextBox False
System.Windows.Input.ProcessInputEventArgs Keyboard.PreviewKeyDown System.Windows.Controls.TextBox False
System.Windows.Input.PreProcessInputEventArgs Keyboard.KeyDown  False
System.Windows.Input.NotifyInputEventArgs Keyboard.KeyDown  False
UIElement_OnKeyDown
System.Windows.Input.NotifyInputEventArgs Keyboard.KeyDown System.Windows.Controls.TextBox False
System.Windows.Input.ProcessInputEventArgs Keyboard.KeyDown System.Windows.Controls.TextBox False
TextBoxBase_OnTextChanged
System.Windows.Input.PreProcessInputEventArgs Keyboard.PreviewKeyUp  False
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewKeyUp  False
UIElement_OnKeyUp
System.Windows.Input.NotifyInputEventArgs Keyboard.PreviewKeyUp System.Windows.Controls.TextBox: d False
System.Windows.Input.ProcessInputEventArgs Keyboard.PreviewKeyUp System.Windows.Controls.TextBox: d False
System.Windows.Input.PreProcessInputEventArgs Keyboard.KeyUp  False
System.Windows.Input.NotifyInputEventArgs Keyboard.KeyUp  False
UIElement_OnKeyUp
System.Windows.Input.NotifyInputEventArgs Keyboard.KeyUp System.Windows.Controls.TextBox: d False
System.Windows.Input.ProcessInputEventArgs Keyboard.KeyUp System.Windows.Controls.TextBox: d False
...
```

for each key press individually. It looks like you are getting none of these since dddddddd appears at once. We could try to go deeper in trying to figure out why but it is getting more challenging to do that over GitHub. I am afraid without anyone else being able to reproduce the problem, it will be difficult to help.

Does this happen in other framework versions? If you put the [Preview]KeyUp/Down events on an empty window, do they fire as keys are pressed? It looks like you are not receiving the messages from Windows in the first place, do the events work e.g. in a Windows Forms project?

Thanks,
Jan

**Comment by bspautz1969** [comment]
You are right. The most interesting thing is the following. It was working correctly the last time i have tested my application. The KeyDown-Event is necessary for me. I am validating an input in my application. And when the valuenis correct a button is enabled to fire the changes. Yesterday than i found this little issue. To be sire that the issue is not based in my application i have created the empty one. And this issue is on different versions of net and also dotnet framework. Tomorrow i try to reproduce this issue in different Windows-Versions. Maybe it is only in my developer machine. That would be bad but solveable. I am going to give you a more detailled information tomorrow. Thanks for you help and effort so far.
Kind regards
Bernd

**Comment by miloush** [comment]
If you are familiar with the [Spy++](https://docs.microsoft.com/en-us/visualstudio/debugger/introducing-spy-increment?view=vs-2022) tool, you could use it to look at the keyboard messages being sent to the window (which would then be translated to the KeyUp/KeyDown events):

![image](https://user-images.githubusercontent.com/10546952/189219308-6e5a96f3-3e48-45d9-b767-538459d12e2f.png)

If you don't get those, then something is going on on the machine rather than in WPF.

**Comment by bspautz1969** [comment]
I have copied my little test application to a clean Windows 10 System.
All normal keys events are missing.
It is exactly the same behavior than on my developer machine.

**Windows version test machine:**
Windows 10 Pro
Language: English (US)
Version 21H2 (OS Build 19044.1826)
Patch level: up to date

**Net version test machine:**
Microsoft Windows Desktop Runtime - 6.0.8 (x64)
Version 6.0.8.31518

**Comment by miloush** [comment]
@bspautz1969 Thank you, I am not sure what else to try. Would you be able to check whether WM_KEYDOWN/WM_KEYUP messages are sent to the Window, or see if the same problem happens to Windows Forms applications?

**Comment by bspautz1969** [comment]
After my vacation I investigated the topic a little more closely. Whatever the reason, this error only occurs during an RDP session on IOS devices. And strangely only the normal keys a-z and 0-9 are affected and not the rest. Since this is the famous special case in the negligible region, I hereby withdraw this bug as relevant. Thank you very much for the trouble and I apologize for the inconvenience.

**Comment by miloush** [comment]
@bspautz1969 thank you for reporting back! It sounds to me that either only WM_CHAR messages are send either due to how the iOS input stack works, or because of an issue in the RDP client.
