### ISSUE TITLE
Define Double as Static Resource - (xmlns:system="clr-namespace:System;assembly=mscorlib" hack)

### ISSUE THREAD

**Issue by PeterOscarsson** [dotnet/wpf#708]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`) 3.0 preview 5
* Windows version: (`winver`) 1809
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

  
 **Problem description:**

xmlns:system="clr-namespace:System;assembly=mscorlib"
not allowed in XAML

 **Actual behavior:** 
 Compiler error

 **Expected behavior:**

 Be able to define
        <system:Double x:Key = "XLargeWidth">200</system:Double>
            <system:Double x:Key = "StartingPointY">-20</system:Double>

for use in styles.

Setter Property="Width" Value="{StaticResource XLargeWidth}" 

 **Minimal repro:**
 Trivial

I guess (hope) I am missing something trivial.

**Comment by weltkante** [comment]
you need to switch the assembly name, .NET Core has no "mscorlib"

**Comment by ryalanms** [comment]
@PeterOscarsson: As @weltkante pointed out, .NET core doesn't use mscorlib.  But any mscorlib references in .NET core should be type forwarded to System.Runtime automatically, so your scenario should work.

The markup below is working for me with 3.0.100-preview6-012085.  Could you try a more recent version of the .NET core SDK?  Thanks.

```xaml
<Window x:Class="t10.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:t10"
        xmlns:system="clr-namespace:System;assembly=mscorlib"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
        <Window.Resources>
        </Window.Resources>
    <Grid>
    <Grid.Resources>
        <ResourceDictionary>
            <system:Double x:Key = "XLargeWidth">200</system:Double>
            <system:Double x:Key = "StartingPointY">-20</system:Double>
        </ResourceDictionary>
    </Grid.Resources>

        <Rectangle Fill="Red" Height="100" Width="{StaticResource XLargeWidth}"/>

    </Grid>
</Window>
```

**Comment by rrelyea** [comment]
(by the way, x:Double likely works in WPF and WPF core.)
Moving away from CLR assembly names for these "core" types may be a good idea...but would take tooling, etc... confirmations. Likely better to keep XAML in a form that can load in both worlds.
