### ISSUE TITLE
My WPF project has a namespace error

### ISSUE THREAD

**Issue by 344089386** [dotnet/wpf#7125]
Error Tip:
No type or namespace name "Windows" in namespace "test.wpf.system" (missing assembly reference?)

This error occurs when my project contains the System namespace.
I predict this is due to the implicit namespaces of.net6.
I tried `<DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>` and `<Using Remove="XXX.System" />`  but it didn't work.

![image](https://user-images.githubusercontent.com/22017199/191935560-2c0b601d-507b-481b-921a-fd2807f9cca7.png)

Repeat steps：
build project

Error Code：
https://github.com/344089386/WpfTest

**Comment by miloush** [comment]
I don't think this has anything to do with implicit usings. You are introducing `Test.Wpf.System` namespace in `UserInfo.cs` and your window is in the `Test.Wpf` namespace. All `System` namespaces then resolve to `Test.Wpf.System` which has precedence.

So don't do that. Technically you could argue that the code generator should use global namespace alias, though I think you would have to present a compelling justification for such change.

**Comment by 344089386** [comment]
This is a large engineering System, and there are other hierarchies that use similar System namespaces. This problem occurs when WPF references other libraries.

1, if you change the namespace of other class libraries, then the change will be a little big.

2. I think there should be a default setting that you can configure and disable.

**Comment by miloush** [comment]
The problem is if you put e.g. a Window into that hierarchy. The libraries cannot inherit anything from the System namespace and they cannot be used by anything that is in the same hierarchy, unless specific and not very common syntax is used. That seems like an unfortunate choice of namespaces.

That said, the resource generator for example does use global namespace alias, so it is not an unreasonable expectation. If we do that, we might break some applications that rely on this behavior, but I don't expect that to be of a significant risk.

**Comment by 344089386** [comment]
Can I only change the name of the namespace now? Is there a middle ground?

**Comment by miloush** [comment]
Not that I am aware of, you would have to change the root namespace, in your example put your App and MainWindow into TestUI.Wpf namespace.

**Comment by 344089386** [comment]
All right. Thank you for your trouble. I'm gonna go change the namespace

**Comment by chris-kruining** [comment]
> I don't think this has anything to do with implicit usings. You are introducing `Test.Wpf.System` namespace in `UserInfo.cs` and your window is in the `Test.Wpf` namespace. All `System` namespaces then resolve to `Test.Wpf.System` which has precedence.
> 
> So don't do that. Technically you could argue that the code generator should use global namespace alias, though I think you would have to present a compelling justification for such change.

@miloush Wouldn't this issue be resolved if the code generator applies the `global::` prefix if a `assembly` is passed via the attribute? this related to my issue in #7173
