### ISSUE TITLE
Performance issue occurs loading data in DataGrid and application go to not responding state

### ISSUE THREAD

**Issue by vijayarasan** [dotnet/wpf#7138]
* .NET Core Version: Net 6.0
* Windows version: Windows 10 Pro 21H1
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio? No

 
 
 **Problem description:**  Performance issue occurs when loading 800 records at runtime in DataGrid and application go to not responding state.
 
 **Actual behavior:**  Data loading is delayed and the application go to not responding the state
 
 **Expected behavior:** Data should be loaded properly without the loading delay and the application not responding to the issue
 
 **Minimal repro:** 
 Step 1: Run the Application
 
 Step 2: Open the Task Manager to ensure the application not responding state
 
 Step 3: Click the Load Data button
 
 Please find the sample and video demo for your reference
 
[Sample And Video Demo.zip](https://github.com/dotnet/wpf/files/9677865/Sample.And.Video.Demo.zip)
 
 Please check this and share the solution to resolve the reported performance issue

**Comment by miloush** [comment]
@vijayarasan that is because your `DataGrid` is unconstrained in size, so you are asking it to render all rows at once. For virtualization to work, make sure you give it fixed or maximum height, either explicitly or through panels. For example, if you put `Height="200"` on the `DataGrid` it will load fast.

**Comment by singhashish-wpf** [comment]
@vijayarasan Does the above comment by @miloush help your case? Please confirm.

**Comment by vijayarasan** [comment]
@singhashish-wpf, Yes the provided suggestion meets our requirements. @miloush, Thanks for the update
