### ISSUE TITLE
transparency of FontFamily is different from office

### ISSUE THREAD

**Issue by tomuGo** [dotnet/wpf#7160]
* .NET Core Version: 6
* Windows version: win11
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? If yes, please file the issue via the instructions [here](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/main/README.md#reporting-security-issues-and-security-bugs).

 
 
![image](https://user-images.githubusercontent.com/24789356/194007108-1808cb53-14e2-40bf-a478-f1fe1fa0fc81.png)

 
As shown in the picture，The color depth of the same font is inconsistent。
here is MainWindow.XAML:
`<TextBlock Grid.Row="0" Text="Microsoft YaHei " Opacity="1" FontFamily="yahei" FontSize="14" Foreground="#000000"></TextBlock>`

here is APP.XAML

`<Application x:Class="Test.App"  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:Test"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>

                <ResourceDictionary>
                   
                    <FontFamily x:Key="yahei">
                        Pack://application:,,,;C:\Windows\Fonts\msyh.ttc
                    </FontFamily>
                </ResourceDictionary>
                
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>`

**Comment by miloush** [comment]
First of all, there is no guarantee that different applications should render text the same.

Second, that's not how you set a font family, your TextBlock is using the default font. Use `FontFamily="Microsoft YaHei"` on the TextBlock. There is no need for the dictionary, also the URI is wrong, you cannot use absolute paths with pack URIs, see https://learn.microsoft.com/en-us/dotnet/desktop/wpf/app-development/pack-uris-in-wpf?view=netframeworkdesktop-4.8.

**Comment by lindexi** [comment]
@tomuGo You need to use `Microsoft YaHei UI`.

```
<TextBlock  FontFamily="Microsoft YaHei UI" />
```

**Comment by lindexi** [comment]
@tomuGo Is your problem solved?
