### ISSUE TITLE
Simplify nested properties in XAML

### ISSUE THREAD

**Issue by KA-Logis** [dotnet/wpf#7170]
If today, for example, I want to bind a property like Text on TextBlock as a nested XAML tag, this should be done like:
```
<local:CustomColorTextBlock>
  <local:CustomColorTextBlock.Text>
    <!-- Reason could be to use a MultiBinding. -->
  </local:CustomColorTextBlock.Text>
<local:CustomColorTextBlock>
```

It would be a need feature if I didn't have to prefix all my nested tags with the FrameworkElement type, but could instead write it as:

```
<local:CustomColorTextBlock>
  <.Text>
    <!-- Much simpler, especially if binding a lot of properties. -->
  </.Text>
<local:CustomColorTextBlock>
```

**Comment by miloush** [comment]
That would not be a valid XML, see http://www.w3.org/TR/REC-xml/#sec-common-syn
