### ISSUE TITLE
`Slider.Ticks` binding IReadOnlyList<double> trap

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/wpf#7172]
* .NET Core Version: `6`
* Windows version: `Win10 21H2
* Does the bug reproduce also in WPF for .NET Framework 4.8?: `Never test.`
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)?: `NO`
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/main/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**
`Slider.Ticks` is a `DoubleCollection`, but in xaml binding syntax, it allows binding to `IReadOnlyList<double>`, and there's not any binding errors at run time. This makes one think that the binding has been successful, but the ticks drawing is wrong.

Also discussed here: https://github.com/HandyOrg/HandyControl/issues/1269

**Relative codes**:
```cs
public class RootViewModel : PropertyChangedBase {
    public IReadOnlyList<double>? Ticks { get; set; }

    public double MinStrike { get; set; }

    public double MaxStrike { get; set; } = 10;

    public double StartStrike { get; set; }

    public double EndStrike { get; set; }

    public void UpdateTicks() {
        Ticks = new[] { 1d, 2d, 5d, 20d, 50d, 200d };

        StartStrike = MinStrike = Ticks[0];
        EndStrike = MaxStrike = Ticks[^1];
    }
}
```

```xaml
<hc:RangeSlider IsSnapToTickEnabled="True" Ticks="{Binding Ticks}" TickPlacement="Both"
                hc:TipElement.Visibility="Visible" hc:TipElement.Placement="Bottom"
                Minimum="{Binding MinStrike}" Maximum="{Binding MaxStrike}" 
                ValueStart="{Binding StartStrike}" ValueEnd="{Binding EndStrike}" />
<Slider Margin="0 20 0 0" IsSnapToTickEnabled="True" Ticks="{Binding Ticks}" TickPlacement="Both" 
        Minimum="{Binding MinStrike}" Maximum="{Binding MaxStrike}" />
<Button Margin="0 20 0 0" Content="Update Ticks" Command="{s:Action UpdateTicks}" />
```

 **Actual behavior:** 
 The ticks are drawn incorrectly, and there are no binding errors.

![image](https://user-images.githubusercontent.com/4510984/194559728-97d846b4-1175-4d0e-8909-8862d0584cb5.png)

 **Expected behavior:**
`Slider.Ticks` accepts `IReadOnlyList<double>` for drawing ticks, or show binding errors at run time in Visual Studio Binding Error window.
 
 **Minimal repro:**
[RangeSliderDemo.zip](https://github.com/dotnet/wpf/files/9734099/RangeSliderDemo.zip)

**Comment by miloush** [comment]
The target is of type `DoubleCollection` so you cannot set anything else to it. The behavior of default converters could most certainly be documented better than "If in doubt, create your own converter."

In case of interfaces, the default converter (`InterfaceConverter`) produces `null` if the value does not implement the desired interface, which you can also see when you enable tracing on the binding:

```
System.Windows.Data Warning: 95 : BindingExpression (hash=9369539): Got PropertyChanged event from RootViewModel (hash=32089967)
System.Windows.Data Warning: 101 : BindingExpression (hash=9369539): GetValue at level 0 from RootViewModel (hash=32089967) using RuntimePropertyInfo(Ticks): Double[] (hash=53406450 Count=6)
System.Windows.Data Warning: 80 : BindingExpression (hash=9369539): TransferValue - got raw value Double[] (hash=53406450 Count=6)
System.Windows.Data Warning: 84 : BindingExpression (hash=9369539): TransferValue - implicit converter produced <null>
System.Windows.Data Warning: 89 : BindingExpression (hash=9369539): TransferValue - using final value <null>
```

Throwing an exception here would be a breaking change, but I agree some hint in the debug output would be helpful.
