### ISSUE TITLE
Update KB5018410 changes ListView behavior in a way that makes software unusable

### ISSUE THREAD

**Issue by obiben** [dotnet/wpf#7199]
* .NET Framework Version: 4.6.2
* Windows version: 21H1

 
 
 **Problem description:**
ScrollViewer changed behavior after windows update KB5018410. Most obviously demonstrated in `ListView` 

 
 **Actual behavior:** 
 Inserting item at index 0, even when ListView is ScrollOffset == 0, will scroll down one item

 **Expected behavior:**
When scrolled at the top, inserting an item at 0 should not move the scrollbar. New item should be displayed without scrolling up.
 
 **Minimal repro:**
Bind a ListView to a ObservableCollection and add enough items to display a vertical scroll bar
Make sure scrollbar is at the top
Insert an item at index 0
ListView is now scrolled down 1 item

Here's a minimal repro solution:
[ListViewUpdate.zip](https://github.com/dotnet/wpf/files/9813869/ListViewUpdate.zip)

Behavior before update:
You will see items being added as the button is clicked

Behavior after update:
You will see items 1-4 being added, after which you will keep seeing 1-4 and the scrollbar will indicate you are scrolling down.

**Comment by miloush** [comment]
@obiben it would be helpful if you could attach the repro project

**Comment by hausenism** [comment]
https://gitee.com/hausenism/wpf-issues-7199.git

@miloush

**Comment by hausenism** [comment]
This change affects our major product. We have many customers complaining on this changed behavior.
MVVM makes us impossible to call ListView.ScrollIntoView every time we Insert new items.
For now we have to ask customers to uninstall this KB update and disable this wsus.

**Comment by obiben** [comment]
@miloush added repro to post.

**Comment by miloush** [comment]
Thank you. Can you not ScrollIntoView the added item?

**Comment by hausenism** [comment]
related: https://developercommunity.visualstudio.com/t/WPF-ListView-scroll-issue-after-windows/10159769

**Comment by hausenism** [comment]
related: https://developercommunity.visualstudio.com/t/WPF-ListView-scroll-issue-after-windows/10159769

**Comment by miloush** [comment]
I was more hoping we could have a productive discussion about which behavior is the correct one. You could argue that other platforms behave the same way or there are accessibility standards that ask for such behavior, if that was the case, and I could argue that the same does not happen at the end when you are scrolled down and that some could view the new behavior as a bug fix that makes sure items do not move randomly without you touching the scrollbar.

Then someone would actually do some work and came with an argument that this happens only for virtualizing stack panel with content scroll enabled and suddenly you have much more convincing argument this is a bug that needs fixing.

**Comment by hausenism** [comment]
@SamBent https://github.com/dotnet/wpf/commit/a30c4edea55a95ec9d7c2d29d79b2d4fb12ed973

**Comment by hausenism** [comment]
```
﻿<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <AppContextSwitchOverrides value="Switch.System.Windows.Controls.VirtualizingStackPanel.OptOutOfCollectionChangeFix=true" />
  </runtime>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.2" />
  </startup>
</configuration>
```

Solution: add 'Switch.System.Windows.Controls.VirtualizingStackPanel.OptOutOfCollectionChangeFix' to App.config file

references:
1. https://docs.driveworkspro.com/Topic/KB22101401
2. decomplied source code of .net compared.

demo git repo fix commit: https://gitee.com/hausenism/wpf-issues-7199/commit/270d5c3d92b3b7590681eaa8f9ea71cbc0ba6139

**Comment by obiben** [comment]
> I was more hoping we could have a productive discussion about which behavior is the correct one and why. You could argue that other platforms behave the same way or there are accessibility standards that ask for such behavior, if that was the case, and I could argue that the same does not happen at the end when you are scrolled down and that some could view the new behavior as a bug fix that makes sure items do not move randomly without you touching the scrollbar.
> 
> Then someone would actually do some work and came with an argument that this happens only for virtualizing stack panel with content scroll enabled and suddenly you have much more convincing argument this is a bug that needs fixing.

I'm not an english speaker and so the tone of this is unclear; the conditionnals confuse me.

It seems to me that the correct behavior is not changing `ScrollOffset` when changing the represented collection. That is why, as I understand it, if you were at the bottom end of the list, adding an item wouldn't change the scroll offset and you'd have to `ScrollIntoView`. If at the top of the list with `ScrollOffset` being 0, adding a new item should also not change the `ScrollOffset` and the new item should therefore come into view of its own accord. This behavior is fairly well known and a developer could choose whether he put items at index 0 or at the end of a list to easily get the behavior he wanted.

In any case, I'd be hard pressed to accept that a new behavior that makes existing apps unusable is an acceptable bugfix. If this was a bug that WPF devs wanted to fix, I'd assume they'd give an option to change the behavior without breaking software already in the wild.

**Comment by dipeshmsft** [comment]
@obiben thanks for the simple repro, we are currently looking into this bug.

**Comment by dipeshmsft** [comment]
The update with the fix for this issue is released. ( https://devblogs.microsoft.com/dotnet/dotnet-framework-january-2023-update/ ) 
@obiben @hausenism, you can disable the opt-out switch and the applications should work as they were working before.
Thanks a lot for your patience.
