### ISSUE TITLE
VisualStateGroup not working

### ISSUE THREAD

**Issue by Marv51** [dotnet/wpf#72]
* .NET Core Version: 3.0 Preview1 (3.0.100-preview-009812)
* Windows version: win10 1809 17763
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**
This is probably a know issue of the first preview, very excited about this thing by the way!

Running my app, I get exceptions for windows that contain a `System.Windows.VisualStateGroup`(only tested via xaml). See below. 
I had this on three different windows and removing the VisualStateGroup fixes it. (That of course also removes the functionality)

I guess this is not yet done?  Known Bug? Or something real?
 
 **Actual behavior:**
 System.Windows.Markup.XamlParseException: "'Set connectionId threw an exception.' Line number '11' and line position '14'."
Inner Exception:
InvalidCastException: Unable to cast object of type 'System.Windows.VisualStateGroup' to type 'System.Windows.Shapes.Ellipse'.

 **Expected behavior:**
Should work as it does in dotnet framework.

 
 **Minimal(ish) repro:**
```xaml
<Grid Name="TheEllipse" MouseUp="TheEllipse_MouseUp">
    <VisualStateManager.VisualStateGroups>
        <VisualStateGroup Name="MouseStates">
            <VisualState Name="MouseEnter">
                <Storyboard>
                    <ColorAnimation To="#A1A1A1" Duration="00:00:00.3" Storyboard.TargetName="BackFill" Storyboard.TargetProperty="(SolidColorBrush.Color)" />
                </Storyboard>
            </VisualState>
        </VisualStateGroup>
   </VisualStateManager.VisualStateGroups>
   <Ellipse Stroke="Black" StrokeThickness="1">
       <Ellipse.Fill>
           <SolidColorBrush x:Name="BackFill" Color="#F1F1F1" />
       </Ellipse.Fill>
   </Ellipse>
</Grid>
```

**Comment by ryalanms** [comment]
@Marv51, could you try with a recent SDK?  There were some fixes to PresentationBuidTasks, and the markup in the minimal repro is now working.  Thanks.

**Comment by Marv51** [comment]
@ryalanms Thanks for keeping me updated on this! Unfortunately, I am crazy busy right now and won't be able to really test this in the next two weeks.

**Comment by ryalanms** [comment]
@Marv51: Thank you for raising this issue.  It appears to be fixed in the most recent SDK, so I'm closing the issue for now.  Please reactivate if you hit it again.  THanks.
