### ISSUE TITLE
[NetSDKE2E][Loc]With VS 17.4 preview 4 + .NET 7 RTM SDK:7.0.100 installed on Loc OS, the template names for WPF are unlocalized after running "dotnet new --list" in CLI .

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/wpf#7204]
Steps:
1.VS17.4.0 Preview 4.0 [33013.205.d17.4] from d17.4 branch of https://ddweb/Dashboard/vsbuild + NET 7 RTM SDK:7.0.100 from https://github.com/dotnet/installer
2.Run "dotnet new --list" in CLI.

Expected result:
Template names are localized.

Actual Result:
Template names for WPF are not localized.

e.g
SC:
![image](https://user-images.githubusercontent.com/87680983/195798174-aa68e9eb-e992-4e39-aa39-e10cf8fec049.png)

TK:
![image](https://user-images.githubusercontent.com/87680983/195801959-60b135aa-cca0-486a-90f4-8324f7dd24d9.png)

EN:
![image](https://user-images.githubusercontent.com/87680983/195806754-a3f2e4c7-b83e-442c-8afe-458e6031e8f9.png)

Note:
Only NET 7 RTM SDK:7.0.100 installed in clean Loc OS, the template names are localized.
![image](https://user-images.githubusercontent.com/87680983/195802967-caa22748-71bf-4947-8538-302cf6b3eb01.png)

dotnet info:
.NET SDK:
 Version:   7.0.100
 Commit:    fbaf018066

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0-rtm.22511.4
  Architecture: x64
  Commit:       d25158d0df

.NET SDKs installed:
  7.0.100-rc.2.22477.23 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rtm.22512.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rtm.22511.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.2.22472.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by miloush** [comment]
https://github.com/dotnet/winforms/pull/6319 might be hepful

**Comment by dipeshmsft** [comment]
@vlada-shubina @marcpopMSFT , it seems from the notes that localization is working fine for WPF Project Templates with the SDK ( before installing VS ), but after installing VS localization for templates seems to stop working. 

Is WPF missing something ?

**Comment by dipeshmsft** [comment]
> [dotnet/winforms#6319](https://github.com/dotnet/winforms/pull/6319) might be hepful

@miloush Corresponding PR [dotnet/wpf#5996](https://github.com/dotnet/wpf/pull/5996) for WPF is already merged.

**Comment by vlada-shubina** [comment]
@dipeshmsft the translations are bundled in the package. I have the same situation in my machine, likely VS also installs .NET SDK 3.1.

For all templates, but WPF Application, 3.1 template conflicts with latest (7.0) because they have different identity, but same precedence. Moreover it leads to the following errors in case .NET SDK 3.1 and later SDK are installed together:

```
> dotnet new wpflib --framework netcoreapp3.0 -o testwpf                                                                                                                                                     
Unable to resolve the template, the following installed templates are conflicting:
Identity                                 Template Name      Short Name  Language  Precedence  Author     Package
---------------------------------------  -----------------  ----------  --------  ----------  ---------  -------
Microsoft.Common.WPF.Library.CSharp.3.1  WPF Class library  wpflib      C#        3000        Microsoft
Microsoft.Common.WPF.Library.CSharp.5.0  WPF Class Library  wpflib      C#        3000        Microsoft

Uninstall the template packages containing the templates to keep only one template from the list or add the template options which differentiate the template to run.

For details on the exit code, refer to https://aka.ms/templating-exit-codes#103

> dotnet new wpflib --framework netcoreapp3.1 -o testwpf                                                                                                                                                   
Unable to resolve the template, the following installed templates are conflicting:
Identity                                 Template Name      Short Name  Language  Precedence  Author     Package
---------------------------------------  -----------------  ----------  --------  ----------  ---------  -------
Microsoft.Common.WPF.Library.CSharp.3.1  WPF Class library  wpflib      C#        3000        Microsoft
Microsoft.Common.WPF.Library.CSharp.5.0  WPF Class Library  wpflib      C#        3000        Microsoft

Uninstall the template packages containing the templates to keep only one template from the list or add the template options which differentiate the template to run.

For details on the exit code, refer to https://aka.ms/templating-exit-codes#103

```

Please change the precedence of the latest version to be higher than 3.1 package precedence `3000`.

**Comment by WenJunJi01** [comment]
Tried to verify it following below steps on Turkish, this issue not happens
1. Clone repo git clone https://github.com/dotnet/wpf/tree/net7-template-localization -b net7-template-localization
2. Install .net 7.0.100 SDK
3. Install all templates in contents directory
dotnet new -i <path to the repo>\wpf\packaging\Microsoft.Dotnet.Wpf.ProjectTemplates\content\WpfApplication-CSharp
4. Install VS Version 17.4.0 Preview 4.0 [33018.223.d17.4] with 3.1 runtime checked.
5. Check in dotnet new --list
![image](https://user-images.githubusercontent.com/87680983/196870538-fa686a14-3c00-472e-ae10-f38b71d5e986.png)

dotnet --info
![image](https://user-images.githubusercontent.com/87680983/196870636-7f886dbf-3ad0-4ce4-823c-1f35cbcf7faa.png)

**Comment by dipeshmsft** [comment]
Closing the issue as the corresponding PR has been merged.
