### ISSUE TITLE
Application Exit not called on windows restart

### ISSUE THREAD

**Issue by Daniellled** [dotnet/wpf#7211]
* .NET Core Version: 6.0
* Windows version: 19044.2130
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

 
 
 **Problem description:**
When a WPF application is running and the I restart Windows. The Application Exit method defined in App.xaml is not called. Additionally when I override the OnExit method it is also not called.

I have (I think) turned off Fast Startup and the issue still occurs.

![image](https://user-images.githubusercontent.com/83433189/196212217-fb690c1e-630e-4b12-8c9f-e2bb4bce9f8d.png)
 
 **Actual behavior:** 
OnExit override and Application Exit method are not called when restarting Windows with application running and visible.
 
 **Expected behavior:**
 OnExit override and Application Exit methods are invoked when Windows is restarted.
 
 **Minimal repro:**
 
 App.xaml
```
 <Application x:Class="ShutdownTest.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:ShutdownTest"
             StartupUri="MainWindow.xaml"
             Exit="Application_Exit"
             SessionEnding="Application_SessionEnding"
             ShutdownMode="OnMainWindowClose">
    <Application.Resources>
         
    </Application.Resources>
</Application>
```
 
 App.xaml.cs
```
    public partial class App : Application
    {
        protected override void OnExit(ExitEventArgs e)
        {
            using(var sw = new StreamWriter(@"c:\logs\test.txt"))
            {
                sw.WriteLine($"{nameof(OnExit)} - called");
            }
            base.OnExit(e);
        }

        private void Application_Exit(object sender, ExitEventArgs e)
        {
            using (var sw = new StreamWriter(@"c:\logs\test2.txt"))
            {
                sw.WriteLine($"{nameof(Application_Exit)} - called");
            }
        }

        private void Application_SessionEnding(object sender, SessionEndingCancelEventArgs e)
        {
            using (var sw = new StreamWriter(@"c:\logs\test3.txt"))
            {
                sw.WriteLine($"{nameof(Application_SessionEnding)} - called");
            }
        }
    }
```

**Comment by Symbai** [comment]
https://stackoverflow.com/questions/47141816/application-exit-event-not-called-on-logoff-or-shutdown

**Comment by Daniellled** [comment]
> https://stackoverflow.com/questions/47141816/application-exit-event-not-called-on-logoff-or-shutdown

I am using *ShutdownMode="OnMainWindowClose"* so when the session ends shouldn't the MainWindow be closed and thus Exit be called?

**Comment by miloush** [comment]
I confirm I am struggling to get the `SessionEnding` event called, although it does work when I post the message to the relevant window. It appears as if Windows does not send the WM_QUERYENDSESSION message to it (TBC).

That said, I think I found a different bug, `Application.WmQueryEndSession` just throw hands in the air and shuts down the app. However, that is not appropriate response to WM_QUERYENDSESSION as the session ending might be cancelled. It should wait for WM_ENDSESSION and check the session is actually ending before shutting down, see [WM_QUERYENDSESSSION](https://learn.microsoft.com/en-us/windows/win32/shutdown/wm-queryendsession) or [Raymond](https://devblogs.microsoft.com/oldnewthing/20170329-00/?p=95855).

**Comment by miloush** [comment]
I think I am onto something. @Danielled does making your app 64-bit fix it by any chance?

**Comment by miloush** [comment]
Also are you trying this under a debugger? The combination that does not work for me is 64-bit Visual Studio with x86 PlatformTarget. If I run it without debugging it seems to work both x86 and x64. If I run x86 under 32-bit debugger, it seems to work too. Do you have a 32-bit Visual Studio to see if it fixes it for x86?

**Comment by Daniellled** [comment]
The project is AnyCPU (64-bit preferred).

These are debug builds that I am copying to a VM.

**Comment by miloush** [comment]
If you have 64-bit preferred then yes. But I can reproduce it under debugger only anyway, and I suspect the debugger process is just shutting it down in panic. Sounds like I don't really have repro then. Just to rule out the obvious - it's a normal desktop app, correct? You don't start as a console or service...

**Comment by miloush** [comment]
Also can you clarify whether the behavior you are seeing is that the system actually restarts and you don't called, and there is no exceptions in the Event Viewer? And you check that by not seeing the files after restart, correct?

**Comment by Daniellled** [comment]
> If you have 64-bit preferred then yes. But I can reproduce it under debugger only anyway, and I suspect the debugger process is just shutting it down in panic. Sounds like I don't really have repro then. Just to rule out the obvious - it's a normal desktop app, correct? You don't start as a console or service...

I just went into Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.1 and created a new WPF project and added the modifications posted in the issue.

So I would say it is a normal desktop app.

**Comment by Daniellled** [comment]
Interestingly enough if I modify the App.xaml code to not call *SessionEnding="Application_SessionEnding"* zero files are created.

```
<Application x:Class="ShutdownTest.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:ShutdownTest"
             StartupUri="MainWindow.xaml"
             Exit="Application_Exit"
             
             ShutdownMode="OnMainWindowClose">
    <Application.Resources>
         
    </Application.Resources>
</Application>
```

It is almost like the behavior is as follows.

If a *SessionEnding* method is defined the *SessionEnding* method is fully invoked. And the *OnExit* override is partially invoked but cut short by the OS. While the *Exit="Application_Exit"* method defined in *App.xaml* is never invoked.

If a *SessionEnding* method is not defined the *OnExit* override is not as well as the *Exit="Application_Exit"* method defined in *App.xaml*.

**Comment by miloush** [comment]
Right, so this is actually kind of behaving as expected. Once you return from SessionEnding indicating you do not intend to block the shutdown, the game is over. You should treat the SessionEnding as an Exit event and do everything you need before you return form it.

On the WPF side, Application.CriticalShutdown invokes the ShutdownCallback asynchronously. It could theoretically keep reference to the operation and block WM_ENDSESSION until it is done.

**Comment by miloush** [comment]
@Daniellled would you be able to test whether https://github.com/dotnet/wpf/commit/fb5b20ceb4030b377d0cd9b6985bb19c8f81b6eb resolves your issue?

**Comment by miloush** [comment]
If you build WPF with the changes in the commit, you should not need to change anything in your app and it should get the exit handler called. OS gives you I think about 5 seconds then you wilk be shut down.

If you are just looking for a fix for your app, my suggestion is to call whatever you need to do on exit during SessionEnd.
