### ISSUE TITLE
Problem recreating app settings after deleting it.

### ISSUE THREAD

**Issue by Perpete** [dotnet/wpf#7221]
Hello,

.NET 6 project in VB with WPF or Winform and visual studio 17.3.6.

Here is the message displayed when recreating application settings after deleting the Settings.settings file in solution explorer containing at least one setting.

![Setting](https://user-images.githubusercontent.com/66659162/197141451-a0d802d1-15dc-4e3f-a200-36bf9cfe996a.png)

Messages :
The designer loader didn't provide any root components and didn't say why.

New app.config file values have been added automatically.

Here are the steps to reproduce the problem:
- Create application settings with at least one parameter.
- Delete the Settings.setting file in Solution Explorer.
- Create application settings again.
- The message should appear.

Apparently, despite deleting the file containing the settings, these would not be entirely removed from the project.
To avoid the message you must:
- Remove all settings from the file.
- Save the file.
- Delete the file in solution explorer.

I tested the resource file (Resources.resx), there is no such problem.

**Comment by Perpete** [comment]
Hello,

I just noticed that the settings remain in the "app.config" file despite the deletion of the Settings.settings file.

![Setting2](https://user-images.githubusercontent.com/66659162/197147845-824da30b-b751-4653-b1cf-2389b0ff2f39.png)

**Comment by dipeshmsft** [comment]
@Perpete , since this is not a WPF issue and as @miloush mentioned that this repros with other projects as well, we are closing this issue and suggest you to raise a feedback ticket with VS : https://developercommunity.visualstudio.com/home
