### ISSUE TITLE
Enable APICompat in WPF Builds

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#724]
Enable API Compat against net48 ref assemblies on WPF Builds. 

This will prevent future breaks like #515

**Comment by rladuca** [comment]
Working branch for this is https://github.com/dotnet/wpf/tree/dev/roladuca/apicompat

To do this we need to access the .NET Framework 4.8 reference assemblies and we have to enable the ApiCompat targets from Arcade as well as match built binaries against the 4.8 reference assembly.

We can then fully baseline the compat runs and filter out/fix any issues for future runs.

Also, enable compat checks from hand-crafted ref assemblies (C++/CLI) to their associated lib assemblies.  These checks are not needed for C# assemblies as we generate the ref assembly from compilation.

**Comment by rladuca** [comment]
Notes on baselining can be found [here](https://github.com/rladuca/ApiCompatNotes/blob/master/ApiCompat%20Notes.txt)

**Comment by rladuca** [comment]
This depends on a fix from #807 to pick up the spare System.Xaml compat errors.  This will in turn create more errors, but these are similar to other errors that are being baselined.

At the time of writing this, the remaining errors in the notes are almost certainly part of the baseline, but we're awaiting 100% clarification.
