### ISSUE TITLE
wpf Listview control ScrollIntoView() bug

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#7276]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/wpf-Listview-control-ScrollIntoView-bu/10189680)._

---
Continuous addition of the same value to the listview causes scrolling to not last

code)
WPF ListView Name: listBox_log
....
....
var index = listBox_log.SelectedIndex;
var item = listBox_log.Items.GetItemAt(index);
listBox_log.ScrollIntoView(item);

---
#### Feedback Bot on 11/3/2022, 06:55 PM: 

(private comment, text removed)
#### Dolly Wang [MSFT] on 11/7/2022, 02:42 AM: 

(private comment, text removed)
#### devkang on 11/9/2022, 05:57 PM: 

(private comment, text removed)
#### devkang on 11/9/2022, 05:58 PM: 

(private comment, text removed)
#### Feedback Bot on 11/9/2022, 07:02 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by miloush** [comment]
This is by design. If you put the same value several times in a collection, then they are all equal to each other. ScrollIntoView has no way to figure out which of them you meant.

**Comment by lindexi** [comment]
@miloush How about add the new API: `ScrollIntoIndex` ?

**Comment by miloush** [comment]
Is there a real use case for that though? How are you going to get the index value? Even if that helped in this one case, there is plenty of other situations where you run into issues by having duplicate objects in a collection.
