### ISSUE TITLE
Narrator narrates TabItem twice when tab changed with navigation keys (arrow keys) 

### ISSUE THREAD

**Issue by ronak-k-p** [dotnet/wpf#7294]
* .NET Framework Version: 4.8 (Any)
* Windows version: Windows 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 **Problem description:**
 Narrator narrates TabItem header twice when tab changed with navigation keys (arrow keys) 
 "**Tabitem2HeaderText** 2 of 2 selected " narrates twice.

 **Minimal repro:**
 [1] Create blank WPF app
 [2] Add TabControl on MainWindow & Add two TabItems into TabControl. (Set their headers "TabItem1" & "TabItem2")
 [3] Run application  & Press Tab key to set focus on TabItem1
 [4] Run Narrator from windows & Switch back to our sample application.
 [5] When Tab key Focus on TabItem move next TabItem press Left/Right arrow key.
 [6] Notice Narrator narrates twice for selected TabItem.

**Comment by lindexi** [comment]
@ronak-k-p Could you provide us a sample repro application ?

I can't reproduce your problem.

**Comment by ronak-k-p** [comment]
[WpfApp1.zip](https://github.com/dotnet/wpf/files/10038342/WpfApp1.zip)
@lindexi

**Comment by lindexi** [comment]
It seems that this behavior is what I expect.

![](https://user-images.githubusercontent.com/16054566/202934806-bad539d6-a024-488e-ad16-6056b8c37a29.gif)

**Comment by ronak-k-p** [comment]
@lindexi 
Please open **Narrator** before opening sample app.

![image](https://user-images.githubusercontent.com/87496698/202972205-d3435c93-8198-4ee4-ab94-05140f05a73a.png)


> Narrator is a screen reader in Microsoft Windows. Developed by Professor Paul Blenkhorn in 2000, the utility made the Windows operating system more accessible for blind and visually impaired users.


When you open narrator it reads out every action performed or focused with keyboard or mouse.
When we do switch TabItem with arrow key narrators read out action two times.

**Comment by anjali-wpf** [comment]
@ronak-k-p I investigated this issue, I observed the behavior even through narrator buddy, it seems to be a narrator issue and not specific to wpf. Same code is getting executed for keyboard navigation and mouse navigation.
