### ISSUE TITLE
ComboBox.Text can't select items in some cases

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/wpf#7309]
* .NET Core Version: All. Also
* Windows version: 7 and 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 **Problem description:**
 When `ComboBox.IsEditable = False`, setting the `ComboBox.Text` to a text that matches an item in the ComboBox should select this item. This doesn't happen in some cases, like setting the Text property to "Test" while the ComboBox contains the items `"test", "Test", "abc"` or `"test1", "Test", "abc"` or `"Test1", "Test", "abc"`.
It seems that matching `Test` to `test`, `test1`, "Test1" causes some error that apports the search (which doesn't happen in WinForms by the way). That proves this submission, is that changing the order (ComboBox contains the items `"Test", "test", "abc"`) will make the combobox select the item Test correctly!

 **Minimal repro:**
```xaml
    <StackPanel>
        <ComboBox x:Name="ComboBox1" IsEditable="False">
            <ComboBoxItem>test</ComboBoxItem>
            <ComboBoxItem>Test</ComboBoxItem>
            <ComboBoxItem>abc</ComboBoxItem>
        </ComboBox>
        <Button Click="Button_Click">Test</Button>
    </StackPanel>
```

```vb
    Private Sub Button_Click(sender As Object, e As RoutedEventArgs)
        ComboBox1.Text = "Test"
    End Sub
```

Run the app and click the button. Nothing will be selected in the comboBox.
Expected behavior is to select the `Test` item.

**Comment by anjalisheel-wpf** [comment]
@VBAndCs Could you please help me with the use case where you want to use this? 

Presently we have a workaround which can fix this issue. In this we are sorting the values of the combo box, also adding a parameter for making combo box items case sensitive, by using this, it will fix the issue -

In MainWindow.xaml you can add - 

<ComboBox x:Name="ComboBox1" IsEditable="False" IsTextSearchCaseSensitive="True"  >


And in MainWindow.xaml.cs you can add -

public MainWindow()
        {
            InitializeComponent();

            SortedSet<string> sortedComboBoxItems = new SortedSet<string>();

            ItemCollection comboitems = ComboBox1.Items;
            foreach (ComboBoxItem item in comboitems)
            {
                sortedComboBoxItems.Add(item.Content.ToString());
            }

            ComboBox1.Items.Clear();
            ComboBox1.ItemsSource = sortedComboBoxItems;
        }

**Comment by VBAndCs** [comment]
@anjalisheel-wpf 
This is not a workaround, since you should not change the item order nor casing. This is the way combobox works on winforms and how it should work in wpf not to break any ported code from winforms.

**Comment by anjalisheel-wpf** [comment]
@VBAndCs Could you please help me the use case for the same?

**Comment by miloush** [comment]
> This is the way combobox works on winforms and how it should work in wpf not to break any ported code from winforms.

No. Winforms and WPF are fundamentally different frameworks and there should be no such expectations.

> Expected behavior is to select the Test item.

The documentation (https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.combobox.text) says otherwise:

> When [IsEditable](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.combobox.iseditable?view=windowsdesktop-7.0) is false, setting this value has no effect.

Sounds like the current behavior is by design.. To select an item, find the item you want and use the `SelectedItem` property.

**Comment by VBAndCs** [comment]
@miloush 
If you think this is by design, so it has a bug to, as I said:
> When ComboBox.IsEditable = False, setting the ComboBox.Text to a text that matches an item in the ComboBox should select this item

I only spotted the case where this `nothing happen` hapens!
So, either combox do nothing all the time, or select the item all the time. The current behavior is against both the docs you quoted and the WinForms long stable design.

**Comment by miloush** [comment]
@VBAndCs I followed your repro steps and saw, as documented, that nothing happens. Maybe I misunderstood, what are the steps to "select the item all the time"?
