### ISSUE TITLE
Only the first item is displayed in the DataGrid group

### ISSUE THREAD

**Issue by LadislavLang** [dotnet/wpf#7315]
* .NET Core Version: 7 (It's working in dotnet6 !)
* Windows version: 11
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**
Set up a DataGrid where the ItemSource is a ListCollectionView with configured GroupDescription and use it with a simple GroupStyle:

             <DataGrid.GroupStyle>
                <GroupStyle>
                    <GroupStyle.Panel>
                        <ItemsPanelTemplate>
                            <DataGridRowsPresenter/>
                        </ItemsPanelTemplate>
                    </GroupStyle.Panel>
                </GroupStyle>
            </DataGrid.GroupStyle>
            
 **Expected/Actual behavior:** 
It should disply all items (grouped), but only the first item is displayed in each group, 
see ![bug](https://user-images.githubusercontent.com/26323488/203943832-ba0a5f81-fe24-40bc-98c6-e1387fb76607.png)

 **Minimal repro:**
[DotNet7WPFGroupingBug.zip](https://github.com/dotnet/wpf/files/10090338/DotNet7WPFGroupingBug.zip)

**Comment by LadislavLang** [comment]
This seems to fix the bug:

            <DataGrid.GroupStyle>
                <GroupStyle>
                    
                </GroupStyle>
            </DataGrid.GroupStyle>

**Comment by to87al** [comment]
I can confirm the same issue. Hoping we have a fix soon.

**Comment by singhashish-wpf** [comment]
The changes in PR https://github.com/dotnet/wpf/pull/4220 are disturbing the HierarchicalVirtualizationConstraints calculation, which is further used in calculation of the sizes of the virtualizing items and availableSize, DesiredSize, Viewport and extendedViewport calculations.
The result of all this is showing just the first item rather than all the items in the group
