### ISSUE TITLE
InputBindings (KeyBinding) behaviour change in net7.0-windows

### ISSUE THREAD

**Issue by danielkaczmarek** [dotnet/wpf#7322]
* .NET Core Version: 7.0
* Windows version: 10
 **Problem description:**
 We use Alt+Right/Left keys alot to navigate between pages in our application, the commands we use are run by InputBindings (KeyBinding).  After updating to .net7 it does not work anymore.
 **Actual behavior:** 
Alt + Right does not call the command
 **Expected behavior:**
  Alt + Right should call the command.
 **Minimal repro:**
In the demo attached in Browse.xaml code behind there are two commands with breakpoint, you will notice that when you run the app and press Alt+Right or Left the breakpoints are never hit while the focus is inside the ListBox. If you stop the application and change the Target Framework from net7.0-windows to net6.0-windows those breakpoints are always called.

[WpfApp3.zip](https://github.com/dotnet/wpf/files/10105445/WpfApp3.zip)

**Comment by lindexi** [comment]
@danielkaczmarek Is your description wrong?

Actual behavior: It does not call it.

Expected behavior: Alt + Right should call the command.

**Comment by lindexi** [comment]
Reference: https://github.com/dotnet/wpf/pull/6812

Cc @anjalisheel-wpf

**Comment by danielkaczmarek** [comment]
@lindexi Yes, the descriptions for Actual behaviour and Expected behaviour descriptions where the wrong way around.
