### ISSUE TITLE
WPF app crashed because the .NET runtime was upgraded by Microsoft Update.

### ISSUE THREAD

**Issue by Bo-Liu-BL** [dotnet/wpf#7332]
### Description

When our app is running(the .NET runtime version is 6.0.10), the .NET runtime was upgraded to 6.0.11 by the Microsoft Update, our product would crash.

### Reproduction Steps

The issue can be reproduced with the following steps:

1. Turn on the following setting:
   Windows Update -> Advanced options
   Enable the following item:
>   Receive updates for other Microsoft products.
2. Create a simple  C#/WPF project with VS2019 or 2022.
   Since the latest .NET runtime is 6.0.11, so please ensure the used .NET runtime is 6.0.10 or lower version.
3. Build and run it.
4. During the app running, run "check for update" from the system Settings.
   You will see the .NET runtime is upgraded to 6.0.11.
5. After the upgrade completes, check the app state.
6. If it doesn't get crashed, close the app manually. ==> You will see the app crashed.

### Expected behavior

The app shouldn't crash either during running or when exiting.

### Actual behavior

The app crashes during running or when exiting.

Per debugging the dump file in VS IDE, the exception message was:
`System.DllNotFoundException: 'Unable to load DLL 'vcruntime140_cor3.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)'`

### Regression?

No

### Known Workarounds

No workaround.

### Configuration

I tested .NET runtime 6.0.9 and 6.0.10 with the simple C#/WPF application in VS2019 and VS2022.

**Comment by lindexi** [comment]
I had this problem a long time ago. I solved this problem by self-contained.

**Comment by Bo-Liu-BL** [comment]
> I had this problem a long time ago. I solved this problem by self-contained.

Thank you, Lindexi.
We couldn't do like that in our product for the sake of the future upgrade of the .NET runtime.
For example, if .NET runtime released important updates such as security related, if we use the self-contained way, we need to release the new version of our product. 
If we don't use the self-contained way which is used by our product currently, users can upgrade the .NET runtime in their environments then continue to use our existing release product.

**Comment by springy76** [comment]
Each time VS-Installer updates the .NET SDK then all already running .NET apps (for example LINQPad) crash at the latest when closing them. (and the VS updater only updates .NET every 2 or 3 times, never telling before whether it will do that).

**Comment by miloush** [comment]
While I understand how this is not a good experience, I do not think this issue is formulated in an actionable way. It sounds like if you go and delete _vcruntime140_cor3.dll_ while the application is running, it will crash on exit. I would think that is expected, yet the cause is the same as in the scenario in the issue.

Either way as it has been pointed above this does not seem to be WPF specific issue.

**Comment by moellerm** [comment]
This is not a WPF specific issue, it happens with simple console dotnet applications as well. The issue is tracked here https://github.com/dotnet/runtime/issues/60144

**Comment by Bo-Liu-BL** [comment]
I will close this issue as https://github.com/dotnet/runtime/issues/60144 is tracking it. Thanks!
