### ISSUE TITLE
The Clipboard.GetDataObject() method doesn't work as expected

### ISSUE THREAD

**Issue by pavelovcharov** [dotnet/wpf#735]
* .NET Core Version: 3.0.100-preview5-011568
* Windows version: 1809 (177663.79)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 
 **Problem description:**
The following test fails when running under .NET Core 3 preview5:
```
        [Test]
        public void Test() {
            DataObject data = new DataObject();
            data.SetData(typeof(string), "SampleText");
            Clipboard.SetDataObject(data);
            string text = ((DataObject)Clipboard.GetDataObject()).GetText();
            Assert.AreEqual("SampleText", text);
        }
```
As far as I remember, the test didn't failed in previous .Net Core 3 previews. 
 
 **Actual behavior:** 
The test fails with the following message:
```
 Message: System.InvalidCastException : Unable to cast COM object of type 'System.__ComObject' to class type 'System.Windows.DataObject'. Instances of types that represent COM components cannot be cast to types that do not represent COM components; however they can be cast to interfaces as long as the underlying COM component supports QueryInterface calls for the IID of the interface.
```
  
 **Expected behavior:**
 The test should pass.

 **Minimal repro:**
git clone https://github.com/pavelovcharov/netcore3_clipboardsetdata
cd .\netcore3_clipboardsetdata\
dotnet test

**Comment by rladuca** [comment]
@pavelovcharov I'm investigating this in the context of an internal bug that was fixed in .NET Core some time ago relating to Marshaling and clipboard objects.  I'll circle back when I have a better understanding for you.

**Comment by rladuca** [comment]
@pavelovcharov I was able to chase this down to a missing port of a bug that was fixed for .NET Core 3 back in November.  Basically, this change didn't make it over to our new repos (both internal and this one) when we switched build systems and synced code against our .NET Framework code.

I'm working on getting this change back into our codebase.

**Comment by rladuca** [comment]
I was able to get the change in and it moves us beyond the original issue.  However, there are recent (in the last few days) issues with Clipboard APIs and marshaling coming out of OLE calls.  At current, we believe this is an issue in the CLR and not WPF.  So this will still block you.  You can follow the progress here: #775
