### ISSUE TITLE
GC seems really unreliable

### ISSUE THREAD

**Issue by IAmTheCShark** [dotnet/wpf#7368]
Problem can be observed in .net 7
Create a small WPF app with a Button and use the following code. Place a breakpoint in ~Foo. Hammer the Button. Breakpoint is never reached, unless you explicitely call GC.Collect.

```
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }




        private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
        {
           new Foo ();
        }
    }

    public class Foo 
    {
        public Foo ()
        {
           
        }

        ~Foo ()
        {
            // BREAKPOINT HERE
        }
    }
```

I bellieve this behaviour is what makes this
https://github.com/dotnet/wpf/blob/86e3b7b6b3db5176d7061661712c18d973837326/src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/CleanupHelper.cs#L59

unreliable. And causes memory leaks.

**Comment by lindexi** [comment]
@IAmTheCShark Sorry, I think this is an unnecessary worry. Because GC works a little differently than you might expect.

**Comment by IAmTheCShark** [comment]
@lindexi yeah i realized, the actual problem is a bit more clomplex i think i oversimplified.
