### ISSUE TITLE
Backport #2377 to .NET 4.8?

### ISSUE THREAD

**Issue by batzen** [dotnet/wpf#7372]
Would it be possible to backport the changes made in #2377 to .NET 4.8?

We can't upgrade from .NET Framework to .NET yet due to technical limitations in the COM support in .NET (no regasm).
As the changes made in #2377 are non breaking, but solve an issue that can't be handled properly at the application level it would be nice if it could be backported to .NET 4.8.

**Comment by singhashish-wpf** [comment]
Any changes in .NET Framework are done through the DTS process. The CSS representative of the corresponding enterprise needs to file a DTS bug for this change to be in .NET Framework along with the business impact and justification.
