### ISSUE TITLE
Is it possible to create a WPF application with .NET 7 that starts in the sys tray?

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/wpf#7409]
I would like to create an application that starts in the sys tray, and I find this question in StackOverflow: [](https://stackoverflow.com/questions/1472633/wpf-application-that-only-has-a-tray-icon)
The answer tells that it is not possible in WPF, but it was requested many times. But this answer is from 2009, so I was wondering if actually it is possibe to do it or not.

Thanks.

**Comment by singhashish-wpf** [comment]
@ComptonAlvaro Can we close this as the solution mentioned by @am11 works?

@am11  Thanks for the detailed procedure !

**Comment by miloush** [comment]
There is also http://www.hardcodet.net/wpf-notifyicon which I used in the past and which does not require WinForms.

**Comment by ComptonAlvaro** [comment]
@singhashish-wpf  Yes, it can be closed, because the solution given by @am11 works perfectly.

@miloush Thanks for this solution, it is good to have an alternative that doesn't need WinForms.



Thanks so much for all.
