### ISSUE TITLE
\PenImc SxS COM registration failure message should be localized

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#744]
Copied from VSO ID: 670084

Steps to reproduce:

/src/WPF/src/PresentationCore/CSharp/MS/Win32/UnsafeNativeMethodsPenimc.cs:106

            if (activationContextCookie == IntPtr.Zero)
            {
                throw new InvalidOperationException("SxS COM registration of PenIMC3_v0400.dll failed.");
            }
        }

**Comment by vatsan-madhavan** [comment]
@ryalanms we'd want this looked at and fixed first thing in P8.

**Comment by grubioe** [comment]
@ryalanms - any updates here?  Thanks

**Comment by ryalanms** [comment]
This is already fixed and translated in the xlfs: 

```cs
          // RegisterDllForSxSCOM returns a non-zero ActivationContextCookie if SxS registration
            // succeeds, or IntPtr.Zero if SxS registration fails.
            if (IntPtr.Zero == RegisterDllForSxSCOM())
            {
                throw new InvalidOperationException(SR.Get(SRID.PenImcSxSRegistrationFailed, ExternDll.Penimc));
            }
```
For example: 

```xml
      <trans-unit id="PenImcSxSRegistrationFailed">
        <source>SxS COM registration of {0} failed.</source>
        <target state="translated">Fehler bei der SxS COM-Registrierung von "{0}".</target>
        <note />
      </trans-unit>
```
