### ISSUE TITLE
Narrator provides wrong count when tabitems collapsed

### ISSUE THREAD

**Issue by shcummin** [dotnet/wpf#7450]
* .Net 4.7.2
* Windows version: (`winver`): Win11
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Pending
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No
 
 **Problem description:**
- Narrator counts all tabitems, even ones that have Collapsed visibility
 
 **Actual behavior:** 
 
 - in this xaml, narrator will say "foo tab item, 1 of 3"
 
 **Expected behavior:**
- Expect a count of 2 as 1 tabitem is collapsed.
 
 **Minimal repro:**
 
```
<Window x:Class="TabApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:TabApp1"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <TabControl TabStripPlacement="Left"
                    Height="470"
                    Margin="0,5,0,0"
                    x:Name="MainTabControl"
>
            <TabItem Header="foo">
            </TabItem>
            <TabItem Header="bar">
            </TabItem>
            <TabItem Header="baz" Visibility="Collapsed">
            </TabItem>
        </TabControl>
    </Grid>
</Window>
```

**Comment by anjalisheel-wpf** [comment]
@shcummin This is working as expected. Narrator announces whatever is there in the design view. Here we have 3 tab items, irrespective of the 'Visibility' of those items, even if it is 'Collapsed', then also the total count of tab items will be 3, that is not going to affect the total count, that's why it is the correct behavior, as per the design.

**Comment by shcummin** [comment]
Is this the design of Narrator, WPF, or both? We have a bug from an accessibility team, based on the idea that it is misleading.

**Comment by anjalisheel-wpf** [comment]
@shcummin It is according to the design of narrator.
