### ISSUE TITLE
Accessibility Narrator reads the class name of the selected Item in the ComboBox instead of the DisplayMemberPath value

### ISSUE THREAD

**Issue by EbramTawfik** [dotnet/wpf#7460]
.Net 4.7.2
Windows version: (winver): Win11
Does the bug reproduce also in WPF for .NET Framework 4.8?: Pending
Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

 
 
 **Problem description:**
 Accessibility narrator reads the class name of the selected Item in the ComboBox instead of the DisplayMemberPath value
 **Actual behavior:** 
 Accessibility Narrator reads the class name of the selected Item in the ComboBox instead of the DisplayMemberPath value
 **Expected behavior:**
 Accessibility Narrator should read the DisplayMemberPath value
 **Minimal repro:**
```
public class Student
{
    public int Id { get; set; }
    public string? Name { get; set; }
}
public class MainViewModel : ViewModelBase
{
    private ObservableCollection<Student> _students;
    private Student _selectedStudents;
    public ObservableCollection<Student> Students
    {
        get
        {
            if (_students == null)
            {
                _students = new ObservableCollection<Student>();
                _students.Add(new Student() { Id = 1, Name = "A" });
                _students.Add(new Student() { Id = 2, Name = "B" });
                _students.Add(new Student() { Id = 3, Name = "C" });
            }
            return _students;
        }
    }

    public Student SelectedStudents
    {
        get
        {
            return _selectedStudents;
        }
        set
        {
            _selectedStudents = value;
            RaisePropertyChanged(nameof(SelectedStudents));
        }
    }
}

```

XAML

`<ComboBox
        Height="30"
        AutomationProperties.Name="Students"
        DisplayMemberPath="Name"
        ItemsSource="{Binding Path=Students}" 
        SelectedItem="{Binding SelectedStudents}"/>`

**Comment by lindexi** [comment]
The UIA will show the data context class name by the call the ToString method. As the image shown

![](https://user-images.githubusercontent.com/16054566/213330783-38e0e412-4a5d-4c8d-b371-79201eebd268.png)

The demo code: https://github.com/lindexi/lindexi_gd/commit/1d2c77b54cacaca279db4bfff47918bfd3754466

But I think it work as I expected.

After I override the ToString in Student class, and the UIA will work well.

```
public class Student
{
    public int Id { get; set; }
    public string? Name { get; set; }

    public override string ToString() => $"{Id} {Name}";
}
```

![](https://user-images.githubusercontent.com/16054566/213331162-9bd77cf4-1abf-4198-9d44-e310eb8fbc2c.png)

And sorry my UIA app doesn't have English language

**Comment by lindexi** [comment]
Reference https://github.com/dotnet/wpf/issues/6861

But not the same issues.
