### ISSUE TITLE
Unable to load DLL 'wpfgfx_cor3.dll' or one of its dependencies during unit test (nunit)

### ISSUE THREAD

**Issue by nickkfwong** [dotnet/wpf#7461]
**Problem description:**
We have an WPF app targeted on .NET6 and built in my dev machine with .NET 7 SDK. (newly migrated from .NET 4.8)

The app is built and run without issue.
We have nunit-test that actually use UI controls and requires the WPF /desktop dlls.

When those tests are run inside Visual Studio (both through resharper or the build-in test runner), there is no problem at all.
When those tests are run in nunit-console.exe, it throws
`System.DllNotFoundException: Unable to load DLL 'wpfgfx_cor3.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)`

This exception is thrown at the time the Control is created.
The stack is as follow:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 System.Windows.Markup.XamlParseException: 'Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.' Line number '13' and line position '10'.
  System.DllNotFoundException: Unable to load DLL 'wpfgfx_cor3.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
...
 at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
...
at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.UIElementCollection.Add(UIElement element)
   at System.Windows.Controls.UIElementCollection.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
```

The test is run through below command:
`nunit3-console.exe <thetest.dll>`

I try to attach the debugger and break where this exception is thrown, I can see it is thrown at this line: [Link to MediaContextNotificationWindow.cs](https://github.com/dotnet/wpf/blob/dd6d6f8ee95cb2437155c61562dc553506370717/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContextNotificationWindow.cs#L94)

If I load up the "module" windows from Visual Studio, I can see the WPF dlls (PresentationCore.dll, PresentationFramework.dll) are loaded correctly from "C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.11"

I can also see "wpfgfx_cor3.dll" is located in the same directory, although when i put it on dotpeek it just says "not supported". (so i dont quite understand what it is)

This [previous-issue](https://github.com/dotnet/wpf/issues/2009) is very similar to what im facing. 
But Im running on a Windows 10 machine, so I believe KB2999226, KB2533623 is just not relevant to me. (and I can see they are for win7)
I also try install Windows Universal C Runtime from VS installer (although above says it is buildin with Win10), but the issue still persist.

I also looked at the [pre-requitesite page](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60#dependencies), It seems everything should have been fulfilled. (Or otherwise the app will not run at all)

One final thing I had tested is with the dotnet test command, and surprisingly it works without issue!
`dotnet test <thetest.dll>`

So, im not quite sure if that is something related to nunit's console runner? or the VS/dotnet test runner have done some magic behind?

Really appreciated if anyone who can give some direction on this issue.

Thanks.

Info about my dev machine:
* Windows version: Windows10 1909
* .NET SDK 7.0.100 (This is installed with Visual Studio 2022)
* Visual Studio 2022 17.4.1, with below components all checked:
   * .NET6/7 runtime
   * Win10 SDK
   * Installed workloads: .NET Desktop, Desktop with c++, .NET MAUI, ASP.NET web, Python

* NUnit:
   * NUnit.ConsoleRunner.3.16.2 (latest)

* Installed package in the test project:
   * Microsoft.NET.Test.Sdk v16.9.1
   * NUnit 3.13.3
   * NUnit3TestAdapter 4.2.1

**Minimal repro:**
- [Please see from here](https://github.com/dotnet/wpf/issues/7461#issuecomment-1423588832)

**Comment by singhashish-wpf** [comment]
Will it be possible to share a minimal repro project?

**Comment by nickkfwong** [comment]
> Will it be possible to share a minimal repro project?

Let me try to set it up after back from the cny holidays. (backing to office next week)

**Comment by nickkfwong** [comment]
Sorry to get back late - I am able to reproduce the same in a very simple setup.

Here is the sample proj:
[wpf_nunit.zip](https://github.com/dotnet/wpf/files/10693197/wpf_nunit.zip)

I have tried the latest NET.Test.SDK (17.4.1) and NUNit3TestAdapter (4.3.1), the issue still persist.

To test this out:
This will fail:
`packages\nunit.consolerunner\3.16.2\tools\nunit3-console.exe MyUserControlsTest\bin\Debug\net6.0-windows\MyUserControlsTest.dll`

This will succeed:
`dotnet test`

But given that dotnet test relies on just NET.Test.SDK & NUnit3TestAdapter (I think?), and it is successful, now I started to doubt if the issue maybe something related to NunitConsoleRunner rather than the framework? (...not sure I should raise to the Nunit repo instead)

More on my current dev env:
```
dotnet --list-sdks
7.0.100 [C:\Program Files\dotnet\sdk]

dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by nickkfwong** [comment]
From discussion from [nunit's repo](https://github.com/nunit/nunit-console/issues/1319), it is pointed out that it is something related to the runtime config of the agent itself.

Yet Im still not quite sure how the runtime config should be managed nicely in case of desktop app.
(eg. Do we expect we need to copy that package and manually overriding the config? Or should a desktop version be packaged just for the modified runtime config?)

I will close the issue shortly if there is no further input from here.
Thanks all for the time.
