### ISSUE TITLE
Is this a bug in radiobutton?

### ISSUE THREAD

**Issue by highspeeder** [dotnet/wpf#7462]
I was developing windows app with wpf, Soon I ran into a problem.

In my app I had 2 radio buttons and they were bound twoway to 2 bool properties in my ViewModel.

Set one of the two properties to an initial value of true,

When I repeatedly opened and closed the window of the view that had the radiobutton, I could see that both radiobuttons were sometimes unchecked at the same time.

Even if you click the radio button in that state, it is not checked.

So I started searching on the internet.

Then I found a solution, and what the person who told me this solution claims is a bug in microsoft.

[[https://stackoverflow.com/questions/50980687/wpf-radio-button-does-not-update-after-several-binding](https://stackoverflow.com/questions/50980687/wpf-radio-button-does-not-update-after-several-binding)

> I finally found the answer:
> 
> If you have tried to bind the RadioButton’s IsChecked property in WPF to an object, you have most
> likely experienced the following problem: In OneWay bindings it works great. But if you have more
> than one RadioButtons binded TwoWay and you click on an unchecked one, you were expecting that the object to which the previously checked RadioButton was binded to receive the value of False. But you were wrong in your expectations. That’s because for some reasons Microsoft does not obey bindings and does not pass the False value to the DependencyProperty and instead of that they just assign the value False directly to the property, which ruins the binding.
> 
> There are many proposed solutions to this around the internet, problem with all those is that they 
> do not work with dynamically generated controls. So since I had to find a way to make this working with dynamic controls, decided to make a wrapper of the real RadioButton which will correctly Bind in two ways. Here is the code for the wrapper:

```
using System;
using System.IO;
using System.Printing;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;
using Microsoft.Win32;

namespace Controls
{
    public class RadioButtonExtended : RadioButton
    {
        static bool m_bIsChanging = false;

        public RadioButtonExtended()
        {
            this.Checked += new RoutedEventHandler(RadioButtonExtended_Checked);
            this.Unchecked += new RoutedEventHandler(RadioButtonExtended_Unchecked);
        }

        void RadioButtonExtended_Unchecked(object sender, RoutedEventArgs e)
        {
            if (!m_bIsChanging)
                this.IsCheckedReal = false;
        }

        void RadioButtonExtended_Checked(object sender, RoutedEventArgs e)
        {
            if (!m_bIsChanging)
                this.IsCheckedReal = true;
        }

        public bool? IsCheckedReal
        {
            get { return (bool?)GetValue(IsCheckedRealProperty); }
            set
            {
                SetValue(IsCheckedRealProperty, value);
            }
        }

        // Using a DependencyProperty as the backing store for IsCheckedReal. This enables animation, styling, binding, etc...
        public static readonly DependencyProperty IsCheckedRealProperty =
        DependencyProperty.Register("IsCheckedReal", typeof(bool?), typeof(RadioButtonExtended),
        new FrameworkPropertyMetadata(false, FrameworkPropertyMetadataOptions.Journal |
        FrameworkPropertyMetadataOptions.BindsTwoWayByDefault,
        IsCheckedRealChanged));

        public static void IsCheckedRealChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            m_bIsChanging = true;
            ((RadioButtonExtended)d).IsChecked = (bool)e.NewValue;
            m_bIsChanging = false;
        }
    }
}
```

> So now all you have to do is to use the ExtendedRadioButton instead of the built-in one and bind to the IsCheckedReal property instead of the IsChecked one. Enjoy 🙂

I did as suggested by the solution proposer and it works fine.

Can you give me an answer if this is right or wrong? Or can it be fixed in the next release?

**Comment by miloush** [comment]
Please provide a repro project, I cannot reproduce the issue.
