### ISSUE TITLE
ElementHost in WinForms App doesn't render its assigned Child.

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/wpf#7478]
* .NET Core Version: 3.1, 5, 6, 7
* Windows version: 10, 11
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio: No.

 **Problem description:**

Porting a small WinForms demo app from .NET Framework to .NET (Core), which uses an ElementHost.
 
[ElementHostDemo.zip](https://github.com/dotnet/wpf/files/10542205/ElementHostDemo.zip)

 **Actual behavior:**

It doesn't render the XAML Control assigned to the Child property.
 
 **Expected behavior:**

It's supposed to render the XAML Control like in the Framework App:

![image](https://user-images.githubusercontent.com/9663150/215650859-c6730410-8a05-43eb-8546-5fc5e9c92950.png)

 **Minimal repro:**

See attached demo project.

Note: We (WinForms Team) are working to enable the `ElementHostDesigner` for the Out-of-Process WinForms Designer, when we notice the behavior. 

Maybe I am missing something here, since there aren't any additional exceptions.

**Comment by ThomasGoulet73** [comment]
Hey @KlausLoeffelmann, I took a quick look at your demo and it looks like there is a bug in the WinForms generated code in Form1.Designer.cs. It looks like in the .Net version of your demo, the field `xamlUserControl` is never initialized which means that it just sets the `Child` property of the ElementHost to null.

Also, there is also a bug in your demo. In the .Net version, the constructor of UserControl1 never calls the generated InitializeComponent method, which means that the Xaml is never loaded so the button is never created.

I hope this helps.

**Comment by KlausLoeffelmann** [comment]
`InitializeComponent` in the UserControl was missing - that was the actual problem.
I had tried several things before I zipped - but damn: I completely missed the InitializeComponent in the XAML UserControl. 

My bad!

🤦
