### ISSUE TITLE
Failed to build PresentationFramework: Missing type `ColumnDefinitionCollection` and `RowDefinitionCollection` in `Grid.cs`

### ISSUE THREAD

**Issue by LinkDoyle** [dotnet/wpf#748]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
3.0.100-preview5-011568

* Windows version: (`winver`)
Windows 10 Version 1903

* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No
No

 
 
 **Problem description:**
Failed to build PresentationFramework: the type `ColumnDefinitionCollection` and `RowDefinitionCollection` could not be found in `Grid.cs`.
See: [Grid.cs](https://github.com/dotnet/wpf/blob/ae1790531c3b993b56eba8b1f0dd395a3ed7de75/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Grid.cs#L309)

 **Actual behavior:** 
```
------ Build started: Project: PresentationFramework, Configuration: Debug Any CPU ------
System\Windows\Controls\Grid.cs(309,16,309,42): error CS0246: The type or namespace name 'ColumnDefinitionCollection' could not be found (are you missing a using directive or an assembly reference?)
System\Windows\Controls\Grid.cs(324,16,324,39): error CS0246: The type or namespace name 'RowDefinitionCollection' could not be found (are you missing a using directive or an assembly reference?)
System\Windows\Controls\Grid.cs(3347,22,3347,48): error CS0246: The type or namespace name 'ColumnDefinitionCollection' could not be found (are you missing a using directive or an assembly reference?)
System\Windows\Controls\Grid.cs(3348,22,3348,45): error CS0246: The type or namespace name 'RowDefinitionCollection' could not be found (are you missing a using directive or an assembly reference?)
System\Windows\Controls\Grid.cs(4151,21,4151,47): error CS0246: The type or namespace name 'ColumnDefinitionCollection' could not be found (are you missing a using directive or an assembly reference?)
System\Windows\Controls\Grid.cs(4152,21,4152,44): error CS0246: The type or namespace name 'RowDefinitionCollection' could not be found (are you missing a using directive or an assembly reference?)
Done building project "PresentationFramework.csproj" -- FAILED.
```

 **Expected behavior:**
 The type `ColumnDefinitionCollection` and `RowDefinitionCollection` could be found in the project PresentationFramework.

 **Minimal repro:**
 Build the project PresentationFramework.

**Comment by rladuca** [comment]
Hey, @LinkDoyle I just tried and was able to build locally.  Can you make sure your branch is fully synced to master and, if you're still experiencing this, can you attach the binlog from `artifacts\log\{Configuration}` (Where {Configuration} is Release or Debug (whatever you're building))?.

Thanks!

**Comment by vatsan-madhavan** [comment]
That's a flaky code-generator. It never fails in build-servers, but sometimes fails on local builds. 

If `Grid.cs` etc. has been generated (search for it by doing `dir /s/b Grid.cs` under `artifacts`), then delete them (or better yet, delete all of `artifacts`) and then rebuild. Things should work ok the next time around

**Comment by LinkDoyle** [comment]
Hi, @vatsan-madhavan @rladuca  After deleting all of `artifacts` and then rebuild, build succeeded. Thank you.
