### ISSUE TITLE
Printing from WPF is leaving random small spaces in the text when using Arial or Calibri fonts

### ISSUE THREAD

**Issue by campeters** [dotnet/wpf#7499]
### Description

When printing in WPF, the graphics engine is inserting small spaces within words.  For instance, the French word 'fonctions' is printed either as 'fonction s' or 'fo nctions' depending on where the word appears within the other text.

### Reproduction Steps

```c#
public void PrintItAll()
        {
            var printDialog = new PrintDialog();
            if (printDialog.ShowDialog() == true)
            {
                var fontFamily = new FontFamily("Arial");
                var printme = new TextBlock {
                    FontSize = 11, FontFamily = fontFamily, Width = 800, TextWrapping = TextWrapping.Wrap,
                    Text = "L'autre personne était incapable de prendre soin des enfants en raison d'une déficience des fonctions physiques ou mentales qui l'a obligée, durant une période d'au moins deux semaines, à garder le lit, à se déplacer en fauteuil roulant ou à recevoir des soins dans un hôpital ou un établissement semblable. Joignez un certificat du médecin traitant qui confirme la nature et la durée de la déficience."
                };
                printDialog.PrintVisual(printme, "Test Print");
            }
        }
```

Reproduction repository: https://github.com/campeters/Wpf-Print-Font-Issue

### Expected behavior

The text should print correctly without extra spaces.

### Actual behavior

The following file shows a space between 'fonction' and the 's'.  It should be a single french word 'fonctions'

[Test Print.pdf](https://github.com/dotnet/wpf/files/10582445/Test.Print.pdf)

### Regression?

This code works correctly in dot net framework and it also seems to work correctly in .net 5.

### Known Workarounds

None.

### Impact

This bug impacts the quality of PDF and print files generated from WPF programs using the 'Arial' or 'Calibri' fonts.  Some fonts work correctly.  However, the filing of some government forms require that only 'Arial' be used.

### Configuration

This bug occurs in .net 6, confirmed in 6.0.11 and 6.0.13 and .net 7. It does not appear to be specific to the configuration.  It happens on Windows 10 and Windows 11.

The exact same code works correctly in .net framework 4.8.1

**Comment by miloush** [comment]
Interesting, net48 blue, net7 red overlaid over it:

![48vs7](https://user-images.githubusercontent.com/10546952/216712169-6aafd225-346f-45cd-8ff6-b0610e1b303d.png)

**Comment by dipeshmsft** [comment]
@miloush @campeters, I am not sure yet but this issue looks like the effect of this fix https://github.com/dotnet/wpf/pull/6295
In the attached bug, you will see screenshots related to the problem.

The main issue here comes from the fact that when we print to XPS ( pdf here ) the 'advance width' values are converted from double to int and therefore after a few characters the difference between what is displayed on the screen and when it is printed became significant. Therefore, to mitigate this, we cumulated the error of conversion and update the next 'advance width' value by +/-1 when the cumulated error exceeded +/-1.

**Comment by miloush** [comment]
Yes it looks like a rounding error (though I would expect it to repeat on the right side). The solution in #6295 might even lead to catastrophic cancellation. It would be better to keep track of the accumulated advance widths rather than errors.

**Comment by campeters** [comment]
@dipeshmsft @miloush  - I can confirm that reversing https://github.com/dotnet/wpf/pull/6295 fixes the rendering problem in our app.

**Comment by campeters** [comment]
Is there a repo that contains an example of the rendering issue shown here?  https://github.com/dotnet/wpf/issues/6525  If so, I could try to find a fix for my issue that does not break that one...

**Comment by dipeshmsft** [comment]
I can find a sample repo for this issue. I will get back to you with the sample application.

**Comment by dipeshmsft** [comment]
Hey @campeters, here is the sample app [GlyphRunIssue.zip](https://github.com/dotnet/wpf/files/10704148/GlyphRunIssue.zip)
to repro the behavior before the fix.

**Comment by campeters** [comment]
Here is a repo that shows both of the issues:

https://github.com/campeters/GlyphRunIssue

In .net 5, the text renders correctly.  In .net 6, the glyphs render correctly.

**Comment by campeters** [comment]
@miloush / @dipeshmsft - I've reviewed this in more detail and the advanceErrorRounding is not the root of the problem.  Somewhere upstream of the GlyphSerializer (maybe the DrawingContextFlattener), the GlyphRuns are separated into groups of no more than 100 characters.  Within the 100 character glyph run, the spacing is correct.  However, when the drawing caret is advanced to start the next 100 character glyph run, the error correction is not taken into account, leaving an extra space (or possibly two characters squished together).  I'm going to look further, but if you have some idea where in the code the glyph runs are separated we could correct the root cause of this issue.

**Comment by miloush** [comment]
The ±100 character chopping happens in `MS.Internal.TextFormatting.TextStore`, resp. `MS.Internal.TextFormatting.TextRunCacheImp.FetchTextRun`, but I don't think it is very relevant. If you turn off the rounding completely, it renders as expected. Fix the rounding and you should be good.

**Comment by miloush** [comment]
OK while technically true, it is not a simple algorithmical issue, there seems to be an actual bug in what is rounded. I suspect the advance widths from shaping and from font can differ in floating precision but not integer precision. There is also the question about what precision does the "font width" use in XPS. I will have a look.

**Comment by miloush** [comment]
Not all scripts use spaces for word separation, and there can be significant differences after and before shaping due to kerning etc., so changing the breaking limit is not really solving the issue.

Btw. Open XPS specification ECMA-388 states in [M5.6]:
> So that rounding errors do not accumulate, the advance MUST be calculated as the exact unrounded origin of the subsequent glyph minus the sum of the calculated (that is, rounded) advance widths of the preceding glyphs [M5.6].

Which is what I originally suggested needs to be done in terms of rounding. @dipeshmsft a good practice might be to consult the specification when changing code in areas that have one.

Nowhere it is stated that the advance width coming from the font table is rounded. Therefore, when the value is omitted from XML, it sounds like the advance width is potentially not an integer.

[M5.13] states:
> When advance widths are omitted from the markup and the glyphs are algorithmically emboldened, the advance widths obtained from the horizontal metrics font table (if IsSideways is false) or the vertical metrics font table (if IsSideways is true) of the font MUST be increased by 2% of the em size [M5.13].
> Glyph advance widths MAY be omitted from markup where the advance width desired is specified in the font tables, once adjusted for algorithmic emboldening. [O5.5]

I don't see the 2% increase in the code for IsSideways (or for algorithmically emboldened glyphs). However, these rules are only for optimizing the XML and I expect the conflicting cases to affect the layout only very rarely. Either way, if that is to be fixed, it should be fixed as a separate issue.

**Comment by dipeshmsft** [comment]
> The solution in https://github.com/dotnet/wpf/pull/6295 might even lead to catastrophic cancellation. It would be better to keep track of the accumulated advance widths rather than errors.

Yes, it might even lead to catastrophic cancellation, but I think that was good in this case -  it just means that the unrounded position and the rounded position are so close together that  0 is a good enough approximation. Am I missing something?

**Comment by miloush** [comment]
@dipeshmsft My intent with the catastrophic cancellation note was that if you subtract two close numbers, you can get arbitrarily large relative error, which then keeps accumulating. I thought I could avoid it by keeping the total advance in an integer, but then I noticed the XPS specification is not clear on whether the advance is integral or not. You are correct, if we don't accumulate it it is fine.

**Comment by wstaelens** [comment]
> @miloush / @dipeshmsft - I've reviewed this in more detail and the advanceErrorRounding is not the root of the problem. Somewhere upstream of the GlyphSerializer (maybe the DrawingContextFlattener), the GlyphRuns are separated into groups of no more than 100 characters. Within the 100 character glyph run, the spacing is correct. However, when the drawing caret is advanced to start the next 100 character glyph run, the error correction is not taken into account, leaving an extra space (or possibly two characters squished together). I'm going to look further, but if you have some idea where in the code the glyph runs are separated we could correct the root cause of this issue.

Glad I found this topic. We are experiencing the same issue when printing out XPS documents.

When we render on screen ourselves, everything is fine:
![xps-bug-01-screen](https://user-images.githubusercontent.com/7447285/226285469-d17f8aa0-5eb4-4ab3-81a5-32aef2082db8.jpg)

When we print the XPS we see `10` being smashed together exactly at character position 100/101.
![xps-bug-02-print](https://user-images.githubusercontent.com/7447285/226285490-7047f3f6-8314-48c5-8f9c-1ac0fdaed0b6.jpg)

This is the content:
![xps-bug-03](https://user-images.githubusercontent.com/7447285/226285149-85124bd5-4f81-4b02-a57d-38d3599538d3.PNG)

The two strings:
`       xxx  DOOS 200ST                                                          3.3776             10    xxx`

`       xxx  DOOS 100ST                                                          8.6726             10    xxx`


**How can we get this fix at/for our customers?**

I've seen this being merged
https://github.com/dotnet/wpf/pull/6555 
https://github.com/dotnet/wpf/pull/6295

But there has also [seen a question by @campeters](https://github.com/dotnet/wpf/pull/7545#issuecomment-1445467488) if this is going into a dotnet 6 maintenance release. So I assume this fix it not available yet for us?

We are also on .net 6.
