### ISSUE TITLE
Add license headers to test code

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/wpf#75]

**Comment by ConnorL33t** [comment]
I'll do this, should be pretty quick!

**Comment by karelz** [comment]
Great! Looking forward to it!
BTW: If it is too big (hundreds of files), I think we would be fine with iterations - each in separate PR. (I didn't check how many files are there ...)

**Comment by karelz** [comment]
BTW: We have used [Code Formatter tool](https://github.com/dotnet/codeformatter) in the past for these things. I'm told it does not work for test projects, but maybe it can be fixed up ... that way you avoid manual work / ad-hoc scripting and it will be useful for other projects in future.
