### ISSUE TITLE
Cannot use local build of WPF in an application

### ISSUE THREAD

**Issue by dotMorten** [dotnet/wpf#751]
* .NET Core Version: 3.0.100-preview5-011568
* Windows version: 1903
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**
When trying to use the locally built binaries using the approach [described here](https://github.com/dotnet/wpf/blob/master/Documentation/developer-guide.md#testing-api-changes), the application compiles and launches, but before any breakpoint is hit (even in App.Xaml.cs' constructor) the app terminates.

 **Actual behavior:** 
The app terminates with code -532462766 (0xe0434352) before even hitting the first line of code. EventViewer shows the following:
```
Application: WpfTest.exe
CoreCLR Version: 4.6.27622.75
.NET Core Version: 3.0.0-preview5-27626-15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```
 PresentationFramework.dll is present in the output folder, and identical to the one built from the repo, so it appears it's looking for a different assembly (version doesn't match either).

 **Expected behavior:**
App launches
 
 **Minimal repro:**
Install latest .NET Core 3.0 SDK (Preview 5)
Then from commandline:
```
  git clone https://github.com/dotnet/wpf 
  wpf\restore.cmd
  wpf\build.cmd -pack
  md WpfTest
  cd WpfTest
  dotnet new wpf
```
Open the generated project and add the following (based on the dev doc, but note the doc left out the `\Debug\` part of the paths):
```xml
 <PropertyGroup>
     <!-- Change this value based on where your local repo is located -->
     <WpfRepoRoot>..\wpf</WpfRepoRoot>
     <!-- Publishing a self-contained app ensures our binaries are used. -->
     <SelfContained>true</SelfContained>
    <!-- The runtime identifier needs to match the architecture you built WPF assemblies for. -->
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(WpfRepoRoot)\artifacts\packaging\Debug\Microsoft.DotNet.Wpf.GitHub\ref\netcoreapp3.0\*.dll" Private="false" />
    <ReferenceCopyLocalPaths Include="$(WpfRepoRoot)\artifacts\packaging\Debug\Microsoft.DotNet.Wpf.GitHub\lib\netcoreapp3.0\*.dll" />
    <ReferenceCopyLocalPaths Include="$(WpfRepoRoot)\artifacts\packaging\Debug\Microsoft.DotNet.Wpf.GitHub\lib\$(RuntimeIdentifier)\*.dll" />
  </ItemGroup>
```

Run the app (it'll exit almost immediately). 

I also tried with the nightly build of the SDK, but `ReferenceCopyLocalPaths` because the version is newer than what you build locally (that's fixable, but then you also need to override you nuget package sources, and at that point you're back to the above problem)

@stevenbrix [reported](https://twitter.com/steven_brix/status/1131695332511760384) he's also seeing the same behavior.

**Comment by vatsan-madhavan** [comment]
Publish your app using the corresponding compatible RID (`win- 86` or `win-x64`), then replace the DLL under the RID specific`publish` folder. Does this work ok?

**Comment by dotMorten** [comment]
> Publish your app using the corresponding compatible RID (win- 86 or win-x64), then replace the DLL under the RID specificpublish folder. Does this work ok?

Isn't that what ` <SelfContained>true</SelfContained> <RuntimeIdentifier>win-x86</RuntimeIdentifier>` does? It copied it all to that folder. I'm not sure what is missing to be copied?

Having to do a publish, then manual copy and launch means you don't get quick iterations on build, debug and step in, fix, repeat.

**Comment by stevenbrix** [comment]
So turns out this is due to a bug in Arcade that has been fixed. I'm going to install the latest daily from core-sdk and give it a go

**Comment by stevenbrix** [comment]
Yeah it worked for me. I'm going to go ahead and close this issue. I filed #781 for fixing the typos in the developer guide and
