### ISSUE TITLE
Intellisense reports incorrect errors in WPF's code behind files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#7513]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-reports-incorrect-errors-in/10208755)._

---
[severity:It's more difficult to complete my work]
Intellisense reports inexistent errors in WPF's code behind files. I think it happens when using a custom base class. The project builds, the app works, intellisense is wrong.

---
#### Feedback Bot on 11/21/2022, 05:09 PM: 

(private comment, text removed)
#### Dolly Wang [MSFT] on 11/21/2022, 09:53 PM: 

(private comment, text removed)
#### Rodolfo Motta on 11/25/2022, 03:49 AM: 

(private comment, text removed)
#### Feedback Bot on 11/27/2022, 06:39 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment]
Closing in absence of any further information.
