### ISSUE TITLE
How to programmatically set a button with Vector image

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#7524]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/How-to-programmatically-set-a-button-wit/10273322)._

---
I can statically set a vector image to a button by binding a button's ContentControl to a static resource. But if I want to do this using code behind and programmatically create a button and set it's ContentControl, it does not work. At runtime the vector image does not show in the button.

I have created a bare bone project (WpfApp9.zip) to illustrate the issue and also a screenshot when it is run.

Thanks.

---
#### Feedback Bot on 2/7/2023, 06:55 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by miloush** [comment]
Can we have the code attached?

**Comment by KC7465128305** [comment]
[WpfApp9.zip](https://github.com/dotnet/wpf/files/10710798/WpfApp9.zip)

Attached is the project.  Thanks!

**Comment by miloush** [comment]
That's because in the code, you are setting the resource to `ContentControl.Control`, while in the XAML you are setting it to `ContentContorl.Template`. i.e. is
```C#
ContentControl contentControl = new ContentControl
{
    Template = (ControlTemplate)this.FindResource("Test1")
};

Button button2 = new Button
{
    Content = contentControl,
    Width = 250,
    Height = 75
};
```
what you are looking for?

**Comment by KC7465128305** [comment]
I am trying to programmatically create a button at runtime and show a vector image on the button.  I can do it statically as shown in the example but not dynamically at runtime.

**Comment by miloush** [comment]
I provided the code to create the button at runtime, does that not do what you need?

**Comment by KC7465128305** [comment]
Yes it does!  Thanks a lot!

**Comment by KC7465128305** [comment]
I should have tested your code before I commented. Thanks very much.
