### ISSUE TITLE
InkCanvas.DynamicRenderer set different custom DynamicRenderer multiple times, throw an exception

### ISSUE THREAD

**Issue by jaelys** [dotnet/wpf#7537]
### Description
When using the touch screen, errors will occur, but not when using the mouse

On the touch screen, the two buttons switch and click multiple times to set a custom Dynamic Renderer for InkCanvas.DynamicRenderer. The crash always occurs after DrawPen OnRemoved

Button(DrawPen)、Button(DrawArrow)

`var dr = name switch
                {                    
                    "GeneralPen" => new DrawPen(this),                   
                    "ArrowPen" => new DrawArrow(this),                                
                    _ => new DrawPen(this),
                };   
           
 DynamicRenderer = dr;
`

If set different custom DynamicRenderer multiple times, throw an exception

`App_DispatcherUnhandledException--Object reference not set to an instance of an object.
 at System.Windows.Input.StylusPlugIns.DynamicRenderer.TransitionComplete(StrokeInfo si)
   at System.Windows.Input.StylusPlugIns.DynamicRenderer.<>c__DisplayClass19_0.<NotifyAppOfDRThreadRenderComplete>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

[PC-Test-develop-2.zip](https://github.com/dotnet/wpf/files/10762876/PC-Test-develop-2.zip)

### Reproduction Steps

Ditto description

### Expected behavior

No exception will be thrown

### Actual behavior

Throw thread exception

### Configuration

.NET Core Version: .NET 7.0.103 SDK
Windows version: Version 22H2 (OS Build 19045.2546)

**Comment by miloush** [comment]
Please provide a repro project having the issue.

**Comment by lindexi** [comment]
@jaelys Sorry, I run your demo but I do not repro it.

**Comment by jaelys** [comment]
@lindexi Thank you for your help. I updated the Demo and annotated some code that may prevent exceptions. These codes are valid, but not 100%. Now we should be able to simply reproduce the exception. Just press the Pen Button several times, switch another button, and repeat it several times

感謝林德熙大神

**Comment by lindexi** [comment]
@jaelys Sorry, I run the `PC-Test-develop-2` , but I do not repro it.

![InkCanvas DynamicRenderer set different custom DynamicRenderer multiple times](https://user-images.githubusercontent.com/16054566/219544728-0aa3fe17-cfa5-4fb7-b485-50c2034bd39d.gif)

**Comment by lindexi** [comment]
@jaelys  Thank you. And I know why. This is the thread-safe issues in WPF.

The DynamicRenderer call the `OnRemoved` before the `TransitionComplete`. And the `OnRemoved` will set the `_applicationDispatcher` to null but the `TransitionComplete` will use the `_applicationDispatcher` which will throw the NullReferenceException.

**Comment by jaelys** [comment]
> @jaelys Thank you. And I know why. This is the thread-safe issues in WPF.
> 
> The DynamicRenderer call the `OnRemoved` before the `TransitionComplete`. And the `OnRemoved` will set the `_applicationDispatcher` to null but the `TransitionComplete` will use the `_applicationDispatcher` which will throw the NullReferenceException.

I use the physical touch whiteboard, which is easy to reproduce,
Abnormality cannot be reproduced in mouse or analog touch

Thank you again for your help

**Comment by lindexi** [comment]
@jaelys Thanks for your feedback, and I am trying to fix this issues.
