### ISSUE TITLE
[netcore3] AssemblyHelper depends on obsolete dlls to be loaded in order to load extensions

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#756]
Copied from VSO ID: 831354
Problem:

\WindowsBase\MS\Internal\AssemblyHelper.cs expects certain obsolete assemblies to be loaded (such as System.Data.dll) in order to load extension dlls.

This is a problem when someone uses types that used to be contained in these assemblies, as the extension functionality does not get loaded and the extension methods cannot be called. 

Steps to reproduce:

1. Run DrtDataSrv 
2. Observe Exception:
System.Exception: 'Assert failed: Target value has wrong value for target String, source SQLStruct, property SqlDouble Expected: null  Got:  [Suite: markup  Test: TestTargetNullValue
]'

**Comment by vatsan-madhavan** [comment]
We should eval whether we really need extension assemblies in .NET Core. 

/cc @rladuca
