### ISSUE TITLE
integrate the electronjs application inside the Wpf application with maximized window. 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#7572]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/integrate-the-electronjs-application-ins/10116295)._

---
Process.StartInfo.WindowStyle = ProcessWindowStyle.Maximized; 

but it is not working for maximized window. it loading as minimize state.
 i am using WondowsFormhost

string exeName = AppDomain.CurrentDomain.BaseDirectory + "filePath";
var procInfo = new System.Diagnostics.ProcessStartInfo(exeName);
procInfo.WorkingDirectory = System.IO.Path.GetDirectoryName(exeName);
procInfo.WindowStyle = ProcessWindowStyle.Maximized;
_childp = Process.Start(procInfo);
System.Windows.Forms.Panel _pnlSched = new System.Windows.Forms.Panel();
WindowsFormsHost windowsFormsHost1 = new WindowsFormsHost();
windowsFormsHost1.Child = _pnlSched;
electrongrid.Children.Add(windowsFormsHost1);
while (_childp.MainWindowHandle == IntPtr.Zero)
{
Thread.Yield();
}
_appWin = _childp.MainWindowHandle;
SetParent(_appWin, _pnlSched.Handle);
// dispatcherTimer.Stop();

could please help me what can i do for maximized window

---
#### Feedback Bot on 8/11/2022, 01:03 PM: 

(private comment, text removed)
#### Feedback Bot on 12/1/2022, 00:24 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by miloush** [comment]
Please provide a repro project.

**Comment by singhashish-wpf** [comment]
Closing in absence of repro/reply.
