### ISSUE TITLE
Changing collection in CollectionChanged event results in exception

### ISSUE THREAD

**Issue by Symbai** [dotnet/wpf#7575]
### Description

If you change the collection within `CollectionChanged` event of an `ObservableCollection` an exception is thrown: `Cannot change ObservableCollection during a CollectionChanged event`.

Which at first makes sense and is probably by design to avoid ending in a loop it simply block us from making SAFE changes to the collection which dont end in a loop. Consider the following pseudo code:

```C#
var collection = new ObservableCollection<int>() { 0, 1, 2, 3, 4}

collection.CollectionChanged += (e, s) => {
	if (s.Action == System.Collections.Specialized.NotifyCollectionChangedAction.Add) {		
		collection.Move(ACollection[1], 0);
	}
};
collection.Add(5);
```

This code is absolutely safe to execute. But an exception is thrown. The only way to get it to work is moving the modification to another thread:

```C#
var collection = new ObservableCollection<int>() { 0, 1, 2, 3, 4}

collection.CollectionChanged += (e, s) => {
	if (s.Action == System.Collections.Specialized.NotifyCollectionChangedAction.Add) {		
		Bla();
	}
};
collection.Add(5);

async void Bla() {
	Application.Current.Dispatcher.Invoke(() => {	
		collection.Move(collection[1], 0);
	}, System.Windows.Threading.DispatcherPriority.Background);
}
```

I dont think changing it would be a breaking change because no existing code looks for and handle that specific exception. 
Instead of throwing an exception, a warning in VS analyzer might be better. Because an exception shouldn't be used as a warning like it is now.

### Reproduction Steps

See above

### Expected behavior

No exception, at most a VS analyzer warning

### Actual behavior

Exception is thrown

### Known Workarounds

See above

### Configuration

.NET 6

**Comment by lindexi** [comment]
@Symbai  The `Dispatcher.Invoke` do not mean run in other thread. And it means that run delay. I wrote a blog about this behavior, see [My Blog](https://blog-lindexi-com.translate.goog/post/WPF-%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98-%E5%9C%A8-ObservableCollection-%E7%9A%84-CollectionChanged-%E4%BF%AE%E6%94%B9%E9%9B%86%E5%90%88%E5%86%85%E5%AE%B9%E5%B0%86%E8%AE%A9-UI-%E6%98%BE%E7%A4%BA%E9%94%99%E8%AF%AF.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp)

I guess this behavior is to solve the problem of infinite loop. And I think it's hard to warn in the analyzer.

**Comment by Symbai** [comment]
> I guess this behavior is to solve the problem of infinite loop. And I think it's hard to warn in the analyzer.

Yes but the infinite loop only occurs in SOME scenarios, not guaranteed always. Thus throwing an exception for something which MIGHT cause a loop isn't ideal. In fact it blocks me and others from writing safe code. I dont know how the analyzer works but in my example I only listen to ADD actions and then I perform a MOVE action to the list (the event raises on my move action but my code is not executed). 

Anyway the analyzer is something which I say could be useful. If the analyzer isn't possible then that is also fine with me. But the exception is definitely a problem and shouldn't be there. Like I said, exceptions shouldn't be used as warnings.

**Comment by lindexi** [comment]
@Symbai I find the code of ObservableCollection is in [dotnet runtime](https://github.com/dotnet/runtime). Should you move the issue to [dotnet runtime](https://github.com/dotnet/runtime)?

**Comment by Symbai** [comment]
How do I do that?

**Comment by Symbai** [comment]
I've created an issue in .NET runtime repo and linked it here. Closing this for now.
