### ISSUE TITLE
Cannot compile WPF with parameterized App constructor

### ISSUE THREAD

**Issue by tim-fernico** [dotnet/wpf#758]
* .NET Core Version: 3.0 Preview5
* Windows version: Windows 10 Pro (1903)
* Does the bug reproduce also in WPF for .NET Framework 4.7.2?: No

 **Problem description:**
Cannot compile WPF app with parameterized App constructor.  My App constructor is defined as
```
 public App(object param1, ...)
``` 

 **Actual behavior:** 
Build fails with following error:
``` 
>obj\Debug\netcoreapp3.0\App.g.cs(74,35,74,46): error CS7036: There is no argument given that corresponds to the required formal parameter 'param1' of 'App.App(object param1)'
``` 
This is due to the generated Main method in app.g.cs calling the App constructor without any parameters.

 **Expected behavior:**
With .NET 4.7, I specify that the App.xaml build action is 'Page' rather than 'Application definition' to make sure duplicate Main is not generated.  I cannot change the build action in a dot net 3.0 csproj as I get:

    error NETSDK1022: Duplicate 'Compile' items were included.
 
 **Related discussion**
https://github.com/dotnet/wpf/issues/192

**Comment by ryalanms** [comment]
@tim-fernico: Microsoft.NET.Sdk.WindowsDesktop.props is the msbuild file that adds the ApplicationDefinition:

https://github.com/dotnet/wpf/blob/master/packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props#L3

Setting EnableDefaultApplicationDefinition to false should allow adding App.xaml as a Page.  (Also take a look at EnableDefaultPageItems to turn off implicit Page globbing.) 

```xml
<PropertyGroup>
  <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
</PropertyGroup>
```
If it is still failing and you can post a small repro project, I will take a look.  Thanks.

**Comment by tim-fernico** [comment]
Thanks @ryalanms, ````<EnableDefaultApplicationDefinition>```` enabled it to build.

**Comment by ryalanms** [comment]
Thanks. Let me know if you run in to any more problems.  Some of this hasn't been documented yet.
