### ISSUE TITLE
Can non-linear gradients be achieved in WPF?

### ISSUE THREAD

**Issue by dhq-boiler** [dotnet/wpf#7603]
This is a WPF expressive question.

I want to express a non-linear gradient in an WPF app I'm developing.

I heard that WPF makes it virtually impossible to inherit from the Brush class.

How do I implement a custom Brush in WPF?
https://stackoverflow.com/a/794624/21066195

Is there a way to achieve non-linear gradients in WPF?

<Supplement>

For example, I want to apply a non-linear gradient brush to the Rectangle's Fill property like this.

```xaml
<Rectangle
	Width="40"
	Height="45"
	StrokeThickness="0">
	<Rectangle.Fill>
		<NonLinearGradientBrush>
			<NonLinearGradientBrush.GradientStops>
				<GradientStop2D Color="#FFFF0000" Point="25, 0" />
				<GradientStop2D Color="#FFFFFFFF" Point="0, 20" />
				<GradientStop2D Color="#FF000000" Point="40, 45" />
			</NonLinearGradientBrush.GradientStops>
		</NonLinearGradientBrush>
	</Rectangle.Fill>
</Rectangle>
```

![Can-non-linear-gradients-be-achived-in-WPF](https://user-images.githubusercontent.com/7916855/223768266-fa56d0ee-0b8f-4ff3-bd45-95199f066fd2.jpg)

The image represents an approximate ideal image. It may be slightly distorted.

**Comment by hez2010** [comment]
Yes. you can write your own shader to achieve it, see https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.effects.shadereffect?view=windowsdesktop-7.0

**Comment by dhq-boiler** [comment]
I see. I've used the ShaderEffect class a while ago, so I'll give it a try.
Thank you for your response.

**Comment by miloush** [comment]
I think it is a reasonable request to enable developers adding new types of brushes. Even if you can do with a shader effect, you cannot use it as a brush.
