### ISSUE TITLE
Windows session change, user interface is broken when reconnecting

### ISSUE THREAD

**Issue by OfenHuryes** [dotnet/wpf#7622]
### Description

When you change user on Windows and then reconnects to his session, the user interface of the application does strange things (disappearance of icon, change of size, ...)

The events (Click, ...) are still functional, it is only the UI.

After analysis, I see that at each reconnection the application's Main constructor is recalled. There is obviously a problem in this use case in WPF, but no solution proposed so far seems to work.

### Reproduction Steps

Create a minimal WPF application, attach a tool to get the call list. Log out of your windows session, then log back in. You can see the call to the constructor during this windows reconnection

### Expected behavior

The constructor must not be called back, or be able to detect if it is the first or nth call

### Actual behavior

Depending on the controls in the interface, especially when it comes to DataTemplate, the UI does anything

**Comment by huiliu-code** [comment]
Hi, @OfenHuryes. Could you show a minimal sample code that can reproduce the problem? Is it possible to show the expected and actual results separately?

**Comment by singhashish-wpf** [comment]
Closing in absence of further information.
