### ISSUE TITLE
System.Reflection.MetadataLoadContext has an incoherent dependency on System.Memory -> causes build breaks in PresentationBuildTasks

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#763]
See https://github.com/dotnet/corefx/issues/37943 for context. 

- [x] Implement a workaround
  - #764 
- [x] Wait for corefx to fix  https://github.com/dotnet/corefx/issues/37943
- [x] Undo the workaround

**Comment by rladuca** [comment]
CoreFX has been updated and we're seeing that in the DARC flow [here](https://github.com/dotnet/wpf/pull/826).

As such, we need to make the final change to remove the pinned packages and close the loop.
