### ISSUE TITLE
.net7 wpf win7 64 use large memory.

### ISSUE THREAD

**Issue by tianmafly** [dotnet/wpf#7640]
.net7 wpf win7 sp1 64, system use large memory.
.net7 wpf win7 sp1 32, system use normal memory.
.net7 wpf win10 64, system use normal memory.
.net6 wpf win7 sp1 64, system use normal memory.

.net7 wpf win7 sp1 64, When run the exe, the process memory is normal, but the system memory use about 4GB.
![image](https://user-images.githubusercontent.com/38370307/226070205-88e1148e-cb06-473d-8e7c-c48cadd98d19.png)

why system memory  use so large with wpf .net7 win7 sp1 64 ?

**Comment by lgztx96** [comment]
.NET 7 doesn't support Windows 7
https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md#support-changes-from-net-60
https://github.com/dotnet/runtime/issues/79469
https://github.com/dotnet/runtime/issues/80078

**Comment by miloush** [comment]
Does this happen with console application too? Without a repro it would be difficult to provide any advice.

**Comment by tianmafly** [comment]
https://github.com/dotnet/runtime/issues/79469
this is the same question

> Does this happen with console application too? Without a repro it would be difficult to provide any advice.

**Comment by miloush** [comment]
Then this is clearly unrelated to WPF. Moreover, the issue there has already been discussed and closed in the referenced repo with a suggested workaround.

**Comment by singhashish-wpf** [comment]
Closing as win7 is not supported with .NET7.
