### ISSUE TITLE
GetCharacterIndexFromPoint does not work as intended if HorizontalContentAlignment is set to Center

### ISSUE THREAD

**Issue by rampaa** [dotnet/wpf#7651]
### Description

If the HorizontalContentAlignment of a TextBox is set to "Center" (or to "Right"), [GetCharacterIndexFromPoint](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.textbox.getcharacterindexfrompoint?view=windowsdesktop-7.0) does not return the correct character index corresponding to a given point and instead returns -1.

### Reproduction Steps

See the following demo:
[GetCharacterIndexFromPointBugDemo.zip](https://github.com/dotnet/wpf/files/11030050/GetCharacterIndexFromPointBugDemo.zip)

### Expected behavior

GetCharacterIndexFromPoint should return the correct character index from a given point even if the HorizontalContentAlignment is set to Center.

### Actual behavior

GetCharacterIndexFromPoint returns -1 if HorizontalContentAlignment is set to Center/Right

### Configuration

.NET 6/7
Windows 10 x64

**Comment by huiliu-code** [comment]
Hi,@[rampaa](https://github.com/rampaa). I encountered errors when unzipping your zip file. Could you provide a new zip file that can reproduce the problem?

**Comment by rampaa** [comment]
https://github.com/rampaa/GetCharacterIndexFromPointBugDemo

**Comment by miloush** [comment]
OK found it, the important part is that `GetCharacterIndexFromPoint` is called with `snapToText: false`.

In that case `TextBoxView.GetLineIndexFromPoint` cannot find the line:

https://github.com/dotnet/wpf/blob/f5be9288bd4595fa32a816fd53377209a783c60c/src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/TextBoxView.cs#L1642-L1646

and the whole character finding is cancelled.

https://github.com/dotnet/wpf/blob/f5be9288bd4595fa32a816fd53377209a783c60c/src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/TextBoxView.cs#L612-L614

So a workaround is to use `snapToText: true`.

I think the fix should be in `GetLineIndexFromPoint` to take into account line alignment.

**Comment by dipeshmsft** [comment]
@rampaa @miloush , closing this issue as the fix has been merged in the main branch

**Comment by rampaa** [comment]
@dipeshmsft will the fix be backported to .NET 6?

**Comment by pchaurasia14** [comment]
@rampaa - We'll need to discuss with shiproom if this can be backported to .NET 6/7.

**Comment by rampaa** [comment]
@pchaurasia14 thanks for your reply! I've developed an application that makes extensive use of GetCharacterIndexFromPoint so this bug is a real headache for me and for my user base. Would really appreciate a .NET 6 backport.
