### ISSUE TITLE
Control are visible in Visual Studio 2022 Toolbox even after DesignTimeVisible attribute as false.

### ISSUE THREAD

**Issue by SaranRajChandrasekaran** [dotnet/wpf#7683]
### Description

In VS 2022, I have a Custom Control Library, When adding the Custom Control to WPF ToolBox the controls are visible even after adding the following attribute "[Browsable(false), EditorBrowsable(EditorBrowsableState.Never), ToolboxItem(false), DesignTimeVisible(false)]". If I use the "DesignTimeVisible(false)" attribute at first "[DesignTimeVisible(false), Browsable(false), EditorBrowsable(EditorBrowsableState.Never), ToolboxItem(false)]" in this format it works.

But In VS 2019, it supports all the formats have no issues.

[WpfCustomControlLibrary (2).zip](https://github.com/dotnet/wpf/files/11090149/WpfCustomControlLibrary.2.zip)

### Reproduction Steps

In VS 2022, 
Create a simple Custom Control Library.
Add the following attribute "[Browsable(false), EditorBrowsable(EditorBrowsableState.Never), ToolboxItem(false), DesignTimeVisible(false)]" to the control.
Add the Custom Control Library to WPF Toolbox. The controls are visible in Toolbox even after adding this attribute"[Browsable(false), EditorBrowsable(EditorBrowsableState.Never), ToolboxItem(false), DesignTimeVisible(false)]"

### Expected behavior

Control shouldn't be visible in the Toolbox.

### Actual behavior

But the controls are visible in the Toolbox even after adding the "DesignTimeVisible(false)" attribute.

But In VS 2019, it supports all the formats have no issues.
Is there any solution to support all formats in VS 2022?

**Comment by miloush** [comment]
I am afraid you need to use the Visual Studio feedback for this, there is no code in this repo that would influence this (which can be seen by searching for `DesignTimeVisible` or `DesignTimeVisibleAttribute`).

@pchaurasia14 It looks like the new bug template no longer contains the information that designer issues do not belong to this repo, might be worth adding it in the description?

**Comment by pchaurasia14** [comment]
@miloush - Yup. I've added the note in the bug template. 

@SaranRajChandrasekaran - You can use [this](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) link to file an issue with VS tooling.
