### ISSUE TITLE
wpf Fontawesome icons are not showing on Visual Studio Designer 2022

### ISSUE THREAD

**Issue by carlos83cc** [dotnet/wpf#7686]
I am writing a WPF application and I’m using fontawesome icons as part of my UI.

These are the Steps I took to get to the issue.

- I downloaded the fontawesome.ttf file
- In Visual studio I created a new WPF project. (.NET Framework 4.8)
- I created a new folder called fonts and placed the .ttf file in the same folder
- I set the property of the .ttf file as a resource.
- I rebuilt the project.
- Then I added the ttf font as a resource in the proper way
 ` <FontFamily x:Key=“FontAwesomeFont” >pack://application:,/Fonts/#Font Awesome 5 Free Solid</FontFamily>`
- I registered the icon in this way
  `<system:String x:Key="FontAngleUp">&#xf106;</system:String>`

If I use the Visual Studio 2019 all warks well: both at the design time and at run time.
If I use the Visual Studio 2022 only at run time works well

Thanks for any help

**Comment by miloush** [comment]
As the bug template says, any designer related issues need to be filed as feedback on Visual Studio, see [here](https://learn.microsoft.com/en-gb/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022). When you do that, I suggest you include a repro project.
