### ISSUE TITLE
wpf OpenFileDialog cuts off name

### ISSUE THREAD

**Issue by danielbanda** [dotnet/wpf#7690]
### Description

Launching an open file dialog displays a cut off the **file name** field:

![image](https://user-images.githubusercontent.com/5540896/228934773-20634779-e389-42a1-9900-31bb343b97ac.png)
Notice how the name field only displays the last N characters of the prepopulated name instead of the whole name - in this case "f00173de206d369809b102e15cc48fc8.pdb".

Here is the same dialog after I moved the caret to the beginning of the **file name**:
![image](https://user-images.githubusercontent.com/5540896/228935660-1d3b5dca-d00d-4c5f-83c6-e909832b68bf.png)

### Reproduction Steps

    var dialog = new OpenFileDialog();
    dialog.Filter = "PDB (*.pdb)|*.pdb";
    dialog.FilterIndex = 0;
    dialog.FileName = "f00173de206d369809b102e15cc48fc8.pdb";
    dialog.ShowDialog();

### Expected behavior

**File name** field displays the whole provided name.

![image](https://user-images.githubusercontent.com/5540896/228943454-509a7287-5693-48e4-a9ca-406960917051.png)

### Actual behavior

**File name** field only displays the last N characters.

![image](https://user-images.githubusercontent.com/5540896/228934773-20634779-e389-42a1-9900-31bb343b97ac.png)

### Configuration

.net 6 & 7
Windows 11 Enterprise
Version 22H2
x64
Do not know if it is specific to this configuration

**Comment by miloush** [comment]
I am convinced this has been filed before but I cannot find the issue. This is not something WPF can influence, you should file a feedback on Windows.

**Comment by dipeshmsft** [comment]
@danielbanda @miloush from what I see this issue looks similar to this issue https://github.com/dotnet/winforms/issues/7968 and it is a Windows bug. Closing this as external issue.
