### ISSUE TITLE
Right clicking on a system menu item (Move, Size, Minimize ....) does not work for a window with custom WindowChrome

### ISSUE THREAD

**Issue by nesakobi** [dotnet/wpf#7739]
### Description

Here is the repo - a simple illustration of the issue https://github.com/nesakobi/window_chrome_wpf
There are 2 windows - one of them is the default Window without any styling and property changes. When the right mouse button is clicked on title bar of the window, the system menu becomes active and it is possible to click on menu items both left and right mouse clicks. Both types of clicks work in the same way. The second is a window with property "WindowStyle = None" and WindowChrome configured. Right clicking at the top of the window activates the system menu. Left-clicking on a menu item performs an action, while right clicking on an item does nothing. When there is a DataGrid and DataGrid has context menu,  right-clicking on the system menu items activates the DataGrid context menu.

![context_menu](https://user-images.githubusercontent.com/41533598/233176151-c4eb8c01-53e5-421a-87a4-f246ae872d2c.png)

### Reproduction Steps

1. Create a style for window
2. Set custom chrome and set the property WindowStyle = None
3. Try opening the system menu by clicking on the window icon
4. Right-click any menu item - Move, Size, Minimize, etc...

### Expected behavior

System menu - the right clicking on menu item should work the same as for window with WindowStyle = SingleBorderWindow

### Actual behavior

System menu - menu item does not work on right click.

Also it activates PreviewMouseRightButtonUp and MouseRightButtonUp for controls inside the window content (annoying behavior)

### Configuration

Tried both with .Net framework 4.8.1 and .Net 7.0
OS: Microsoft Windows [Version 10.0.19044.2846]

**Comment by dipeshmsft** [comment]
@nesakobi this issue is fixed now. 
Thanks to @miloush for fixing this bug.

**Comment by batzen** [comment]
@nesakobi As the PR was merged into main it's .NET 8.0.

**Comment by nesakobi** [comment]
Thank you all.
