### ISSUE TITLE
WPF apps crash when using clipboard APIs

### ISSUE THREAD

**Issue by miguep** [dotnet/wpf#775]
* .NET Core Version: 3.0.100-preview6-012099
* Windows version: Win10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 **Problem description:**
 
Using some of the Clipboard APIs, throw exceptions and cause application crashes.

E.g.
Clipboard.SetData(DataFormats.UnicodeText, "abc");

 **Actual behavior:** 

Throws an ExecutionEngineException.
 
 **Expected behavior:**

sets the data to the clipboard without issue
 
 **Minimal repro:**
Clipboard.SetData(DataFormats.UnicodeText, "abc");

**Comment by miguep** [comment]
Filed a coreclr issue for this:

https://github.com/dotnet/coreclr/issues/24816

**Comment by rladuca** [comment]
Looks like @jkotas fixed this in https://github.com/dotnet/coreclr/pull/24818, thanks Jan!
