### ISSUE TITLE
Visual Studio IntelliSense / XML documentation for WPF

### ISSUE THREAD

**Issue by space-alien** [dotnet/wpf#7753]
I'm using `Visual Studio 17.5.4` and `.NET SDK 7.0.5`

Upon creating a new WPF application, I have no XML documentation available in IntelliSense for the WPF library.

Browsing to source (F12) shows the library at `C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\7.0.5\`

This is in contrast to a WinForms app, which has the docs in IntelliSense, with F12 showing sources via SourceLink.

Am I missing something obvious?

**Comment by space-alien** [comment]
Please also see https://stackoverflow.com/questions/76079639/no-xml-documentation-intellisense-for-wpf

**Comment by pchaurasia14** [comment]
We are investigating this issue. Will keep this thread posted.
