### ISSUE TITLE
WPF .NET framework 4.8.1 fails to launch application

### ISSUE THREAD

**Issue by Holilife** [dotnet/wpf#7811]
### Description

When you try to start application it's closed instantly without showing UI window.

- Only happens for 4.8.1 target. 
- 4.8 and below works as expected. 
- .NET core works as expected.

### Reproduction Steps

1. Create WPF application from default templates, which targets .NET framework 4.8.1.
2. Start application.

### Expected behavior

Run and show application window.

### Actual behavior

Instantly closes application.

### Configuration

.NET 4.8.1

**Comment by karahbit** [comment]
This is happening to me with my WPF app under .NET Framework 4.8.1. The crash does not occur at launch, but when hovering the mouse over any point of its window. 

Exception thrown when Debugging within Visual Studio:

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Bloomberglp.AppPortalApi.Desktop.AppPortalPopupControlService' threw an exception.
  Source=Bloomberglp.AppPortalApi
  StackTrace:
   at Bloomberglp.AppPortalApi.Desktop.AppPortalPopupControlService.OnPostProcessInput(Object sender, ProcessInputEventArgs e)

Inner Exception 1:
TypeLoadException: Could not load type 'System.Windows.Controls.ToolTip+ToolTipTrigger' from assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

Please see [#7935](https://github.com/dotnet/wpf/issues/7935)
