### ISSUE TITLE
 Screen.AllScreens return different size 

### ISSUE THREAD

**Issue by DaZiYuan** [dotnet/wpf#785]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Windows version: (`winver`)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No

 
 
 **Problem description:**
 Screen.AllScreens return different size between framework and netcore ,system DPI 125%
 **Actual behavior:** 
 net core
![image](https://user-images.githubusercontent.com/80653/58603529-b1849300-82c3-11e9-8afc-7dee8439d1fc.png)

 **Expected behavior:**
 framework 4.7.2
![image](https://user-images.githubusercontent.com/80653/58603550-c9f4ad80-82c3-11e9-8143-64efed9d4c22.png)

 **Minimal repro:**
 https://github.com/giantapp-libraries/LiveWallpaperEngine/blob/master/LiveWallpaperEngine/LiveWallpaperEngineManager.cs

Line:56

**Comment by rladuca** [comment]
Screen is a Windows Forms class. @DaZiYuan are you accessing this from a WPF application?  Does the same behavior occur in a Windows Forms application?

This could be related to #334, but I don't want to make that call without a bit more information.

@Tanya-Solyanik, @zsd4yr  is this an issue that rings a bell in WinForms?

**Comment by DaZiYuan** [comment]
![image](https://user-images.githubusercontent.com/80653/58605255-b4828200-82c9-11e9-9384-202e4ead25d2.png)
all accessing from Winform get same result. but when accessing from WPF is not between WPF Framework4.72 and WPF core.
 I created a simple demo here. https://github.com/DaZiYuan/netcore_wpf_test

**Comment by rladuca** [comment]
@DaZiYuan Thanks for the extra info.  I'll confirm tomorrow, but this sounds very much like a dupe of the root cause in #334 (and other high DPI issues stemming from it).

**Comment by DaZiYuan** [comment]
I think it's same issue. I will use this workaround until to new version. thanks for help 
```
  <!-- Indicates that the application is DPI-aware and will not be automatically scaled by Windows at higher
       DPIs. Windows Presentation Foundation (WPF) applications are automatically DPI-aware and do not need 
       to opt in. Windows Forms applications targeting .NET Framework 4.6 that opt into this setting, should 
       also set the 'EnableWindowsFormsHighDpiAutoResizing' setting to 'true' in their app.config. -->

  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <!-- Per Monitor V1 [OS >= Windows 8.1] 
         Values: False, True, Per-monitor, True/PM -->
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
        true/PM
      </dpiAware>
      <!-- Per Monitor V1 [OS >= Windows 10 Anniversary Update (1607, 10.0.14393, Redstone 1)]
         Values: Unaware, System, PerMonitor -->
      <!-- Per Monitor V2 [OS >= Windows 10 Creators Update (1703, 10.0.15063, Redstone 2)]
         Value: PerMonitorV2 -->
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
        PerMonitorV2, PerMonitor
      </dpiAwareness>
    </windowsSettings>
  </application>
```
