### ISSUE TITLE
Custom ShaderEffect does not work in DrawingVisual or background control rendering

### ISSUE THREAD

**Issue by BigHeadDev** [dotnet/wpf#7856]
### Description

I am trying out custom shaders to develop a tool for modifying image brightness and saturation
like this：
![image](https://github.com/dotnet/wpf/assets/23449064/4de2d4cb-7c7a-44e6-9668-a2da50c93b44)
You can import an image, modify the slider in the bottom right corner, and then click the save button to save it to a file
>>>
Fortunately, by sliding two sliders in the form, the image has brightness and saturation changes, 
**Unfortunately, The saved image does not have any additional effects**

After various attempts, I have found that the built-in Effect of WPF can operate normally, but the custom ShaderEffect does not work. It seems to have done some different rendering operations on the interface

### Reproduction Steps

1,xaml：
```xml
 <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="50" />
            <RowDefinition />
            <RowDefinition Height="50" />
        </Grid.RowDefinitions>
        <Button
            Grid.Row="0"
            Click="Load_Click"
            Content="Load Image" />

        <Image x:Name="image" Grid.Row="1">
            <Image.Effect>
                <shader:IntensitySaturationEffect
                    BaseIntensity="{Binding ElementName=sliderIntensity, Path=Value}"
                    BaseSaturation="1"
                    BloomIntensity="1"
                    BloomSaturation="{Binding ElementName=sliderSaturation, Path=Value}" />
            </Image.Effect>
        </Image>

        <Grid Grid.Row="2">
            <WrapPanel HorizontalAlignment="Left" VerticalAlignment="Center">
                <TextBlock Text="Intensity:" />
                <Slider
                    x:Name="sliderIntensity"
                    Width="100"
                    Maximum="1"
                    Minimum="0"
                    Value="0.5" />
                <TextBlock Text="Saturation:" />
                <Slider
                    x:Name="sliderSaturation"
                    Width="100"
                    Maximum="2"
                    Minimum="0"
                    Value="1" />
            </WrapPanel>
            <Button
                Margin="10,0"
                Padding="10"
                HorizontalAlignment="Right"
                VerticalAlignment="Center"
                Click="Save_Click"
                Content="Save" />
        </Grid>
    </Grid>
```
2,C#
```C#
private void Load_Click(object sender, RoutedEventArgs e) {
            OpenFileDialog openFileDialog = new OpenFileDialog();
            if (openFileDialog.ShowDialog().Value) {
                var bitmapImage = new BitmapImage(new Uri(openFileDialog.FileName));
                image.Source = bitmapImage;
            }
        }

        private void Save_Click(object sender, RoutedEventArgs e) {
            DrawingVisual dv = new DrawingVisual() {
                Effect = image.Effect
            };
            using (DrawingContext dc = dv.RenderOpen()) {
                dc.DrawImage(image.Source, new Rect(0, 0, image.Source.Width, image.Source.Height));
            }
            var renderTargetBitmap = new RenderTargetBitmap((int)image.Source.Width, (int)image.Source.Height, 96, 96, PixelFormats.Pbgra32);
            renderTargetBitmap.Render(dv);

            SaveFileDialog saveFileDialog = new SaveFileDialog();
            if (saveFileDialog.ShowDialog().Value) {
                using (var fileStream = new System.IO.FileStream(saveFileDialog.FileName, System.IO.FileMode.Create)) {
                    var encoder = new PngBitmapEncoder();
                    encoder.Frames.Add(BitmapFrame.Create(renderTargetBitmap));
                    encoder.Save(fileStream);
                }
            }
        }
```
3.Comparing UI and Files(The left side shows the saved results, and the right side shows the UI display)
![image](https://github.com/dotnet/wpf/assets/23449064/fad0dcbe-869d-44b0-b21c-301f5edeb47b)

### Expected behavior

UI and file consistency

### Actual behavior

UI and file inconsistency

### Known Workarounds

No solution
The methods I have tried:
Using the DropShadowEffect that comes with WPF    √

But WPF does not have its own saturation brightness effect......

### Other information

I have uploaded the code to github：https://github.com/BigHeadDev/CustomShaderEffectTest

**Comment by akon47** [comment]
This may be a pixelshader version issue. In my experience, the RenderTargetBitmap needs to be version 2.0 for the pixelshader to be applied to the RenderTargetBitmap. Anything higher than that will not be applied on save.

**Comment by BigHeadDev** [comment]
> This may be a pixelshader version issue. In my experience, the RenderTargetBitmap needs to be version 2.0 for the pixelshader to be applied to the RenderTargetBitmap. Anything higher than that will not be applied on save.

Wow! That is great! You are my god, thank you very much

**Comment by miloush** [comment]
Great you figured it out, shouldn't we try to fix this though so that RTB supports higher versions as well or at least outputs some warning in the debug output?

**Comment by BigHeadDev** [comment]
> Great you figured it out, shouldn't we try to fix this though so that RTB supports higher versions as well or at least outputs some warning in the debug output?

Yes, you're right. I don't think we should compromise on the PixelShader version, but rather let WPF embrace PixelShader-3
