### ISSUE TITLE
A11y_.NET Core_WPF_DatabindingDemo_ListofProducts_Resize: In 200% zoom, the content under "List of items for sales" are getting truncated. 

### ISSUE THREAD

**Issue by v-inanda** [dotnet/wpf#7862]
### Description

“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS;#A11yTCS;#BM_.NET Core[WPF]_Win32_May23;#.NET Core;#A11ySev2;#WCAG1.4.4;#DesktopApp;#Win11;#Zoom;#Benchmark;

### Environment Details:
Application Name: .NET Core
.NET Version: .NET-SDK-8.0.100-preview.4.23260.5
WPF
Operating System: Windows 11 Enterprise 21H2

### Reproduction Steps

1. Launch VS 2022 Preview
2. Navigate to Sample Applications and right-click on the "DatabindingDemo" and click on build.
3. Then right click on "DatabindingDemo" then Click on Debug-->Start New Instance.
4. "List of products" screen should open.
5. Zoom the screen to 200% using Text Size and observe that the content under "List of items for sales" are getting truncated in 200% zoom. 

### Expected behavior

In 200% zoom, the content under "List of items for sales" should not getting truncated. All the contents should completely visible.

### Actual behavior

In 200% zoom, the content under "List of items for sales" are getting truncated. The texts are not completely visible.

![A11y_ NET Core_WPF_DatabindingDemo_ListofProducts_Resize](https://github.com/dotnet/wpf/assets/91525824/826feee9-07f7-46f2-9162-e105024f2402)

### Impact

Users with low vision who zoom the page for better visibility will face difficulty if the content of "List of items for sales" are getting truncated.

**Comment by harshit7962** [comment]
Updated the code to fix the issue. Kindly fetch the new code and test for the same.
Merged PR at: https://github.com/microsoft/WPF-Samples/pull/490/files

**Comment by v-inanda** [comment]
@harshit7962 Verified the issue and it is fixed. Hence, closing the bug.

![res](https://github.com/dotnet/wpf/assets/91525824/9bd144a8-d8cc-4ba3-9b25-d4f18d23073f)
