### ISSUE TITLE
A11y_.NET Core_WPF_DatabindingDemo_ListofProducts_Add product listing_Resize: In 200% zoom, the content under "Item for sale" are getting truncated.

### ISSUE THREAD

**Issue by v-inanda** [dotnet/wpf#7863]
### Description

“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS;#A11yTCS;#BM_.NET Core[WPF]_Win32_May23;#.NET Core;#A11ySev2;#WCAG1.4.4;#DesktopApp;#Win11;#Zoom;#Benchmark;

### Environment Details:
Application Name: .NET Core
.NET Version: .NET-SDK-8.0.100-preview.4.23260.5
WPF
Operating System: Windows 11 Enterprise 21H2

### Pre-Requisites:

1. Open settings, tab till Display and press enter.
2. Tab till Scale and press enter.
3. Tab till Text Size and press enter.
4. Zoom the screen to 200% using Text Size.

### Reproduction Steps

1. Launch VS 2022 Preview
2. TAB to Sample Applications and right-click on the "DatabindingDemo" and click on build.
3. Then right click on "DatabindingDemo" then Click on Debug-->Start New Instance.
4. "List of products" screen should open.
5. TAB to "Add product" button and click on it.
6. Zoom the screen to 200% and observe that the content under "Item for sale" are getting truncated in 200% zoom.

### Expected behavior

In 200% zoom, the content under "Item for sale" should not getting truncated. All the contents should completely visible.

### Actual behavior

In 200% zoom, the content under "Item for sale" are getting truncated. The texts are not completely visible.

![A11y_ NET Core_WPF_DatabindingDemo_ListofProducts_Add product listing_Resize](https://github.com/dotnet/wpf/assets/91525824/3a776239-0ffc-4d2a-ade7-e4bbd96d7a89)

### Impact

Users with low vision who zoom the page for better visibility will face difficulty if the content of "Item for sale" are getting truncated.

**Comment by miloush** [comment]
Where are these demo applications coming from? All the accessibility issues we are getting seem to be because the demos are of very poor quality rather than issues in WPF. I am concerned that these are the samples we are giving out to people to follow.

**Comment by v-inanda** [comment]
@miloush We are using this link https://github.com/microsoft/WPF-Samples to install the WPF sample.

**Comment by harshit7962** [comment]
Updated the code to fix the issue. Kindly fetch the new code and test for the same.
Merged PR at: https://github.com/microsoft/WPF-Samples/pull/492

**Comment by merriemcgaw** [comment]
@v-inanda please retest with the new sample.

**Comment by v-inanda** [comment]
@harshit7962 Verified the issue and it is fixed. Hence, closing the bug.

![add p](https://github.com/dotnet/wpf/assets/91525824/9841d545-74ff-44e5-b42c-06f1a9de7efe)
