### ISSUE TITLE
InputEventArgs.Timestamp field is static and shared by all instances

### ISSUE THREAD

**Issue by hughbe** [dotnet/wpf#7887]
### Description

`InputEventArgs.Timestamp` field description is "Gets the time when this event occurred": https://learn.microsoft.com/en-us/dotnet/api/system.windows.input.inputeventargs.timestamp?view=windowsdesktop-8.0

An `InputEventArgs` is created using the constructor `InputEventArgs(InputDevice device, int timestamp)`:
https://github.com/dotnet/wpf/blob/32d08ffa22a0e42730e14efd27d4b2424c401d5c/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputEventArgs.cs#L30-L36

The `InputEventArgs.Timestamp` property is implemented as an accessor to an underlying field
https://github.com/dotnet/wpf/blob/32d08ffa22a0e42730e14efd27d4b2424c401d5c/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputEventArgs.cs#L51-L54

However, the field `_timestamp` is `static`: https://github.com/dotnet/wpf/blob/32d08ffa22a0e42730e14efd27d4b2424c401d5c/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputEventArgs.cs#L74

This means that it is shared between Timestamp instances. As in the test below, when you create a new `InputEventArgs`, it overrides the `Timestamp` property of all other previously created instances.

This can't be correct behaviour. The fix would be to make the field non `static`.

I can submit a fix if approved.

### Reproduction Steps

Consider the following test:
```cs
[StaFact]
public void Timestamp_GetDifferentInstances_ReturnsExpected()
{
    var e1 = new InputEventArgs(Mouse.PrimaryDevice, 0);
    Assert.Equal(0, e1.Timestamp);

    var e2 = new InputEventArgs(Mouse.PrimaryDevice, 1);
    Assert.Equal(0, e1.Timestamp); // !FAILS HERE!
    Assert.Equal(1, e2.Timestamp);
}
```

### Expected behavior

The test passes. `e1.Timestamp != e2.Timestamp`

### Actual behavior

The test fails:
```
  Failed System.Windows.Input.Tests.InputEventArgsTests.Timestamp_GetDifferentInstances_ReturnsExpected [7 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 0
Actual:   1
     at System.Windows.Input.Tests.InputEventArgsTests.Timestamp_GetDifferentInstances_ReturnsExpected() in InputEventArgsTests.cs:line 33
```

**Comment by singhashish-wpf** [comment]
@hughbe Thanks for the report! This looks like a mistake in the code, please submit a PR, and I will get tested.
