### ISSUE TITLE
Unexpected UIA TextRange navigation results when moving through hyperlink UI hosted in a RichTextBox

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#789]
Copied from VSO ID 607015

Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 **Problem description:**
Unexpected UIA TextRange navigation results when moving through hyperlink UI hosted in a RichTextBox
 
 **Repro:**

Steps to reproduce:

1. Create a new WPF in VS, and add the following XAML:

<RichTextBox VerticalAlignment="Center" HorizontalAlignment="Center" FontSize="14">

    <FlowDocument>

        <Paragraph>First <Bold>Second</Bold> Third <Hyperlink>This is a link</Hyperlink> Final</Paragraph>

    </FlowDocument>

</RichTextBox>

2. Run the app.
3. Point the Keros For Desktop tool or Inspect SDK tool at the text in the app.
4. Use the tool's text navigation functionality to move through the text by format.
5. Move through the text as expected up to moving onto the hyperlink. 
6. Try to move beyond the hyperlink.

Result: The tool stays at the hyperlink.
Expected. The tool moves to the text following the hyperlink, just as it does with similar text in Wordpad or Word.

This bug was logged in response to the JAWS screen reader becoming unresponsive when interacting with the UI in the above app, and also at similar WPF UI in VS 2017.

**Comment by anjali-wpf** [comment]
@grubioe Could you please share a screen recording video showing how to reproduce this issue at my end?
