### ISSUE TITLE
Image control cannot display picture using relative uri

### ISSUE THREAD

**Issue by CodingOctocat** [dotnet/wpf#7899]
### Description

The `Image` control has a strange problem, I put the image in the resources folder, it looks like this: `/Resources/img1.png`, then right click on the image `property>build action>resource`, after running the program the image is not displayed, then use the `pack uri`, after running the program the image is displayed normally, then change to the `Relative uri`, after running the program Image The image is displayed normally after running the program.

### Reproduction Steps

1. `<Image Source="/Resources/img1.png" />`
2. Set img1.png build action `Resource`.
3. Run app, image not displayed.
4. `<Image Source="pack://application:,,,/Resources/img1.png" />`
5. Run app, image displayed.
6.  Restore Code `<Image Source="/Resources/img1.png" />`
7. Run app, image displayed!!!

### Expected behavior

`Relative uri` can display images normally when first set.

### Actual behavior

You must switch to the `Pack uri` and then restore the `Relative uri` to display the image.

### Configuration

- .NET7 x64
- Ver	Windows 11 Pro
- Ver	22H2
- Date	‎2022/‎10/‎5 ‎星期三
- OS Ver	22621.1778
- Windows Feature Experience Pack 1000.22642.1000.0

**Comment by lindexi** [comment]
@CodingOctocat Can I know your VisualStudio version? I didn't repeat your question with VisualStudio 2022 17.6.2

**Comment by CodingOctocat** [comment]
@lindexi My VS version is also17.6.2.

![动画](https://github.com/dotnet/wpf/assets/7220248/93f76b5d-9010-413d-9dc2-bac06a6c0bb2)

**Comment by miloush** [comment]
As asked in the issue template, attaching a demo project would be helpful, particularly to see the build action on the image file.

**Comment by lindexi** [comment]
I think it's a VisualStudio problem. Can you try clean the code and re-build it to test?

**Comment by CodingOctocat** [comment]
> I think it's a VisualStudio problem. Can you try clean the code and re-build it to test?

I tried cleaning up the code and rebuilding it, but the problem persists, the image display behavior must first be done with `pack uri` and then `relative uri` to work correctly, and each image must be done this way.

**Comment by lindexi** [comment]
@CodingOctocat Could you commit the code and then use `git clean -xdf` to clean up the code?

**Comment by miloush** [comment]
If you are suspecting the build process, try building from command line outside of VS.

**Comment by lindexi** [comment]
> If you are suspecting the build process, try building from command line outside of VS.

1. Open `Developer Command Prompt for VS 2022` in start menu
2. Enter your code folder and Run the `msbuild -restore` command

**Comment by CodingOctocat** [comment]
I suspect this may be a VS issue, I just rebuilt the project and it actually displays the images properly.

**Comment by dipeshmsft** [comment]
If you believe this is a VS issue, you may open an issue here - https://developercommunity.visualstudio.com/VisualStudio/report
