### ISSUE TITLE
Wpf application not closing properly (.NET 8)

### ISSUE THREAD

**Issue by Rustaud** [dotnet/wpf#7915]
Hello,

I have a problem with an application (WPF) that works perfectly with version 7 of .NET. The particularity of this application is that the main form opens many independent windows and each window creates a few threads.
With version 8 (preview 4) from time to time, when I quit my application (Application.Current.Shutdown()) from the main form, the application seems to close normally but if I restart it I have problems because during the previous shutdown, the main window is invisible but remains active. Note that all other windows seem to close normally. After some research, I've realised that when the shutdown doesn't work properly, the application's main window goes into the background process in the task manager. Apart from this problem, I haven't encountered any anomalies, at least in appearance, when my application is running with .NET 8. I should point out that the anomaly is intermittent and occurs both when using the runtime installed on the PC and when the application is deployed in standalone mode. All the PCs tested have the same problem (Windows 10, Windows 11).

Best regards,
Thierry 
I'm republishing this post, amended, published by mistake in the dotnet/Winforms section.

**Comment by rchauhan18** [comment]
Hey @Rustaud 
Could you please provide us minimal repo of the above issue.
Also, please edit your issue using the issue template.

**Comment by Rustaud** [comment]
Works with .NET 8 preview 5
