### ISSUE TITLE
Window Visibility Property Binding

### ISSUE THREAD

**Issue by DinnerGit** [dotnet/wpf#7919]
### Description

I created a simple WPF program using the Prism framework. The functionality of the program is to hide the window when a button is clicked. In the ViewModel, I defined 'IsVisible' and bound it to the 'Visibility' property of the Window in the View. The mode is set to 'OneWay', and I also defined the corresponding converter. However, when I click the button and set 'IsVisible' to false in the ViewModel, the window doesn't disappear as expected. On the other hand, when I bind it to the 'Visibility' property of the Button, it works correctly

### Reproduction Steps

![image](https://github.com/dotnet/wpf/assets/100114486/1aad1bb4-1ccb-4eb8-a30b-eaa1fcb76ef5)

![image](https://github.com/dotnet/wpf/assets/100114486/b65617eb-431b-45f9-9c48-49b4c4fd4efc)

![image](https://github.com/dotnet/wpf/assets/100114486/19e31e9d-ac2c-4873-bb63-763a91fa4f41)

### Expected behavior

The window is hidden

### Actual behavior

The window is not hidden

### Known Workarounds

Setting it to TwoWay achieves the desired result, but using OneWay is sufficient in the logic.

### Configuration

.NET6.0 WPF
Prism 8.1.97
Windows 10

**Comment by DinnerGit** [comment]
> Please provide a demo project. Resporting an issue in English would increase chances of response.

Thank you for your suggestion. I have now revised it and described it in English.

**Comment by miloush** [comment]
I cannot reproduce this, works as expected, you might need to share your project.

**Comment by DinnerGit** [comment]
[BindingDemo.zip](https://github.com/dotnet/wpf/files/11734771/BindingDemo.zip)

**Comment by DinnerGit** [comment]
> I cannot reproduce this, works as expected, you might need to share your project.

The attachment is my demo. Thank you.

**Comment by miloush** [comment]
Thank you. When `Window.Show` is called, it sets `Visibility` to `Visible`, removing your databinding. However, when you either set the `DataContext` before the `InitializeComponent` or when you use two-way binding, you set `Visibility` to `Visible` before `Window.Show` is called, effectively making the window show without it setting the property.

**Comment by miloush** [comment]
Calling `Show` calls `UpdateVisibilityProperty` which sets the dependency property:

https://github.com/dotnet/wpf/blob/7e8bd2118e4260a8440fa78821dc6b22595e7f05/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs#L5306

Setting the DP to a constant value will replace the binding. The `_visibilitySetInternally` flag is only to avoid trying to show the window twice.

Basically you need to apply your binding after the window is shown to avoid this, or do not use the `Show` method.

If this is to be improved on WPF side, the line above needs to be changed to `SetCurrentValue`. It is not 100% risk free, it changes the existing behavior.
