### ISSUE TITLE
contextmenu disappears when a WPF usercontrol is displayed in a WinForm Form (using an element host)

### ISSUE THREAD

**Issue by stivoberlin** [dotnet/wpf#7960]
### .NET version

.NET 6.0 
.NET 7.0 
Tested on both

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

.net 4.8

### Issue description

There is a bug when a WPF usercontrol is displayed in a Winform Form (using an element host).
If this WPF usercontrol has a context menu, and the scaling in Windows Display Settings are different than 100% (125% for exemple). Then if we try to pass the mouse over the menu items, they disappear… It makes impossible for the user to select an item in the menu (making this a blocking issue for one of our project).

This issue is only appearing if the WPF usercontrol is used in a WinForms application. If the same control is copied in a full WPF app, there is no problem. I guess there is some mechanism with the scaling and WinForms that has a small thing to fix.

![image](https://github.com/dotnet/winforms/assets/1432610/8447c550-0f14-4790-a97a-8afb9080e077)

### Steps to reproduce

I have created a small demo project under : 
[https://github.com/stivoberlin/WinFormsAppSetHighDpiModeBug2](https://github.com/stivoberlin/WinFormsAppSetHighDpiModeBug2)

If you want to create a new project from scratch : 
Create a WinForm Application, with a winforms form
Create a WPF Usercontrol with a context menu and some menu items
Put the WPF Usercontrol in the WinForms Form
Set your windows scaling to 125% (in the Windows Display Settings for the screen)
Start the app, and try to select the last item of the context menu. They disappear.

**Comment by miloush** [comment]
The [System.Windows.Forms.Application.SetHighDpiMode](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.application.sethighdpimode) does not exist on .NET Framework and without it the issue does not reproduce, so I wouldn't call it a regression from .NET Framework.

**Comment by miloush** [comment]
Is there a a manifest equivalent of setting `DpiUnawareGdiScaled`?

**Comment by merriemcgaw** [comment]
> Is there a manifest equivalent of setting `DpiUnawareGdiScaled`?

@dreddy-work should be able to tell you. And I wonder what happens if the app is set to DPI unaware? WinForms in .NET defaults to System Aware, but .NET Framework was DPIUnaware.

**Comment by dreddy-work** [comment]
> The [System.Windows.Forms.Application.SetHighDpiMode](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.application.sethighdpimode) does not exist on .NET Framework and without it the issue does not reproduce, so I wouldn't call it a regression from .NET Framework.

This shows you are running your app in .NET Framework as DpiUnAware.  in .NET 6.0 and above versions, you could use [ApplicationHighDpiMode](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props-desktop#applicationhighdpimode) project property to set mode to `DpiUnAware`.  `DpiUnawareGdiScaled` mode in WinForms is not fully supported yet and if used, you may see some scaling issues.

**Comment by miloush** [comment]
This does not really answer the manifest question. Anyway, the issue reproduces only for `DpiUnawareGdiScaled`, all other values work as expected. I don't know what `DpiUnawareGdiScaled` does exactly, but since @dreddy-work suggests this mode is not fully supported for Winforms, I would be inclined to leave it at that. @stivoberlin can you use any other dpi mode?

**Comment by miloush** [comment]
Following https://blogs.windows.com/windowsdeveloper/2017/05/19/improving-high-dpi-experience-gdi-based-desktop-apps/ I take it I can set `DpiUnawareGdiScaled` on .NET Framework projects using the _System (Enhanced)_ compatibility setting in properties and I confirm this reproduces for .NET Framework too.

**Comment by Ashley-Li** [comment]
> @Olina-Zhang - could you please investigate in what release of .NET this regressed? 

@Tanya-Solyanik This is a not regression issue in .NET. It can repro .NET Core 3.1 & .NET 5.0 & .NET 6.0 & .NET 7.0 & .NET 8.0.  
![7960](https://github.com/dotnet/wpf/assets/56664234/b8d4cb7d-ee2a-4a0e-9472-007d5a760f4d)

In Framework4.8, set app is not PerMonitorV2 mode(add key="DpiAwareness" value="false"), the issue cannot repro.

**Comment by stivoberlin** [comment]
> > The [System.Windows.Forms.Application.SetHighDpiMode](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.application.sethighdpimode) does not exist on .NET Framework and without it the issue does not reproduce, so I wouldn't call it a regression from .NET Framework.
> 
> This shows you are running your app in .NET Framework as DpiUnAware. in .NET 6.0 and above versions, you could use [ApplicationHighDpiMode](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props-desktop#applicationhighdpimode) project property to set mode to `DpiUnAware`. `DpiUnawareGdiScaled` mode in WinForms is not fully supported yet and if used, you may see some scaling issues.

[ApplicationHighDpiMode](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props-desktop#applicationhighdpimode)  is not working well as the text seems to be scaled way more than the rest. And this, eventough if we choose DpiUnaware.

The only working solution is to put : 

`  <application xmlns="urn:schemas-microsoft-com:asm.v3">
	  <windowsSettings>
		  <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">false</dpiAware>
	  </windowsSettings>
  </application>`

in the app.manifest.

But this raise the warning : 
`Remove high DPI settings from ...\My Project\app.manifest and configure via 'HighDpiMode' property in Application Framework
`
And the HighDpiMode has the same problems as ApplicationHighDpiMode.

Therefore the only working alternative is noted as obsolete. I am worried that this option will no more work in the future and we will be stuck with failing alternatives. Therefore a fix - or another solution - will be greatly appreciated.

**Comment by stivoberlin** [comment]
> This does not really answer the manifest question. Anyway, the issue reproduces only for `DpiUnawareGdiScaled`, all other values work as expected. I don't know what `DpiUnawareGdiScaled` does exactly, but since @dreddy-work suggests this mode is not fully supported for Winforms, I would be inclined to leave it at that. @stivoberlin can you use any other dpi mode?

Unfortunately our customers are buying screens with bigger resolution all the time and they are not satisfied with a 100% scaling. And changing the dpi mode are not solving the problems. Other problems arise, like the font being scaled more than the forms.

**Comment by Tanya-Solyanik** [comment]
>Therefore the only working alternative is noted as obsolete. I am worried that this option will no more work in the future and we will be stuck with failing alternatives.

This option is implemented on the windows level, we will not be able to disable it. This is not the preferred option for winforms only because we plan to support other option in the designer.
Can you use Application.SetHighDpiMode(HighDpiMode.SystemAware); or comment out SetHighDpiMode line from the Main and thus let WPF control force your application into SystemAware mode?

**Comment by pchaurasia14** [comment]
@stivoberlin - Could you please try the steps mentioned above and let us know if this solves your issue.
