### ISSUE TITLE
Build script fails building with Visual Studio 2019 Preview 1 because script is looking for MsBuild in the wrong place

### ISSUE THREAD

**Issue by Wintermute21** [dotnet/wpf#80]
* .NET Core Version: (3.0 Preview1)
* Windows version: (Windows 10 build 18290.1000)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 
 **Problem description:**
 When cloning and building using Visual Studio 2019 Preview 1, build.cmd fails by not looking for NuGet.exe in the correct directory for Preview. 
Line 183 of eng/common/tools.ps1 has   $script:buildDriver = Join-Path $vsInstallDir "MSBuild\15.0\Bin\msbuild.exe" where for Preview1 it should be   $script:buildDriver = Join-Path $vsInstallDir "MSBuild\Current\Bin\msbuild.exe"
 **Actual behavior:** 
 build fails with NuGet.exe not found
 **Expected behavior:**
 build succeeds and restores packages correctly.
 **Minimal repro:**
 clone and build under 2019 Preview 1.

**Comment by Wintermute21** [comment]
I should note also that this issue does *not* occur with the WinForms repo. That build script appears to handle both situations (e.g dealing with 2017 and 2019 paths) correctly.

**Comment by vatsan-madhavan** [comment]
@chcosta - would this be something that Arcade SDK would need to fix?

This is related to https://github.com/Microsoft/msbuild/issues/3778

Cc @ericstj

**Comment by karelz** [comment]
Looks like WPF repo does not have this Arcade change: https://github.com/dotnet/arcade/pull/1409

**Comment by rladuca** [comment]
@karelz DARC PRs were failing the CI build as we transitioned to open.  The next PR should pick up all related changes and pass the new CI build, giving us the appropriate changes.
See #44 .

**Comment by Wintermute21** [comment]
potentially dumb question, but since I manually changed the script to fix it, should I revert that or just do a git pull and it will overwrite what I changed with the fix?

**Comment by rladuca** [comment]
@Wintermute21 If you've done work on top of a commit with your fix, you can interactively rebase on top of the latest update once it arrives and just delete that commit.  

Otherwise, just be sure you don't commit your fix.  Then you can pull the latest update when it arrives and resolve the conflict to pick up the latest.

**Comment by Wintermute21** [comment]
@rladuca Yeah, I hadn't committed my change so I'll just let Git overwrite it. 
Thanks. 
Btw, this is my first issue in an official MS repo and I appreciate how responsive people have been, especially so late at night. <3

**Comment by rladuca** [comment]
@Wintermute21 It's my first official MS repo that I'm directly involved with, excitement all around!

**Comment by Wintermute21** [comment]
it's an amazing time to be a .NET dev and it keeps getting better.

**Comment by rladuca** [comment]
#83 failed.  I'll start to look at it when I get in this morning.  @vatsan-madhavan FYI.  We have to figure out what is going on with the latest DARC PRs.

**Comment by rladuca** [comment]
#83 now passes after some changes from @vatsan-madhavan .  @Wintermute21 Can you retry your build without your workaround and confirm you're good to go?

**Comment by Wintermute21** [comment]
Sure, let me get latest and give it a shot. One sec.

**Comment by Wintermute21** [comment]
@rladuca I just did a git pull and it does work out of the box now with the latest changes. 👍

**Comment by rladuca** [comment]
@Wintermute21 Closing as everything seems to work now.
