### ISSUE TITLE
The specified RuntimeIdentifier 'win-' is not recognized

### ISSUE THREAD

**Issue by Yoonwoo** [dotnet/wpf#8011]
### Description

I finally succeeded in building wpf locally with build.cmd with no errors. 

Then as per documentation put the WpfRepoRoot and <Import Project="$(WpfRepoRoot)\eng\wpf-debug.targets" />

It comes up with this error

Error	NETSDK1083	The specified RuntimeIdentifier 'win-' is not recognized.	WpfApp2	C:\Program Files\dotnet\sdk\7.0.304\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	90	

Project file:

  <Project Sdk="Microsoft.NET.Sdk">
  
    <PropertyGroup>
      <OutputType>WinExe</OutputType>
      <TargetFramework>net7.0-windows</TargetFramework>
      <Nullable>enable</Nullable>
      <UseWPF>true</UseWPF>
    </PropertyGroup>
	  <PropertyGroup>
		  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
		  <WpfRepoRoot>C:\Code2\wpf</WpfRepoRoot>
	  </PropertyGroup>
	  <Import Project="$(WpfRepoRoot)\eng\wpf-debug.targets" />
  </Project>

### Reproduction Steps

build wpf and make sample wpf app

### Expected behavior

compiles normally

### Actual behavior

Error	NETSDK1083	The specified RuntimeIdentifier 'win-' is not recognized.

**Comment by Yoonwoo** [comment]
Thanks, that fixed that. For some reason if I make a WPF project using dotnet command and set it up, it fails with "you must install .NET desktop runtime", but making a project normally with visual studio works.

All of this was so I can step into WPF code, which I seem to have finally managed to do with all variables not optimized away.

**Comment by singhashish-wpf** [comment]
@Yoonwoo can we close this now? Let us know if you find any issues in the documentation.
