### ISSUE TITLE
WPF Control embedded in Win32 program does not resize with parent QWidget

### ISSUE THREAD

**Issue by xingwozhonghua126** [dotnet/wpf#8020]
### .NET version

PS C:\Users\fab\Desktop> dotnet --info
.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.302\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
P

### Did it work in .NET Framework?

Yes

### Issue description

Creating Dynamic Resizing for WPF Controls Embedded in Win32 Programs

https://github.com/dotnet/docs-desktop/blame/9bee5c22944ff78a055e50c45242cf8a3baab502/dotnet-desktop-guide/samples/snippets/cpp/VS_Snippets_Wpf/Win32HostingWPFPage/CPP/Win32HostingWPFPage.cpp#L267-L268

### Steps to reproduce

Hello Maintainers,

I am working on a project where I'm trying to integrate a WPF Control into a Win32 program. The parent window of this control is a `QWidget`. It works to a certain extent, but I am currently having an issue with the resizing of the WPF Control: it does not resize when the parent QWidget resizes.

Environment:
- OS: [Include the version of your operating system here]
- Qt version: [Include the version of the Qt framework you are using]
- .NET Framework: [Include the version of the .NET Framework you are using]
- Visual Studio: [Include the version of Visual Studio you are using]

Expected behaviour:
When I resize the parent `QWidget`, I expect the embedded WPF Control to resize accordingly to maintain its relative size and position.

Actual behaviour:
The embedded WPF Control does not resize when the parent `QWidget` resizes. It just keeps its initial size.

I looked around for solutions online, searched in the past issues of this GitHub project, and tried several potential solutions, but nothing seems to work in this case. Here is the code snippet for how I'm embedding the WPF control:

```
void CommonPlugin::AdjustWPFWnd(HWND parent, int x, int y, int width, int height, Object ^ object)
{
	if (static_cast<System::Windows::Interop::HwndSourceParameters ^>(m_sourceParams) == nullptr)
	{
		m_sourceParams =
		    gcnew System::Windows::Interop::HwndSourceParameters("WPF"); 
		m_sourceParams->PositionX = x;
		m_sourceParams->PositionY = y;
		m_sourceParams->Height = height;
		m_sourceParams->Width = width;
		m_sourceParams->ParentWindow = IntPtr(parent);
		m_sourceParams->UsesPerPixelOpacity = true;
		m_sourceParams->WindowStyle = 0x10000000L | 0x40000000L; // WS_VISIBLE | WS_CHILD
		m_sourceParams->RestoreFocusMode = System::Windows::Input::RestoreFocusMode::None;
		m_sourceParams->AcquireHwndFocusInMenuMode = false;
		System::Windows::Interop::HwndSourceParameters^ sourceParams = m_sourceParams;

		m_source = gcnew System::Windows::Interop::HwndSource(*sourceParams);
		if (static_cast<System::Windows::Interop::HwndSource ^> (m_source) == nullptr)
			return;
		m_source->CompositionTarget->BackgroundColor = System::Windows::Media::Brushes::White->Color;
		m_source->RootVisual = (System::Windows::Media::Visual ^) object;
	}
	else
	{
		m_context->Reset();
		m_context->PreferredSize = QSize(width, height);
		qDebug() << __FUNCTION__ << " width:" << width << " height:" << height;
		m_sourceParams->SetSize(width, height);
		System::Windows::FrameworkElement ^ fe =
		    dynamic_cast<System::Windows::FrameworkElement ^>(m_source->RootVisual);
		if (fe != nullptr)
		{
			fe->Width = width;
			fe->Height = height;
			fe->InvalidateMeasure();
			fe->InvalidateArrange();
			fe->Measure(System::Windows::Size(width, height));
			fe->Arrange(System::Windows::Rect(0, 0, width, height));
		}
	}
}

void CommonPlugin::onResizeEvent(int width, int height)
{
	qDebug() << __FUNCTION__ << " width:" << width << " height:" << height;
	if (m_w)
	{
		AdjustWPFWnd((HWND)m_w->winId(), 0, 0, width, height - 10, m_gccontext->ViewerContent);
	}
}
```

I'm not sure if I'm missing something in regard to hooking and handling the resize event. Any assistance or pointers about how to get the WPF Control to resize along with its parent QWidget would be greatly appreciated. Thank you for your time and consideration.

Best regards,
shijie.chen

**Comment by singhashish-wpf** [comment]
@xingwozhonghua126 
Do we have a minimal repro for this bug?
