### ISSUE TITLE
Support for RegisterPropertyChangedCallback

### ISSUE THREAD

**Issue by LokiMidgard** [dotnet/wpf#803]
UWP's DependencyObject has a [`RegisterPropertyChangedCallback`](https://docs.microsoft.com/de-de/uwp/api/windows.ui.xaml.dependencyobject.registerpropertychangedcallback?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(Windows.UI.Xaml.DependencyObject.RegisterPropertyChangedCallback)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue) that enables you to be notified when a DependencyProperty changes and can be applied to any DependencyProperty.

I'm not aware of a way to achieve this in WPF without explicitly implementing events. Which adds even more boilerplate code the already very verbose DependencyProperty declaration. 

And if you are not owner of the class, it gets complicated.
You could inhere the object and override the metadata, or create a binding to a property that fires an event.

**Comment by weltkante** [comment]
You can use DependencyPropertyDescriptor to get access to change notifications. Examples aren't too hard to find, e.g. [this](https://stackoverflow.com/questions/8482923/how-to-subscribe-to-change-dependencyproperty) or [that](https://stackoverflow.com/questions/4764916/listen-to-changes-of-dependency-property)

Alternatively you can use a binding to forward the property to your own object, where you can register a natural PropertyChanged event on your own property.

**Comment by LokiMidgard** [comment]
Thank you. I knew of the binding approach. But I wasn't aware of `DependencyPropertyDescriptor` and it looks like what I was looking for :)
