### ISSUE TITLE
WriteableBitmap Lock() is fast at specific sizes, very slow at other sizes

### ISSUE THREAD

**Issue by AngryCarrot789** [dotnet/wpf#8045]
### Description

I have a control that spans most the window size, and when I make it span both my monitors to around 3000px width, the render times (which involves Locking, modifying the back buffer's raw pixels, adding dirty rect, then unlocking and finally drawing to the drawing context) are really bad around 200ms per render. 

However, I figured out if I resize the window such that the WriteableBitmap's pixel width and height is 3353x909, 3329x909, 1617*932 or 3302x909 (and there's probably plenty more of these "fast" resolutions), the render times are very fast; Lock() takes practically no time at all

I profiled this by getting the system time (with the help of the Stopwatch.GetTimestamp function) before and after the render, and I narrowed it down to the WriteableBitmap's Lock() call

I believe it's this line specifically that's causing the wait time: [WriteableBitmap.AcquireBackBuffer()](https://github.com/dotnet/wpf/blob/11b45badc1a514ac9a3311145316b2e7cb543eae/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/WriteableBitmap.cs#L1067C49-L1067C49)
The caller is waiting for the render thread to complete a copy of the bitmap I guess?

### Reproduction Steps

Have a WriteableBitmap with the size 3352x909 (1 pixel less than the one I mentioned above), and Lock() should take around 100-200ms. But when you increase the width by 1 pixel, Lock() should take less than a millisecond. 

The render most likely has to be caused by mouse input (in my case, mouse movement while the mouse is captured), which calls `InvalidateVisual`, causing `OnRender` to be invoked eventually and that's where you lock/unlock the bitmap. I tried using a task+dispatcher to constantly decrease the size of the window, but the Lock() time was always roughly constant. However when I did the same but also provided the mouse inputs that invalidate the render, I saw that some resolutions were causing Lock() to take a long time

### Expected behavior

There shouldn't be specific resolutions (nearby to each other) that perform well. 3352x909 and 3353x909 should perform relatively the same, but they don't

### Actual behavior

Specific resolutions (like 3352x909) cause Lock() to perform horribly, whereas 3353x909 causes Lock() to take almost no time at all

### Regression?

I tried this in .NET Framework 4.7.2's version of WPF and I got this behaviour. I also tried this in WPF for .NET 6.0 (targeting windows, version 7.0 in visual studios) and also got the same behaviour. The .NET 6.0's "slow" performance was much better than .NET Framework version, but there's still a noticeable frame rate change between the "slow" and "fast" resolutions

### Known Workarounds

I guess clamping the size of the WriteableBitmap to known "fast" resolutions would work

### Configuration

- Tried both .NET Framework 4.7.2 and .NET Core 6.0
- Windows 10
- Tried both x64 and x86

### Other information

I used a Task to increase the window size, then awaited a 35ms delay and captured the last time it took to Lock(), and also recorded the width of the window and bitmap at that time. Here is what it collected, it might be slightly incorrect at times because I was just constantly moving my mouse:
https://pastebin.com/df7NFp4r

And this is the code I used:
```
await Task.Delay(2500);
editor.Width = 3500;
editor.Height = 1000;
// Bitmap's height was 949;
editor.Top = 20;
editor.Left = -1900;
for (int i = 0; i < 200; i++) {
    editor.Width--;
    await Task.Delay(35);
    long time = editor.OGLViewPort.PART_RenderTarget.lastLockTime;
    if (time > 0) {
        editor.OGLViewPort.PART_RenderTarget.lastLockTime = 0;
        Debug.WriteLine($"Win width = {Math.Round(editor.ActualWidth, 1).ToString("F1").FitLength(8)} | Bitmap width = {Math.Round(editor.OGLViewPort.PART_RenderTarget.ActualWidth, 1).ToString("F1").FitLength(8)} | Render Time = {Time.TicksToMillis(time).ToString("F2")}");
    }
}
```

I also made a video demo. The darker panel is my view port (rendered with OpenGL. I profiled the OpenGL render and glReadPixels time and they were fine). 
When debugging, it said the size was 3353x909 and it renders at around 50fps. Then I resized the width to 3351 and the render time was much worse. Then after resizing it back to 3353, it renders fine:

https://github.com/dotnet/wpf/assets/32274404/6c45a3aa-06fa-4d96-bc25-cc1ac295c4e1

Edit: It seems like it might have something to do with the greatest common divisor of the width and height being 3... The GCD of 1617x932, 3302x909, 3329x909, 3353x909, 3422x909 and 3425x909 are all 3. Maybe because that's the number of subpixels, which allows the GPU to do some sort of optimisation?

**Comment by lindexi** [comment]
@AngryCarrot789 It looks like this is a DX maximum size limitation issue. But I'm not sure if that's really the problem.

See https://learn.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-resources-limits and https://learn.microsoft.com/en-us/windows/win32/direct3d9/performance-optimizations#texture-size

**Comment by singhashish-wpf** [comment]
@AngryCarrot789 Is it possible to share the minimal repro(complete project)?

**Comment by AngryCarrot789** [comment]
[Yeah sure](https://github.com/AngryCarrot789/R3Modeller)

**Comment by AngryCarrot789** [comment]
Well... I think I figured out what caused it. My app was using the Alt key to activate mouse input, and I noticed that it was showing the, I think, focus visual (the checkerboard outline thing). So I changed the key to CTRL and the lag was pretty much all gone. Then I clicked Alt again to show the focus visual and the lag was back again.

I guess the `StrokeDashArray` feature of rectangles is just incredibly GPU intensive, enough to force WPF to have to wait for the render commands to complete before allowing the bitmap to be locked I guess? I think I might just remove the focus visual for anything that requires using a `WriteableBitmap`

**Comment by lindexi** [comment]
@AngryCarrot789 Is it a similar problem to https://github.com/dotnet/wpf/issues/5874 ?

**Comment by AngryCarrot789** [comment]
I don't think so. My focus visual was defined as:
```
<Style x:Key="FocusVisual">
    <Setter Property="Control.Template">
        <Setter.Value>
            <ControlTemplate>
                <Rectangle Margin="2" SnapsToDevicePixels="true"
                           Stroke="{DynamicResource ABrush.ColourfulGlyph.Static}"
                           StrokeThickness="1" StrokeDashArray="1 2" />
            </ControlTemplate>
        </Setter.Value>
    </Setter>
</Style>
```
And `StrokeDashArray` ends up being used by the `Pen` class' `DashStyle`, so I think it's just because pen dash styles are very render-intensive.
Based on the documentation for the `WriteableBitmap` source code, it might also explain why `Lock()` takes a long time, because it seems like a "copy-forward" command it sent to the render thread at some point, and `Lock()` calls `AcquireBackBuffer` which sits there waiting for the command to finish via the `_copyCompletedEvent` wait handle

**Comment by miloush** [comment]
> I guess the StrokeDashArray feature of rectangles is just incredibly GPU intensive

Does that mean that using a solid rectangle as focus visual does not slow you down?

**Comment by AngryCarrot789** [comment]
Correct

**Comment by ARM830** [comment]
Is it because of the different priority levels of the UI thread that is causing this?

**Comment by AngryCarrot789** [comment]
I launched the app multiple times and got the same results each time, so I guess not

**Comment by lindexi** [comment]
@AngryCarrot789 Can this issues close?

**Comment by AngryCarrot789** [comment]
Yeah. I'm just gonna assume the random FPS boosts at certain width and heights is caused by the focus visual being a certain perfect size that opens up some sort of "efficient" dash array rendering... and if it's not, then I have no idea
