### ISSUE TITLE
Source code for the WPF Calendar control

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#8216]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Source-code-for-the-WPF-Calendar-control/10464077)._

---
This [article](https://learn.microsoft.com/en-us/archive/msdn-magazine/2009/june/customizing-the-new-wpf-calendar-controls) says "All the source code for the Calendar control is downloadable from the CodePlex site".  Where would I find the code these days?

---
#### Feedback Bot on 9/12/2023, 07:42 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by miloush** [comment]
https://codeplexarchive.org/

But otherwise you just search the repo for Calendar... https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Calendar.cs
