### ISSUE TITLE
CSS like style engine

### ISSUE THREAD

**Issue by cuiliang** [dotnet/wpf#8229]
I am reaching out to bring to your attention a potential feature enhancement that could significantly improve the flexibility and user-friendliness of styling in WPF — introducing a CSS-like multi-style application where a single element can be controlled through multiple styles, harmoniously integrated and applied simultaneously.

As you might already know, in CSS, a developer has the luxury to apply multiple styles to a single element; the styles stack, with later styles having the ability to override earlier ones, providing a rich, layered, and finely controlled aesthetic. This facilitates a dynamic and flexible design experience that many developers appreciate.

In WPF, as of now, the styling is primarily controlled through single style resources applied to elements. While this works functionally well, it doesn't offer the level of granular control and layering that a CSS-like multi-style application can potentially offer. The current system requires defining all necessary properties within a single style, sometimes leading to bulky and less maintainable style definitions.

The introduction of a multi-style application system would enable WPF developers to:

Create more modular and maintainable style definitions by allowing the segregation of different stylistic properties into different style resources.
Facilitate a more dynamic and layered design approach, akin to what is currently possible with CSS.
Reduce the complexity of style definitions by avoiding the necessity to define all properties in a single style resource, hence fostering code reusability.
I genuinely believe that introducing a CSS-like multi-style application mechanism in WPF would be a groundbreaking enhancement, elevating the design flexibility to new heights and bringing a much-appreciated feature to the WPF developer community.

I sincerely hope you will consider this feature request for implementation in a future version of WPF. Thank you for your time and consideration.

Looking forward to seeing continued improvements in WPF, making it even more powerful and user-friendly for developers globally.

**Comment by miloush** [comment]
Note that styles in WPF can inherit from each other. Since elements are strongly typed and you need to resolve on which types you are trying to set stuff, I am not quite sure there is enough scenarios in which such feature would be useful enough to add it to the framework itself and increase its learning curve. (as opposed to, for example, a nuget package with markup extension allowing to pick up and combine multiple styles - in fact if there was such a package and it had significant usage, that would be a good evidence for its need and usefulness)

Could you give some practical examples where you would like to use such feature and how it should look like?

**Comment by cuiliang** [comment]
It's harder to learn and use WPF styling than css.

> WPF makes the hard trivial and trivial hard.  [source](https://stackoverflow.com/questions/20073294/change-color-of-button-when-mouse-is-over)

here is some examples.

### 1) Change color of button when mouse is over
**WPF：**  [Answer from stackoverflow](https://stackoverflow.com/a/20073418/3335415)
```xaml
<Button Content="Button" HorizontalAlignment="Left" VerticalAlignment="Bottom" Width="50" Height="50" HorizontalContentAlignment="Left" BorderBrush="{x:Null}" Foreground="{x:Null}" Margin="50,0,0,0">
    <Button.Style>
        <Style TargetType="{x:Type Button}">
            <Setter Property="Background" Value="Green"/>
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="{x:Type Button}">
                        <Border Background="{TemplateBinding Background}">
                            <ContentPresenter HorizontalAlignment="Center" VerticalAlignment="Center"/>
                        </Border>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
            <Style.Triggers>
                <Trigger Property="IsMouseOver" Value="True">
                    <Setter Property="Background" Value="DarkGoldenrod"/>
                </Trigger>
            </Style.Triggers>
        </Style>
    </Button.Style>
</Button>
```
**CSS:**  
```css
.button-class:hover {
  background-color: #808080; 
}

<button class='button-class'>title</button>
```

### 2）relative font size:
Request: make all buttons has font size 150% of container when we have `PrimaryButton`,`DangerButton`,`WarningButton` on same window.
**WPF** ：Define multiple new styles based on `PrimaryButton`,`DangerButton`,`WarningButton`.
**CSS** : `button { font-size: 1.5em }`

### 3）define button styles with variations on different aspect: 
- button sizes: `normal`,`large`,`xsmall`,`xxsmall`  
- background colors: `normal`,`primary`,`success`,`warning`,`danger`, `info`,  `light`, `dark`
- corner styles: `round-5px`,`round-3px`,`round-0px`,
- border style: `bordered`, `borderless`
- text colors: `normal`,`primary`,`success`,`warning`,`danger`, `info`,  `light`, `dark`

**WPF**  We have to make lot's of styles like `LargeDangerRound5pxLightTextButtonStyle`... 

**CSS**  Define classes for each aspect, then mix these classes on button.  `<button class='btn-danger btn-sm bordered round-3px text-light`>button</button>

### 4） styling based on container: 
**WPF**  do not support.
**CSS**   very easy with css selector: `.content-form .btn-delete { background: red } `


I know It will be very hard to impliment such kind of styling system like CSS, but perhaps we can begin to imagine it.

**Comment by miloush** [comment]
1. is a misleading example and the CSS way would not help in any way. The style redefines a template which can be done separately for all buttons, and then the main bit is the trigger, which is pretty much the same in CSS.

2. WPF indeed does not support relative font size or scaling and none of the methods to do it currently are as simple as using a relative unit. #3701 could be treated as such feature request. But if you had a relative unit, then I would think it would work exactly like the css example.

3. That is mainly what I imagined you are asking for. You can make a markup extension that will combine referenced styles.

4. I imagine you could have an attached property and/or style selector that would traverse the tree up and build the style name to reference. This incurs performance penalty, which might or might not be acceptable.


I see some differences on what you can do in CSS vs WPF styles, but not a blocking limitation in a real-world scenario. These two are simply two different technologies and I am not very convinced so far that one should be bended to work like the other (in reality it would be introducing and mainting two separate ways to do styling). If CSS and HTML layout works for your application, then great, Electron and similar technologies are your friend.

**Comment by cuiliang** [comment]
Yes, maybe there is not a blocking limitation in a real-world scenario, but perhaps we can make it easyer to accomplish these common tasks, in any way.

For example: Introduce a `HoverBrush` property , this will reduce most needs to redefine control templates. 
As a low level developer, It's my first time to hear about `make a markup extension` , I will try to learn that, thank you. 
( And this is  also a evidence that there is too much to learn for WPF. )

I post this issue after I saw these words on [devblogs]( https://devblogs.microsoft.com/dotnet/wpf-file-dialog-improvements-in-dotnet-8/ ).  Wish WPF a better future. 
![image](https://github.com/dotnet/wpf/assets/1972649/3041f5e5-d43a-41f3-84d8-0b46485f1ec7)

**Comment by miloush** [comment]
The button case is very specific in that its template (specifically in this theme) uses trigger to change the background to a predefined color (consistent, at that time, with OS). That is something that could theoretically be changed, but it would be a change affecting every application, which seems unreasonably disruptive when you can supply an alternative, trivial template for all buttons in _App.xaml_ and then a style with a trigger that works, or, you can indeed create a `HoverBrush` attached property. Introducing a built-in `HoverBrush` property to controls would be detrimental to the WPF principle of separating controls from their appearance, you would expect that all controls would react on mouse over and somehow use the hover brush for that.

Creating a markup extension is, I would say, not a beginners scenario, but it is not _that_ difficult and can be rewarding. Here is some guidance: https://learn.microsoft.com/en-us/dotnet/desktop/xaml-services/markup-extensions-overview. You could create one that would be used like
```xaml
<Button Style="{local:CombineStyles btn-danger btn-sm bordered ...}" />
```

However, it might be easier and more powerful in less effort to start with attached properties: https://learn.microsoft.com/en-us/dotnet/desktop/wpf/properties/attached-properties-overview. That would allow you to do
```xaml
<Button local:Css.ClassNames="btn-danger btn-sm bordered ..." />
```
In the property changed handler, you would pick or construct the needed style and set it to the control. You could also traverse the tree and see if any parents have the property set, and then pick/set appropriate styles based on the container.

Either way, feel free to use the discussion if you run into problems or questions.

Obviously there are other users of WPF and I might be in minority, but I would suggest you learn how to make the best use of WPF - in this case styles, templates, their selectors, properties inheritance and precedence, dynamic resources - and then you would be in a good position to decide what from the CSS world would be a useful fit and what would be the most elegant way to make it work.

I would also suggest that you keep an eye on the Win11 theming plans and make sure that the new default templates allow the required customization in perhaps an easier way than the current theme.

**Comment by cuiliang** [comment]
Thank you @miloush, I have better understanding now.
