### ISSUE TITLE
Touch inputs are not promoted to MouseDevice

### ISSUE THREAD

**Issue by PhilTrueEvon** [dotnet/wpf#8238]
### Description

Sometimes touch inputs are not promoted to the MouseDevice. I can see that all of my touch events climb up and down the visual tree, but my mouse events do not get fired.
The reason is that the number of active devices in StylusTouchDeviceBase is not 0. What I have seen is that a TouchDevice is not removed in the TouchDevice Class, because the whole work flow when touching and releasing a finger is interrupted by another touch input. It can' be reproduced reliably, but if a lot of touch inputs including swipes are done the issue can occur (maybe if the UI Thread is very busy). I made some traces to the ouput window while debugging which show more or less what happens. If you do a lot of touch inputs while in this error state (activeTouchDevices > 0 although no finger is on the touch screen), the issue resolves itself - usually a real mouse click also resolves the error state.
In my trace file you can see the [ClassName].[Method] + Device ID from PresentationCore.dll. MainWindow entries are the events in my window (top of visual tree).
[TouchInputTrace.txt](https://github.com/dotnet/wpf/files/12661018/TouchInputTrace.txt)

The moment where the error occurs is after TouchDevice.OnManipulationEnded 26. You can see that suddenly another TouchDevice with ID 16 interrupts the promotion. At the end of the trace file you can see that TouchDevice 26 was removed from the active device list again. From there on the touch inputs work again.
The moment where Wisp ActiveDeviceCount = 1 is when the promotion to mouse is not done anymore.
![image](https://github.com/dotnet/wpf/assets/145466438/baa60138-2c77-41f2-862e-d3e000d6432f)
![image](https://github.com/dotnet/wpf/assets/145466438/6d2f40a4-6eb7-4811-beaa-045c3cbc8729)

### Reproduction Steps

Can't be reproduced reliably. A lot of touch inputs and swipes may cause the issue.

### Expected behavior

Touch inputs are always promoted to mouse.

### Actual behavior

Touch inputs are not promoted to mouse.

### Known Workarounds

Real mouse clicks or some touch double clicks resolve the issue.

### Configuration

.net Framework 4.7.2 SDK 4.7.03081
PresentationCore.dll 4.7.3062.0

**Comment by singhashish-wpf** [comment]
Can you please confirm if this is just in .NET framework or in core as well?
Could you also share a sample minimal repro with detailed steps or TTD trace so that we could investigate it further?

**Comment by PhilTrueEvon** [comment]
Hello!

We cannot switch our program to .net Core, that would be way to much effort.
A minmal repro does not cause the issue, because it does not slow down enough to make the UI Thread busy (which is what I think is mandatory for the issue to occur)
I made a TTD trace while the issue is present (activeDeviceCount = 1 although no finger is on the touch screen), but it's 800MB big. Is there a way to upload it somewhere?

Br

**Comment by lindexi** [comment]
I'm work with the touchable applications development many years, but I've never had the problem you describe. But I found another similar problem, see https://blog-lindexi-com.translate.goog/post/WPF-%E6%8F%92%E6%8B%94%E8%A7%A6%E6%91%B8%E8%AE%BE%E5%A4%87%E8%A7%A6%E6%91%B8%E5%A4%B1%E6%95%88.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp

I hope it was helpful. Feel free to let me know more info.

**Comment by PhilTrueEvon** [comment]
@lindexi Thanks for your reply, the link was very informative on how things work, but unfortunately wasn't the reason for my issue. For the moment I removed the active device via refelection in case of my error state. Not a clean solution, but it worked for me and it didn't cause any unexpected behaviour so far.
