### ISSUE TITLE
Narrator not working for links in FlowDocumentScrollViewer

### ISSUE THREAD

**Issue by mgchaitanyababu** [dotnet/wpf#8240]
### Description

I am having a .rtf file with hyperlinks in it. I need to show them in my WPF application. I am using FlowDocumentScrollViewer as it makes links accessible with keyboard. But the narrator is not narrating the links when they are on focus. Attaching sample project with code. 
[SampleApp.zip](https://github.com/dotnet/wpf/files/12665507/SampleApp.zip)

### Reproduction Steps

Navigate the app using keyboard with navigator on.

### Expected behavior

Narrator should announce the links when they are focused.

### Actual behavior

Narrator is not announcing the links when they are focused.

**Comment by anjali-wpf** [comment]
@mgchaitanyababu - This is working as expected. Narrator is reading text, try using shortcuts - CAPS + W and CAPS + C. 
CAPS + W will take that window into focus and CAPS + C will focus the section, also enable the scan mode (Caps + Space) and then focus to the flow document, after that use down arrow key and the narrator will start reading the contents.
