### ISSUE TITLE
.Net 6.0 WPF first launch is very very slow

### ISSUE THREAD

**Issue by AnswerHJW** [dotnet/wpf#8247]
### Description

.Net 6.0 first launch is very very slow.Perhaps over 6s.

### Reproduction Steps

just first launch

### Expected behavior

Please faster

### Actual behavior

null

**Comment by Kuldeep-MS** [comment]
@AnswerHJW - Can you confirm whether a blank WPF application is slow, or if you are referring to a specific application?

**Comment by Symbai** [comment]
Unless this is about a regression between .NET versions the overall reasons for a slow cold startup for WPF apps is explained [here](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/application-startup-time?view=netframeworkdesktop-4.8#understanding-cold-startup-and-warm-startup) and [here](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/optimizing-performance-other-recommendations?view=netframeworkdesktop-4.8#configure-font-cache-service-to-reduce-start-up-time)

**Comment by AnswerHJW** [comment]
> @AnswerHJW - Can you confirm whether a blank WPF application is slow, or if you are referring to a specific application?

Yes , it is slow too.

If a blank WPF application that use windowsdesktop-runtime-6.0.22-win-x64 is launched, then run my application.it is normal,not slow.

**Comment by lindexi** [comment]
I have analyzed my application which using dotnet 6.0.13 and based on the data from 3,016,336 users over the past 7 days, the average startup time is found to be 2.7 seconds. It is important to further clarify that my application is a complex one with a rather complicated startup process. The above information is provided for your reference.

**Comment by AnswerHJW** [comment]
> I have analyzed my application which using dotnet 6.0.13 and based on the data from 3,016,336 users over the past 7 days, the average startup time is found to be 2.7 seconds. It is important to further clarify that my application is a complex one with a rather complicated startup process. The above information is provided for your reference.

哈哈，林德熙大佬，我是你的粉丝。你的这个数据是冷启动的启动时间吗？

**Comment by lindexi** [comment]
@AnswerHJW 
这是混合冷热启动时间的，没有单独统计冷启动时间  
This is a mixture of Cold Startup and Warm Startup times.

**Comment by AnswerHJW** [comment]
Hi,@Kuldeep-MS 
I have uploaded a viedo
[https://1drv.ms/v/s!ApoJv_a2lBw20ZI06CG1dGaqSvRcqw?e=TsPUsc](myvideo)

**Comment by AnswerHJW** [comment]
> @AnswerHJW 这是混合冷热启动时间的，没有单独统计冷启动时间 This is a mixture of Cold Startup and Warm Startup times.

大佬，你可以看一下我刚刚上传的视频，可以很明显的看到首次启动和非首次启动的速度

**Comment by lindexi** [comment]
试试调试一下启动性能，可以使用界面比较友好的 dotTrace 工具或者是能够监控到比较多信息的微软极品工具箱里的 ProcessMonitor 工具调试看启动时间卡在哪里  
How about test the proforamce by dotTrace or ProcessMonitor and etc.

另外我注意到你的视频里面不是一个标准的空 WPF 项目，而是包含了 WinRT 的功能，这部分可能会造成一些干扰  
In addition, the WinRT may affect the result in your video

**Comment by singhashish-wpf** [comment]
Observations:
1. First launch is slow and subsequent launches are faster.
2. Most of time is spent in JIT. 
3. R2R images have comparable performance. They aren't slow.
![image](https://github.com/dotnet/wpf/assets/82596204/bde20c13-5633-43b5-9a7f-f392760ad91b)
@AnswerHJW  Could you please let me know if the above observations are correct in your understanding too?

**Comment by lindexi** [comment]
@singhashish-wpf I am afraid that the problem he has encountered is the Antivirus software is scanning the DLL files

**Comment by AnswerHJW** [comment]
> @singhashish-wpf I am afraid that the problem he has encountered is the Antivirus software is scanning the DLL files

Yes, it is caused by Windows Defender :(

**Comment by lindexi** [comment]
@singhashish-wpf Is there anything developers can do to make Windows Defender happy?

**Comment by AnswerHJW** [comment]
> Observations:
> 
> 1. First launch is slow and subsequent launches are faster.
> 2. Most of time is spent in JIT.
> 3. R2R images have comparable performance. They aren't slow.
>    ![image](https://user-images.githubusercontent.com/82596204/276487242-bde20c13-5633-43b5-9a7f-f392760ad91b.png)
>    @AnswerHJW  Could you please let me know if the above observations are correct in your understanding too?

It is caused by Windows Defender. If Windows Defender don't update, .net6.0 first launch is not slow.

**Comment by singhashish-wpf** [comment]
OK. Are we good to close this then?

**Comment by miloush** [comment]
> Is there anything developers can do to make Windows Defender happy?

You can exclude your projects folder from being scanned.

**Comment by lindexi** [comment]
@AnswerHJW and @miloush Submit your application to https://www.microsoft.com/en-us/wdsi/filesubmission seems to help a little.

将自己的应用向微软报备看起来有几毛钱用，报备是免费的，入口选开发者，登录后报备，里面的信息带星号的就填，不带的不用填

**Comment by AnswerHJW** [comment]
> @AnswerHJW and @miloush Submit your application to https://www.microsoft.com/en-us/wdsi/filesubmission seems to help a little.
> 
> 将自己的应用向微软报备看起来有几毛钱用，报备是免费的，入口选开发者，登录后报备，里面的信息带星号的就填，不带的不用填

UWP application also need to submit? Does it useful?

UWP也需要报备吗？会有用吗？

**Comment by lindexi** [comment]
@AnswerHJW The WinUI3 application is not UWP application. And we need not submit the UWP application. It has little help.

报备只有几分钱用…
