### ISSUE TITLE
WPF 3D to 2D projection appears wrong?

### ISSUE THREAD

**Issue by WoodManEXP** [dotnet/wpf#8276]
### Description

Please see https://learn.microsoft.com/en-us/answers/questions/1365779/wpf-3d-to-2d-projection-appears-wrong.

After researching this for a while let me ask for this info which would enable a work-around: Is there a way in WPF to perform the 3D to 2D projection that will produce the 2D viewport pixel coordinates where WPF will render the 3D point in 2D space? If it were possible to do this then work-arounds could be implemented at higher levels in the application when these cases occur. Neither MathUtils.TryWorldToViewportTransform and Visual3D.TransformToAncestor produce the results as seen on the screen (please see info in the case for details)

TY!

### Reproduction Steps

A small VS project is provided.

### Expected behavior

Explained at https://learn.microsoft.com/en-us/answers/questions/1365779/wpf-3d-to-2d-projection-appears-wrong

### Actual behavior

Explained at https://learn.microsoft.com/en-us/answers/questions/1365779/wpf-3d-to-2d-projection-appears-wrong

**Comment by miloush** [comment]
Please include the sample project.

It is unclear what you are asking. Are you reporting a bug? Are you asking a question how to calculate a projection without using 3D visuals?

**Comment by WoodManEXP** [comment]
A project showing an example of how a coordinate centered on the LookDirection Vector is not draw in the center of the 2D viewport is here: [https://drive.google.com/file/d/1R_qqZT4jEMMt_Z0e8fvhfyZXEGXsgiTk/view?usp=sharing](https://drive.google.com/file/d/1lX2GSxbj5LCa01FF-RumZAFblmkhb3WS/view?usp=sharing)

This is not reporting a bug, although this feels like a bug in Viewport3D. Instead, the ask is to be able to perform the 3D to 2D projection calculation as WPF's Viewport3D does in order to detect and implement a work-around.

**Comment by WoodManEXP** [comment]
After lots of research into WPF’s 3D capabilities (using the Viewport3D control to render 3D) including reverse engineering parts of the WPF Viewport3D source code, the best way forward has been to give up using WPF’s 3D subsystem. It does not offer a usable means of dealing with or controlling, among others, the 3D to 2D projection problems baked into it.

Fortunately, a WPF OpenGL C# binding is available, it is called OpenTK and can be nicely woven into the WPF framework. Can be found at http://opentk.net/.

OpenGL is somewhat of a paradigm shift from WPF’s 3D. It, at first, feels more tedious to learn and use. Once getting into the Zen of OpenGL though it is, IMHO, a nice improvement.  It provides excellent control of the many things that are hard to control in WPF 3D, including the 3D to 2D projection issues.

OpenGL seems to offer better performance in terms of both processing and memory utilization.

WPF 3D’s hit testing will be missed though. It is baked more into WPF 3D’s object model, not the case with OpenGL…
