### ISSUE TITLE
WPF Application run failed with large resources

### ISSUE THREAD

**Issue by XamlTest** [dotnet/wpf#8284]
### Description

The initial issue reported in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1880935.

WPF application failed to run with large resources(>1.9G). 

### Reproduction Steps

**Repro Steps:**
1. Create a WPF Core project or directly download the project [WpfApp1.zip](\\ddfiles3\Team_XAML\User\v-dollywang\Bug)
2. Add a new folder: images
3. Add a large image to the images folder, such as 50M.(You can download bmp file from https://filesamples.com/formats/bmp)
4. Copy and paste the images 37 times, make the images folder size about 1.9 GB
5. Press F5 to run

### Expected behavior

Application runs successfully.

### Actual behavior

1. If the images folder size is about 1.9GB, application will exit automatically without error.
2. If the images folder size is larger than 2GB, error CS1566: "Error reading resource "WpfApp2.g.resources" -- Specified argument was out of the range of valid values." will display in Error List after rebuilding.
![image](https://github.com/dotnet/wpf/assets/97647558/2a8ea5c8-6f22-4362-a9c4-3c06338ca518)
3. If the images folder size is smaller than 1.85GB, application works fine.

**Comment by lindexi** [comment]
This issue seems quite amusing, perhaps the ancient developers didn't foresee that someone would need to harness such colossal resources.

**Comment by miloush** [comment]
I don't find it that much amusing, 2GB is max int value and a lot of the things in the framework cannot deal with larger values easily (such as array indxes). These limitations are also in file formats (including the exe) and the OS and processor architectures as well, in terms of how much memory can be loaded and addressed at once.

Either way, the resources infrastructure is not WPF specific and it is more of .NET limitation and should be filed there (in fact the error raised is an error from Roslyn), but I wouldn't have very high expecations here.

**Comment by singhashish-wpf** [comment]
Closing this as of now as this seems a system limitation. There isn't anything much that wpf can do in this w.r.t this issue.
