### ISSUE TITLE
Localization issue with vertical ScrollBar context menu in Japanese/Russian etc.  

### ISSUE THREAD

**Issue by Admiri92** [dotnet/wpf#8292]
### Description

The context menu of vertical _ScrollBar_ is not fully translated in many languages including Japanese, Russian, Spanish etc. 
There is a missing localization for **Top** menu item, **Top** item translation will be in english only. I have tested the issue on .NET 6/7 .

![2imagesio](https://github.com/dotnet/wpf/assets/7899899/2496c0f7-fb3b-4915-b36d-cf9ccf00836b)

### Reproduction Steps

1. Create new .NET WPF application
2. Add a ScrollBar.
3. Localize application CurrentUICulture to Japanese, Russian or Spanish and run the application.
4. Right-click on vertical scrollbar.

### Expected behavior

Application must show localized translations of menu context.
This is a screenshot from WPF .Net Framework 4.6.2:
 
![russianversion](https://github.com/dotnet/wpf/assets/7899899/a4a6afec-3c8f-466e-b5a4-321102105f3c)

### Actual behavior

**Top** item of  vertical scrollbar menu context is not translated in Japanese, Russian, Spanish and many other languages.

### Regression?

Issue is present on .NET 6 and .NET 7.
Not present on .Net Framework 4.6.2 .

### Configuration

.NET version: 6 and 7
OS: Windows 11 Pro, Version 10.0.22621 Build 22621
Architecture: x64

**Comment by IrinaPykhova** [comment]
note, it's the same on Windows 10

**Comment by dipeshmsft** [comment]
Closing this issue as it has been fixed by PR #8396 . Thanks @Admiri92 , for raising the issue.
