### ISSUE TITLE
CustomDataGridColumnHeader Derived from DataGridColumnHeader Causes InvalidOperationException

### ISSUE THREAD

**Issue by jamesnet214** [dotnet/wpf#8294]
### Description

A problem has been identified with the DataGridColumnHeader in WPF.

As a WPF developer, I am aware that in order to customize the DataGrid's ColumnHeader, one needs to use the DataGridColumnHeader. To manage this based on a CustomControl, I created a class called CustomDataGridColumnHeader.

```csharp
public class CustomDataGridColumnHeader : DataGridColumnHeader
```

However, upon execution, the following error message is encountered:

> System.InvalidOperationException: ''CustomDataGridColumnHeader' TargetType does not 
match type of element 'DataGridColumnHeader'.'

Despite trying various methods, the outcome remains the same.

### Reproduction Steps

1. Create a CustomDataGridColumnHeader derived from DataGridColumnHeader.
2. Attempt to use this custom header in a DataGrid.

### Expected behavior

The CustomDataGridColumnHeader should be applied without any errors.

### Actual behavior

An error is thrown:

> System.InvalidOperationException: ''CustomDataGridColumnHeader' TargetType does not match type of element 'DataGridColumnHeader'.'

### Regression?

Not provided.

### Known Workarounds

The only way to anticipate a normal execution is to use the DataGridColumnHeader as it is.

### Impact

Not provided.

### Configuration

OS: Microsoft Windows 11
.NET: .NET 7.0

### Other information

Attempts made:

Using Style Target for CustomDataGrid:

```xaml
<Style Target="{x:Type based:CustomDataGrid}">
    <Setter Property="ColumnHeaderStyle" Value="{StaticResource {x:Type based:CustomDataGrid}}"/>
</Style>
```

Using separate Style Target for CustomDataGridColumn and CustomDataGrid:

```xaml
<Style Target="{x:Type based:CustomDataGridColumn}" x:Key="CDGC">
</Style>
<Style Target="{x:Type based:CustomDataGrid}">
    <Setter Property="ColumnHeaderStyle" Value="{StaticResource CDGC}"/>
</Style>
```

Using separate Style Target for CustomDataGridColumn and CustomDataGridRow:

```xaml
<Style Target="{x:Type based:CustomDataGridColumn}" x:Key="CDGC">
</Style>
<Style Target="{x:Type based:CustomDataGridRow}">
    <Setter Property="HeaderStyle" Value="{StaticResource CDGC}"/>
</Style>
```

Setting the ColumnHeaderStyle programmatically in CustomDataGrid:

```csharp
public CustomDataGrid()
{
    ColumnHeaderStyle = new Style(typeof(CustomDataGridColumnHeader));
}
```

Setting the HeaderStyle programmatically in CustomDataGridRow:

```csharp
public CustomDataGridRow()
{
    HeaderStyle = new Style(typeof(CustomDataGridColumnHeader));
}
```

Furthermore, using the same approach with DataGridCell also yields the same issue.

Thank you for taking the time to read and consider this issue.

**Comment by miloush** [comment]
> Attempt to use this custom header in a DataGrid.

Can you show us how you are using it or can you provide a repro project?

**Comment by miloush** [comment]
Also what is the customization of a column header you are trying to achieve?

**Comment by jamesnet214** [comment]
@miloush 

I apologize for the oversight. I've prepared the following GitHub repository for further reference. Thank you for your understanding and patience.

https://github.com/jamesnet214/issue/blob/main/dotnet/wpf/issue/CustomColumnHeader/WpfApp1/Themes/Units/CustomDataGrid.xaml

**Comment by miloush** [comment]
I am still not quite sure what customizations you need that would require you to derive from all these controls. However, the one you missed is the one you need - `DataGridColumnHeadersPresenter` is the control that creates `DataGridColumnHeader`. You should be able to make a custom headers presenter, override the `GetContainerForItemOverride()` method and return your custom column header from it.

**Comment by jamesnet214** [comment]
@miloush 
Thank you for your response. I tried as you mentioned, and while there were no errors, the header returned through the GetContainerForItemOverride() doesn't seem to be created. I've also updated the source code. I'm curious as to why the derived controls aren't being recognized. What criteria cause such differences? I would think this functionality should be inherent in WPF's design architecture.

Thank you once again for your valuable answer.

https://github.com/jamesnet214/issue/blob/main/dotnet/wpf/issue/CustomColumnHeader/WpfApp1/Themes/Units/CustomDataGrid.xaml

**Comment by Laniusexcubitor** [comment]
Following issues with your code:
You are overriding the `DefaultStyleKeyProperty` for `CustomDataGridColumnHeader` and `CustomDataGridColumnHeadersPresenter` but WPF cannot find any templates for them.
Remove the x:Key from your styles. They must have a default style key.

**Comment by jamesnet214** [comment]
@Laniusexcubitor 
Firstly, I apologize for the delayed response.

I added the x:Key because I couldn't resolve the issue with the CustomControl connected through DefaultStyleKey, so I tried various approaches.

The core of the issue is that I cannot apply the HeaderStyle and CellStyle to controls such as DataGridColumnHeader and DataGridCell when they are transformed into CustomControls.

I expect the following code to work, but in reality, it does not (it results in an error):
```
<Setter Property="HeaderStyle" Value="{StaticResource {x:Type CustomDataGridColumnHeader}}"/>
<Setter Property="CellStyle" Value="{StaticResource {x:Type CustomDataGridCell}}"/>
```

Similarly, trying to directly link resources using x:Key also produces the same error:
```
<Setter Property="HeaderStyle" Value="{StaticResource MyColumnHeaderStyle}"/>
<Setter Property="CellStyle" Value="{StaticResource MyGridCellStyle}"/>
```

In the case of DataGridRow, when made into a CustomControl, you can specify a redefined class through the GetContainerForItemOverride in the CustomDataGrid class. However, for classes like DataGridColumnHeader and DataGridCell, they cannot be linked due to the aforementioned error.

As a result, one must use style templates through the widely-known base classes of DataGridColumnHeader and DataGridCell.

I want to use the newly redefined CustomControl class. Moreover, I believe that, given the structure of WPF, this should work naturally.

**Comment by Laniusexcubitor** [comment]
You should try to create a complete example of your problem, so people can directly reproduce and advice.

There is still one instance of the default `DataGridColumnHeader` left. The [default template](https://github.com/dotnet/wpf/blob/6634719e22053aab8e5e0db37618170494aea334/src/Microsoft.DotNet.Wpf/src/Themes/XAML/DataGrid.xaml#L169C23-L169C23) for `DataGridColumnHeadersPresenter` adds a `DataGridColumnHeader` which will also get the HeaderStyle applied which will target the wrong type.
So you would have to override the template.

**Comment by Laniusexcubitor** [comment]
The `DataGrid` is very hard to customize. 🤪
