### ISSUE TITLE
Issue routing events in WPF designer with Visual Studio 2022

### ISSUE THREAD

**Issue by ilCosmico** [dotnet/wpf#8352]
### Description

In my WPF custom control, I define some inner elements that must invalidate the parent control when a dependency property has been changed at design-time.
I use `EventManager.RegisterClassHandler` for this purpose and it works fine with VS 2019, but with VS 2022 it does not work anymore.

In short, there is a MyViewbox with a MyFrameworkElement as an inner element.
When I change the Lighting property of MyFrameworkElement the painting of the MyViewBox is updated in real-time on VS2019, but not on VS2022.

The below GIF shows this different behavior with VS2019 (on the left) and VS2022 (on the right)

### Reproduction Steps

This is a sample code reproducing the issue.

[WpfAppTestDependencyProperty.zip](https://github.com/dotnet/wpf/files/13113612/WpfAppTestDependencyProperty.zip)

### Expected behavior

In short, there is a `MyViewbox` with a `MyFrameworkElement` as an inner element.
When I change the `Lighting` property of `MyFrameworkElement` the painting of the `MyViewBox` is updated in real-time on VS2019, but not on VS2022.

The below GIF shows this different behavior with VS2019 (on the left) and VS2022 (on the right)
![VS2022_WpfDesignerIssue](https://github.com/dotnet/wpf/assets/8678145/d2b4c73b-1678-4b9b-b080-e788f469e5bf)

### Actual behavior

When I change the `Lighting` property of `MyFrameworkElement` the painting of the `MyViewBox` is NOT updated in real-time on VS2022.

### Regression?

It was working with VS 2019.

### Impact

Users cannot see updated changes during the XAML editing.

### Configuration

The regression is strictly linked to VS2022 and WPF. I tested both net472 and net6.0.

**Comment by singhashish-wpf** [comment]
Looks like we will need to check this with VS and Designer team.

**Comment by spadapet** [comment]
The VS feedback item has been resolved:
* https://developercommunity.visualstudio.com/t/Issue-routing-events-in-WPF-designer-wit/10481861

**Comment by ilCosmico** [comment]
> The VS feedback item has been resolved:
> 
> * https://developercommunity.visualstudio.com/t/Issue-routing-events-in-WPF-designer-wit/10481861

The VS team has given a workaround for the simple sample provided. More details are asked for a more complex scenario.

**Comment by ilCosmico** [comment]
In the meantime, the MS team provided more help on this, so I can consider the case closed.
