### ISSUE TITLE
DataContextChanged not fire and binding not work in nested properties.

### ISSUE THREAD

**Issue by HppZ** [dotnet/wpf#8376]
### Description

code here https://github.com/HppZ/TestDataContextBinding.git

### Reproduction Steps

run the project.
click the button.

### Expected behavior

FrameworkElement_OnDataContextChanged should fire.
Texts shoud change to 'world'.

### Actual behavior

FrameworkElement_OnDataContextChanged does not fire.
Text property binding with 'Item.Layout.Name' works fine, the other not.

**Comment by miloush** [comment]
As far as I can tell from the code, you are not changing the value of the DataContext property, it is still the same instance of the same class, so you will not get a property changed event for this property.

The grid gets a notification, evaluates the data context and finds out it's the same one. So not only the property value did not change, but there is no need to re-evaluate the child bindings.

If you expect the change of Name property to be noticed, notify about change of the name property.
