### ISSUE TITLE
Generate resources SRID's as constant key strings instead of properties that retrieve values

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#841]
Copied from VSO ID 689973

Found when running ValueSeriealizerTests, which are part of Xaml DRT's. 

resources are loaded in WPF like this:

   SR.Get(SRID.ResourceName). 

The current SRID system in .NET Core generates SRID's like this: 

public string SRID.ResourceName
{
  get { ResourceManager.GetResource("ResourceName"); }
}

When WPF applies SR.Get over this string, it fails (because it effectively results in SR.Get(SR.Get("ResourceName")). 

We need to go back to producing SRIDs that look like the .NET Framework codebase, which look like this:

public const string SRID.ResourceName = "ResourceName". 

There are about 7500 places in WPF where we have code that depends on SRID lookups. Without this fix, we will have unpredictable behavior in all of those places.

**Comment by vatsan-madhavan** [comment]
No longer a problem - this has been fixed. In fact, #1 exists to eventually improve the way we do this and use `nameof`.
