### ISSUE TITLE
Remove vcruntime140.dll dependency from PresentationCore.dll

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#843]
Copied from VSO ID 725939

**Initial Research**

From @rladuca 
Attached Loader Snaps and Stack from PCore
[pcorestack.txt](https://github.com/dotnet/wpf/files/3253356/pcorestack.txt)
[pcoresnap.txt](https://github.com/dotnet/wpf/files/3253357/pcoresnap.txt)

From @ericstj 
 took a look at this.

PresentationCore itself is PInvoking into VCRuntime140.dll:
<img width="287" alt="fd0e81ef-31d1-4487-9017-cb900b1df099" src="https://user-images.githubusercontent.com/49078227/58894715-5c6fc500-86a7-11e9-9d69-c4d4c92a8b80.png">

 

Looking through the IL of the PresentationCore.dll I see this is coming from the following 3 PInvokes:

```
.method assembly static pinvokeimpl("VCRUNTIME140.dll" lasterr cdecl)

        void* modopt([mscorlib]System.Runtime.CompilerServices.CallConvCdecl)

        memmove(void* A_0,

                void modopt([mscorlib]System.Runtime.CompilerServices.IsConst)* A_1,

                uint64 A_2) cil managed preservesig

{

  .custom instance void [mscorlib]System.Security.SuppressUnmanagedCodeSecurityAttribute::.ctor() = ( 01 00 00 00 )

}

.method assembly static pinvokeimpl("VCRUNTIME140.dll" lasterr cdecl)

        int32 modopt([mscorlib]System.Runtime.CompilerServices.CallConvCdecl)

        __FrameUnwindFilter(valuetype _EXCEPTION_POINTERS* A_0) cil managed preservesig

{

  .custom instance void [mscorlib]System.Security.SuppressUnmanagedCodeSecurityAttribute::.ctor() = ( 01 00 00 00 )

}

.method assembly static pinvokeimpl("VCRUNTIME140.dll" lasterr cdecl)

        void modopt([mscorlib]System.Runtime.CompilerServices.CallConvCdecl)

        __std_type_info_destroy_list(valuetype __type_info_node* A_0) cil managed preservesig

{

  .custom instance void [mscorlib]System.Security.SuppressUnmanagedCodeSecurityAttribute::.ctor() = ( 01 00 00 00 )

}
```

These appear to be added by the C++ linker.  I found that all these exports exist on ucrtbase.dll, which is where our native code will call.  We should investigate if there is a setting / lib that will link these to ucrtbase.dll instead of VCRuntime140.dll

**Comment by vatsan-madhavan** [comment]
This is a dup of #37 and has since been fixed.
