### ISSUE TITLE
CMILFactory::GetCurrentDisplaySet causes 0xC0000005 at D3D12Core.dll in software rendering mode

### ISSUE THREAD

**Issue by wfjsw** [dotnet/wpf#8440]
### Description

A user with an Intel integrated graphic driver >= 4900 reported that a simple WPF program crashes when the first window is opening. 

The issue is originally happened on a larger bunch of users, where the `Application.Run` would somehow crash at `igd12um64xel.dll`. In order to mitigate this, I set 

```
RenderOptions.ProcessRenderMode = RenderMode.SoftwareOnly;
```

in the App constructor. This works for some people, but in this case the application would still crash regardless of that settings.

A comprehensive memory dump for this specific issue is available here:
https://1drv.ms/u/s!As2fjvowlSTGhY5DeovEMGQuVo_w9Q?e=5PSbyP

The memory dump where the original crash happens is available here:
[A.exe.8804.dmp](https://github.com/dotnet/wpf/files/13407383/A.exe.8804.1.dmp)

### Reproduction Steps

According to the reporter:
- Have an active Intel integrated graphics and disable discrete graphics, if exists
- Intel graphics driver version >= 4900
- Any WPF project

### Expected behavior

The application should run normally.

### Actual behavior

The application crashes with no indications. A crash dump is then located in `%LOCALAPPDATA%\CrashDumps`

### Impact

This seems specific. When the discrete graphics is enabled the issue is gone for this reporter.

### Configuration

- .NET Core Desktop Runtime 6.0.22,6.0.25
- Windows 11 Pro 22H2 22621.2715
- x64
- The application is compiled to win-x64 targeted `net6.0-windows` with ReadyToRun enabled

**Comment by Symbai** [comment]
Likely a dup of #7076 same problem (crash), same cause (intel integrated graphic cards), same workaround (disable HW acceleration)

**Comment by wfjsw** [comment]
> Likely a dup of #7076 same problem (crash), same cause (intel integrated graphic cards), same workaround (disable HW acceleration)
> 
> I guess this post provides more background: https://github.com/dotnet/wpf/issues/2063#issuecomment-1741205008

From user reports the registry value mostly does nothing. Changing the in-app variable, on the other hand, have limited effect. Some users failed to run despite these workarounds in place.

**Comment by Symbai** [comment]
Never trust an end user's report. Besides its still the same problem, same cause and same workaround (whether registry or in app, the workaround is disabling HW acceleration, you said it yourself in first post). And when WPF uses HW acceleration it uses DirectX9 which is why I added the link for the comment on why COULD this fail on Intel graphic cards.

**Comment by wfjsw** [comment]
> Never trust an end user's report. Besides its still the same problem, same cause and same workaround (whether registry or in app, the workaround is disabling HW acceleration, you said it yourself in first post). And when WPF uses HW acceleration it uses DirectX9 which is why I added the link for the comment on why COULD this fail on Intel graphic cards.

I was doing peer debugging with an Intel employee and I sent them a blanket software-only rendering wpf app. That's how the 450M large dump comes from. So I'm pretty sure the workaround itself does not work.

**Comment by wfjsw** [comment]
I think I'm going to rephrase the question as: 
Why WPF decides to call DirectX when SoftwareOnly is set?

**Comment by Symbai** [comment]
I think the MDSN gives an answer to your question:

```
Note ProcessRenderMode specifies a preference and does not necessarily change the actual rendering mode. 
Other parts of the system may override this preference and force the system into software rendering.
```

So if something on the end user's system overrides this preference you end up with still using HW acceleration.

**Comment by wfjsw** [comment]
Seems I invoked the `ProcessRenderMode` a bit too early. It has to be in `App_OnStartup`.
