### ISSUE TITLE
Visibility.Collapsed is not work with Remote Desktop

### ISSUE THREAD

**Issue by sakai-IST** [dotnet/wpf#8486]
### Description

I create an application that working on the tasktray. The user can hide the window and show it again from the tasktray.
However, when redisplayed via Remote Desktop, the window turns black.

### Reproduction Steps

1. Create the new WPF application from template.
2. Change source code in **App.xaml.cs**.

```
    public partial class App : Application
    {
        private System.Windows.Forms.NotifyIcon _notifyIcon;

        private MainWindow _win = null;
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);

            var icon = GetResourceStream(new Uri("test.ico", UriKind.Relative)).Stream;

            _notifyIcon = new System.Windows.Forms.NotifyIcon
            {
                Visible = true,
                Icon = new System.Drawing.Icon(icon),
                Text = "SampleApp",
            };

            _notifyIcon.MouseClick += (s, er) =>
            {
                if (er.Button == System.Windows.Forms.MouseButtons.Left)
                {
                    ShowMainWindow();
                }
            };
            
            if (_win == null)
            {
                _win = new MainWindow();
                _win.WindowStartupLocation = WindowStartupLocation.CenterScreen;

                _win.Closing += (s, ea) =>
                {
                    _win.Visibility = Visibility.Collapsed;   //the window turns black
                    //_win.Visibility = Visibility.Hidden;   //if use Visibility.Hidden, the window not turns black.
                    ea.Cancel = true;
                };
            }
        }

        protected override void OnExit(ExitEventArgs e)
        {
            _notifyIcon.Dispose();
            base.OnExit(e);
        }

        private void ShowMainWindow()
        {
            if (_win != null)
            {
                _win.Show();
            }
        }
    }
```
3. Delete `StartupUri="MainWindow.xaml"` from **App.xaml**.
4. Build the solution.
5. Start the application. You must check that the application working on the tasktray.
6. Close the window. You must check that the application working on the tasktray, again.
7. Connect to machine of the step 6 using Remote Desktop(mstsc.exe)
8. Redisplay the application from the task tray.

### Expected behavior

If you use `_win.Visibility = Visibility.Collapsed;`, the window turns black in step 8.
If you use  `_win.Visibility = Visibility.Hidden;`, the window not turns black in step 8.

### Actual behavior

This capture is step 8.
![キャプチャ](https://github.com/dotnet/wpf/assets/98733014/ea6c4389-3d9d-400a-9f9c-07678c2c7144)

If you dragging to resize the window, renders the window correctly.

### Configuration

I try windows10, windows server 2016, 2019, etc. But I can't solve this problem.

**Comment by aquinn39** [comment]
That is a strange issue, but for hiding a WPF window, you could try Window.Hide() as the Visibility property on WPF Windows I believe does not really work properly. Window.Hide() will make the Window invisible and intangible and it will take up no space (basically just the default behaviour for hiding a Win32 window).

**Comment by anjali-wpf** [comment]
@sakai-IST - 
The black screen is due to how Remote Desktop handles the visibility of UI elements.

You can still use `Visibility.Hidden` when you are not using remote desktop, when you set an element's visibility to Collapsed, then the element will still be present in the UI tree, but it's not rendered or displayed. And when you hide a window using `window.Hide()`, the entire window is hidden from view, removing it from the display entirely.

Another alternative is setting the `opacity` property to 0 in order to hide the window without collapsing it.

**Comment by sakai-IST** [comment]
@anjali-wpf I understand that I should use `window.Hide()`. It's surprised `Visibility.Hidden` and `window.Hide()` are not equal. Thank you great comments :)
