### ISSUE TITLE
Localized strings incorrectly replaced to English or keyboard shortcuts in the Scrollbar context menu (and maybe more)

### ISSUE THREAD

**Issue by AdrienTD** [dotnet/wpf#8522]
### Description

When executing a WPF app on .NET Core/5/6/7/8 using a non-English system, the scrollbar context menu has some incorrect command names, which does not happen on .NET Framework 4.8. For example, "Page Up" remains in English in some languages including French, Italian, and more.

### Reproduction Steps

On a Windows environment set to one of the languages, including but not limited to: French, Italian, Spanish.
Open any WPF app running on .NET Core or .NET 5+, and right-click on a scrollbar to open its context menu (from a ListView as an example).

### Expected behavior

All menu items should be on the same language and consistent, like in .NET Framework 4.8.
![image](https://github.com/dotnet/wpf/assets/19519567/6cef8089-6c10-4e4c-a22c-f5aeeeed82de)
Above language shows the context menu in French.

### Actual behavior

But since .NET Core, in some languages (French, Italian), the menu items "Page Down" and "Page Up" still appear in English, whereas the others are in the correct language.
![image](https://github.com/dotnet/wpf/assets/19519567/079c39a1-a95d-45ab-bc11-8d55e53e6e91)

This can also be seen in the localized string resource files (such as https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.fr.xlf ) and looking at string IDs starting with ScrollBar_ .

Moreover, the menu item "Top" is not translated in almost all languages, including
 * [Japenese](https://github.com/dotnet/wpf/blob/47cf91bf2e375466c9584967cf082b4fc3bcc6ab/src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.ja.xlf#L4818)
 * [Russian](https://github.com/dotnet/wpf/blob/47cf91bf2e375466c9584967cf082b4fc3bcc6ab/src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.ru.xlf#L4818), ...

In some languages [Spanish](https://github.com/dotnet/wpf/blob/d17750126f3b5aab8e3986ab78812eb12132781f/src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.es.xlf#L4768), the menu items use keyboard shortcut abbreviations (e.g. AvPág instead of "Avanzar la página" I presume).

### Regression?

In .NET Framework 4.8, the menu items in the Scrollbar are correctly translated, but since .NET Core, depending on the language, some menu items either changed to English or uses the keyboard shortcut abbreviation (instead of the command sentence).

### Known Workarounds

N/A Needs fixes in the localized string resources.

### Impact

Confusion for people who don't know English.

### Configuration

I tested on both .NET 5 and the latest .NET 8.
Though all .NET versions from .NET Core to .NET 8 are impacted (at least since WPF became open-source).
OS: Windows 10 22H2 x64
Not specific to any platform.

### Other information

Note that the Scrollbar might not be the only area where this translation regression happened. When looking at the [commit history of the French text resources of PresentationFramework]( https://github.com/dotnet/wpf/commits/47cf91bf2e375466c9584967cf082b4fc3bcc6ab/src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.fr.xlf), this issue was already present in its very first commit (that is ae1790531c3b993b56eba8b1f0dd395a3ed7de75 #720).
But in commit 9afa976db6618e4cd9a944d68149d70e0cbeea58, at an attempt at "fixing localization crashes with key gestures", the document [Documentation/localization_untranslated_strings.md](https://github.com/dotnet/wpf/blob/47cf91bf2e375466c9584967cf082b4fc3bcc6ab/Documentation/localization_untranslated_strings.md) was created and mentions the strings "PageUp" and "PageDown" as being affected. However it seems that during the fixing all strings containing "Page Up" (even with space) were accidently being changed, even those that were not related to the crash, including the scrollbar context menu. This is means that all strings that contained similar words to the keyboard shortcuts mentioned in the document in the English version would be "reset" to English everywhere, or to an keyboard shortcut for some reason.

The issue was already reported in issue #4367 for the Simplified Chinese localization, and it might have been fixed, but nobody has realised that all the other languages were also affected. However, I checked in the latest commit and the fix seems to have been reverted to the English "Page Up" again by commit ddbf5a86f3ca221014c97720b97e26cd19eb8c25.

It might be ideal to find the pre-opensource commit that caused the regression and restore the localization of all strings unrelated to the crash that that pre-opensource commit was attempting to fix.

**Comment by miloush** [comment]
See also #4367, #8295 and the respective PRs. (i.e. the "Top" one has been fixed)

**Comment by dipeshmsft** [comment]
This issue has been fixed by the PR #8396 . Closing this issue now. Thanks @AdrienTD for raising this issue.
