### ISSUE TITLE
[netcore3] Remove dependencies on <wingdip.h> and WPF_REMOTE_SUPPRESS_DRAWING

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#853]
Copied from VSO ID: 660416

Commit 1bb28a36

Affects core\uce\{hwndtarget.cpp, precomp.hpp}

**Comment by vatsan-madhavan** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/1818?_a=overview fixes this.
