### ISSUE TITLE
Custom TitleBar : Using WindowChrome and Snap Layout

### ISSUE THREAD

**Issue by singhashish-wpf** [dotnet/wpf#8543]
- [x] Verify that snap layout is working for WPF applications
- [x] Snap layout works fine with Window Chrome as well
- [x] Custom Chrome Title Bar of WPF doesn't support snap layout features.

**Comment by dipeshmsft** [comment]
We have verified the above behaviors with WPF Gallery Application, however there are issues when using custom title bar buttons, as that requires handling on the app side and as discussed on an earlier thread it causes other issues when we try to handle this.

I am closing this for now, in regard with Fluent theme discussion. Rest of the issues with WindowChrome and snap layout will be handled seperately.
