### ISSUE TITLE
Theme Manager and Theme Switching

### ISSUE THREAD

**Issue by singhashish-wpf** [dotnet/wpf#8553]
- [x] The app's theme should change depending upon the system theme changed event.
- [x] App developers should have a method to change the theme to light/dark.
- [x] Theme manager should handle all the necessary actions corresponding to themes.
- [ ] Give an option to the developer to not change the App theme based on System theme change.

**Comment by dipeshmsft** [comment]
This is now complete with the implementation of ThemeMode properties for Application and Window.
