### ISSUE TITLE
[Regression] AdvXamlFeatureTests.LocalAssembly_FriendWithKey and AttachablePropertyServicesTests.SerializeWithAttachedPropertyOnInstanceOfOwner are failing with latest shared framework

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#856]
Run Xaml DRT's on any recent build of the shared framework. 
Observe that AdvXamlFeatureTests.LocalAssembly_FriendWithKey and AttachablePropertyServicesTests.SerializeWithAttachedPropertyOnInstanceOfOwner are failing 

AttachablePropertyServicesTests.SerializeWithAttachedPropertyOnInstanceOfOwner is returning extra x:Null properties that are unexpected. This is not incorrect, but likely breaks compat (or even correctness). We need to understand what is happening, and how to get this back in line with our original expectations. 

AdvXamlFeatureTests.LocalAssembly_FriendWithKey failure reason is unclear. We should investigate whether it has anything to do with loading Xaml types from internalsvisibleto: assemblies. If this is broken, this is a very basic scenario that should be fixed. 

Note: When this is fixed, these tests should be re-enabled in dnceng\dotnet-wpf-systemxaml-proto (or dnceng\dotnet-wpf)

**Comment by rladuca** [comment]
Both of these suites are currently passing on `3.0.100-preview8-013348`.  This bug is no longer relevant.
