### ISSUE TITLE
[netcore3] PresentationBuildTasks TaskHelper.cs contains #if false conditional code required for .NET Framework GAC cache

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#857]
Copied from VSO ID 840043

[netcore3] PresentationBuildTasks TaskHelper.cs contains #if false conditional code required for .NET Framework GAC cache

This code should be re-enabled, only for . NET Framework.

**Comment by ryalanms** [comment]
Fixed by https://github.com/dotnet/wpf/pull/949.
