### ISSUE TITLE
NET Core WPF applications are not high DPI aware by default

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#859]
Copied from VSO ID 860905

Affected Branch: rel/d16.1 
Affected Build:  Version 16.1.0 Preview 3.0 [28829.227.d16.1] + .NET Core SDK 3.0.100-preview5-011568
Affected Product Language: C#

**Steps to reproduce:**

1. Create a new .NET Core WPF project.
2. Open MainWindow.xaml in the designer.
3. Drag a button control onto the window.  Note that the designer appears to be high-DPI aware as the button is easily readable.
4. Run the application.

Expected results:
The window should match what the designer displayed, namely an easy to read button.

It should look like this:
![1](https://user-images.githubusercontent.com/49078227/58901159-74e6dc00-86b5-11e9-8a7e-3ef87d0701d5.png)

Actual results:
The window is small and the button has text that is very difficult to read.

It looks like this:
![2](https://user-images.githubusercontent.com/49078227/58901170-7a442680-86b5-11e9-907e-93659f1b625b.png)

Workaround:
Add a "app.manifest" file to the project with the following contents:

```xml
<?xml version="1.0" encoding="utf-8"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity version="1.0.0.0" name="foo"/>

  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitor</dpiAwareness>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
    </windowsSettings>
  </application>

</assembly>
```

In project properties, change Application -> Icon and Manifest -> Manifest to `app.manifest`.

By default, the apphost has the same manifest that a .NET Framework application executable has (the one generated by the C# compiler).  However, the .NET Framework application starts high DPI aware.

Also, it's hard to see the difference from the screenshots as they're being scaled in the issue, but there's a night and day difference with and without the manifest workaround.

**Comment by rladuca** [comment]
This is fixed in Preview 6, closing.

**Comment by matthewpetch** [comment]
Not fixed in preview 6, I've just had to follow @grubioe's workaround on a new WPF/dotnet core 3 preview 6 project

**Comment by 0xd4d** [comment]
Yes, this doesn't appear to be fixed. `Process Explorer` says it's `System Aware`, not `Per-Monitor Aware`.

**Comment by rladuca** [comment]
I think I see the confusion here.

All WPF applications are, by default, system DPI aware.  Applications must explicitly opt into per-monitor DPI awareness.  This is likely the difference you are seeing between the designer and your runtime application.  Visual Studio now opts into per-monitor DPI awareness.  The bug that was fixed in Preview 6 was adding back a module initializer that set the process to system aware by default.

So the difference between the designer and the runtime application isn't a bug (at least in WPF), it's how WPF has operated for years.  Please see [this guide](https://docs.microsoft.com/en-us/windows/desktop/hidpi/declaring-managed-apps-dpi-aware).

What is a good conversation to have is should/can the designer process inherit the DPI awareness of the application being designed?  I'm not sure if this is, currently, technically feasible to them or a desirable trait.  If I had a choice, I'd like them to have the same DPI awareness.

CC: @dotnet/wpf-developers Anyone have opinions on bringing this up to the designer team?

**Comment by cbaysinger** [comment]
The link "this guide" to "Developing a Per-Monitor DPI-Aware WPF Application" has a link for Windows 10 targets "This page covers legacy WPF development for Windows 8.1. If you are developing WPF applications for Windows 10, please see the latest documentation on GitHub." but the link to GitHub is broken.

**Comment by rladuca** [comment]
@cbaysinger Thanks for pointing that out.  The samples have been moved around a bit and it seems external links haven't been updated.  Try [this link](https://github.com/Microsoft/WPF-Samples/blob/master/PerMonitorDPI/readme.md) and also read the updated information about .NET 4.8 on [this page](https://devblogs.microsoft.com/dotnet/announcing-the-net-framework-4-8/).

@vatsan-madhavan Are there better links to high DPI documentation or are these the main ones right now?

**Comment by vatsan-madhavan** [comment]
Your link is the best one _right now_. 

I opened https://github.com/microsoft/WPF-Samples/issues/92 against myself - I'll get to it as soon as I can. 

That said, on .NET Core, the guidance for a _typical application_ ought to be something as simple as having an application manifest that contains something like this:

```xml
<!-- 
  https://docs.microsoft.com/en-us/windows/desktop/sbscs/application-manifests
-->
<application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <!-- dpiAwareness is recognized only on Win10 1607(aka RS1)+ --> 
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2,PerMonitor</dpiAwareness>
      <!-- Prior to Win10 1607, WPF really doesn't support per-mon DPI. Do not specify true/pm - use just true --> 
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
     <!-- optional -->
      <!--
     <highResolutionScrollingAware>true</highResolutionScrollingAware>
     <ultraHighResolutionScrollingAware>true</ultraHighResolutionScrollingAware>
      -->
    </windowsSettings>
  </application>
```
