### ISSUE TITLE
Crash in VS opening 'Naming'

### ISSUE THREAD

**Issue by SamBent** [dotnet/wpf#860]
Port from .Net 4.8 bug.

**Comment by priestm** [comment]
@SamBent I suspect our product might have also experienced this bug in .NET Framework 4.8. With the latest .NET Framework installed, when we select a row in a DataGrid, we are getting an exception inside the DataGridItemAutomationPeer constructor.

Are there any more details about this issue anywhere? Is there a timeline for the release of the fix? Is there any known workaround for the crash?

**Comment by priestm** [comment]
I've just found this report: https://developercommunity.visualstudio.com/content/problem/575165/vs-1604-ide-crash-argumentnullexception.html

It looks like the same issue, and you have provided a link to an update that should fix it. I'll give that a go. Thanks.
