### ISSUE TITLE
Need to embed wpf loose theme files into their theme assemblies

### ISSUE THREAD

**Issue by chabiss** [dotnet/wpf#865]
For the XAML tooling experience for WPF NetCore needs to be decoupled from .Net Framework.  The themes loose file will need to be embeded into their theme assemblies so that XAML Designer can extract theme when creating a copy of a template.  

Below is the table of the loose file to be included into their respective theme assemblies

XAML | Assembly
-- | --
aero.normalcolor.xaml | PresentationFramework.Aero.dll
aero2.normalcolor.xaml | PresentationFramework.Aero2.dll
aerolite.normalcolor.xaml | PresentationFramework.AeroLite.dll
classic.xaml | PresentationFramework.Classic.dll
luna.homestead.xaml | PresentationFramework.Luna.dll
luna.metallic.xaml
luna.normalcolor.xaml
royale.normalcolor.xaml | PresentationFramework.Royale.dll

**Comment by vatsan-madhavan** [comment]
This is something we have agreed with the VS team to deliver in Preview 8.

**Comment by weltkante** [comment]
Old framework had design time companion DLLs to distribute design time only customization and content, mostly in WinForms but WPF also supported this. If design time assemblies are still going to be a thing in .NET Core it may be worth to put these resources in there instead of the runtime assemblies?

It probably doesn't make much difference in term of deployment size, but may be worth for separation of concerns to keep designer specific resources in the design time assembly. Also may be worth to take a moment and think about whether it's worth to standardize/document how this works and allow 3rd party controls/themes to do the same.

**Comment by vatsan-madhavan** [comment]
> Old framework had design time companion DLLs

Which DLLs are you referring to?

**Comment by weltkante** [comment]
@vatsan-madhavan the DLLs you can put in a `Design` subfolder, usually with a `.Design.dll` suffix, which get picked up by the designer to provide design-time behavior.

**Comment by vatsan-madhavan** [comment]
I've been thinking about this a bit and chatted with winforms folks about it as well. 

It looks like the `*.design.dll` assemblies are being consumed as if they are _runtime assemblies_ by many applications. In effect, they are both _design time_ **and** _runtime_ assemblies, and any real benefits of compartmentalizing _design-time only_ assemblies form _runtime_ assemblies seems to be lost in many real scenarios. (BTW, `System.Drawing.Design.dll` is a facade in .NET Core that redirects to `System.Windows.Forms.Design.Editors.dll`)

WPF's theme assemblies are already a lot like _design time_ assemblies. Their payload (resources - namely BAML, as well as types under [`Microsoft.Windows.Themes`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windows.themes?view=netcore-3.0)) all about providing theming constructs, and they are already consumed at _design-time_ occasionally (to peek into the respective BAML, for e.g.). 

The general principle of _design-time_ assembly is appealing, but in this specific instance the distinction between `PresentationFramework.Aero2.dll` and (a hypothetical) `PresentationFramework.Aero2.Design.dll` seems rather slim. Even if we were to invent `PresentationFramework.Aero2.Design.dll` and embed these XAML files as resource in them, _design-time_  tools will likely to continue to load `PresentatitonFramework.Aero2.dll` to read the BAML, negating the _separation of concerns_ design goal. 

And finally, at this stage in the 3.0 (getting close to RC!), we don't want to add a new _construct_ (namely, _design-time_ assemblies) to WPF. 

We will revisit this in .NET 5, when we look into a better approach to delivering these same XAML resources to interested consumers (notably VS).

**Comment by vatsan-madhavan** [comment]
This is now available in `4.8.0-preview7.19319.15`  `runtime.win-x64.Microsoft.DotNet.Wpf.DncEng` package out of https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/index.json feed. 

I'd expect it to flow through core-setup into core-sdk shortly. 

![image](https://user-images.githubusercontent.com/20246435/59801967-5c71e680-929d-11e9-989d-92ede3ac82d1.png)
