### ISSUE TITLE
RelayCommand is used in Clear Button - Refactor to use Icommand

### ISSUE THREAD

**Issue by singhashish-wpf** [dotnet/wpf#8650]
RelayCommand is used in Clear Button

**Comment by batzen** [comment]
The addition of a class named RelayCommand will wreck havoc on most MVVM based applications using WPF.
Is it required for anything?
If it should be part of WPF itself choosing a different name would be wise.

**Comment by miloush** [comment]
Not unless it is in the same namespace? **_If_** it should be part of WPF, choosing name people are already familiar with sounds reasonable. How do you expect @batzen things to break? Or do you just expect conflicts when it is put into a namespace that people would normally have imported together with one for another RelayCommand class?

That said I agree it might not be justified just for the sake of clear button.

**Comment by batzen** [comment]
> How do you expect @batzen things to break? Or do you just expect conflicts when it is put into a namespace that people would normally have imported together with one for another RelayCommand class?

I will cause compile errors for most people.
I have a lot of UI code that uses my IRelayCommand interface and that UI code also uses System.Windows.Input.
What also will happen is:
People will accidentally start using the RelayCommand from WPF without noticing.
That might not be a problem for everyone, but it would be severe for the application i write at work for multiple reasons:
- CanExecuteChanged has to be triggered manually (our work implementation forwards the event to a custom implementation of CommandManager.RequerySuggested)
- Multiple executions are automatically prevented by guarding the execution
- etc. etc.

**Comment by ThomasGoulet73** [comment]
The issue is not very detailed but at first read to me it looks like the goal of this issue is to replace RelayCommand with ICommand. Maybe in their current Win11 Theming code RelayCommand is exposed publicly and this issue is about fixing this. The goal of this issue should probably be clarified.

**Comment by singhashish-wpf** [comment]
Yes, the issue was just created to fix the wpfui implementation of IRelayCommand, we didn't want to use it the same way or make it public for the reasons which @batzen has mentioned. As of now we aren't using this and hence the issue has no significance as of now.
