### ISSUE TITLE
ExpandDirection of an Expander not respected in Windows 11 Styles

### ISSUE THREAD

**Issue by harshit7962** [dotnet/wpf#8651]
### Description

The `ExpandDirection` property of an Expander does not work in Windows 11 styles. Irrespective of the value provided to `ExpandDirection` it always opens downwards.

### Reproduction Steps

Create a WPF Application supporting windows 11 themes. Create an expander with `ExpandDirection` property set to either `Right` or `Left` or `Up`.

### Expected behavior

The Expansion should happen in accordance to the value specified to `ExpandDirection`

### Actual behavior

The Expansion of contents happen downwards.

### Impact

Incorrect layout of applications designed to cater the specific needs.

### Configuration

.NET 9
Windows 11
x64

**Comment by dipeshmsft** [comment]
Closing this issue as it has been fixed in the working branch.
