### ISSUE TITLE
Document Microsoft Patent grants/licensing/etc...

### ISSUE THREAD

**Issue by JeroMiya** [dotnet/wpf#87]
**Motivation**
The MIT license grants a license for the source w.r.t. copyright, but not any patents that Microsoft may have that cover the software. Even using this software for its intended purpose, i.e. writing Windows apps, potentially exposes users to patent infringement liability.

**Suggestion**
It would be nice to have some documentation from Microsoft that includes:
- What Microsoft-owned patents might cover functionality in WPF.
- Which of those patents already have public grants/licenses such as OIN, and under what terms.
- Instructions for licensing said patents, if not covered by an existing grant.

**Comment by legistek** [comment]
Related to this, could someone from Microsoft please clarify whether everything currently in `PresentationCore` and `PresentationFramework` (https://referencesource.microsoft.com/) is now covered by MIT, or is it only the code in this repo? In other words is WPF only being open sourced bit by bit or is the full current version of WPF now licensed under MIT? Thanks!

**Comment by karelz** [comment]
@legistek each source location has its own license. MIT license here affects only code here. Reference source (there are 2) have their own licenses. They are unchanged by this effort.

**Comment by legistek** [comment]
Thanks @karelz! So in other words it's not so much that all of WPF is now suddenly open source, but rather y'all are in the process of porting the existing WPF codebase to an open source model. That helps clarify some of the popular reporting. :)

**Comment by karelz** [comment]
@legistek correct - we tried to cover that in our README.md: https://github.com/dotnet/wpf#status

**Comment by richlander** [comment]
I meant to reply to this back in December, but work and life got in the way. Someone on the team just re-pointed me to this today.

Here is our answer to the questions on patents:

> When Microsoft made this code available as open source under the MIT license, our intent was that anyone in the community can use this code as long as they comply with the license. You do not need any additional patent grants from Microsoft to use this code.
