### ISSUE TITLE
PasswordBox styles not working

### ISSUE THREAD

**Issue by harshit7962** [dotnet/wpf#8706]
### Description

The `PasswordBox` styles in new windows 11 theme does not work.

### Reproduction Steps

1) Create a WPF application that supports Windows 11 styles
2) Create a PasswordBox

### Expected behavior

The PasswordBox should have a new look and feel

### Actual behavior

PasswordBox looks as usual

**Comment by dipeshmsft** [comment]
Create a PR for feature/win11theming/staging branch if needed.

**Comment by dipeshmsft** [comment]
This is already fixed in the main branch, hence closing the issue.
