### ISSUE TITLE
System.Printing Support

### ISSUE THREAD

**Issue by shaggygi** [dotnet/wpf#871]
This was created based on a discussion from https://github.com/dotnet/corefx/issues/37978

> I was trying to port an API to .NET Core that uses System.Printing PrintServer and related.  I came across this [doc](https://docs.microsoft.com/en-us/dotnet/api/system.printing.printserver?view=netcore-3.0) and have the impression System.Printing is supported.

I was informed ([from issue link above](https://github.com/dotnet/corefx/issues/37978#issuecomment-498908611)) this is part of WPF and can be use by creating a `dotnet new wpf`.  However, I would like to use as a Class Library even if it must use the Win Compatibility package and Windows only.

We have many APIs to create/print labels that call the System.Printing APIs.  It would be nice to continue the same approach using WPF with .NET Core v3 and beyond.

Thanks in advance for any help.  It will be appreciated.

**Comment by dsplaisted** [comment]
You can add the following to a .NET Core 3.0 class library project in order to access System.Printing:

```xml
<ItemGroup>
  <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
</ItemGroup>
```

**Comment by shaggygi** [comment]
Thanks team for all the help.  I was able to change one of our label and printer APIs to a .NET Core Class Library project and now works similar to .NET (full framework).
