### ISSUE TITLE
Menu styles inconsistent in Windows 11 Theme

### ISSUE THREAD

**Issue by harshit7962** [dotnet/wpf#8742]
### Description

The styles for menu and menu item is inconsistent when using dark theme for windows 11 applications. The menu items are not visible in dark theme.

### Reproduction Steps

1) Create a WPF application that supports Windows 11 styles
2) Create a menu control with some menu items
3) Turn the system to dark theme
4) Launch the application

### Expected behavior

The menu items should be visible with white color

### Actual behavior

Menu items are not visible as they are in black color and background is black in color as well.

### Configuration

Windows 11
.NET 9
x64

**Comment by dipeshmsft** [comment]
@harshit7962 , I guess this is fixed as well right ? In that case, let's go ahead and close this.
