### ISSUE TITLE
Custom RoutedEvents Don't Propagate

### ISSUE THREAD

**Issue by kellyelton** [dotnet/wpf#8761]
### Description

When I create a `RoutedEvent` and try any routing mode (except Direct), the event never ends up firing in WPF.

### Reproduction Steps

```
    <Border x:Name="MainBorder">
        <Border.Resources>
            <Storyboard x:Key="ShowStoryboard">
                <DoubleAnimation Storyboard.TargetProperty="Opacity" From="0" To="1" Duration="0:0:0.8"/>
                <DoubleAnimation Storyboard.TargetProperty="Height" From="10" To="350" Duration="0:0:0.3"/>
            </Storyboard>
            <Storyboard x:Key="HideStoryboard">
                <DoubleAnimation Storyboard.TargetProperty="Opacity" From="1" To="0" Duration="0:0:0.4"/>
                <DoubleAnimation Storyboard.TargetProperty="Height" From="350" To="10" Duration="0:0:0.5"/>
            </Storyboard>
        </Border.Resources>
        <Border.Triggers>
            <EventTrigger RoutedEvent="local:MainWindow.ShutdownStarted">
                <BeginStoryboard Storyboard="{StaticResource HideStoryboard}"/>
            </EventTrigger>
            <EventTrigger RoutedEvent="FrameworkElement.Loaded">
                <BeginStoryboard Storyboard="{StaticResource ShowStoryboard}"/>
            </EventTrigger>
        </Border.Triggers>
        <Border.Style>
            <Style TargetType="Border">
                <Setter Property="Opacity" Value="0"/>
                <Setter Property="Height" Value="10"/>
                <Setter Property="Width" Value="450"/>
            </Style>
        </Border.Style>
```
        
        
```
    public static readonly RoutedEvent ShutdownStartedEvent = EventManager.RegisterRoutedEvent(
        nameof(ShutdownStarted),
        RoutingStrategy.Bubble,
        typeof(RoutedEventHandler),
        typeof(MainWindow)
    );

    public event RoutedEventHandler ShutdownStarted {
        add { AddHandler(ShutdownStartedEvent, value); }
        remove { RemoveHandler(ShutdownStartedEvent, value); }
    }
```
    
`    RaiseEvent(new RoutedEventArgs(ShutdownEventStarted));`

### Expected behavior

When I raise the event, the border should fade out. It does not.

### Actual behavior

The border doesn't change.

### Regression?

This code work fine in .net 4.8 and WPF

### Known Workarounds

You have to call RaiseEvent on the actual element that's listening for the event.

In this case, I have to call `RaiseEvent(new RoutedEventArgs(ShutdownEventStarted))` to get the Trigger to work.

### Impact

Maybe I misunderstand the state of dotnet and wpf, but I had assumed it was production ready. This is a pretty big issue I think.

### Configuration

dotnet core 8
Windows 11
Visual Studio 17.9.0 Preview 3.0
x64

### Other information

Same problem happens with or without visual studio and with or without debugging.

**Comment by MichaeIDietrich** [comment]
Your sample is not complete so I can only assume that the `Border` is direct child of the `MainWindow` 
and `RaiseEvent(new RoutedEventArgs(ShutdownEventStarted))` is invoked on the `MainWindow`.

Routed events work as they are meant to work:
> [Bubbling](https://learn.microsoft.com/en-us/dotnet/api/system.windows.routingstrategy#system-windows-routingstrategy-bubble): Initially, event handlers on the event source are invoked. The routed event then routes to successive parent elements, invoking their event handlers in turn, until it reaches the element tree root. Most routed events use the bubbling routing strategy. Bubbling routed events are generally used to report input or state changes from composite controls or other UI elements.
https://learn.microsoft.com/en-us/dotnet/desktop/wpf/events/routed-events-overview?view=netdesktop-8.0#routing-strategies

As defined events bubbling from the event source to the root and since it is invoked on the `MainWindow` it never passes the `Border` as the the `Border` is a child and not a parent of the `MainWindow`.

The behavior is identical between .NET Framework and .NET (Core) and works as specified.

Feel free to add a full sample project how this works with .NET Framework, since as mentioned I had to do some assumptions here from your reproduction steps.

**Comment by kellyelton** [comment]
Replacing the routing strategy with Tunneling also does not work

**Comment by kellyelton** [comment]
Yes, the border is a child of the Window, that would be a safe assumption.

**Comment by kellyelton** [comment]
I tested in this .net framework and it also doesn't work, including using Tunneling instead of Bubbling. I must be misunderstanding something about Routed Events.
