### ISSUE TITLE
Relative Binding Find Ancestor does not work

### ISSUE THREAD

**Issue by kellyelton** [dotnet/wpf#8762]
### Description

Using RelativeSource does not actually seem to work.

### Reproduction Steps

```
<Window x:Class="Asdf.Tester"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Asdf"
        mc:Ignorable="d"
        Title="Tester" Height="450" Width="800">
    <Grid>
        <TextBlock
                Text="{Binding Source={RelativeSource AncestorType=local:Tester, Mode=FindAncestor}, Path=Status, TargetNullValue='...', FallbackValue='...'}"
                FontSize="20"
                HorizontalAlignment="Center"
                VerticalAlignment="Bottom"
                Margin="0 10 0 10"
            />
    </Grid>
</Window>
```

```
namespace Asdf;

public partial class Tester : Window
{
    public static readonly DependencyProperty StatusProperty = DependencyProperty.Register(
        nameof(Status),
        typeof(string),
        typeof(Tester),
        new PropertyMetadata("Loading...")
    );

    public string Status {
        get { return (string)GetValue(StatusProperty); }
        set { SetValue(StatusProperty, value); }
    }

    public Tester() {
        InitializeComponent();
    }
}
```

![image](https://github.com/dotnet/wpf/assets/1356163/4682b53c-6183-4a4d-a1a8-81649311df07)

### Expected behavior

I would expect that the TextBlock says 'Loading...', but it does not.

### Actual behavior

The TextBlock just displays the fallback value, even if you try and change the DependencyProperty.

### Regression?

This code work as is in .net framework 4.8.

### Known Workarounds

You have to name the window, and then bind to the element instead

```
<Window x:Class="Asdf.Tester"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Asdf"
        mc:Ignorable="d"
        x:Name="thiswin"
        Title="Tester" Height="450" Width="800">
    <Grid>
        <TextBlock
                DataContext="{Binding ElementName=thiswin}"
                Text="{Binding Path=Status, TargetNullValue='...', FallbackValue='...'}"
                FontSize="20"
                HorizontalAlignment="Center"
                VerticalAlignment="Bottom"
                Margin="0 10 0 10"
            />
    </Grid>
</Window>
```

### Configuration

dotnet core 8

**Comment by kellyelton** [comment]
I'm really not meaning to be rude, but there are too many bugs in WPF with dotnet core right now to consider this product production ready in my opinion.

I've been using WPF almost daily since maybe 2011 or something. So it gets frustrating trying to use all of my old knowledge, and half of the time things don't work as I expect. I have spent way too many hours troubleshooting these issues at this point, because I never expect it to be an issue with the framework. Unfortunately with WPF and dotnet core, it always ends up being an issue in the framework I have to work around.

I'm not trying to dog on the hard work you developers have put in, bugs happen, it's just a part of software. None of use write perfect code. This is a message to whoever decided to flip the switch and decide the framework was ready for prime time. While bugs do happen, there should not be so many basic bugs in a "production ready" framework from Microsoft.

**Comment by MichaeIDietrich** [comment]
There is an issue in your `Binding`.
You need to use the `{RelativeSource}` markup extension in conjunction with the `RelativeSource` `Binding` property.

So just update your `Binding`
`Text="{Binding Source={RelativeSource AncestorType=local:Tester, Mode=FindAncestor}, Path=Status}"` to
`Text="{Binding RelativeSource={RelativeSource AncestorType=local:Tester, Mode=FindAncestor}, Path=Status}"`,
then it works just fine.

I did not test whether your code worked in .NET Framework, but even if, that's not the way it is supposed to be used.

**Comment by IAmTheCShark** [comment]
Confirming whar @MichaeIDietrich wrote. It's `RelativeSource=...` not `Source=...`

**Comment by kellyelton** [comment]
Good catch, you're right.
