### ISSUE TITLE
The name 'InitializeComponent' does not exist in the current context (CS0103), MainWindow.xaml.cs

### ISSUE THREAD

**Issue by dmartinezfernandez** [dotnet/wpf#8779]
I get this annoying message from Visual Studio Code with every WPF application a create from scratch (.NET 8):
`dotnet new wpf -n WpfApp1`

![image](https://github.com/dotnet/wpf/assets/24685301/ddee6139-b5c2-4369-893a-af84e63e46c5)

Nevertheless, `dotnet build` and `dotnet run` work fine. Neither I find this issue from Visual Studio. It is only from Visual Studio Code.

**Comment by miloush** [comment]
Perhaps this needs to be raised with VSCode then? It would need support running the compiler in the background and use the generated code in the code editor. You might get a better experience from an actual IDE.

**Comment by dmartinezfernandez** [comment]
Yes, I think so, this needs to be raised with VSCode or rather their C#
extension.
Thank you.
