### ISSUE TITLE
An ActiveX control hosted in a WindowsFormsHost is redrawn incorrectly after resizing the host window.

### ISSUE THREAD

**Issue by cbaysinger** [dotnet/wpf#878]
* .NET Core Version: (e.g. 3.0 Preview15-27626-15)
* Windows version: (1809(OS Build 17763.503)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No in 4.7.2

 
 
ActiveX control is redrawn shifted to the left and up such that its left and top edge are clipped when the control has focus and the window is resized. The control continues to shift left and up as the above steps are repeated. 
<img width="367" alt="image" src="https://user-images.githubusercontent.com/22218080/58994284-d46fe500-87a4-11e9-8bce-98c759c111a5.png">

I found this issue while attempting to port our code to Core3. 
We have a highly customized ActiveX graphing control that we moved from MFC to WPF a couple of years ago. 
We are now moving to Core 3 and noticed a problem with the control. When a user clicks on the graph it is redrawn shifted to the left and up such that its left and top edge are clipped.
We then tested several other ActiveX components and found similar behavior although resizing the host window was required to reproduce the shifted drawing.
Just to rule out our ActiveX controls we built a sample button from GetHub\VCSamples-master\VC2008Samples\MFC\controls\button and observed the same behavior although it throws a pair of unrelated exceptions when the window loses focus.

Expected Behavior:
Building the same application but using .Net 4.7.2 does not display the drawing defect although the exceptions are thrown by the sample button. The control simply changes size as the window changes size.

Minimal Repro:
Using Visual Studio 2019 Preview Version 16.1.0 Preview 3.0 create a new WPF application using .NET Core 3.
Add to the MainWindow.xaml a Loaded event and a 3x3 grid containing a WindowsFormsHost in row 1 column 1. Set the background property of the WindowsFormsHost to yellow and the grid background to azure or any contrasting color.
To Dependencies add a registered ActiveX component wrapped by aximp.exe to the Assemblies and add NuGet Microsoft.NETCore.App.Host.win-x86 (3.0.0-preview5-27626-15).
In MainWindow.xaml.cs add the Window_Loaded event and within the function new the button and assign it to WindowsFormsHost.Child.

Alternatively the two projects at https://1drv.ms/f/s!AB8PEB5wHC4Jeg contain the button control and the WPF application. 
After building the button control register it using regsvr32.
Then create the import wrapper by running aximp.exe. 
In my case C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools>aximp.exe button.ocx /out: C:\Download\MS MFC Samples\GetHub\VCSamples-master\VC2008Samples\MFC\controls\button\Debug\AxInterop.button.dll
Next build the WPF application and ensure the following dependencies: 
Under Assemblies AxInterop.button  
NuGet Microsoft.NETCore.App.Host.win-x86 (3.0.0-preview5-27626-15) 

1. Run the app
2. click the button
3. Resize the window by dragging lower right corner 
4. button is redrawn with boarder on all sides
5. Minimize the window
6. Restore the window. Button is now drawn in the upper left corner of the WindowsFormsHost
7. Repeat steps 2-4, button is redrawn with small boarder at top-left, larger boarder bottom-right.
8. Repeat steps 5-6, button is redrawn in upper left corner with large boarder at bottom-right.
9. As these steps are repeated the button's upper left corner is increasingly clipped.

**Comment by rladuca** [comment]
@cbaysinger Can you try this against the latest daily builds and let me know if this reproduces?  This might be related to #334 which we fixed post-Preview 5.  It's currently available in daily builds and will be in Preview 6.

**Comment by cbaysinger** [comment]
Congratulations, the release at https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries Release /3.0.1 fixed the problem.

**Comment by rladuca** [comment]
Closing as it's fixed.
