### ISSUE TITLE
ReadLocalValue Within DataTemplate Always Returns UnsetValue

### ISSUE THREAD

**Issue by KatoFett** [dotnet/wpf#8786]
### Description

DependencyObject.ReadLocalValue always returns DependencyProperty.UnsetValue if the element is coming from a DataTemplate, irrespective if the value is actually set.

### Reproduction Steps

XAML: Define a DataTemplate for a type. Render the content using any kind of ContentPresenter.
C#: Get the visual content and compare the value returned from ReadLocalValue to the value returned from GetValue.

(MRE here: https://github.com/KatoFett/LocalValueDebugRepo)

### Expected behavior

ReadLocalValue should return the value set in the XAML.

### Actual behavior

ReadLocalValue returns DependencyProperty.UnsetValue.

### Regression?

No.

### Known Workarounds

None.

### Impact

Because we are unable to reliably check whether a property is set locally, it is impossible to conditionally apply bindings or values to properties.

### Configuration

.NET 7 (unable to test 8 yet)

**Comment by miloush** [comment]
That seems correct to me. The button instance you are querying has the value from the template, it does not have it set locally. You can find out where a value comes from using `DependencyPropertyHelper.GetValueSource`.

Can you elaborate on what are you trying to conditionally achieve? Maybe we can come up with better solution.

**Comment by KatoFett** [comment]
I'm creating a custom control that extends `Grid`. It does other things, but has a custom `Padding` property that gets applied to each child element's margin. The problem is that I want the client to be able to override it for specific elements. My train of thought was that if the value is set locally, like in my repo, then the control should skip binding the margin.

The condition I was using was `if(child.ReadLocalValue(MarginProperty) == DependencyProperty.UnsetValue) { ... }` which worked except for when the custom grid is placed inside a `DataTemplate`, like in an `ItemsControl`. After reading your comment, I've changed it to `if(valueSource.BaseValueSource == BaseValueSource.Default) { ... }` and it seems to work, though I might still be missing something.

**Comment by KatoFett** [comment]
The layouts are static in my case so the children will never do that. If they did, I would probably make the control wrap each child in a `Border` or something and put the margin on it instead, so the children can have their own margins. The attached property would be necessary in this case. I may just do that anyways, especially since my current solution needs to wait on the Dispatcher to get the binding correctly.

Since `DependencyPropertyHelper.GetValueSource` has fixed my problem so far, I'm going to close this issue.
