### ISSUE TITLE
The GetHashCode implementation of the Thickness struct is broken for uniform length.

### ISSUE THREAD

**Issue by davidskula** [dotnet/wpf#8789]
### Description

For any uniform length instance of Thickness struct GetHashCode returns zero.

### Reproduction Steps

```
var h1 = new Thickness(5).GetHashCode();
var h2 = new Thickness(10).GetHashCode();
```

### Expected behavior

h1 and h2 should have different values

### Actual behavior

h1 and h2 have the same value

**Comment by lindexi** [comment]
The reason is:

https://github.com/dotnet/wpf/blob/19f227f76e8d3789f1fcb762410c56d88584b88f/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Thickness.cs#L96-L99

I'm not sure I can change its behavior.
