### ISSUE TITLE
Update Roadmap

### ISSUE THREAD

**Issue by dotMorten** [dotnet/wpf#8808]
### Description

The [Roadmap](https://github.com/dotnet/wpf/blob/main/roadmap.md) is very much out of date, and haven't seen an update since May 2023. The first table alone still lists things that were completed in .NET 8 Preview 1, and everything on that list is marked as completed.

The .NET 9 Preview 1 blogpost just went live and links to this roadmap and it reflects really poorly on WPF that this roadmap isn't updated along with those announcements.

**Comment by pchaurasia14** [comment]
@dotMorten - Yes, you're right. We're working on this and should have the updated roadmap out as soon as possible.

**Comment by lindexi** [comment]
I think everyone will be amazed by the Windows 11 theme feature.

**Comment by lindexi** [comment]
Can close this by https://github.com/dotnet/wpf/pull/8825 ?
