### ISSUE TITLE
System.Windows.Media MediaPlayer class does not load audio when Ccr.PresentationCore is used by itself.

### ISSUE THREAD

**Issue by Floodh** [dotnet/wpf#8885]
### Description

I wan't to be able to use the media player from Ccr.PresentationCore on its own regardless of which graphic library or framework I'm using for the UI, or maybe I don't even wan't graphics in the first place.
Previously I've been able to use MediaPlayer class alongside a project I made with SDL2 a while back, but now when I'm trying to rewrite this project with MonoGame, the WPF media player is unable to load a simple .wav file and as such can't play any audio.

### Reproduction Steps

Note that I'm not using WPF, I'm just trying to use the media player on its own. This should work.

Sample code:
```cs
using System.Windows.Media;

class MainClass
{
    static MediaPlayer mediaPlayer = new MediaPlayer();

    [STAThreadAttribute]
    static int Main()
    {

        Console.WriteLine("Start");

        string path = "ytdlp_AjspnMNkGu8.wav";
        Console.WriteLine($"    File exist : {File.Exists(path)}");

        Uri uri = new Uri(path, UriKind.Relative);
        Console.WriteLine($"    {uri}");

        mediaPlayer.Open(uri);
        Console.WriteLine($"    has audio : {mediaPlayer.HasAudio}");

        mediaPlayer.Play();
        Console.WriteLine($"    trying to play audio");

        Thread.Sleep(100000);
        
        Console.WriteLine("End");
        return 0;
        
    }

}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Ccr.PresentationCore" Version="4.0.0" />
<!-- These packages do not fix the problem.
    <PackageReference Include="Ccr.Std.Core" Version="3.1.0" />
    <PackageReference Include="Ccr.Std.Introspective" Version="2.0.0" />
    <PackageReference Include="Ccr.WinCore" Version="4.0.0" />
    <PackageReference Include="Microsoft-WindowsAPICodePack-Core" Version="1.1.5" />
    <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.5" /> -->
  </ItemGroup>
</Project>

```

### Expected behavior

I expect the ``MediaPlayer.Open`` function to result in audio being loaded and the property ``HasAudio`` to read true. After which the selected audio should be played with ``MediaPlayer.Play``.

### Actual behavior

The program compiles and can be run, however the ``HasAudio`` property remains false and no audio is played.

### Regression?

I'm pretty sure that the media player used to work perfectly fine with .net 5 and .net 6. I have tried to verify this, but for some reason it does not work even when i target ``net5.0-windows`` and ``net6.0-windows`` so maybe I'm misremembering it.

### Impact

There is currently no easy to use media player that can play audio files supporting volume adjustment and positioning in .NET.
The SoundPlayer class from ``System.Media`` work but does not have these features.

### Configuration

dotnet version: 8.0.201
Windows 10
x64

**Comment by Floodh** [comment]
No, I can issue there instead. But when I look at [this page](https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.mediaplayer?view=windowsdesktop-8.0) the assembly used is PresentationCore.dll. Is there a way I could create a reference to that and make the media player work that way?

**Comment by miloush** [comment]
It works for me using the WPF assembly. Maybe it's an unsupported audio format? Can you share your project including the audio file?

**Comment by Floodh** [comment]
The project is just the .csproj file and .cs file I've shared Reproduction Steps.
I use the dotnet sdk, as in i type ``dotnet run`` in the terminal to run it.
As for the audio file, I just used I random .wav file I've downloaded from youtube.

**Comment by singhashish-wpf** [comment]
@Floodh Is it not working for any other audio files too?

**Comment by Floodh** [comment]
Going back to what miloush stated with Ccr packages not being maintained by microsoft. This issue might be out of scope. I have made a new [issue](https://github.com/vreniose95/Ccr/issues/8) at the appropriate repository.

This issue is now essentially a feature request where I want the media player to be usable outside of a WPF application for playing audio files. Maybe through a official nuget package?

**Comment by miloush** [comment]
As I said the player works with your sample code. Provide a repro application with an audio file if you think something is wrong in WPF.

**Comment by Floodh** [comment]
[TestMediaPlayer.zip](https://github.com/dotnet/wpf/files/14563433/TestMediaPlayer.zip)

Output from running this:
```
Start
    has audio : False
End
```

**Comment by miloush** [comment]
Thank you, that was helpful.

Two issues: You are using relative Uri, but you are not copying the audio file to the output directory next to the binary. Put the audio next to exe (or in Visual Studio, set the _Copy To Output Directory_ property to something else than _Do not copy_. This is already noted both in the [MediaPlayer](https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.mediaplayer) documentation as well as [Multimedia Overview](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/multimedia-overview).

Second, you are checking `HasAudio` too soon, it takes some time to load the media. However, `Play()` can be called before that is set.

**Comment by Floodh** [comment]
Thanks this helped me discover the problem.

The problem or rather what confused me, turned out to be that the media player always uses the output directory as its directory. Unlike lets say the ``System.IO.File.Exist()`` function, which in my case uses the directory of the .csproj file. I always thought that it was more of a Visual Studio thing to always use the output directory, but it seems to be tied to the class itself this time.

Sidenote: The documentation says that I need to mark content to be outputed to the output directory, but since that I in my actual project would be downloading audio files during runtime I did not consider doing this. In hindsight I should have considered that this meant that the media player could be using the output directory no matter what, but this was not obvious to me.
 
Thanks a lot for the help and sorry for the confusion.

**Comment by miloush** [comment]
Any file API also works out of current directory when using relative paths, I would be surprised if WMP API used different one than IO API. You can check and set the current directory using `System.Environment.CurrentDirectory`.

If your app is not running from a remote site, much better practice would be to resolve your file to a full path or absolute Uri and use that. In some cases, it is a security concern if you allow user to make you load a file from a relative path that navigates out of your application directory. Especially since WMP allows scripting.

**Comment by Floodh** [comment]
If i run a program with Visual Studio the CurrentDirectory is ``C:\Users\User\Desktop\Project\CS\Test\bin\Debug\net8.0-windows``
However if i run the same program using a CLI command the CurrentDirectory is just ``C:\Users\User\Desktop\Project\CS\Test``

But the media player only finds the file using a relative Uri if its placed in ``C:\Users\User\Desktop\Project\CS\Test\bin\Debug\net8.0-windows`` regardless of whether I used Visual Studio or a CLI command to run the program. Correct me if I'm wrong, but doesn't that mean that the media player can in some cases work out of a different directory than ``System.Environment.CurrentDirectory`` ?

I will for the time being be using absolute paths to solve this issue.
