### ISSUE TITLE
Use ThemeGenerator for new Win11 Theme

### ISSUE THREAD

**Issue by singhashish-wpf** [dotnet/wpf#8904]
### Description

Currently there are multiple xamls being added, and they are using DynamicResources at multiple places, this can potentially cause delays in xaml parsing, memory consumption and slowness. Fix the new win11 theme to work with themegenerator to have a single  theme optimized theme file as in other themes.
related: https://github.com/dotnet/wpf/pull/8870#discussion_r1524158549

### Reproduction Steps

Build and test

### Expected behavior

The new theme should be like how other themes in wpf work. Should be optimized, use StaticResources and single file.

### Actual behavior

High memory, slow, high parsing time.

### Regression?

No

### Impact

High memory, slow, high parsing time.

**Comment by dipeshmsft** [comment]
Complete this, with the introduction of ThemeGenerator.Fluent.ps1
