### ISSUE TITLE
DataGrid row validation does not triggered unless the focus moved out of the row immediately.

### ISSUE THREAD

**Issue by zewditu** [dotnet/wpf#8914]
### Description

I have a DataGrid row validation rule that validates the value in each cell. However, row validation is triggered only when the focus moves out of the row. When I violate a rule in one cell and move to the next cell, it does not trigger. Even after moving out of the row, it does not trigger the row validation

### Reproduction Steps

1. DataGrid row with validation rule.
2. Violate the row in one of the cell.
3. Move the focus to any cell in the same row.

### Expected behavior

After a violation of the row happen in cell it should trigger.

### Actual behavior

No validation rule happen.

**Comment by miloush** [comment]
Please attach a repro project.

**Comment by zewditu** [comment]
Here is Repohttps://dev.azure.com/devdiv/DevDiv/_git/vs-resource-explorer

**Comment by zewditu** [comment]
Closed: the couse of the issue is because of customized WPF DataGrid in our repo.
