### ISSUE TITLE
WPF UserControl Hosted in Winform - NullReferenceException

### ISSUE THREAD

**Issue by SamBent** [dotnet/wpf#898]
(Port of bugfix in .NET 4.8)

The issues is that when a WPF UserControl has a reference to the Form hosting (using ElementHost) and the UserControl tries to close the Form from a keystroke it will cause a NullReferenceException.

**Comment by vatsan-madhavan** [comment]
@SamBent - if #649 fixes this issue, can this be closed?

**Comment by SamBent** [comment]
@vatsan-madhavan - #649 does not _fix_ this issue, it's a _duplicate_ of this issue.

**Comment by SamBent** [comment]
Fixed by checkin in wpf_int

**Comment by GLantaff** [comment]
Any idea when this fix will make it to a release? Major pain to get this exception all the time.

**Comment by SamBent** [comment]
The fix is in .NETCore 3.0 Preview 7, released last week.
For .NET Framework, the fix will be included when .NET 4.8 is released through Windows Update.  There's not a publicly-announced date for that, but it will likely happen within a couple of months.

**Comment by GLantaff** [comment]
Wow. I wish I knew this fix was that long coming. I could have told our users to not allow update to the Windows 10 1903 (as that is when the .NET update was installed). Our application is pretty sick on 1903.

Is there a way to uninstall the version of .NET framework that has this bug?

**Comment by SamBent** [comment]
1903 comes with .NET 4.8;  you can't uninstall it.

**Comment by SamBent** [comment]
This issue tracks the port of the fix into .NETCore (it's in .NETCore 3.0 Preview 7).
For .NET Framework 4.8, please consult [https://github.com/microsoft/dotnet-framework-early-access/issues/62](https://github.com/microsoft/dotnet-framework-early-access/issues/62).
