### ISSUE TITLE
Error MediaElement when play (.net framework)

### ISSUE THREAD

**Issue by BaoToan305** [dotnet/wpf#9146]
I'm learning about WPF and having a problem with MediaElement. Why when i try to play video with MediaElement it allways error output " Object reference not set to an instance of an object ". In spite of MediaElement is not null and source is not null too. I use link url to play . I need help to fix this.
![image](https://github.com/dotnet/wpf/assets/72989660/877e5974-1c24-44eb-8c63-4ac68cf70b42)

[WpfApp1.zip](https://github.com/dotnet/wpf/files/15399074/WpfApp1.zip)
this is a project i do

**Comment by miloush** [comment]
Sorry this is a bug in the .NET Framework.
https://ref12.io/net472?rightProjectId=PresentationCore&file=Core%5cCSharp%5cSystem%5cWindows%5cMedia%5cMediaPlayerState.cs&line=988 doesn't check for null (the whole premise of forbidding cross-domain https requests seems unreasonable at best).

If you need to play videos with https URL, your options are either to switch to .NET Core WPF or download the file first (or make it available over http).

**Comment by lindexi** [comment]
Reference https://github.com/dotnet/wpf/issues/722

**Comment by miloush** [comment]
Closing as duplicate then!

**Comment by lindexi** [comment]
As [vishalmsft](https://github.com/vishalmsft) says, *This is not planned to be taken in 4.8*. See https://github.com/dotnet/wpf/issues/722#issuecomment-1011950093
