### ISSUE TITLE
Why do combobox item and radiobutton have a hand cursor?

### ISSUE THREAD

**Issue by Symbai** [dotnet/wpf#9150]
### Description

I just downloaded the WPF gallery to see the windows 11 style. On comobox page the items have a hand as cursor. I opened the windows 11 settings app to verify this is NOT how it should be.

Same for radio button

### Reproduction Steps

Open combobox selection or radiobutton page in WPF gallery

### Expected behavior

Normal cursor

### Actual behavior

Hand cursor

### Other information

https://github.com/dotnet/wpf/assets/14368203/911a26cd-366a-45df-9878-f69d71dcce94

https://github.com/dotnet/wpf/assets/14368203/c8c124a1-bb32-49c1-b823-206bc7cb84d2

**Comment by huiliuss** [comment]
Cursor: Represents the image used to paint the mouse pointer. You can use it to change different mouse icons
Cursor has default settings on some controls . If you want the mouse to be an arrow icon when placed on RadioButton and ComboBox, you can refer to the following code
```xaml

<Grid>

    <Grid.Resources>

        <Style x:Key="MyStyle_1" TargetType="RadioButton">

            <Setter Property="Cursor"  Value="Arrow"></Setter>

        </Style>

        <Style x:Key="MyStyle_2" TargetType="ComboBoxItem">

            <Setter Property="Cursor"  Value="Arrow"></Setter>

        </Style>

    </Grid.Resources>

    <StackPanel>

        <GroupBox>

            <StackPanel >

                <RadioButton IsChecked="True" >A</RadioButton>

                <RadioButton>B</RadioButton>

            </StackPanel>

        </GroupBox>

        <ComboBox Cursor="Arrow">

            <ComboBoxItem >Q</ComboBoxItem>

            <ComboBoxItem >W</ComboBoxItem>

            <ComboBoxItem >E</ComboBoxItem>

        </ComboBox>

    </StackPanel>

</Grid>

```

**Comment by miloush** [comment]
I believe the report is that the default value is wrong in the Win11 styles work-in-progress and I agere.

**Comment by Symbai** [comment]
@huiliuss Thanks but @miloush is correct.
