### ISSUE TITLE
Remove PresentationUI ref assembly from WPF

### ISSUE THREAD

**Issue by miguep** [dotnet/wpf#918]
Before preview 7, we need to ensure that PresentationUI does not generate a ref assembly.
In .NET Framework, this never shiped as a ref assembly and shouldn't be included in the .NET Core set either.

**Comment by miguep** [comment]
This work has been done in an internal PR:
https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/1503?_a=overview

**Comment by miguep** [comment]
We've reverted this change, there is a problem with ref assembly generation for PresentationFramework that causes it to reference PresentationUI, until we fix this we should continue to produce this ref assembly

**Comment by vatsan-madhavan** [comment]
Moving to rob to roll into ref-assembly generation work.

**Comment by rladuca** [comment]
This will be fixed by the GenAPI work, so I'm going to just close this as a dupe against that.  In fact, the GenAPI branch already doesn't generate the reference assembly for this binary.

Closing in favor of #932
