### ISSUE TITLE
ContentControl does not display Content of a DataTemplate

### ISSUE THREAD

**Issue by Freddo37** [dotnet/wpf#9190]
I'm trying to make my windows jump between views and following SingletonSean example of navigation in WPF following MVVM architecture i saw that this no longer works in NET.8 but not sure why and how to fix it.

MainViewModel.cs

```
using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PointOfSale.ViewModels
{
    public partial class MainViewModel : ObservableRecipient
    {
        [ObservableProperty]
        public ObservableObject currentViewModel = new MenuViewModel();
    }
}
```

I add a Property to hold the currentViewModel in the DataContext of the MainWindows and add a DataTemplate for the ViewModel type and its corresponding View in the XAML Markup of the MainWindows.

MainWindow.xaml
```
<Window x:Class="PointOfSale.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:PointOfSale"
        xmlns:vs="clr-namespace:PointOfSale.Views"
        xmlns:vms="clr-namespace:PointOfSale.ViewModels"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Window.DataContext>
        <vms:MainViewModel></vms:MainViewModel>
    </Window.DataContext>
    <Window.Resources>
        <DataTemplate DataType="{x:Type vms:MenuViewModel}">
            <vs:MenuView></vs:MenuView>
        </DataTemplate>
    </Window.Resources>
    <Grid>
        <ContentControl DataContext="{Binding CurrentViewModel}">
        </ContentControl>
    </Grid>
</Window>
```

Then i add a ContentControl to the Grid and set its DataContext to the currentViewModel property, I expected just as in the video example, the ContentControl to display the View (Mapping the current typeof the currentViewModel to the DataType of the DataTemplate is my guess as i'm not sure how this binding works), but it does not render the View and neither returns a binding error.

MenuView.xaml
```
<UserControl x:Class="PointOfSale.Views.MenuView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:PointOfSale.Views"
             mc:Ignorable="d" 
             d:DesignHeight="450" d:DesignWidth="800">
    <Grid>
        <TextBlock Background="White">Hello World</TextBlock>
    </Grid>
</UserControl>
```

[AppSample.zip](https://github.com/user-attachments/files/15533567/AppSample.zip)

Help please

**Comment by singhashish-wpf** [comment]
@Freddo37 
Can you please attach your sample repro project?

**Comment by Freddo37** [comment]
> @Freddo37 Can you please attach your sample repro project?

Done, also it's in this repo in case is easier that way for anyone:
[https://github.com/Freddo37/AppSample](url)

**Comment by miloush** [comment]
The ContentControl (and ContentPresenter) do not automatically use data context as content. Use the binding to set Content property rather than DataContext, or if you want both, use `Content="{Binding}"` to use the data context value.

**Comment by Freddo37** [comment]
> The ContentControl (and ContentPresenter) do not automatically use data context as content. Use the binding to set Content property rather than DataContext, or if you want both, use `Content="{Binding}"` to use the data context value.

Thanks you, Adding `Content="{Binding}"`, works perfect.

Any ideas why it did work in NET.6 without adding the `Content="{Binding}"`?

**Comment by miloush** [comment]
If I change the project to target .NET 6, I get the same behavior. Do you have an example it working?

**Comment by Freddo37** [comment]
> If I change the project to target .NET 6, I get the same behavior. Do you have an example it working?

Oh, i double checked, you are right, the WpfSample i was deriving from had `Content="{Binding CurrentViewModel}"`.

Apologies, and thanks for the help.
