### ISSUE TITLE
.NET 9 Preview 4 Wpf Themed using PresentatinFramework.Fluent Fonts do not scale with System Font scaling

### ISSUE THREAD

**Issue by jcddcjjcd** [dotnet/wpf#9192]
### Description

When using the the PresentationFramework.Fluent in .NET 9 Preview 4 the Fonts do not scale with Settings/Accesability/TextSize when usig WPF

### Reproduction Steps

Any control showing text will reveal the issue

### Expected behavior

Scalling as in .NET 8

### Actual behavior

Test remains the same size

### Impact

I guess this is a work in progress

### Configuration

.NET 9 Preview 4
Windows 11
x64
Unkown

**Comment by hongruiyu** [comment]
There doesn't seem to be a standard PresentationFramework.Fluent library specifically for fonts in the default .NET WPF libraries.
Are you using the Fluent.Ribbon package and installing it by opening the NuGet package manager?
 If not, could you share a link to `PresentationFramework.Fluent` and show how to use it?

**Comment by dipeshmsft** [comment]
@jcddcjjcd, this issue is now fixed. We have merged the changes in both .NET 9 and .NET 10 for this. Font scaling will work the controls.
