### ISSUE TITLE
[dotnet-sdk-9.0.100-preview.7.24321.3] Unable to load one or more of the requested types for "PresentationCore.dll"

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/wpf#9288]
### Description

When run the 3rd party application with the latest .NET 9 build "dotnet-sdk-9.0.100-preview.7.24321.3", it failed to load menu nodes in application.

### Reproduction Steps

Minimal Repro steps (Demo attached: [LiveSPICEDemo.zip](https://github.com/user-attachments/files/15967880/LiveSPICEDemo.zip)):
The machine has dotnet-sdk-9.0.100-preview.7.24321.3 installed.
1. Create a WPF project.
2. Add the following code to MainWindow.xaml.cs.
```
public MainWindow()
{
    InitializeComponent();

    foreach (Assembly i in AppDomain.CurrentDomain.GetAssemblies())
    {
        i.GetTypes();
    }
}
```
4. Build the project.
5. Change the runtime.config file to let the app run against with dotnet-sdk-9.0.100-preview.7.24321.3.
```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-preview.6.24319.11"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "9.0.0-preview.7.24320.6"
      }
    ]
```
7. Launch the project.

### Expected behavior

Launch successfully.

### Actual behavior

Launch failed with error:
```
System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.'
Stack Trace:
   at System.Reflection.RuntimeModule.GetDefinedTypes()
   at System.Reflection.RuntimeModule.GetTypes()
   at LiveSPICEDemo.MainWindow..ctor() in E:\Demos\LiveSPICEDemo\LiveSPICEDemo\MainWindow.xaml.cs:line 26
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```

### Regression?

Yes
Verify Scenarios:
1). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.6.24317.13: Pass
2). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.7.24321.3: Fail

### App Repro Steps:
1.Change the runtime.config file to let the app run against with dotnet-sdk-9.0.100-preview.7.24321.3.
```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-preview.6.24319.11"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "9.0.0-preview.7.24320.6"
      }
    ]
```
2. Launch LiveSPICE.exe
3. Click “Generic”.

**Expected Result:**
Content display as normal.
![image](https://github.com/dotnet/wpf/assets/83067197/c1a39f04-767b-414c-94bf-63c5cf0e5f66)

**Actual Result:**
Content in Components tab are missing.
![image](https://github.com/dotnet/wpf/assets/83067197/0bafd66e-2c03-464b-9628-a7d8534ecfc4)

### Configuration

**Application Name:** LiveSPICE
**OS**： Windows 10 21H2
**CPU**: X64
**.NET Build Number**: dotnet-sdk-9.0.100-preview.7.24321.3
**App Source or App Installer checking at:**  https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2106401
**Github Link:** 
https://github.com/dsharlet/LiveSPICE

### Other information

**Findings:**
This exception only thrown when GetTypes for "PresentationCore.dll". Other assemblies that get with AppDomain.CurrentDomain.GetAssemblies() don't have this exception.

**Dotnet Info:**
```
.NET SDK:
 Version:           9.0.100-preview.7.24321.3
 Commit:            941ec62ab2
 Workload version:  9.0.100-manifests.cc027b4d
 MSBuild version:   17.11.0-preview-24318-05+4a45d5633

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.7.24321.3\

Host:
  Version:      9.0.0-preview.6.24319.11
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  9.0.100-preview.7.24321.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.6.24320.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24319.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.7.24320.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```
@dotnet-actwx-bot @dotnet/compat

**Comment by harshit7962** [comment]
Following up on the removal of BinaryFormatter comment [here](https://github.com/dotnet/runtime/issues/103952#issuecomment-2189379223), the issue can be fixed by explicitly including the System.Runtime.Serialization.Formatters.

**Comment by Junjun-zhao** [comment]
> Following up on the removal of BinaryFormatter comment [here](https://github.com/dotnet/runtime/issues/103952#issuecomment-2189379223), the issue can be fixed by explicitly including the System.Runtime.Serialization.Formatters.

Yes. The workaround mentioned for that bug works for application. 
Thank you @harshit7962 and team for working on the final fix for this issue on the .NET side. We will verify it once the fix is completed and merged.

**Comment by Junjun-zhao** [comment]
Verified this issue on build dotnet-sdk-9.0.100-preview.7.24402.8, it has been fixed.

**Comment by harshit7962** [comment]
Thanks for the update. Closing the issue as it has been fixed now.
