### ISSUE TITLE
[dotnet-sdk-9.0.100-preview.7.24321.3] Exception "Data on clipboard is invalid (0x800401D3 (CLIPBRD_E_BAD_DATA))" shows when do paste operation in LiveSPICE

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/wpf#9289]
### Description

When run the 3rd party application with the latest .NET 9 build "dotnet-sdk-9.0.100-preview.7.24321.3", the Paste function doesn't work.

### Reproduction Steps

Minimal Repro steps (Demo attached [PastDemo.zip](https://github.com/user-attachments/files/15968062/PastDemo.zip)):
The machine has dotnet-sdk-9.0.100-preview.7.24321.3 installed.
1. Create a WPF project.
2. Add the following code to MainWindow.xaml.cs.
```
public MainWindow()
{
    InitializeComponent();
   
Clipboard.SetData(DataFormats.StringFormat, "<Schematic><Element Type=\"TestTypeName\" /></Schematic>");

string s = Clipboard.GetData(DataFormats.StringFormat) as string;
}
```
4. Build the project.
5. Change the runtime.config file to let the app run against with dotnet-sdk-9.0.100-preview.7.24321.3.
```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-preview.6.24319.11"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "9.0.0-preview.7.24320.6"
      }
    ]
```
7. Launch the project.

### Expected behavior

Launch successfully.

### Actual behavior

Launch failed with error:
```
System.Runtime.InteropServices.COMException: 'Data on clipboard is invalid (0x800401D3 (CLIPBRD_E_BAD_DATA))'
Stack Trace:
      at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
   at System.Windows.DataObject.OleConverter.GetDataFromOleHGLOBAL(String format, DVASPECT aspect, Int32 index)
   at System.Windows.DataObject.OleConverter.GetDataFromBoundOleDataObject(String format, DVASPECT aspect, Int32 index)
   at System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert, DVASPECT aspect, Int32 index)
   at System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert)
   at PastDemo.MainWindow..ctor() in E:\Demos\PastDemo\PastDemo\MainWindow.xaml.cs:line 25
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```

### Regression?

Yes
Verify Scenarios:
1). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.6.24317.13: Pass
2). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.7.24321.3: Fail

### App Repro Steps:
1.Change the runtime.config file to let the app run against with dotnet-sdk-9.0.100-preview.7.24321.3.
```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-preview.6.24319.11"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "9.0.0-preview.7.24320.6"
      }
    ]
```
2. Launch LiveSPICE.exe
3. Click “Open”.  
4. Input “Test.schx” file path in File name (in LiveSPICEApp folder).
5. Click “Open” button.
6. Select “Label”.
7. Click “Edit”.    
8. Click “Cut”.
9. Click “Edit”.
10. Click “Paste”.

**Expected Result:**
Paste successfully.
![image](https://github.com/dotnet/wpf/assets/83067197/315158fe-8d39-4c47-bd0e-7f051d783dba)

**Actual Result:**
Paste function failed.
![image](https://github.com/dotnet/wpf/assets/83067197/2e89c3de-5799-4a3b-b8fe-2c57415bdc6e)

### Configuration

**Application Name:** LiveSPICE
**OS**： Windows 10 21H2
**CPU:** X64
**.NET Build Number:** dotnet-sdk-9.0.100-preview.7.24321.3
**App Source or App Installer checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2106402
**Github Link:** 
https://github.com/dsharlet/LiveSPICE

**Dotnet Info:**
```
.NET SDK:
 Version:           9.0.100-preview.7.24321.3
 Commit:            941ec62ab2
 Workload version:  9.0.100-manifests.cc027b4d
 MSBuild version:   17.11.0-preview-24318-05+4a45d5633

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.7.24321.3\

Host:
  Version:      9.0.0-preview.6.24319.11
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  9.0.100-preview.7.24321.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.6.24320.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24319.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.7.24320.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Other information

@dotnet-actwx-bot @dotnet/compat

**Comment by lindexi** [comment]
I test it with `9.0.0-preview.5.24306.7` and it can launch successfully.

PastDemo.runtimeconfig.json:

```json
{
  "runtimeOptions": {
    "tfm": "net6.0",
   "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-preview.5.24306.7"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "9.0.0-preview.5.24306.7"
      }
    ]
  }
}
```

**Comment by rchauhan18** [comment]
This is by design.
In this case we are using Binaryformatter, which has been remove from .NET9.0 (preview6 onwards).
To fix this issue we need to:
-  explicitly include the System.Runtime.Serialization.Formatters.
-  Set the tag EnableUnsafeBinaryFormatterSerialization to true.

**Comment by miloush** [comment]
I don't think inability to copy and paste text is by design. People should be able to do that without doing any extra work or expose themselves to security risks, which is presumably why the binary formatters were removed (and which I am not sure why are needed for dealing with string). If that is indeed the case, this should be fixed for the final release.

**Comment by IrinaPykhova** [comment]
> This is by design. In this case we are using Binaryformatter, which has been remove from .NET9.0 (preview6 onwards). To fix this issue we need to:
> 
> * explicitly include the System.Runtime.Serialization.Formatters.
> * Set the tag EnableUnsafeBinaryFormatterSerialization to true.

Last week I was playing with drag&drop to avoid using binary serialization where we had it from our side. And I've found that there are a lot of other differences from MS side which forced me to change even the way I worked with strings. (I used Preview 5). 
Nobody expects you to use binary formatter for strings. Juat imagine that after you happily got rid of it from your side, you will force every single app developer who doesn't use it at all, to start using it. How does it sound?

**Comment by rchauhan18** [comment]
@miloush 
We disallow deserialization of DataFormats.StringFormat to prevent potentially malicious objects from deserialized as part of "text". We consider it as a DataFormats.Serializable and currently using BinaryFormatter to serialize/deserialize.
Refer to the [comment](https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs#L2798-L2823) 

@IrinaPykhova and @miloush 
I agree that people should be able to copy and paste a text without doing some extra work. 
For that we are working on it, I have raised a PR which performs serialization/deserialization for ```Primitive types``` without using Binaryformatter. After our fix is added, we won't require to add the package for primitive data types. 
PR: https://github.com/dotnet/wpf/pull/8532

**Comment by rchauhan18** [comment]
> Verified with build dotnet-sdk-9.0.100-preview.7.24374.17, it still reproduces.

@Junjun-zhao You are able to repro this issue because the application could not find ```System.Runtime.Serialization.Formatters.dll``` in ```Microsft.NETCore.App```. This could be due to the runtime version is way behind the 9.0.100-preview.7.24374.17. This could be resolved when the versions get sync.

I am resolving the issue by pointing the assembly to to the path where it exists in Microsft.NETCore.App.

MainWindow.xaml.cs  (LiveSPICE)
```diff
        public MainWindow()
        {
+            AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;
            InitializeComponent();

            Components.ComponentClick += component_Click;
            Properties.PropertyValueChanged += properties_PropertyValueChanged;
            schematics.ChildrenTreeChanged += (o, e) => NotifyChanged("ActivewViewerZoom");

            string[] args = Environment.GetCommandLineArgs();
            for (int i = 1; i < args.Length; i++)
            {
                if (args[i].EndsWith(".schx") && System.IO.File.Exists(args[i]))
                    Open(args[i]);
            }
        }

+        private System.Reflection.Assembly? CurrentDomain_AssemblyResolve(object? sender, ResolveEventArgs args)
+       {
+           if (args.Name.StartsWith("System.Runtime.Serialization.Formatters"))
+            {
+                return Assembly.LoadFrom(@"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.7.24358.7\System.Runtime.Serialization.Formatters.dll");
+            }
+
+           return null;
+        }
``` 



This will work with the new implementation added. PR: https://github.com/dotnet/wpf/pull/8532

**Comment by Junjun-zhao** [comment]
Verified this issue on build dotnet-sdk-9.0.100-preview.7.24402.8, it has been fixed.

**Comment by harshit7962** [comment]
Thanks for the update. Closing the issue as it has been fixed now.
