### ISSUE TITLE
Duplicated frameworks in runtimeconfig.json

### ISSUE THREAD

**Issue by glent1** [dotnet/wpf#929]
**.NET Core Version:**  
3.0.100-preview7-012361

**Windows version:**
1803 

**Does the bug reproduce also in WPF for .NET Framework 4.8?:**
Unlikely

 **Problem description:** 
Build creates a runtimeconfig.json as follows ...

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.0",
    "frameworks": [
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "3.0.0-preview7-27811-08"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "3.0.0-preview7-27811-08"
      }
    ]
  }
}
```

Application then fails with Invalid runtimeconfig.json

Editing and removing the duplication allow the application to run

**Comment by rladuca** [comment]
@glent1 Do you have a sample project where this occurs or are you seeing this on the basic `dotnet new wpf` template?

**Comment by glent1** [comment]
Unfortunately not, my project is quite complex.  The problem does not occur on the template.  I will attempt to establish what might contribute by trial and error.

**Comment by rladuca** [comment]
@glent1 That does seem to either point to something more related to your build targets, or a complex interaction between projects.  If you can get some sort of minimal reproduction that would be great.  You could also post a binlog somewhere and share it with us.  However, that could contain data you'd not like to be public, so you'll have to evaluate that.

**Comment by glent1** [comment]
Build log attached.

[msbuild.zip](https://github.com/dotnet/wpf/files/3283534/msbuild.zip)

**Comment by glent1** [comment]
This problem has gone away as of a later preview 7 build.  I have now gone back to preview 6 which is finally working for my combined WPF/Blazor solution and it also does not occur there, so from my perspective this call can be closed.

**Comment by vatsan-madhavan** [comment]
Thanks for the update!

**Comment by LokiMidgard** [comment]
I have the same problem with `3.0.0-preview7-27824-03`.
 
A new wpf project does not have this problem but another project I'm working on does. I haven't found out what actually provokes this behaviour. I tried to comment elements out from the original csproj or coppy them over to a new WPF project. Nither removed/provoked the error.

**Comment by AlexanderTaeschner** [comment]
I also see this in multiple projects with 3.0.100-preview7-012629. The solutions are rather complex but all of them use nuget packages of my own libraries where some of them are using WPF parts and target both net472 and netcoreapp3.0.

**Comment by AlexanderTaeschner** [comment]
It seems to be a problem when mixing WPF and WinForms apps. I opened https://github.com/dotnet/sdk/issues/3380 for this.
