### ISSUE TITLE
[API Proposal] Introducing AccentColor as SystemColors

### ISSUE THREAD

**Issue by dipeshmsft** [dotnet/wpf#9295]
## Background and Motivation

Since Windows 10 onwards, Accent color has been one of the key compoenents of visual styles in Windows controls. However, there is no easy way to get the system's accent color. Accent colors can be used in custom styles to align the styling of controls with what the OS is showing.

In earlier versions of Windows, visual styles were defined using system colors and brushes, and corresponding to that we had `SystemColors` static class that contained getters to all the system colors, brushes and corresponding resource keys for using the colors and brushes in XAML.

Since, Accent color and it's variations are also system wide defined colors, we propose to expose them using the `SystemColors` class.

## API Proposal

```csharp

    public static class SystemColors
    {
        // Accent Colors
        public static Color AccentColor;
        public static Color AccentColorLight1;
        public static Color AccentColorLight2;
        public static Color AccentColorLight3;
        public static Color AccentColorDark1;
        public static Color AccentColorDark2;
        public static Color AccentColorDark3;

        // Accent Color Keys
        public static ResourceKey AccentColorKey;
        public static ResourceKey AccentColorLight1Key;
        public static ResourceKey AccentColorLight2Key;
        public static ResourceKey AccentColorLight3Key;
        public static ResourceKey AccentColorDark1Key;
        public static ResourceKey AccentColorDark2Key;
        public static ResourceKey AccentColorDark3Key;
        
        // Accent Color Brushes
        public static SolidColorBrush AccentColorBrush;
        public static SolidColorBrush AccentColorLight1Brush;
        public static SolidColorBrush AccentColorLight2Brush;
        public static SolidColorBrush AccentColorLight3Brush;
        public static SolidColorBrush AccentColorDark1Brush;
        public static SolidColorBrush AccentColorDark2Brush;
        public static SolidColorBrush AccentColorDark3Brush;

        // Accent Color Brush Keys
        public static ResourceKey AccentColorBrushKey;
        public static ResourceKey AccentColorLight1BrushKey;
        public static ResourceKey AccentColorLight2BrushKey;
        public static ResourceKey AccentColorLight3BrushKey;
        public static ResourceKey AccentColorDark1BrushKey;
        public static ResourceKey AccentColorDark2BrushKey;
        public static ResourceKey AccentColorDark3BrushKey;
    }
```

I think it may be possible to reduce the number of properties that we are exposing here, if the operations to calculate the variations of AccentColor are simpler. We don't know that yet so, I would like to keep these APIs **experimental**.

### Alternative Design

Rather than having the accent colors defined here, we can introduce a new class, say `AccentColorManager` which will store the system accent and opens up possibility for theme related customization.

**Comment by miloush** [comment]
LGTM.

**Comment by dipeshmsft** [comment]
@robert-abeo , thanks for the insight on the history of accent colors. It pretty much means that we would have to access all of them from WinUI's UISetting type then.

Yeah, while working with Fluent I have understood the layering in the resources and styles and I will try to keep that in order. 
But I have included the brush keys here because that has been the general use in theme styles. So basically it will support either scenario.

**Comment by dipeshmsft** [comment]
cc @ThomasGoulet73 @lindexi @batzen @Symbai @pomianowski @rladuca @vatsan-madhavan

**Comment by pomianowski** [comment]
Looks great, what about the change while the application is running, maybe some 'AccentColorsChanged' delegate?

**Comment by miloush** [comment]
These would be updated, so if you use DynamicResource with the keys, the color will change when it changes in the system. There is also [UserPreferenceChanged](https://learn.microsoft.com/en-us/dotnet/api/microsoft.win32.systemevents.userpreferencechanged) event generated when the theme changes.

**Comment by lindexi** [comment]
LGTM for SystemColors.

**Comment by dipeshmsft** [comment]
If the community is okay with the shape of this API and there are no objections, I will go ahead and mark it as ready for review tomorrow.

**Comment by ThomasGoulet73** [comment]
LGTM except a small question:
Is the OS call used to retrieve the values of these properties available/working on all supported versions of Windows ? And if not, what should be the behavior in this case.

**Comment by dipeshmsft** [comment]
@ThomasGoulet73, no we used a WinRT type UISettings to retreive the values, this is present from Windows 10. In the case where we don't have this type to provide a value, we will provide a fallback for the same.

**Comment by terrajobst** [comment]
* The API ref seems to imply they are fields, but they should be properties.
* Otherwise looks good.

```C#
namespace System.Windows;

public static class SystemColors
{
    // Accent Colors
    public static Color AccentColor { get; }
    public static Color AccentColorLight1 { get; }
    public static Color AccentColorLight2 { get; }
    public static Color AccentColorLight3 { get; }
    public static Color AccentColorDark1 { get; }
    public static Color AccentColorDark2 { get; }
    public static Color AccentColorDark3 { get; }

    // Accent Color Keys
    public static ResourceKey AccentColorKey { get; }
    public static ResourceKey AccentColorLight1Key { get; }
    public static ResourceKey AccentColorLight2Key { get; }
    public static ResourceKey AccentColorLight3Key { get; }
    public static ResourceKey AccentColorDark1Key { get; }
    public static ResourceKey AccentColorDark2Key { get; }
    public static ResourceKey AccentColorDark3Key { get; }
    
    // Accent Color Brushes
    public static SolidColorBrush AccentColorBrush { get; }
    public static SolidColorBrush AccentColorLight1Brush { get; }
    public static SolidColorBrush AccentColorLight2Brush { get; }
    public static SolidColorBrush AccentColorLight3Brush { get; }
    public static SolidColorBrush AccentColorDark1Brush { get; }
    public static SolidColorBrush AccentColorDark2Brush { get; }
    public static SolidColorBrush AccentColorDark3Brush { get; }

    // Accent Color Brush Keys
    public static ResourceKey AccentColorBrushKey { get; }
    public static ResourceKey AccentColorLight1BrushKey { get; }
    public static ResourceKey AccentColorLight2BrushKey { get; }
    public static ResourceKey AccentColorLight3BrushKey { get; }
    public static ResourceKey AccentColorDark1BrushKey { get; }
    public static ResourceKey AccentColorDark2BrushKey { get; }
    public static ResourceKey AccentColorDark3BrushKey { get; }
}
```
