### ISSUE TITLE
WPF binding error when using Hebrew culture for .net 8

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#9298]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WPF-binding-error-when-using-Hebrew-cult/10628500)._

---
[regression] [worked-in:.Net Framework 4.8.1]
Hello,

When setting the UI language to Hebrew doesn't work well when using minus sign.
If, for example, a double with value -0.2 is bind to the Text property of some TextBox,
the result string is not "-0.2".
As a result when one use double.TryParse for the Text, the parsing is fail.
See attached project.

Regards,

Eyal

---
#### Feedback Bot on 4/2/2024, 04:15 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by miloush** [comment]
Can the attached project be included?

**Comment by pchaurasia14** [comment]
> Can the attached project be included?
Sample Repro - [WpfApp71.zip](https://github.com/user-attachments/files/15988280/WpfApp71.zip)

**Comment by miloush** [comment]
You cannot expect a number formatted using none locale data will parse using other locale data.
Use the same CultureInfo for parsing:
```diff
- bool result = double.TryParse(textBoxTest.Text, out readValue);
+ bool result = double.TryParse(textBoxTest.Text, cultureInfo, out readValue);
```

**Comment by pchaurasia14** [comment]
Thanks @miloush !
