### ISSUE TITLE
[dotnet-sdk-9.0.100-preview.6.24325.8] clashN get System.PlatformNotSupportedException: BinaryFormatter serialization and deserialization have been removed.

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/wpf#9313]
### Description

When run the 3rd party application with the latest .NET 9 build "dotnet-sdk-9.0.100-preview.6.24325.8", it failed to launch with error: 
```
System.PlatformNotSupportedException: BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
```

### Reproduction Steps

1.Change the runtime.config file to let the app run against with dotnet-sdk-9.0.100-preview.6.24325.8
```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-preview.6.24321.8"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "9.0.0-preview.6.24322.3"
      }
    ]
```
2. Launching clashN.exe.
3. Click “配置文件”.
4. Click “添加配置文件”.
5. Input “appcompat” in remarks.
6. Click “确定”.
7. Double click appcompat.

### Expected behavior

Successfully jump to the interface.

### Actual behavior

App no response.
**Exception details (Exception comes from \clashN\guiLogs):**
System.PlatformNotSupportedException: BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.

### Regression?

Yes

**Verify Scenarios:**
1). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.6.24317.13: Pass
2). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.6.24325.8: Fail
3). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.7.24321.3: Fail

### Known Workarounds

No
We tried to install the System.Runtime.Serialization.Formatters nuget package but failed because it is not compatible with this .NET 6.0 App. The supported .NET version of System.Runtime.Serialization.Formatters nuget package is .NET 8.

### Configuration

**Application Name:** clashN (WPF net6.0)
**OS：** Windows 10 21H2
**CPU:** X64
**.NET Build Number:** dotnet-sdk-9.0.100-preview.6.24325.8
**App & Source Location:** Check at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2110679
**Github Link:**  https://github.com/2dust/clashN

**Dotnet Info**:
```
.NET SDK:
 Version:           9.0.100-preview.6.24325.8
 Commit:            89054b0c37
 Workload version:  9.0.100-manifests.29b7987d
 MSBuild version:   17.11.0-preview-24318-05+4a45d5633

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.6.24325.8\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.6.24321.8
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  9.0.100-preview.6.24325.8 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.6.24324.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24321.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.6.24322.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
@dotnet-actwx-bot @dotnet/compat

**Comment by miloush** [comment]
The posted GitHub repo uses .NET 8. Also please post full call stacks.

**Comment by Junjun-zhao** [comment]
Thanks @miloush . We tried it and the issue is not repro with the latest version which is using FromJSon. Closing it.
