### ISSUE TITLE
Customize style is applied to windows form hosted within a WPF control

### ISSUE THREAD

**Issue by sudharsan-narayanan** [dotnet/wpf#9346]
### Description

If we customize window style and applied for the Winforms host within a WPF control. Customize style is applied to partial Winforms control. We suspect it is a bug. 

**Note**: The style is applied to partially control not for all control.

Can you please check and fix this issue ASAP?

### Reproduction Steps

1. Run the Sample.
2. Note: Customize window style is applied to partial Winforms control.

[WPFWinformsHost.zip](https://github.com/user-attachments/files/16085810/WPFWinformsHost.zip)

### Expected behavior

Customize style should not applied to winforms control.

### Actual behavior

Customize style is applied to partial Winforms control.

### Impact

Affects when we use the windows form hosted within a WPF control.

**Comment by miloush** [comment]
This is by design, see https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/windows-forms-and-wpf-property-mapping

You can use `winformshost.PropertyMap.Clear()` to disable that.
