### ISSUE TITLE
Designer: XDG0062 error on d:DesignInstance

### ISSUE THREAD

**Issue by hillin** [dotnet/wpf#937]
* .NET Core Version: 3.0 Preview 5
* Windows version: Windows 10 Version 1803
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 
 **Problem description:**
When using `d:DesignInstance` for `d:DataContext` in a UserControl or Window, the designer throws an ArgumentException and reports an `XDG0062` error in the error list. A wavy line will also show under the corresponding XAML.

It seems this only happens if another object, referenced in a `clr-namespace`, is created in the same UserControl/Window.

 **Actual behavior:** 
 Attaching a debugger to WpfSurface.exe reveals the following exceptions:

> System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: key
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)

 **Expected behavior:**
 Does not report an error.

 **Minimal repro:**
 https://github.com/hillin/NetCoreWpfDesignerIssues, in the `DesignInstance_XDG0062` project.

**Comment by grubioe** [comment]
@diverdan92 can you look into this?

**Comment by diverdan92** [comment]
@LyalinDotCom - this one too? :)

**Comment by vatsan-madhavan** [comment]
This needs to be moved over to the right repo (or closed out since this isn't actionable in dotnet/wpf). Clearing 3.0 milestone.

/cc @grubioe

**Comment by grubioe** [comment]
@diverdan92 @LyalinDotCom thoughts on where this issue can go to?

**Comment by grubioe** [comment]
Hi @hillin can you log an issue in the Visual Studio Developer Community- it will then be directed to the Designer team.  
https://developercommunity.visualstudio.com/content/problem/post.html?space=8

Thanks!

**Comment by hillin** [comment]
OK, reported
