### ISSUE TITLE
Designer: XDG0062 error on ControlTemplate

### ISSUE THREAD

**Issue by hillin** [dotnet/wpf#938]
* .NET Core Version: 3.0 Preview 5
* Windows version: Windows 10 Version 1803
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 
 **Problem description:**

This issue is highly likely to be the same as https://github.com/dotnet/wpf/issues/937.

When using an object referenced in a `clr-namespace` in a `ControlTemplate`, the designer throws an ArgumentException and reports an `XDG0062` error in the error list. A wavy line will also show under the corresponding XAML.

It seems this only happens if another object, referenced in a `clr-namespace`, is created in the same UserControl/Window.

 **Expected behavior:**
 Does not report an error.

 **Minimal repro:**
 https://github.com/hillin/NetCoreWpfDesignerIssues, in the `ControlTemplate_XDG0062` project.

**Comment by grubioe** [comment]
@diverdan92 can you look into this?

**Comment by diverdan92** [comment]
+ @LyalinDotCom - can you take a look?

**Comment by vatsan-madhavan** [comment]
@grubioe, We need to move this out of dotnet/wpf. I'm clearing the milestone. Please help us find the right home for this.

**Comment by grubioe** [comment]
@LyalinDotCom @diverdan92 thoughts on where we can move this issue to?

**Comment by grubioe** [comment]
hi @hillin  - can you log an issue via in the Visual Studio Developer Community- it will then be directed to the Designer team.  
https://developercommunity.visualstudio.com/content/problem/post.html?space=8

Thanks!
