### ISSUE TITLE
Dynamically Create TextBox Issue

### ISSUE THREAD

**Issue by turboyang-cn** [dotnet/wpf#940]
- .NET Core Version: 3.0.100-preview6-012264
- OS: Windows 10
- OS Version: 17134.471
- Visual Studio Version: Visual Studio 2019 16.1.3

Errors occurred when I created text boxes dynamically in my code

> System.ArgumentException:"Requested value 'Delete' was not found."

`TextBox TextBox = new TextBox();`

**Comment by lindexi** [comment]
Can you give a minimal repository? I run your code in my project and I can not find the exception. 

My version is 3.0.100-preview5-011568

**Comment by turboyang-cn** [comment]
https://github.com/turboyang-cn/wpf-core-test

There's no problem with this version. The problem is in the new version (3.0.100-preview6-012264).

**Comment by turboyang-cn** [comment]
![image](https://user-images.githubusercontent.com/20012260/59419966-9a36c100-8dfe-11e9-868d-6ad7fc1133ae.png)

**Comment by lindexi** [comment]
It seems a language issues.

The `KeyGesture.CreateFromResourceStrings` need the arguments with `keyGestureToken` and the value of `keyGestureToken` is a Chinese word `删除`, not the expected word `delete`.

And the code will use the Chinese word to `ConvertFromInvariantString` which will call the `	PresentationCore.dll!System.Windows.Input.KeyGestureConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object source)`


https://github.com/dotnet/wpf/blob/ae1790531c3b993b56eba8b1f0dd395a3ed7de75/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/KeyGesture.cs#L299


I find the value of source in `KeyGestureConverter.ConvertFrom` is the Chinese word.


https://github.com/dotnet/wpf/blob/ae1790531c3b993b56eba8b1f0dd395a3ed7de75/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/KeyGestureConverter.cs#L82

And the `KeyGestureConverter.ConvertFrom` will call Enum.Parse that will throw exception.

![](https://user-images.githubusercontent.com/16054566/59421984-2ac2d080-8e02-11e9-94a8-1d3601487e6e.png)

And the `ConvertFrom` will call the `keyConverter.ConvertFrom` to convert the `keyToken` and the `keyToken` is the Chinese word.

https://github.com/dotnet/wpf/blob/ae1790531c3b993b56eba8b1f0dd395a3ed7de75/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/KeyGestureConverter.cs#L120

**Comment by lindexi** [comment]
This issus can be closed, because @ryalanms fix it in https://github.com/dotnet/wpf/pull/919

**Comment by lindexi** [comment]
Thank for @ryalanms. And he change `SRID.KeyDelete` which value is "KeyDelete" to `KeyDelete` which value is "Delete" that can fix it.

```diff
- CommandHelpers.RegisterCommandHandler(controlType, EditingCommands.Delete               , new ExecutedRoutedEventHandler(OnDelete)               , onQueryStatusNYI                  , SRID.KeyDelete,           SRID.KeyDeleteDisplayString                 );
+ CommandHelpers.RegisterCommandHandler(controlType, EditingCommands.Delete               , new ExecutedRoutedEventHandler(OnDelete)               , onQueryStatusNYI                  , KeyDelete,           SRID.KeyDeleteDisplayString                 );
```

https://github.com/dotnet/wpf/commit/9afa976db6618e4cd9a944d68149d70e0cbeea58#diff-8491c698fe3be6a213b6db468e74c815L81

Because `ResourceManager.GetString("Delete")` will return null and `ResourceManager.GetString("KeyDelete")` will return the Chinese word "删除" and the `SR.GetResourceString` will return the resourceKey when not found.

And the `Key` enum can find the "Delete" value.
