### ISSUE TITLE
Transparent Fill/Background disables MouseLeftButtonDown on Rectangle/Canvas 

### ISSUE THREAD

**Issue by istareatscreens** [dotnet/wpf#9554]
### Description

Having Intractability of an element be influenced by a style attribute of an element in this case Background/Fill is a side effect. Style attributes should do one thing, change style not influence component intractability.  

If this design is due to a security consideration it would be nice if there was a warning.

### Reproduction Steps

Create a WPF project add a button to activate this window:

```xml
<Window x:Class="Test.Window.Test"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Test.Window"
        xmlns:svg="http://sharpvectors.codeplex.com/svgc/"
        mc:Ignorable="d"
        AllowsTransparency="True"
        WindowStyle="None"
        Background="Transparent"
        Title="TouchConfigWindow" 
        Height="450" Width="800"
        >
        <Grid>
            <Canvas 
                       Background="Transparent"
                       HorizontalAlignment="Stretch"
                       IsHitTestVisible="True"
                       VerticalAlignment="Stretch"
                       MouseLeftButtonDown="Window_MouseLeftButtonDown"
                       Panel.ZIndex="2"
                />
        </Grid>
</Window>
```

```C#
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Test.Window
{
    public partial class Test: System.Windows.Window
    {

        public TouchConfigWindow()
        {
            InitializeComponent();
        }
        
        // Will never fire
        private void Window_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            DragMove();
        }
        
    }
}
```

### Expected behavior

Expect Window_MouseLeftButtonDown should execute on button click

### Actual behavior

Window_MouseLeftButtonDown never fires and what ever is behind it or the window is selected.

### Known Workarounds

Note setting Opacity here to 0 also causes MouseLeftButtonDown to be disabled.
```xml            
<Canvas 
                       Background="Red"
                       Opacity="0.01"
                       HorizontalAlignment="Stretch"
                       IsHitTestVisible="True"
                       VerticalAlignment="Stretch"
                       MouseLeftButtonDown="Window_MouseLeftButtonDown"
                       Panel.ZIndex="2"
                />
```

### Configuration

    Which version of .NET is the code running on?
    .NET 8.0
    What OS and version, and what distro if applicable?
    Windows 10
    What is the architecture (x64, x86, ARM, ARM64)?
    Intel x64
    Do you know whether it is specific to that configuration?
    No

**Comment by lindexi** [comment]
@istareatscreens Sorry, I think this issues be caused by AllowsTransparency

**Comment by miloush** [comment]
> Style attributes should do one thing, change style not influence component intractability.

That is clearly not true, you can set `IsEnabled`, `IsHitTestVisible` and many other properties affecting interactibility using styles. Even setting background brush as opposed to having it null affects the hit testing.

The hit-test behavior of transparent windows is a Win32 matter and documented here: https://learn.microsoft.com/en-us/windows/win32/winmsg/window-features#layered-windows

> Hit testing of a layered window is based on the shape and transparency of the window. This means that the areas of the window that are color-keyed or whose alpha value is zero will let the mouse messages through.
