### ISSUE TITLE
Grouping issues caused by a custom GroupDescription implementation

### ISSUE THREAD

**Issue by ILepekhov** [dotnet/wpf#9577]
### Description

Hello everyone!

I am currently working on a project that involves the sorting and grouping functionality of the DataGrid component. The requirements for this functionality are quite complex and not straightforward. LiveSorting, LiveGrouping and LiveFiltering are used.

To meet these requirements, I have implemented LiveSorting, LiveGrouping, and LiveFiltering. These features allow for real-time sorting, grouping, and filtering of data in the DataGrid component.

As part of this implementation, I also had to create a custom GroupDescription implementation. This allows me to apply different grouping and group-sorting rules based on the selected sorting property of the element collection.

However, I have encountered some issues with the application crashing frequently. This occurs specifically when a single group of elements is added and then removed in succession.

### Reproduction Steps

I created a simple demo project https://github.com/ILepekhov/WpfDemos to show off the issue.

To reproduce the issue, run the app and click the "Add" and "Remove" buttons in turn a few times until the error message is written to the console.

https://github.com/user-attachments/assets/25f5891c-1dab-48a6-9fdf-94b1a53804ea

### Expected behavior

The issue hadn't appeared until I replaced the default PropertyGroupDescription with my custom implementation. I don't see any issues with my implementation. So I expect it to work without problems with LiveGrouping and LiveSorting. I turned off the LiveSorting feature for now, and the issue is gone, but it's not acceptable behavior for me.

### Actual behavior

No errors occurred when running the code.

**Comment by ILepekhov** [comment]
While I was doing the demo project, I came up with the idea of leveraging the PropertyGroupDescription in conjunction with a set of custom group-name classes and converters that encapsulate naming and sorting logic. And it works pretty well!
The corresponding code is in a separate branch: https://github.com/ILepekhov/WpfDemos/tree/feature/try-using-PropertyGroupDescription-with-converters.

Then I'd created a special abstract base class describing all the necessary sorting and naming methods in my business project with a set of implementations and all the aforementioned issues gone!

Anyway, I still really interesting why the approach with a custom GroupDescription implementation doesn't work.

**Comment by h3xds1nz** [comment]
You launch the Add/Remove operations from a random background thread (via `Task.Run`) and you do not marshal them properly to the UI thread (e.g. via Dispatcher), which causes forementioned issues. If I really try I can get it to crash 3 different ways.

**Comment by ILepekhov** [comment]
Yes, you're right that the events are fired in background threads. But the UnboundedChannel instance is used to collect them and hand on to the handler which works on the main thread. The events are asynchronously taken from the ChannelReader instance on the UI thread.

**Comment by h3xds1nz** [comment]
You're totally right, I realized that few minutes after writing it when I went through your repro more.

Anyways, the issue is in the subgroups map (backed by `_nameToGroupMap`) in `CollectionViewGroupInternal`, it is inconsistent, which causes the addition to fail after swift removal of the whole grouping map (which is what your example does).

**Comment by ILepekhov** [comment]
@h3xds1nz, thank you a lot!
Now I see the root of the problem. It's turned out to be a really subtle issue!
Glad, that the reason is not in WPF itself.
I really appreciate your help!

**Comment by ILepekhov** [comment]
Anyway, now it seems to me that the solution with the custom GroupDescription implementation is more complex and error-prone than that one I came up with later, where the default PropertyGroupDescription with a set of more sortable column-specific name-objects is used.

Thanks for helping!

**Comment by h3xds1nz** [comment]
No worries, you're welcome.

Yeah, your other solution is a bit more common I'd say.
