### ISSUE TITLE
I am getting an exception when using the preview 7 SDK in a WPF project using the new fluent.xaml. The pasted lines (line number 17-19 in the code) throws an exception:

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/wpf#9580]
_Originally posted by @tivik7 in https://github.com/dotnet/core/discussions/9448#discussioncomment-10344729_

I am getting an exception when using the preview 7 SDK in a WPF project using the new fluent.xaml. The pasted lines (line number 17-19 in the code) throws an exception:

            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/PresentationFramework.Fluent;component/Resources/Fluent.xaml" />
            </ResourceDictionary.MergedDictionaries>

Set property 'System.Windows.ResourceDictionary.Source' threw an exception.' Line number '82' and line position '18'.

with the inner exception:

IOException: Cannot locate resource 'resources/fluent.xaml'.

Workloads, Visual Studio Preview, NuGets and dotnet preview 7 all installed without errors.

**Comment by thurrott** [comment]
I'm seeing this error as well. x64 and Arm64 VS 2022 17.12 Preview with .NET 9 Preview 7

**Comment by ThomasGoulet73** [comment]
I think the path changed in Preview 7 and it looks like it's supposed to now be `pack://application:,,,/PresentationFramework.Fluent;component/Themes/Fluent.xaml`.

**Comment by tivik7** [comment]
> Themes

Changing from 

pack://application:,,,/PresentationFramework.Fluent;component/Resources/Fluent.xaml

to:

pack://application:,,,/PresentationFramework.Fluent;component/Themes/Fluent.xaml

resolved the exception. Thx @ThomasGoulet73

**Comment by thurrott** [comment]
> I think the path changed in Preview 7 and it looks like it's supposed to now be `pack://application:,,,/PresentationFramework.Fluent;component/Themes/Fluent.xaml`.

This is correct. Thank you!

**Comment by thurrott** [comment]
> > Themes
> 
> Changing from
> 
> pack://application:,,,/PresentationFramework.Fluent;component/Resources/Fluent.xaml
> 
> to:
> 
> pack://application:,,,/PresentationFramework.Fluent;component/Themes/Fluent.xaml
> 
> resolved the exception. Thx @ThomasGoulet73

This is correct. Thank you!

**Comment by pchaurasia14** [comment]
@ThomasGoulet73 - Thanks for the help.
I've updated the [documentation](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview4/wpf.md) as well.
