### ISSUE TITLE
When using .NET9 pre7 build and run, will throw System.Windows.Markup.XamlParseException

### ISSUE THREAD

**Issue by ssccinng** [dotnet/wpf#9582]
### Description

![image](https://github.com/user-attachments/assets/27353ae3-aaff-4a90-ad87-4e04dc505f72)

When using the above code, an error will be thrown

System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=“在“System.Windows.StaticResourceExtension”上提供值时引发了异常。”，行号为“12”，行位置为“10”。
  Source=PresentationFramework
  StackTrace:
   在 System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   在 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   在 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   在 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   在 System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   在 WpfBugTest.MainWindow.InitializeComponent() 在 D:\wcsrepo\WpfBugTest\MainWindow.xaml 中: 第 1 行

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

内部异常 1:
IndexOutOfRangeException: Index was outside the bounds of the array.

### Reproduction Steps

https://github.com/ssccinng/WpfBugTest

Run it using the latest preview version

Please note that this error does not occur when selecting net9 for the targetframework, but only when selecting net8
 <TargetFramework>net8.0-windows</TargetFramework>

### Expected behavior

not throw error

### Actual behavior

throw error

**Comment by heku** [comment]
I got same issue after upgrading my VS2022 preview to latest, my workaroud is installing .NET 8 SDK and adding a global.json to force .NET SDK to version 8.

**Comment by Taiizor** [comment]
When the project is compiled with .NET 9 Preview 7, it only runs successfully with .NET 9. Unfortunately, it encounters errors on lower versions.

**Comment by pchaurasia14** [comment]
@heku @Taiizor - Thanks for the report. 

We have a candidate fix already in place for fixing this issue - #9584

**Comment by Taiizor** [comment]
> @heku @Taiizor - Thanks for the report.
> 
> We have a candidate fix already in place for fixing this issue - #9584

So, will there be an interim release of .NET 9 to fix this, or do we need to wait until the .NET 9 RC version?

**Comment by pchaurasia14** [comment]
We are working out the logistics on this one. Currently awaiting approval from .NET. 
I'll keep this thread posted on updates.

**Comment by melytc** [comment]
My team is also being impacted by this. Commenting to get notified of any update! cc: @haileymck

**Comment by Jakedahl94** [comment]
I am having this issue after upgrading VS this week.

**Comment by singhashish-wpf** [comment]
Apologies for the inconvenience. This happened because of regression of Setter.Value ContentProperty change. 
We have reverted the changes and the changes are included in RC1 builds, this will be reflected in RC1. 
There are two workarounds for now:
- Use global.json and pin the dotnet sdk version to 8. Something like below:
```json
{
  "sdk": {
    "version": "8.0.300"
  },
}
```
- Use RC1 nightly builds - The builds which have the reverted changes included.

**Comment by AlanHauge-Interacoustics** [comment]
This also happens in .NET framework 4.8, so it might not be isolated to .NET 9

**Comment by i2van** [comment]
> This also happens in .NET framework 4.8, so it might not be isolated to .NET 9

`global.json` can be used as WA:

```
{
  "sdk": {
    "version": "8.0.107",
    "rollForward": "latestFeature"
  }
}
```

**Comment by majocha** [comment]
This is affecting Visual F# Tools extension and probably many other Visual Studio extensions using WPF as they target net472:
https://github.com/dotnet/fsharp/issues/17602

https://github.com/dotnet/fsharp/issues/17602#issuecomment-2308873352

**Comment by pfre017** [comment]
> We are working out the logistics on this one. Currently awaiting approval from .NET. I'll keep this thread posted on updates.

I have the VS 17.12.0 Preview 2 and 9.0.100-rc.1.24452.12 [C:\Program Files\dotnet\sdk], but still get the same issue? I thought this was resolved in rc1?

**Comment by singhashish-wpf** [comment]
@pfre017 I am unable to repro with the VS and dotnet versions mentioned. I am trying to repro with the sample repro mentioned in the issue description. Attached is a video. Let me know if there is something different with your setup or repro.
https://github.com/user-attachments/assets/a22c0690-5f69-4d2e-9d12-bb0fe29f6087

**Comment by AlanHauge-Interacoustics** [comment]
> @pfre017 I am unable to repro with the VS and dotnet versions mentioned. I am trying to repro with the sample repro mentioned in the issue description. Attached is a video. Let me know if there is something different with your setup or repro. https://github.com/user-attachments/assets/a22c0690-5f69-4d2e-9d12-bb0fe29f6087

I got it with a .NET framework 4.8 application

**Comment by singhashish-wpf** [comment]
> > @pfre017 I am unable to repro with the VS and dotnet versions mentioned. I am trying to repro with the sample repro mentioned in the issue description. Attached is a video. Let me know if there is something different with your setup or repro. https://github.com/user-attachments/assets/a22c0690-5f69-4d2e-9d12-bb0fe29f6087
> 
> I got it with a .NET framework 4.8 application

Could you share your repro sample?

**Comment by DaveInCaz** [comment]
Same problem here but using NET48 and VS2022 Version 17.12.0 Preview 1.0.

**Comment by pfre017** [comment]
> @pfre017 I am unable to repro with the VS and dotnet versions mentioned. I am trying to repro with the sample repro mentioned in the issue description. Attached is a video. Let me know if there is something different with your setup or repro. https://github.com/user-attachments/assets/a22c0690-5f69-4d2e-9d12-bb0fe29f6087

Thank you @singhashish-wpf. I have now got it to work. I suspect it was a my own NUGET package that was built with an old version of .net 9.0

**Comment by singhashish-wpf** [comment]
Nice @pfre017 !
Thanks for the confirmation.
