### ISSUE TITLE
Fluent2 ContextMenu Has Incorrect Key

### ISSUE THREAD

**Issue by robert-abeo** [dotnet/wpf#9626]
### Description

`ContextMenu` in the Fluent2 style has the wrong key. It should be `DefaultContextMenuStyle` (**Style** suffix).

https://github.com/dotnet/wpf/blob/6cd6fac35873f7db9bf2b3021a4df3544f6cc654/src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ContextMenu.xaml#L12

### Reproduction Steps

None, See code

### Expected behavior

`DefaultContextMenuStyle` (**Style** suffix).

### Actual behavior

```x:Key="DefaultContextMenu"```

### Other information

Please review other keys! A search in this directory for `x:Key="Default` should find all cases to review.

**Comment by siagupta0202** [comment]
Thank you @robert-abeo for bringing this issue to our attention. We have made the changes in the main branch for the same and have raised a PR for fixing this in .NET 9 RC 2
