### ISSUE TITLE
Invalid BAML generated

### ISSUE THREAD

**Issue by drolevar** [dotnet/wpf#9636]
### Description

When I build an app containing the following XAML with 9.0.0-preview.7, it's compiled into an unreadable BAML:
```xml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <Style x:Key="DefaultAccessTextStyle" TargetType="{x:Type AccessText}">
        <Setter Property="Background" Value="Transparent" />
        <Setter Property="FontSize" Value="14" />
        <Setter Property="Margin" Value="0" />
        <Setter Property="Focusable" Value="False" />
        <Setter Property="SnapsToDevicePixels" Value="True" />
        <Setter Property="OverridesDefaultStyle" Value="True" />
    </Style>

    <Style
        x:Key="{x:Type AccessText}"
        BasedOn="{StaticResource DefaultAccessTextStyle}"
        TargetType="{x:Type AccessText}" />

</ResourceDictionary>
```
![image](https://github.com/user-attachments/assets/ff65f47b-80e1-4f98-a4fe-5e59f1f9140f)

### Reproduction Steps

Build and run the attached project:

[WpfApp1.zip](https://github.com/user-attachments/files/16729526/WpfApp1.zip)

### Expected behavior

Windows is shown:

![image](https://github.com/user-attachments/assets/672dbb7c-5e2b-4268-93fb-1f61d21363d2)

### Actual behavior

Exception is thrown:

![image](https://github.com/user-attachments/assets/85f8e42e-2270-4216-bd30-8d709ae1672d)

### Regression?

This has worked with NET 8.0.

### Impact

Cannot build with .NET 9.0.0-preview.7.

**Comment by miloush** [comment]
Duplicate of #9582. Fixed in RC.

**Comment by drolevar** [comment]
@miloush Ok. Closing issue.
