### ISSUE TITLE
Is DPI broken in 3.0.100-preview6-012264?

### ISSUE THREAD

**Issue by markzielinski** [dotnet/wpf#976]
I just updated from 3.0.100-preview5-011568 to 3.0.100-preview6-012264 and it looks like there were some changes made to DPI.

I checked the release notes and didn't see any changes documented for DPI, however after updating to Preview 6 my WPF application now looks huge.    If I switch back to Preview 5, it works as expected.

My display resolution is 2560 x 1440 with the scale set to the recommended 125%.

**Comment by rladuca** [comment]
There was a period where the default DPI awareness was not being set (see #334 ).  This has been fixed now.  This is likely the difference you are seeing between Preview5 and Preview6.  The application size should also be the same as in .NET Framework 4.8.
