### ISSUE TITLE
Can we build xaml to XBF in WPF?

### ISSUE THREAD

**Issue by lindexi** [dotnet/wpf#99]
WPF should cost too many time to parse the xaml during startup. In UWP, we can build xaml to XBF that the binary representation enables performance advantages versus loading and parsing a XAML file as text.

**Comment by wjk** [comment]
WPF actually already does this, but not to XBF, strictly speaking. WPF uses BAML, which is a similar technology, but not the same file format as UWP's XBF.

**Comment by lindexi** [comment]
In WPF, it is compiled into a format known as Binary Application Markup Language (BAML). In Windows Store and universal apps, it is compiled into a format known simply as XAML Binary Format (XBF).

**Comment by rrelyea** [comment]
When presentationbuildtasks.dll and presentationframework.dll projects get added to this repo, take a look at the baml writing and baml reading code...and consider improvements.
I am not deeply familiar with advances that xbf made over baml, but their could be some?

**Comment by georgethejournalist** [comment]
According to [some performance tips from MS](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/optimize-xaml-loading#use-xbf2) targeting XBF2 (which is a new version of XBF) 'reduces the disk footprint of a XAML file' (over XBF1) and also 'improves the heap and object creation costs'. So there's those benefits at least.
