### ISSUE TITLE
Linking dll files in WPF solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#9919]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Linking-dll-files-in-WPF-solution/10756819)._

---
Hi,
I have a Visual Studio 2022 solution file (that will be compiled as a .dll) which is making references to 4  C# projects.
Right now, when I build my solution, I’m generating 5 .dll. And I want to generate only one.
Is there a way to do this in Visual Studio without using ILMerge or ILRepack?

---
#### Feedback Bot on 10/4/2024, 09:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by batzen** [comment]
That's possible by publishing as SingleFile, isn't it?

**Comment by disla-vestas** [comment]
Hi, thanks for your replies.
ILMerge was not a problem, I was just trying to understand if a built-in solution was available. 
I think that this issue can be closed.
